vanilla/vanilla

library/core/class.applicationmanager.php
Update locale refreshing on application manager to wait until the application is actually enabled.
=> Update locale refreshing for applications. `$Locale` is not superfluous.

library/database/class.database.php
As it was, the Structure doesn't initialize with the correct database
and even sets the wrong prefix incorrectly.  This meant that the
standard database may have been initialized unnecessarily as well.
This patch passes the database object as an argument to the constructor.
=> Pass $Database into Structure when creating it inside a Database object

library/database/class.mysqlstructure.php
Mark columns as explicitly null when they are marked as such in the structure
Per the MySQL column definition this is perfectly fine:
```
column_definition:
data_type [NOT NULL | NULL] [DEFAULT default_value]
[AUTO_INCREMENT] [UNIQUE [KEY] | [PRIMARY] KEY]
[COMMENT 'string']
[COLUMN_FORMAT {FIXED|DYNAMIC|DEFAULT}]
[STORAGE {DISK|MEMORY|DEFAULT}]
[reference_definition]
```
=> be explicit over nullable fields in GDN_MySQLStructure

library/core/class.request.php
Depending on the source used to fill it the 'Host' environment variable, it may already contain the port. This change makes sure the port is added only if not already present, since otherwise Gdn_Request::Url could return Host:port:port in those scenarios.
I've spent two hours trying to figure out why my local installation on port 86 was failing with a blank screen; eventually I figured out it wasn't my nginx configuration what was failing but vanilla itself, as it tried to redirect to host:86:86/index.php?p=/dashboard/setup upon accessing index.php.
=> Updated class.request.php to support non-standard ports

applications/dashboard/settings/class.hooks.php
There is currently no way to make proper POST api calls because our CSRF checks kick in. This change will validate CSRF checks making a call against a .json endpoint with a valid SSO string (?sso=).
=> Relax CSRF checks on api calls made with an SSO string.

applications/vanilla/settings/stub.php
If you have a community where guests can view any discussions then a utility/update will continuously add the initial stub discussion.
=> Fix bug where too many stub discussions are created.

applications/dashboard/views/user/users.php
Event UserCell was misbehaving because the current user has never been passed as the EventArgument
Backport to 2.1
=> Correct typo in function call "EventArgs" instead of "EventArguments"

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/settings/class.hooks.php, applications/dashboard/settings/structure.php
Make mass banning an admin permission and add some additional tracking information to the ban table. Note that the additional information on the ban table will take effect after a structure update, but will still work without it.
=> Escalate the permissions required for mass banning.

applications/dashboard/models/class.rolemodel.php
See https://github.com/vanilla/vanilla/issues/2385  
If a role should be deleted and not replaced, all entries in UserRole for that role should also be deleted so that it couldn't happen that users will be assigned to a newly created role just because of relicts in table UserRole
=> Clear deleted roles from table UserRole

plugins/Tagging/class.tagging.plugin.php, plugins/Tagging/class.tagmodel.php
This is #1897 re-targeted against master.
Closes #1896.
When deleting spammers, I found my tag counts would be messed up if they
used any tags. This fixes that.
=>  Add dba/counts handler to the core tagging plugin

library/core/class.format.php
Emulate %l and %e for Windows like in Gdn_Format::Date();
fixes #2027
=> DateFull windows compatibility

applications/dashboard/models/class.usermodel.php
There are checks in some of the `ProfileController` methods for whether or not a user’s photo is a url or not. These needed to be updated to the now standardized `IsUrl()`. Without this the activity feed renders incorrect photo change activities and some user API calls will have incorrect photo urls.
=> Fix url checks for profile photos.

applications/vanilla/views/discussion/helper_functions.php
Backport of that merged pull request: https://github.com/vanilla/vanilla/commit/0321c0551fb2ead494bbef0b4126a29b9c4880f5
Added class names to options menu of a single discussion
=> Backport Classname for Discussion Options

applications/vanilla/controllers/class.postcontroller.php
When a user POSTs to /post/comment, but has a bad CSRF token then right now that endpoint silently fails or throws a blank server error in some cases (such as the API). This change throws a noisier error to aid with troubleshooting.
=> Throw a bad CSRF error on postback for comment posts.

applications/conversations/views/messages/messages.php
Dates in conversations were missing the <code>< time ></code> element.
=> Render HTML date in conversations

applications/vanilla/models/class.discussionmodel.php
GetUnread only showed discussions with unread comments.This fix includes unread discussions without any comments.   
This PR replaces https://github.com/vanilla/vanilla/pull/1881
=> Fix for GetUnread to include unread discussions without comments

plugins/Emotify/class.emotify.plugin.php
Since Emoji are rendered through vanilla before Emotify comes in, a
number of smilies are broken.
This removes  the EmojiSet and the Emoji autocomplete list for the time
Emotify is enabled.
=> Emotify: Surpress Emoji rendering and autocomplete

bootstrap.php
The goal here is to protect against a common problem: the .ini files in the `cache` folder get messed up for whatever reason during an upgrade and it completely baffles the user with an error like "Fatal error: Class 'Gdn' not found".
Examples: http://vanillaforums.org/search?adv=&search=%22Fatal+error%3A+Class+%27Gdn%27+not+found%22&title=&author=&cat=all&tags=&discussion_d=1&discussion_question=1&comment_c=1&comment_answer=1&page_p=1&within=1+day&date=
This is the most straightforward way I could see of making this an easy issue to sidestep for our open source users, but I'm not sure it's the best solution. Suggestions welcome.
=> Give better feedback if ini files are busted

js/global.js, js/library/jquery.atwho.js
- Options in the <code>@mention</code> flyout can now be selected with a mouseclick.
This was already the librarys default, but "overridden" by the
display_timeout setting of 0 in global.js.
(The inputs blur event is triggered before the click event, closing the flyout before anything
can be selected. This is the reason for the timeout being there.)
- The tab key no longer closes the flyout, but moves to the next item.
This required 2 minimal changes in the library.
Fixes https://github.com/vanilla/vanilla/issues/2201
=> Adds click-to-complete mentions

applications/vanilla/models/class.discussionmodel.php
Currently, there is no way of fixing a user's discussion count if its off, except by deleting a discussion which just may not happen. This pr will always recalculate a user's discussion count if it's less than 100, but increment if it's higher.
=> Fully recalculate a user’s discussion count when its low, but increment when it is high.

library/database/class.sqldriver.php
class constants need to be accessed with self:: inside of the class
=> Fix use of MAX_SIGNED_INT constant

applications/vanilla/views/settings/addcategory.php
* Use same itemwrap for _PermissionFields as editcategory
* Fixes broken `li` nesting that caused permission block to now show/hide together
=> Fix addcategory view's _PermissionFields markup

library/core/class.format.php, library/core/functions.general.php, plugins/ProfileExtender/class.profileextender.plugin.php
Replaces #2377
* Adds `Gdn_Format::HtmlFilter()` as non-magic HTML parsing.
* Add `IsHtml()` convenience function.
* Fixes Profile Extender automatically magic-parsing its field values, which is bad on profiles.
=> Allow non-magic HTML parsing & fix it in Profile Extender fields

library/core/class.form.php
I'm creating a plugin that allows the user to choose the format (HTML or Markdown) of each of their individual posts.
Prior to [this commit](https://github.com/vanilla/vanilla/commit/e2b1f69393d0fe54ff7790b9957fe8402329e9bb#diff-bcdcd95ad070ab8428b1b3eb3e2353cbL150), `BeforeBodyBox`'s `BodyBox` parameter contained HTML for the textbox and the hidden `Format` input. My plugin would rewrite this string to remove the hidden input.
After that commit, `BeforeBodyBox` does not receive the hidden input in the `BodyBox` parameter - it's always `<div class="bodybox-wrap">`, which is pretty pointless.
This PR restores the old behaviour (the current behaviour in 2.1.x). It additionally makes it easier than in 2.1 for `BeforeBodyBox` to change `BodyBox`: it no longer needs to modify the passed string …
=> Let BeforeBodyBox change the BodyBox again

applications/dashboard/design/style.css
style.css has this:
```css
.TextBoxWrapper textarea,
.TextBoxWrapper input {
width: 100%;
display: block;
}
```
I have a plugin that adds a post format chooser to the activity form and this CSS makes my radio buttons show up weird. I can always re-override, but hey, let's have sensible defaults. This PR makes that block not apply to radios or checkboxes. Tested with 2.1.6.
=> Don't restyle radios and checkboxes in TextBoxWrapper

applications/dashboard/views/home/updatemode.php, applications/dashboard/views/modules/me.php, js/global.js
When notifications are clicked in the MeModule, the `Alert` sticks around even tho they have been cleared on the backend. This adds an instant-clearing mechanism in the UI using generic class names we can use elsewhere to accomplish the same effect anywhere we access notifications or display its count.
=> Clear notifications immediately

applications/vanilla/models/class.discussionmodel.php
Since `DiscussionModel->GetID()` can only return an object currently, specifying an array is wrong and just a land mine of a regression bug waiting to happen.
=> Fix typos in calls to DiscussionModel->GetID().

library/core/class.form.php
Class Forms function Checkbox() already translates the parameter Label: https://github.com/vanilla/vanilla/blob/master/library/core/class.form.php#L394-407   
So it doesn't have to be used when passing a label.
=> Removed unneeded call to T() function

applications/dashboard/views/profile/helper_functions.php
- Change thru to through. http://grammarist.com/spelling/through-thru/
- Don’t talk about site config to users that potentially aren’t
concerned with administration.
=> Fix the wording of unverified user tooltip.

applications/dashboard/modules/class.profileoptionsmodule.php
If a user doesn't have profile editing permission, the MeModule falls back to a "Preferences" link. The profile should do the same.
=> Profile editing: fallback to Preferences to match MeModule behavior

library/core/class.uploadimage.php
As per http://vanillaforums.org/discussion/28683/images-are-rotated-when-resized , added rotation of image files if EXIF rotation tags are present.
=> Fix rotation issue with iPhone uploads

applications/vanilla/modules/class.promotedcontentmodule.php, applications/vanilla/views/modules/helper_functions.php
**Fix `SelectByScore`:** As currently coded, the top-scoring posts will get stuck in the PromotedContent module forever by all-time top scoring. We really just want the freshest content that passed our threshold. Also, the `where` clause was getting double-added.
**Add `SelectByPromoted`:** Add integration with Reactions since it is coming to core anyway.
**Fix conventions & errors**: There were several naming & syntax contention errors preventing the above from working correctly.
=> Promoted Content module fixes and improvements

library/core/class.autoloader.php, library/core/class.configuration.php, library/core/class.pluginmanager.php, library/core/class.thememanager.php, library/core/functions.error.php, library/core/functions.general.php
I was working on an experimental change to our error reporting and noticed a tonne of strict errors in our app which gives me OCD twitches.
EDIT: This PR also includes some changes to the way we error report so it may need a bit more of a go-through although I think the risk is fairly low(ish). Since the changes are fairly significant I'll try and explain them here.
- Don't use a separate error reporting level for debug mode. Debug mode will trace errors that are beneath the error reporting level and display the detailed error page on more severe errors.
-  `display_errors` is never turned on anymore. It's not needed and is a security vulnerability.
- Don't do anything with `E_STRICT` errors.
- Don't trace @ suppressed errors.
- Remove the backtrace from errors that are below the error …
=> Improve error reporting and fix PHP strict errors.

applications/dashboard/modules/class.pagermodule.php, applications/vanilla/controllers/class.discussionscontroller.php
* Setting `_PagerUrl` had no effect on `DiscussionsController->Index()`
* The Pager's `Url` option was ignored after page 1.
=> Fix PagerUrl to allow hooking & setting

applications/dashboard/controllers/class.dbacontroller.php
We do imports that only set `Sort` & `ParentCategoryID`, and/or sometimes need to do manual manipulations of the category table. This lets us rebuild the tree on the fly.
=> Add dba/fixtree for categories after import/manipulation

library/core/class.controller.php
The regex was never working right, because it doesn't match the start character of the string.
JSON keys can be arbitrary strings, so there is no need for this restriction.
=> Remove (defect) definition restrictions

applications/dashboard/controllers/class.usercontroller.php
UserControllers function _GetFilter() uses the field name "DateLastVisit" which doesn't exist. The field is called "DateLastActive".
Using `/dashboard/user?Keywords=&Go=Go&Filter=DateLastActive = 2015-01-23 11:46:40` wouldn't work because the filter field "DateLastActive" doesn't exist and therefore the filter is ignored. `/dashboard/user?Keywords=&Go=Go&Filter=DateLastVisit = 2015-01-23 11:46:40` breaks the request because you get a `WHERE user.DateLastVisit..." sql and that column doesn't exist.
But to be honest: I have no clue what this means in practice. You have to use it like that `/dashboard/user?Keywords=&Go=Go&Filter=DateLastActive = 2015-01-23 11:46:40` in order to get results and who wants to filter any date field by such an exact time (hours, minutes and seconds are needed)? …
=> Correct typo: "DateLastVisit" should be "DateLastActive"

applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/views/settings/managecategories.php
This change happened because hitting the manage categories page always throws a csrf error. Rather than just patching it I decided to make the toggle a proper postback which is better and also fixes the csrf error.
=> Put the enable/disable category use on a proper authenticated post back endpoint.

library/core/class.dispatcher.php
Pockets are currently triggered when looking at a Category RSS feed because it hits the `GdnDispatcherControllerFoundException` in the Dispatcher with a `DeliveryType` of `false`, which then overrides the `DeliveryType` to `XHTML`. When we detect the `OutputFormat()` earlier and find a syndication type result, also set the correct DeliveryType so that doesn't happen.
xdebug ![](http://icrontic.com/images/linc/dance.gif)
=> Set RSS DelveryType when we detect a feed format

applications/dashboard/controllers/class.activitycontroller.php, applications/dashboard/models/class.activitymodel.php, applications/dashboard/views/activity/helper_functions.php
- Send a wall comment notification when someone comments on a wall post.
- Wall posts and status updates now bump when comments are added.
- Fix the notifications view for wall comment and post notifications.
This PR will resolve #1663.
=> Send notifications on wall comments and other goodies.

library/core/class.theme.php, library/core/functions.render.php
Function `Img()` uses function [`Attribute()`](https://github.com/vanilla/vanilla/blob/master/library/core/functions.render.php#L560) 
to transform the attributes array to html and [that function uses htmlspecialchars](https://github.com/vanilla/vanilla/blob/master/library/core/functions.general.php#L445)  for each value. So it is not needed to use htmlspecialchars already in the function call.
=> Strip out unnecessary call to htmlspecialchars

plugins/GooglePlus/class.googleplus.plugin.php
The config option ``Plugins.GooglePlus.SocialReactions`` wasn't respected by the plugin
=> Don't show react button if social reactions are turned off

applications/dashboard/views/search/results.php
`$this->Data('SearchTerm')` is already sanitized in controller with `$this->SetData('SearchTerm', Gdn_Format::Text($Search), TRUE);` so `htmlspecialchars()` mustn't be called in the output (again)
=> Fix HTML special char bug

applications/dashboard/models/class.rolemodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/models/class.draftmodel.php, library/core/class.configurationmodel.php, library/core/class.model.php, library/core/class.validation.php, library/core/functions.validation.php, plugins/Tagging/class.tagging.plugin.php, plugins/Tagging/class.tagmodel.php
The GDN_Validation object has some severe edge cases and this aims to deal with them.
- Remove a bunch of properties that can be calculated from other properties.
- Make `Gdn_Validation->Validate()` a bit more idempotent.
- Separate rules applied manually from those applied from the schema so that the schema does not pollute the validation object during `Validate()`.
- Protect methods that really shouldn’t be called externally.
- Remove some dangerous methods.
- Allow columns with default values to be left out during inserts.
- Add a ResetOnValidate property to Gdn_Validation to allow the validation results to reset whenever `Validate()` is called.
- Change the way auto-increment fields are validated.
- Allow empty strings to validate as required if the default field value is an empty …
=> Refactor the validation object.

library/core/class.format.php
The /e modifier is deprecated and will end up being removed before we know it. This change accomplishes what the /e modifier accomplished with `preg_replace_callback()`.
=> Remove the /e modifier from Gdn_Format::HtmlFilter().

applications/dashboard/design/style.css
Unlike Chrome, FireFox doesn't force wrapping of long lines inside code blocks with white-space:pre so such lines break the site layout.
=> Wrap inline CODE tags in FireFox

applications/vanilla/views/post/discussion.php
See that question http://vanillaforums.org/discussion/29331/new-discussion-blank-category-available-as-option-but-isnt-selected-by-default 
I think it is just a matter of taste if you would like to see a blank line when user hasn't chosen any category yet or you see the "Select a category" text.
But the blank line cannot be chosen/has to be changed (post would be done to root category) and this is not obvious to users. So I'd say it's a better UX if user is informed that he has a todo here.
Btw: I've also replaced `GetValue` with `val` but I don't think that's of big interest. And I was tempted to replace it with $this->Category->CategoryID, but I didn't want to change to much...
=> Use "Select a category" in new discussion forms CategoryDropDown

applications/conversations/views/messages/add.php, applications/conversations/views/messages/addmessage.php, applications/vanilla/views/post/comment.php, applications/vanilla/views/post/discussion.php, applications/vanilla/views/post/editcomment.php, plugins/editor/class.editor.plugin.php
File upload in the advanced editor is on by default. This PR makes that functionality opt-in. Signatures and Activity forms use BodyBox, but should not have file upload functionality.
=> Make BodyBox accept a param indicating whether file upload is allowed.

applications/dashboard/controllers/class.profilecontroller.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php
Adds GetByUser events for filtering out troll content on their own profiles. Adds a 'UserLoaded' event to ProfileController to intercept userdata before logic is done on it.
=> Add events for TrollManagement fixes

applications/dashboard/models/class.usermodel.php
Fixes #2005.
- `AllIPAddresses` is now a list of the most recently used IP addresses rather than being "all".
- This list is now sorted from least recently used to most recently used rather than sorted alphanumerically.
- If a new IP address brings the list over the size of the column (currently 100 characters), least recently used IP address(es) will be dropped until it's back within the limit.
Note that 100 characters is enough room for between 6 and 14 IP addresses.
**Test 1 - a new IP address brings you over the limit**
- Update your user to have a nearly full IP address list: `update GDN_User SET AllIPAddresses = '123.123.123.109,123.123.123.107,123.123.123.105,123.123.123.103,123.123.123.101,123.123.123.100' where UserId = YOURUSERID;`
- Log out
- Log in
Expected result: no error, …
=> Use as many recently used IP addresses in AllIPAddresses that will fit

library/core/class.form.php
This prevents the option from appearing as an attribute in the select tag when using the CategoryDropdown with custom data:
categorydata="Array"
=> Add CategoryData as reserved attribute

library/vendors/SmartyPlugins/function.pocket.php
Depending on the smarty instance in pockets is not good functionality because then the pockets can only be called from within smarty.
=> Revert "Smarty pocket: Add Sender param."

applications/vanilla/controllers/class.discussionscontroller.php, applications/vanilla/modules/class.promotedcontentmodule.php, applications/vanilla/views/discussions/promoted.php, applications/vanilla/views/modules/helper_functions.php, applications/vanilla/views/modules/promotedcontent.php, library/core/class.controller.php
* Add `Promoted` endpoint on `DiscussionsController` to access `PromotedContentModule`.
* Filter additional user info from API calls that should be PersonalInfo by default. It would otherwise be exposed by this endpoint.
* Refactor PromotedContentModule to allow controller access  via `Load` & `Validate` methods.
* Make the `SelectBy*` methods all work the same if only `selection` value is passed as `$Parameters`.
* Fix array index issue in `Prepare`.
* Fix passing ID array in `SelectByCategory`.
* Fix misc coding standards & docs throughout `PromotedContentModule`.
* Fix caching of multiple RoleIDs in selection (array to string conversion error).
* Allow Ranks & Categories to be selected by Name.
* Remove date keying of `Content` array.
=> Create an endpoint for accessing promoted content

applications/dashboard/models/class.usermodel.php
This chooses the best available store for rate limiting:
Gdn_Cache > APC store > Database (User attributes)
I have tested the APC and UserModel store variant. The Gdn_Cache implementation hasn't changed.
New pull for #2346 with a cleaner changeset
=> Rate limit logins on installs without a cache

plugins/Quotes/class.quotes.plugin.php
Plugin uses classes, so the config settings aren't needed.
=> Remove unused config settings

library/core/functions.general.php
There are arrays initialized but never used in the complete functions. I simply deleted them.
=> Strip unused variables from GetMentions() and ReflectArgs()

library/core/class.format.php, library/core/functions.error.php, library/core/functions.general.php, library/core/functions.render.php, plugins/Debugger/views/debug.php
htmlspecialchars uses a mixture of `C('Garden.Charset', '')`, `C('Garden.Charset', 'UTF-8')`, `UTF-8` and no charset info at all. I've harmonized all that uses any charset parameter to respect config setting and default to UTF-8 (`C('Garden.Charset', 'UTF-8')`)
=> Harmonize charset (where used) in htmlspecialchars

index.php, js/global.js, library/core/class.format.php
* Fix hyphens being disallowed in YouTube URLs (regression).
* Fix support for start times via `#t=1` anchors (regression).
* Unify pattern matching in JS to match PHP.
* Use a `data-youtube` param instead of `id` to prevent conflicts & attribute rule breaking.
* Give a useful console log error by providing the bad videoid parsed.
* Adds more example cases for YouTube testing.
* Cleanup some comments & increment version to cache bust.
=> YouTube embed fixes: start time, hyphens, data-youtube

applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/views/discussion/helper_functions.php, applications/vanilla/views/discussions/helper_functions.php
Moves the more complex logic of discussion edit permissions into a single place to reduce inconsistency errors.
=> Provide a helper function for determining if a discussion can be edited.

applications/vanilla/models/class.categorymodel.php
The recent posts don't need to get joined every time the categories are queried.
This change just joins the recent posts when necessary.
=> Don’t always join recent posts.

applications/dashboard/models/class.usermodel.php, library/core/class.dirtycache.php
The user model stores null users when a user does not exist so that it isn’t queried again and again. The dirty cache does not properly handle this leading to some cases of the user getting queried too many times on a page.
=> Allow the dirty cache to store null values.

index.php
Fast-forward master version to 2.2.100 so that open source release can occupy 2.2.x.
=> Abandon the 2.2 namespace and never look back

applications/vanilla/models/class.discussionmodel.php
GetMentions was called for discussion body and for discussion title and then the result arrays were merged.
Simplified that to one call to GetMentions() with title _and_ body as arguments.
=> Eliminate one GetMentions() call

applications/conversations/settings/structure.php
Expand GDN_Conversation.Subject column to 255 characters from 100 characters.
Groups currently sends an invitation that uses the field. The German translation apparently exceeds the threshold. Reasonable size increase and a fairly conservative database change to make.
=> Fix too-short private message subject allowance

library/core/class.format.php, plugins/ProfileExtender/class.profileextender.plugin.php
* There is a bug in `strtotime` on 64-bit systems that returns the negative integer limit for `0000-00-00 00:00:00` so that case should never be allowed.
* A non-existent birthday should never get displayed.
* If you were actually born at the moment of the Unix epoch, your life is cursed and should not be celebrated.
=> Fix zeroed birthdays & zeroed timestamps

applications/dashboard/controllers/class.rolecontroller.php, applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/models/class.permissionmodel.php, applications/dashboard/models/class.rolemodel.php, applications/dashboard/settings/class.hooks.php, applications/dashboard/settings/structure.php, applications/dashboard/views/role/index.php, applications/dashboard/views/user/index.php
- Define a set of ranking permissions. This means that users can only assign roles/permissions if they
have those ranking permissions.
- Administrators can assign any role.
- Community managers with the edit users permission can assign roles that they have ranking permission of.
- Other users with the edit users permission can assign roles without any ranking permission.
- Add a hidden Garden.Roles.Manage permission that can be defined in plugins that will allow non admins to add and edit roles.
=> Allow users without admin access to assign roles and edit permissions.

applications/vanilla/models/class.commentmodel.php
The comment page cache was implemented because of a single rather grotesque example of too many comments per discussion.
This functionality is prone to glitches and probably isn't required anymore.
There are several reasons why we think this isn't necessary anymore.
1. After the caching was implemented we discovered a way to optimize the comment queries on their own.
2. The community with the massive number of comments per discussion has had the comment cache turned off with no issues.
This PR turns off the comment cache by default as a "just in case" measure. If we don't have any issues then another PR will remove the code altogether.
=> Turn the comment page cache off by default.

applications/dashboard/controllers/class.activitycontroller.php, applications/dashboard/models/class.activitymodel.php, applications/dashboard/views/activity/helper_functions.php
Users with the Garden.Profiles.Edit permission will now be able to delete any activity on their own wall.
Also:
Add function to check whether a user has permission to delete.
Revoke ability for users to delete their own posts on other users' walls.
=> Profile activity: Allow users to curate the activity on their own wall.

plugins/OpenID/class.openid.plugin.php
Make sure the authentication url that a user enters is http or https. Deals with a potential SSRF attack vector.
=> Validate the scheme on OpenID’s identity.

applications/dashboard/controllers/class.settingscontroller.php
Mobile theme options aren't working, as there is no view. This simply uses the `themeoptions` view to display mobile theme options.
=> Mobile theme options: Render a view

applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/views/settings/advanced.php, applications/vanilla/views/settings/floodcontrol.php
Moved min/max comment length to advanced section, instead of flood
control.
=> #2456 min/max comment length to advanced

plugins/Quotes/class.quotes.plugin.php
Fixes bug where Emoji get double-parsed when quoted post is a different input formatter.
To test, make a post with BBCode format containing Emoji. Switch to Html and quote the post. Without this patch, you'll get broken Emoji HTML in the post.
=> Quotes: disable Emoji parse for FormatQuote

applications/vanilla/controllers/class.moderationcontroller.php
Current behavior is that `Garden.ForceInputFormatter` with a `Garden.InputFormatter` of something other than `Html` will break the redirect move feature. This sets our InputFormatter to Html for a hot second to sidestep the problem.
=> Moved discussions conflict with a forced inputformat

applications/dashboard/models/class.rolemodel.php
RoleModel::GetApplicantCount was potentially returning a non-zero value for the total number of applicants awaiting approval, even if the registration was not set to "Approval".  This fix skips the count and returns zero from RoleModel::GetApplicantCount if registration mode isn't explicitly set to "Approval".
Fixes #2036
=> Return zero applicants when registration type not Approval

library/core/class.format.php
Fixes bug where hashes with a html tag directly after the hashtag string do not pass the regex. NBBC transforms a new line to a <br /> tag, so hashtags at the end of a line were not being processed correctly.
=> Add '<' to list of ending chars in hashtag regex.

applications/dashboard/models/class.importmodel.php
When importing a file, ImportModel wasn't checking to see if the file was readable before it attempted to open it.  If the read permission wasn't granted to the user or group PHP was running under, it would throw an error informing the user that the file was in the wrong format, because attempting to read the file would fail when validating the file's header.  This fix implements a check before the import and alerts the user they need to verify permissions on the import file.
Fixes #2674
Also removing tabs from class.importmodel.php.
=> Checking if source file is readable before import

applications/dashboard/settings/structure.php
Some of our column lengths are unnecessarily long. This causes problems when they are indexed and they then break utf8mb4 (the emoji encoding).
=> Reduce some column lengths.

library/core/class.controller.php, library/core/class.dispatcher.php
An internal method is a method that is public, but should not be dispatched to. It’s a method to be used by plugins and the framework, but not accessed from a url.
=> Add support for internal controller methods.

plugins/ProfileExtender/class.profileextender.plugin.php
The Profile Extender plug-in was displaying custom fields for users, even after they were banned.  This fix bails out of displaying those fields if the user is flagged as banned.
Fixes #1667
=> ProfileExtender: Do not display fields for banned users

applications/dashboard/models/class.usermodel.php
Profile Extender was allowing empty values to be set for user meta values.  These created empty user meta rows in the database and it was also reported that this sometimes caused empty fields to be displayed on the user's profile.  This fix updates the check when saving user meta to also account for empty strings when deleting, not just a nulls.
Fixes #1619
=> Adding removal of empty UserMeta rows where value set is empty string

library/core/class.format.php
The non-unicode fallback in Gdn_Format::Url was using invalid regex.  This fix updates the regex to replace any non-alphanumeric characters and underscores.
Fixes #2017
=> Updating non-unicode fallback regex in Gdn_Format::Url

library/database/class.sqldriver.php
Dashes are not eliminated by NamedParameter() so that a column name with a dash could cause a PDO error. See here: http://vanillaforums.org/discussion/29710/view-permissions-not-working#latest
Dashes are nor allowed in named parameters, only alphanumerics and underscores: 
https://github.com/php/php-src/blob/master/ext/pdo/pdo_sql_parser.re#L49
=> NamedParameter() didn't eliminate dashes

plugins/ButtonBar/class.buttonbar.plugin.php, plugins/ButtonBar/js/buttonbar.js
If you happened to have InputFormatter configured to Wysiwyg, probably after using Advanced Editor, the Button Bar plug-in would not display.  This fix adds support for the Wysiwyg format by having ButtonBar treat it as Html.
Fixes #2517 
Also some IDE-assisted whitespace fixes to class.buttonbar.plugin.php and buttonbar.js
=> ButtonBar: Adding support for Wysiwyg input format

library/core/class.form.php, plugins/editor/class.editor.plugin.php
* Allow BeforeBodyBox to once again change Format, `$Column`, and `$Attributes`.
* Allow for intent of #2089 by adding Format opt-out EventArg.
=> Editor: Revert #2089 and allow Format opt-out separately

applications/dashboard/controllers/class.embedcontroller.php, applications/dashboard/controllers/class.entrycontroller.php, library/core/functions.general.php
* Stores Garden.TrustedDomain as a string rather than an array.
* Preserves backwards compatibility with stored arrays.
* Better input cleanup.
/embed/settings is currently broken on cloud, possibly due to our config override resetting the schema and disallowing arrays.
=> Garden.TrustedDomain should be formatted as a string in config

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/locale/en-CA/definitions.php, applications/dashboard/models/class.banmodel.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/modules/class.profileoptionsmodule.php, applications/dashboard/modules/class.userbanmodule.php, applications/dashboard/views/modules/userban.php, applications/dashboard/views/profile/user.php, applications/dashboard/views/user/unban.php
Currently, there is no way to know the difference between a  user being banned manually and then by IP address. This can cause issue where users get blanked banned/unbanned when they aren't supposed to. This feature adds the following.
* Adds a bit mask to the banned flag to keep track of the various ways users get banned.
* Allows CMs to manually ban/unban users that have been caught by an IP ban, but keep that IP ban in effect.
* Adds some hooks for future bans by warnings and temporary banning.
=> Differentiate the ways users can be banned.

applications/vanilla/models/class.commentmodel.php
The issue is caused when memcached is enabled. The logic was looking at a property erroneously and that check was removed.
=> Fix bug where comments don’t update the latest post on categories.

plugins/HtmLawed/class.htmlawed.plugin.php
This does a global filter of the `class` attribute on all HTML elements, then re-allows a whiltelist of values of `class` for a whitelist of elements.
Whitelisted values for `class`:
Quote|Spoiler|CodeBlock|Spoiled|P|ImageResized|AuthorAction|MeAction, plus Align* and post-* (This last one is Editor's class prefix, which would be how plugin authors can sidestep this restriction going forward.
Elements allowed to have these `class` values: a,span,div,p,li,i,b,strong,em,code,blockquote,dd,dt,img,pre,h1,h2,h3,h4,h5,h6,s,del,sup,sub,q,small,cite,ins
=> Change class filter on user generated content to a whitelist

applications/dashboard/settings/class.hooks.php
Lithe uses the SiteNavModule to display its links. This fixes a bug where the Activity menu item shows up on Lithe whether a user has permission or not.
=> Only show Activity link to those with Garden.Activity.View permission

applications/dashboard/models/class.permissionmodel.php
If there are no entries for a role in `GDN_Permission` then editing that role shows default permissions. This is misleading because that role really has no permissions. This fix makes the role show no permission so that admins know to fix the role.
This is an issue that usually won’t occur unless the data is incorrect from something like an import.
=> Don’t show misleading permissions when editing a role without any permissions.

applications/vanilla/models/class.categorymodel.php
Fix an issue where depths are not properly adjusted when calling `CategoryModel::MakeTree()` without specifying a root.
=> Fix issue with CategoryModel::MakeTree().

applications/dashboard/locale/en-CA/definitions.php, library/core/class.validation.php, library/core/functions.validation.php, plugins/OpenID/class.openid.plugin.php, plugins/OpenID/views/url.php
Prevent users from using OpenID to examine non-standard urls.
=> Add some more error checking to OpenID urls before discovery.

plugins/Tagging/class.tagmodule.php
Fix an issue where tags are getting double url’d in the popular tags module.
=> Fix tag URLs when in a subdirectory.

js/global.js
Change proposed here: http://vanillaforums.org/discussion/29836/possible-bug-in-core-global-js#latest
`this` is not in the proper context when the `complete` method is called. `$elem` should be used to reference the element that initiated the $.ajax request.
=> global.js context bug: change `this` to `$elem`

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/settings/structure.php
The Garden.SSO.SyncRoleBehavior can be set to “register” so that roles will only synchronize when registering and not on subsequent sign ins.
=> Add a config setting to only sync roles on register and fix the sync roles config spelling mistake.

applications/dashboard/controllers/class.notificationscontroller.php
Excerpt was being formatted as Display, which was displaying encoded HTML.  This was specifically an issue with conversation messages, because formatting and image markup was being displayed in a way that made it difficult to see the content of the original message.
=> Formatting Inform Messages excerpt as PlainText

library/core/class.emoji.php, library/core/class.format.php
This PR defines a new function - `Gdn_Format::ReplaceButProtectCodeBlocks`. This function works like `preg_replace` and `preg_replace_callback`, but avoids doing any replacements inside `<code>` tags. The function accepts four parameters: the first three are the same as `preg_replace` and `preg_replace_callback`, the fourth controls whether it acts like `preg_replace` (default/`FALSE`) or `preg_replace_callback` (`TRUE`).
Internally, `Gdn_Format::ReplaceButProtectCodeBlocks` replaces `<code>` tags and their contents with placeholders, does the requested replace, then puts the `<code>` tags back.
This PR changes the `@mention`, `#hashtagsearch`, and `/me does something` code to use this new function. I believe `/me` only runs if it's at the start of the comment, but I've included it for …
=> Don't do mentions, hashtag searches, emoji, or links inside <code>

library/core/class.request.php
This will make sure that only http urls are returned when SSL is forbidden.
Please note that although this is a small change it does risk breaking backwards compatibility and caching scenarios. It needs to be tested in various scenarios. On sites with a custom domain. Make sure it doesn’t break accessing the *.vanillaforums.com version.
=> Don’t allow https urls when Garden.AllowSSL is false.

applications/vanilla/views/discussions/table_functions.php
The event BeforeDiscussionName has been commented out in table view without any obvious reason. Since Linc called that a bug (https://github.com/vanilla/vanilla/issues/2375) I've simply included it again.
=> Uncomment FireEvent('BeforeDiscussionName')

applications/vanilla/views/discussions/table_functions.php
https://github.com/vanilla/vanilla/pull/2758
Maybe there will be another Vanilla 2.1 release and this one is so easy to fix that there is no reason to not do it.
=> "Backport" Uncomment FireEvent('BeforeDiscussionName')

library/core/class.autoloader.php
I found out where the actual fix were so I change only on that to implement the fix per @tburry feedback to get a clean PR.
=> Fix parse_ini_file for running from a Windows network share

applications/dashboard/settings/structure.php, library/core/class.locale.php
This will fix sites that have “en-CA”, changing
them to “en”. In the future the “en-CA” kludge
may be removed.
=> Make sure the config locale is canonicalized

library/core/functions.validation.php
Vanilla requires PHP 5.2 and since this PHP version, there is a native validation function: http://php.net/manual/en/function.filter-var.php
Changes I've made:
ValidateRegex: about 20% faster
ValidateEmail: speed increase not measured, but current implementation calls external class which checks if filter_var() is valid function and uses it afterwards. So basically the previously done "external" check is now done inside of the function. The ValidateRequired check has not been passed the $Field parameter.
ValidateInteger: more than 35% faster for number in quotes, slightly slower (4%) for float, slightly faster for other values
Changes I have not made:
ValidateNoLinks: `return (filter_var($Value, FILTER_VALIDATE_URL) === false);` would have done the job but it is slower than the current …
=> Use PHP 5.2 function filter_var() for validations

plugins/Tagging/js/tagadmin.js
Addresses an issue where adding a new tag would not automatically update the content of the page.  The new tag wasn't displayed until you manually refreshed or revisited the page.
This fix adds another selector to the JS popup call that was being used when editing tags (editing a tag automatically updated the page contents).
=> Refresh tag page content when adding a tag

applications/dashboard/models/class.importmodel.php
This PR does two things:
1. Keeps temporary import data files contained in uploads/import (they were previously just output into uploads)
2. Makes sure the temporary data directory is writable
=> Improves temporary file handling during import

plugins/editor/class.editor.plugin.php
Image uploads made using Advanced Editor were not adjusting for orientation exif data.  Editor uploads now use the core function Gdn_UploadImage::SaveImageAs, which handles orientation adjustments.
Fixes #2552
=> Updating Editor upload handling to use Gdn_UploadImage::SaveImageAs

library/database/class.dataset.php, library/database/class.mysqlstructure.php
When you change the Database.CharacterEncoding and Database.ExtendedProperties.Collate config settings then all tables will alter on the next utility/structure to reflect the changes.
This is primarily to support databases that want to switch to the `utf8mb4` encoding.
You may also need to modify the `set names 'utf8'` startup statement.
=> Allow the database encoding to be changed in utility/structure.

library/core/functions.general.php
Raise the max length from 20 to 64 to match `GdnFormat::Mentions()` which accounts for jsConnect & import names rather than the default {3,20} restriction.
=> Fix mention detector to allow longer usernames

applications/conversations/models/class.conversationmodel.php
When programatically sending messages to the current user (e.g. from a bot user), the InsertUserID gets a notification but the receiving user does not, because it excludes the session user (as opposed to the insert user) from the notifications.
This commit changes the behaviour to excluding the InsertUserID to make the Save() function session independent.
=> Don't use the session user in ConversationModel

applications/dashboard/js/import.js
Prior to this fix, the import "Go" page was displaying a popup window of the same page every time the page checked for an update to the current progress of steps.  This was due to the DeliveryType and DeliveryMethod JSON being lost during the status update requests, so the full markup of the page was returned, instead of just the relevant data.  The loss of those parameters occurred when no query string originally existed on the "Go" page.
The original JavaScript just tried to append `&DeliveryType=VIEW&DeliveryMethod=JSON` onto the end of a URL.  If no query string existed, these parameters obviously weren't being passed on.  This fix appends either a ? or a & to the target URL, depending on if a query string already exists, before attempting to pass the parameters.
=> Fixes import steps page when no original query string is present

applications/vanilla/modules/class.promotedcontentmodule.php
Fixes bug where page crashes if Promoted Content module is used and Ranks is not enabled.
=> Check to see if rank model exists in Promoted Content Module before use.

library/core/class.controller.php
If someone sets an invalid DeliveryType, just do nothing instead of gratifying them with a lurid stack trace.
=> Fix stack trace on invalid DeliveryType

applications/dashboard/settings/structure.php
Dashboard's structure recently added Role.Type to the database, which needs to exist before attempting to use the Type column for additional queries.
This change has the unfortunate side effect of making the default role change not advertise itself on /utility/structure before it is run, but I think that's an acceptable tradeoff give the alternatives of A) Big red warning on that page instead or B) Refactoring how that page calculates changes to be done to not fatal when a column isn't present yet, which sounds like a nightmare.
=> Check for Gdn_Role.Type before using in where clause

applications/dashboard/models/class.importmodel.php
DeleteFiles and DeleteOverwriteTables were renamed to celeteFiles and celeteOverwriteTables during The Casening.  This just fixes those function names.
=> Fixes typo in importmodel function names

plugins/GooglePlus/class.googleplus.plugin.php
Google sign in button was showing if the plug in was turned on, even if there was no google clientID provided to the plugin. Added the isConfigured function to the condition for printing out the link, changed the functionality of the isConfigured function so that it pings google with the clientID and returns false if anything but a 200 or 301 is returned.
=> Do not show google sign in button if google authentication not properly configured.

applications/conversations/views/messages/conversations.php
Fixes issue where Spoilers appear in excerpt.
=> Conversations: Use plainText format for excerpt in messages/inbox.

library/core/functions.general.php
The externalUrl() function used a check against “http” instead of using
the isUrl() function. Also, external urls should not be schemaless.
=> Fix the extenralUrl() function

plugins/Debugger/default.php
The debug database was not getting registered early enough and was therefor not showing any queries.
=> Fix query tracking in the debugger plugin

applications/vanilla/views/discussion/helper_functions.php
The `formatMeAction` function was running regardless of whether Garden.Format.MeActions was true or false.
I am a bit confused as to the purpose of this code, as there is a MeActions format handler in `/library/core/class.format.php`
I don't use MeActions on any of my forums so I haven't tested what happens when you switch the config on, but it seems like it might double up the AuthorAction markup.
=> Make formatMeAction obey Garden.Format.MeActions in config

plugins/editor/js/editor.js
Fixes bug where editor attempts to calculate the width of the element the image is being placed into before the image has finished uploading.
=> Editor: Use textarea id to calculate width of textarea.

library/core/class.form.php
Descending years is usually a better user experience than ascending.
=> Change order of values in Year select input.

applications/vanilla/models/class.commentmodel.php
Event names should communicate in which state of a process they are. So "BeforeDeleteComment" is clear while "DeleteComment" is not determined. I suggest to make "DeleteComment" deprecated as of version 2.somethinginthefuture.
=> Add event BeforeDeleteComment right after DeleteComment

applications/dashboard/views/entry/registerbasic.php, applications/dashboard/views/entry/registercaptcha.php, applications/dashboard/views/entry/registerinvitation.php
Gdn_Form->CheckBox() already translates its string so this code was being translated twice.
=> Remove double translate on registration forms

.htaccess
Removing this rule destroyed access to any `/folder` that isn't Vanilla. Broke statistics for my sites and whole slew of other things I didn't notice until now.
=> Read directory exception to rewrite rules in htaccess

plugins/SplitMerge/class.splitmerge.plugin.php
Disallow using a discussion redirect as part of a merge. Currently, merging into a redirect is a backdoor delete (sort of). Fixes #2782.
=> Throw permission exception when attempting to merge discussion redirects

applications/dashboard/js/addons.js
This has no affect on the execution of the click event, it makes it possible to add events to links. All this needs to be done so that we can attach events in the intercom integration plugin.
=> Remove "return false" in "enable" jquery event so that other events can be added to the link

plugins/editor/class.editor.plugin.php, plugins/editor/js/advanced.js
The IPB format is a special mashup of HTML and BBCode.  Processing is facilitated through the IPB Formatter plug-in.
This PR just adds IPB as a supported format to Advanced Editor, so discussions, comments and metadata (e.g. signatures) imported from IPB are easier to edit.
=> Adds IPB to supported formats for Advanced Editor

library/core/functions.general.php
Only tested with the 3DS, but the new 3DS should work too, since its user agent string is `New Nintendo 3DS`.
=> Recognize Nintendo 3DS and New 3DS browser as mobile

library/core/class.cache.php, library/core/class.memcached.php
Cache sharding was breaking when the number of servers was > 9, because ksort() sorts numerically by default and was putting "10" just after "1", followed by "2" and "3" etc. Added SORT_NATURAL to fix.
Also added some sharding boundaries / limits to make it more efficient. Don't create shards that are too small (< 10000 bytes), and automatically shard keys that are too large (> 100000 bytes).
=> Fix underlying sharding issue (sort order) and add auto sharding + randomization

library/core/class.format.php, plugins/GooglePrettify/class.googleprettify.plugin.php
Adding a code block with html formatting in the advanced editor automatically applies 'CodeInline' and 'CodeBlock' css classes to the pre and code tags. These css rules apply styling that interferes with the prettifier's styling. This removes the offending css classes from the code and pre tags.
=> Syntax Prettifier: Override code block formatting.

applications/dashboard/models/class.permissionmodel.php
There are some cases where JunctionID goes through to a permission model save twice and causes an SQL error.
=> Always remove redundant columns from permission value updates.

library/core/functions.render.php
* Fix coding standards in `userPhoto()`.
* Fix `userPhoto()` to accept 'PhotoUrl' when no 'Photo' is provided. Fixes interaction with PromotedContent module + Reactions, which only sets PhotoUrl, which seems reasonable.
=> Let userPhoto() fallback to PhotoUrl

applications/vanilla/views/discussions/helper_functions.php
Replaced misspelled function_exists('DiscussionSorter') with function_exists('WriteDiscussionSorter') in applications/vanilla/views/discussions/helper_functions.php so function WriteDiscussionSorter() can be overwritten.
=> Fixed misspelled function_exists('DiscussionSorter')

applications/vanilla/models/class.discussionmodel.php
Solves issue: https://github.com/vanilla/vanilla/issues/2871
Notifications for new discussions with advanced notifications were done wrong: at first the HeadlineFormat.Discussion was set to $Activity['HeadlineFormat'], then it was checked if users were mentioned and were to be informed. If yes,  $Activity['HeadlineFormat'] was set to HeadlineFormat.Mention. At last the users with advanced notification were notified but with the last HeadlineFormat.
Simply changing the order to first inform the users with advaanced notification before changing the HeadlineFormat solved the problem.
=> Prevent $Activity['HeadlineFormat'] from being overwriten

library/core/class.controller.php
The function informMessage expects parameter $Options to be an array, but the default has been a string. That string has always had to be converted to an array when the function has been called with no options.
=> Change default informMessage parameters to array()

plugins/Quotes/class.quotes.plugin.php
A bullet item is now only shown if the quote button is visible. Guests no longer see a 'stray' bullet item. Fixes http://vanillaforums.org/discussion/30497/issue-quote-plugin-shows-stray-bullet-item-for-guests
=> Fix quote plugin's stray bullet item

library/core/class.form.php
A year range of e.g. 2016-2018 procudes an ascending ordering, while a year range of e.g. 2018-2016 procudes a descending ordering.
Without supplied year range, the behavior is as before (descending ordering).
See also https://github.com/vanilla/vanilla/pull/2913
=> Made ordering of years in Gdn_Form::Date() dependend on supplied year range

applications/dashboard/controllers/class.homecontroller.php
Add the ability to add an additional CSS class to home/error via the data array. This allows the CSS class to be modified in re-dispatches.
=> Allow a CSS class to be added to error pages programmatically

applications/dashboard/views/social/connection_functions.php
Fix dashboard/view/social to not show non-functional settings link for social plugins without settings URL. The settings icon is now only shown if the plugin has a settings URL / settings page.
=> Fix settings link for social plugins without settings URL

library/core/class.applicationmanager.php
If plugins are found that require a to-be-deactivated application to be enabled, an error is thrown with the names of the dependend plugins in the error message.
This fixes possibly fatal errors caused by enabled plugins that expect certain application classes to be loaded even though the application has been deactivated.
Fixes http://vanillaforums.org/discussion/30540/fatal-error-after-disabling-vanilla-application
=> Added check for dependend plugins when disabling an application.

applications/vanilla/controllers/class.postcontroller.php
If a discussion is posted and is detected as spam then clear out the form so that the drafts autosaver doesn’t pick it up after the fact.
=> Prevent spam discussions from saving as drafts

applications/dashboard/models/class.usermodel.php
We call Validation->validate() in the save() method, and from what it looks like, it is primed with the schema.
The schema says that column is a string, so if you pass in an array for AllIPAddresses it will error out.
We handle the case of it being an array though, but only AFTER the validate(), so it is never able to do its work.
This PR fixes that issue.
=> Handle array values for AllIPAddresses in UserModel::save()

library/core/functions.render.php
Currently the sign in button write something like this `class="SocialIcon SocialIcon-Twitter js-extern" class="js-extern"` which is not valid.
=> Prevent duplicate class on SocialSignInButton

applications/vanilla/views/categories/helper_functions.php
The CategoryOptions event is useless, because the function builds a string that is not exposed.
This adds the string to the event arguments.
=> Add category options to event arguments

library/core/class.proxyrequest.php
* Don’t log the request being sent by default. Only log the response.
* Always log the response unless it is too long.
=> Tweak ProxyRequest logging

library/core/class.applicationmanager.php, library/core/functions.general.php
Fixes bug where application assets were being appended with the default APPLICATION_VERSION in the head.
=> Application manager: Add correct version to application assets.

library/core/class.cookieidentity.php
* `array_slice` was used wrong in `getCookiePayload` (it had an inverted offset so it returned only last element instead of all remaining payload).
* `checkCookie` call in `getCookiePayload` is redundant and would then create loop if used from `checkCookie`.
* `checkCookie` should call `getCookiePayload` to get secure expiration.
=> Rework cookie expiration check

library/core/class.autoloader.php
This fixes #2860 so that plugin controllers are recognized as such on windows.
=> Normalize paths in autoloader maps

applications/vanilla/settings/class.hooks.php
Deleting user content on sites with many categories is prohibitively slow.
It turns out that this is because `CategoryModel->setRecentPost()` rebuilds the entire category cache each time because of issues in `CategoryModel->setField()`.
This fix doesn’t address that concern because the code will take some work to untangle. Rather, this code instead makes sure that only the categories that the user actually has the most recent post for are recalculated. Before all categories with no posts were also being included.
There is also an issue with the DateLastComment being set improperly for discussions with no comments that was also fixed.
=> Speed up user deletes on sites with a lot of categories

applications/dashboard/models/class.assetmodel.php
Show the path of the asset that is causing the deprecated notice.
=> Add some more information to AssetModel deprecated notices

applications/dashboard/controllers/class.settingscontroller.php
TextBoxes in ThemeOptions have always been empty, regardless of their config value. The reason is that the value has been set to the form, but not to forms $_DataArray.
Thanks to ThemeSteam who spotted this misbehavior!
For anyone interested in this: you can create text inputs in your theme options quite easily (in themes about.php)
~~~
$ThemeInfo['SomeTheme'] = array(
// ...
'Options' => array(
'Text' => array(
'PanelPosition' => array(
'Default' => 'left',
'Description' => 'Please choose between "left", "right", or "none"',
'Type' => 'TextBox'
)
)
),
// ...
~~~
Afterwards you can access such a setting with `c('ThemeOption.PanelPosition')`
=> Fix TextBoxes Content in ThemeOptions

library/core/class.authenticationprovidermodel.php
Since the primary key of authentication providers is not an identity it needs some way of being changed on save. You can now do this by passing the current value of the primary key to the `ID` field of the `$Settings` array.
=> Allow Gdn_UserAuthenticationProviderModel->save() to change primary keys

applications/dashboard/locale/en.php, applications/dashboard/views/activity/helper_functions.php, applications/dashboard/views/modules/message.php, js/global.js, js/library/jquery.popup.js, plugins/GettingStarted/default.php, plugins/Tagging/views/tagging.php
The multiply character is used as a "Close" symbol in the UI. I replaced it with it's html entity counterpart.
I think generally the source code should rely as much on ascii as possible and avoid using unicode characters.
=> Replace "×" with "&times;" to avoid character encoding issues

plugins/Quotes/js/quotes.js
When quoting text, if you do not use the Advanced Editor WYSIWYG mode your cursor does not got into the comment box after the quoted text is appended. This fixes that.
=> Put focus into the text box when quoting

applications/vanilla/controllers/class.discussioncontroller.php
If a discussion was not found with /discussion/(discussion ID), Vanilla would immediately move to throw notFoundException.  This update adds an event just prior to this, so that custom handling of "discussion not found" behavior can be made with plug-ins.
=> Add event before notFoundException in /discussion/index

library/core/class.controller.php
By default, Gdn_Controller sends the following Cache-Control header to prevent caching:
"Cache-Control: private, no-cache, no-store, max-age=0, must-revalidate"
The "no-store" attribute however causes the client browser not to cache form input fields. As a result, users may experience data loss when writing e.g. comments and navigating back and forth in history. Instead of the last cached form content, a blank form field is shown.
See also http://blogs.atlassian.com/2007/12/cache_control_no_store_considered_harmful/
Side-effect: Without no-store, navigating through the browser history is much faster (at least on mozilla based browsers). This is because without no-store, history really means history - pages are not re-loaded but taken from the browser's history cache.
Fixes …
=> Fix client-side form caching via removal of "no-store" from "Cache-Control" header

js/global.js
The replacements finally handle full 3 or 4 byte utf8 unicode representations well.
See http://ecmanaut.blogspot.de/2006/07/encoding-decoding-utf8-in-javascript.html
This fixes http://vanillaforums.org/discussion/30590/issue-unicode-emoji-mangled-by-vanilla-js
=> Fix UTF8 decode/encode in global.js to support multibyte unicode strings

plugins/ButtonBar/js/buttonbar.js
- Create function ButtonBar.init() which does what the livequery handler did
- Call this function on document.ready, EditCommentFormLoaded and popupReveal
=> ButtonBar: Remove livequery dependency

js/global.js
- Bound autodismiss to the proper event
- There is not input with the name of "HourOffset" anywhere (the hour offset is set using ajax + definitions)
- Bound the gdn.atCompleteInit call to the proper events
=> Remove remaining livequery uses from global.js

plugins/editor/js/editor.js
The (optional) selector argument is needed, because the jQuery selector API has been deprecated.
See http://api.jquery.com/selector/
=> editor: Remove livequery dependency

applications/dashboard/controllers/class.sessioncontroller.php, applications/dashboard/models/class.assetmodel.php, library/core/class.form.php, library/core/functions.general.php, plugins/OpenID/class.lightopenid.php, plugins/OpenID/class.openid.plugin.php
Removed or made deprecate all code related to handling PHP's deprecated magic quotes.
Exception: Vendor libraries. I didn't touch them.
* Made TrueStripSlashes() and removeQuoteSlashes() from functions.general.php deprecated and removedreferences to it.
* Removed all "if ($MagicQuotes) ..." or similar code.
=> Remove error prone magic_quotes support

library/core/class.controller.php, library/core/functions.general.php
If delivering JSON and receiving an Origin header from the client, attempt to verify the host of Origin against Garden.TrustedDomains.
Origin values should match if they are a legitimate part of a domain in Garden.TrustedDomains.  For example: If google.com is a trusted domain, we should be able to use it to match mail.google.com, www.google.com or google.com, but not fakegoogle.com.
Adds isTrustedDomain function to determine if a supplied domain is a match for an entry in TrustedDomains.  If no domain is provided, fallback to the request's host.
=> Add CORS allow-origin header for trusted domain-originating requests

library/core/class.plugin.php
Assuming you want to use the dispatcher in a plugin and access the request arguments, you had to always access them with $sender->RequestArguments.
Following code, which I expected to work flawlessly did fail since the $args parameter is not passed to the custom function:
~~~
public function vanillaController_something_create($sender, $args) {
$this->dispatch($sender, $args);
}
// For example: /vanilla/something/edit/1
public function Controller_Edit($sender, $args) {
// will fail because $args are not passed, although this is a common way to access request arguments
$somethingId = $args[0];
// by now you have to do it like that:
$somethingId = $sender->RequestArguments[1];
}
~~~
=> Add $RequestArgs as parameter for dispatcher function

applications/vanilla/models/class.discussionmodel.php
This issue manifests itself when memcache is enabled and a new discussion is posted as an announcement. The discussion does not show up in in the announcements list and is thus removed from the recent discussions list.
=> Fix issue involving posting new announcements

applications/vanilla/js/discussion.js, plugins/editor/js/editor.js
Moves attachment editing to a more sane place in the bodybox form.
Also trigger reset and clear functions when clearing comment form.
Fixes bug where selecting the edit comment option from a comment's options dropdown twice shows makes the upload preview not read-only.
=> Fix attachment placement when editing a post.

applications/dashboard/modules/class.configurationmodule.php
If "Title" and "Description" have been assigned to the controller _before_ the call to function initialize(), they have been overwritten. Now they will be merged to the config data that is assigned to the controller.
=> Make the assignment of the config data be non destructive

applications/vanilla/controllers/class.discussioncontroller.php, applications/vanilla/views/post/comment.php, index.php, js/global.js
Fixes these issues:
The DiscussionController::index() method looks for stashed comments, but fails to correctly put these stashed values into the comment form.
The $('a.Stash').click() event handler in global.js detects a stashed comment, but fails to differ between non-embedded and embedded stashed comments. Also, it redirects automatically to the login form even if c('Garden.SignIn.Popup') is set to true. 
The view vanilla/view/post/comment.php incorrectly asks for $this->data('ForeignUrl') even though this view is for non-embedded comments where the concept of a ForeignUrl doesn't make sense.
=> Fix stashing of non-embedded comments written by non-logged-in users.

plugins/Quotes/js/quotes.js
* Remove livequery dependency.
* Remove the editor stack concept and insert quotes in the last TextBox that had focus instead.
* Pull the function definitions out of the constructor.
* Make quote folding strings translateable.
* Remove commented out code.
* Remove dead code.
* Added comments.
* Lord Brackos
Tested with: ButtonBar, editor.
=> Quotes: JS refactor

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/controllers/class.messagecontroller.php, applications/dashboard/models/class.messagemodel.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/settings/class.hooks.php, applications/dashboard/settings/structure.php, library/core/class.session.php
No functionality changes.
* Casening.
* Remove last of `[Admin]` location code in messages.
* Remove direct config checks for email confirmation in favor of `UserModel::requireConfirmEmail()`.
=> Code cleanup around messages & email checking

plugins/ProfileExtender/class.profileextender.plugin.php
If an existing field gets edited into a DOB field, it could have a different config slug, which shouldn't matter.
=> Fix profile extender to not choke on DOB field w/ non-standard slug.

library/core/class.controller.php
Currently only themes and applications have the privilege of defining a master view. Since plugins are first-class citizens now they should be able to also.
=> Allow a plugin to contain a master view

applications/dashboard/modules/class.configurationmodule.php, plugins/Facebook/class.facebook.plugin.php, plugins/Twitter/class.twitter.plugin.php
* Trim incoming values to ConfigurationModule generally - I cannot think of a use case where you'd ever purposefully enter a space at the start or end of a config value, but it can seriously mess up folks when it's a copy/paste error.
* Trim Twitter & Facebook API keys entered by user (since they don't use ConfigurationModule yet).
* Fix some misc casening in config module.
See #1509
=> Trim user-entered API keys and config strings

applications/dashboard/controllers/class.entrycontroller.php
When an SSO user association is initially made without sending across a name for the user, the user enters their own name.  That name is supposed to be validated, but Vanilla was skipping over that process, due [to the setting of Name to ConnectName prior to the AutoConnect process](https://github.com/vanilla/vanilla/commit/3cf773bbc413150c387a74ce99e9a1056d60556a).  [In later logic](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/controllers/class.entrycontroller.php#L612-L614), since the Name field is set in the Form data, the user is automatically created without validating the name.
This PR moves the setting of the Name field to the value of ConnectName into the AutoConnect block, so it is only run if an existing user is found and being updated.  This allows …
=> Fix username validation after manual entry during SSO

applications/vanilla/settings/class.hooks.php
class.hooks is being called from dashboard and no default application is specified for the call to
disscussion.js so the application tries to find it in dashboard. adding vanilla as default location fixes
the issues.
=> addjsfile fails to find discussion.js on profile page

applications/vanilla/views/categories/all.php
Adds an if statment that checks if Category->Depth is set. This will prevent the undefined object notice.
=> fix call to undefined object in the Category View

library/core/class.controller.php, library/core/functions.general.php
Gdn_Controller::fetchViewLocation() makes a call to viewLocation() without using its return value (only for creating a trace() in case its return value diverges from the view location it determines on its own).
Each call to viewLocation() results in one or more calls to file_exist(). On a test installation, a normal request resulted in about 75 calls to file_exist() with unique path argument which translated into a delay of about max. 10 milliseconds.
This PR makes Vanilla faster and cleans-up the codebase. You need to check for references to viewLocation() in your proprietary code.
* Removed calls to viewLocation() from Gdn_Controller::fetchViewLocation()
and Gdn_Controller::renderMaster().
=> Remove calls to viewLocation() from Gdn_Controller

applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/views/profile/picture.php
* Add a link to remove the profile picture in the edit profile menu no matter what. Previously it was just when editing someone else’s profile.
* Change the way the transient key is added to the remove picture URL. This fixes an issue when user URLs have no user IDs.
Note that this tweak breaks index.php?p= style configs, but we are deprecating that behavior.
=> Tweak profile picture removal

js/global.js
Checked with JSHint. There are still a few warnings.
This fixes mostly missing semicolons and undefined variables, strict condition checks where possible and a leaky global smiliar to #3051.
One functional change that comes with that:
`null` can now be used as a default fallback in `gdn.definiton`.
This is actually fixes a check (line 810) that would always return true:
if (gdn.definition('TickExtra', null) != null)
=> Clear up JSHint warnings in global.js

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/modules/class.cropimagemodule.php
Apparently paths to Vanilla's uploads don't always contain 'uploads'. Checks to see if the directory 'defaultavatar' exists, rather than 'uploads/defaultavatar'. Also forces hidden form values to update when a new avatar is uploaded.
=> Default avatar path

index.php, js/global.js
The calling object and params were mixed here. The proper function calls are regexObj.test(str) (vs. str.match(regexp) ). This pr fixes broken youtube embeds.
=> Fix call to test regex for youtube video embeds.

applications/dashboard/models/class.usermodel.php, library/core/functions.render.php
Some views take care of possible missing avatars, some do not. This fixes a regression bug where some default avatars or vanillicons were not showing up (in conversations and activity).
Also moves placement of url variable assignment outside of if statement, so it gets assigned no matter what.
=> Readd default photo value to joinUsers function.

applications/vanilla/views/settings/managecategories.php, plugins/GettingStarted/default.php
The getting started plugin had a lot of sloppy calls to t().
This PR addresses them.
- Give long translations a pithy code.
- Combine concatenated translations into one string using formatString() for links.
- Remove references to “left” or “right” so that RTL locales won’t be confusing.
=> Clean up the translations on the getting started plugin

applications/dashboard/models/class.usermodel.php
see #2363 and http://www.iana.org/domains/reserved
domain.com is a registered domain, while example.com can not be registered.
=> Use system@example.com for system user

applications/dashboard/controllers/class.entrycontroller.php
There is a code path in entry/connect that always sent the connect email instead of looking at the config setting.
=> Honor the Garden.Registration.SendConnectEmail setting

library/core/functions.render.php
When formatting html posts, we add br tags in place of line endings. This also adds br tags between table html tags, which causes strange rendering.
=> Remove <br> tags around list items tags and table content tags.

library/core/class.format.php, library/core/class.markdownvanilla.php, library/vendors/markdown/Michelf/Markdown.php
This PR moves most of the Vanilla Markdown customizations to a new class that extends the library. It also adds a flag to Gdn_Format::Markdown() to allow call-time toggling of these rules.
=> Move Markdown customizations out of vendor

applications/dashboard/controllers/class.entrycontroller.php, index.php, js/global.js
- Allow plugins to force a popup check by using the data array.
- Use `window.location =` instead of `window.location.replace()` to maintain proper history.
=> Tweak the behavior of sign in popups

applications/dashboard/controllers/class.utilitycontroller.php, applications/dashboard/models/class.assetmodel.php, library/core/class.controller.php
This allows the list of files that can trigger CSS combining to be hooked and modified, thereby allowing different applications to create their own unique lists of combined files.
=> Formalize CSS anchor list event hook, fix utility/css comments

library/core/class.controller.php
This makes debugging a bit easier when looking at the API without a JSON view type plugin.
=> Pretty print JSON responses

applications/conversations/controllers/class.messagescontroller.php, applications/conversations/js/conversations.js, applications/conversations/views/modules/clearhistory.php
Users don’t really delete conversations so the wording was confusing. This change also moves the confirmation into a proper postback rather than a GET request that validates the CSRF token.
=> Rename “Delete Conversation” to “Leave Conversation”

applications/vanilla/js/discussion.js
Puts the code to switch out the buttons in the right place (`resetCommentForm()`, since the preview is also removed there). Fixes #1708
=> Show the preview button again when posting in preview mode

applications/dashboard/models/class.usermodel.php
- Make sure the RoleID validation rule is cleared when not saving roles. This avoids the rule from creeping in from a previous save.
- Make sure the user photo and roles don’t get put into an SSO user if not set originally.
=> Fix UserModel pollution issues

library/core/class.form.php, library/core/class.request.php
This prevents the puzzling issue where a user submits a form without a valid CSRF token and the app doesn’t behave like it is in a postback state. This change allows developers to throw an exception if the page is posted back AND has an invalid CSRF token.
=> Allow CSRF authentication to throw exceptions

applications/dashboard/models/class.usermodel.php
In UserModel::joinUsers(), the default avatar is attached to a user if they don't have one. Later, in the userPhoto function, the basename of a user's avatar is changed if it's not a url. This PR changes the return value of the default default avatar from a relative path to a full url, so the basename does not get changed.
Fixes a bug where the default default avatar is a broken image.
=> Return full url to to the default default avatar.

applications/dashboard/models/class.usermodel.php, library/core/class.session.php
Change to a better random string method for transient keys. Also, expire the transient key cookie on sign out.
=> Use a different method to generate random strings

applications/dashboard/models/class.usermodel.php
Static files must be enclosed in `asset()`, not `url()`.
=> Fix the default avatar URL

library/core/class.request.php
There were certain situations where Gdn_Request would incorrectly grab a user's IP address, having a comma (and possibly a space) appended to it.  A couple of possible scenarios have been identified that may be responsible:
* X-Originally-Forwarded-For is sent along with the request and contains a comma in its value.  Reading this value happened to fall after the current multi-value IP list check and overwrote whatever value had been established for the IP address up to that point.  After discussing with Tim, I've purged this code, since it is no longer needed.
* The fallback is met when trying to determine the value to use for the request's IP address.  If this value happened to contain a comma-separated list, it was passed along without further processing.  I've added a check to see if …
=> Fix invalid IP address being recorded & submitted to antispam services

library/core/functions.general.php
Our default userAnchor change from `/{id}/{name}` to just `/{name}` has broken they previously-passable links to `/{id}/You`. This corrects the formulation to quarantine the derived username in case it's "You".
=> Correct 'You' links in activity

applications/vanilla/views/discussion/discussion.php
A comment displays the poster's IP to users with the Garden.PersonalInfo.View permission, the discussion should as well.
=> Add IP meta to a discussion item in the discussion page.

applications/dashboard/controllers/class.entrycontroller.php
Move the form filtering to an earlier spot in entry/connect in order to take some of the responsibility off of individual SSO plugins.
=> Move the form filtering routine in entry/connect

applications/vanilla/modules/class.newdiscussionmodule.php, applications/vanilla/views/post/comment.php
Instead of just sending user to /entry/register, the NewDiscussion button will now remember where they were trying to go so they can go back there afterward.
=> Add Target redirect support to NewDiscussion module when guest access is enabled

applications/dashboard/controllers/class.setupcontroller.php, library/core/class.configuration.php
- Allow a non-existent config file to be created on save. This prevents the bug where the configuration cannot be written when it doesn’t exist.
- Don’t create an empty config file on setup until it has data.
=> Fix configuration file creation and saving

applications/dashboard/controllers/class.setupcontroller.php
- Throw an exception when Vanilla is already installed instead of rendering an HTML-only page.
- Set a data flag when Vanilla installs correctly.
- Throw an exception when Vanilla has setup errors and JSON is requested.
- Only redirect to the dashboard when the full HTML page is requested.
=> Make the setup controller more RESTful

plugins/GooglePlus/class.googleplus.plugin.php
Wrap an update statement around a db check so that it doesn’t show up in /utility/structure all the time.
=> Fix /utility/structure pollution in the Google+ plugin

applications/dashboard/controllers/class.rolecontroller.php, applications/dashboard/models/class.rolemodel.php
Add some additional information when getting a single role as data.
- Return the role as a single “Role” key in the data array.
- Add the role’s permissions to the result.
=> Cleanup the API access for role/get

applications/dashboard/controllers/class.rolecontroller.php, applications/dashboard/models/class.rolemodel.php
- Allow permissions to be set in an optional “Permissions” key.
- Return a more API-friendly role after adding/editing a role via API.
=> Enhance the role/add and role/edit endpoints for API access

applications/vanilla/views/modules/helper_functions.php
Slicing before stripping tags results in some tags being sliced and therefore, not stripped. This fixes a bug where tags were showing up in promoted content excerpts.
=> Promoted Content: Change excerpt formatting.

applications/dashboard/models/class.usermodel.php
I found that ordering the tag search results by comment count generally gives better results, as these are the users you are more likely to mention / message.
=> Order user tag search by comment count

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/views/settings/registration.php
Adds config `Garden.Registration.ManageCaptcha` that, when set to `false`, blocks access & editing of the Captcha API key.
=> Add ManageCaptcha config to optionally block key editing

applications/dashboard/controllers/class.profilecontroller.php, plugins/ProfileExtender/class.profileextender.plugin.php
The $User object is used by Smarty to check if a User is logged in. This User object is being overwritten by the removed line and the data is not used by the profile because the same data is stored in the $Profile object. This change should fix  #2993.
=> Fix incorrect User being set on profiles for Smarty templates

applications/dashboard/models/class.usermodel.php, plugins/ProfileExtender/class.profileextender.plugin.php
Rename the event arg 'Users' in the `register()` method to `RegisteringUser` (and pass by reference for greater utility) to prevent naming conflict with the event arg in `setCalculatedFields()` which will overwrite this arg when sending a confirmation email for applicant users.
=> Fix ProfileExtender dropping data when email confirmation is used with applicant registration

applications/dashboard/models/class.usermodel.php
There were some invalid array_key_exists calls in UserModel::sso that were causing a couple SSO data fields to be erroneously removed.  This update addresses those function calls.
=> Address invalid array_key_exists calls in UserModel::sso

.htaccess
Path info was a little ahead of its time on some hosts.  This update reverts .htaccess to use the universally loved and supported p URL parameter to pass the request path to Vanilla.
=> Revert .htaccess to rely on p URL parameter

library/core/functions.render.php
The attributes array was not being passed through the attribute function before echoing.
This fix is similar to the master branch.
=> Fix regression in 2.1 re: Img function

js/global.js
When attempting to sign-in with the "Comment As ..." button on an embedded comment form, the redirect-to-sign-in page behavior is not being triggered if the comment body has been filled out.  This is due to the comment data being stashed, which involves stopping the default anchor href behavior.  Previous versions of global.js had the redirect in place, but it looks like it was removed in [this commit](https://github.com/vanilla/vanilla/commit/8e3e07fcceb62b62f6e20e0b0fce7d9865735d68#diff-206bb8e5b8584223b92afae06825d2faL1149).
It's not immediately apparent why it was removed, so this PR only restores the redirect-after-stashing behavior.
=> Restore redirect after stash

build/build.xml
This update adds the ability for Phing to grab Vanilla's version number from index.php.  If a valid value is found for the version, it's used to build the output filename (e.g. vanilla-2.1.100.zip).  If a valid value is not found, it falls back to simply vanilla.zip.
=> Parse index.php with Phing, use APPLICATION_VERSION in build filename

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/views/settings/email.php, library/core/class.email.php
Sometimes you don't want to include a forum user's username in the "to" field of your e-mails.  This update adds a new configuration option (`Garden.Email.OmitToName `) and a corresponding new form control on the "Outgoing Email" page of the dashboard.  When enabled, this option stops usernames from being included in the "to" field of outgoing e-mails.  Only the e-mail address will be passed to that field.  By default, the value is false, so Vanilla's current behavior of including usernames is not affected unless explicitly changed.
=> Add option to not include usernames in "to" field of outgoing e-mails

library/database/class.database.php
This will help code know how many rows were affected and possibly take different actions depending on whether or not a query did anything.
=> Keep the row count around after running queries

library/core/functions.general.php
Add the ability to pass a set of explicit characters to betterRandomString() so that randomString() can just call betterRandomString(). This will lead to a deprecation of betterRandomString().
=> Unify the randomString() and betterRandomString() functions

library/core/functions.validation.php
\pPc was being interpreted as \pP.
This fixes bug where usernames with any kind of punctuation character pass the validation.
=> Add braces around unicode categories regex.

applications/dashboard/models/class.usermodel.php
Some permission checks early in the request may incorrectly return a false value, because the current user's session hasn't been fully started.  This error is causing some fields to be unduly stripped from form posts, such as RankID.
This fix moves the permission-based addFilterField calls from the UserModel constructor, back down into the filterForm function. By the time filterForm is called, the proper session setup should've taken place and the permission checks should be accurate.
This essentially reverts commit 7290c664208fbcd222f91d196fe1ef56b78729f3.
=> Move UserModel field filters from constructor to filterForm

applications/vanilla/models/class.discussionmodel.php, index.php
Fixes #3240
Please review for PHP 5.3 compatibility in addition to normal review.
=> Backport discussionModel::canEdit() to 2.1

library/core/class.autoloader.php
=> 2.2. Backport: Normalize paths in autoloader maps

library/vendors/phpbb/phpbbhash.php
phpBB can potentially use the Blowfish hashing algorithm for its passwords.  Vanilla doesn't currently support these password hashes when checking against a password imported from phpBB/a password with phpbb as the `HashMethod`.
This update enables `phpbb_check_hash` to recognize and compare hashes for Blowfish.
=> Expand phpBB password hash type to support crypt/Blowfish

library/core/class.upload.php, plugins/editor/class.editor.plugin.php
Adds OriginalFilename to uploads, so that the file's original name can be referenced in Gdn_Upload::saveAs
Recap of current issue:
1. Non-image uploads made with the Advanced Editor plug-in eventually make their way to be saved: [class.editor.plugin.php:739](https://github.com/vanilla/vanilla/blob/7963683ee411e8935baa7ebd4f2dcc7abf6f25b9/plugins/editor/class.editor.plugin.php#L739)
2. Gdn_Upload::saveAs fires an event prior to the save: [class.upload.php:296](https://github.com/vanilla/vanilla/blob/8ab35aca6fec97aa117cc1295c4ba9434f41876f/library/core/class.upload.php#L296)
3. The CloudFiles plug-in hooks into this event: [class.cloudfiles.plugin.php](https://github.com/vanilla/vanillainfrastructure/blob/6741cdec7b6c470f88989e8b9ab7bd05127d7019/plugins/cloudfiles/class.cloudfiles.plugin.ph …
=> Add support for OriginalFilename to uploads

library/core/functions.general.php
Attempt to clarify what the third parameter in `decho()` means. Given [this](https://github.com/vanilla/vanilla/pull/3225) there was obviously some confusion of what the `$Permission` parameter meant to the point of flipping it’s meaning entirely.
=> Rename the parameters in decho

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/js/user.js, applications/dashboard/views/user/add.php
Adds a checkbox to the add user form that allows no password to be specified. Users added this way must request their own passwords or user SSO and auto-connect.
=> Add the ability for admins to add users without passwords

plugins/Quotes/js/quotes.js, plugins/editor/js/editor.js
The scrolling happens anyway and the scrolling animation doesn't play nice with the WYSIWYG editor.
Fixes bug where quoting would scroll down, then up the page when the WYSIWYG editor was enabled.
=> Remove the animated scrolling from the Quotes plugin.

plugins/ProfileExtender/views/profilefields.php, plugins/ProfileExtender/views/registrationfields.php
This will allow us to manually include an array in the config file called OptionsLabel which is merged with the Options array to create dropdowns which have different values and labels. Presently when you create a dropdown we take the array of options provided by the user and merge it to itself to make something like:
&lt;option value='Canada'&gt;Canada&lt;/option&gt;
This PR provides the opportunity for someone to manually include an array in the config that would be merged with the options to provide user friendly labels:
&lt;option value='ca'&gt;Canada&lt;/option&gt;
If no OptionsLabel array is present, it continues to work as it always has.
=> Allow creation of separate values and labels in dropdowns in profile extender plugin.

library/vendors/markdown/Michelf/Markdown.php, plugins/Quotes/class.quotes.plugin.php
Allow nested quotes in Markdown and include Vanilla's quote classes to allow folding.
=> Allow nested quotes in Markdown

index.php, js/embed_local.js
Fix an issue where paths that have special characters don’t always work as deep links.
The most common case of this would be if a path includes an unencoded # symbol. Try adding one into a username somewhere and then click on their name for their profile link.
=> Encode the paths that are sent to the parent frame in embedding

applications/vanilla/models/class.discussionmodel.php
`DiscussionModel::getID` takes `DataSetType` as a parameter, but doesn't make use of it.
This update passes the `DataSetType `parameter to `firstRow` when querying the database for the discussion row.
=> Allow DiscussionModel::getID to use dataset type

applications/dashboard/models/class.spammodel.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/views/post/spam.php
When comments or discussions are edited, they aren't passed through the SPAM filter.  This means there is a very real possibility a spammer could create a legitimate discussion, have it pass the SPAM filter, then go back and edit it with something that wouldn't have been able to pass in the first place.
The SpamModel::IsSpam blocks for discussions and comments have been moved above the insert- and update-specific routines, so it should be able to hit them both.
The $this->CheckForSpam condition is not used in this fix, because it is not pluggable. SpamModel::IsSpam uses a handy CheckSpam event, so plug-ins like Akismet can do their thing.
=> Add SPAM check when editing discussions or comments

.gitattributes
Reverts vanilla/vanilla#2850
see: http://vanillaforums.org/discussion/comment/235275/#Comment_235275
Without composer.json you can't run composer from the archive (which is convenient sometimes).
=> Revert: Ignore composer files for archive

applications/dashboard/controllers/class.activitycontroller.php, applications/dashboard/settings/configuration.php
It is currently not possible to change the length of an activity page.
I don't think this warrants a GUI, but I do think it is important.
=> Activity page length configuration

applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php
Add new method to test whether a user has permission to view a specific discussion by first checking category-specific permissions and then firing an event so it can be overridden.
=> Add discussion-specific view permission check.

applications/dashboard/models/class.permissionmodel.php, bootstrap.php
See #2862
**Summary**: MySQL 5.6+ defaults to strict mode, so we need to support it. Our method of mapping permissions to defaults causes a strict mode failure on initial setup. This works around this problem by detecting this situation and force-mapping the permissions to off.
**Only functional change is the new block starting at 250 ($DefaultRow)**. Everything else is to improve the clarity (docs, casening, line length).
=> Detect initial setup in permissionmodel->define() and force mappings

applications/dashboard/controllers/class.profilecontroller.php
This update adds the ability to set a user's `Photo` attribute to a URL when the current user has `Garden.Manage` permissions.
=> Allow photo user record attribute to be set via API

applications/dashboard/models/class.usermodel.php
Currently `usermodel->removePhoto()` will only set `User.Photo` to `null` if the current value evaluates to `true` (If `Photo` were `0` for instance, it would get stuck), and it blindly attempts to delete a physical file even tho it's acceptable for that field to be a URL. This fixes both of these bad behaviors.
=> Fix photo removal to always wipe field and selectively attempt file delete

library/database/class.database.php
Remove notice when a slave database in configured with no password.
To test a slave configuration you can specify a slave DSN to be the same as the master configuration.
```php
$Configuration['Database']['Slave']['Dsn'] = 'mysql:host=localhost;dbname=xxx';
$Configuration['Database']['Slave']['User'] = 'xxx';
```
=> Fix PHP notice with a partial slave database config

applications/dashboard/controllers/class.profilecontroller.php, library/core/class.upload.php
Move the ability to set a user's photo to a URL to `/profile/picture` and tighten the security involved in such an action.
=> Move ability to set avatar to URL into /profile/picture

applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/models/class.categorymodel.php
Allows permissions to be saved with a category by specifying the
permissions with a Permissions key. The format mirrors the one returned
from /settings/getcategory.
=> Allow categories to be saved with an API-friendly Permissions key

library/vendors/Auth/OpenID/AX.php, library/vendors/Auth/OpenID/Consumer.php, library/vendors/Auth/OpenID/Server.php, library/vendors/Auth/Yadis/XRDS.php
These changes are a result of passing PHP’s code linter over our source code. If you want to add lint checking to your local machine you can try the bash script [here](https://gist.github.com/tburry/53b374492b24beae1b0b).
=> Remove some deprecated language features in the OpenID library

library/core/class.request.php
The SCRIPT_NAME variable is part of the CGI spec while PHP_SELF is not. Additionally, PHP_SELF includes PATH_INFO which we don’t want.
=> Use SCRIPT_NAME instead of PHP_SELF to determine web root

applications/vanilla/settings/class.hooks.php, library/core/class.controller.php
The definition list is already json encoded. This double encoding (and
decoding) serves no purpose.
=> Remove json encoding from Gdn_Controller->_Definitions['ResolvedArgs']

js/global.js
Use SelfUrl rather than the document url.
Fixes bug where cancelling the moderation inform message in Vanilla comments brings the user to /index.php?p=/discussion/embed/ rather than staying on the current page.
=> Use explicitly defined SelfUrl in inform messages, if it exists.

applications/vanilla/controllers/class.settingscontroller.php, library/core/class.form.php
Fixes issue where Categories cannot be saved or edited with strict mode enabled.
=> Enforce tinyint on Category fields.

library/core/class.passwordhash.php, library/vendors/Auth/OpenID/AX.php, library/vendors/Auth/OpenID/Association.php, library/vendors/Auth/OpenID/Consumer.php, library/vendors/Auth/OpenID/DiffieHellman.php, library/vendors/Auth/OpenID/Discover.php, library/vendors/Auth/OpenID/DumbStore.php, library/vendors/Auth/OpenID/FileStore.php, library/vendors/Auth/OpenID/MemcachedStore.php, library/vendors/Auth/OpenID/Message.php, library/vendors/Auth/OpenID/PAPE.php, library/vendors/Auth/OpenID/Parse.php, library/vendors/Auth/OpenID/SQLStore.php, library/vendors/Auth/OpenID/SReg.php, library/vendors/Auth/OpenID/Server.php, library/vendors/Auth/Yadis/HTTPFetcher.php, library/vendors/Auth/Yadis/Manager.php, library/vendors/Auth/Yadis/ParanoidHTTPFetcher.php, library/vendors/Auth/Yadis/ParseHTML.php, library/vendors/Smarty-2.6.25/libs/Smarty_Compiler.class.php, library/vendors/pclzip/pclzip.lib.php, library/vendors/phpThumb/phpthumb.ico.php, library/vendors/phpass/PasswordHash.php
PHP 7 deprecates class constructors named with the class name. Renaming them to __constuct() ensures that we will be compatible with future versions of PHP.
=> Fix class constructors for forwards compatibility

library/core/class.proxyrequest.php
The response body ends up logging a lot of data. This feature decreases response body logging by default in the following ways:
- Don’t log the response bodies of GET or OPTIONS requests unless it is forced via the `LogResponseBody` option.
- Correct a bug in JSON-encoded responses. This will decrease the amount of escaping in the response and save us some bytes.
- Logging requests is now controlled via the `LogRequest` option and is disabled by default.
- Logging is now done at the INFO level because we intend to stop recording DEBUG level messages except via the debug bar.
=> Lower the amount of ProxyRequest response body logging

library/core/functions.general.php
There was an issue when the context contained a 0 that it would output an empty string. Try this code to test:
```php
die(formatString('"{num}" === 0', ['num' => 0]));
```
=> Fix issue with formatting “0” in formatString().

library/core/class.proxyrequest.php
This allows code to not log regular responses, but log them when there is an HTTP error.
=> Add the LogResponseErrorBody option to ProxyRequest

applications/dashboard/models/class.usermodel.php, library/core/class.dispatcher.php
I've experienced issues with the `Visit` event being fired by `UserModel`.  Specifically, I was unable to successfully obtain an Anniversary badge with the Badges plug-in until I moved this event.  Moving the `UserModel::fireEvent` call from `Gdn_Dispatcher` and putting it in a similar place in `UserModel` seemed to do the trick.
=> Moves Visit UserModel event from dispatcher to UserModel

plugins/editor/class.editor.plugin.php, plugins/editor/js/editor.js
If wysihtml5 has a custom key handler, it's failing here. This fixes a bug where clicking enter from the fileupload dropdown submits the post.
=> Add button enter key handler to wysiwyg-format editor.

applications/dashboard/views/modules/trace.php, library/core/functions.error.php, library/core/functions.general.php
- Trace errors as ErrorException objects instead of just their messages.
- Render empty error variables. Before they were ignored in the trace output.
=> Tweak the way errors are traced

library/core/class.proxyrequest.php
The method was being confused with the page the log was being called on.
=> Change the names of the log context for ProxyRequest

library/core/class.pluginmanager.php
Changes the way mobile friendliness is determined in a plugin's settings, as MobileFriendly should be the rule, not the exception.
Before we would need to mark a plugin as 'MobileFriendly' => true for it to work on mobile.
This pr would make is necessary to mark 'MobileFriendly' => false to disable it on mobile.
=> Make addons mobile-friendly by default (opt out, not in)

applications/dashboard/models/class.usermodel.php, applications/dashboard/settings/class.hooks.php, library/core/class.validation.php
Change the way bail-out errors happen with SSO strings. The tracing is now done on the validation results rather than within the function. This lets other code get at those errors in case they aren’t just for debugging.
=> Change the way UserModel->sso() traces validation errors

library/core/functions.render.php
I first thought of changing alternate() when I saw it uses a modulo calculation when handling a bool value would also be enough, but looking closer at it showed that the output of `function alternate($Odd = 'Alt', $Even = '', $AttributeName = 'class')` is in almost any combination of parameters not what you expect.
Called without any parameters, it echos the following:
Odd:
Even: ` class="Alt"`
...
Already here it is faulty: it uses the standard $Odd parameter for the even lines.
If I pass `alternate('odd', 'even')`, I get
Odd:  `even`
Even: `odd` 
That they are mixed up was to be expected after point 1, but I would expect those to be enclosed in class="..."
Even if I pass `alternate('odd', 'even', 'arbitraryName')`, I only get
Odd:  `even`
Even: `odd` 
So it's obviously not as useful as …
=> Make alternate() use parameters correctly

applications/vanilla/controllers/class.postcontroller.php
I have a [plugin](https://github.com/JasonBarnabe/ChooseYourOwnFormat) that lets users choose whether to post in Markdown or HTML.
In 2.2, Vanilla is not reading the `Format` parameter on an AJAX comment preview. It reads it correctly when posting the comment, as well as posting or previewing discussions, but just not previewing comments. This PR fixes that.
=> Respect format coming from params on comment preview

library/core/class.emoji.php
The current emoji regex allows english letters and  some arbitrary characters (`+` and `-` for `:+1:` and `:-1:`) only.
This will recognize any non-whitespace character `[^\r\n\t\f ]` between delimiters (`:`) as an emoji. (Non-greedy so that `:smile::smile:` is recognized as two emoji).
=> Expand emoji regex to allow all non-whitespace chars

library/core/class.form.php
Added a new event to form->captcha to allow plugins to easily output custom captchas instead of the default reCAPTCHA. 
Also changed spelling of vars to lowercase and eliminated one unneeded if clause. For an explanation: the original code would have been extended to:
~~~
if (!in_array($Language, $Whitelist)) {
if (in_array(Gdn::locale()->Locale, $Whitelist)) {
$Language = Gdn::locale()->Locale;
} else {
$Language = false;
}
}
if ($Language) {
$Options['lang'] = $Language;
}
~~~
I've shortened
~~~
if (!in_array($Language, $Whitelist)) {
...
}
if ($Language) {
$Options['lang'] = $Language;
}
~~~
to
~~~
if (in_array($Language, $Whitelist)) {
$Options['lang'] = $Language;
} else {
...
}
~~~
and kicked out the now unneed
~~~
} else {
$Language = false;
~~~
Thanks @peregrine for [making me …
=> Add BeforeCaptcha event to easily enable custom captchas

plugins/Facebook/class.facebook.plugin.php
Facebook avatars get distorted when you post, so everyone's face is squishy. As an example, compare the following two images, where the left is the incorrect forum behavior, and the right is what it should be:
This is due to an incorrect API call. We're using `//graph.facebook.com/[userid]/picture?type=large`, which yields a rectangular image in which the longest dimension is 200px. When we try to resize it to 50x50, the aspect ratio changes and faces get squishy.
What we really want is a "large"-size image that's square. Using `//graph.facebook.com/[userid]/picture?width=200&height=200` yields the correct behavior.
=> Fix incorrect Facebook API call leading to "squished" avatars

plugins/Facebook/class.facebook.plugin.php
When using Facebook connect, Vanilla tries to obtain the user's email, but doesn't succeed due to a malformed API call.
As a result, FB connect doesn't work as expected: it connects your FB account, but then requires you to manually type in your email and username again. This is particularly problematic in that it completely nullifies the "Use Facebook names as usernames" option. The user is forced to manually type in a username.
The problem is calling /me without specifying any fields. The default action is only to return the name and id. By specifying fields=name,id,email, the problem is completely solved.
Detailed writeup here: http://vanillaforums.org/discussion/31226/bugfix-facebook-connect-does-not-auto-pull-email-address-due-to-incorrect-api-call#latest
=> Fix Facebook API call to pull email

applications/dashboard/views/entry/connect.php
Sometimes a person will use Facebook Connect with an account that doesn't have a primary email associated with it. When this happens, Vanilla detects that there's no email, and renders a quick form to have the user type in their email. However, the form in question also makes the user reenter their username - even if there's already a valid username entered and stored in ConnectName.
This is mainly unfortunate if someone has the "Use Facebook names for usernames" setting enabled, because it completely negates it by asking the user to enter another username.
To be clear, here's what happens, even if "Use Facebook names for usernames" enabled.:
The solution is as simple as checking if ConnectName is set before displaying the Username box:
The other textboxes on the page have this sort of …
=> Preserve ConnectName when asking for email

applications/dashboard/js/entry.js
Found this typo in a JQuery selector in entry.js. I'm not sure what effect it has, but I'm pretty sure it's not supposed to be there.
=> Fixed "#ConectPassword" typo in entry.js

applications/dashboard/controllers/class.settingscontroller.php
Currently you can accidentally put a space before or after an IP address, which will then match no IP addresses. That's super frustrating and stupid.
=> Trim ban values to avoid mismatches later

applications/vanilla/settings/class.hooks.php, applications/vanilla/settings/configuration.php, applications/vanilla/settings/structure.php, applications/vanilla/settings/stub.php, bootstrap.php
* Missed casening, prune dead code, and fix some docs in Vanilla hooks.
* Fix `<?php if (!defined('APPLICATION')) exit();` on a few nearby files from codesniffer.
* Cleanup some comments, casening and spacing in bootstrap.
=> Cleanup the Vanilla hooks file & bootstrap

library/core/class.form.php
If the label is wrapped around the input, the 'for' attribute is unnecessary. Fixes issue where multiple forms on the same page have conflicting labels.
=> Remove 'for' attribute for wrapped radio inputs.

library/core/class.format.php
The change from #2694 doesn't work if the code block is multiline.
```
<code> @JasonBarnabe :) :smile:
line 2 #search <img src="http://site.com/example.gif" /> </code>
```
[One little "s"](http://php.net/manual/en/reference.pcre.pattern.modifiers.php) fixes this.
=> Protect multi-line code blocks from formatting

library/core/functions.general.php
Improve the decho function
1. Prepend the file and line from which the function was called from to the output.
2. Replace "falsy" values by their string representation wrapped by "safePrint{}". This is done to circumvent the fact that print_r (and echo) print nothing for [false,null,0,(empty string)] and we cannot easily know what is the value when nothing is printed. (Also true become 1 so it's replaced as well)
=> decho function enhancement

applications/dashboard/design/style.css, index.php
Fixes issue where the group banner's clearfix interferes with the floating panel and where the new discussion button is missing from the group page.
=> Tweak Baseline+ theme to work better with Groups

applications/dashboard/controllers/class.importcontroller.php, applications/dashboard/models/class.importmodel.php, applications/dashboard/views/import/go.php, applications/dashboard/views/import/info.php
The import UI uses styled anchors as buttons when stepping through the process, so the requests are not form posts.  `isAuthenticatedPostback` checks were causing all attempted imports to fail, because of this.
This PR adds the CSRF token into the URL for `ImportController::go` and `ImportController::reset` and checks for them, in addition to the existing `isAuthenticatedPostback` behavior.  In addition, this update makes the user's current CSRF carry through the import process.  This is because the user's `TransientKey` is reset when the "Insert Users Table" step is performed, thus breaking all `validateTransientKey` checks that follow.
=> Updates TK check in import

library/core/class.session.php
CSRF validation is currently done with loose comparisons.  This PR updates the CSRF validation to use strict comparison to verify identical types and values.
=> Validate TransientKey with strict comparison

applications/dashboard/views/settings/helper_functions.php
This PR updates the Vimeo API calls to use JSON, instead of the existing PHP code/unserialize method.
=> Updates getTutorials to use JSON for Vimeo

library/core/class.form.php
Revises 237c4339b0181f5c4d838a8ead351d35b4c47c43 to use purification instead of escaping. As @hgtonight points out, this disabled links in error messages even internally, which are useful and good UI. Needs to be reevaluated against the security condition that prompted the change in the first place.
=> Filter form errors rather than htmlspecialchars

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/views/user/index.php
* Add a new "megasite" threshold for user total (in addition to existing lower "userthreshold").
* Always show a user total when not searching for users. For megasites, we approximate based on table status. Everyone else gets an accurate count. Previously, only sites below userthreshold got any total for this.
* Preserve "next/last" pager with no count for searches once we cross the userthreshold.
* Fix plural case for "X users found." to not hedge with (s).
=> Restore user count to default user list

applications/dashboard/models/class.rolemodel.php, applications/dashboard/models/class.usermodel.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, library/vendors/Smarty-2.6.25/libs/Smarty.class.php
In PHP 7, methods of subclasses must match the base class. We’ve got a few methods that don’t follow this and they should.
=> Fix class definition notices

applications/dashboard/controllers/class.activitycontroller.php
This update implements authentication for activity comments.  In addition, it verifies the activity ID before attempting to post the comment.
=> Revise permission check on activity comment

applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/views/profile/user.php
Remove event firing connect method, as Connect plugins create their own endpoints.
Also check for authenticated posts on clear method and remove transient key from clear url.
=> Postback checks and tweaks in Profile controller

applications/dashboard/controllers/class.entrycontroller.php
The {username} variable is always available in log events.
=> Fix a typo in the password_reset event

library/core/functions.general.php
Log a warning when `openssl_random_psuedo_bytes()` isn’t available or not cryptographically strong. Also add an additional fallback to `mcrypt_create_iv()` for systems that have the mcrypt extension, but not open SSL.
=> Log a warning when random number generation is weak

applications/dashboard/controllers/class.embedcontroller.php, applications/dashboard/settings/class.hooks.php, applications/dashboard/views/embed/advanced.php
Vanilla explicitly avoids forced embedding of a forum when viewing on a mobile device.  This update removes that restriction, allowing mobile browsers to also be forced into embedding.
I'm not sure if this was put in place 3+ years ago for UE or compatibility.  I didn't run into any issues with compatibility and I figure the UE for this kind of advanced implementation should be the responsibility of the admin/developer/designer, if they want to pursue it.
=> Allow forced embed on mobile

applications/dashboard/views/profile/index.php
There is a difference in how files are rendered in Vanilla. Sometimes you find `include($this->fetchViewLocation('ViewName'));` and sometimes `echo $this->fetchView('ViewName');`.
Only `fetchView()` handles template files; `fetchViewLocation()` only includes php files.
Since all Vanilla views are php files, this is no problem. Only when a plugin generates a part of a view, this restricts the plugin author. With `profileController->setTabView()` you have the chance to reuse a normal profile page and insert only a small piece of content to it.
But all tab views are inserted through a `include fetchViewLocation()` before the complete (php!) view is handed over to `fetchView()`. Therefore, using a Smarty template for a profile tab added by a plugin, will fail since it is not treated as a …
=> Empower Profile Tabs to Use Smarty

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/js/bans.js, applications/dashboard/views/settings/banstable.php, js/library/jquery.popup.js
How the "delete ban" workflow currently happens:
1. User clicks "Delete" on a record row on /settings/bans.
2. User clicks "Okay" in the popup to confirm the deletion.
3. `SettingsController::bans` checks to see if `isAuthenticatedPostback` and fails, because the request is not sent with POST, nor does it contain the session's `TransientKey`.
This update adds the transient key to the delete link by way of the `Gdn_Theme::link` function and has `SettingsController::bans` check for a valid transient key in the URL parameters before committing the deletion.
=> Fix CSRF check when deleting a ban

plugins/editor/class.editor.plugin.php
This update removes the exception for `Html` for being reinterpreted as `Wysiwyg` in Advanced Editor.
Re: https://github.com/vanilla/vanilla/pull/3393#issuecomment-165848168
=> Remove Html exception for Wysiwyg reinterpretation

applications/dashboard/controllers/class.dbacontroller.php, applications/dashboard/controllers/class.logcontroller.php, applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/controllers/class.searchcontroller.php, applications/dashboard/views/search/index.php, library/core/class.form.php, library/vendors/SmartyPlugins/function.searchbox.php, plugins/OpenID/class.openid.plugin.php, plugins/Tagging/class.tagging.plugin.php
This is a rebase of #2964.
- Allow empty form element names.
- Fix escaping and unescaping of form field names.
- Remove unused Gdn_Form->InputPrefix.
- Fixes http://vanillaforums.org/discussion/30583/gdn-form-associative-arrays
Related issue: #2963
=> Fix Gdn_Form Field Name Handling

applications/dashboard/controllers/class.profilecontroller.php
Profile tabs get the css class "Active" based on a loop in views/profile/tabs.php:
~~~
foreach ($SortOrder as $TabCode) {
$CssClass = $TabCode == $this->_CurrentTab ? 'Active ' : '';
~~~
Therefore this cheek needs not to be here.
Moreover, if you add a profile tab with no class at all, it gets the class "Active Active".
Problem is solved if the check for the active tab is deleted in addProfileTab()
=> Delete duplicate check for active profile tab

applications/vanilla/models/class.discussionmodel.php
`$Discussion ` is not passed by reference all the way through the calls beginning from the `getWhere()` method; the discussion data cannot be modified from the `SetCalculatedFields` event when the `getWhere()` method is used when it should be able to.
Currently, you can workaround this by running the code via the `AfterAddColumns` (adding fields via a for loop), but it should be able to be done via the method described above as well.
---
For example, this code: https://github.com/austins/Vanilla-App-Articles/blob/54e2b0d59ec60caeac75920d1b8750c0d6ba49bb/settings/class.hooks.php#L57
The discussion can't be modified unless the reference operator is added.
=> Ensure $Discussion is passed by reference in calculate()

plugins/editor/views/attachments.php
When downloading an attachment, this will retain the actual filename (as opposed to a random string).
Note, that this will also show the download prompt for image files.
[More info on the download attribute](https://davidwalsh.name/download-attribute)
=> Editor: Use the actual file name for attachment downloads

applications/dashboard/controllers/class.usercontroller.php
Change the behavior where posting to the UserController with an invalid transient key will now throw a CSRF exception. Previously the endpoints would fall through to the GET behavior which always appears as some other bug when being called from an API context.
=> Throw CSRF errors on the user controller

library/core/class.format.php
Users can paste the direct link for their video for example
https://adrianwebpm.wistia.com/medias/3ydyjg4ynu
I am using their embed with auto-responsive size.
There is also an option to embed with this code per Wisita :
`<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding"    style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_3ydyjg4ynu videoFoam=true" style="height:100%;width:100%">&nbsp;</div></div></div>`
Not sure what we can do if people paste this code directly. 3ydyjg4ynu seems to be the only indicator of the video.
=> Adding Wisitia Embed

applications/vanilla/controllers/class.settingscontroller.php
See https://github.com/vanilla/vanilla/pull/3294
Fixes the "add" case.
=> Strict mode compatibility for addCategory

plugins/Tagging/class.tagging.plugin.php
- FIX: view not found for RSS feed if table layout is active
- FIX: defective link in breadcrumbs if vanilla is installed in sub directory
- see http://vanillaforums.org/discussion/31419/bugfixing-rss-feeds-for-tagging-plugin-in-vanilla-2-2
=> Fixing RSS Feed and Breadcrumbs

applications/dashboard/models/class.updatemodel.php
Need to add a License field check to analyzed addons. To do this would duplicate code in 4 places, so we abstract it (along with the Description and Version checks) to new method `checkRequiredFields()` and use its results to detect failed validation.
=> Pass license info when analyzing an addon

applications/vanilla/controllers/class.postcontroller.php
Spaces in field names need to be replaced with underscores because of https://github.com/vanilla/vanilla/commit/4435940f8c486ab1c473e8245e8e34be26f8c373
fixes #3411
=> Fix draft saving

library/core/class.session.php
Add an event to the start of a user's session to act as a counterpart to the [end event](https://github.com/vanilla/vanilla/blob/a4ddd914389ce34ffead54dbbf40a8ecb7b4b717/library/core/class.session.php#L184) in `Gdn_Session`.
=> Add start event to Gdn_Session

applications/conversations/controllers/class.messagescontroller.php, applications/conversations/models/class.conversationmessagemodel.php, applications/conversations/models/class.conversationmodel.php, applications/conversations/modules/class.inboxmodule.php, applications/conversations/modules/class.inthisconversationmodule.php, applications/dashboard/controllers/class.activitycontroller.php, applications/dashboard/controllers/class.notificationscontroller.php, applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/controllers/class.rolecontroller.php, applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/models/class.activitymodel.php, applications/dashboard/models/class.banmodel.php, applications/dashboard/models/class.messagemodel.php, applications/dashboard/models/class.rolemodel.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/modules/class.morepagermodule.php, applications/dashboard/modules/class.recentactivitymodule.php, applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/controllers/class.discussioncontroller.php, applications/vanilla/controllers/class.discussionscontroller.php, applications/vanilla/controllers/class.draftscontroller.php, applications/vanilla/controllers/class.moderationcontroller.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/models/class.draftmodel.php, applications/vanilla/modules/class.draftsmodule.php, library/core/class.model.php, plugins/SplitMerge/class.splitmerge.plugin.php, plugins/Tagging/class.tagging.plugin.php
This will get rid of PHP 7 notices and allow us to use our models in a more OOP way.
=> Refactor methods to match base class signatures

library/core/class.cookieidentity.php, library/core/functions.compatibility.php, library/core/functions.general.php
- Remove the custom implementations of hash_hmac in favor of the built in function.
- Deprecate compareHashDigest() in favor of hash_equals().
=> Remove Gdn_CookieIdentity::_hash()

applications/conversations/models/class.conversationmessagemodel.php
getNew() used get() before, so it should use getRecent() now.
=> ConversationMessageModel refactor error

applications/conversations/js/conversations.js, applications/dashboard/js/activity.js, applications/dashboard/js/applications.js, applications/dashboard/js/import.js, applications/dashboard/js/profile.js, applications/vanilla/js/discussion.js, applications/vanilla/js/post.js, js/global.js, js/library/jquery.gardenhandleajaxform.js, js/library/jquery.gardenmorepager.js, js/library/jquery.popup.js, library/core/class.controller.php
This is a rebase of #3038.
- Remove base64-encoding / decoding of informMessageStack
- Remove base64-encoding / decoding of json-encoded Data
- Remove error prone UTF8-encoding / decoding functions
- Remove error prone base64-encoding / decoding functions
- Deprecate $.postParseJson()
=> Remove base64-encoding of JSON data

applications/dashboard/models/class.spammodel.php, applications/vanilla/models/class.discussionmodel.php
Currently, marking items in the spam queue as Spam is broken.
=> Fix spam deletion by using updated method

applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/controllers/class.categorycontroller.php, applications/vanilla/controllers/class.discussionscontroller.php
The default `Cache-Control` header does not include `no-store`, which can cause issues (e.g. inaccurate unread status or new comment counts) when users visit the discussion list via the browser's back button. This update adds `no-store` to the `Cache-Control` header sent by `DiscussionsController`.
Fixes https://github.com/vanilla/vanilla/issues/3056
Issue originates from https://github.com/vanilla/vanilla/pull/2948
=> Add no-store header to DiscussionsController

applications/vanilla/controllers/class.postcontroller.php
This update adds special considerations for formatting the body of embedded comments.  Since advanced editing capabilities aren't present when adding a comment in the embedded form, we may need to run the body through special handling to ensure the intended display is maintained (e.g. newlines).
Fixes https://github.com/vanilla/vanilla/issues/3430
=> Improve saving of embedded comments

library/database/class.sqldriver.php
I just wanted to change the order of a database result and added `orderBy('...', 'ASC')`. This didn't work an took me several hours to find out why. It's because only `asc` is accepted and `ASC` is changed to `desc`.
Since that's confusing and not documented, I propose this tiny change.
=> Fix order direction in SQL driver

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/models/class.usermodel.php, library/core/functions.render.php, plugins/ProfileExtender/class.profileextender.plugin.php
Writing these queries manually has grown tiresome. This is a simple endpoint that dumps a CSV file of some standard user fields + all their Profile Extender data. Admin-only, and we size-check the user table before proceeding.
* Move user table size calculating from UserController to UserModel (for accessibility, but also because duh).
* Add a new `exportCSV()` function for rendering.
* Add utility endpoint on the Profile Extender plugin for exporting all custom user data.
* Fix issue in Profile Extender where database field size in UserMeta can truncate the Name, causing it to be disjointed from config-saved value (thereby corrupting the data, essentially).
=> Add CSV export for Profile Extender's extra fields

library/core/class.proxyrequest.php
This update corrects a casening error (`$this->responseBody` should be `$this->ResponseBody`) in ProxyRequest.
=> Fix casening error in ProxyRequest

applications/vanilla/models/class.discussionmodel.php
In the table layout for discussions, the column for the newest comment is not displayed correctly, if there is no comment. This can be solved by changing the calls to methods working on the user data of the discussions.
For more details and an alternative solution see http://vanillaforums.org/discussion/31381/discussionstable-display-error-if-there-is-no-comment
This should also fix #3397
=> Fix newest comment data for zero-comment discussions in table view

applications/dashboard/controllers/class.dbacontroller.php, applications/dashboard/models/class.importmodel.php, library/core/functions.general.php
I had a really big import to do and it died after a while.
I found this in my error log:
```
016/01/26 13:14:51 [error] 26764#0: *34 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 600 seconds exceeded in /var/workspace/htdocs/vanilla/applications/dashboard/models/class.importmodel.php on line 1590
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/workspace/htdocs/vanilla/index.php:0
PHP message: PHP   2. Gdn_Dispatcher->dispatch() /var/workspace/htdocs/vanilla/index.php:44
PHP message: PHP   3. call_user_func_array() /var/workspace/htdocs/vanilla/library/core/class.dispatcher.php:326
PHP message: PHP   4. ImportController->go() /var/workspace/htdocs/vanilla/library/core/class.dispatcher.php:326
PHP message: PHP   5. ImportModel->runStep() …
```
=> Fix that only allows increase of max_execution_time.

library/core/class.controller.php, tests/Library/Core/ControllerTest.php, tests/phpunit.php
Currently, only the method `data` is using the dot-notation while the method `setData` is not.
Therefore a value set by `setData("meta.name", "Vanilla")` cannot be recovered by `data("meta.name")` using the same key `meta.name`.  The only way to get this value back was to access the public `Data` attribute directly like `Data["meta.name"]`.
This PR adds the dot-notation to setData so that both `setData` and `data` have the same behaviour.
The original behaviour of `GDN_Controller::setData()` remains unchanged.
Only consequence though, if one was calling `Data["meta.name"]`, the call would have to be rewritten to `Data["meta"]["name"]`.
=> Add dot-notation behaviour to controller method 'setData'

applications/dashboard/views/entry/signin.php, library/core/class.form.php
fixes #3429
In this context, this pull request also
- introduces boolean HTML attributes for form elements (required for `autofocus` attribute)
- adds `wrap` to `ReservedAttributes` an hence removes it from the output. `Wrap` is used internally as virtual attribute and is not in standard HTML.
=> Adds auto-focus on username field when loading /entry/signin

js/global.js
This update adds a JavaScript event to `gdn.stats`, allowing handlers to attach to when a call is made to `/settings/analyticstick`.  This will allow add-ons to use existing code to determine if and when custom analytics JavaScript should be triggered.
=> Add analytics event to JavaScript

library/core/class.theme.php
Currently, `Garden.Logo` = `http://example.com/path/to/logo.png` works, but `//example.com/path/to/logo.png` does not. This fix detects schemaless URLs before trimming the leading slash.
=> Fix logo to allow schemaless full URLs

applications/vanilla/controllers/class.discussioncontroller.php
If the CountComments in the UserDiscussion table ever gets ahead of the total number of comments, this sets the latest comment to the last comment in a discussion.
=> Ensure our LatestItem data is never greater than the total number of comments.

applications/conversations/models/class.conversationmodel.php, applications/dashboard/models/class.activitymodel.php
Especially with HTML emails, the activity notification can make it look as if the forum is sending the conversation message to the user, rather than another user. This preserves the 'username sent you a message' headline and appends the conversation subject to the body. 
It also updates the email call to action text and allows future activity items to update this text, as well.
=> Update conversation activity headline.

applications/conversations/controllers/class.messagescontroller.php, applications/conversations/modules/class.inthisconversationmodule.php, applications/conversations/views/modules/inthisconversation.php
We're cramming an object directly into the Data property of a module but then checking if it's an array before actually settings it.
Or we could just use our proper conventions and make this all easier.
Fixes bug where (surprise) InThisConversation has just stopped appearing globally. We probably made a low-level change to our data handling somewhere that's causing this to appear now.
=> Make InThisConversation module store data sanely

library/core/class.dispatcher.php, library/core/class.router.php
This update adds a new route type: drop.
A request matching a route of this type will immediately be killed.
Closes #3524
=> Add "Drop" type to routes

applications/conversations/settings/structure.php
Solves issue where starting a conversation with a new user when the database is in strict mode causes an error. Addresses https://github.com/vanilla/vanilla/issues/3465
=> Add default null to Conversations Contributors column to comply with strict mode.

applications/vanilla/views/discussions/helper_functions.php
Mostly useful to stop warning from showing if you use the helper functions outside of discussions.
=> Assume ShowOptions is false if the property is not defined on the sender.

library/database/class.sqldriver.php
There is no `$this->Options` and from the context it is obvious that it must be `$this->_Options`.
The only time this array is really used is in class sqldrivers query method, but it is only checked for a value "Slave". So only if someone explicitly queries a slave connection, that error might show up.
=> Fix Typo in Variable Name

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/js/entry.js
If somebody is connecting to a Vanilla account that already exists, we need their password to confirm that they can connect to the existing Vanilla account. Currently, the ajax username checking is tied to the blur event and if the user just hits the 'Connect' button after they type in an existing username, the password field never shows up. But the validation sees an empty password field.
This checks the username on keyup to see whether the username exists or not and adds the password field if necessary. It also adds a helpful message indicating so.
=> Add messaging to inform user if username exists and check on keyup.

library/core/class.form.php
Allows for sending info about whether a checked is selected.
Also fixes return variable name in checkbox function.
=> Pass along the options for a checkbox in the simple function.

applications/dashboard/library/class.emailtemplate.php, applications/dashboard/library/interface.iemailtemplate.php, library/core/class.email.php
This PR removes coupling between Gdn_Email and EmailTemplate classes in the dashboard application, and adds an IEmailTemplate interface to mediate the replacement of EmailTemplate with other versions with different functionality.
=> Remove coupling and allow overriding EmailTemplate

library/core/class.format.php
This update to Wistia allows embedded videos to be started at a specific time by appending the `wtime` parameter to the end of video URLs (e.g. `?wtime=10s`).
=> Update Wistia embed formatting

applications/dashboard/controllers/class.settingscontroller.php
I have added that event to themeOptions() as well as mobileThemeOptions() and I have decided to use the same name, because both methods change the same part of the config.
Based on that discussion: https://vanillaforums.org/discussion/31730/theme-options-capability I have seen that there might be a need to react on theme option changes immediately.
Adding hooks on themeOption changes doesn't influence runtime performance of the forum as such, so I think they are uncritical.
=> Add event 'AfterSaveThemeOptions' to allow reacting on theme option changes

library/core/functions.general.php
Let the join-er decide whether to check category permissions.
=> Optionally opt out of category permission check in joinRecords

applications/dashboard/controllers/class.profilecontroller.php
Fixes issue where session-specific components do not update when users sign in or out.
See https://github.com/vanilla/vanilla/pull/3471
Issue originates from https://github.com/vanilla/vanilla/pull/2948
=> Add no-store header to profile controller for signed-in users.

applications/dashboard/models/class.attachmentmodel.php, applications/dashboard/models/class.rolemodel.php, applications/dashboard/models/class.usermodel.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.draftmodel.php, library/core/class.form.php, library/core/class.model.php
The function is deprecated because it too closely matching the unset() language feature.
=> Remove calls to removeKeyFromArray()

plugins/Flagging/views/reportemail.php
E-mail notifications from the Flagging plug-in have been broken since https://github.com/vanilla/vanilla/commit/54f25f33af8c93d95acfa50dd9dd8182d8fa92f1.  This is due to the e-mail view previously referencing the controller's data array, directly, instead of through its `data` function. The data slugs are converted into multi-dimensional arrays when going in with `setData`, while the e-mail view expected the slugs to remain in the dot-notation format.
This update cleans up the e-mail view a little bit and updates it to use the controller's `data` function.
=> Cleanup Flagging e-mail view

themes/default/README.txt
It was still showing `default.master.php` instead of `default.master.tpl`.
=> Update default master extension in default themes README

js/embed.js
If you're navigating an embedded site and happen to use your browser's back button to move all the way up to the root of the forum, a 404 error is encountered.  This is because of an issue in `checkHash` within embed.js that can allow the request path to be set to an empty string (`?p=`) and that doesn't Jive with Vanilla.
This update adds a default value of `/` to `checkHash`'s path polling.
=> Add default value for checkHash in embed.js

library/core/functions.general.php
`strtolower($Needle)` was called inside of the comparing foreach loop. If it is converted to lowercase outside of the loop it needs only to be done once.
=> Optimize arrayValueI()

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/js/entry.js, applications/dashboard/views/entry/connect.php
Create a functionality whereby a forum can add a line in their config that would stop users who are connecting through SSO from claiming an existing user by entering the username and password.
=> Add AllowConnect setting to optionally disable SSO connecting to existing accounts

library/core/class.form.php
This PR is a better alternative than https://github.com/vanilla/vanilla/pull/3554
With this new event we won't need to modify every view that use the function to enable plugins to filter down the categories.
=> Add a new event that allows to filter down the categoryDropDown input

applications/dashboard/modules/class.headmodule.php, library/core/class.format.php
The meta description in the header of a discussion is derived from the beginning of the discussion text and therefore often contains linebreaks. However, these should not be included in the meta description tag. Therefore, a new helper function `Gdn_Format::reduceWhiteSpaces` is introduced and used by the `HeadModule`.
If you don't think, this function will be ever used anywhere else, then I can move it's functionality directly into the `HeadModule`.
=> Remove linebreaks in meta description

applications/vanilla/models/class.discussionmodel.php
Filters should be registered as soon as they are requested.
=> Move the DiscussionFilters event to its appropriate place

plugins/editor/js/editor.js
This update hides the Advanced Editor toolbar when previewing a comment.  When the "Edit" button is clicked, the toolbar is restored.
=> Hide editor toolbar when previewing

library/core/class.markdownvanilla.php
This update makes sure the Markdown handling functions are properly weighted by priority before transformations are done.  This necessary, because our Markdown library only sorts by priority in its constructor.  We potentially add additional handlers after this, but their priority is never accurately accounted for.  This leads to behavior like quotes disrupting the markup before spoilers can be run.
=> Update MarkdownVanilla to sort gamut by priority

applications/vanilla/js/discussion.js
This update improves the draft deletion handling in the `clearCommentForm` JavaScript function.  By default, comment drafts are deleted (as they always have been).  However, drafts will not by deleted if `clearCommentForm` is initiated from a "Post Comment" button, because the draft is already deleted by the `/post/comment` endpoint.  A second parameter, `deleteDraft`, has been added to allow overriding this behavior.
=> Update clearCommentForm draft deletion

applications/dashboard/views/profile/connections.php, applications/dashboard/views/social/manage.php
This PR: https://github.com/vanilla/vanilla/issues/2102 fixed a typo, but broke the connect pages. This PR removes a rule that never should have existed.
=> Fix weirdness with connect pages.

applications/dashboard/modules/class.navmodule.php
Make the check for exit criteria as early as possible so that empty groups will cost "no" time.
=> Micro performance tweak for NavModules renderGroup()

library/core/class.autoloader.php
Last element of array has been CONTEXT_CORE and I cannot tell if it shouldn't be still there. I simply guess that there would have been a serious breakdown if it would be needed here. Therefore it is the remaining comma has to be corrected.
=> Fix typo in Autoloaders $contextOrder array

library/core/class.session.php
API calls force a valid CSRF key and should not log a CSRF failure.
=> Don’t report a CSRF failure when forcing a valid CSRF

applications/dashboard/design/cropimage.css, applications/dashboard/design/style.css, applications/dashboard/scss/legacy/_style.scss, themes/2011Compatibility/design/custom_red.css
When attempting to crop a photo thumbnail, the full-size image has an opaque gray box overlay.  This makes it so you can't see what you're actually cropping.
This update removes some styling rules that were causing the box to be fully opaque.  The cropping box should now be semitransparent.
Closes #3425
=> Fix opaque photo cropping box

applications/dashboard/controllers/class.entrycontroller.php
Let begin by saying
---
The logic of the connect function _should_ be refactored/simplified!
A bit of context
---
When Garden.Registration.NameUnique is set to true and a user tries to connect through SSO using a name that already exist in the forum we give 2 options:
Appropriate yourself the user by providing its password or use a different name.
There is a bug with the latter option... We are always told that the new chosen name exist.
That new name is provided via the field "ConnectName" which is what we use to check that this new name is not already existing. All this is correct. 
But we then create the user using the "Name" field. Which is the name that already exist in the DB and got us to provide a ConnectName in the first place.
In short
---
When registering a user on connect we …
=> Register user using connect name when provided

library/core/class.format.php
- The `replaceButProtectCodeBlocks` method will handily protect the contents of `code` elements from the formatting methods, but it only works with a plain `<code>` element - it cannot have any attributes on it.
- If the code output uses a class name, which my markdown parser does to add language information (GFM) for the syntax highlighter then the code block is no longer protected.
- For example:
\`\`\`js
...
\```
would result in:
\<code class="language-js">
...
\</code>
- This change allows the element to have attributes
**edited** Formatting
=> Consider `code` elements with a class name when protecting code blocks

library/core/class.format.php
This PR address the NBBC addon sometimes breaking search results. This fixes [vanilla/addons#268](https://github.com/vanilla/addons/issues/268) and will work better than [Wrap Format() return in html_entity_decode() #269](https://github.com/vanilla/addons/issues/269). 
I move the logic to remove list items from plainText() into its own function and then enhanced the regex to remove html list items and encode list items.
=> Fix NBBC sometimes breaking search results

bootstrap.php, library/core/functions.error.php
Remove the side-effects from this file so that it can be more easily used in unit testing and other libraries.
=> Don’t register error/exception handlers in functions.error.php

plugins/editor/views/attachments.php
Fixes issue where image attachments were being downloaded on click rather than being opened in a new tab. Downloading an attachment on click is great if it's a document, but is unexpected if it's an image.
=> Only add the download attribute if the download is not an image.

library/core/class.request.php
The request object double decodes paths somewhere along the way. Since it used urldecode() instead of rawurldecode() a “+” sign in the path would get changed into a space.
The main place where this would happen is with usernames. Put a plus sign in a username and then browse to their profile page.
Whether or not the double decoding itself is a bug is too much of a change to play with here, but since paths are always supposed to use rawurlencode() I think this is a safe fix for now.
=> Fix recognition of plus signs in paths

bootstrap.php
Our custom error and exception handlers are set before those functions can actually be used.  Trying to use them before all their dependencies have been created causes them to throw their own errors.
This update moves `setHandlers` down the bootstrap to the earliest point in which our error and exception handlers are usable.
=> Move setHandlers further down the bootstrap

applications/vanilla/models/class.discussionmodel.php
Scenario 1:
1. Create a discussion.
2. Call the getUnread method in DiscussionModel
Expected : The newly created discussion doesn't appear.
Seen : The newly created discussion is fetched.
PS : Even if you click to view the discussion. It's not set to viewed, I noticed after investigation that the LastDateViewed field is null after the discussion is created.
=> Fixed unread discussion flag when discussion just created

plugins/Quotes/class.quotes.plugin.php, plugins/Quotes/js/quotes.js
There are some inconsistencies about the quotes markup.
You can have "Quote", "Quote UserQuote", "UserQuote".
This PR aim at making all quotes being able to be collapsed.
There is also the possibility of quotes inside a discussion that was not covered before this PR.
Before merging this PR it may be wise to raise an issue about the quotes' inconsistencies in order to fix the source of the problem. 
Something like [this PR](https://github.com/vanilla/vanilla/pull/3606) could be done
=> Allow all quotes to be collapsed.

applications/vanilla/views/discussion/helper_functions.php
No functional change.
* Move doc blocks above function declaration where they belong.
* Add missing doc blocks.
* Break up some too-long lines.
* Casing.
* Hail Lord Brackos!
=> Fix code standards in discussion view helpers

library/core/class.format.php
Fixes a backwards-compatibility issue with the Spoilers plugin rendering BBCode spoiler tags in non-BBCode format posts. Also fixes issue where only the first Spoiler in a post gets rendered properly.
=> Render BBCode-style spoilers in non-BBCode posts.

applications/vanilla/views/discussion/helper_functions.php, plugins/adobe
`getCommentOptions()` use `Gdn::controller()->data('Discussion');` to ultimately check if an user can delete it's own comment. This "data" is not set in the post controller which cause the delete option not to appear in the dropdown.
=> Add Discussion to $sender's data if it is not set already

applications/vanilla/views/discussion/helper_functions.php, plugins/Quotes/js/quotes.js
... before returning it.
After a post edit the editor is sometime refreshed. Let's make sure we have the correct editor in hand before returning it!
=> Make sure the cached editor Element is still in the DOM

applications/dashboard/js/spoilers.js, index.php
Fixes issue where replaceSpoiler function is re-called on all of the spoilers at each ajax load.
=> Don't set spoilerFunctioning property on jQuery object.

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/js/applicants.js, applications/dashboard/models/class.usermodel.php, applications/dashboard/views/user/applicants.php, applications/vanilla/controllers/class.postcontroller.php
Approving applicants is an awful process and always has been. Either you have to wait for the page to reload with the entire applicant list every time you click a button, or you have to pick either "allow" or "deny" and only check those, then do the others in a second batch. AND, if you choose the former, the two links are RIGHT NEXT TO EACH OTHER and in exactly the same style, making it super easy toclick the wrong one, which has absolutely no undo. It's madness.
What's been changed:
* Redo the Applicants page as a table of user data instead of cramming it all in 1 column.
* Add IP address (linked to search) & link the email address.
* Move the Approve / Decline options to the left.
* Make Approve / Decline actions asyncronous - no more pageloads!
* Clicking either option immediately …
=> Applicants v2

library/core/class.format.php
Fixes issue where spoilers destroy search results.
=> Cast simple_html_dom object to a string before returning it.

conf/config-defaults.php, library/core/class.validation.php, library/database/class.databasestructure.php
The timestamp type is very close to the DateTime type, but stores dates internally in UTC which makes for easier conversion when looking at the data internally.
=> Support the MySQL timestamp type

library/core/class.pluginmanager.php
We don't have a convention for plugin names, let this check be case-insensitive.
=> Make checkPlugin method case-insensitive.

applications/dashboard/Gruntfile.js, applications/dashboard/package.json
We can add it back in if we ever need it. Saves us some hassle in the meantime.
=> Remove js concat functionality from Grunt workflow.

plugins/editor/class.editor.plugin.php
Vanilla currently checks to see if an upload is an image before processing it as an image and generating a thumbnail for it.  However, not all images are handled by Vanilla.  GIF, JPG and PNG are the only image types that are processed.  Other images will fail with an error.
This update alters the upload logic to attach other types of images without attempting additional processing, treating them like any other non-image file, instead of throwing an error during the upload.
Closes #2846
=> Limit image processing to valid uploads

applications/vanilla/views/categories/all.php
Every other view that displays comment count, discussion count, view count, etc... uses the combination of `PluralTranslate()` and `BigPlural()` to show numbers formatted as 1.2K instead of 1200. This update to category/all makes it consistent with other views, making styling more predictable for these elements.
=> make category all view's count elements consistent with other views

library/core/class.proxyrequest.php
The HTTP_USER_AGENT has been hard coded as "Vanilla/2.0". I've changed it to always use the version from the config
=> Correct wrong Vanilla version number in class ProxyRequest

library/core/class.proxyrequest.php
When requesting the HEAD of a site that has e.g. multiple "Link:" lines, only the last of those lines made it to proxyRequest->ResponseHeaders array. It is a flat array so `proxyRequest->ResponseHeaders['Link'] = ...` is called for every Link line.
I've made it do a check for double entries and to transform the entry to an array if needed.
=> Make proxyRequest::curlHeader handle responses with multiple identical fields correct

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/models/class.rolemodel.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/modules/class.profileoptionsmodule.php, applications/dashboard/views/user/edit.php, applications/dashboard/views/user/unban.php
There's currently no way to manually remove an automatic ban from a user, such as those applied by ban rules.  This update adds the ability to detect and remove automatic bans from the user, based on bitmask comparisons of their ban flag.  The flags are similarly updated with bitmasks to allow plug-in based rules to remain in place.  A notification messages is displayed when viewing a banned user if the ban may persist or reappear.
This update also addresses two other issues in Vanilla:
1. `UserModel::save` will no longer force a boolean value for the `Banned` field.  Any integer value can be used.
2. `UserController::ban` was using an incorrect bit flag when checking for the type of ban.
Closes #3424
=> Update how user bans attributes are managed

applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/modules/class.userphotomodule.php, applications/dashboard/views/modules/userphoto.php
This update simplifies and unifies checks for `Garden.Profile.EditPhotos`.  Instead of using a half dozen different methods, we now only use one:
```
Gdn::session()->checkRankedPermission(c('Garden.Profile.EditPhotos', true)) || Gdn::session()->checkPermission('Garden.Users.Edit')
```
This check is performed once and saved in an object, where applicable.  This updated check performs the following:
1. Load the config value for `Garden.Profile.EditPhotos`, defaulting to `true`.
2. Pass the config value to `checkRankedPermission`.
3. If the config value is a boolean, use that as the value for the permission check.  If the config value is a string, try to use it as a permission slug and verify the current user has that permission.
4. If `checkRankedPermission` winds up evaluating to false, …
=> Reign in various checks to Garden.Profile.EditPhotos

library/core/class.proxyrequest.php
Setting  $Method => 'HEAD' in request() results in a timeout since the request method doesn't include the head. So it must be handled extra.
=> Allow HEAD requests in ProxyRequest->request()

applications/vanilla/views/discussion/helper_functions.php
Currently, if an empty `$options` array is passed to `discussionOptionsToDropdown` (as is possible in `getDiscussionOptionsDropdown`), an empty value is returned.  This can potentially overwrite the original `DropdownModule` module and break menus on the site.
This tweaks the logic of `discussionOptionsToDropdown` to always return a `DropdownModule` instance.
=> Update discussionOptionsToDropdown return value

library/core/functions.general.php
In my forum, I have several discussions beginning with a short greeting, like:
```
Hi folks,
foo bar is great. Bla bla bla.
```
The `DiscussionController` uses `sliceParagraph` for setting an appropriate `description` in the `meta` tags of the discussion page. Hence, the result is currently `Hi folks,` which is not very useful (and e.g. google webmaster tools complain about a too short description).
Therefore, I propose to add a new parameter `MinLength`. If the found paragraph is shorter than this value, then the string is sliced on a sentence.
In the example, the result will be `Hi folks, foo bar is great.` which has clearly more benefit.
=> add (optional) MinLength for sliceParagraph

applications/vanilla/controllers/class.postcontroller.php
fetchPageInfo  - global function defined  in /library/core/functions.general.php - its purpose to content of html page specified by URL parameter.
For some reason it's name is misspeled as FetchPageInfo - that's why in vanilla comments integration blog posts doesn't get right content and title. In my case i think
=> Fixed misspeled fetchPageInfo

applications/vanilla/models/class.discussionmodel.php
fetchPageInfo  - global function defined  in /library/core/functions.general.php - its purpose to content of html page specified by URL parameter.
For some reason it's name is misspeled as FetchPageInfo - that's why in vanilla comments integration blog posts doesn't get right content and title. In my case i think
=> Misspelled fetchPageInfo Fix.

library/core/class.format.php
Fixes bug where unbalanced spoiler tags break a page's markup.
=> Ensure spoiler opening and closing tags are balanced.

library/core/class.uploadimage.php
The default for PNG compression was set to 0, which is *no* compression.  This was causing PNGs to be tremendously large.
This restores compression to PNGs.  The format is lossless, so this should not affect their image quality.
=> Update Gdn_UploadImage to constant PNG compression

composer.json, composer.lock
We will be adding some PSR-4 namespaced autoloading into the library directory so the class map needs to be more explicit so as not to scan everything when it comes.
=> Make the library class map subdirectories explicit

js/library/jquery.atwho.js
At.js currently has some problems, particularly with WYSIWYG mode.
1. When grabbing the text from a WYSIWYG editor, multiple lines are concatenated into one with no separator, before the pattern matching is done.  This means if you want to start a line with a mention, it's a no-go, because the mention character ends up in the middle of two "words" (e.g. Hello world@vanilla is my name.)
2. After a mention is inserted, the caret/cursor remains inside the mention markup, at least on Webkit-based browsers ([see this similar tale of woe](http://miles-by-motorcycle.com/fv-b-8-665/you-can---t-select-that-----webkit-browser-selections-and-ranges-in-chrome-and-safari)).  The `span` element containing the username also ends up containing all text that follows, even additional mentions. (e.g. How …
=> Address At.js Issues

applications/dashboard/views/activity/popin.php, applications/dashboard/views/profile/notifications.php, applications/vanilla/views/drafts/index.php
We already have two uses of
sprintf(t('You do not have any %s yet.'), t('messages'));
and one of 
sprintf(t('You do not have any %s yet.'), t('bookmarks'));
This brings the other uses of empty state message into compliance with that format, eliminating 2 translations.
=> Unify empty state messages

applications/dashboard/models/class.updatemodel.php
The new requirement for a license field in the addons repository makes it impossible to upload Vanilla and the porter. This fix changes that.
=> Default core and porter uploads to GPLv2 license

plugins/Quotes/js/quotes.js
https://developer.mozilla.org/en/docs/Web/API/Node/contains
https://connect.microsoft.com/IE/feedback/details/780874/node-contains-is-incorrect
document is a node so contains do not work on it in IE.
=> Fix contains method not working on "document" node in IE

applications/vanilla/js/discussion.js
Some JavaScript existed to halt the preview routine if the content was empty.  This can be confusing to some users.  This update removes that condition and allows a preview to be generated, even with no content.
=> Allow preview of empty post

composer.json
Got this notice when validating the composer.json file:
License "GPLv2" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
=> Use a valid SPDX license in composer.json

applications/dashboard/js/entry.js
The prefix causes an issue where private communities can’t access the endpoint because the prefix is not in the dispatcher’s whitelist.
=> Remove the /dashboard prefix from entry.js

applications/conversations/js/conversations.js, applications/dashboard/js/bans.js, applications/dashboard/js/log.js, applications/dashboard/js/messages.js, applications/dashboard/js/previewtheme.js, applications/dashboard/js/profile.js, applications/dashboard/js/routes.js, applications/dashboard/js/search.js, applications/dashboard/js/settings.js, applications/dashboard/js/user.js, js/global.js, js/library/jquery.menu.js
The /application prefix for URLs will soon be deprecated. Removing it where possible helps to prevent future bugs.
=> Remove the /dashboard prefix from js files

applications/dashboard/views/settings/plugins.php, library/core/class.pluginmanager.php
The “Dir” key defines the application root relative directory of the plugin. This is useful to build both file paths and URLs for the plugin’s assets. The “IconUrl” key defines the application root relative path of the plugin’s icon, if any, and can be passed right to asset().
These two keys will be standardized across all addons.
=> Add the “Dir” and “IconUrl” keys to plugin info and use them

applications/vanilla/views/post/comment.php
Fixes issue where role titles were no longer appearing in the comment form css.
=> Pass the form CSS class by reference in the comment form.

applications/vanilla/views/discussion/helper_functions.php
It looks like we lost the ability to dismiss an announcement when we switched over how we build discussion dropdown menus.  This update re-adds the ability to dismiss an announcement.
=> Re-add option to dismiss announcements

applications/dashboard/locale/en.php, applications/dashboard/models/class.activitymodel.php, applications/dashboard/models/class.usermodel.php
The recent HTML email feature stopped using the email translation compound strings in favour of smaller, concatenated translations. This allowed us to split up the email into its components (title, button, etc.) However, it broke backwards compatibility for users with custom email translations. 
This PR addresses that issue in 2 ways:
1. If there is a custom translation for the welcome email body, it uses that.
2. For activity-related emails, adds the ability to prepend a string to the email body, using the 'Garden.Email.Prefix' config setting.
This does not restore backwards compatibility, but addresses the need for users to add custom messages to the emails.
=> Add options for overriding email messages.

applications/dashboard/models/class.messagemodel.php
Do not display messages in the categories  you do not have the Vanilla.Discussions.View permission.
=> Prevent messages from being displayed when you do not have view permission

plugins/editor/class.editor.plugin.php
This would allow plugins to hook into the process before up images are uploaded via the Advanced Editor to perform any operations to the images (i.e. resizing, watermarking, colourization, etc.)
=> Add a hook for manipulating images uploaded in Advanced Editor.

js/global.js, js/library/jquery.atwho.js
\n are replaced by spaces in the atwho.matcher function.
This cause problems with the mention auto-complete feature since space are registered as part of a search. This cause every searches at EOL to have a space appended to them which returns no result in 98% of the cases.
This PR update the code logic to treat \n as EOL.
=> Treat \n as EOL for mentions

applications/dashboard/models/class.importmodel.php
I got an Out of Memory error doing a migration because there was over 700k users with no roles (this is normal in that case).
=> Execute a count(*) query instead of counting the number of returned rows

applications/conversations/settings/class.hooks.php
This solves https://github.com/vanilla/vanilla/issues/3536
I've dropped the session->isValid check, since the permission would also fail for invalid sessions.
=> Check Conversation.Add permission before showing "Message" button on other users profile

js/global.js
Safari utilizes a back-forward cache (bfcache) which keeps a copy of the page's state between clicking the back/forward buttons.  This conflicts with how we want Vanilla to work with caching, since users hitting their browser's back button from a discussion might expect that discussion to appear as "read" in the discussions list.
This update implements a kludge to force a reload on all pages detected to have "persisted" via Safari's bfcache.  Normal browser caching *should* still be in play. We're only forcing a standard page refresh, instead of allowing the browser to hold onto the state of any given page's DOM between back/forward clicks.
=> Add event to dodge Safari's bfcache

.travis.yml, applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/settings/class.hooks.php, applications/vanilla/settings/class.hooks.php, library/core/class.gdn.php, library/core/class.regarding.php, library/core/class.statistics.php
Plugins in core is being deprecated so the couple that are there must be refactored into regular hooks classes.
=> Remove plugins from library/core

applications/dashboard/models/class.rolemodel.php
if RoleModels method `getDefaultRole()` is called with a $type not handled in the switch statement, `$backRoleIDs` is undefined. Merging an array with NULL results in NULL, that's why `$roleIDs = array_merge($roleIDs, $backRoleIDs);` didn't work for `TYPE_ADMINISTRATOR` and `TYPE_MODERATOR`
Adding a default to the switch statement that defines $backRoleIDs solves that.
=> Fix RoleModel::getDefaultRoles for admins and mods

library/database/class.mysqlstructure.php
Allows columns to be renamed when just their casing changes. Currently if you change the casing on a column then a new column will be attempted to be added when really the existing column should be changed.
To see the effect of this PR, change the casing of a column in an applications structure file and then go to /utility/structure.
=> Allow column case changes

applications/vanilla/models/class.categorymodel.php, composer.lock
Our object pollution knows no boundaries. Make sure we really have an array before using it like one, even this deep in the categories collection.
=> Don't let objects creep into makeTreeChildren()

library/core/class.controller.php
This is just to make the page more compact. I noticed this data gets really long on some pages.
=> Don’t pretty print gdn.meta

applications/dashboard/models/class.rolemodel.php, applications/dashboard/models/class.usermodel.php
This is slightly backwards incompatible in that it returns a data set with DATASET_TYPE_ARRAY instead of DATASET_TYPE_OBJECT, but since all the calls I searched for request the resultArray() then I’m hoping we can get away with leaving this as is.
This should help close #3686.
=> Use caching in RoleModel->getUserByID()

applications/dashboard/views/deverror.master.php, applications/dashboard/views/error.master.php, library/core/class.locale.php, library/core/class.smarty.php, library/core/functions.error.php, themes/2011Compatibility/views/default.master.tpl, themes/EmbedFriendly/views/default.master.tpl, themes/bittersweet/views/default.master.tpl, themes/mobile/views/default.master.tpl
This update ensures all pages have a `lang` attribute on the HTML tag that reflects the site's currently configured locale.
Closes #3698
=> Add and update lang attributes on HTML tags

applications/vanilla/models/class.categorymodel.php
The event CategoryWatch has been fired as an event of the plugin manager. This one closes this issue: https://github.com/vanilla/vanilla/issues/1914
=> Fire "CategoryWatch" as an event of CategoryModel

applications/vanilla/models/class.discussionmodel.php
`DiscussionModel::getAnnouncements` potentially attempts to pass an array value to `Gdn_MySQLDriver::where`, which will throw the following error: `Gdn_SQL->ConditionExpr(VALUE, ARRAY) is not supported.`
This update alters the logic of `DiscussionModel::getAnnouncements` to pass the `$CategoryID` to `wherein` if its value is an array.
=> Update category checking in DiscussionModel::getAnnouncements

applications/dashboard/views/deverror.master.php, applications/dashboard/views/error.master.php, library/core/functions.error.php
The Gdn::locale() might not be available when errors occur so it should not be referenced in those scenarios.
=> Rollback overzealous language attributes

applications/dashboard/models/class.usermodel.php
There was a previous bug in the cached version of definePermissions where the $serialize argument was not respected. When we fixed that it cascaded to another bug.
=> Fix bug with UserModel->definePermissions and caching

library/database/class.sqldriver.php
`Gdn_SQLDriver::where` currently assumes the presents of an index of 0 when determining whether the value should be handled as a "where" or a "where in".  This can be problematic when the value being passed is an array and there is no zero index.  In that event, the following error may be triggered:
```
Gdn_SQL->ConditionExpr(VALUE, ARRAY) is not supported.
```
This update drops checking for an element with a zero index and, if necessary, retrieves the first value in the array without hardcoding the index.
=> Don't assume zero index in Gdn_SQLDriver::where

applications/vanilla/models/class.discussionmodel.php, library/core/functions.general.php, tests/Library/Core/DbEncodeDecodeTest.php
- The documentation for serialize does not mention triggering any errors so the exception handling has been removed.
- Change exception handling in dbdecode to @ error suppression to prevent notices in the debug bar.
- Fix the deserialization in discussion tags which has a bunch of mixed data.
=> Change error handling on dbencode/dbdecode

composer.json, composer.lock
There is a lot of functionality coming that will all be under the Vanilla namespace. This is PR allows us to run multiple PRs that use it without having to add the namespace every time.
=> Add the Vanilla namespace to composer’s autoloader

library/core/class.passwordhash.php, tests/Library/Core/PasswordTest.php, tests/Library/PasswordTest.php
Attempt to use PHP 5.5’s password_* functions for password hashing and verification unless portable passwords are required.
=> Upgrade to PHP’s password_* functions for passwords if possible

applications/dashboard/design/spoilers.css, index.php
Spoilers are rendered with js and sometimes, especially when users have slower connections, the spoilers can appear before the spoilers are rendered. This assigns the spoiler color to the same color as its background until the spoiler is rendered. 
Using the same color property as the background is favoured over using transparent to give the added bonus of being able to read the text when highlighting it if javascript is disabled.
=> Add css to make initial spoiler text the same colour as its background.

applications/vanilla/models/class.discussionmodel.php
Fixes issue where category-only announcements get removed when there are no global announcements. Fixes #2693.
=> Fix category announcements on recent discussions page

applications/dashboard/views/modules/dropdown.php
Fixes rendering issues when themes and plugins override the sprite function.
=> Use the sprite function to output the sprite in the dropdown view.

applications/dashboard/views/activity/helper_functions.php, applications/vanilla/views/discussions/helper_functions.php, applications/vanilla/views/discussions/table_functions.php, plugins/editor/class.editor.plugin.php
Objects are already references. Declaring them as reference parameters is almost always a bug.
=> Remove double references from functions

library/core/functions.general.php
Add an extra cache-busting hash to the end of asset versions based on the "Garden.Deployed" config setting. The config setting must be a timestamp and is usually set by some mechanism other than the app. When the app encounters the timestamp it gives it a grace period. Before the grace period has passed, the original timestamp is used. Once the grace period is expired then the timestamp + 30 is used. In this way there is a waiting period for race conditions to be resolved on multi-server setups.
Eventually, the versions themselves may be removed in favor of the deployed time entirely.
=> Improve asset cache busting on deployed servers

library/core/functions.general.php
Since the timestamp is set at the beginning of a deploy it must be a bit longer.
=> Increase the asset grace period

applications/dashboard/views/user/users.php, library/core/functions.render.php
This update adds a function to format IP addresses for display.  In addition, it aims to ensure any IP address that might be displayed are done so with either `ipAnchor` or this new function.
Closes #3687
=> Add function to format IP addresses for display

applications/dashboard/controllers/class.utilitycontroller.php, applications/dashboard/views/utility/structure.php, library/database/class.databasestructure.php, library/database/class.mysqlstructure.php
Add an optional alter table row threshold which represents the maximum number of rows a table is allowed to have for an in-application alter to be allowed to run. If a table is too large then the admin is expected to copy the SQL from the structure endpoint into their RDBMS.
By default this threshold is turned off, but may be turned on by config.
=> Implement an alter table threshold

applications/vanilla/controllers/class.settingscontroller.php
Managing a category is related to `Garden.Community.Manage` not `Garden.Settings.Manage`
With this fix users with `Garden.Community.Manage` won't get permission problem when deleting(categories and categories' photo) and sorting categories
=> Use the correct permission in category management actions

js/library/jquery.form.js
The jQuery Form plug-in we use for handling in-page popup window form submissions had some issues with older versions of Internet Explorer.  The issue was addressed, but the version we use does not include that fix.  I've cherrypicked that fix into our version of the plug-in.  I chose not to update the whole plug-in for a couple reasons:
1. The plug-in has been abandoned for about two years.  There are several issues outstanding.  I know what we have works.  I don't know what issues have been introduced and won't be addressed if we go to the new version.
2. The fix is tiny, but the diff between our version and the current version is sizable.  I'd rather make one tiny change with limited impact than risk upgrading the whole library and having it somehow break existing integrations.  If we …
=> Improve compatibility of popup AJAX form submission

conf/constants.php
The cache, conf, and uploads directories are really the only directories that need overriding. The other ones will most likely cause bugs so lets make it clear that we don’t want them overridden in the comments.
=> Make the dynamic paths easier to override

applications/dashboard/models/class.activitymodel.php
Makes sure that the config setting is respected in Activity emails with no message.
=> Ensure Garden.Email.Prefix displays even if there is no email message.

applications/vanilla/models/class.commentmodel.php
`CommentModel` always passes `CommentID` to `SpamModel::isSpam` checks, even when `CommentID` isn't present (i.e. a new comment).  This empty value becomes a 0, which is `RecordID` in the log table, if a SPAM comment is detected.  SPAM comments are grouped by this `RecordID` column.  Once you have one of them in the database, the next new comment being flagged as SPAM will overwrite the original record and the pattern will repeat itself until the 0 record is removed from the database.
This update only attempts to join in `CommentID` if a valid ID is present, which avoids these types of ID collision scenarios.
=> Only use CommentID for SPAM check if available

js/global.js
Emoji are wrapped in span tags when using the WYSIWYG editor.  In addition, sometimes autocompletion of emoji fails to trigger, altogether.
This update aims to strip span tags from the emoji insertion template and make the appearance of the autocomplete menu more reliable.
Closes #3719
=> Update JavaScript insert template for emoji

library/core/functions.render.php, tests/Library/Core/RenderFunctionsTest.php
Allows us to migrate legacy columns without breaking compatibility. Closes #3812.
=> Add fallback prefixes to the userBuilder() function

applications/dashboard/controllers/class.rolecontroller.php, applications/dashboard/models/class.rolemodel.php, library/core/class.model.php
The Gdn_Model->coerceData() method will partially clean up a data array based on the model’s schema. This helps against databases that use MySQL’s strict mode.
Fixes #3507.
=> Add data coercion to Gdn_Model

applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/models/class.usermodel.php, tests/APIv0/APIv0.php, tests/APIv0/StandardTest.php
Allow moderators to set the Photo field to a URL in /profile/edit. This was functionality that was originally removed, but is getting eased back in. Since the photo would be previously filtered out that behavior is being reproduced for non-admins.
There is a cursory check to make sure the Photo field is a valid URL, but built in function isn’t exhaustive. Since this functionality is mod-only I think this is okay for now, but a more robust URL validator will need to be added in the future.
=> Allow the Photo field to be set in /profile/edit

plugins/Gravatar/default.php
Gravatar allows for a [rating](http://en.gravatar.com/site/implement/images/#rating) parameter in image requests.  The Gravatar plug-in does not currently use this parameter, so it defaults to G.
This update adds a new configuration value, `Plugins.Gravatar.Rating `, which will allow users to set the rating threshold of the images Gravatar serves.
Closes #3873
I also rewrote most of the plug-in.
=> Add configurable rating parameter to Gravatar

library/database/class.databasestructure.php, library/database/class.mysqlstructure.php
Since https://github.com/vanilla/vanilla/pull/3605 the property has been set private but is used in the child class (which is now "hiding" the parent property since php allows to declare properties on the fly)
Anyway.. let's just move the property declaration in `Gdn_MySQLStructure` since it is not used in `Gdn_DatabaseStructure`
=> Move member $rowCountEstimates from databaseStructure to mysqlStructure.

library/core/functions.general.php
htmlEntityDecode returns an empty string in PHP 7 because the `e` modifier does not exist anymore.
This cause fetchPageInfo to return empty Title and Description. (Embedding is broken)
=> Remove regex "e" modified since it is deprecated in PHP 7

applications/dashboard/settings/class.hooks.php, index.php, js/embed_local.js
This is a hopefully more simple version of #3672. The query string is set in the controller hooks and then just joined in the path. Only altering embed_local.js helps with cache busting.
=> Pass the query string from embedded pages out to the parent frame

applications/dashboard/models/class.importmodel.php
When we extracted the functionality of inserting a table from a CSV we fixed the condition 'skip_header' to truncating the table which meant that if you wanted to skip a header you could truncate the table, otherwise you couldn't.
=> Allow for optional headers in imported CSV.

applications/dashboard/models/class.updatemodel.php
This method currently does not work. It stops after finding `'APPLICATION'`. This PR changes the logic check to continue to match the new default set in d248335abf9538deea372e87a35405c68c517986. ( #3768)
=> Fix parseCoreVersion()

plugins/Quotes/js/quotes.js
This update removes a `console.log` call from quotes.js.
=> Remove debug code from quotes.js

applications/dashboard/models/class.messagemodel.php, applications/vanilla/controllers/class.discussioncontroller.php, applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/library/class.categorycollection.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/settings/structure.php, applications/vanilla/views/categories/subtree.php, applications/vanilla/views/post/comment.php, library/core/class.memcached.php
Help scale categories for communities with too many categories to iterate every page load. The entire category table is still loaded when necessary so there are only some pages that this optimization will work. Some testing tips:
- The checklist below can be used as a testing checklist too!.
- Make sure you turn off the categories in the side panel when testing this PR.
- In the debug bar, you should see the following message when all categories have been loaded: **CategoryModel::loadAllCategories**.
- If you are seeing the above message all the time then some plugin may be loading all of the categories. It would be helpful to figure out which one and post it here so the plugin can be refactored, if possible.
- It is imperative to test this PR with caching ON.
- There is some messy stuff …
=> Category Scaling Part 1

applications/dashboard/modules/class.headmodule.php
Discovered as a notice on vanillaforums.org.
`file_get_contents(): Filename cannot be empty (/var/www/frontend-f3ee4959f7f61e/applications/dashboard/modules/class.headmodule.php line 424)`
=> Verify we have a Path in HeadModule before attempting to open it as a file

plugins/Tagging/js/tagging.js
When the tag object is built in JavaScript for a post being edited, the mapping is currently reversed: the ID is the name and the value is the ID.  This displays tags as their ID, instead of their label, when editing a discussion.
This update flips the mapping to correctly display the values.
=> Update JavaScript mapping of tag object when editing a post

applications/vanilla/views/discussion/discussion.php
Add the event beforeDiscussionMeta so that we can be able to hook at the same place that every other comments (using beforeCommentMeta) in a discussion.
=> Add beforeDiscussionMeta event to be on par with the comments events.

applications/vanilla/models/class.discussionmodel.php
We added an optimization to `getCount()` in #3875 but did not account for `CategoriesController` behavior of setting that to an array. This patch fixes pagination on `/categories/{slug}` pages.
Fixes #3926
=> Handle a 1-element array in DiscussionModel::getCount()

plugins/editor/class.editor.plugin.php
Visiting `/utility/mediathumbnail/[media ID]` currently throws the following error:
>Using $this when not in object context
This is due to `Gdn_Upload::copyLocal` being called in `utilityController_mediaThumbnail_create` hook of the Advanced Editor plug-in.  This update alters the call to be non-static and also uses `Gdn_UploadImage`, since it's a more relevant class for handling image uploads.
=> Update Gdn_Upload::copyLocal to be called in non-static manner

applications/dashboard/controllers/class.statisticscontroller.php
The statistics re-registration was failing whenever there was an existing ID/secret. You can verify this PR by entering a bogus ID/secret combo to get the bad credentials error and then clicking re-register.
=> Fix statistics registration

library/database/class.mysqldriver.php
Gdn_SqlDriver->delete() didn't support a limit. This addresses that issue.
=> Support delete limits in Gdn_MySQLDriver

applications/dashboard/settings/structure.php
I've replaced the unconditional update statements with a replace statement. They have been executed on **every** /utility/structure run and thus the scan running database structure upgrades always showed something to do which has already been done.
See here: https://vanillaforums.org/discussion/32127/utility-structure-needed-once-upgrade-to-2-2-1-done#latest
=> Prevent unneeded recurring updates in dashboards structure()

library/core/class.format.php
`strip_tags` hates what it perceives to be invalid markup.  When you use a "less-than" sign, followed by a non-whitespace character, it's taken to mean an opening tag.  If you have an opening tag that is never fully completed/closed, you have invalid markup.  When users use "<3" in their messages, `strip_tags` immediately truncates the message just before the "heart".
This is an issue for plain-text e-mails. The message text is cutoff, because it is passed through `EmailTemplate::plainTextEmail`, which then passes the content through to `Gdn_Format::text` where it has a run in with `strip_tags`.  This is also an issue for anywhere in Vanilla which uses `Gdn_Format::text` to display user input.
This update implements a simple routine to convert the opening character of what it detects to …
=> Update Gdn_Format::text to deal with the love bug

plugins/Tagging/class.tagging.plugin.php, plugins/Tagging/class.tagmodel.php
This method should add existing tags to a discussion. It should not wipe out tags that have already been assigned to the discussion.
=> Add TagModel->addDiscussion()

applications/vanilla/controllers/class.postcontroller.php
After editing a discussion you get redirected to the last page (auto offset), which is confusing.
=> Always redirect to the first page after saving a discussion

plugins/SplitMerge/class.splitmerge.plugin.php
If `Garden.ForceInputFormatter` is enabled, the SplitMerge plug-in may be unable to save the discussions it creates with the proper "Html" format.  Since the content SplitMerge generates for these posts contains HTML, this can lead to posts being rendering escaped markup text.  E.g.
```
This discussion was created from comments split from: <a href="/discussion/1/example-discussion">Example Discussion</a>.
```
This update applies a [method taken from ModerationController](https://github.com/vanilla/vanilla/blob/320e922082771a160ddba16f63435cf3cd35ad8c/applications/vanilla/controllers/class.moderationcontroller.php#L417) to temporarily set `Garden.InputFormat` to "Html" if `Garden.ForceInputFormatter` is enabled.
=> Update SplitMerge to overcome Garden.ForceInputFormatter

applications/vanilla/models/class.categorymodel.php
`CategoryCollection` was unable to read from the site config and therefore unable to determine the value of `Vanilla.Categories.NavDepth` because its `config` property was never set.
This update executes `CategoryCollection::setConfig` after the object is instantiated in `CategoryModel`.
=> Pass config to CategoryCollection in CategoryModel

library/database/class.mysqlstructure.php
Vanilla's routine for dropping a column in `MySQLStructure` diffs existing vs target table structure, iterates through the list of columns to drop, then tries to use those column names as indexes in the array it already determined they don't exist in.  Additionally, `$Column` contains details about columns as an array of `stdClass` objects, not just their names.  Trying include a member of `$Column` directly into a string is invalid.
```php
$RemoveColumns = array_diff(array_keys($existingColumns), array_keys($columns));
foreach ($RemoveColumns as $Column) {
$AlterSql[] = "drop column `{$columns[$Column]}`";
}
```
Our current logic can lead to errors like ```Can't drop ``; check that the column/key exists``` when an existing column is being removed from a table.
This update reverts to …
=> Update drop column query builder in MySQLStructure

applications/vanilla/models/class.categorymodel.php
`CategoryModel::filterCategoryPermissions` currently returns an array of input category IDs, filtered by the current user's permissions.  It does this by utilizing `array_intersect`, which maintains the original indexes of the array.  We don't care about the original indexes.  On the contrary, we need the category to have complete numeric indexes.  For example, `Gdn_SqlDriver::where` checks to see if an element with an index of 0 exists.  If it does not, it gets passed off to `Gdn_SqlDriver::conditionExpr`, which can potentially throw a fatal error:
> Gdn_SQL->ConditionExpr(VALUE, ARRAY) is not supported.
This update applies `array_values` to the filtered result of `CategoryModel::filterCategoryPermissions`, which creates new, complete numeric indexes for the resulting array.
=> Reindex result of CategoryModel::filterCategoryPermissions

applications/dashboard/controllers/class.profilecontroller.php, library/core/class.upload.php, tests/APIv0/StandardTest.php
This update adds `Gdn_Upload::isUploaded` to determine if a URL matches a valid type/domain pattern (e.g. `cf://uploads`) provided by an upload plug-in.  This function is then used in `ProfileController::edit` to allow those types of URLs to be saved by users as their photo.
=> Allow users to save upload URLs as photo

applications/vanilla/controllers/class.categoriescontroller.php
-`AnnounceData` is always used as a property of the controller.
-`Announcements` is often requested as data of the controller but was not set.
=> Fix announcements' data assignation in CategoriesController

plugins/Twitter/class.twitter.plugin.php
If the Twitter plug-in is enabled directly via the config, the `UserAuthenticationProvider` is never added, because `setup` is never run.
This update moves inserting the `UserAuthenticationProvider` record to the plug-in's `structure` routine, which will allow it to be created when /utility/update is visited.
=> Move inserting Twitter plugin's UAP to structure

library/core/class.smarty.php, library/core/class.smartysecurity.php, library/core/class.smartysecurityvanilla.php
`Smarty_Security::isTrustedPhpFunction` is case-sensitive.  We need it to be case-insensitive, especially since we changed our code style guidelines in the last year.
This update extends `Smarty_Security` and overrides `isTrustedPhpFunction` to force casing of function names to lowercase for testing.  This update also adds a new function to the Smarty security class, `setPhpFunctions`, which transforms all PHP function names to lowercase before setting them on the object.
Closes #4014
=> Implement custom Smarty_Security class

applications/vanilla/controllers/class.vanillasettingscontroller.php
Maintain backwards compatibility with the events in VanillaSettings by firing as settingsController.
Closes https://github.com/vanilla/vanilla/issues/4025
=> Maintain backwards compatibility in Vanilla settings

applications/dashboard/models/class.assetmodel.php
The old error message was confusing:
`The js file 'filename.js' in folder 'something' is deprecated`
Now it shows:
`The file path 'something/filename.js' is deprecated. Use 'something/js/filename.js' instead.`
I saw that while fixing https://github.com/vanilla/addons/pull/334
=> Improve AssetModel::jsPath() deprecated "path" message.

applications/vanilla/settings/structure.php
When the "General" category is created on install, it has a depth of 0.  This is because it has no depth of its own and defaults to 0.
This update adds the value of 1 for the `Depth` column of the "General" category on install.
Closes #3976
=> Update General Discussion category's depth to 1 on install

library/core/class.authenticationprovidermodel.php
I noticed the default provider was being queried several times when multiple SSO plugins were enabled.
=> Cache the default authentication provider within the request

library/core/class.authenticator.php
`Gdn_Authenticator::lookupToken` currently queries user tokens from the `UserAuthenticationToken` table, based partially on the following:
```php
where('(uat.Timestamp + uat.Lifetime) >=', 'NOW()')
```
By default, `Gdn_SQLDriver::where` escapes field values.  This means by the time the query is run, it reads something like:
```sql
where (uat.Timestamp + uat.Lifetime) >= 'NOW()'
```
This update disables escaping of the value field to allow MySQL's `NOW` function to return a proper time for comparison.
Closes #2011
=> Fix token expiry check in Gdn_Authenticator

applications/dashboard/settings/structure.php
```
sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```
I used the default sql-mode of mysql 5.7.8 to fix a bug and I'm finding more while fixing other issues.
=> Fix a structure issue when using MySQL 5.7 default "sql-mode" (strict)

plugins/VanillaInThisDiscussion/class.inthisdiscussionmodule.php
MySQL > 5.7.5 comes with ONLY_FULL_GROUP_BY enabled in sql-mode.
Update the query to comply with this "strict" mode.
Fix: https://github.com/vanilla/vanilla/issues/3974
=> Make "In this discussion" plugin work with sql mode ONLY_FULL_GROUP_BY

applications/vanilla/js/discussion.js
On /me comments the message is invisible.
So instead of checking for message visibility, check if no `.EditCommentForm` exists inside the comment.
fixes #1769
=> Fix /me comment editing

library/core/class.emoji.php
Use "tongue" for :stuck_out_tongue: (tongue.png) emoji instead of "stuck_out_tongue", which only exists in the archive.
No functionality change.
=> Use canonical emoji name in editor list

library/core/class.controller.php
Since the RootController is intended for plugin methods at the root, it should not include the name in the canonical url, e.g. `mydomain.com/root/method` becomes `mydomain.com/method`
=> RootController: Remove controller name from canonical url

applications/vanilla/models/class.categorymodel.php
This prevents strict errors in MySQL 5.7. Vanilla without any plugins is okay, but plugins that add checkboxes especially have issues.
=> Call Gdn_Model->coerceData() in CategoryModel->save()

applications/vanilla/settings/structure.php
$Database had been used although it had not been defined before.
=> Fix usage uf undefined var in Vanilla structure

applications/dashboard/controllers/class.statisticscontroller.php, applications/dashboard/views/statistics/configuration.php, applications/dashboard/views/statistics/verify.php
Use pop-ins instead of slices for the analytics page. Closes #3934.
=> Remove slicing from the statistics configuration page

plugins/GooglePlus/class.googleplus.plugin.php
The option to login with google+ is not shown in guest module when ClientID and secret are not configured. But in entry/signin that check wasn't there.
=> Don't show Google+ login when not configured

plugins/OpenID/class.openid.plugin.php
When given a wrong url, the url.php view is rendered multiple times. Since it is the default view in the following switch case construct, it doesn't need to be rendered before.
=> Prevent errorneous rendering when OpenID url is invalid

library/database/class.mysqlstructure.php
I don't know if sanitation has to be done at all, but it was only used for UNIQUE and FULLTEXT keys, not for normal INDEXes, which surely wasn't meant that way.
=> Sanitize table name in _create() method

README.md
Suggestion for the readme.
The bundled Facebook, Twitter and GooglePlus plugins all require SSL to work correctly.
See issue #1889
=> Add note regarding OpenSSL support to README

library/core/functions.general.php
The share url for comments was the discussion url which would make share buttons below every comment useless.
fixes #2034
=> Make individual comments shareable

library/core/class.request.php
This method is used but not described anywhere. Description is not as easy as e.g. remoteHost since for getting the IP, multiple server variables are checked.
Additionally, I've changed some casening. No functional code changes were done.
=> Add description for remoteAddress method

library/core/class.format.php
This prevents URIs that don't point to videos like https://www.youtube.com/user/VanillaForumsTV being matched.
While Google doesn't guarantee it will always be that way, video IDs have always been 11 characters and it probably won't change anytime soon.
More info: http://webapps.stackexchange.com/a/54448
fixes #3377
=> YouTube embed: More restricitve video ID match

library/core/class.smarty.php
This fixes things like `register_function` being renamed. They already made a compatibility layer, so let's use it.
=> Use backwards compatible Smarty 3 to avoid theme breaks

conf/config-defaults.php, library/core/functions.error.php
**First part** in allowing php logging to flow normally to the server error logs.
Before this change, in order to enable PHP logging to flow to the error log file, the config key `Garden.Errors.LogEnabled` needed to be set to true.  This makes it harder for a sysadmin to troubleshoot an installation since `php.ini` settings on the server such as `log_errors` is not respected and `error_reporting` is overridden in `index.php`. 
- Config `Garden.Errors.LogEnabled` as been removed.  
Detection is now based on `ini_get('log_errors')` value.
- PHP errors and exceptions are formatted the same way as the native PHP error handler would.
- `Non-Fatal errors` are not converted to exception anymore, preventing the request to halt for `E_NOTICE` for example.
- The `php.ini` server setting …
=> Allow php logging when enabled in php.ini

library/Vanilla/AddonManager.php
When lookup is by value, our error message needs to still make sense. Locales have a numeric array from calling `array_keys`, so their keys are nonsensical. Improving the message while maintaining legibility required a small refactor.
=> Improve error message from startAddonsByKey() 

js/global.js
- Allow popins to work off the .js-popin class. This should lead to deprecation of the .Popin class.
- Fire the contentLoad event off the popin instead of its content. The reasoning is that the popin itself is always a direct container.
=> Tweak popins

applications/dashboard/settings/class.hooks.php, applications/vanilla/controllers/class.postcontroller.php, js/global.js, library/core/class.dispatcher.php, library/core/class.form.php, library/core/class.request.php, library/core/class.session.php
This update does a few things:
1. Registers a new function, `Gdn_Dispatcher::sendHeaders`, as a callback with `header_register_callback` in `Gdn_Dispatcher::start`.  This function only fires an event.
2. Adds a new hook, `gdn_dispatcher_sendHeaders_handler`, to the Dashboard application.  This hook checks to see if a transient key was supplied.  If it was and it is invalid, the valid transient key is sent back to the client in a X-CSRF-Token header.
3. Creates a new JavaScript hook: `ajaxComplete`.  This hook checks the headers of any completed AJAX requests fired by jQuery.  If a X-CSRF-Token header is present, its value is grabbed and used to update the CSRF token value in the `gdn.meta` collection.
Closes #3962
=> Automatically update CSRF token with AJAX requests

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/views/settings/gettingstarted.php
The email feature was intended to be used to invite 10 or so peoples but was used to mass invite.
Since it is bugged and we do not want to promote mass import we are removing it.
Fixes: https://github.com/vanilla/vanilla/issues/4064
=> Remove the invite feature from the GettingStarted page

applications/vanilla/settings/class.hooks.php
When we merged in https://github.com/vanilla/vanilla/pull/3693, the Vanilla application had its settings folder, under views, renamed to vanillasettings.  Vanilla's `profileController_CustomNotificationPreferences_Handler` hook hadn't been updated to use this renamed directory.  When users visited their preferences page, they were met with a "View not found" error.
This update alters a `fetchViewLocation` call to use the proper view folder name.
=> Fix "View not found" error on preferences page

applications/dashboard/controllers/class.dashboardcontroller.php, applications/dashboard/settings/class.hooks.php
This update moves to populate Dashboard's menu items by way of a new earlyAppSettingsMenuItems event, which will run before the existing getAppSettingsMenuItems.  This is done to allow other addons to be able to modify Dashboard's menu items, regardless of the addon's configured priority.
=> Move Dashboard menu population to earlyAppSettingsMenuItems

plugins/Flagging/class.flagging.plugin.php
- The query returns 0 when `sql-mode` `ONLY_FULL_GROUP_BY` is off.
- The plugin crash when we turn it on when `sql-mode` `ONLY_FULL_GROUP_BY` is turned on.
Fix https://github.com/vanilla/vanilla/issues/3942
This should be fixed in release/2.3 too, when approved.
=> Fix the flagging plugin "number of tracked item" query

applications/dashboard/settings/structure.php
Define the GDN_UserIP table for future use. This allows structures to be run before changes that require the table.
=> Define the GDN_UserIP table

library/core/class.proxyrequest.php
From https://github.com/vanilla/vanilla/issues/4078:
The following code was throwing a fatal since the error code need to be a "digit" and an empty string was given to it.
```php
throw new Gdn_UserException(val('Exception', $response, 'There was an error performing your request.'), $request->ResponseStatus);
```
=> Set the default ResponseStatus of ProxyRequest to 0 instead of ""

applications/dashboard/controllers/class.dashboardcontroller.php, applications/dashboard/modules/class.sidemenumodule.php, applications/vanilla/controllers/class.vanillasettingscontroller.php, applications/vanilla/settings/class.hooks.php
1. The Dashboard menu items still are not sorting correctly. This is visible most easily on the Categories page, but there are several other things amiss everywhere. The problem is we need to build it in this order EXACTLY: Dashboard tier-1 -> Vanilla (all) + Dashboard tier-2 -> Plugins etc. Any deviation from this results in wrongly ordered items. We only had 2 events, and because of the new addon manager order were firing things in the order: Dashboard (all) -> Plugins -> Vanilla (all). This fails when Vanilla initiates as in the `vanillasettings` controller, but it also fails to put Vanilla's menu items before plugin items in second-tier ordering. My solution here rather than add a third, even earlier event is to move the manual build of Dash tier-1 into the `addSideMenu()` methods.
2. …
=> Fix sorting and sync problems in the Dashboard menu creation (part 2)

applications/dashboard/views/profile/preferences.php
If `Garden.Registration.NoEmail` is enabled, the profile page does not properly display description for notification preferences.  This is due to the preferences page assuming a 0-index is available in one of the preference arrays.
This update re-indexes the array before attempting to reference the 0-index to ensure it will be available.
=> Fix empty description on notification preferences page

applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/controllers/class.categorycontroller.php, applications/vanilla/controllers/class.vanillasettingscontroller.php, applications/vanilla/library/class.categorycollection.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/settings/structure.php, applications/vanilla/views/categories/all.php, applications/vanilla/views/categories/table.php
Optimize the various all category type views to use the CategoryCollection instead of iterating all categories. This is the implementation of #3845.
=> Category Scaling Part 2

library/Vanilla/AddonManager.php
On some setups, Vanilla's add-on manager will trigger a fatal error due to trying to `require` the multi-cache file after it's initially been generated.  This seems to be due to a delay between when the file is created and when it is accessible. `file_exists` check passes, but the actual file is not yet readable, so `require` fails.
This update changes `file_exists` checks to `is_readable` in order to verify the file can be read before attempting to load it with `require`. Additional checks and error logging are also included.
=> Fix add-on manager fatal error when initially generating multi-cache

applications/vanilla/controllers/class.postcontroller.php
The NewDiscussionModule has been added in postControllers initialize() method.
a) Panel is hidden so panel modules wouldn't be displayed anyway
b) There is no sense to present "New discussion" while the current action is to create a new discussion
c) Adding a new comment or editing it is done inline so the New discussion is already visible
d) Only when editing an existing discussion it might be useful to present a "New Discussion" button to the user. But I doubt that this has been the intention why this module has been added and if that has been the reason, it should be added in the editDiscussion method itself.
To my opinion, it could be dropped completely here.
=> Don't add NewDiscussionModule to postController

applications/vanilla/controllers/class.postcontroller.php
DiscussionModels save method only expects FormPostValues as a parameter. The postController also added the commentModel as a parameter at one line.
=> Strip unused parameter from call to discussionModel->save()

library/core/class.markdownvanilla.php
The current markdown implementation requires an empty line before a list:
```
This is a list:
* One
* Two
```
While on github and most other implementations, this will also work:
```
This is a list:
* One
* Two
```
The author explains the reasons for this here:
https://github.com/michelf/php-markdown/blob/6b4f89fd19944f0cdc36a8d6655a8909b91671d8/Michelf/Markdown.php#L1107-L1112
For unordered lists however, it is more intuitive not to require the empty line, see #3792
=> Markdown: Allow starting lists without a newline

applications/vanilla/controllers/class.discussioncontroller.php, applications/vanilla/views/discussion/helper_functions.php
`SelfUrl` can't be used for a target url, because it will point to `discussion/sink` or `discussion/close` whenever the dropdown is updated via ajax.
fixes #2013
=> Refresh after announcing a discussion

applications/vanilla/settings/class.hooks.php, applications/vanilla/views/discussions/helper_functions.php, applications/vanilla/views/modules/discussionfilter.php, library/core/functions.render.php
Count popins would fail on installs in subfolders, because the ajax url was passed through url() inconsistently.
fixes #1904
=> Unify countString() usage

plugins/SplitMerge/class.splitmerge.plugin.php
Since we have more than one plugin that need to do some cleanup I think it should be their responsibility.
=> Defer responsibility to manage TransformDiscussionToComment to other plugins

applications/dashboard/models/class.usermodel.php
The try/catch blocks in UserModel's save- and get-IP functions are attempting to catch `Gdn_UserException`, when actually `Exception` is being thrown.
This update alters the catch block in user IP functions to use `Exception`.
=> Fix try/catch blocks in UserModel save- and get-IP functions

applications/dashboard/models/class.usermodel.php
`Gdn_UserModel::setCalculatedFields` currently queries the `UserIP` table whenever a user record is fetched.  This can double our queries when retrieving user records and may potentially cause unnecessary stress on larger forums due to the increased database traffic.
This update removes querying the `UserIP` table from `Gdn_UserModel::setCalculatedFields`.  Instead, a simple array comprised of the user's `InsertIPAddress` and `LastIPAddress` fields is used as a simple backwards-compatibility shim.
Closes #4093
=> Remove AllIPAddresses querying from calculated user fields

library/core/class.userexception.php
Fixes the “Wrong parameters for Gdn_UserException” error we are seeing in the logs.
=> Fix issue with Gdn_UserException and non-integer codes

applications/vanilla/settings/class.hooks.php
`$session` has been declared in Vanillas base_render_before() hook although it is not used there.
I've also made a few casening and spelling corrections.
=> Strip unneeded variable declaration.

library/core/class.email.php
Having accents in the subject field led to an empty subject when receiving the email since it was not encoded properly.
=> Encode mail subject properly (UTF-8 anyone?)

index.php, library/core/class.dispatcher.php
Smarty use a constant named `DS` to know how to handle `DIRECTORY_SEPARATOR`.
Having our own `DS` constant defined to '/' was making smarty crash on windows.
Also, the dispatcher had hard coded '/' as directory separators so it did not match `\controllers\`.
This PR address those issues.
=> Fix Smarty and dispatcher paths on Windows

applications/dashboard/settings/structure.php
**Please be careful with this!**
There has been an error that made the field FullName hold 255 characters right after installation until the first run of /utility/structure. Then it is cut down to 100 characters.
I don't know if the model makes any restrictions, but if not, the FullName could be user for strings longer 100 characters and thus might get cut when utility/structure is run for the first time.
It might be safer to set all values to 255 based on that error.
=> Correct field length of GDN_Tag.FullName

js/global.js
The current regex for matching emojis allows for matches including trailing whitespace and newlines.  This can cause the autocomplete menu from disappearing if users enter a string like " : ".  The menu would appear when the colon was typed and not disappear when the space was typed after that, as it should.
This update alters emoji regex matching to remove the ability to allow emoji to end with spaces.  The pattern has also been simplified by combining like elements.
Closes #3883
=> Fix emoji menu not being properly dismissed

applications/conversations/settings/structure.php, applications/dashboard/settings/structure.php, applications/vanilla/settings/structure.php, library/database/class.databasestructure.php, library/database/class.mysqlstructure.php
Gdn_DatabaseStructure::query() is to be used internally.
- Rename query() to executeQuery and set the method as protected.
- Forward query() to $this->database::query() and deprecate it.
=> Deprecate Gdn_DatabaseStructure::query() for Gdn_SqlDriver.

library/Vanilla/Addon.php
This makes addons with parse errors in their info arrays less likely to take down sites.
=> Handle addons with errors in their info arrays

library/database/class.sqldriver.php
The regex which searches for the SQL keyword "AS" in the SELECT string is not case insensitive. `->select('Name AS UserName`')` would output a column named "AS UserName".
I've also stripped down the rest of the if condition, where there was an unneeded regex when a normal string operation does the trick.
I've tested it with following examples:
~~~
$test[1] = 'ColumnWithoutAlias';
$test[2] = 'Column   `AliasWithoutAs`';
$test[3] = 'Column    as AliasLowerCaseAs';
$test[4] = 'Column AS AliasLowerCaseAs';
$test[5] = 'Column aS     AliasMixedCaseAs';
$test[6] = 'Table.`Column`';
$test[7] = 'Table.Column';
~~~
They all show the expected result.
If strstr() fails it returns `false`and `trim(false)` return an empty string. Therefore there is no need for the former else section of this condition. …
=> Make "AS" in "select X as Y" case insensitive

plugins/editor/class.editor.plugin.php
Advanced Editor was sometimes attempting to force a post to be re-interpreted as Wysiwyg, even when the post was already in that format.  This led to post content being formatted before it was returned to the editor, so the code for YouTube embeds, etc, had been generated.  This caused the post to be updated with this invalid markup when it was saved, which led to some content being lost.
This update backports the current `ForceWysiwyg` check in Advanced Editor to the 2.2 release branch.
Closes #4114
=> Fix ForceWysiwyg check in Advanced Editor causing markup to generate early

applications/vanilla/models/class.commentmodel.php
By now only $CommentID is passed although $Comment is available. If a plugin has to check  anything on e.g. Comment->Body, the plugin would have to get the comment again.
=> Add $Comment to EventArguments on DeleteComment

applications/dashboard/models/class.usermodel.php
This update makes the following changes to user search in the dashboard:
1. User IP addresses are searched for the human-readable and packed form. (see https://github.com/vanilla/vanilla/pull/4133)
2. User IP addresses are searched for in the UserIP table. (see https://github.com/vanilla/vanilla/pull/4026)
Closes #3908
=> Expand user searching by IP address in dashboard

library/core/class.captcha.php, plugins/recaptcha/class.recaptcha.plugin.php
This update alters the behavior of `Captcha::enabled`.  It now considers if any plug-ins have registered captcha validation handlers before determining if captcha is enabled for a site, instead of solely relying on the `Garden.Registration.SkipCaptcha` config check.
Closes #4087
=> Fix inability to register when no captcha plug-in enabled

applications/dashboard/models/class.usermodel.php, applications/dashboard/settings/structure.php, applications/vanilla/settings/structure.php
This update adds capabilities to the Vanilla application's structure to migrate legacy IP data from the `User` table into the `UserIP` table.  Migration can be done with `/utility/update`.
The migration is done in batches of 10,000. The `InsertIPAddress` and `LastIPAddress` fields are analyzed and inserted into the `UserIP` table, if they are valid.  The `AllIPAddresses` column is wiped out after this operation and acts as a marker of which user records have been updated.
In addition, `UserModel::saveIP` has been updated to verify IPs with `filter_var`, because the `$IP` parameter is expected to be a human-readable address.  A new parameter, `$dateUpdated` has also been added to this function to force a specific `DateUpdated` column value.
Closes #3907
=> Add legacy IP data migration

applications/dashboard/modules/class.headmodule.php
The function begins like that:
~~~
public function title($Title = '', $NoSubTitle = false) {
if ($Title != '') {
// Apply $Title to $this->_Title and return it;
$this->_Title = $Title;
$this->_Sender->title($Title);
return $Title;
~~~
So if the first parameter `$Title` is specified, the second parameter is not considered. `$this->_Title` is set to `$Title` but in the definition it is clearly stated that it is `The main text for the "title"`.
The title method is never called with a parameter (except for one wrong usage in rolecontroler->edit for which I already made a PR). That's why changing the logic will not change the behavior. By now calling `title('Some Title')` would have created a title "Some Title" and after my Pull Request it would be "Some Title - $Subtitle" which, based on the …
=> HeadModule->title() NoSubTitle parameter is useless.

applications/vanilla/settings/class.hooks.php, applications/vanilla/views/vanillasettings/notificationpreferences.php
Update advanced notification to take Garden.Registration.NoEmail into account instead of not displaying at all.
Fixes https://github.com/vanilla/vanilla/issues/4112
=> Display advanced notification settings even when Garden.Registration.NoEmail is enabled.

applications/conversations/controllers/class.conversationscontroller.php, applications/dashboard/controllers/class.dashboardcontroller.php, applications/dashboard/controllers/class.statisticscontroller.php, applications/dashboard/views/statistics/configuration.php, applications/dashboard/views/statistics/disabled.php, applications/dashboard/views/statistics/index.php, applications/dashboard/views/statistics/verify.php, applications/vanilla/controllers/class.vanillacontroller.php, js/global.js, js/library/jquery.popin.js
Allows you to add a .js-form class to a form or around a form and that form will be AJAX submitted within the page.
Closes #3933
=> Add support for inline forms

applications/dashboard/modules/class.headmodule.php
On a discussion page, the `_Title` property of the HeadModule has its HTML entities encoded.  When the  `og:title` tag is built, its attributes are passed through the `attribute` function, which encodes the values again with `htmlspecialchars`.  This ultimately leads to things like ampersands being represented as `&amp;&amp`, which renders as `&amp;`.
This fix decodes the title value before it is passed to `attribute`, where it is then properly encoded.
=> Fix double encoding Open Graph title tag

library/core/class.dispatcher.php, library/core/class.smarty.php
In #4158 we lost the ability to have a blank path for homepage requests because we now have a unified request object that takes the path of the defaultcontroller in that case.
This change adds homepage detection in the dispatcher before this overwrite is done. Then this condition is passed onto Smarty as a new `$Homepage` variable, which is a boolean.
=> Add homepage detection

applications/dashboard/models/class.rolemodel.php, applications/dashboard/settings/class.hooks.php, applications/vanilla/settings/class.hooks.php
While we don't have a database load problem as in #3686 from adding role data to the page, we do have an infrastructure problem because we're calling the database too early and on too many page loads. We only need this data if Vanilla (the forum app) is loaded and only need it as the page renders in HTML, so here we move the hook as late as possible (which is always a better default anyway).
We also change `getPublicUserRoles()` to a static method because it it's only used in this sort of context-less querying way.
=> Move role meta query to latest possible and only in Vanilla app

plugins/Tagging/class.tagging.plugin.php
The pager, cannonical and feed urls where not properly made since Plugins.Tagging.UseCategories was not respected. The Category code was missing from them.
=> Fix $UrlTag when Plugins.Tagging.UseCategories is ON.

applications/vanilla/controllers/class.categoriescontroller.php
Use `categoryUrl()` instead of `$this->SelfUrl` for the category RSS link to include the domain and avoid having an RSS link with the page number in it. This is consistent with the `addRss()` usage on the `/discussions` index.
=> Use category URL for category RSS link

plugins/Facebook/class.facebook.plugin.php
As of v2.1, unversioned Graph API endpoints are [deprecated](https://developers.facebook.com/docs/apps/changelog#v2_1_deprecations).  This update alters API endpoints to use versioned URLs and implements the current API version.
Please note: After verifying the functionality, please visit the [API Upgrade Tool](https://developers.facebook.com/tools/api_versioning/) to verify no upgrade notices were generated.
Closes #4129
=> Update Facebook API to use versioned endpoint

library/core/class.dispatcher.php, library/core/class.request.php
When a route’s destination does not include a querystring then the requests original querystring will pass through a rewrite rule.
Example:
```
/test -> /discussions
```
Going to /test?page=p2 will rewrite to /discussions?page=p2
However consider this example:
```
/page1 -> /discussions?page=p1
```
Going to /page1?page=p2 will rewrite to /discussions?page=p1
There is also a change in Gdn_Request to make Gdn_Request->path(/foo) automatically strip out the trailing slash. This mirrors the functionality of Gdn_Request->pathAndQuery() and really seems like the correct behavior. However, since this is low-level functionality it does carry some risk and should be carefully reviewed.
=> Allow query strings to pass through simple routes

plugins/ProfileExtender/class.profileextender.plugin.php, plugins/ProfileExtender/views/helper_functions.php
This update moves rendering of Profile Extender fields on the profile view into a helper function, which can then be overridden.
Closes #4178
=> Add ability to override public field rendering in Profile Extender

library/core/class.smarty.php
Sooooo.... Setting this make no sense since path never match directories on disk.
Also, `/profile/name-ending-with-a-dot.` cause an infinite loop because the path is rewritten to `/profile/name-ending-with-a-dot./` and is then evaluated by Smarty's `_realpath()` function: https://github.com/smarty-php/smarty/blob/v3.1.29/libs/Smarty.class.php#L1184
Fun fun fun :)
Please test this carefully! (I tested the change with multiple client themes + Bootstrap 3 and more)
=> Remove Gdn_Request::path() from smarty's secure_dir variable.

applications/vanilla/models/class.discussionmodel.php
When discussion edits are logged, they are attempting to pass along the original data as an object (`$Stored`), when the formatter used by the log view is expecting an array.
This update alters the logging method for discussion edits to match the [existing method for comment edits](https://github.com/vanilla/vanilla/blob/417f98c55869e86068535ad249e808e46b680093/applications/vanilla/models/class.commentmodel.php#L871).
Closes #3945
=> Fix data capture when logging a discussion edit

applications/dashboard/models/class.importmodel.php
The docs say a bool is to be returned. We've been sloppily using a count instead. However, it appears hitting exactly a multiple of 100 would cause the count to reset to zero and be "false". Here we add a simple bool variable that flips to true once once the first record is found instead.
=> Return a bool from the table importer instead of a fickle count

library/core/class.controller.php, plugins/ProfileExtender/class.profileextender.plugin.php
This fixes an issue where if a plugin has a view (i.e., `helper_functions.php`) and a theme overrides the view with the same name (i.e., `profile/helper_functions`), `fetchViewLocation()` will return the controller-based view when we are in a page with that controller.
This specifically fixes the above issue with in the ProfileExtender by explicitly opting out of any controller view look-ups.
Reproduce this error by: 
1. Overriding `profile/helper_functions` in a theme or plugin.
2. Enabling ProfileExtender.
3. Navigating to any profile page.
Closes https://github.com/vanilla/vanilla/issues/4247
=> Allow overriding controller view lookups in fetchViewLocation()

applications/dashboard/settings/structure.php
The UserIP table migration scan is currently setup to run whenever Vanilla's structure routine is invoked.  This is a problem, because the routine may be invoked when we're just doing a capture-only scan (e.g. /utility/structure) and the tables aren't available when they're expected to be.
This update adds a check for determining if we're in capture-only mode, using the `$Structure` variable provided by `UtilityModel::runStructure`, and avoids attempting to migrate IP addresses under such a condition.
Closes #4240
=> Fix table error on /utility/structure scans

applications/vanilla/controllers/class.categoriescontroller.php
When categories are configured to display root categories as headings, the headings are taken into account for the category display depth.  This does not seem to be how things were prior to recent category component refactors.
1. Create a category structure at least three levels deep (not counting the root).
2. Configure "Place nested categories in a comma-delimited list when they are" to "more than 1 level deep".
3. Enable "Display root categories as headings".
4. Set "Categories Layout" to "Table Layout".
5. Visit `/categories` on your forum.  Your third level is not be displayed.
This update increments the display depth by one in `CategoriesController::all` if `Vanilla.Categories.DoHeadings` is enabled.
=> Fix category display depth when configured to display headings

plugins/editor/class.editor.plugin.php
If MySQL is in strict mode it will reject uploads from the advanced
editor with the following error
> PHP Fatal error: Incorrect integer value: '' for column 'ThumbWidth'
at row 1|Gdn_Database|Query|insert GDN_Media
This is because the advanced editor is trying to insert a string value
into an integer. Setting a default value of 0 for the thumb and image
height and width values corrects this.
* Forum thread on this topic:
https://vanillaforums.org/discussion/32255/advanced-editor-upload-failing-incorrect-integer-value#latest
master
=> Fix Advanced Editor upload incompatibility with MySQL strict mode

applications/dashboard/controllers/class.settingscontroller.php, conf/constants.php, library/core/class.controller.php, library/core/class.dispatcher.php
This is a fairly big refactor, but is really only moving things out of large methods into smaller methods.
There is a bit of a methodology change too where controllers are discovered before their methods are examined. This mirrors where the dispatcher is going even though it currently doesn’t serve much of a great purpose.
I recommend walking through the code to review this PR, starting at Gdn_Dispatcher->dispatch(). You should be able to see the logic of a dispatch more clearly now:
1. Check to see if the application is in update mode.
2. Check for GDN_Route URL rewrites.
3. Check against private communities.
4. Analyze the request, looking for a controller.
5. Dispatch to that controller.
a) Instantiate the controller.
b) Look for the method to dispatch to.
c) Reflect the method's …
=> Gdn_Dispatcher untagling, part 2

library/core/class.controller.php
The dispatcher refactor assigns a lowercased application name to the controller rather than the title cased one. This causes the asset sort arrays to not work. Rather that changing the application that’s assigned to the dispatcher I opted to make the asset sort containers case-insensitive.
This PR also includes some variable renaming to be in line with code standards.
=> Fix asset sorting

applications/dashboard/models/class.rolemodel.php, applications/vanilla/settings/class.hooks.php
Change the calling method "getPublicUserRoles" to a non static method and update every call to it.
Fixes https://github.com/vanilla/vanilla/issues/4252
=> Fix RoleModel::getByUserID() should not be called statically.

applications/vanilla/views/discussion/helper_functions.php
Wrap discussion options in url function in discussion option adapter.
Fixes issue where urls to some discussion options are unexpected.
Closes https://github.com/vanilla/vanilla/issues/4253
=> Wrap discussion options in url()

library/database/class.sqldriver.php
`SqlDriver::where` current uses `list` to [grab the first value](https://github.com/vanilla/vanilla/blob/be5c4099669d098707640b8944d947a2e3b7c26c/library/database/class.sqldriver.php#L1994) for field criteria.  If there is no zero index, [list fails because it assumes a numerically-indexed array, complete with a zero index](http://php.net/list).
This update swaps out the call to `list` with `replace`, which [rewinds the internal pointer for the array and returns its first value](http://php.net/reset).
=> Use reset to grab first val in SqlDriver::where

applications/dashboard/views/user/add.php, applications/dashboard/views/user/edit.php
Users' Location and Title fields can only be editted from their profile. This allows these fields to be editted in the dashboard.
Closes https://github.com/vanilla/vanilla/issues/4256
=> Let Location and Title be editted from the dashboard

plugins/recaptcha/class.recaptcha.plugin.php
By adding the captcha script in the form, we can use captcha in popups.
Closes https://github.com/vanilla/vanilla/issues/4265
=> Add captcha script in form markup rather than head

applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/views/post/discussion.php, library/core/class.form.php
Show the categories in the category dropdown that are children of the category in the url.
Show the category selector in any category that is not a DisplayAs: Discussion category.
Closes https://github.com/vanilla/vanilla/issues/4275
=> Fix category selector for nested categories in /post

plugins/ProfileExtender/class.profileextender.plugin.php
Profile Extender already natively will use column `GDN_User.SomeField` if it exists rather than adding `Profile.SomeField` to `GDN_UserMeta.Name` with a matching `Value` for inserting and updating values.
This was to allow it to work with fields like Title and Location that already exist and have special functionality in Vanilla, including displaying on profiles if populated.
This updates Profile Extender to also allow READING from `GDN_User.SomeField` to display it on the profile even if it's not a special field in Vanilla.
The point of this is that putting a column manually on `GDN_User` will let Profile Extender access it while also making it available over the API.
=> Profile Extender: Show native fields on profile

library/core/class.controller.php, library/core/class.dispatcher.php
This should set the ResolvedPath correctly, with the following caveats:
- The property is set in the dispatcher rather than Gdn_Controller->initialize(). This should be more robust.
- The property is set a bit later due to when the controller method is determine. This could cause issues.
- Plugins with controllers will just use the plugin name rather than “plugins/pluginname” in the resolved path.
=> Fix the Gdn_Controller->ResolvedPath compatibility bug

applications/dashboard/controllers/class.entrycontroller.php
If registration takes place in a popup, `FormSaved` is set to `true` in the JSON response (as it should be).  This field triggers behavior that closes the window and, if `RedirectUrl` is set, sends the user to the new URL.
When approval registration is enabled and a user successfully registers in a popup, the site responds back with `FormSaved` but no `RedirectUrl`.  This would normally render the registerthanks view when delivering all assets.  When delivering JSON, to the user it just closes the popup window.  This update adds a `RedirectUrl` value of "/entry/registerthanks" to successful approval registrations when not delivering all assets.  This redirects the user to the "Your application will be reviewed..." page.
Closes #4278
=> Add RedirectURL to JSON approval registration response

library/core/class.smarty.php
Useful for when the same theme is used on mobile and desktop and we want to conditionally output different stuff within the master view.
=> Allow smarty to call isMobile() and userAgentType()

applications/dashboard/settings/structure.php
If `Garden.Registration.ConfirmEmailRole` is set to a role ID (or IDs) that do not exist in the database, a fatal error is encountered when running the dashboard's structure file.  This is due to...
1. The structure.php attempts to run a `Gdn_SQLDriver::replace` call to [update the role records](https://github.com/vanilla/vanilla/blob/341885917626a70ae8ca585c74e57f85263be219/applications/dashboard/settings/structure.php#L189).
2. `Gdn_SQLDriver::replace` tries to lookup the existing role records to update, finds none, merges our sets+wheres and [passes everything off to `Gdn_SQLDriver::insert`](https://github.com/vanilla/vanilla/blob/341885917626a70ae8ca585c74e57f85263be219/library/database/class.sqldriver.php#L1156).
3. `Gdn_SQLDriver::insert` [passes things off to …
=> Revise updating role type based on ConfirmEmailRole config

applications/vanilla/controllers/class.categoriescontroller.php
The root category is included in the /categories/apiv1list endpoint.
This update checks for the existence of the root category before the data is delivered and purges it if present.
=> Avoid including root category in /categories/apiv1list

library/core/class.request.php
This makes the URL shorter and prevents an empty question mark when URL parameters are null.
=> Filter out empty get parameters when building the current query string

applications/vanilla/controllers/class.vanillasettingscontroller.php, applications/vanilla/views/vanillasettings/managecategories.php, applications/vanilla/views/vanillasettings/movecategory.php
This update allows a user to move a category from its current parent to another of its parents/ancestors from the Manage Categories dashboard area.
Closes #4157
=> Add ability to move a category to another of its parents

applications/vanilla/js/post.js
`post.js` requires there be an element with an ID of `#Content` to display some content from the server, like the "Your post is pending approval" message.  The issue is that some themes do not have this element.  Some themes have instead implemented tagging their content elements with classes like `site-content`.  This update adds support for these additional content element identifiers in `post.js`.
Closes #4098
=> Improve approval notice compatibility with some themes

applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/controllers/class.vanillasettingscontroller.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/modules/class.categoriesmodule.php, applications/vanilla/settings/structure.php, applications/vanilla/views/categories/flat_all.php, applications/vanilla/views/categories/flat_table.php, applications/vanilla/views/vanillasettings/addcategory.php, applications/vanilla/views/vanillasettings/editcategory.php
=> Add basic support for flat categories

applications/dashboard/models/class.usermodel.php
The plain-text version of Vanilla's welcome email has no line break character after the account information portion.  If the site requires users to confirm their e-mail, the "You need to confirm your email" text runs into the end of the user's email address and creates an invalid hyperlink.
This update adds a line break to the end of the account information portion of the email, which ensures that any text immediately following it (e.g. email confirmation prompts) is placed on a new line. 
Closes #3920
=> Add additional line break to welcome e-mail
