library/core/class.applicationmanager.php
This reverts commit b06639891474779f16d5c3df6c17815a8f5bcc2d.
This reverts a bad commit for the sake of brevity. Yay testing!
=> Revert "Remove superfluous variable." for issue #1779

README.md
Added .htaccess to the list of what should be backuped when you do a update
=> Add "backup .htaccess" to update information

applications/dashboard/locale/en-CA/definitions.php, library/core/class.validation.php, library/core/functions.validation.php, library/database/class.sqldriver.php
This is just grabbing the changes from https://github.com/vanilla/vanilla/pull/2355 into master.
=> Remove ad-hoc array function calling from GDN_SQL.

applications/dashboard/views/user/users.php
Event UserCell was misbehaving because the current user has never been passed as the EventArgument
=> Correct typo in function call "EventArgs" instead of "EventArguments"

library/core/class.passwordhash.php
Tested against MyBB 1.8 database.
=> Fix MyBB hash

library/core/functions.compatibility.php, library/database/class.mysqlstructure.php
* Fix primary key alters with more strict “one query allowed” policy.
* Fix bug in `paths()` function.
=> Fix issues with 2.1.8p1

applications/vanilla/models/class.categorymodel.php, library/core/functions.general.php
=> Translatable category names

applications/dashboard/controllers/class.activitycontroller.php
This allows the `/activity/item` view to actually display a single activity.
=> Change data name on activity controller

applications/dashboard/views/embed/forum.php
=> Use Asset() instead of Url() for embed script

plugins/Debugger/default.php
This will greatly reduce support effort for the OS version.
Also submitting against 2.1.
=> Enable/disable debug mode with the Debugger addon

library/core/class.format.php
These are two popular video sites for video game streaming.
=> Added support for Twitch.tv and Hitbox.tv

applications/dashboard/views/profile/user.php
It looks like we added a line without adding braces a while back.
=> Fix display bug where users without a title would show a bullet with nothing on the profile page.

library/core/functions.compatibility.php
Replaces #2374. Hat tip to @peregrine-web & @x00.
=> Use gzopen64 as fallback for gzopen

applications/dashboard/models/class.permissionmodel.php, applications/dashboard/settings/structure.php
* Do some additional schema checking when saving permissions.
* Set additional default permissions for administrators and moderators.
=> Permission defining and saving tweaks.

library/core/class.request.php
Since domain includes the scheme it's not that far fetched for it to have the port as well.  This fixes assets that are loaded with domain pointing at the wrong URL.
Fixes #2072
=> use HostAndPort in domain parsing

js/library/jquery.popup.js
Makes the confirm action consistent with the reveal.
=> Popup: Process targets on confirm clicks

library/core/class.request.php
=> We don't need no stinkin' val()

plugins/Emotify/class.emotify.plugin.php
=> Disable Emoji sets when Emotify is enabled

library/core/class.emoji.php
Also added some other emoji fixes.
=> Remove the markup breaking star emoji alias.

applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/views/categories/all.php
When the nav depth is increased then categories tend to not cooperate in terms of their depth.
This pull request attempts to adjust the category views a bit better when a nav depth is specified.
=> Make categories play nice with different navigation depths.

applications/dashboard/controllers/class.importcontroller.php, applications/dashboard/models/class.importmodel.php, applications/dashboard/views/import/credentials.php, applications/dashboard/views/import/index.php
Removed UseCurrentPassword, Password form fields and references;
Forcing all conditional code related to UseCurrentPassword being true
to run on import
=> Import: Force current user's password on new admin

applications/vanilla/models/class.categorymodel.php
This helps with doing a mass category re-order from other plugins.
=> Add a `$BySort` parameter to `CategoryModel->RebuildTree()`.

applications/vanilla/views/discussion/delete.php
The div element around the buttons wasn't properly closed.
=> Fix malformed HTML in delete popup

applications/vanilla/models/class.categorymodel.php
Backport PermissionCategory() to 2.1 for the FileUpload plugin.
https://github.com/vanilla/addons/pull/169
=> backport PermissionCategory() for FileUpload

applications/dashboard/modules/class.morepagermodule.php
An elegant fix to an ongoing sync problem.
=> Change MorePager to extend Pager

applications/dashboard/controllers/class.entrycontroller.php
Get access to ConnectData Form values.
=> Entry Controller: Add new event.

plugins/VanillaStats/views/dashboardlocalhost.php
expanded data on local hosts and stats in docs
=> updated to new link

applications/dashboard/models/class.usermetamodel.php
fixes https://github.com/vanilla/vanilla/issues/2057
=> UserMetaModel: respect default parameter

applications/dashboard/views/settings/helper_functions.php, applications/dashboard/views/settings/tutorials.php
The tutorial videos used http exclusively which gets blocked over https.
=> Make tutorial videos work over https.

library/core/functions.compatibility.php
When an array is tested for a non existing $key, the current behavior also checked if the array is an object before the default value was returned. Nesting the first if clause brings a performance enhancement. Not too big and only in one special case, but nevertheless!
I've used this script to test:
~~~
<?php
define('ITERATIONS', 3000000);
ini_set('display_errors', 1);
ini_set('track_errors', 1);
function val($key, $collection, $default = false) {
if (is_array($collection) && array_key_exists($key, $collection)) {
return $collection[$key];
} elseif (is_object($collection) && property_exists($collection, $key)) {
return $collection->$key;
}
return $default;
}
function value ($key, $collection, $default = false) {
if (is_array($collection)) {
if (array_key_exists($key, $collection)) { …
=> Mini performance enhancement for function val()

applications/vanilla/controllers/class.postcontroller.php
Allow changing of the embed discussion data in event handlers.
This closes #2536
=> Pass embed discussion data by reference

applications/vanilla/views/discussions/index_atom.php
I noticed there was no atom view for discussions, so I made one using the rss one as a basis. I'm not sure it's 100% correct, but it's working in my setup now.
-David
=> Add /discussions/feed.atom support.

library/core/functions.render.php
Only call Attribute() if there are $Attributes ;-)
=> Optimize function Img()

library/core/class.configuration.php
A better solution than the previous pull request #2523. Tested and works.
=> Clear cache on config save for Zend OPcache

applications/vanilla/views/discussions/helper_functions.php
The discussions within the discussion list did not check the edit timeout setting.
=> Use the correct permission check for editing of discussions.

library/vendors/SmartyPlugins/function.pocket.php
Give pockets plugin more info to check page when rendering.
=> Smarty pocket: Add Sender param.

library/core/class.validation.php
Fixes bug where Attributes (i.e. 'Criteria') are not being saved when updating Ranks.
=> Validation: Add default rule.

applications/dashboard/views/profile/thumbnail.php
All the other profile editmode pages use h1.
=> Change "Edit My Thumbnail" heading to h1 for consistency

applications/vanilla/controllers/class.postcontroller.php
This fixes a bug where notifications were not processed when posting comments via API.
=> Process notifications on API calls.

applications/dashboard/controllers/class.profilecontroller.php
- Throw an exception of there is a problem during an API call such as an invalid photo.
- Don’t redirect after API calls.
- Keep the response type for API calls.
- Return the uploaded avatar in the API response.
=> Fix user photo API calls.

applications/dashboard/models/class.usermodel.php, applications/vanilla/models/class.categorymodel.php
=> Fix for using iterator by reference in foreach

plugins/Flagging/class.flagging.plugin.php
Add mobile friendly to flagging.
=> Allow flagging to work on mobile

applications/dashboard/modules/class.profileoptionsmodule.php
=> Don't show the "Preferences" button to guests

README.md
This file also needs to be deleted for upgrading from 2.0.x to 2.1.x
=> Add master php view deletion reference for README upgrade process

plugins/editor/js/editor.js
Solves that issue: https://github.com/vanilla/vanilla/issues/2572
=> Highlight "http://" whenever link button is clicked

library/core/class.format.php
=> Allow unicode characters in links

library/core/class.format.php, library/core/functions.general.php
`(@someone)` wasn't recognized as a mention. Changed regex to allow that,
=> Add support for mentions in brackets

applications/dashboard/views/modules/configuration.php
Adds an easy way of providing a description in the configuration module by simply adding `$configurationModule->setData('Description', t('Some Description'));`
=> Add div.Info to ConfigurationModule

library/core/functions.render.php
The function returned `" <span class=\"Count\">$Number</span>"` for `CountString(10, '', array('CssClass' => 'SomethingSpecial'))`.
Now it returns `"<span class=\"SomethingSpecial Count\">$Number</span>"`.
**Note that I've also stripped the preceding space from the output!** The function could also return an empty string or `"<span class=\"$CssClass\" rel=\"$Url\"></span>"` and they have no space as the first character so I think there is no problem stripping it.
I've changed "if is_string($Options) ... else" to "if is_array($Options) ... else" so that numerical parameters for $Options do not break the function. They will end as (useless) class="13 Count" though...
I made some changes to the rest of the function and this are the results in a speed comparison:
CountString(0): **80% …
=> CountString() ignored CssClass parameter for "normal" counts

plugins/Quotes/class.quotes.plugin.php
Changes:
1. Added if brackets where necessary
2. Replaced **variable** RenderQuotes $with $HandleRenderQuotes
3. Make Settings Title translatable
4. Eliminate one superfluous if else block
5. Stripped out unneeded variable
6. Replaced use of deprecated `$Sender->EventArguments['Object']`
7. Added support for quotes in discussions
8. Stripped unneeded config settings from Setup and OnDisable
*Phew...* this is the longest pull request I've ever submitted! So I'm quite nervous and that's why I explain here what I have done in detail
Explanations:
2.) Added variable $HandleRenderQuotes because there was an ambiguous use of a variable and a function called `RenderQuotes`: `$this->RenderQuotes = C('Plugins.Quotes.RenderQuotes', TRUE);`
3.) `$Sender->Title("Quotes Settings");` to …
=> Add quote formatting to discussions + updating old code

index.php, js/library/jquery.atwho.js
Fixes bug where double tab/enter would delete completed mention by adding keyup action to disable properly.
=> atwho: prevent tab & enter from replaying

applications/dashboard/models/class.invitationmodel.php
Allow duplicate invites when declared by deleting the old one.
=> Invites: allow resend option

applications/vanilla/controllers/class.discussioncontroller.php, applications/vanilla/controllers/class.draftscontroller.php, applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/js/discussion.js, applications/vanilla/views/categories/helper_functions.php, applications/vanilla/views/discussion/helper_functions.php, applications/vanilla/views/discussions/helper_functions.php, applications/vanilla/views/post/discussion.php
Use of `/vanilla` in these cases is inconsistent & redundant.
=> Remove /vanilla from non-ambiguous controller URLs

applications/dashboard/controllers/class.profilecontroller.php
=> Fix activity to get first element via reset()

applications/dashboard/controllers/class.profilecontroller.php
Only add notification preferences for wall if activities are shown.
=> Profile controller: Wall notification preferences

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/views/user/index.php, library/database/class.sqldriver.php
Remove some costly features on the users page when there are too many users in the database.
To test this PR you can edit `UserModel->UserThreshold` to see the changes for the two cases of user counts.
=> Speed up the user page.

library/core/class.controller.php
Also remove an old unused method from `Gdn_Controller`.
=> Improve the view lookup logic against some edge cases.

library/core/functions.general.php, plugins/Tagging/class.tagging.plugin.php
Allow users and programmers to populate the default list of tags by adding the ?tags= parameter to the querystring when posting a new discussion.
=> Support the ?tags= query string parameter.

applications/dashboard/views/modules/configuration.php
Show divs for description only when there is a description. Thanks @bleistivt for this hint: https://github.com/vanilla/vanilla/pull/2648#issuecomment-98006466
=> Show div.description only conditionally

applications/dashboard/models/class.assetmodel.php, library/core/class.format.php, library/core/class.locale.php, library/database/class.mysqldriver.php, library/database/class.sqldriver.php, library/vendors/Smarty-2.6.25/libs/plugins/function.fetch.php
=> A regex \w already matches underscores and digits

applications/dashboard/models/class.banmodel.php
=> Ban model: Have banning user be the user who created the ban.

library/core/class.format.php
Allows customers to share SoundCloud track, by simply pasting the link to a SoundCloud page link
=> Adding SoundCloud

applications/conversations/controllers/class.conversationscontroller.php, applications/dashboard/models/class.assetmodel.php, applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/controllers/class.discussionscontroller.php, applications/vanilla/controllers/class.draftscontroller.php, applications/vanilla/controllers/class.postcontroller.php
Remove old references to deprecated css files from the core applications.
=> Remove unnecessary CSS files.

applications/dashboard/controllers/class.dbacontroller.php, applications/dashboard/models/class.dbamodel.php, applications/dashboard/models/class.importmodel.php, applications/dashboard/views/dba/fixuserrole.php, applications/dashboard/views/dba/job.php, applications/dashboard/views/import/stats.php
Adding checks for InsertUserID on imported discussions and comments; Adding check for valid role on imported users; Adding dba function to update missing InsertUserIDs on discussions and comments with SystemUserID; Adding dba function to apply specified role to users without a valid one
Rebase, #2641
=> Adding post-import data checks and fixes

applications/dashboard/views/entry/auth/password.php, applications/dashboard/views/entry/passwordform.php, applications/dashboard/views/entry/signin.php
=> Removing account creation link on sign-in form when invitation-only

applications/dashboard/views/modules/userinfo.php
htmlspecialchars for username.
=> Never let user data output unfiltered

applications/dashboard/models/class.assetmodel.php
Removes extra slash in plugins css file asset path.
=> Asset model: Remove superfluous slash in path.

library/core/class.request.php
Fix an issue when `Garden.RewriteUrls` is off where `index.php` gets added multiple times.
=> Fix an issue with generating urls when rewrite is off.

applications/vanilla/modules/class.promotedcontentmodule.php, applications/vanilla/views/modules/helper_functions.php
Add Url field to post
Prune Author field 
Add Url, PhotoUrl, RankName and RoleNames fields to Author field, 
Add 'Re' to comment Name field
=> Promoted Content api update

applications/vanilla/controllers/class.moderationcontroller.php
#1410 This needs to be tested with caching enabled and multiple discussions.
=> Update recent post when moving a discussion

library/core/class.autoloader.php
=> Write library map contents correctly

applications/dashboard/controllers/class.dbacontroller.php
Adds an endpoint to dba that allows the manual reset of permissions, based on a role's assigned type.
=> Adds dba/resetpermissions to reset permissions to default

applications/dashboard/views/profile/preferences.php, applications/vanilla/settings/class.hooks.php
=> Fix typo in CustomNotificationPreferences event name

plugins/Facebook/class.facebook.plugin.php, plugins/GooglePlus/class.googleplus.plugin.php, plugins/OpenID/class.openid.plugin.php, plugins/Twitter/class.twitter.plugin.php
=> Increase min version to 2.2 for plugins using SocialSignInButton()

conf/constants.php
=> Increase minimum PHP version check to 5.3

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/models/class.logmodel.php, applications/vanilla/settings/class.hooks.php, bootstrap.php, library/core/class.configuration.php, library/core/class.format.php, library/core/class.gdn.php, library/core/class.router.php, library/core/functions.error.php, library/core/functions.general.php
=> Casening cleanup

README.md
Fix copyright, update upgrade instructions, update PHP version info, and strike `stage` & `2.0` info.
=> Update README for 2015

applications/dashboard/models/class.messagemodel.php, library/core/class.model.php
* Refactor away use of `$this` in closure by using a static method (which is probably shoulda been anyway).
* Cleanup docs & method casing found along the way.
=> Fix PHP 5.3 compatibility in MesageModel::getMessagesForLocation()

plugins/HtmLawed/class.htmlawed.plugin.php, plugins/HtmLawed/htmLawed/htmLawed.php
=> Htmlawed 1.1.20

applications/vanilla/views/post/editcomment.php
=> Add missing events to edit post view to match post comment form

themes/mobile/class.mobilethemehooks.php
=> Refactor and fix casing in mobile themehooks

applications/conversations/controllers/class.messagescontroller.php
Allows manipulation of conversations before messages popin and messages/inbox.
=> Add events to messages controller.

plugins/Tagging/class.tagging.plugin.php
=> small typo due to casening

library/core/class.format.php
Fixes issue where spoilers appear in messages popin and messages/inbox view.
=> Garden formatter: Add function to remove spoilers and invoke in plainText function.

applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/views/home/error.php, applications/dashboard/views/home/filenotfound.php, applications/dashboard/views/home/permission.php, applications/vanilla/controllers/class.discussioncontroller.php, library/core/class.controller.php, library/core/functions.general.php
* Use `notFoundException()` for users & discussions.
* Add traces to `Default404` and `DefaultPermission` views.
* Change controller to prefer rendering those views.
Closes #2774
=> Improve 404 handling & error views

applications/conversations/models/class.conversationmessagemodel.php
The notifications for PM replies was using the old headline format from
the activity type table. This standardizes the notifications between the
initial message and replies.
=> Use the correct headline string for private messages

applications/dashboard/design/admin.css, applications/dashboard/js/settings.js, index.php
* Minor tweak to close the gap under feed headlines.
* Headline-only news feed by default.
=> Improve dashboard feed style

applications/dashboard/models/class.usermodel.php
* Pass 'Roles' thru `UserModel::sso()` so embedded forums can sync roles.
* Correct spelling of `UserModel::syncUser()`.
* Correct variable casing.
=> Fix syncUser so embedded SSO can pass roles

library/core/class.format.php, library/core/functions.general.php
PR for 2.2
Fixes https://github.com/vanilla/vanilla/pull/2652
Regex was done wrong and allowed `)@someone` instead of  `(@someone`
@bleistivt told me I did it wrong, but I missed to correct it... :(
=> Fix mentions in brackets

applications/dashboard/models/class.permissionmodel.php, library/core/class.session.php
- Add PermissionModel->getPermissionsByRole().
- Add PermissionModel::addPermissions().
- Add Gdn_Session->addPermissions().
These methods are meant to aid plugin development that modifies the current user’s permissions in interesting ways.
=> Add some permission utility methods.

applications/dashboard/models/class.usermodel.php
This issue manifested itself when Garden.SSO.SyncRoles was turned on and then a new user was registered via embedded SSO. In this case the new user would have no roles rather than those passed via the SSO.
=> Fix issue with saving roles when creating a new user via embedded SSO

plugins/editor/class.editor.plugin.php
=> Editor: Don't process gifs

plugins/editor/class.editor.plugin.php
* Do spacening.
* Fix coding standards.
* Remove stale commented code.
=> Cleanup Editor

applications/dashboard/controllers/class.setupcontroller.php, applications/dashboard/models/class.permissionmodel.php, applications/dashboard/models/class.updatemodel.php, applications/dashboard/settings/class.hooks.php, applications/dashboard/settings/structure.php, applications/vanilla/settings/class.hooks.php, applications/vanilla/settings/structure.php
* Add second permission setup call in structure so it is triggered when called remotely.
* Minor cleanup in code I read while evaluating this issue.
=> Fix initial permissions during site spawning

library/core/class.dummy.php
PHP 5.3 introduced __callStatic
=> Update Gdn_Dummy for static mocks

applications/dashboard/design/style.css
#2864 I have no idea how that could have fixed the users problem with deleting PMs, but removing the default style can't hurt.
=> Remove webkit-appearance from .Button

applications/vanilla/controllers/class.settingscontroller.php
Fixes bug where you can't move categories on managecategories page.
=> Manage categories: Update addJs calls.

applications/dashboard/controllers/class.profilecontroller.php
Allow the link to be modified via theming.
=> Add a CSS class to the social link on profile pages

applications/dashboard/design/admin.css
This class comes from style.css and is a useful utility.
=> Add the .Inline class to admin.css

applications/vanilla/models/class.discussionmodel.php
The event was not firing with the correct argument format in all cases.
=> Fix the event arguments in DiscussionModel->setField()

applications/vanilla/views/categories/all.php, library/vendors/SmartyPlugins/function.searchbox.php
* Add alt and title attributes to the RSS feed icon for categories/all.
* Add an access key to the search box smarty helper.
=> Add some accessibility attributes

plugins/editor/class.editor.plugin.php
Fixes bug where file upload attachments do not render for answers.
=> Editor: Load discussion media for answers, as well as comments.

library/core/class.format.php
=> Adds support for inline Imgur GifV embeds

applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/views/settings/managecategories.php
* Pull the `CanDelete` logic out of the managecategories view up to the controller.
* Set the `CanDelete` flag per-category instead of globally so it can be overridden by plugins.
=> Extract CanDelete out of managecategories view and set per category

applications/dashboard/controllers/class.activitycontroller.php, applications/dashboard/controllers/class.modulecontroller.php, applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/controllers/class.statisticscontroller.php, applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/views/admin.master.php, applications/vanilla/settings/class.hooks.php, library/core/class.form.php, library/core/class.request.php, library/core/class.smarty.php, library/core/functions.general.php
* Increase coverage of postback authentication.
* Sanitize JSON output from `user/tagsearch`.
* Add sane upper bound to `limit` param for `/modules` endpoint.
* Sanitize some template variables.
* Sanitize modulecontroller's applicationfolder handling.
* Add visibility management to `activity/item`.
=> Add intent checks & sanitize misc outputs

applications/dashboard/controllers/class.statisticscontroller.php, applications/vanilla/settings/class.hooks.php
Likely find-and-replace-type errors from https://github.com/vanilla/vanilla/pull/2973
=> Fix form postbacks checks.

library/core/class.request.php
Fixes port forwarding problems.
=> Use port from Host header if supplied

library/core/functions.general.php
Remove the @ operators from parseUrl() and clean up the internals of the function a bit.
=> Clean up parseUrl()

library/core/class.format.php, library/core/functions.general.php
Fixes an issue where a username like todd#123 would not format the URLs correctly.
=> Fix mentions formatting for usernames with special characters

js/library/jquery.atwho.js
fixes #2478 
This backports a change that was made in At.js which fixes above problem.
=> Prevent empty mention when hitting return

library/core/class.format.php
* Remove the deprecated \e modifier from preg_replace().
* Fix newline parsing.
* Remove the .PreContainer from the pre tags.
* Do a bit of trimming around pre tags to remove extra newlines.
=> Rework Gdn_Format::bbcode()

applications/dashboard/models/class.usermodel.php
=> Fix search attribute typo

applications/dashboard/models/class.importmodel.php
=> Increase import timeouts to 10 minutes

applications/dashboard/views/settings/gettingstarted.php
=> Add translatable number steps on Getting Started page

applications/vanilla/models/class.categorymodel.php
There was a notice when no categories in a forum had a most recent comment.
=> Fix notice in CategoryModel->joinRecentPosts()

plugins/GooglePrettify/class.googleprettify.plugin.php
Blocked by #3041 because it relies on the preview event working right.
=> GooglePrettify: replace livequery calls

applications/dashboard/views/social/connection_functions.php, library/core/functions.render.php
=> Fix coding standards

js/library/jquery.popup.js
Fixes http://vanillaforums.org/discussion/25089/opening-popup-programatically
=> Fix jquery.popup.js; make $.popup respect targetUrl setting.

applications/dashboard/js/settings.js
=> Bugfix for loadFeed() in dashboard/js/settings.js.

applications/dashboard/controllers/class.settingscontroller.php
Saves the path to the uploaded cloud file avatar in config.
=> Fix the path to the default avatar.

applications/vanilla/models/class.discussionmodel.php
=> Always display discussions as unread for guests

applications/dashboard/views/settings/ban.php
=> Fix untranslatable strings in ban.php

applications/vanilla/controllers/class.discussioncontroller.php
=> Don't set discussions as read on API requests

plugins/GooglePrettify/class.googleprettify.plugin.php
Lets prettifier style code blocks in private messages.
=> Google Prettify: Render in messages.

applications/dashboard/controllers/class.settingscontroller.php
Restrict visibility of new avatar methods.
=> Avatars: Make helper functions private.

index.php
A basic version check will help cut down on support requests.
=> Check the PHP version before executing.

applications/dashboard/views/settings/registration.php
Since CAPTCHA is an acronym it should be capitalized.
=> Fix the casing of CAPTCHA

applications/dashboard/models/class.assetmodel.php, library/core/class.controller.php, library/core/class.factory.php
Also adds search() to Gdn_Factory and viewHandlers() and viewExtensions() methods to AssetModel.
=> Add view location lookup method to AssetModel.

plugins/GooglePrettify/class.googleprettify.plugin.php
Let Google Prettifier manipulate code blocks in posts on the profile page.
=> Add prettify assets to Profile page.

applications/dashboard/models/class.searchmodel.php
=> Fix Typo "Relavence" => "Relevance"

library/core/class.module.php
Helps explicitly set a view for a module.
=> Add view property, getter and setter to module class.

library/core/class.theme.php
Favour using a setter method over directly setting the property.
=> Check for a setter method before assigning a value to a property.

applications/dashboard/modules/class.cropimagemodule.php, applications/dashboard/views/modules/cropimage.php
Also make headings less specific and add css class to button.
Fixes bug where cropping assets aren't added outside of dashboard application.
=> Crop image module: Specify app folder for assets.

applications/dashboard/controllers/class.utilitycontroller.php, applications/dashboard/views/utility/structure.php
- utility/structure now presents a start page on GET.
- The user must postback to scan and run the database structure.
=> Make utility/structure require an authenticated postback

applications/vanilla/models/class.categorymodel.php
=> Validate category url code

applications/dashboard/models/class.usermodel.php, library/core/class.model.php
- Add the property Gdn_Model->filterFields to control which fields get filtered on Gdn_Model->save().
- Add convenience methods to manipulate Gdn_Model->filterFields.
The idea behind this functionality is allowing more control on form filtering.
=> Refactor model form filtering

applications/dashboard/controllers/class.homecontroller.php, applications/dashboard/views/home/error.php, applications/dashboard/views/home/filenotfound.php, applications/dashboard/views/home/unauthorized.php, applications/vanilla/controllers/class.categoriescontroller.php
Also, pass safer errors from /categories/archives.
=> Add some basic sanitization to the HomeController

applications/vanilla/views/discussions/index.php, applications/vanilla/views/discussions/table.php
=> Make HTML in categories description consistent

applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/models/class.categorymodel.php
- Fix a bug in CategoryModel->getID() when getting a category as an array.
- Add CategoryModel->getRolePermissions().
- Add SettingsController->getCategory().
=> Add an endpoint to get admin information on a single category

applications/dashboard/controllers/class.assetcontroller.php, applications/dashboard/controllers/class.utilitycontroller.php, library/core/class.controller.php, library/core/class.dispatcher.php
Add new asset controller for serving css.
=> Add Asset controller

applications/dashboard/models/class.usermodel.php
* Casening.
* Add some missing docs.
* Remove some cruft commented code.
* Swap `array_column` in place of `consolidateArrayKeysByFirstBornChild()`.
=> Fix UserModel coding standards

applications/dashboard/controllers/class.activitycontroller.php, applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/views/activity/delete.php, applications/dashboard/views/profile/removepicture.php, applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/views/settings/deletecategoryphoto.php
* Add missing views for 3 actions (remove picture, delete category photo, delete activity).
* Remove janky Home controller faking & FileNotFound view calling.
* Fix bad redirect checking on `ActivityController->Delete()`.
See #3179
=> Fix "xstructure method not found" error in certain 404 conditions

applications/dashboard/controllers/class.utilitycontroller.php
This fixes #3200.
Also expanded the logic to be more readable.
=> Removes PHP 5.5 requirement from utility controller.

applications/dashboard/controllers/class.entrycontroller.php
Short array syntax is PHP 5.4+
=> Remove short array syntax

applications/dashboard/controllers/class.utilitycontroller.php, applications/dashboard/views/utility/structure.php, library/vendors/misc/functions.arraycolumn.php
This adds a userland implementation of array_column for PHP < 5.5. It is recommended per the PHP documentation: http://php.net/manual/en/function.array-column.php
I also removed some more short arrays.
=> Hotfix/php 5.3 compatibility

applications/dashboard/controllers/class.utilitycontroller.php
Submitted against master per request from @linc at #3201
=> Remove PHP 5.5 requirement from utility controller

applications/dashboard/models/class.usermodel.php
This will allow plugins to also handle user merging.
=> Throw an event when merging users

applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/models/class.categorymodel.php
* Casening
* Doc blocks
* Deprecated call replacements
=> Fix coding standards around categories

README.md
Add badges to the README. Check out the result [here](https://github.com/vanilla/vanilla/tree/feature/issue-badges).
=> Add some Github issue badges to the README

library/core/functions.general.php
Fighting zombies: https://github.com/vanilla/vanilla/pull/1867 :-D
=> Fix decho() behavior to show info only to admins

applications/dashboard/design/admin.css, applications/dashboard/js/colorpicker.js, library/core/class.form.php
Add new method to Gdn_Form for a color-picker form element.
Add new javascript file to synthesize the text input and color-picker.
Add necessary CSS.
=> Add support for a form color-picker element.

applications/dashboard/controllers/class.activitycontroller.php, applications/dashboard/settings/configuration.php
Used the naming scheme for Vanilla.Discussions.PerPage.
=> Let activity page length be configurable

applications/dashboard/models/class.permissionmodel.php, bootstrap.php
Backport #3266 to 2.2
Fixes #2862
=> Fix permissions definition when MySQL is in strict mode

library/core/functions.general.php
I've told you, decho is a zombie...
=> Backport decho() to 2.2

applications/dashboard/views/activity/helper_functions.php
See: https://validator.w3.org/nu/?doc=http%3A%2F%2Fvanillaforums.org%2Factivity
=> Fix invalid closing span in activities

applications/dashboard/views/activity/all.php
For consistency, since the profile/activity input is already a BodyBox.
=> Use BodyBox for /activity form

composer.json
Add Garden HTTP as a library for use in Vanilla
=> Add Garden HTTP library

applications/vanilla/controllers/class.postcontroller.php
Fixes bug where newlines are not being rendered in Vanilla comments if the editor is set to WYSIWYG.
=> Force wysiwyg embedded comments to Text format.

plugins/editor/js/editor.js
Could theoretically be a security issue if someone got super clever with a tic-tac-toe one day.
=> Don't echo filename back to user

applications/dashboard/models/class.activitymodel.php
Allow event handlers to change activity comment properties.
=> ActivityModel: Pass comment to handler by reference

applications/conversations/controllers/class.messagescontroller.php
=> Prevent empty range [50...50] in MessagesController

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/controllers/class.usercontroller.php, library/core/class.controller.php, library/core/class.dispatcher.php, library/core/class.email.php, library/core/class.format.php, library/core/functions.error.php, library/core/functions.general.php, library/core/functions.render.php, plugins/Debugger/views/debug.php
Hardcode all charset values to UTF-8.
https://github.com/vanilla/vanilla/pull/3038#issuecomment-137195756
=> Eliminate Garden.Charset

applications/conversations/settings/class.hooks.php, applications/dashboard/controllers/class.usercontroller.php, applications/vanilla/views/discussion/helper_functions.php, library/core/class.auth.php, library/core/class.cache.php, library/core/class.controller.php, library/core/class.dispatcher.php, library/core/class.email.php, library/core/class.emoji.php, library/core/class.filecache.php, library/core/class.form.php, library/core/class.format.php, library/core/class.gdn.php, library/core/class.locale.php, library/core/class.memcached.php, library/core/class.plugin.php, library/core/class.pluginmanager.php, library/core/class.regardingentity.php, library/core/class.request.php, library/core/class.session.php, library/core/class.statistics.php, library/core/class.theme.php, library/core/class.thememanager.php, library/core/class.validation.php, library/core/functions.compatibility.php, library/core/functions.error.php, library/core/functions.general.php, library/core/functions.render.php, library/core/functions.validation.php, library/database/class.mysqlstructure.php
Related to PR [https://github.com/vanilla/vanilla-docs/pull/74]
=> Refactor "c" function to lower case for consistency

applications/dashboard/modules/class.sortablemodule.php
Fixes sorting function to also sort nested lists.
=> Sort nested lists in sortable module.

applications/dashboard/design/style.css, index.php
Fixes issue where new discussion button is missing from some themes.
=> Revert new discussion rule specificity and add new rule for group page.

library/core/functions.general.php
=> Backport: Correct 'You' links in activity

applications/dashboard/controllers/class.settingscontroller.php
Force users to update using the form. Removes need for a transient key check.
=> Remove the ability for theme options to be set using GET

library/core/class.pluginmanager.php, library/core/class.thememanager.php
=> Remove variable variable references in the managers

applications/dashboard/settings/structure.php
Set config setting in preparation for new HTML email feature.
=> Set plaintext email styles default.

applications/dashboard/views/embed/forum.php
Will be set once locales are updated with: https://github.com/vanilla/locales/pull/4
=> Fix typo in embed view.

plugins/editor/class.editor.plugin.php
Don't add the canUpload js definition in base_render_before event handler.
Add separate function to resolve the canUpload property.
Call canUpload() only when needed in the beforeBodyBox_handler.
Addresses https://github.com/vanilla/vanilla/issues/3372.
=> Remove canUpload calculation from editor's constructor.

applications/dashboard/settings/structure.php, plugins/editor/class.editor.plugin.php
=> Remove unused column StorageMethod from Media table.

applications/dashboard/models/class.usermodel.php
When users merge some cache-style fields were not getting updated.
=> Update some cached fields when merging users.

applications/dashboard/controllers/class.utilitycontroller.php
Makes sure the Target param is safe before redirecting in utility/update
=> Validate the utility/update Target before redirecting.

applications/dashboard/controllers/class.logcontroller.php, applications/dashboard/js/log.js
Also checks for authenticated postbacks.
=> Enforce postbacks on log endpoints.

applications/dashboard/models/class.updatemodel.php
The addon directory needs the ability to find files in an addon collection for https://github.com/vanilla/community/pull/70
=> Allow access to UpdateModel's file finding capabilities

applications/vanilla/views/discussion/discussion.php, applications/vanilla/views/post/comment.php, applications/vanilla/views/post/discussion.php
Some minor standards fixing and general cleanup. No functionality changes.
=> Code cleanup

applications/dashboard/views/routes/index.php
Breaks the Transifex keys for 2 sentences, but the improvement seems worth it.
=> Update Routing help text and docs link

applications/conversations/models/class.conversationmessagemodel.php
500 error actually breaks the ajax.
=> Fix http code in ConversationMessageModel exception

js/global.js
These methods have also been moved and should now be available before document.ready().
=> Restore $.base64Encode() and $.base64Decode()

phpunit.xml.dist, tests/APIv0/APIv0.php
This will allow other devs to change settings more easily if they wish.
=> Use phpunit.xml config variables for the test environment

applications/dashboard/models/class.logmodel.php
We've deprecated `DiscussionModel->delete()`
=> Fix model delete call in log deletion

index.php, js/library/jquery.popup.js
Fixes issue where popups get cut off if overflow is hidden on the body.
=> Add a max-height and scroll to popups.

README.md
=> Fixed typo in line 121

plugins/Quotes/class.quotes.plugin.php
Fixes issue where quoting doesn't work when opened in a new tab.
=> Access data array using data function in Quotes plugin.

applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php
Useful to reject or tag (for review) discussions and comments.
=> Adds AfterValidate[Type] event for discussions and comments

applications/vanilla/views/discussions/table_functions.php
The modern view has this event, let's add it to the table view as well.
=> Add event to discussions table view to be congruous to modern view.

applications/vanilla/views/discussions/index.php
Allow plugins and modules to add html to the PageControls div.
=> Add a new event to allow components to render in the PageControls div.

applications/vanilla/views/discussions/table.php
It already exists in the modern view.
=> Add page controls hook to table view.

library/core/class.form.php
In method date() array for days and years were initialized as empty arrays and right the next step was to add their first element with a static value. I've changed that so that the are initilized with that static element right from the start.
I've also changed all
`public function ... (..., $Attributes/$Options = false)` to
`public function ... (..., $Attributes/$Options = array())`.
The parameter is expected to be an array, so its default should be an array, too.
=> Minor coding improvements to class.form.php

applications/dashboard/controllers/class.notificationscontroller.php
This update encodes the excerpt contents of all information notification popup windows.
=> Encode inform notification excerpt

applications/vanilla/views/discussions/helper_functions.php, applications/vanilla/views/discussions/table_functions.php
Also fixes coding standards in the existing call.
=> Add BetweenDiscussions event to table view

plugins/vanillicon/class.vanillicon.plugin.php
The time has come to take this baby out of beta.
=> Default vanillicon to v2

plugins/editor/class.editor.plugin.php
Add the "canUpload" definition to the base_render hook so that if you request the editor via ajax that definition will be present in the page
=> Fix the editor upload feature when it is called via ajax.

.gitignore
Exclude these folder from everywhere and not just the root of the project.
=> Exclude node_modules and bower_components folders

index.php, plugins/Whitelist
This is done in order to be able to rely on DiscussionsSortFilterModule being in core.
=> Bumb patch version. 

applications/vanilla/modules/class.discussionssortfiltermodule.php
Handle empty urls for clearing filters in the discussion sort filter module.
=> Massage url to allow clearing filters in the root.

applications/vanilla/models/class.categorymodel.php, applications/vanilla/modules/class.newdiscussionmodule.php
Also add an optional parameter for the child category we're testing.
=> Add hooks to category model's allowed discussion types function

applications/vanilla/controllers/class.discussioncontroller.php, applications/vanilla/views/categories/helper_functions.php, applications/vanilla/views/discussion/helper_functions.php, applications/vanilla/views/discussion/index.php, applications/vanilla/views/discussions/helper_functions.php, library/core/functions.general.php
Add function for converting strings to slugs for auto-generating dropdown item keys.
Deprecate discussion options functions.
=> Use dropdown module to render discussion and category options

library/core/functions.general.php, library/core/functions.render.php
From discussion on https://github.com/vanilla/vanilla/pull/2507
I'm not super-convinced we need this but it seems a useful shortening / abstraction. I was toying with this for a specific issue and ended up not needing it, but thought I'd throw it out there in case we think it's useful since I already wrote it.
=> Add htmlEsc() convenience function

plugins/Tagging/class.tagging.plugin.php
Lets plugins register tags as being reserved.
=> Add support for reserved tags in Tagging plugin.

applications/vanilla/views/categories/all.php
This div handles the float property of the options.
=> Wrap options in div with Options css class in categorylist.

applications/dashboard/design/spoilers.css, applications/dashboard/js/spoilers.js, library/core/class.format.php
Remove 'UserSpoiler' class from spoilers.
=> Remove UserSpoiler.

applications/conversations/controllers/class.messagescontroller.php, applications/dashboard/design/spoilers.css, applications/dashboard/js/spoilers.js, applications/vanilla/controllers/class.discussioncontroller.php, library/core/class.format.php, library/core/functions.render.php
Move existing server-side spoiler markup generation into the client-side JavaScript.
=> Move spoiler markup gen into JavaScript

composer.json, composer.lock, library/core/class.bbcode.php
Update Composer requirements for NBBC library and fix a casing error.
=> Update NBBC requirements

.htaccess, library/core/class.request.php
Fixes #3002 probably. @adrianspeyer can you test this branch?
=> Add X_PATH_INFO fallback to deal with naughty hosts

applications/vanilla/views/categories/helper_functions.php, applications/vanilla/views/discussion/helper_functions.php
Fixes issue where discussion options break in subcommunities.
=> Use url function in dropdown links.

applications/dashboard/views/email/email-basic.tpl, applications/dashboard/views/email/src/email-basic.php
Fixes issue where HTML emails render poorly in Outlook.
=> Update the html email template.

index.php
Cache busting, s'il vous plaît
=> Increment version

plugins/Quotes/class.quotes.plugin.php
Fixes issue where people can quote a post and see unfiltered content.
=> Filter content in posts before quoting.

library/core/class.format.php
The function may receive an HTML formatted (read HTML escaped) string.
=> Update formatMentionsCallback to parse escaped and non escaped HTML.

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/controllers/class.logcontroller.php, applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/library/class.emailtemplate.php, applications/dashboard/models/class.messagemodel.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/modules/class.sortablemodule.php, applications/dashboard/views/entry/connect.php, applications/vanilla/controllers/class.settingscontroller.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/modules/class.newdiscussionmodule.php, applications/vanilla/settings/class.hooks.php, applications/vanilla/views/modules/discussionssortfilter.php, conf/config-defaults.php, plugins/Flagging/views/reportemail.php, plugins/SplitMerge/class.splitmerge.plugin.php, plugins/Tagging/class.tagging.plugin.php, plugins/Tagging/class.tagmodel.php, plugins/editor/class.editor.plugin.php, plugins/editor/generate_thumbnail.php, showthread.php
@tburry requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/vanilla/vanilla/
=> Scrutinizer Auto-Fixes

.travis.yml, index.php
=> Bump version

applications/dashboard/models/class.usermodel.php, applications/dashboard/views/settings/registration.php, library/core/class.form.php, library/core/functions.validation.php
Supersedes https://github.com/vanilla/vanilla/pull/3417
=> Upgrade to reCAPTCHA 2

applications/dashboard/design/style.css
Affects text that is hovered on the profile picture in edit profile.
=> Fix typo in style.css

applications/dashboard/views/entry/registerapproval.php, applications/dashboard/views/entry/registerbasic.php, applications/dashboard/views/entry/registercaptcha.php, applications/dashboard/views/entry/registerinvitation.php, applications/dashboard/views/profile/edit.php
Remove gender selection from user-facing forms.
=> Remove gender from user-facing elements

applications/dashboard/controllers/class.usercontroller.php, tests/APIv0/APIv0.php, tests/APIv0/BaseTest.php, tests/APIv0/StandardTest.php
=> Add a test for /user/add.json

applications/conversations/models/class.conversationmessagemodel.php, applications/conversations/models/class.conversationmodel.php
Allows plugins to filter user-generated content from conversation messages.
=> Add arguments to conversation message notification events.

library/core/class.format.php
=> Fix Gdn_Format::serialize() double encoding detection

applications/dashboard/views/settings/helper_functions.php, applications/dashboard/views/settings/tutorials.php
=> Tweak some of the help & tutorial code

applications/dashboard/controllers/class.settingscontroller.php
=> Remove hidden locales from settings listings unless they are enabled

applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/models/class.importmodel.php, applications/dashboard/views/error.master.php, library/core/class.upload.php, library/core/functions.general.php, plugins/Tagging/class.tagmodule.php, plugins/VanillaInThisDiscussion/class.inthisdiscussionmodule.php
We are getting scrutinized for these things.
=> Remove @error suppression in a few places

.gitignore, phpunit.xml.dist, tests/Library/Core/ControllerTest.php
Split the unit tests into their own suite. Also ignore the test cache folder.
=> Tweak PHPUnit config

applications/conversations/settings/stub.php, applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/models/class.activitymodel.php, applications/dashboard/models/class.attachmentmodel.php, applications/dashboard/models/class.dbamodel.php, applications/dashboard/models/class.logmodel.php, applications/dashboard/models/class.usermodel.php, applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, library/core/class.authenticationprovidermodel.php, library/core/class.model.php, library/core/class.session.php, library/core/functions.general.php, library/core/functions.render.php, library/database/class.dataset.php, plugins/Quotes/class.quotes.plugin.php, tests/Library/Core/ArrayFunctionsTest.php
This update refactors encoding and decoding of certain values, primarily `Attributes`, stored in the database.
Closes #3685
=> Refactor database serialization calls

applications/dashboard/models/class.usermodel.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/settings/class.hooks.php, plugins/Tagging/class.tagging.plugin.php, plugins/editor/class.editor.plugin.php
Fixes scrutinizer reference assignment spacing.
=> Fix scrutinizer reference assignment spacing.

applications/dashboard/models/class.activitymodel.php
These variables are not being used. I can't find any evidence of them ever being used, so I believe they're able to be safely deleted.
=> Remove unused and undefined variables from mergeActivities method.

applications/dashboard/models/class.importmodel.php
This method has been made public to provide support to addons that wish to have some import functionality.
=> Add ImportModel->loadTableInsert()

applications/dashboard/models/class.usermodel.php
These are issues reported by Scrutinzer and could lead to future bugs.
=> Fix some UserModel doc blocks and remove some dead code

applications/conversations/settings/class.hooks.php
=> Fix conversations permission check when adding button.

js/global.js, js/library/jquery.popup.js
Also rename internal method from *Start to *Trigger.
=> Rename start event to contentLoad.

applications/dashboard/views/rss.master
=> Fix RSS title encoding and some caps

applications/vanilla/views/modules/helper_functions.php
Fix https://github.com/vanilla/vanilla/issues/3725
=> Pass the correct format to Gdn_Format::plainText

plugins/ProfileExtender/class.profileextender.plugin.php
Handles the special case of birthdays on utility/exportprofiles. Birthdays are saved on the User table.
=> Handle Birthdays in Profile Extender exporter.

applications/dashboard/views/search/index.php, library/core/class.form.php, library/vendors/SmartyPlugins/function.searchbox.php
Improves accessibility and addresses https://github.com/vanilla/vanilla/issues/3697
=> Add aria labels to search form fields.

applications/dashboard/models/class.updatemodel.php
- Privatize protected methods.
- Remove underscore from method names.
- Remove dead code.
- Remove unused parameters.
=> Fix inspection issues in the UpdateModel

applications/dashboard/controllers/class.entrycontroller.php
Although this won’t do anything when browsed to it really shouldn’t be an endpoint.
=> Make /entry/target internal

plugins/ProfileExtender/class.profileextender.plugin.php
This gives themes the ability to override the view.
=> Use fetchViewLocation instead of getView in ProfileExtender

library/core/class.proxyrequest.php
Do not set the response information (ResponseStatus, ContentType...) if it failed.
=> Fix the state of a ProxyRequest when it timeouts

applications/dashboard/controllers/class.logcontroller.php
Allows mods to view the logs for records created by a given user.
=> Give an interface for logs to be queried based on the recordUserID

applications/dashboard/settings/structure.php
This removes @error suppression.
=> Use touchFolder() in the dashboard structure

library/database/class.sqldriver.php
You can specify an increment/decrement operation in the SQL driver by adding a +/- after the field name followed by the increment as the value.
Example:
```php
Gdn::sql()->put(‘User’, [‘CountComments+’ => 1]);
```
=> Support increment/decrement in SQL updates

applications/dashboard/models/class.logmodel.php
This includes non-functional changes in the LogModel.
- Short array syntax.
- Add missing doc blocks.
- Correct casing.
- Remove unused local variables.
=> LogModel cleanup

applications/dashboard/models/class.usermodel.php
Clean up comments, coding style, etc. in the UserModel. This includes no material functionality changes.
=> Clean up UserModel

applications/dashboard/models/class.activitymodel.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/modules/class.recentactivitymodule.php, library/database/class.dataset.php
- Code casing.
- Doc blocks.
- Unused variables.
=> Clean up inspection issues with the ActivityModel

applications/vanilla/modules/class.discussionssortfiltermodule.php, applications/vanilla/views/modules/discussionssortfilter.php
Allows the discussion module renderer to opt out of showing sorts or filters.
=> Opt out of sort/filter rendering

js/embed.js, js/embed_local.js
=> Revert "Pass URL query through embed"

index.php, js/global.js
Addresses issue where edit comment textareas are not resizing.
=> Add contentLoad to autosizeTriggers.

library/core/class.logger.php, library/core/functions.general.php
- Add Logger::addLogger().
- Add Logger::removeLogger().
- Add Logger::getLevels().
- Change Logger::setLogger().
See the testing notes on the linked PR.
Closes #3824.
=> Implement Logger wrapper methods

applications/vanilla/views/discussion/discussion.php
This event is for discussion lists, not discussions.
=> Remove beforeDiscussionMeta event

library/core/class.statistics.php
This will used to make light API calls against the stats server.
=> Add Gdn_Statistics::generateAccessToken()

library/core/functions.compatibility.php, library/core/functions.general.php
Some compatibility functions where in `functions.general.php` instead of `functions.compatibility.php`
=> Move compatibility functions to the correct file.

applications/dashboard/models/class.activitymodel.php
This helps prevent the activity table from growing out of control. Requires #3954.
=> Make activities prune after 2 months

.gitignore, tests/README.md
* Revise & add to phpunit README.
* Add `/cgi-bin/` to gitignore.
=> Improve phpunit docs

plugins/Tagging/class.tagging.plugin.php
The pagination code was already there but the pager was not displayed due to some missing code.
=> Fix the tagged endpoint's pager

applications/conversations/controllers/class.messagescontroller.php, applications/conversations/models/class.conversationmessagemodel.php, applications/conversations/models/class.conversationmodel.php, applications/conversations/modules/class.addpeoplemodule.php, applications/conversations/settings/class.hooks.php
Just picking away at some of our Scrutinizer issues. PRs like this are often easier to go through commit-by-commit.
=> Fix code issues in the messages controller

applications/dashboard/views/profile/preferences.php
The notification preferences view has a minor bug which you can only see if you create an additional notification type beside Email and Popup via `profileController_afterPreferencesDefined_handler`. When a checkbox should be ommitted, three additional(!) checkboxes will be printed instead. Use this for a quick test:
~~~
public function profileController_afterPreferencesDefined_handler($sender) {
foreach ($sender->Preferences as $preferenceGroup => $preferences) {
foreach ($preferences as $name => $description) {
$nameParts = explode('.', $name);
$sender->Preferences[$preferenceGroup]['Whatever.'.$nameParts[1]] = $description;
}
}
}
~~~
Taken a look at the view made me shiver. That's the first time I've seen ugly spaghetti code in Vanilla and that's why I did not only solved the problem, …
=> Correct minor bug in notifications preferences.

library/core/class.format.php
=> Terminate unquoted mentions before apostrophes

applications/dashboard/models/class.usermodel.php, applications/dashboard/settings/structure.php, library/core/functions.general.php, library/core/functions.render.php
Move saving IP addresses from `AllIPAddresses` field in the `User` table to a separate, new table: `UserIP`.
Closes #3906
Closes #3808
Addresses half of #3809
=> Migrate AllIPAddresses field to new UserIP table

applications/vanilla/views/discussion/helper_functions.php
`$canDismiss` has to take log in status of user into consideration.
=> Hide "Dismiss" option from guests

library/vendors/Auth/Yadis/ParseHTML.php, library/vendors/phpmailer/class.phpmailer.php
The e modifier was removed from PHP7
=> Replace preg_replace regexes using the e modifier with preg_replace_callback

library/core/class.thememanager.php
Fixes issue where a themehook's setup and onDisable methods are not being respected.
Closes https://github.com/vanilla/lithe/issues/50
=> Call setup and onDisable methods in themehooks

applications/dashboard/controllers/class.rolecontroller.php, applications/dashboard/views/role/edit.php
The title (html tag) was wrong for rolecontrollers edit method. The title in the view was correct since it did not rely on $this->data('Title'). I've also corrected that.
=> Use correct title for Edit Role

applications/dashboard/js/profile.js, index.php
Fixes IE javascript errors when trying to upload a new avatar.
Closes https://github.com/vanilla/vanilla/issues/4139
=> Fix closest invocation on avatar upload

applications/dashboard/controllers/class.profilecontroller.php, applications/dashboard/views/profile/picture.php
Closes https://github.com/vanilla/vanilla/issues/4144
=> Allow for the possibility of differently named photo upload directories

applications/dashboard/models/class.usermodel.php
=> Deprecate UserModel->definePermissions() with serialization

library/core/class.dispatcher.php
This is the first in many, progressive dispatcher updates. I'm going to make successive PRs that build on one-another so that they can get merged more granularily.
Follow the commits in this PR to understand what's going on here. These are mostly just extract method refactors.
=> Gdn_Dispatcher untagling, part 1

applications/dashboard/controllers/class.messagecontroller.php
* Add message target "Categories Page"
* Add missing docs.
* Cleanup some arrays in MessageController.
Closes #4091
=> Add categories page as Message target

plugins/AllViewed/class.allviewed.plugin.php
* Require `POST` and tk check on Mark All Viewed actions.
* Remove use of `HTTP_REFERER` redirects.
* Clean up code standards.
Closes #4104
=> Add TK check and remove redirect from AllViewed

applications/dashboard/controllers/class.entrycontroller.php
Fixes issue where string is not translatable.
=> Wrap Connection error in t function

applications/vanilla/views/discussion/helper_functions.php
"Display ip address before CommentInfo to be on par with Discussions"
=> Display ip address before CommentInfo to be on par with Discussions.

library/core/class.dispatcher.php
This is code left over from previous refactoring. Depends on #4160.
=> Remove unused Gdn_Dispatcher code

library/core/class.dispatcher.php
This was another rebase error.
=> Fix delivery type for RSS

applications/vanilla/models/class.categorymodel.php
Update a category's cached data when its sort position is updated.
=> Set the cache when categories are sorted

applications/vanilla/library/class.categorycollection.php
This need to be backported in release/1607 for the knot.
=> Increase CategoryCollection's absoluteLimite to 300.

plugins/VanillaInThisDiscussion/class.inthisdiscussionmodule.php
So it can be selected and styled.
=> Add classes to In This Discussion's panel box

library/core/class.dispatcher.php
This is a kludge that will be deprecated shortly. Closes vanilla/multisite#62.
=> Allow controller initialize methods to augment dispatch arguments the old way

js/embed_local.js
Fixes https://github.com/vanilla/vanilla/issues/4185
=> Scroll to the top (inside the iframe) when we change page!

applications/dashboard/models/class.updatemodel.php
This clears out a bunch of notices.
=> Make UpdateModel->runStructure() parameter optional

js/global.js
If you wrap the image you end up not being able to follow the original link....
=> Do not wrap images that are already in an anchor.

library/core/class.dispatcher.php
When calling Gdn_Dispatcher->dispatch() multiple times the previous delivery type/method should be maintained to support backwards compatibility. In all honestly, this behavior is bad because it necessarily relies on object pollution, but since we have a lot of code depending on it then we have to support it.
This is method is slightly different than the previous method and is not without potential issues as was the previous method so let me explain some things.
The previous method managed to Mr. Magoo its way into working in a sensible way with two pieces of behavior:
1. When dispatching to a .json endpoint then Gdn_Dispatcher would override its own delivery type/method that would then be used for subsequent requests.
2. When re-dispatching the current query string is used even if the …
=> Keep the current delivery type/method between dispatches

applications/dashboard/design/cropimage.css
Fix https://github.com/vanilla/vanilla/issues/4270
=> Fix defaultavatar buttons being pushed to the bottom of the page.

applications/dashboard/models/class.usermodel.php
Serve the profile pictures properly.
=> Fix photos' URL for /user/summary

applications/dashboard/views/deverror.master.php, applications/dashboard/views/error.master.php
=> Do not send noindex on errors

applications/dashboard/controllers/class.usercontroller.php
=> Do not revalidate username on edit if no change

library/database/class.mysqlstructure.php
Closes #1788 
Adds a parameter to _defineColumn that allows it to be safely compatible with the renameColumn method.
=> Fix renameColumn() so it works for the first time ever

applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/controllers/class.discussionscontroller.php
=> Add announcements to RSS

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/models/class.banmodel.php
Fixes #1686 
I've chosen to omit blocking moderators from being banned. Blocking the super admin is good enough.
=> Prevent insane bans

applications/vanilla/controllers/class.postcontroller.php
Fix https://github.com/vanilla/vanilla/issues/3656
I decided not to do anything with the body since it is does not impact the UX much.
=> Trim all control characters from discussion title.

applications/dashboard/models/class.usermodel.php
Closes #2258
This is a limited case and we already have an index on the Name column so I do not foresee any scaling issue here.
=> Allow numeric name search for exact matches

applications/dashboard/views/profile/preferences.php, applications/vanilla/views/vanillasettings/notificationpreferences.php
Closes #2074
I acknowledge this adds logic to a view, but submit that those views need a massive refactor and this does not significantly increase the scope of that effort.
=> Hide email preferences when email is disabled

applications/dashboard/views/profile/picture.php
Added classes to make it easier to target these buttons in CSS.
=> Add a classes to upload and remove picture buttons

applications/vanilla/views/categories/all.php
Closes #2064 
Thanks @peregrine-web
=> Remove Category RSS icon when DisplayAs is 'Categories'

applications/dashboard/models/class.assetmodel.php
Closes #2032
Assigning @tburry since it was his suggestion in the original issue.
=> Increase the sort of custom.css to 1000

applications/vanilla/models/class.categorymodel.php, applications/vanilla/modules/class.flatcategorymodule.php, applications/vanilla/views/modules/flatcategory.php, js/global.js
This update adds a filter/search box to the top of the flat category module.  Text entered here is used to filter the displayed categories by name.
=> Add filtering to flat category module

library/core/functions.render.php
Depends on https://github.com/vanilla/vanilla/pull/4352
Kind of related to this issue: https://github.com/vanilla/vanilla/issues/4308 (SSO names)
=> Encode slashes in users's name.

js/library/jquery.popup.js
=> Set popup overflow-y to auto

applications/dashboard/views/profile/activity.php, applications/dashboard/views/profile/connections.php, applications/dashboard/views/profile/invitations.php, applications/dashboard/views/profile/notifications.php, applications/dashboard/views/profile/picture.php
Some of the edit profile pages were using an h2 for the title of the page. I changed them to h1s.
=> Changed h2s for h1s for a few edit profile pages

applications/dashboard/models/class.rolemodel.php, applications/dashboard/models/class.usermetamodel.php, applications/dashboard/views/modules/userinfo.php, applications/vanilla/modules/class.bookmarkedmodule.php, applications/vanilla/modules/class.promotedcontentmodule.php, library/core/functions.deprecated.php, plugins/SplitMerge/views/mergediscussions.php, plugins/Tagging/class.tagmodel.php
Fix https://github.com/vanilla/vanilla/issues/3701
=> Replace consolidateArrayValuesByKey by array_column

applications/dashboard/js/dashboard.js, applications/dashboard/js/src/modal.dashboard.js
Because I like it to close when I press ESC (without having to click on it)
=> Give focus to the modal dialog when opening it

applications/dashboard/models/class.assetmodel.php
Theme option css should follow custom.css.
=> Change order of theme option css

applications/vanilla/views/discussion/helper_functions.php
The addLinkIf() function handles the url-ing.
=> Fix double url in discussion dropdown

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/modules/class.dashboardnavmodule.php, applications/dashboard/settings/class.hooks.php, plugins/VanillaStats/class.vanillastats.plugin.php
Ensure permission in for the navigation link is the same as the permission for the page itself.
Ensure that a section's landing page will be a page that a user has permission to see.
=> Resolve issues with dashboard permissions

applications/dashboard/models/class.activitymodel.php
Backport of https://github.com/vanilla/vanilla/pull/4481 to 2.3
=> Add BeforeCheckPreference event to ActivityModel

applications/dashboard/controllers/class.homecontroller.php
Fixes issue where 404s are borked for non-logged-in users.
=> Check for session before trying to fix user navigation preferences

plugins/VanillaStats/class.vanillastats.plugin.php
This update increments the VanillaStats plug-in version number.
=> Update VanillaStats version

applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/views/discussions/helper_functions.php, applications/vanilla/views/discussions/table_functions.php
Replace https://github.com/vanilla/vanilla/pull/4390
Fix #4196
=> Treat discussion's name with no word character as empty

plugins/editor/class.editor.plugin.php, plugins/editor/js/editor.js
One of our clients pointed out the file upload wasn't translating and I noticed the strings were hard coded.
=> Modified the file upload to make the text translatable.

library/core/class.oauth2.php
Created a generic class that can be extended to (almost) any class that performs SSO using the OAuth2 spec.
This class has been tested extending several existing OAuth2 plugins all ready in use. It would require a minimum of changes to the code and configuration to base them off this class.
=> Create a core class as a base for OAuth2 connections

applications/dashboard/controllers/class.profilecontroller.php, applications/vanilla/settings/class.hooks.php
Add missing js files.
Fix https://github.com/vanilla/vanilla/issues/4538.
=> Fix avatar cropping in profile

plugins/Tagging/js/tagging.js
Fix https://github.com/vanilla/vanilla/issues/4298
=> [Tagging] Allow to tab out of the tokenInput field

applications/dashboard/settings/class.hooks.php
Check proper permissions!
https://github.com/vanilla/vanilla/blob/5db541f6721edb6711eaed8406f26287f904a724/applications/dashboard/controllers/class.logcontroller.php#L161
https://github.com/vanilla/vanilla/blob/5db541f6721edb6711eaed8406f26287f904a724/applications/dashboard/controllers/class.logcontroller.php#L179
:)
=> Fix permission check for Change Log page

composer.json, composer.lock
This is a package we’ll be using shortly.
=> Add container-interop and the Garden namespace to composer.json

applications/dashboard/controllers/class.importcontroller.php, applications/dashboard/js/import.js, applications/dashboard/views/import/go.php, applications/dashboard/views/import/index.php, applications/dashboard/views/import/info.php, applications/dashboard/views/import/stats.php
Functionality is fixed with this PR, but form styling relies on https://github.com/vanilla/vanilla/pull/4539 The .progress css class is not styled yet but will be in with another PR.
Closes https://github.com/vanilla/vanilla/issues/4402
Closes https://github.com/vanilla/vanilla/issues/4401
=> Fix styling of import settings

applications/dashboard/views/modules/dropdown.php
Tooltip was untranslatable on option button
=> Fixed tooltip translation on option button

applications/conversations/views/messages/all.php, applications/conversations/views/messages/popin.php, applications/dashboard/views/activity/popin.php, applications/dashboard/views/profile/notifications.php, applications/vanilla/views/discussions/popin.php, applications/vanilla/views/drafts/index.php
This PR does essentially what PR https://github.com/vanilla/vanilla/pull/4395 but supplies the old concatenated translation as a default.
=> Translate flat strings to accommodate gender in other languages

applications/vanilla/views/categories/subtree.php
This update adds the categories/subtree view back in, populating it with the code originally used to replace it.
=> Re-add categories/subtree view

applications/dashboard/models/class.invitationmodel.php
=> Simplify phpMailer try/catch in InvitationModel

applications/dashboard/views/modules/configuration.php, library/core/class.form.php
Add image upload dashboard styling to form simple and the configuration module. Also add some missing docs to the form object.
=> Add options for rendering image upload

library/core/class.controller.php, library/core/functions.general.php
Fix: https://github.com/vanilla/vanilla/issues/4599
=> Fix truncated encoded data when binary representations of IP addresses are present

applications/dashboard/views/user/applicants.php
This update applies formatting to the IP address column on the list of applicants.
=> Use ipAnchor to format IP addresses on list of applicants

plugins/GooglePlus/views/settings.php
=> Fix link to Google Plus docs

plugins/Twitter/views/settings.php
=> Fix link to Twitter docs

plugins/Facebook/views/settings.php
=> Fix link to Facebook docs

applications/vanilla/js/discussion.js
This can happen with the QnA plugin having QnA.AcceptedAnswers.Filter set to false!
Fix https://github.com/vanilla/addons/issues/386
=> Update comments that are multiple time in the same page

applications/dashboard/settings/class.hooks.php
=> Add version warning to settings pages

applications/dashboard/views/log/edits.php, applications/dashboard/views/log/moderation.php, applications/dashboard/views/log/record.php, applications/dashboard/views/log/spam.php
Fixes issue where pager isn't appearing any longer.
Closes https://github.com/vanilla/vanilla/issues/4531
=> Add pager to log views

applications/vanilla/modules/class.discussionssortfiltermodule.php
Fixes issue where dropdown filter in Ideation doesn't work with subcommunities.
=> Fix double url in sort filter module

applications/dashboard/controllers/class.setupcontroller.php, conf/config-defaults.php, library/core/class.request.php
=> Improve install experience for future

plugins/Quotes/class.quotes.plugin.php
fix: https://github.com/vanilla/vanilla/issues/4442
=> Make sure to show the quote button only if you have permission to post

applications/dashboard/js/jquery.tablejenga.js
Optimize and document tablejenga and add support for colspans.
Closes https://github.com/vanilla/vanilla/issues/4431
=> Optimize tablejenga

applications/conversations/settings/class.hooks.php
Make the "Message" option in profile options work for all characters.
https://github.com/vanilla/vanilla/pull/4286
=> Backport PR #4286 to Vanilla 2.3

library/core/class.session.php
Let the stash method use a local clone of the sql class. Backport of https://github.com/vanilla/vanilla/pull/4499
=> Backport PR #4499 to Vanilla 2.3

plugins/IndexPhotos/class.indexphotos.plugin.php
https://github.com/vanilla/vanilla/pull/4325
Fixes issues with index photos on mobile table layout
=> Backport PR #4325to Vanilla 2.3

applications/conversations/controllers/class.messagescontroller.php
Let /messages/add accept recipient (which will be validated) and subject
https://github.com/vanilla/vanilla/pull/4221
https://github.com/vanilla/vanilla/pull/4288
=> Backport PR #4221 and #4288 to Vanilla 2.3

applications/vanilla/models/class.commentmodel.php
Add $Comment to event arguments in BeforeDeleteComment
https://github.com/vanilla/vanilla/pull/4124
=> Backport PR #4124 to Vanilla 2.3

applications/vanilla/views/discussion/helper_functions.php
Hide "Dismiss" option from guests
https://github.com/vanilla/vanilla/pull/4099
=> Backport PR #4099to Vanilla 2.3

applications/vanilla/controllers/class.postcontroller.php
Don't add NewDiscussionModule to postcontroller
https://github.com/vanilla/vanilla/pull/4081
=> Backport PR #4081 to Vanilla 2.3

plugins/GooglePlus/class.googleplus.plugin.php
Don't show Google+ login when not configured
https://github.com/vanilla/vanilla/pull/3745
=> Backport PR #3745 to Vanilla 2.3

js/library/jquery.popup.js
Fix "Signin popup displays scrollbar when not needed"
https://github.com/vanilla/vanilla/pull/4223
=> Backport PR #4223 to Vanilla 2.3

applications/dashboard/js/dashboard.js, applications/dashboard/js/src/main.js, applications/dashboard/js/src/modal.dashboard.js, applications/dashboard/views/settings/banner.php
Also ensure non-hijack confirm modals don't make ajax calls.
Closes https://github.com/vanilla/vanilla/issues/4461
=> Confirm that user wants to delete images before deleting

applications/conversations/settings/class.hooks.php
Fix conversations permission check when adding button.
https://github.com/vanilla/vanilla/pull/3764
=> Backport PR #3764 to Vanilla 2.3

applications/vanilla/models/class.categorymodel.php
Fire "CategoryWatch" and "AllowedDiscussionTypes" as events of CategoryModel
https://github.com/vanilla/vanilla/pull/3740
=> Backport PR #3740 to Vanilla 2.3

plugins/OpenID/class.openid.plugin.php
Prevent errorneous rendering when OpenID url is invalid
https://github.com/vanilla/vanilla/pull/3742
=> Backport PR #3742 to Vanilla 2.3

applications/vanilla/controllers/class.vanillasettingscontroller.php, applications/vanilla/views/vanillasettings/addcategory.php
Fixes issue where category photos don't save on category creation.
Closes https://github.com/vanilla/vanilla/issues/4472
=> Add Photo upload to addCategory method

plugins/Flagging/views/flagging.php
Add the <tr> tags on the *inside* of the for loop.
=> Fix Flagging view

plugins/Flagging/views/flagging.php
Tweak flagging view css classes.
=> Tweaks to flagging settings view css classes

applications/dashboard/modules/class.headmodule.php, applications/dashboard/scss/src/_toolbar.scss, applications/dashboard/views/admin.master.php, applications/dashboard/views/modules/nav-adventure.php, applications/dashboard/views/modules/nav-dashboard.php, applications/dashboard/views/modules/pager-dashboard.php
Remove type attributes in style and script elements.
Put pagers in a nav element.
Add nav element to side menu.
Remove nav element from nav-adventure.
Add HTML5 elements to admin.master template.
=> HTML5 tweaks

library/core/class.oauth2.php, plugins/oauth2/class.Oauth2.plugin.php
Fix App version in OAuth2 plugin, remove an extra line of code in core OAuth2 class
=> Minor tweaks to OAuth2 plugin and core class.

applications/dashboard/scss/src/_type.scss, applications/dashboard/views/embed/comments.php, applications/dashboard/views/embed/forum.php, applications/dashboard/views/embed/settings.php, applications/dashboard/views/embed/universal.php, applications/dashboard/views/embed/wordpress.php, applications/dashboard/views/import/index.php, applications/dashboard/views/log/moderation.php, applications/dashboard/views/message/index.php, applications/dashboard/views/role/edit.php, applications/dashboard/views/role/index.php, applications/dashboard/views/routes/index.php, applications/dashboard/views/settings/avatars.php, applications/dashboard/views/settings/banner.php, applications/dashboard/views/settings/bans.php, applications/dashboard/views/settings/defaultavatar.php, applications/dashboard/views/settings/emailstyles.php, applications/dashboard/views/settings/themeoptions.php, applications/dashboard/views/social/manage.php, applications/dashboard/views/user/index.php, applications/vanilla/views/vanillasettings/categories.php, applications/vanilla/views/vanillasettings/floodcontrol.php, library/core/functions.render.php, plugins/Flagging/views/flagging.php, plugins/ProfileExtender/views/settings.php, plugins/Tagging/views/tagging.php
Revisit markup in type elements.
Add section tags around sections.
=> Add and implement header rendering functions

applications/vanilla/controllers/class.postcontroller.php
Fix https://github.com/vanilla/vanilla/issues/4648
=> Do not validate title when a draft is saved

applications/dashboard/models/class.usermodel.php
Add AllIPAddresses to our list of filtered User save fields
=> Fix issue with saving users directly via model after IP address changes

applications/conversations/views/messages/popin.php, library/core/functions.render.php
Fix https://github.com/vanilla/vanilla/issues/4561
=> Allows UserPhoto to not be clickable

applications/dashboard/models/class.importmodel.php, applications/dashboard/models/class.rolemodel.php
Fix https://github.com/vanilla/vanilla/issues/3796
=> Clean invalid relation between users and roles

applications/dashboard/scss/src/_buttons.scss, applications/dashboard/scss/src/_forms.scss, applications/dashboard/views/user/index.php, library/core/class.form.php, plugins/Tagging/views/tagging.php
Adds and implements rendering functions for search forms.
Only renders a clear button if a query has been performed.
Find pre-whitespace-changes for tagging.php here: https://github.com/vanilla/vanilla/commit/7c5c668826e081dbebf43b4061dd07182c6940f5
=> Add and implement rendering functions for search forms

applications/dashboard/scss/legacy/_category-settings.scss, applications/dashboard/scss/src/_buttons.scss, applications/dashboard/scss/src/_variables.scss, applications/dashboard/views/modules/dropdown-twbs.php, applications/vanilla/views/vanillasettings/category-settings-functions.php
Reset button styling, remove unused css rules, and add trigger properties to twbs view. Also clean up variable sheet.
=> Tweak category settings page

applications/dashboard/js/jquery.fluidfixed.js, applications/dashboard/scss/src/_card.scss, applications/dashboard/scss/src/_forms.scss, applications/dashboard/scss/src/_panel.scss, applications/dashboard/scss/src/_tables.scss, applications/dashboard/views/settings/themes.php, applications/vanilla/views/vanillasettings/editcategory.php
Add back button to add/edit category header.
Make theme link an external link icon.
Tweak spacing on table icons.
Make control panel heading an h2 element.
Tweak spacing.
=> SCSS, js, and view tweaks

applications/dashboard/modules/class.headmodule.php
Fix https://github.com/vanilla/vanilla/issues/4719
=> Add meta tags for Twitter cards

applications/dashboard/controllers/class.dashboardcontroller.php
=> Fix annoying warning about magnific-popup.css

applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/models/class.discussionmodel.php
$Offset was never set in the function.
=> Fix DiscussionModel::getAnnouncement() offset

applications/dashboard/views/modules/pager-dashboard.php
Use PagerModule::hasMorePages()
=> Fix dashboard pager next button when there are 0 results

applications/dashboard/library/class.emailtemplate.php
Add functionality to remove button from email.
=> Add functionality to remove button from email

applications/dashboard/controllers/class.usercontroller.php
The ban page contains links to the user page that uses a `Filter` parameter.  This parameter has some special considerations, allowing wildcards to be used for its values.  Currently, the IP user search is not functional from this page.  These searches rely on a DB function (`inet6_ntoa`) to convert packed IP addresses their human-readable values, before they're compared against wildcards.  These functions are being filtered out, so the search is failing.
This update alters `UserController::_getFilter` to allow the usage of whitelisted DB functions.
In addition, I came across a notice where `array_pop` need a value that could be passed by reference, so now it has that.
Closes #4754
=> Fix IP filtering on user management page

applications/vanilla/modules/class.discussionsmodule.php, applications/vanilla/views/modules/discussions.php, applications/vanilla/views/modules/helper_functions.php, plugins/IndexPhotos/class.indexphotos.plugin.php
* Adds a showPhotos option for the discussions module to display the avatar of the discussion author.
* Updates the Index Photos plugin description to be more exclusive.
Closes https://github.com/vanilla/vanilla/issues/4771
=> Add showPhotos param in discussions module

applications/dashboard/views/admin.master.php, applications/dashboard/views/settings/mobilethemes.php, applications/dashboard/views/settings/themes.php, library/core/functions.render.php
Fixes issue where an inline svg has a space inserted before it.
=> Ensure svg icons have no white space around them

applications/dashboard/views/settings/banstable.php
The delete button will now work :)
=> Make ban's delete button issue a post request with valid transient key

library/core/functions.render.php
Type hint the function to be sure we receive an array for $attr
=> Fix "Cannot use assign-op operators with overloaded objects nor string offsets" error

applications/dashboard/controllers/class.messagecontroller.php, applications/dashboard/views/message/index.php
Otherwise you endup on `/dashboard/message/delete/12/{TransientKey}` with TRUE as the content of the page
=> Add js-hijack on messages delete button

applications/dashboard/views/modules/userphoto.php
=> Fix standards in userphoto view

applications/dashboard/modules/class.headmodule.php
Fixes https://github.com/vanilla/vanilla/issues/4777
=> Remove itemprop attributes from meta tags

applications/dashboard/models/class.usermodel.php
Add GivenPoints, Source and Timestamp to the givePoints event
=> Add more information to the GivePoint event.

applications/vanilla/views/modules/helper_functions.php
Add hidden comment count meta item in the Discussions Module.
Closes https://github.com/vanilla/vanilla/issues/4799
=> Add hidden comment count meta item in the Discussions Module

library/core/class.configuration.php
Allows the ksort sort flag to be set in the configuration class.
=> Allow the ksort sort flag to be set in the configuration class

applications/dashboard/Gruntfile.js, applications/dashboard/bower.json, applications/dashboard/js/dashboard.js, applications/dashboard/js/src/main.js, applications/dashboard/js/vendors/jquery.checkall.min.js, applications/dashboard/settings/class.hooks.php, applications/dashboard/template/public/admin.css
Adds check-all functionality to the dashboard js.
=> Add check-all jquery plugin to dashboard

applications/dashboard/controllers/class.profilecontroller.php
Fixes https://github.com/vanilla/multisite/issues/8
Internal re-dispatching is buggy when subcommunities.
I'm not gonna play with that (for now at least) so here is an easy fix!
I've filled an issue about the dispatcher: https://github.com/vanilla/vanilla/issues/4867
=> Use redirect instead of internal dispatching

applications/dashboard/models/class.activitymodel.php
Also allow relative dates to be specified as a positive or negative date.
=> Add support for activity prune config setting

applications/vanilla/views/discussion/helper_functions.php
closes #4829 - further notes on that issue.
=> Remove tabindex from comment embed submit button

applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/views/post/discussion.php
=> Change "cancel" action on edit discussion to redirect to single discussion view

applications/dashboard/js/dashboard.js, applications/dashboard/js/src/main.js, applications/dashboard/scss/src/_card.scss, applications/dashboard/scss/src/_icons.scss, applications/dashboard/styleguide/public/dashboard.js, applications/dashboard/styleguide/section-12.html, applications/dashboard/styleguide/section-3.html, applications/dashboard/template/public/dashboard.js, applications/dashboard/views/admin.master.php
Makes the drop content configurable by allowing the specification of the content selector. Applies this to the user dropdown in the dashboard and adds documentation to the styleguide.
=> Let dropdown cards be configurable

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/views/entry/connect.php
Fixes https://github.com/vanilla/vanilla/issues/4551
Also fix a bug where the username field would appear on the form if the email validation (or any validation) failed.
=> Validate email if it was not set by the provider

applications/dashboard/views/user/edit.php
Also fix a few coding standards issues in the form view.
Closes #4844
=> Disable autocomplete on edit user fields 

applications/dashboard/views/user/index.php
=> Improve user search tips text

tests/APIv0/SmokeTest.php
This update adds a couple things to our automated testing:
1. The creation of a restricted ("Moderators Only") category, with permissions stripped so that only users with moderator permissions or better can access it.
2. The addition of tests to verify users cannot access, to post or view, the contents of the restricted category.
This branch is based off (and depends on) #4901 
Closes #4902
=> Add integration test to verify category permissions

plugins/Quotes/class.quotes.plugin.php
Fixes https://github.com/vanilla/vanilla/issues/3329
=> Fix TextEx quote returning null

library/core/class.passwordhash.php
This is a backport PR of https://github.com/vanilla/garden-password/pull/3
Fixes https://github.com/vanilla/vanilla/issues/2545
=> Add xf12 authentication method

applications/dashboard/views/log/confirm.php
Fix https://github.com/vanilla/vanilla/issues/4697
Make the "All" checkbox actually check all other checkboxes!
=> Fix selectAll in the spam queue

applications/dashboard/modules/class.mediaitemmodule.php
Makes the view responsible for calling url on the titleUrl property.
Closes https://github.com/vanilla/vanilla/issues/4893
=> Let the media module views handle the url-ing of titleUrls

applications/dashboard/controllers/class.settingscontroller.php
Ensure a ban model exists before trying to use it.
=> Ensure ban model exists before using it

applications/dashboard/models/class.logmodel.php
Update the log model to display Group and Event record properly!
=> Handle Groups and Events display

applications/dashboard/settings/structure.php
Relate to https://github.com/vanilla/internal/pull/808#issuecomment-268060075
=> Add type Event to log table

library/core/class.configuration.php
Makes format options configurable in Gdn_Configuration.
=> Make format options configurable in Gdn_Configuration

applications/dashboard/models/class.usermodel.php
Fixes https://github.com/vanilla/vanilla/issues/4830
=> Prevent user's visit information from being updated if banned

plugins/editor/class.editor.plugin.php
Be more aggressive about disabling buttonbar.
=> Disable AdvancedEditor's conflicting plugins  on utility/update

plugins/Facebook/class.facebook.plugin.php
When connecting a Facebook account, [an optional `state` parameter can be used](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/#logindialog).  This update implements that parameter into the Facebook connect workflow.
=> Use state parameter when connecting with Facebook

applications/dashboard/controllers/class.dashboardcontroller.php, applications/dashboard/controllers/class.utilitycontroller.php
This was causing problem with pockets being included in the analytics section!
Need to be backported in at least release/1611
=> Specificy that we are in the dashboard when using the dashboard controller

applications/vanilla/library/class.categorycollection.php
This config needs to be increased in some specific cases.
=> Allow category query limit to be configurable

library/core/class.configuration.php
Fixes https://github.com/vanilla/vanilla/issues/5033
=> Fix Gdn_ConfigurationSource::save() when Configuration is null

applications/dashboard/views/log/table.php
Adds more date/time info to the moderation tables.
Closes https://github.com/vanilla/vanilla/issues/4909
=> Add more date/time info to the moderation tables

composer.json, composer.lock
Fixes https://github.com/vanilla/vanilla/issues/4842
Require the new `vanilla/legacy-passwords`
=> Require legacy-passwords

applications/dashboard/views/settings/avatars.php
Update EditPhotos config description.
=> Update EditPhotos config description

composer.json
=> Revert "Add YAML parser as a dependency"

applications/dashboard/models/class.mediamodel.php
Make sure that deleteID() removes files and thumbnails!
=> Implement deleteID and make sure it uses delete() which also remove local files

applications/dashboard/models/class.mediamodel.php
Do not forget to delete the thumbnail too :)
=> Delete thumbnails when deleting media in MediaModel->delete()

plugins/editor/class.editor.plugin.php
Depends on https://github.com/vanilla/vanilla/pull/5072 (Thumbnail deletion)
Fixes https://github.com/vanilla/vanilla/issues/5060
=> Use MediaModel instead of Gdn_Model('Media') in the editor plugin

plugins/editor/class.editor.plugin.php
Remove file extension from view.
=> Remove file extension from view

plugins/Flagging/class.flagging.plugin.php
Remove file extensions from flagging plugin views.
Closes https://github.com/vanilla/vanilla/issues/5079
=> Remove file extensions from flagging plugin views

applications/dashboard/controllers/class.profilecontroller.php
=> Allow JSON access to profile when ShowActivity is disabled

README.md
closes https://github.com/vanilla/vanilla/issues/2292
closes https://github.com/vanilla/vanilla/issues/4878
related to https://github.com/vanilla/vanilla/pull/5081
=> Update requirements and notes in README

applications/vanilla/models/class.discussionmodel.php
Fixes #2323 (see https://github.com/vanilla/vanilla/issues/2323#issuecomment-65359469)
=> Prevent discussions from having an invalid categoryID on creation

applications/dashboard/models/class.logmodel.php
=> Update category discussion and comment counts when restoring a record

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/views/entry/passwordreset.php
Depends on #5090
Fixes: #5048
Add validation on the reset password form! Min length, min score, password matching...
=> Validate password constraints on the reset password form

applications/dashboard/models/class.logmodel.php
Fixes https://github.com/vanilla/vanilla/issues/4950
=> Display IPAddress on blocked registrationss

library/Vanilla/ClassLocator.php, library/Vanilla/VanillaClassLocator.php, tests/Library/Vanilla/ClassLocatorTest.php, tests/Library/Vanilla/VanillaClassLocatorTest.php, tests/fixtures/src/SomeController.php
Currently we dispatch by looking up classes with class_exists() and method_exists(). We also use events though which is a Vanilla peculiarity. What I want to do is create a class abstraction on class/method locating so that we can modify the behavior more easily.
=> Add the ClassLocator

library/core/functions.render.php
=> Fix hasEditProfile return value

library/Vanilla/Addon.php
FIX THEM!
Cached the issues in the plugin infos!
Fixes: https://github.com/vanilla/vanilla/issues/5193
=> Addons now always trigger their issues

library/core/class.dispatcher.php
Now checks for admin permissions asap.
Make the function public so that you can call it from somewhere else!
=> Make Dispatcher::getCanBlock a public method

applications/dashboard/views/modules/configuration.php
This allows us to render the description for a Configuration Module toggle-type field.
=> Pass description to toggle in Configuration Module

applications/dashboard/controllers/class.messagecontroller.php
Break cache when changing Message status.
Also adds some docs.
=> Fix Message toggle not removing/adding message immediately

library/database/class.database.php
This is a bug that was uncovered during unit testing since Vanilla will always have a default config. Basically the following call:
```php
$defaultConfig = Gdn::config(‘Database’);
```
This returns **null** when there is no default config and then makes all the following array merges to come out null too.
Fixing that one line fixes the bug, but I couldn’t let this go without cleaning up the code. On inspection I think this is the first function I touched on Vanilla and represents a very novice understanding of the PHP language. It’s quite the nostalgia trip to look at it, but we certainly don’t need so many calls to val() anymore.
=> Allow the database to be instantiated when there is no default config.

applications/vanilla/controllers/class.postcontroller.php
Fixes https://github.com/vanilla/vanilla/issues/5203
=> Make sure to set discusion's categoryID when Vanilla.Categories.Use is false

applications/dashboard/views/modules/dropdown.php, applications/dashboard/views/modules/me.php
Adds attributes to dropdown view and add "Account Options" to me modules settings dropdown trigger.
Closes https://github.com/vanilla/vanilla/issues/5210
=> Add "Account Options" title back to MeModule settings dropdown

bootstrap.php, conf/constants.php
- Add the MYSQL_DATE_FORMAT constant.
- Deprecate the complete overriding of the constants file.
=> Vanilla constant tweaks

library/Garden/Web/ResourceRoute.php, library/Garden/Web/Route.php, tests/Library/Garden/Web/ResourceRouteTest.php, tests/fixtures/src/DiscussionsController.php, tests/fixtures/src/Request.php
- Rearrange some internal methods. Mainly switch some methods from working on parameter names to parameter reflection objects.
- Fix variadic route argument mapping.
- Add path mapping.
- Other miscellaneous fixes.
=> Add more resource routing fixes and options

applications/dashboard/models/class.userauthenticationnoncemodel.php
We are gonna put pruning on that model.
From https://github.com/vanilla/addons-patches/pull/4#issue-211833213
>  and pruning on the new model once the pruning trait is merged!
Sorry :)
=> Add the UserAuthenticationNonceModel

.travis.yml
Update Travis to include PHPUnit version compatible with their PHP 7.x image.
=> Update Travis to include PHPUnit

applications/dashboard/views/profile/picture.php
This button has a margin-bottom rule set inline. It messes with a bunch of themes and doesn't appear to be necessary.
=> Remove inline styles on upload picture button

library/Vanilla/AddonManager.php, tests/Library/Vanilla/AddonManagerTest.php, tests/fixtures/src/TestAddonManager.php
This method allows the application to search for classes based on a
glob-style match.
=> Add the AddonManager::findClasses() method

bootstrap.php
This will allow addons to find it.
=> Name the APIv2 route

library/Garden/Web/Route.php
This isn’t optimal, but I need it for Swagger right now.
=> Make Route::isMapped() public

library/Garden/EventManager.php, tests/Library/Garden/EventManagerTest.php
Allow addons to unbind their events.
=> Add EventManager::unbind()

themes/2011Compatibility/about.php, themes/EmbedFriendly/about.php, themes/bittersweet/about.php, themes/default/about.php, themes/mobile/about.php
We're going to hide all themes by default. As a first step, I want to explicitly set core themes to visible.
=> Explicitly set ‘Hidden’ to false for core themes

library/Vanilla/Permissions.php
=> Tweak some ban constants

applications/vanilla/controllers/class.discussionscontroller.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php
Unread was mostly removed from core already. I just deprecated more stuff!
Fixes https://github.com/vanilla/vanilla/issues/2417
=> Deprecate the unread feature since it does not scale

applications/dashboard/models/class.userauthenticationnoncemodel.php
Also add the missing new line at EOF
Fixes https://github.com/vanilla/vanilla/issues/5329
=> Add pruning to UserAuthenticationNonceModel

applications/dashboard/js/jquery.fluidfixed.js
Documents and tweaks the fluidfixed javascript.
Closes https://github.com/vanilla/vanilla/issues/5333
=> Document and refactor fluidfixed for clarity

themes/2011Compatibility/about.php, themes/EmbedFriendly/about.php, themes/bittersweet/about.php, themes/default/about.php, themes/mobile/about.php
We've changed the logic for theme visibility. Here's the fix to display Core Vanilla themes.
=> Fix for core theme visibility

library/Vanilla/Addon.php, library/Vanilla/Models/AddonModel.php, library/Vanilla/Models/InstallModel.php, tests/APIv2/InstallTest.php, tests/TestInstallModel.php, tests/phpunit.php
The purpose of this PR is to allow for easier installation of the application, mainly for testing.
Right now the application will not use this model, but some unit tests will.
=> Add the InstallModel

applications/dashboard/models/class.usermodel.php
This PR adds two events and two arguments into the UserModel to allow the SQL object to be manipulated.
=> Create events in UserModel to allow plugins to alter user search.

applications/vanilla/controllers/class.postcontroller.php
Prevent embed discussion creation if embed is not turned on
=> Prevent creation of embed comments if embedding is not ON

applications/dashboard/library/class.nestedcollection.php, applications/dashboard/modules/class.dashboardnavmodule.php, applications/dashboard/modules/class.dropdownmodule.php, applications/dashboard/modules/class.navmodule.php, applications/dashboard/modules/class.sitenavmodule.php, applications/dashboard/views/message/index.php, applications/dashboard/views/modules/dropdown-navbutton.php, applications/dashboard/views/modules/dropdown-twbs.php, applications/dashboard/views/modules/dropdown.php, applications/dashboard/views/modules/nav-adventure.php, applications/dashboard/views/modules/nav-dashboard.php, applications/dashboard/views/modules/nav.php
Refactor and document nav and nested collection classes and views.
Closes https://github.com/vanilla/vanilla/issues/5331
=> Refactor and document nav and nested collection classes

library/database/class.database.php
Fixes https://github.com/vanilla/vanilla/issues/5312
=> Set charset through PDO's dsn string

library/database/class.database.php
=> Condense 4 lines onto one. SUCH WOW -Doge

themes/default/about.php, themes/mobile/about.php
I had spaced the data in the about.php file to make it easier to read, but Travis doesn't like it.
=> Changed spacing to keep Travis happy

plugins/Facebook/class.facebook.plugin.php, plugins/Facebook/views/settings.php
Closes https://github.com/vanilla/vanilla/issues/5063
=> Remove facebook automatic social sharing feature

applications/dashboard/controllers/class.dashboardcontroller.php, applications/dashboard/controllers/class.setupcontroller.php, library/core/class.controller.php
Fixes https://github.com/vanilla/vanilla/issues/5351
=> Remove Garden.Cdns.Disable and always use local assets

library/Vanilla/Addon.php, library/Vanilla/AddonManager.php, tests/Library/Vanilla/AddonManagerTest.php, tests/fixtures/plugins/multiclass-namespaced-plugin/class.multiclass-namespaced-plugin.plugin.php, tests/fixtures/src/TestAddonManager.php
Fixes https://github.com/vanilla/vanilla/issues/5231
Based on / Add functionalities to https://github.com/vanilla/vanilla/pull/5345.
=> Update AddonManager findClasses function

library/Vanilla/VanillaClassLocator.php, tests/Library/Vanilla/VanillaClassLocatorTest.php, tests/fixtures/plugins/multiclass-namespaced-plugin/class.multiclass-namespaced-plugin.plugin.php
Fixes https://github.com/vanilla/vanilla/issues/5232
Based on / Add functionalities to #5383.
=> Use AddonManager->findClasses() in VanillaClassLoader

applications/conversations/settings/class.hooks.php
Fix https://github.com/vanilla/vanilla/issues/5258
Clean UserConversation and ConversationMessage properly
=> Delete all UserConversation entries when delete a user's content

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/settings/class.hooks.php, applications/dashboard/settings/structure.php, applications/dashboard/views/settings/tagging.php, applications/vanilla/controllers/class.discussionscontroller.php, applications/vanilla/modules/class.tagmodule.php, applications/vanilla/settings/class.hooks.php
https://github.com/vanilla/internal/pull/954 needs an update too.
=> Fix config name for tagging discussions

library/core/class.format.php
Fixes https://github.com/vanilla/vanilla/issues/2474
Related https://github.com/vanilla/vanilla/issues/5399
=> Format mentions early for markdown

applications/dashboard/settings/structure.php, plugins/Flagging/class.flagging.plugin.php
Depends on https://github.com/vanilla/vanilla/pull/5402
Partially addresses https://github.com/vanilla/vanilla/issues/5284
=> Fix index sizes for utf8mb4

applications/dashboard/views/settings/tagging.php
Tagging.Discussions.Enabled should not be "true" as default...
=> Fix the Enable Tagging toggle

applications/dashboard/settings/class.hooks.php, applications/dashboard/views/settings/tagging.php
Make sure the UI is properly updated when a tag is created/edited/deleted
Fixes https://github.com/vanilla/vanilla/issues/2463
=> Update the UI when modifying a tag

applications/dashboard/settings/class.hooks.php
The file was deleted. This PR removes it from the settingsController_tagging_create
=> Remove tagamin.js

library/Garden/Web/Exception/HttpException.php
Refactoring gone wrong: fixed!
=> Fix HttpException::jsonSerialize assignation

README.md
The badge from Travis can't have square corners, so the other two were rounded.
Fixes https://github.com/vanilla/vanilla/issues/5352
=> README - Rounded badges to keep them consistent

applications/dashboard/settings/class.hooks.php, applications/vanilla/js/tagging.js, applications/vanilla/views/discussion/helper_functions.php, applications/vanilla/views/discussion/tag.php
Fixes https://github.com/vanilla/vanilla/issues/2464
You can only add new tags as specified in the issue.
Adding a tag that already is linked to the discussion does nothing.
=> Add the Tag option to the discussion list menu

applications/conversations/models/class.conversationsmodel.php, applications/dashboard/models/class.activitymodel.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/models/class.vanillamodel.php, applications/vanilla/views/vanillasettings/floodcontrol.php, library/core/helpers/class.floodcontrolhelper.php
Backport to the latest release.
This will need to be pushed on all the clusters.
PM me if you want me to do the push.
=> Fix FloodControl configuration names for conversations

library/SmartyPlugins/function.nomobile_link.php
=> Fix casening on the class attribute

applications/dashboard/views/settings/helper_functions.php
This reverts commit e06a6cd6f24ffcb15cbe85b7f46697749e0be424.
=> Revert "Add debug information"

plugins/oauth2/class.Oauth2.plugin.php
Update the OAuth2Plugin to work with the fixed code from https://github.com/vanilla/vanilla/pull/5350
=> Properly set the setting view in OAuth2Plugin

library/core/helpers/class.floodcontrolhelper.php
Fixes https://github.com/vanilla/vanilla/issues/5434
=> Use UserModel::saveAttribute not setAttribute

themes/2011Compatibility/views/default.master.tpl
Added class to "Powered by Vanilla" container
=> Add PoweredByVanilla-Wrap  class to "Powered By Vanilla" wrapper

plugins/Facebook/class.facebook.plugin.php, plugins/GooglePlus/class.googleplus.plugin.php, plugins/IndexPhotos/class.indexphotos.plugin.php, plugins/Quotes/class.quotes.plugin.php, plugins/SplitMerge/class.splitmerge.plugin.php, plugins/Twitter/class.twitter.plugin.php
I got frisky in Quotes and killed a useless abstraction. Otherwise this is all adding, editing & deleting code comments.
=> Add & improve inline docs in some addons

applications/vanilla/models/class.categorymodel.php
When adding a new post, the aggregate counts for the category and its ancestors are updated. However, the "Latest Post" info is only being updated on the current category. This update alters `CategoryModel::updateLastPost` to refresh all its ancestors' "Latest Post" info, as well.
=> Refresh latest post info for all category ancestors

library/database/class.dataset.php, tests/APIv0/APIv0.php, tests/APIv2/InstallTest.php
APIv0 plays with the DI Container but does not clean itself!
=> Fix APIv0 test suite container corruption

library/core/class.format.php
Part of #5423 was putting the security filter after the magic parser. Our security filter doesn't have sufficient exceptions to allow our embeds. While ideally we would dig deep into the guts of Htmlawed and see if we can whitelist certain domains for embed very granularly, for now taking a step back is our best option.
=> Let magic formatter go last

library/Vanilla/AddonManager.php
Make the AddonManager cache optional.
This is great if you want to use the AddonManager in a context where the cache is useless.
=> Update AddonManager's caching to be optionnal

tests/travis/templates/vanilla/cgi-bin/saveconfig.php
You won’t believe how it happened.
=> This one little tweak might be the answer to our Travis build issues

applications/dashboard/views/modules/me.php
=> Initialize the ModerationCount variable regardless of logic

applications/vanilla/models/class.categorymodel.php
Clears notices on Recent Discussions.
=> Check if category fields exist before adding them

library/core/class.pluginmanager.php
Let's make that we actually have data in $PluginInfo
=> Make sure that we do not return an empty array

applications/dashboard/settings/structure.php
Fix "Calling update on null" error
=> Remove $this reference from structure file

applications/dashboard/models/class.usermodel.php
Prevent this [error](https://github.com/vanilla/vanilla/blob/50f3e1fa4fc478e0ea28f5db5dc02607bc30e39e/library/database/class.sqldriver.php#L1836) from being thrown..
=> Make sure to dbencode Preferences if present

applications/conversations/models/class.conversationmessagemodel.php, applications/conversations/models/class.conversationmodel.php, applications/conversations/models/class.conversationsmodel.php, applications/dashboard/models/class.activitymodel.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/models/class.vanillamodel.php, library/Vanilla/FloodControlTrait.php
I updated the function name from "is*" to "check*" since it does not only return a state.
I updated the docblock to reflect that change.
Only do the check if the discussion/comment is new
=> Do the UserSpamming check only if the discussion/comment is an insert

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/controllers/class.utilitycontroller.php, applications/dashboard/modules/class.headmodule.php, applications/dashboard/settings/structure.php, library/core/class.controller.php
Moving Touch Icon plugin to core, new branding option for mobile address bar colour
Closes #2560
=> Add Apple touch icon support

library/Vanilla/Addon.php, library/core/class.applicationmanager.php
That way applications can work with both about.php and addon.json.
=> Refactor the ApplicationManager to use the AddonManager to get applications info

library/core/class.oauth2.php
Replaces pull request https://github.com/vanilla/vanilla/pull/5461 by cherry picking from PR https://github.com/vanilla/vanilla/pull/5350
=> Backport fixes to Oauth2 class

library/database/class.sqldriver.php
We are increasingly using DateTimeInterface objects and support in the database layer will remove a lot of potential bugs.
=> Add support for DateTime parameters in GDN_SQLDriver

applications/dashboard/controllers/class.homecontroller.php
This is to go along with this change in the locales [here](https://github.com/vanilla/locales/pull/34)
=> Add a translation tag for leaving

library/core/class.format.php
`Gdn_Format::wysiwyg` calls `Gdn_Format::htmlFormat` on its content. There exists code in `Gdn_Format::htmlFormat` that encodes the contents of code blocks to ensure HTML entities are preserved. However, Wysiwyg should already be valid HTML. This includes encoded special characters, even in code blocks. This process is redundant and can lead to doubly-encoded characters in code blocks in Wysiwyg posts.
This update adds an `$options` parameter to `Gdn_Format::htmlFormat` and gives it its first option: codeBlockEntities. This value defaults to `true`. If it is a truthy value, the current behavior is performed. If formatters opt out of this behavior, this step is skipped before running the content through the site's configured HtmlFormatter (htmLawed). `Gdn_Format::wysiwyg` now uses this …
=> Fix doubly encoding code blocks with Wysiwyg format

applications/vanilla/controllers/class.vanillasettingscontroller.php
Do not change the value unless provided.
Also cover HideAllDiscussions and Archived.
=> Update AllowFileUploads only if supplied when editing a category

applications/dashboard/controllers/class.assetcontroller.php
Mare sure that the requested config contains an image before trying to delete it.
=> Validate that the config contains an image

library/core/class.form.php
- Touch "Control" early in simpleform
- Make sure that labels use the input's id when specified
- Properly place toggles descriptions
- Allow to set custom classes on simpleform items
=> Fix multiple minor issues in Gdn_Form::simple

library/core/class.format.php
Fix twitch over ssl and always go ssl!
There is no valid reason to hit http if you can get https.
=> Fix embedding Twitch video

.gitignore
We have `.htaccess.dist`
`.htaccess` should be ignored!
=> Add .htaccess to the ignore list

library/core/class.format.php
#5344 updated a lot of functionality in the `Gdn_Format` class. However, one of the things it did was to [remove the ability for `Gdn_Format::linksCallback` to reset its internal static variables](https://github.com/vanilla/vanilla/pull/5344/files#diff-b4fbc949423c122721c207f9d731c9d3L1238). This meant one post's state can affect the parsing of subsequent posts, since the function's state is carried over.
This update deprecates `Gdn_Format::linksCallback` and instead moves its contents into an anonymous function in `Gdn_Format::links` to avoid state from one call to the function carrying over into another.
To test, you can add two comments to a discussion, each with their format set to Html:
First comment:
```html
> Troublemaker
```
Second comment:
```html
```
As a result, the second …
=> Fix link parsing in tag attributes

applications/vanilla/models/class.categorymodel.php
Also super important: calculate the relative category URL as done in calculate()
=> Calculate category URL and PhotoURL only if not already calculated

.travis.yml
Make Travis-CI send a notification in our HipChat server on build failure or when a build is fixed.
Fixes https://github.com/vanilla/vanilla/issues/5467
=> Add Travis build status notification in HipChat

library/core/helpers/class.floodcontrolhelper.php
Presently when using he flood control helper we detect if the user is an admin or a moderator and by-pass flood control. There are some specialized instances where we may want to control the frequency of some activity of admins as well, e.g. executing a custom script like downloading.
The PR adds an `$skipAdmins` param to the flood control helper constructor.
https://github.com/vanillaforums/vanilla-clients/pull/269
=> Allow FloodControlHelper to restrict the actions of admins and mods

plugins/Flagging/views/flag.php, plugins/Flagging/views/report.php, plugins/Flagging/views/reportcomment.php
(cherry picked from commit b9a9e41eecdc69bab8148a72ff7ef07cd4c8679a)
Backport https://github.com/vanilla/vanilla/pull/5219 to Vanilla 2.4
=> Flagging plugin: fixed broken array references

applications/vanilla/models/class.commentmodel.php
https://github.com/vanilla/vanilla/commit/da8ec1b2e7cebb84dafb529a00da818a0ccd4a09 introduced some improvements to `CommentModel`. Unfortunately, they do not seem to work well when order parameters are not explicitly defined in a call to `CommentModel::getWhere`.
1. [`CommentModel::getWhere` passes its order parameters straight through to `CommentModel::select`.](https://github.com/vanilla/vanilla/blob/95fc6cdac37d420b5372d76d6ab592638a7395f8/applications/vanilla/models/class.commentmodel.php#L201)
1. If no values for the `$orderFields` or `$orderDirection` parameters are given, [`CommentModel::select` falls back to using whatever element is set to the instance's `_OrderBy` property's first element](https://github.com/vanilla/vanilla/blob/95fc6cdac37d420b5372d76d6ab592638a7395f8/applicatio …
=> Fix "unknown column Array in order clause" when querying comments

applications/dashboard/settings/class.hooks.php
This fixes issue https://github.com/vanilla/vanilla/issues/5358
=> Add permission check to /settings/tagging

applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/models/class.discussionmodel.php
=> Use path-only for new discussion activity route

library/core/class.oauth2.php
Add changes to OAuth2 base class to accommodate alternative SSO workflows, clean up code.
#5736
=> Backport #5736

library/core/functions.general.php
Partially addresses https://github.com/vanilla/vanilla/issues/5197
Switch from using serialize/unserialize to json_encode/json_decode.
dbencode now only work with json_encode.
dbdecode first try to json_decode and if it fails it will try unserialize. This will be a bit slower at first but it's backward compatible and will be faster than checking the type of data when all the data will have been converted to json.
I also fixed the doc blocks to respect the function behavior and added a comment to explain why we cast null and '' to null.
=> Default to json in dbencode() and dbdecode()

applications/vanilla/views/post/discussion.php
Closes https://github.com/vanilla/vanilla/issues/3518
=> Add `spellcheck="true"` to discussion title input box

applications/dashboard/controllers/class.profilecontroller.php
~~This allows a forum behind Varnish to work properly (Cookies are usually stripped for guests which means that no transient key is generated)~~
Actually guests don't get cookies.
=> Fix guests' inability to switch to full site from mobile theme

js/library/jquery.atwho.js
The atwho plugin didn't work properly in IE11. I've added more checks to make sure it doesn't generate an error.
Fixes https://github.com/vanilla/vanilla/issues/5697
=> Fix @mentions in Internet Explorer 11

applications/conversations/models/class.conversationmodel.php, applications/conversations/modules/class.addpeoplemodule.php
=> Prevent AddPeopleModule from adding more than the maximum of allowed recipients

library/core/helpers/class.floodcontrolhelper.php
Backport of PR #5698 to 2017-Q2-6
=> Add parameter to apply flood control or not to moderators/admin

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/controllers/class.importcontroller.php, applications/dashboard/library/class.nestedcollection.php, applications/dashboard/models/class.logmodel.php, applications/dashboard/models/class.smf2importmodel.php, applications/dashboard/models/class.updatemodel.php, applications/dashboard/models/class.vbulletinimportmodel.php, applications/dashboard/modules/class.mediaitemmodule.php, applications/dashboard/modules/class.morepagermodule.php, applications/dashboard/modules/class.navmodule.php, applications/dashboard/modules/class.pagermodule.php, applications/dashboard/views/settings/helper_functions.php, applications/vanilla/controllers/class.discussionscontroller.php, applications/vanilla/models/class.categorymodel.php, plugins/AllViewed/class.allviewed.plugin.php, plugins/Facebook/class.facebook.plugin.php, plugins/Flagging/class.flagging.plugin.php, plugins/GooglePlus/class.googleplus.plugin.php, plugins/Twitter/class.twitter.plugin.php
Scrutinizer gives code feedback. This update applies most of the current "informational" suggestions.
=> Apply feedback from Scrutinizer's informational recommendations

plugins/editor/class.editor.plugin.php
Refactor of the editor plugin variables that were not affected by the huge variable refactoring because they contain a require statement.
=> Fix coding standard

js/library/jquery.atwho.js
Backporting https://github.com/vanilla/vanilla/pull/5793
=> Backport: Fix @mentions in Internet Explorer 11

applications/dashboard/models/class.userauthenticationtokenmodel.php, plugins/Twitter/class.twitter.plugin.php
See connected issue for more information.
=> [Twitter] Bind OAuth token to the user requesting it.

applications/conversations/models/class.conversationmodel.php
Backport #5843 
I had to change the case of the variables from the origin commit.
=> Backport: Fix max recipient check

library/core/class.pluginmanager.php
See https://github.com/vanilla/vanilla/pull/5859 for details.
=> Use the DI container to instantiate plugins

plugins/editor/class.editor.plugin.php
Depends on #5845 
See linked issue for more details.
=> Editor upload hardening

applications/dashboard/views/entry/auth/password.php, applications/dashboard/views/entry/passwordrequest.php
Backport #5879 to the current release.
=> Backport: Fix email translation string

applications/dashboard/views/activity/popin.php, applications/vanilla/views/discussions/popin.php
=> Fix "All Notifications" and "All Bookmarks" strings for translation.

applications/vanilla/models/class.discussionmodel.php
=> Backport: Fix "All Discussions" so that it translates better.

applications/vanilla/js/category-settings.js
Fixes https://github.com/vanilla/vanilla/issues/5888
=> Fix changing category display type

applications/conversations/models/class.conversationmodel.php, applications/conversations/models/class.conversationsmodel.php
Allow to get conversations members full data set and add pagination to it!
=> Refactor ConversationsModel to accommodate the API Controller

applications/dashboard/models/class.sessionmodel.php, applications/dashboard/settings/structure.php
Also drop the transient key column since we do not use it anymore.
Complement https://github.com/vanilla/vanilla/pull/5837
Relate to https://github.com/vanilla/vanilla/issues/5763
=> Pad insert/update date in insert model and reduce prune time

applications/conversations/models/class.conversationmodel.php
fixes #5922
introduced in #5908
looks like DateConversationUpdated is not set automatically by the model like DateUpdated
=> Set DateConversationUpdated when a conversation is created

library/core/class.format.php
Class Session contains a helper method hourOffset() which returns the correct $hourOffset for current user/guest.
In class format that same offset calculation was done in two methods. I replaced that calculation directly with the sessions method.
=> Use Session->hourOffset() in class Format

library/core/class.vanillahtmlformatter.php
=> Allow table-related HTML elements to have classes in posts

.travis.yml
Closes https://github.com/vanilla/vanilla/issues/5878
=> Test php 7.2 on travis

composer.lock, library/Vanilla/Web/Controller.php
This includes a bug fix to the setID method.
=> Update composer dependencies

applications/conversations/models/class.conversationmodel.php
=> Fix deprecated detection when receiving an object in conversation model

applications/dashboard/controllers/class.entrycontroller.php
=> Restore redirectTo on entryController and deprecated it.

library/Garden/Web/Dispatcher.php
Backport https://github.com/vanilla/vanilla/pull/5990
=> Backport: Fix CSRF issue in Hootsuite app connection

library/core/class.cookieidentity.php
=> Disregard Garden.Cookie.Domain if the hosts are completely distinct

bootstrap.php
Clean left over comments from https://github.com/vanilla/vanilla/pull/5864/commits/30dbaa1ee34cd9e0f36a05677352f602391198db#diff-fdeb45dbb17d6e9c521987b15c0f816fR47
=> Remove unused code

bootstrap.php, library/core/class.dispatcher.php, library/core/class.pluginmanager.php
=> Backport DI improvements in plugins

js/global.js
=> Remove alert

composer.json, composer.lock
The composer lock file was out of date so I ran update.
Here are the updates:
```
Package operations: 0 installs, 5 updates, 0 removals
- Updating doctrine/instantiator (1.1.0 => 1.0.5):Downloading (100%)         )
- Updating phpunit/php-token-stream (2.0.1 => 1.4.11): Downloading (100%) 
- Updating phpdocumentor/type-resolver (0.4.0 => 0.3.0): Loading from cache
- Updating phpdocumentor/reflection-docblock (4.1.1 => 3.2.2): Loading from cache
- Updating phpunit/phpunit (5.7.21 => 5.7.23): Loading from cache
```
=> Update the Composer dependencies

library/core/class.oauth2.php
=> Backport: Add bearer token in HTTP header for profile requests in OAuth2

.gitignore, plugins/vanillaconnect/LICENSE.md, plugins/vanillaconnect/README.md, plugins/vanillaconnect/VanillaConnectAuthenticator.php, plugins/vanillaconnect/VanillaConnectPlugin.php, plugins/vanillaconnect/addon.json, plugins/vanillaconnect/views/settings.php, plugins/vanillaconnect/views/settings_addedit.php
Requires https://github.com/vanilla/vanilla/pull/5831
- Clone https://github.com/vanilla/stub-sso-providers/pull/1
- Composer install
- Setup nginx to work with stub-sso-providers
- Base yourself on https://github.com/vanilla/vanilla-docker/pull/1/files#diff-4e5487559f07f86005bca108c798464e
- Create a config.php in stub-sso-providers (The [template work as is](https://github.com/vanilla/stub-sso-providers/pull/1/files#diff-ce65fe62e6de6a262dc6fefc3c869e7f) in the current PR if your host is vanilla.dev)
- Enable the plugin
- Add a provider ![screen shot 2017-10-04 at 12 13 23 pm](https://user-images.githubusercontent.com/2412909/31186728-7917dd48-a8fd-11e7-9889-6489a236269f.png)
- Read this: https://github.com/vanilla/vanilla-connect-php/blob/b006096d5fc011c1343860aa1aa32d0ade36eea1/README. …
=> Add VanillaConnect addon

library/core/class.form.php
See https://github.com/vanilla/vanilla/pull/6080
=> Backport: Fix filtering categories by allowed types in new post form

composer.lock
This fixes issues with sparse validation and **requireOneOf()**.
=> Update Garden Schema

applications/dashboard/controllers/api/ApplicantsApiController.php, applications/dashboard/controllers/api/InvitesApiController.php, tests/APIv2/ApplicantsTest.php, tests/APIv2/InvitesTest.php, tests/APIv2/UsersTest.php
Closes #6088, #6090 
Change the name of the API controllers.
=> Rename applications and invitations endpoints to applicants and invites

applications/dashboard/models/class.usermodel.php
Backporting pull request #6131 from vanilla/fix/searching-by-rank
=> Enable turning off search optimization plugin adds custom filter criteria.

plugins/Quotes/class.quotes.plugin.php
Added the ability to Quote Usernames with dots in their usernames
=> Allow quoting usernames with dots

applications/vanilla/views/post/discussion.php, library/core/class.form.php
=> Backport: Add ability to filter category dropdowns by allowed discussion type

applications/dashboard/models/class.usermodel.php
Added translation for 'The captcha was not completed correctly. Please try again.'
=> Added Translation For Captcha String

applications/dashboard/controllers/api/AddonsApiController.php, library/Vanilla/AddonManager.php, library/Vanilla/Models/AddonModel.php, tests/APIv2/AddonsTest.php, tests/SiteTestTrait.php
These endpoints are for managing addons.
=> Add some /api/v2/addons endpoints

library/core/class.controller.php, library/core/functions.general.php
Backport vanilla/vanilla-patches#138
=> [Backport] Escape backslashes to prevent the browser from converting them to slashes

library/core/class.oauth2.php
Frequently authenticating servers are sending multi-dimensional responses as the user's profile. We have a mechanism to allow admins to input keys to map single dimensional arrays so that the array keys sent will match the array keys we use. This pull request will allow admins to use Vanilla's "dot notation" to access values in sub-arrays. e.g.
```
$arrayMap = [
'email' => 'Email',
'user_name' => 'Name',
'picture.thumbnail' => 'Photo'
]
$JSONResponse = {
"email": "patrick.k@vanillaforums.com",
"user_name": "patrick",
"picture": {
"thumbnail": "https://somecdn.com/patricksthumbnail.png",
"photo": "https://somecdn.com/patricksphoto.png"
}
}
```
Photo will now equal the value of thumbnail.
=> Parse values from multi-dimensional arrays sent over SSO

library/Vanilla/ApiUtils.php
This class is meant to contain static helper functions for API endpoints.
=> Add the ApiUtils helper class

applications/dashboard/controllers/api/AbstractApiController.php
The expand defintion wasn't very clear so I'm updating the description for a little more clarity.
=> Improve expand API parameter description

applications/conversations/controllers/api/ConversationsApiController.php, applications/conversations/controllers/api/MessagesApiController.php, applications/dashboard/controllers/api/AbstractApiController.php, applications/dashboard/controllers/api/ApplicantsApiController.php, applications/dashboard/controllers/api/AuthenticateApiController.php, applications/dashboard/controllers/api/InvitesApiController.php, applications/dashboard/controllers/api/RolesApiController.php, applications/dashboard/controllers/api/TokensApiController.php, applications/dashboard/controllers/api/UsersApiController.php, applications/vanilla/controllers/api/CategoriesApiController.php, applications/vanilla/controllers/api/CommentsApiController.php, applications/vanilla/controllers/api/DiscussionsApiController.php, applications/vanilla/controllers/api/DraftsApiController.php, library/Vanilla/ApiUtils.php, tests/APIv2/RolesTest.php
=> Standardize case normalization in API

applications/dashboard/controllers/api/UsersApiController.php
The ability to set user roles over the API was broken. This update restores that ability.
=> Fix setting user roles with the API

applications/dashboard/controllers/api/UsersApiController.php
This update backports #6200 to [release/2.5](https://github.com/vanilla/vanilla/tree/release/2.5).
=> Backport: Fix setting user roles with the API

applications/dashboard/controllers/api/RolesApiController.php, applications/dashboard/controllers/api/TokensApiController.php, applications/vanilla/controllers/api/CategoriesApiController.php, applications/vanilla/controllers/api/DiscussionsApiController.php
Depends on vanilla/internal#1303
Backport #6210
=> [Backport] Fix swagger documentation

plugins/Quotes/class.quotes.plugin.php
=> Backport: Fix Category view permission check in Quotes

applications/dashboard/controllers/class.authenticatecontroller.php
Prepare the authenticate endpoint to work with javascript frontend
=> Add redirect to JSON response from AuthenticateController::index

plugins/Quotes/class.quotes.plugin.php
=> Backport: Fix permission check when quoting a post

applications/vanilla/views/discussions/table_functions.php
=> Fix latest comment link to point directly to the comment

library/core/class.format.php
Closes https://github.com/vanilla/vanilla/issues/6234
The issue was introduced by this change: https://github.com/vanilla/vanilla/commit/83139ebbbb72c37964da29a22096a6e102396eee
=> Only do html to text conversion when it makes sense

library/core/class.format.php
=> [Backport] Only do html to text conversion when it makes sense

applications/dashboard/controllers/class.profilecontroller.php
=> Backport: Fix generating user tokens from profile pages

applications/dashboard/controllers/api/AuthenticateApiController.php, applications/dashboard/controllers/class.authenticatecontroller.php, applications/dashboard/views/authenticate/connectuser.php, library/Vanilla/Authenticator/SSOAuthenticator.php, library/Vanilla/Models/SSOData.php, library/Vanilla/Models/SSOModel.php, plugins/vanillaconnect/VanillaConnectAuthenticator.php, tests/APIv2/Authenticate/AuthSessionTest.php, tests/APIv2/Authenticate/AutoConnectTest.php, tests/APIv2/Authenticate/LinkUserTest.php, tests/APIv2/Authenticate/NoEmailTest.php, tests/APIv2/InvitesTest.php, tests/fixtures/src/TestSSOAuthenticator.php
Closes #6217
Split Authenticator/User/Extra data to prevent properties overriding.
=> Refactor SSOData

applications/dashboard/controllers/api/AuthenticateApiController.php, applications/dashboard/models/class.sessionmodel.php, applications/dashboard/settings/structure.php
The column was not named properly.
=> Rename column DateExpire to DateExpires

applications/conversations/controllers/api/ConversationsApiController.php
This update alters the conversations API index, defaulting to the current user as the `participatingUserID`. Requests made to this endpoint with no parameters will list all conversations the current user is a member of.
Closes #6127
=> Default conversations API index to current user

library/core/class.request.php
It's time to turn this on by default.
=> Update RewriteUrls default to true

README.md
See  #5177
For now, mentioning it is better than nothing.
=> Add a note about MySQL strict mode to README
