vanilla/vanilla

applications/vanilla/models/class.categorymodel.php

We introduced flat categories with https://github.com/vanilla/vanilla/pull/4198.  Part of this update added `CategoryModel::makeTree` to `CategoriesModule::getData`.  `CategoryModel::makeTree` assumes some data keys are set (namely `ChildIDs`) and that isn't the case with the data we have in the categories module.
This update removes the assumption of the `ChildIDs` key being available in category data used by `CategoryModel::_MakeTreeChildren`, which is used by `CategoryModel::makeTree`.  This removes numerous errors that can be generated when the category is iterated through, potentially two per category: one for an invalid array index and one for an invalid `foreach` source.

Don't assume ChildIDs set in CategoryModel::_MakeTreeChildren

---

plugins/AllViewed/class.allviewed.plugin.php

When _not_ using the default async MeModule option (i.e. a normal link) you land on a blank page for Mark All Viewed. This simply redirects you to the home page in that case instead.

Fix AllViewed redirect

---

applications/vanilla/modules/class.categoriesmodule.php

This update simplifies the tree building in `CategoriesModule`.  It replaces the usage of `CategoryModel::makeTree` with `CategoryModel::getChildTree`, which is more inline with what is used on category pages.

Simplify tree building in categories module

---

library/core/functions.render.php

Since popins call gdn.url() client-side we shouldn’t do it on the server.

Fix the double URLing in countString()

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

When editing a category, the category data being read is expected to be an object.  `CategoryModel::categories` returns an array.  This update casts the result to an object, which resolves issues with reading category values on edit (e.g. custom permissions).

Fix editing custom category permissions

---

applications/vanilla/controllers/class.categoriescontroller.php

The "Heading" category display type uses the discussions layout.  This update alters it to use the categories layout.

Display heading categories using category layout

---

plugins/IndexPhotos/class.indexphotos.plugin.php

Throughout the plugin the functionality is capsuled in such an if construct:
`if (!$this->hasLayoutTables() || IsMobile()) {`
So if the plugin is used from mobile, every output is made even when table layout is used, which doesn't makes sense at all. But I do not know where this comes from. Maybe that fix isn't correct...
I've deleted that helper function for determining if layout = 'table' since I thought that this wouldn't be helpful if this is the only thing that is checked now.

IndexPhotos is buggy on mobile with table layout.

---

applications/dashboard/models/class.usermodel.php

IP search can match per IP address entry. It's foreseeable this will happen for other conditions in the future too, so let's group our results on UserID so we never get duplicates.

Never duplicate user search results even if they match twice

---

applications/dashboard/controllers/class.entrycontroller.php

**Whereas:** Opening Vanilla's SSO signin in a new tab could cause the new tab to close after login.
**Whereas:** The EntryController used inconsistent logic about when to close itself / detecting if it was in a popup.
**Whereas:** The EntryController did access the global `GET`.
**Therefore:** It is resolved that we shall speak respectfully to the Gdn_Request singleton to resolve these disputes when setting up our redirects and master view.

Standardize our checking of signin popups in the entry controller

---

applications/vanilla/modules/class.categoriesmodule.php

`Gdn_DataSet` has an issue with its type property that currently requires a hack of setting, then resetting, the data type to properly re-cast its data.
This update adds such a fix to the categories module.

Redundantly set the data type in the categories module

---

library/core/class.session.php

First check in the method is 
~~~
if ($Name == '') {
return;
}
~~~
So it is safe to assume that $Name != '' but nevertheless that is checked three times afterwards in that method. I've simply removed that checks.
I've also changed the arrays from `array()` to `[]`, changed the casening of the variables and added a documentation that passed the latest coding standard :)

Remove superfluous if constructs in stash() method

---

applications/conversations/views/messages/add.php
applications/conversations/views/messages/addmessage.php
applications/vanilla/views/post/comment.php
applications/vanilla/views/post/discussion.php
applications/vanilla/views/post/editcomment.php

So according to the [w3 HTML5 documentation on tabindex](https://www.w3.org/TR/html5/editing.html#sequential-focus-navigation-and-the-tabindex-attribute), setting a tabindex attribute value to a an existing value means that the browser will navigate between them using the document tree order. Setting everything to tabindex 1 here fix all our problems.
That way we can jump from the body to the save button of every comments and discussions even when editing.
Close https://github.com/vanilla/vanilla/issues/3344

Fix tabindex for comments, conversations, discussions

---

library/core/functions.render.php

These characters are properly parsed and encoded now.
I added double encoding to `&` to make sure it will work properly with the `p` parameter.
Fix https://github.com/vanilla/vanilla/issues/4308

Do not strip quotations marks and ampersand from usernames.

---

plugins/Quotes/class.quotes.plugin.php

Enclose usernames with spaces in-between double quotes when using markdown.

Fix quotes that are done on a user with spaces in its name.

---

applications/dashboard/views/profile/connection_functions.php

The buttons in ". ActivateSlider" on /profile/connections really need an extra class. They always inherit the styling from ". Button", but are completely different.

Added class to ActivateSlider buttons

---

plugins/Tagging/class.tagging.plugin.php
plugins/Tagging/js/tagging.js

Closes #1917 (but backend validation was already happening, this is just for the second part).
The real change is in commit number 3. The others are just cleanup.

Add tokenizer max tags enforcement and cleanup tag validation

---

applications/dashboard/controllers/class.searchcontroller.php
applications/dashboard/views/search/results.php

The search results view ignores the pager that was being built in the search controller. Instead, just pass along the `_CurrentRecords` tally via the data array.
Closes #2319
Closes #1826

Fix the basic search pager

---

applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/models/class.discussionmodel.php
applications/vanilla/models/class.draftmodel.php
applications/vanilla/views/drafts/drafts.php

This changes the behavior of what happens to drafts when their parent (live) discussion is deleted. Previously, we silently deleted them all and neglected to update draft counters. Now, we let them become "orphans" that bring up the Post Discussion form.
Rationale:
* Drafts are a "private zone" that should not be touched by moderators.
* Moderators cannot have the intent to delete drafts because they cannot ever see them.
* A restored discussion now restores drafts. The previous behavior was permanently destructive.
* Does not interfere with counters.
We also rework the drafts view to operate on arrays and use some nicer logic.
Closes #1922
Closes #4187

Allow drafts to be orphaned and rework drafts view

---

applications/vanilla/settings/structure.php

When the Root category was being inserted, it was populating its `DisplayAs` value with the table default.  This used to be "Default", but is now "Discussions", which isn't proper for Root.
This update explicitly sets Root's `DisplayAs` to "Categories".
Closes #4365

Insert root category with DisplayAs set to Categories

---

library/core/class.pluginmanager.php

Fix a case when plugins are enabled right after being disabled because its hooks have not removed from the plugin manager. 
Log model on configuration save?
Fixes https://github.com/vanilla/addons/issues/369

Unregister plugin after it has been disabled.

---

README.md
applications/dashboard/models/class.importmodel.php

Fix: https://github.com/vanilla/vanilla/issues/4073
Mysql is removed from PHP7.0
Mysqli is available since 5.3 and we support 5.4 an up so we are good :D

Replace MySQL with MySQLi for imports

---

plugins/editor/views/editor.php

Selecting buttons in CSS is already pretty messy in Vanilla. I'd like all flyout buttons to have a "Flyout-Button" class. Usually, designers want those buttons to be smaller than the rest.

Added a class for buttons in create link flyout.

---

library/database/class.databasestructure.php

The SQL is too verbose to be useful in a log message.

Don’t log the ALTER SQL during a structure_threshold event

---

applications/dashboard/modules/class.configurationmodule.php

Use case: https://github.com/vanilla/addons/pull/371
If we manually add errors to the ConfigurationModule's form, it should respect that and stop.

Add ability for configuration module to fail on error

---

applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/library/class.categorycollection.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/views/vanillasettings/addcategory.php
applications/vanilla/views/vanillasettings/category-settings-functions.php
plugins/GettingStarted/default.php

This update adds flat category management capabilities to version 3 of the dashboard application.
Addresses the following items from #4155 
1. Add the "flat" option to the display as dropdown.
2. Rename the "categories" label to "nested".
3. A category with display as of "flat" should display as a link, just like display as "categories". Clicking on the link will nest into it.
4. When a category in this view has child categories then it should display as a link to edit the children.

Add flat category handling to category management

---

applications/dashboard/views/user/edit.php

When editing users in the dashboard, certain fields that are empty (e.g. Name) are being auto-filled. If an admin is not careful, they could add it to the user's record. The P.R. fixes that .

Turn off AutoComplete when editing users in dashboard

---

library/core/class.pluginmanager.php
tests/Library/Core/PluginManagerTest.php

Add the Gdn_PluginManager->regsterCallback() method to allow callbacks to be registered in a more free-form way.

Allow callbacks to be registered directly in a Gdn_PluginManager object

---

applications/dashboard/models/class.usermodel.php

Closes #2325
Avoid situation where you end up with a blank site name in emails due to incomplete setup.

Let welcome email fallback to HomepageTitle

---

library/core/class.dispatcher.php
library/core/class.request.php

I played a bit with the request object and found out that you cannot double encode a character in the URL right now.
`/profile/UserWith%252FSlash` "UserWith/Slash"
is still parsed as
`UserWith/Slash` instead of `UserWith%2FSlash` because we rawurldecode the value in `Request::_environmentElement()`.
While this is something that can be "correct" when making internal requests we should not double decode the URI in `Request::_loadEnvironment()`.
The dispatcher has been updated to compensate for this change.

Avoid REQUEST_URI double decoding at the request level.

---

applications/dashboard/views/modules/dropdown.php

The tool tip for ".OptionsTitle" was not translatable.

Fixed option tool tip to be translatable

---

applications/vanilla/modules/class.categoriesmodule.php
library/database/class.dataset.php

[`Gdn_DataSet::__construct`](https://github.com/vanilla/vanilla/blob/8efb18d446977d17bfd5738ec2af0bdff64ef00c/library/database/class.dataset.php#L58) attempts to determine the incoming data type based on the first element of its `$Result` parameter, if no explicit value for `$DataSetType` is provided.  It assumes a numerically-indexed array, starting with 0, when retrieving the first element.  If it cannot locate that element, the data type remains as the class default: `DATASET_TYPE_OBJECT`.  There are occassions (see #4340) where a multi-dimensional array might be passed in as `$Result` with no zero index and no explicitly-defined type parameter.  This leads the instance of `Gdn_DataSet` to assume it is dealing with an array of objects, which can lead to issues.  One such issue is the …

Fix auto-detection of incoming data type in Gdn_DataSet

---

applications/dashboard/controllers/class.entrycontroller.php

Our SSO workflow bears further illumination. Breaking this into multiple methods in the future would be preferable to this very long workflow.
No functional changes here excepting the `randomString()` call, which is now standardized on 16 characters as elsewhere.

Improve legibility and docs in EntryController::connect()

---

plugins/IndexPhotos/design/indexphotos.css

The IndexPhotos aren't displayed on the profile discussions index, so padding styles shouldn't be applied there.

IndexPhotos: no padding on profile discussions index

---

applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/js/category-settings.js
applications/vanilla/models/class.categorymodel.php
applications/vanilla/views/vanillasettings/categories.php

Parent ID was not set properly when moving the first "level" children of a category on the same level of its parent.
This was due to the fact that saveSubtreeInternal was setting the `ParentCategoryID` only if `$parentID` is supplied and it was not!
Fix: https://github.com/vanilla/vanilla/issues/4419

Fix category depth adjustements

---

applications/dashboard/settings/class.hooks.php

Fix the 'View not found.' error on /discussions.rss

Do not fetch add symbols when delivery method is RSS

---

applications/dashboard/js/dashboard.js
applications/dashboard/js/src/modal.dashboard.js
applications/dashboard/views/settings/helper_functions.php

Add a flag to let the modal know not to refresh after form save and apply it to the addon settings.
Also clean js a bit.
Closes https://github.com/vanilla/vanilla/issues/4476

Don't reload page after saving addon settings in a popup

---

applications/dashboard/models/class.activitymodel.php

While trying to write a plugin which uses Pushbullet for sending notifications to users, I've found no way to queue activities for users who have neither the Email nor the Notification preference set, based on the rigid `if (!$Popup && !$Email) return` preference check
I needed an event before that check so that I could queue an activity based on my custom preferences ("BeforeCheckPreference"). I would have prefered a "BeforeQueue" event right before the `self::$Queue[...] = ...` but that would have required a logic change in that method and I wanted to be least invasive.
What would it take to ensure this change is in your next release (even if it would be a 2.2.bugfix)?

Add BeforeCheckPreference event to ActivityModel

---

applications/dashboard/controllers/class.dashboardcontroller.php
applications/dashboard/controllers/class.homecontroller.php
applications/dashboard/models/class.usermodel.php

Clear the url from a user's preferences if it's one that redirects them to a 404, 401, etc.
Provide an endpoint to manually clear a user's navigation preferences.

Handle clearing problematic user preferences

---

applications/vanilla/views/vanillasettings/category-settings-functions.php

This update adds a "View" item to the menu for each category on the Manage Categories page of the dashboard.  This menu item takes the user to the public-facing category page.
Closes #4428

Add View link to manage category page

---

applications/vanilla/controllers/class.postcontroller.php

`PostController::notifyNewDiscussion` was using a local variable named `$Code` as the translation slug for the `t` function, without having actually defined it before being used.
This update copies the logic from [DiscussionModel::save](https://github.com/vanilla/vanilla/blob/603163710edd49efcd83915424fca0773bb9d8f3/applications/vanilla/models/class.discussionmodel.php#L2029) to determine what `$Code` should be set to.

Fix missing translation slug in PostController::notifyNewDiscussion

---

library/core/class.pluginmanager.php
tests/Library/Core/PluginManagerTest.php

Since the Gdn_PluginManager stores different types of event handlers into different arrays, registering a new callback must respect this.
Previously, `registerCallback()` also stored `_override` and `_create` types as `_handler`s.

Allow Gdn_PluginManager->registerCallback() to properly register “create” and “override” style callbacks

---

plugins/VanillaStats/js/vanillastats.js

This update alters the VanillaStats plug-in's JavaScript to use `toLocaleString` on the number values it displays on the chart and in the sparkline widgets.  This formats the numbers with commas.

Use toLocaleString to format numbers in VanillaStats plug-in

---

library/core/class.form.php

Old forms output buttons with a value equal to their label. The new buttons should fall back to the same.

Make sure new-school form buttons have a value

---

applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/models/class.categorymodel.php

https://github.com/vanilla/vanilla/pull/4371 and https://github.com/vanilla/vanilla/pull/4387 have conflicting signatures for `CategoryModel::getTreeAsFlat`.  This causes some issues in category management pages (e.g. no children show up when managing a flat category).
This update fixes the parameter collision and updates the necessary calls.

Fix conflicting param usage in CategoryModel::getTreeAsFlat

---

applications/dashboard/js/jquery.tablejengo.js

Fixes issue where table meta for a collapsed table shows a colon `:` but no label when the column has no label.
Closes https://github.com/vanilla/internal/issues/683
Closes https://github.com/vanilla/vanilla/issues/4487

Don't show empty column labels when a table collapses

---

applications/dashboard/design/style.css

The default vanilla style does not have a background colour on the overlay. It's not always obvious (especially with a small popup) that you can't click elsewhere.

Added a background colour to Overlay

---

library/core/class.session.php

When using `stash()` while the query builder is not finished with an sql, there would either be errors or false results since the Session class uses the singleton Gdn::sql().
The `stash()` method (and its helper method `_getStashSession()`) are the only two methods using db queries in Session. So I've not set $this->sql in `__construct()` but only in `stash()` since it wouldn't be needed elsewhere.
This solves issue https://github.com/vanilla/vanilla/issues/4391

Make stash() use clone of sql class

---

.travis.yml

This update alters Vanilla's Travis CI config file to allow the HHVM job to fail without considering the whole build to be a failure.
Based on information available at [Customizing the Build - Travis-CI](https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail)
Closes #4511

Allow CI build to succeed when HHVM job fails

---

library/database/class.mysqlstructure.php

This update alters the `ipaddress` type alias in `Gdn_MySQLStructure` from `varchar(15)` to `varbinary(16)`.
Data seems to remain intact after a utility-update.  Updating data also seems to be unaffected.
Closes #3805

Update IP Address field types to varbinary(16)

---

applications/dashboard/models/class.activitymodel.php
applications/dashboard/models/class.logmodel.php
applications/dashboard/models/class.usermodel.php
library/core/class.model.php
plugins/StopForumSpam/class.stopforumspam.plugin.php

This update encodes all IP address values in preparation for storage in `varbinary(16)` fields.
Requires https://github.com/vanilla/vanilla/pull/4133
Closes #3809

Update all IP address fields to be able to store IPv6 values

---

applications/vanilla/views/discussions/index.php
applications/vanilla/views/discussions/table.php

This update verifies the `CategoryModel` property is present and an instance of `CategoryModel` before attempting to use it in discussion views.  Prior to this update, there was a potential to reach a "Call to a member function joinRecent() on null" error.

Verify presence of CategoryModel in discussion views

---

applications/conversations/controllers/class.messagescontroller.php

By now only the recipient can be "pre-filled" by adding its name to "/messages/add/recipient". This enhancement allows using "/messages/add/recipient/subject of the message"

Let class messages add() accept a "Subject" parameter

---

applications/dashboard/controllers/class.settingscontroller.php

By now it is possible to access /settings/tutorials without any permissions at all. Though this is not a security problem, it might be disturbing for admins to see that even guests can access parts of the admin area.

Make settings/tutorials require permissions

---

applications/vanilla/controllers/class.categoriescontroller.php
applications/vanilla/modules/class.categoryfollowtogglemodule.php
applications/vanilla/views/categories/helper_functions.php
index.php

This update removes the less-than-intuitive "Hide Category" feature and replaces it with "Mute Category".  Muting a category will still display it in the category list (unlike hiding it), but filter its discussions out of the recent discussions page.  Since we're removing this functionality, `CategoryFollowToggleModule` is being deprecated.  The class still exists, but should not longer render any code when included.
Existing fields, functions and variable naming (following, unfollow, watching, etc.) remain unchanged.  Existing filtering for the recent discussions page remains the same as implemented in [`DiscussionModel::getWhere`](https://github.com/vanilla/vanilla/blob/c5616600b41438fc8de53eb034e7c74ea882cdf7/applications/vanilla/models/class.discussionmodel.php#L601)
Closes #4394

Replace Hide Category with Mute Category

---

js/global.js

Using HTMLawed, we have a whitelist of CSS classes that are allowed to be applied to user-generated content. As such, there's no need to have the restrictions added in this pull-request any longer: https://github.com/vanilla/vanilla/pull/2012
Further, this fixes the Groups issue which was addressed here: https://github.com/vanilla/internal/pull/706
which was introduced by a misunderstanding of the overloaded `Message` term here: https://github.com/vanilla/vanilla/commit/952324939824d5b4554dc086951d7ecd60387bf2#diff-206bb8e5b8584223b92afae06825d2faR764  which was originally a problem because .Hijack wasn't working in the Message setting page in the dashboard.
All apologies for the run-on sentence.

Remove Message restrictions from global.js

---

library/core/class.controller.php

Mustache support never existed. The corresponding plugin wasn't touched for two years. Even if the plugin would be finished in the future, the complete template handling should be one by that plugin.

Remove Mustache support fragments from Controller

---

library/core/class.controller.php
library/core/functions.general.php
tests/Library/Core/GeneralFunctionsTest.php

This update addresses issues with binary values causing JSON encoding to fail in `Gdn_Controller::RenderData`.  It does this by recursively iterating through the `$Data` array and running `ipDecode` against fields with recognizable names (e.g. *IPAddress, *IPAddresses).
*Note: Elements in the `$Data` array can be other arrays ___or objects___, making this not an ideal candidate for `array_walk`/`array_walk_recursive`.  These functions skip over iterating through object properties.  Also, with `array_walk_recursive`, any key that holds an array will not be passed to the callback function. This makes it tough to handle values like "AllIPAddresses", which is an array, itself.*
Closes #4590

Decode IP field data in Gdn_Controller::renderData

---

library/core/functions.render.php

`ipAnchor` was not attempting to decode packed IP addresses before creating a URL with them.
This update passes the IP value through `ipDecode` when building the URL.

Decode packed IP in ipAnchor

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/models/class.activitymodel.php
applications/dashboard/models/class.invitationmodel.php
applications/dashboard/models/class.usermodel.php
library/core/class.email.php
plugins/Flagging/class.flagging.plugin.php

This update...
1. Adds a new status for the `Emailed` column of the Activity table: `SENT_SKIPPED`.  This is used to indicate when sending an email has been skipped, instead of an error occurring. 
2. Adds try/catch blocks around all the `Gdn_Email::send` calls I could find that didn't already have them, because that function can (and does) throw exceptions, even before this update.
3. Appeases my IDE by tweaking some docs and default parameter types.
Closes #4397

Fix activity notifications falsely flagging as sent

---

plugins/SplitMerge/class.splitmerge.plugin.php

Previously, the moderator performing the action would become the OP. This caused them to start receiving notifications, which turned out to be undesirable in most cases.

Change Split action to makes new OP from System user

---

applications/dashboard/models/class.spammodel.php

This update alters `SpamModel::isSpam` by passing `$Data` through `ipDecodeRecursive` before firing its "CheckSpam" event.  This should ensure all IP address data transmitted will be unpacked/human-readable.

Decode IP addresses before checking for SPAM

---

applications/vanilla/models/class.categorymodel.php

`CategoryModel::setCache` is a static method.  This update alters some calls in `CategoryModel` to call it as a static method.

Fix non-static references CategoryModel::setCache

---

applications/vanilla/models/class.categorymodel.php

This update adds a call to `CategoryModel::clearCache` at the end of `CategoryModel:: saveSubtreeInternal`, which should ensure there is no lingering category data (e.g. sorting) after the structure has been modified.

Fix caching of data when rearranging categories

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

`VanillaSettingsController::categoriesTree` currently assigns `Response` to the return value of `CategoryModel::saveSubtree`, which does not return a value.  This means the `Response` data is always `null`.
`CategoryModel::saveSubtree` calls `CategoryModel::saveSubtreeInternal`, which can flag validation errors.  These are not currently accounted for.
This update uses the validation object of `CategoryModel` to determine the value of `Response`: `true` if no errors, `false` when errors/results are added.  In addition, the full validation result array is being added under the `Validation` key.

Update response in VanillaSettingsController::categoriesTree

---

library/core/class.cache.php

`Gdn_Cache::option` takes two parameters: `$Option` and `$Default`.  If `$Option` isn't set in cache configuration array, we should be getting the `$Default` value.  However, there is currently a condition that is preventing this from occurring.
This update removes the aforementioned condition, allowing code execution to reach the call to `val` which follows, allowing the value of `$Default` to be returned if `$Option` is not a key in the cache configuration array.

Allow default caching option value to be reached in Gdn_Cache

---

applications/vanilla/views/categories/helper_functions.php

The [`getOptions`](https://github.com/vanilla/vanilla/blob/a3423c6869eef3dd009db5253511880f6f1b61f2/applications/vanilla/views/categories/helper_functions.php#L76) categories helper function passes its URLs to `DropdownModule::addLink` through [`url`](https://github.com/vanilla/vanilla/blob/a3423c6869eef3dd009db5253511880f6f1b61f2/library/core/functions.general.php#L3546).  However, the view for `DropdownModule` also [passes the URL values through `url`](https://github.com/vanilla/vanilla/blob/a3423c6869eef3dd009db5253511880f6f1b61f2/applications/dashboard/views/modules/dropdown.php#L19).  If add-ons are hooking in and modifying URLs, this can cause them to be doubly affected and potentially result in invalid URLs.
This update nixes the call to `url` in the categories `getOptions` …

Fix redundant calls to url for category options

---

applications/dashboard/models/class.banmodel.php

This update augments ban checking/enforcement in `BanModel` by updating its ability to handle packed IP addresses.  IP comparisons in PHP are done with `ipDecode`.  IP comparisons in MySQL make use of `inet6_ntoa`, which is available since [MySQL 5.6.3 (released October 3, 2011)](https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-3.html)

Update packed IP address handling in BanModel

---

.travis.yml
applications/dashboard/controllers/class.setupcontroller.php
conf/config-defaults.php
library/core/class.request.php

* We automatically provide the Smarty compile folder, so also make sure of its permissions.
* `chmod 777` is bad advice.
* Default to RewriteUrls.
* Remove a dead method and fix a few coding standards issues in the general vicinity.

Improve install experience for 2.3

---

library/database/class.sqldriver.php

Guess no one's ever cared if this worked, because it returns null currently.

Fix MySQL version get

---

applications/dashboard/settings/class.hooks.php

For 2.3 release.
Use our MessageModule to add upgrade warnings to all /settings pages in the Dashboard.
We strongly suggest PHP 5.6+ and MySQL 5.6+.
This also allows the messages to be dismissed by the folks who are powerless to do anything about it presently and cannot abide by this message annoying them.

Add an upgrade warning for PHP and MySQL to all settings pages

---

applications/dashboard/settings/class.hooks.php

* Hooks should extend `Gdn_Plugin`; implementing IPlugin is deprecated.
* Found a `safeRedirect` todo that is fine to resolve now that we have implemented everything around it.
* Add a missing docblock.

Update Dashboard hooks to use correct class and redirect method

---

applications/dashboard/README.md

Addresses issues I found while setting this up:
* Was not clear it needed not-default Ruby.
* Was not clear you needed to be in that sub-directory, but only when you got to `npm install`.
* Some steps required clicking links when it's just 1 more command that could've been inline.
* Clarifies who the doc is for.

Make dashboard asset compilation readme clearer

---

applications/dashboard/js/jquery.tablejenga.js

Fix issue where empty labels appear in table jenga. This was originally fixed here https://github.com/vanilla/vanilla/commit/2341115ce5304f8b7860fc04129e24e95e2d626c but mistakenly reverted here: https://github.com/vanilla/vanilla/commit/23bc9bb693ee2b6e04973c43e95da3fcfdea0596

Fix empty Table Jenga label still appearing

---

applications/dashboard/views/profile/activity.php

I wrongfully changed the headings for "activity" in this PR:
https://github.com/vanilla/vanilla/pull/4415
It appears in the profile page, not as the title for an edit profile page.

Fixed wrong heading for "activity" on profile page

---

applications/dashboard/library/class.emailtemplate.php

[Stronger, Better, Faster, Simpler than this sug-ges-ti-on](https://www.youtube.com/watch?v=gAjR4_CbPpQ):
https://github.com/vanilla/vanilla/issues/4183#issuecomment-252344447
Fix: https://github.com/vanilla/vanilla/issues/4183

Only double space the message section in plainTextEmail()

---

js/embed_local.js

This update avoids automatically scrolling to the top of an embedded site when it's a comment embed.
Closes #4550

Avoid auto-scrolling to top when in comment embed

---

plugins/VanillaStats/js/vanillastats.js

This update forces formatting selected dates in the target range as UTC strings in Vanilla Stats, instead of relying on the browser's date-object-to-string conversion, which can lead to inconsistent date formatting.
Closes #4560

Send range dates as UTC when fetching Vanilla Stats summaries

---

applications/vanilla/js/manage-categories.js

Fixes issue where you can't choose which category to move discussions to.
Closes https://github.com/vanilla/vanilla/issues/4660

Check for change instead of click in category deletion

---

applications/dashboard/settings/structure.php

Prevent column FullName of table Tag to be set to a false length
https://github.com/vanilla/vanilla/pull/3996

Backport PR #3996 to Vanilla 2.3

---

applications/dashboard/design/style.css

Fix typo in style.css
Affects text that is hovered on the profile picture in edit profile.
https://github.com/vanilla/vanilla/pull/3711

Backport PR #3711 to Vanilla 2.3

---

library/core/class.controller.php

If IP addresses happen to still be in their binary representations by the time JSON output is due to be created, it is killing the entire output due to the bad JSON conversion.
This update runs the data through `ipDecodeRecursive` before attempting to encode it as JSON.

Ensure all IP addresses are decoded before JSON encoding

---

plugins/editor/js/editor.js

Allows files with the same names in a discussions. Only restrict unicity by posts.
Fix: https://github.com/vanilla/vanilla/issues/3492

Restrict file upload per post instead of by discussion

---

applications/vanilla/js/manage-categories.js

The nav calculates the page height before the permissions are hidden. This triggers the nav to recalculate the height of the page.

Fix issue where nav is cut off on category add/edit

---

library/core/class.form.php

Just as the label in the checkBox() or radio() element, the label in the new toggle element should use the t() function by default.

Make label of toggle element always use translations

---

applications/vanilla/modules/class.discussionssortfiltermodule.php

[`DiscussionsSortFilterModule::getFilterDropdowns`](https://github.com/vanilla/vanilla/blob/9d8a5a3441ab9c634b7f9b7e5136079f6e0b02a0/applications/vanilla/modules/class.discussionssortfiltermodule.php#L165) uses `DropdownModule`.  `DropdownModule` uses [`NestedCollection`](https://github.com/vanilla/vanilla/blob/9d8a5a3441ab9c634b7f9b7e5136079f6e0b02a0/applications/dashboard/modules/class.dropdownmodule.php#L73). The parameters used in [`DiscussionsSortFilterModule::getFilterDropdowns`](https://github.com/vanilla/vanilla/blob/9d8a5a3441ab9c634b7f9b7e5136079f6e0b02a0/applications/vanilla/modules/class.discussionssortfiltermodule.php#L192) do not match up with the signature of [`NestedCollection::addLink` ](https://github.com/vanilla/vanilla/blob/9d8a5a3441ab9c634b7f9b7e5136079f6e0b02a0/appli …

Fix links in discussions filter module always being disabled

---

library/core/functions.compatibility.php

This update alters `safeCookie` defaults to set the secure flag on cookies if the following conditions are met:
1. The `$secure` parameter is `null`. Previous boolean values will continue to work as they have.
1. `Garden.ForceSSL` is enabled.
1. The current request is served via HTTPS.
Closes #4552

Default to secure cookies if ForceSSL and behind HTTPS

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/js/addons.js
applications/dashboard/settings/class.hooks.php
applications/dashboard/views/settings/mobilethemes.php
applications/dashboard/views/settings/themes.php
library/core/class.thememanager.php

Reinstates Theme Preview for both mobile and desktop themes.
Functionality is different than before, in that you can preview both a mobile and desktop theme simultaneously. Caveats are that themehooks and theme view overrides cannot be previewed.
Also proposes new theme property 'AllowPreview', which can be set to false for themes that absolutely can't be previewed in this context. Lithe would be one of these theme, since it requires enabling plugins to work.
Closes https://github.com/vanilla/vanilla/issues/4227

Reinstate Theme Preview

---

applications/dashboard/views/settings/helper_functions.php
library/Vanilla/Utility/CamelCaseScheme.php
library/Vanilla/Utility/NameScheme.php
library/core/class.pluginmanager.php

$addonInfo could come either from the PluginManager or the AddonManager.
The AddonManager save the info with CamelCaseScheme and load them as is.
The PluginManager convert $addonInfo to CapitalCaseScheme. (Probably for backward compatibility)
For now I decided to use CapitalCaseScheme->convertArrayKeys in writeAddonMedia() which fix the problem with the keys being either differents.
Fix: https://github.com/vanilla/vanilla/issues/4491

Fix $addonInfo being wild about its key casing in writeAddonMedia()

---

applications/dashboard/views/modules/message.php

This update replaces a direct array index value check with a call to `val` in the `MessageModule` view.  The assumption of the "AllowDismiss" key was sometimes throwing a PHP notice.

Don't assume presence of AllowDismiss in message module view

---

applications/dashboard/controllers/class.rootcontroller.php

Since https://github.com/vanilla/vanilla/commit/791ef112f27d879395b024a56a7339825bcdfbcb, `Gdn_Controller::fetchViewLocation` has had an additional parameter: `$useController`. `RootController` extends `Gdn_Controller`, but it's `fetchViewLocation` does not include this new parameter, which can throw a warning.
This update adds the `$useController` parameter to `RootController::fetchViewLocation`.  In addition, since it's such a small function, I've taken the opportunity to update the coding standards.

Update RootController::fetchViewLocation to match parent

---

applications/dashboard/settings/class.hooks.php
library/core/class.dispatcher.php

Clear user navigation preferences if we can't find the explicit method on the controller.
You can test this fix by adding these user preferences to the Preferences field for your user:
```
a:2:{s:33:"DashboardNav.DashboardLandingPage";s:9:"Analytics";s:32:"DashboardNav.SectionLandingPages";a:3:{s:9:"Analytics";s:47:"settings/analytics/dashboard/personal-dashboard";s:10:"Moderation";s:15:"/dashboard/user";s:8:"Settings";s:28:"/vanilla/settings/categories";}}
```

Handle user preferences and settings controller 302s

---

applications/dashboard/library/class.emailtemplate.php

Fix https://github.com/vanilla/vanilla/issues/4735
Test code (put in index before `$dispatcher->start();`
```php
$email = new Gdn_Email();
$email->setFormat('text');
$email->from('admin@vanilla.dev');
$email->to('alexandre.c@vanillaforums.com');
$content = "**Plex Media Server 1.2.3 is now available for Plex Pass members.**
**NEW**
- (Web) Updated Plex Web to 2.10.5.
- (Media Flags) Update bundle.
- (Localization) Updated server translations.
**FIXES:**
- (Network) Clients might incorrectly report a server as unclaimed or remote access as unavailable after network timeouts. (#4994)
- (Streaming Brain) In some cases the server could unexpectedly reserve any remaining bandwidth. (#5447)
- (Streaming Brain) Playback failures on Android. (#5537 #5589)
- (Streaming Brain) Issues starting …
```

Do not add extra <br> tags in plain text emails

---

library/Garden/Schema.php

This update adds the `Garden\Schema::$description` property, as well as its getter and setter.
Closes #4708

Add description property to Garden\Schema

---

library/Garden/Schema.php

This update adds `Garden\Schema::dumpSpec`.  This function is intended to output a representation of the schema data that is compatible with the [OpenAPI v2 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject).
Closes #4709

Add Garden\Schema::dumpSpec

---

composer.json
composer.lock

We can now use the upstream: https://github.com/chrisbliss18/php-ico/commit/4d972cc60e1f7b87be1844d1bc241f48c9e1a444

Change php-ico package in Composer

---

applications/dashboard/models/class.usermodel.php

* Joins User table and UserIP table with a left join.
* Pulls out the IP searching function into its own function.
* Update search count.
Previously, we only returned users who had an entry in the UserIP table. This adds a left join to the query to return all users, whether in the UserIP table or not. Also, fixes searchCount for IP searches, as the count was always empty.
Closes https://github.com/vanilla/vanilla/issues/4752

Return all users with a valid IP address and update searchCount query

---

applications/dashboard/models/class.usermodel.php

The user photo returned from this is not a valid image, as it has no prefix on it. The views usually overlook this by using the userPhoto() function, but it fails when you try using the userPhotoUrl() function on the users page. Because we set a full url here, userPhotoUrl() doesn't change the basename and returns a url to an image without the n or p prefix, an image that doesn't exist.

Set the user photo to an actual user photo in search

---

applications/vanilla/views/categories/helper_functions.php

When a category is configured to display as "Heading", it isn't supposed to have an anchor.  This is true for most of Vanilla, but [`writeListItem`](https://github.com/vanilla/vanilla/blob/7ae304aa7cb89496bc17925d05798352056b4b6c/applications/vanilla/views/categories/helper_functions.php#L130) and [`writeTableRow`](https://github.com/vanilla/vanilla/blob/7ae304aa7cb89496bc17925d05798352056b4b6c/applications/vanilla/views/categories/helper_functions.php#L225) do not currently account for this adjustment.  Everything gets an anchor.
This update alters the aforementioned functions to only apply an anchor to the title of categories when they are not configured to display as "Heading".
Closes #4634

Fix heading categories sometimes being wrapped in an anchor

---

applications/dashboard/js/user.js
applications/dashboard/views/user/edit.php

* Executes on contentLoad to ensure the javascript executes in a modal.
* Listens for a `change` on the radio field instead of `click`, which fixes the interference with iCheck.
* Explicitly checks for visibility of the password input element, so we can toggle the text on the button.
* Reorders the HTML to work with hiding/showing the `NewPassword` element and adds data attributes to aid translation.
Closes https://github.com/vanilla/vanilla/issues/4694

Ensure password editing fields toggle appropriately

---

applications/dashboard/controllers/class.entrycontroller.php
applications/dashboard/models/class.updatemodel.php
library/core/class.configuration.php
library/core/class.format.php

This update removes some serialization calls and replaces them with their DB-encoding counterparts (e.g. `dbencode`, `dbdecode`).
Closes #3749

Replace some serialization calls with their DB-encoding counterparts

---

applications/dashboard/modules/class.mediaitemmodule.php

This update addresses a notice potentially being fired if "class" hasn't been set yet in `MediaItemModule::$attributes` by the time `MediaItemModule::setView` is called.

Fix notice caused by MediaItemModule::setView

---

applications/vanilla/library/class.categorycollection.php

`CategoryCollection::getTree` creates a union from its default options array and the incoming `$options` parameter.  However, before performing this union, it runs `$options` through `array_change_key_case`.  A potential result of this function is a boolean `false`, which shouldn't be used for an array union.
This update moves `array_change_key_case` out onto its own and falls back to an empty array, should it fail.
Closes #4723

Fix potential invalid array union in CategoryCollection

---

applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/views/categories/helper_functions.php
applications/vanilla/views/vanillasettings/advanced.php

This update restores the long-lost form control for setting `Vanilla.Categories.MaxDisplayDepth`.  Prior to Vanilla's dashboard refresh, this control was found on the categories page.  Now, it can be found in Vanilla's settings, on the Advanced page.
Closes #4625

Add input control for Vanilla.Categories.MaxDisplayDepth

---

library/Garden/Schema.php
tests/Library/Garden/BasicSchemaTest.php
tests/Library/Garden/NestedSchemaTest.php

This update makes a couple changes to `Garden\Schema`:
1. Adds `filterData` function, which removes fields from a `$data` array that aren't explicitly a configured part of the schema.
2. Adds `VALIDATE_*` class constants to assign and detect validation behavior.
In addition, test have been added for each new validation behavior for both basic and nested schemas.
Closes #4703 
Closes #4707

Update validation in Garden\Schema to handle unexpected parameters

---

applications/vanilla/models/class.categorymodel.php

This update adds `getRootDisplayAs` to `CategoryModel`.  This method will be used to retrieve the value of the `Vanilla.RootCategory.DisplayAs` config key, defaulting to "Categories" (Nested).
Closes #4790

Add CategoryModel::getRootDisplayAs

---

applications/dashboard/controllers/class.settingscontroller.php

This update is a minor fix to soothe Scrutnizer.

Ensure $newUpload always set in SettingsController::defaultAvatar

---

library/core/class.request.php

The bootstrap installs a request that is created with Gdn_Request::create() which just creates a new instance. Allowing other code to create new Gdn_Request objects normally is not too much to ask.

Expose the constructor of Gdn_Request

---

applications/vanilla/views/categories/flat_table.php
applications/vanilla/views/categories/helper_functions.php
applications/vanilla/views/categories/table.php

The only way to get a table-view category list to display headings is to use the `Vanilla.Categories.DoHeadings` config setting. This rewrites the writeCategoryTable function to respect a category's `DisplayAs: Headings` property and render in the same way as they did with `Vanilla.Categories.DoHeadings` on.
Partially addresses: https://github.com/vanilla/vanilla/issues/4547

Support headings when writing a category table

---

composer.json

Vanilla can sometimes be used as purely an API. In this case it doesn’t need GD, but won’t install because chrisjean/php-ico requires it.

Allow Vanilla to composer install without gd

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

`VanillaSettingsController::index` currently just calls the old category management page.
This update redirects `/vanilla/settings` requests to `/vanilla/settings/categories`.

Redirect default Vanilla settings page to new category management

---

applications/dashboard/views/log/table.php

dashboardSymbol was refactored, but the call in log/edit was missed.

Fix dashboardSymbol call in log/edit

---

applications/vanilla/controllers/class.categoriescontroller.php
applications/vanilla/library/class.categorycollection.php
applications/vanilla/models/class.categorymodel.php

* Removes unused $maxDisplayDepth variable from Categories Controller. 
* Moves the logic for temporarily saving the DoHeadings config to the model where DisplayAs is calculated.
* Moves the DisplayAs calculation into its own function.
Partially addresses https://github.com/vanilla/vanilla/issues/4547

Contain DoHeadings logic for DisplayAs calculations in Category Model

---

applications/vanilla/models/class.categorymodel.php

By this point, DisplayAs has been calculated so we can safely check the DisplayAs setting instead of checking config and depth.
Partially addresses https://github.com/vanilla/vanilla/issues/4547

Check DisplayAs for Heading check rather than config

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

A new config setting was introduced in https://github.com/vanilla/vanilla/pull/4800 which will allow us to control how the root category is displayed.  Specifically, this config allows the root to display as a flat category.
This update alters the way the category management page works.  Now, when `Vanilla.RootCategory.DisplayAs` is configured to be "Flat", the page will show top-level categories in the flat category format.
Closes #4791

Make manage categories respect Vanilla.RootCategory.DisplayAs

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

This update alters the way editing a category works.  When a category is saved, its parents are checked to determine which management page the user should be redirected to: the root list or a parent's subset of categories.
The following rules are used:
* If the parent is the root, redirect to the root page.
* If the parent is configured to display as flat/nested, redirect to that category's subset.
* If the parent is heading/discussions, check another level higher.
* If all else fails, go to the root page.
Closes #4794

Add parent-relative redirect after editing a category

---

library/core/class.cookieidentity.php

`Gdn_CookieIdentity` attempts to delete cookies, even if they do not exist.  This can be problematic, as documented in https://github.com/vanilla/vanilla/issues/4797
This update alters `Gdn_CookieIdentity::_deleteCookie` to check for a cookie's existence before attempting to remove it.
Closes #4807

Stop CookieIdentity from deleting nonexistent cookies

---

applications/vanilla/controllers/class.categoriescontroller.php
applications/vanilla/models/class.categorymodel.php

Fixes issue where headings are prematurely cancelled, introduced with https://github.com/vanilla/vanilla/commit/dd47bbcd64bc730ece101811c93ca079a9e072c0

Headings calculation

---

applications/dashboard/controllers/class.rolecontroller.php
applications/dashboard/views/role/index.php

This update adds a column to the roles dashboard page: Users.  This column displays the total number of users in the role, along with a link to the user search page, pre-populated with the criteria to search for users of that role.
Closes #2316

Add user count to roles page

---

plugins/ProfileExtender/class.profileextender.plugin.php

Profile Extender uses `include_once` for its registration page controls.  When the first is executed, used for non-checkbox fields, it ensures the second, used for checkbox fields, is not.
This update swaps out the `include_once` calls to `include`.

Fix Profile Extender checkbox display on registration

---

library/core/class.locale.php

Adds an event before returning a translated string.

Add event before translating

---

plugins/GooglePlus/class.googleplus.plugin.php

The Google Plus reaction is missing a label, like the other social reactions.

Add label for Google Plus reaction

---

library/Vanilla/Permissions.php

This update adds the `Vanilla\Permissions` class, which will serve as a central object for handling permissions.  More detail can be found in the associated issue.
Closes #4828

Add Vanilla\Permissions class

---

library/Vanilla/Permissions.php
tests/Library/Vanilla/PermissionsTest.php

This update adds a suite a tests for the Vanilla\Permissions class.
It also fixes a bug I uncovered while writing these tests.

Add unit tests for Vanilla\Permissions

---

applications/dashboard/modules/class.menumodule.php
library/Vanilla/Permissions.php
library/core/class.session.php
tests/Library/Vanilla/PermissionsTest.php

This update moves to replace internal permission checking in `Gdn_Session` with an instance of `Vanilla\Permissions`.  More details may be found in the original issue.
Closes #4834

Refactor Gdn_Session permission checking to use Vanilla\Permissions

---

applications/dashboard/models/class.usermodel.php
library/core/class.session.php

This update swaps out model-specific permission handling for the `Vanilla\Permissions` class.  More detail can be found in the original issue.
Closes #4826

Refactor UserModel to use Vanilla\Permissions

---

library/core/class.uploadimage.php
plugins/editor/class.editor.plugin.php

A bug was introduced in #2711 that caused uploaded images and files to be treated differently. We need to be able to send editor content to a different container and this broke that.

Fixes issues where images no longer uploaded as content

---

bootstrap.php

There are two small changes here:
1. Smarty is now a composer library loaded via the autoloader so a hard-coded path is not necessary (and also a bug).
2. I’m trying to get rid of some of the peculiarities of the factory in order to replace it with a more flexible dependency injection container. Converting the Gdn_Request from a “real singleton” to a “singleton” helps here. Note that Gdn_Request::Create() just news up a Gdn_Request object anyway.

Clean up the bootstrap

---

applications/dashboard/views/modules/userphoto.php

closes #4299 
Note this cannot be done globally because the avatar can substitute for the name in other contexts, and so must always be the username where there could be many of them.

Add meaningful alt text to profile avatar image

---

applications/dashboard/controllers/class.entrycontroller.php
applications/dashboard/views/entry/signout.php
applications/dashboard/views/settings/homepage.php
applications/dashboard/views/user/ban.php
themes/mobile/class.mobilethemehooks.php

Vanilla uses html5 and in html5 the type="text/javascript" is optional.
Also removed an unused `$Script` variable definition from applications/dashboard/controllers/class.entrycontroller.php

Remove "type" attribute from script tags

---

library/Vanilla/Permissions.php

At least for my installation the permission array values are strings, not integers. That's why using equal "==" should be enough.
Using the identical comparator "===" caused false positives and in my test installation the dashboard was accessible even for guests.

Use "==" instead of "===" for permission comparison

---

applications/dashboard/models/class.usermodel.php
library/core/class.session.php

This update fixes:
* An instance of `Vanilla\Permissions` was attempting to be read as an array in `UserModel::getSession`.
* JunctionID not being passed in category permission checks, resulting in global permission grants if you had said permission in _any_ category instead of the specified one.

Fix critical permissions errors introduced in #4877

---

applications/dashboard/controllers/class.rolecontroller.php
applications/dashboard/models/class.permissionmodel.php
applications/dashboard/models/class.rolemodel.php

This update adds a new config value: `Vanilla.HideRoleCategoryPermissions`.  This config controls whether or not the per-category permissions are displayed when editing a role.  More information can be found on the original issue.
Closes #4827

Add ability to hide category permissions when editing a role

---

plugins/Quotes/class.quotes.plugin.php

Fixes https://github.com/vanilla/vanilla/issues/4747
Also check the category's permission!

Check permissions correctly before displaying the quote button

---

applications/dashboard/js/user.js

Pass the context to the listeners in the contentLoad block in user.js. Fixes issue where each click to RevealPassword was counting as 3.
Closes https://github.com/vanilla/vanilla/issues/4845

Fix modal password generation

---

applications/dashboard/controllers/class.entrycontroller.php

This update adds a new event to `EntryController`: AfterConnectSave.  This event will allow plug-ins to perform actions against a user after they have successfully connected via SSO, and `UserModel::save` or `UserModel::register` has been executed, under the following conditions:
1. [Logging in as a user with an existing UserAuthentication entry.](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/controllers/class.entrycontroller.php#L524)
2. [Connecting to an existing user where Garden.Registration.AutoConnect is enabled.](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/controllers/class.entrycontroller.php#L602)
3. A new user is registered for the connection. (see [here](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/contro …

Add AfterConnectSave event

---

library/core/class.bbcode.php
plugins/Quotes/class.quotes.plugin.php

Fixes https://github.com/vanilla/vanilla/issues/4700
The fix is not retroactive.

Add distinction between comments and discussion in BBCode quotes

---

applications/dashboard/modules/class.menumodule.php

The menu module does not seem to be used anywhere anymore.
If the reviewer comes to the same conclusion we should file an issue about deprecating/removing it.
Fix https://github.com/vanilla/vanilla/issues/4887

Check permissions with Gdn_Session::checkPermission in MenuModule

---

plugins/Quotes/js/quotes.js

Add a CSS class to the div wrapper on QuoteFolding.
Closes https://github.com/vanilla/vanilla/issues/4876

Add a CSS class to the div wrapper on QuoteFolding

---

applications/vanilla/js/discussions.js

On the profile/discussions page, the more pager appears in the container where the paging occurs. The morepager configuration currently appends additional discussions to the end of the container. This results in the more link being anchored in the middle of the discussion list rather than at the end. 
This PR configures morepager to prepend the discussions to the more link. It also removes the unneeded not(.Message .MorePager) filter.
Closes https://github.com/vanilla/vanilla/issues/4939

Fix profile/discussions more pager

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/js/dashboard.js
applications/dashboard/js/src/main.js
library/core/class.upload.php

Rely on UploadImage to validate the image and throw an error if the upload is incorrect and remove adding a form error if no image is found.
Closes https://github.com/vanilla/vanilla/issues/4919

Fix necessity to add image to email styles form

---

applications/dashboard/models/class.permissionmodel.php
applications/dashboard/models/class.usermodel.php

There are circumstances wherein `PermissionModel::getJunctionPermissions` may not receive a RoleID or a JunctionID in its `$Where` parameter (e.g. site is configured with Garden.Registration.ConfirmEmail, but no "unconfirmed" role).  However, the function currently assumes one or the other will be set.  If RoleID isn't present, it will attempt to use JunctionID, without attempting to verify it is available.  This can cause a fatal error, because the query generated by this function may have an empty value for one of its conditions (e.g. `... where p.junctionid = order by ...`).
This update alters the logic of `PermissionModel::getJunctionPermissions` to the following:  If RoleID is available, use it.  If it isn't, but JunctionID is, use that.  If neither are available,  use an empty …

Handle no RoleID or JunctionID in getJunctionPermissions

---

applications/dashboard/views/home/unauthorized.php

Only sanitize the message, not the translation of 'PermissionErrorMessage'. Fixes issue where HTML in the translation of 'PermissionErrorMessage' is displayed as HTML.

Allow HTML translations for 'PermissionErrorMessage'

---

applications/dashboard/views/email/email-basic.tpl
applications/dashboard/views/email/src/email-basic.php
applications/vanilla/controllers/class.discussioncontroller.php
container.html

Vanilla uses html5 and in html5 the default type is "text/css". Based on [that information](http://www.w3schools.com/tags/att_style_type.asp), this type is the only supported type anyway. So even if browsers wouldn't be compatible with html5, they would treat a simple `<style>` tag correctly.

Drop attribute "type" for style tags

---

applications/dashboard/models/class.usermodel.php

`UserModel::getSession` has an issue with verifying sign-in permissions when the email confirmation is required for users.  It attempts to run a permission check/assignment functions against a permissions array, instead of the permissions object.
This update tweaks the logic to avoid grabbing the permissions array until after the proper checks and updates have been made.

Ensure unconfirmed role has sign-in permissions

---

plugins/Quotes/class.quotes.plugin.php

Fix a [regression bug](https://github.com/vanilla/vanilla/pull/4925/files#diff-65a59ade5d93c6930c77c9accc6d31ceR242) where the quote button would not appear in some case because 'Discussion' is not always an event's argument.

Fix the quote button not appearing in multiple cases

---

applications/vanilla/views/categories/all.php
applications/vanilla/views/categories/helper_functions.php

Refactor and edit the modern category view to render in the same way as the table view. This includes rending children for any heading-type category, no matter the depth.
Closes https://github.com/vanilla/vanilla/issues/4916

Ensure modern category list view has same organization as table view

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/views/settings/homepage.php
library/core/class.thememanager.php

This allows a theme to set its expected layout in its about.php array. This layout will be saved to config when the theme is enabled. 
When previewing a theme, it will preview with the expected layout.
To test, edit the about.php of a theme and add
```
'Layout'      => [
'Categories'  => 'modern',
'Discussions' => 'modern'
]
```
Clear your cache and then enable the theme. Ensure that the layout on `/settings/homepage` has changed to what has been specified in the theme. Preview the theme and make sure that no matter what the config is set as, the theme previews with the settings specified in about.php.
Closes https://github.com/vanilla/vanilla/issues/4666

Give themes the option to set their layout

---

applications/dashboard/settings/class.hooks.php
library/core/class.upload.php

Add a special schema and domain of static://v that links to files within the application. The reasoning for this is to provide a hook for a static CDN to override some of these files, but default to the local server for OSS and development.

Add static uploads

---

library/core/class.request.php

There are two main changes here:
1. Check for X_REWRITE first since that is the situation a properly configured installation will have. If X_REWRITE is found then don’t check $_GET for a path argument.
2. Remove some redundant logic when parsing the $_GET that was probably a result of previous refactoring.

Simplify the request parsing logic a bit

---

applications/dashboard/models/class.usermodel.php

By now the whole "user needs to confirm mail address" process is quite of buggy. Although the Unconfirmed role is explicitly described as the role a user gets if he needs to confirm his mail address, that role is not assigned. Instead of this, new users only get the Member role, which grants them more rights than the admin would have guessed.
That can only be "fixed" if Garden.Registration.DefaultRoles in the config is set to the unconfirmed role ID. But that is only a workaround, which might lead to unwanted behavior later on.
If the admin decides that his users will no longer need to require the mail confirmation by removing the tick from the "Require users to confirm their email addresses (recommended)" checkbox in /dashboard/settings/registration, new users still will be assigned to …

Assign Unconfirmed role to new users if confirmation is required

---

library/core/class.format.php

In WYSIWYG mode a &nbsp; is added as the last character of a post.
If the last part of your post is an URL you will end up with the following text: `... http://example.com&nbsp;`
Since our URL regex is pretty lenient the whole thing is taken as the URL and then passed to linksCallback which removes the last punctuations characters (in this case ";") which break the &nbsp; entity.
I think that having a lenient URL regex is good because that way we can parse weird URLs correctly so I decided to try to detect if there is a (or many) &nbsp; at the end of the URL and put it/them as punctuation (it will be removed from the url and put back after the URL is wrapped with an anchor).
EDIT: The last space in WYSIWYG is a &nbsp; so you have to hit space at the end.

Exclude &nbsp; as part of the URL when formatting links

---

applications/dashboard/views/default.master.tpl

There are three links in the default.master.tpl which have been commented out. Nevertheless they are processed by Smarty and written as HTML. If they aren't already obsolete they should better be commented with Smarty comment tags so that their content is never processed.

Replace HTML comments with Smarty comments

---

applications/vanilla/models/class.categorymodel.php
applications/vanilla/models/class.vanillasearchmodel.php

The normal search was not searching in categories that had the flag `HideAllDiscussions`.
I updated categoryWatch doc block and parameter name to be more significative.

Search should return results from all categories we have permission to view

---

applications/vanilla/models/class.draftmodel.php

Currently when adding a new draft, the draft ID form value will be retrieved as the string '0' and if there's no category, the category ID will be retrieved as and empty string. The DraftModel expects its falsey values for draft ID to be an empty string and Category ID to be === false. As such, we never reach the if ($Insert) block on line 162.
This PR adjusts the $Insert calculation and category ID check to ensure we properly calculate the category ID on a draft if it doesn't exist.
Closes https://github.com/vanilla/vanilla/issues/4880

Allow draft saves on new posts

---

applications/vanilla/controllers/class.categoriescontroller.php

This update moves the permission check in `CategoriesController::index` to a much higher point in the method.  This should stop needless processing occurring if the current user doesn't even have permission to view the resource.
Previous behavior might've allowed a user to view a category with a display type of Heading, Flat or Nested, even though they didn't have view permissions.  However, the page would likely be empty, due to [`CategoryModel::filterCategoryPermissions`](https://github.com/vanilla/vanilla/blob/ea84fccb2a7b2ade07fa0dace703400c63056fd3/applications/vanilla/models/class.categorymodel.php#L624) removing any categories the user didn't have access to view discussions in.

Check permissions earlier when viewing a category

---

applications/vanilla/views/categories/helper_functions.php

We pass the row's children to the getWriteChildrenMethod function, when it expects the category itself. This PR fixes that.
Fixes issue where comma-delimited child categories are not displaying in table layouts.

Fix call to getWriteChildrenMethod

---

applications/vanilla/controllers/class.postcontroller.php

draftModel->delete() is deprecated, deleteID() should be used instead
https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.draftmodel.php#L214

Replace deprecated draftModel->delete() call

---

library/core/class.request.php

Allow requests to be made with an application/json content type. In these cases the raw input will be json-decoded and passed as the post.

Support a JSON content type in the request

---

library/core/class.session.php
tests/APIv0/APIv0.php
tests/APIv0/SmokeTest.php

This update moves the anti-CSRF token from a static value stored in the user record to a per-browser cookie.
A few new methods were added to `Gdn_Session`:
* `decodeTKCookie`
* `generateTKPayload`
* `generateTKSignature`
A couple methods were updated in `Gdn_Session`:
* `ensureTransientKey` - There was already an anti-CSRF measure stored with cookies in Vanilla, but it was seemingly only ever used for guests.  It's been updated to work with all users.
* `transientKey` - Setting a transient key with this method now also sets the value in the users cookie by default.
Since the transient key mechanic was fundamentally altered, it broke our existing integration tests.  These tests were looking up values in the database.  Now, since the client tells Vanilla what the transient key should be, a …

Move CSRF token into browser cookie

---

library/Vanilla/Logger.php

Logger::removeLogger incorrectly compares a [LoggerInterface, int] tuple to a passed LoggerInterface object using ===, which will always fail. This PR correctly addresses the first field of the tuple so that we are comparing LoggerInterface instances directly.

Fix Logger::removeLogger() bad comparison

---

applications/dashboard/controllers/class.utilitycontroller.php
library/core/class.dispatcher.php
library/core/functions.general.php
library/database/class.databasestructure.php

This update performs a few improvements related to maintenance mode:
1. A new function, `inMaintenanceMode`, has been added.  This function returns true/false, depending on whether or not Garden.UpdateMode (maintenance mode) is enabled.
2. The dispatcher's direct call to check the config value of Garden.UpdateMode has been removed in favor of using `inMaintenanceMode`.
3. `Gdn_DatabaseStructure::__construct` now sets its `$alterTableThreshold` property to 0 (disabled) if the site is in maintenance mode.
4. A new utility endpoint has been added: /utility/maintenance.  This endpoint can enable or disable the maintenance mode status for a site, depending on the value of the `$updateMode` parameter it receives.  Additionally, this endpoint has the ability to receive a specific value for …

Improve maintenance mode

---

applications/dashboard/models/class.updatemodel.php

Only `runStructure()` is used now.
I think that everything else was replaced by the AddonsManager.

Deprecate all dead code in UpdateModel

---

js/global.js
library/core/functions.render.php

Any CSS class prefixed with `js` should signify that it is there for javascript purposes and should not be styled on. Going forward, this PR allows us to use `js-hijack` for hijacking rather than `Hijack`.
Also removes superfluous .Popin class from the popin badge rendering function.
Closes https://github.com/vanilla/vanilla/issues/3937

Add js-hijack CSS class as hijack selector

---

applications/dashboard/models/class.permissionmodel.php

Fixes #5000
Only accepts arrays now!
Raise a warning and return in other cases.
All immediate usage of PermissionModel->define() is done using arrays but I added a warning for debug purpose.

Make PermissionModel->define() more strict about its received paramters

---

plugins/editor/js/editor.js

Close editor dropdowns when the user clicks outside of a dropdown.
Closes https://github.com/vanilla/lithe/issues/60

Close editor dropdowns when the user clicks outside of a dropdown

---

library/core/functions.general.php

Just stumbled upon this blog post and thought it might be a quick and easy (though micro) performance win for safeGlob(): https://www.exakat.io/php-likes-sorting/

Speed up safeGlob() by surpressing sorting

---

applications/vanilla/controllers/class.discussioncontroller.php
applications/vanilla/modules/class.newdiscussionmodule.php
applications/vanilla/views/post/comment.php

Although "Vanilla.Categories.Use" is set to false, category is shown in breadcrumbs and was used for "New Discussion" module. Using no categories at all should hide categories in all aspects for users.

Hide category from breadcrumb on New Discussion when categories are disabled

---

js/global.js

Makes the `requires_quotation` flag more strict about username quoting.
Surrounding names with quotes it not that much of a big deal and it saves a lot of hassle.
Anyway, in most cases, the autocomplete will do the job.
Fixes https://github.com/vanilla/vanilla/issues/4658

Mentions now quote most usernames

---

applications/dashboard/models/class.spammodel.php

This update adds a simple check to `SpamModel::isSpam`, which determines if the user is a super admin or bot account.
Closes #4873

Check user admin flag in SpamModel::isSpam

---

.travis.yml
index.php

Just what it says on the tin.
We have forked for version 2.4 release with the existing PHP 5.4 requirements: https://github.com/vanilla/vanilla/tree/release/2.4
Version 2.5 will require PHP 5.6.

Require PHP 5.6

---

library/core/class.markdownvanilla.php

The doListFix operation adds a newline before and unordered list if one doesn't already exist (see https://github.com/vanilla/vanilla/pull/4066). The doHeaders implementation in the Markdown library interferes with this.
This PR changes the order so that the doListFix operation comes before the doHeaders operation.
Fixes issue where list items appearing directly after a heading are wrapped in `<p>` tags.
Closes https://github.com/vanilla/vanilla/issues/5041

Change order of list fix in markdown processor

---

applications/dashboard/models/class.usermodel.php
applications/dashboard/views/entry/registerapproval.php
applications/dashboard/views/entry/registerbasic.php

and use the correct config for min length
`Garden.Registration.MinPasswordLength` was used only user for UI display so I replaced it with  `Garden.Password.MinLength` which is used to validate the password length
Fixes #5047
Fixes #2708

Improve password requirement message

---

applications/dashboard/models/class.activitymodel.php

Any changes you make to $Data during a BeforeCheckPreference event get overwritten by old Data in this line (if either email or popup preferences are present): self::$Queue[$Data['NotifyUserID']][$Data['ActivityType']] = [$Data, $Options];
If the reference is passed, you can change the data while in the event and have the changes persist.
https://open.vanillaforums.com/discussion/comment/245537#Comment_245537

Pass reference to Data array instead of array

---

composer.json
library/Garden/EventManager.php
library/Garden/LazyEventHandler.php
library/core/class.pluginmanager.php
tests/Library/Garden/EventManagerTest.php
tests/fixtures/src/BasicEventHandlers.php
tests/fixtures/src/Container.php

The EventManager class replaces the event handling that the Gdn_PluginManager used to do. The goals of the EventManager are the following:
- Add parameter support to events so that we no longer have to use the object polluting EventArguments property.
- Add support for event priorities so that event handlers can be ordered.
- Consolidate event types. Overrides, creates, and handlers are all now one kind of event.

Add the EventManager class

---

applications/vanilla/settings/class.hooks.php

Add CSS assets before custom.css on the front end. Fixes issue where Tags CSS appears after custom theme CSS.

Add CSS assets before custom.css

---

applications/vanilla/settings/class.hooks.php

Readd empty string to $types array after Tagging move. Fixes issue where you cannot delete a tag from a discussion.

Readd empty string to $types array after Tagging move

---

applications/dashboard/controllers/class.settingscontroller.php
library/Vanilla/Addon.php
library/core/class.pluginmanager.php

Move  the `oldType` addon key from the `special` array into the `info` array in `Vanilla\Addon`.
Closes #5119

Move oldType into addon info array

---

library/Garden/Schema.php
tests/Library/Garden/BasicSchemaTest.php
tests/Library/Garden/NestedSchemaTest.php

This update swaps around the order of the name and type specifiers in `Garden\Schema`'s short param syntax.  Unit tests have been updated accordingly.
Closes #5132

Swap short param syntax order in Garden\Schema

---

conf/config-defaults.php

Add default password min length config setting. Fixes issue where registration message indicates that the password must be at least 0 characters long.

Add default password min length config setting

---

applications/dashboard/models/class.mediamodel.php

Account for Object-type media in MediaModel delete method. Fixes issue where attachments cannot be removed from discussions and discussions with attachments cannot be deleted.

Account for Object-type media in MediaModel delete method

---

bootstrap.php

The cache currently fires an event on initialization which means that it requires the plugin manager before its available. This means that the plugin manager’s configuration needs to be moved up.
Before the container, the plugin manager would just return null before being configured. Because of auto-wiring that’s not the case with the container.

Install the addon managers earlier

---

library/core/class.factory.php
library/core/class.gdn.php

Fixes a bug when installing a singleton with no constructor args.

Fix shared object installation

---

applications/vanilla/modules/class.usercommentsmodule.php
applications/vanilla/modules/class.userdiscussionsmodule.php
applications/vanilla/views/modules/usercomments.php
applications/vanilla/views/modules/userdiscussions.php

At present, in the profile controller there are ways of viewing all of a user's posts or comments but there is no way of having a limited widget view of the most recent. This pull request would create two modules to do that.

Create modules see a user's most recent comments and posts

---

applications/dashboard/controllers/class.profilecontroller.php

Fixes issue where json is not rendered at API endpoint when`Garden.Profile.ShowActivities` is set to false.
Partially fixed by: https://github.com/vanilla/vanilla/pull/5088
Closes https://github.com/vanilla/vanilla/issues/5082

Render the json response at dashoard/profile.json

---

applications/dashboard/models/class.searchmodel.php

This update adds a call to `commentUrl` if a result row in `SearchModel::search` is a comment.

Use commentUrl on comment results in search

---

library/database/class.mysqldriver.php
library/database/class.sqldriver.php

[`Gdn_SQLDriver::put`](https://github.com/vanilla/vanilla/blob/0a341172fde05143958592d5ec1beb67bd03f393/library/database/class.sqldriver.php#L1618) makes a call to `Gdn_SQLDriver::getUpdate` with five parameters: from/table, set, where, order by and limit. The problem is [`Gdn_SQLDriver::getUpdate`](https://github.com/vanilla/vanilla/blob/0a341172fde05143958592d5ec1beb67bd03f393/library/database/class.sqldriver.php#L851) only supports three parameters: from/table, set and where.
This update adds support for the remaining two parameters, order by and limit, to `getUpdate` in `Gdn_SQLDriver` and `Gdn_MySQLDriver`. Code was adapted from [`Gdn_SQLDriver::getSelect`](https://github.com/vanilla/vanilla/blob/0a341172fde05143958592d5ec1beb67bd03f393/library/database/class.sqldriver.php#L820) to …

Update SQLDriver::getUpdate to use order and limit parameters

---

library/core/class.cache.php

This update alters `Gdn_Cache::makeKey`, which is used by `Gdn_Memcached::set` and `Gdn_Memcached::get`, to ensure the strings generated are [valid Memcached keys](https://github.com/memcached/memcached/blob/d9dfbe0e2613b9c20cb3c4fdd3c55d1bf3a8c8bd/doc/protocol.txt#L41). This is done by stripping out any whitespace or control characters from the keys and making certain they are no longer than 250 characters.
Closes #4996

Ensure Memcached keys are valid

---

applications/dashboard/library/class.nestedcollection.php
applications/dashboard/modules/class.dropdownmodule.php
applications/dashboard/views/modules/dropdown.php
applications/dashboard/views/modules/me.php
plugins/AllViewed/class.allviewed.plugin.php

Updates MeModule settings to use DropdownModule to make it configurable and sortable.
Also:
* Removes sprites from the dropdown menu.
* Adds the ability to add a list item CSS class to an item.
* Updates MarkAllViewed's way of adding an item to the menu.
* Adds the ability to add a url for the dropdown trigger.
Other than removing the sprites, this update does not affect the markup of the MeModule menu and should not affect any themes.

Update MeModule settings to use DropdownModule

---

applications/dashboard/models/class.assetmodel.php

The factory had a method to search the entire factory for items matching a wildcard pattern. This functionality isn't supported in the new container and it won't be added because it's just a bad practice.
To temporarily kludge past this I'm just going to search through our known file extensions. If some OSS plugin adds view handler support we can add that one. Longer term we'll think of a better way to do this.

Kludge AssetModel::viewExtensions() to work with the container

---

library/Vanilla/AddonManager.php
library/core/class.applicationmanager.php
library/core/class.pluginmanager.php

This update renames `checkDependants` and `lookupDependants` to use the -ent spelling. Functions using the -ant spelling are left behind and trigger a deprecation warning. Calls to these methods have also been updated to use the -ent name.
Closes #5139

Deprecate alternatively-spelled methods in AddonManager

---

applications/dashboard/js/colorpicker.js
applications/dashboard/views/modules/configuration.php
library/core/class.form.php

Configures the color picker to optionally accept empty values and also accepts 'transparent,' 'initial' or 'inherit' as values.
* Adds an options param to the color picker renderer for configuring the 'AllowEmpty' setting.
* Passes the configuration module options data to the color rendering function.
Closes https://github.com/vanilla/vanilla/issues/5040

Configure color picker to optionally accept empty values

---

applications/vanilla/models/class.discussionmodel.php

- Move the BeforeGetCount event to an earlier point. Fixes https://github.com/vanilla/vanilla/issues/2222
- Make sure we do not skip permissions check. [An optimization that was added during the category refactoring and it was skipping the permissions check](https://github.com/vanilla/vanilla/commit/77fe648508c76f5342d396d26471d6ba60e99130#diff-461fbde3929a6742e0a92301a01cdd04R1403).
- Better comments

Refactoring of DiscussionModel->getCount(). Also fix permission checks

---

library/Garden/ArrayContainer.php
library/Garden/Exception/ContainerNotFoundException.php

This is a base implementation of the ContainerInterface to act as a default when a more sophisticated container library isn’t available.

Add the ArrayContainer class

---

applications/dashboard/views/role/index.php

When viewing the role management page, the link behind total number of users in the role is currently broken. It points to the user search page in the dashboard, using the `Filter` param for keywords. However, that page currently uses the `Keywords` param for searches. This update fixes that parameter name.
Closes #4994

Fix link to filtered users from roles page

---

applications/vanilla/library/class.categorycollection.php

Many views will render children if they exist. This PR unsets the children after flattening a category list.

Reset the Children property when flattening categories

---

library/Vanilla/Permissions.php
library/core/class.session.php

This update adds the ability to universally override permissions in `Vanilla\Permissions`. This ability to override the result of permission checks has been added to `Gdn_Session`. Banned or deleted users will always return `false`. Admin users will always return `true`.
More details available in the original issue.
Closes #5162

Add overrideAll to Vanilla\Permissions

---

applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/views/vanillasettings/editcategory.php

* Removes the CustomPoints field from the add/edit category form in favour of adding it to the plugin that uses it.
* Moves the 'AfterCategorySettings' event to fire no matter whether we're adding or editing a category.
Relies on https://github.com/vanilla/internal/pull/912

Remove ShowCustomPoints property on Vanilla Settings Controller

---

applications/dashboard/views/admin.master.php

Add event argument for showing/hiding the Vanilla Version in the dashboard footer.
Relies on https://github.com/vanilla/vanillainfrastructure/pull/84
Closes https://github.com/vanilla/vanillainfrastructure/issues/80

Add event argument for showing/hiding the Vanilla version

---

applications/dashboard/models/class.tagmodel.php

`TagModel::joinTags` can potentially use an instance of `Gdn_Dataset` in its loops. One of these loops passes its elements by reference. If `Gdn_Dataset` is the source, the following error is thrown in HHVM: An iterator cannot be used with foreach by reference
This update checks the type of the `$data` param and, if necessary, switches it up for a reference to an instance of `Gdn_Dataset`'s results array.
Closes #5141

Update TagModel::joinTags to handle iterating Gdn_Dataset

---

applications/vanilla/models/class.discussionmodel.php

https://github.com/vanilla/vanilla/blob/9656876e959f55758fb1f776d6e6f5d97fb17c11/applications/vanilla/models/class.discussionmodel.php#L1887 will catch it if the category is not set.
The group application uses the BeforeSaveDiscussion event to inject a categoryID

Let Form->validate check that the category is properly set

---

applications/vanilla/views/modules/usercomments.php

The display of comments in the user comments module looked sparse without a linkable title to the discussion, especially when you display the UserComments next to the UserDiscussions that does have a link to the discussion. This PR adds a title to the comment.

Add the title of a discussion to a comment in the user comments module.

---

library/Garden/Web/RequestInterface.php
library/core/class.request.php
tests/Library/Core/RequestTest.php

This update adds forwards-compatible methods to Gdn_Request and tests to support them. For details, see the original issue.
Closes #4162

Add forwards-compatible methods to Gdn_Request

---

plugins/editor/class.editor.plugin.php

The cloudfiles plugin stored its scratch files in /uploads/cftemp/ and the editor was specifically checking for that path slug. s3files stores its scratch files in /uploads/cloudtemp/ and so the "cftemp" check was failing and files were not being deleted.
This fixes that problem, not in a great way but ok for now.

Allow editor to find and delete locally copied scratch files from both s3 and cf

---

plugins/Flagging/views/flag.php
plugins/Flagging/views/report.php
plugins/Flagging/views/reportcomment.php

This fixes an issue where discussions and discussion comments created by flagging actions don't populate the source comment and reason given by the user doing the flagging.
Also fixes comment link URL and display on the popup where the user doing the flagging enters their reason text.

Flagging plugin: fixed broken array references

---

bootstrap.php

This is a stopgap to #5031 so that other PRs can add DIC rules in the
bootstrap without the entire DIC being configured.

Make the container available in the bootstrap

---

applications/dashboard/modules/class.dropdownmodule.php
applications/dashboard/views/modules/dropdown-twbs.php
applications/vanilla/js/category-settings.js
applications/vanilla/js/categoryfilter.js
applications/vanilla/models/class.categorymodel.php

Add an attributes param to the trigger and render the attributes on the the dropdown-twbs view.
Fixes issue where all children of a category have their trigger updated when their parent's display as property is set.

Add category ID to dropdown trigger data attributes in category settings

---

library/core/functions.general.php
tests/Library/Core/JsonFilterTest.php

This update adds a global `jsonFilter` function, which is intended to prepare data for conversion to JSON via `json_encode`. Currently supported are:
1. Converting `DateTimeInterface` subclasses (e.g. `DateTime`) from objects to their RFC 2822 representations
2. Converting packed IP addresses to their human-readable forms with `ipDecode`.
Closes #5156

Add jsonFilter function and tests

---

library/core/class.format.php
plugins/HtmLawed/class.htmlawed.plugin.php
plugins/editor/js/advanced.js

Stops adding `target="_blank"` to anchors in user generated content. 
Also blocks the target attribute in HTMLawed unless it is explicitly set in config.
Closes https://github.com/vanilla/vanilla/issues/4958

Stop adding target="_blank" to ugc links

---

library/core/class.session.php

Backstory: We added the Permissions class a while back as a better way
to wrangle permissions than just an opaque array. When doing so there
was an incompatibility with Gdn_Session’s getPermissions() method.
We could have come up with a new method, but not using the proper
getter name for the permissions object kind of sucked. So we put a
process in place:
1. Add the getPermissionsArray() method and deprecate getPermissions()
temporarily.
2. Look through our source code for getPermissions() calls and migrate
them to getPermissionsArray(). We’ll eventually want to refactor this
too as manipulating the internal array should be a no-no.
3. Re-introduce getPermissions() in the correct form (this PR).
I recommend doing a final search through our repos for bad calls to getPermissions() and then …

Bring Gdn_Session->getPermissions() back

---

library/Garden/Schema.php
tests/Library/Garden/BasicSchemaTest.php
tests/Library/Garden/NestedSchemaTest.php

This update does a few things:
1. Adds `Garden\Schema::getParameters`, which returns the schema's current parameter array.
1. Adds `Garden\Schema::merge`, which allows one instance's parameters to be consumed by another instance.
1. Implements the ability to specify a `Garden\Schema` instance as a parameter value. In this way, a single schema object can be re-used multiple times as a child in other schemas.
1. Includes tests for the `merge` method and reusing schemas as children.
Closes #5248 
Closes #5250 
Bonus: Fixes some improper type adjustment in `Garden\Schema::dumpSpec`.

Add merging and nesting instances to Garden\Schema

---

library/Vanilla/Permissions.php
library/core/class.session.php
tests/Library/Vanilla/PermissionsTest.php

Bans revoke all permissions from a Permissions instance, but with a flexible API.
- Bans are added with the **addBan()** method. You can add as many bans as you want and they stack on top of each other.
- If a Permissions instance has a ban then all permission checks will return false.
- Bans can be bypassed by passing their names as a pseudo permission to any permission check.
- Bans themselves can also specify exceptions when being added so that users with given permissions will not be considered banned.
This implementation uses bans for banned or deleted users. In the future they will be used for private communities, update mode, 2 factor authentication, and XRF prevention.
This supersedes and removes the **setOverrideAll()** method. Bans along with **isAdmin()** handle permission …

Add bans to the Permissions class

---

applications/dashboard/controllers/class.addoncachecontroller.php
applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/js/addoncache.js
js/global.js

This update does a few things:
1. Adds a new controller, `AddonCacheController`, to handle interfacing with the addon cache via endpoints.
2. Adds two endpoints to the new controller: `verify` and `clear`. The `verify` endpoint scans addons of a particular type and verifies the cache is in sync with the directory contents. The `clear` endpoint nukes the current addon cache.
3. Implements an automatic, asynchronous request for cache validation upon loading up the applications, plug-ins or theme management pages. This request is limited to the type currently being viewed (e.g. only verify the themes cache if you're viewing the themes page). Based on the result, the user is warned their cache is outdated and prompts them to clear it. If they elect to clear it, a second request is sent to the …

Implement basic addon cache validation and clearing

---

library/database/class.database.php
library/database/class.databasestructure.php
library/database/class.sqldriver.php

This PR addresses a couple of issues.
- Delete queries were erroneously returning data sets which would cause a general error on the next query because they were getting fetched improperly.
- Update and delete queries were specifying a null return type which meant that a regular expression would be called on those queries to figure out the return type.
- I threw in a doc block fix and some “==“ to “===“ micro-opts.

Fix the return type for delete queries

---

applications/dashboard/controllers/class.entrycontroller.php
applications/dashboard/models/class.logmodel.php

Currently, when a user connects over SSO and triggers a SPAM filter, they're dumped to a page with a single error message: "Tell us why you want to join!". There is no form control to enter any text. It's just the error and the "Connect" button.
This update alters the connect workflow to log the connection attempt if the SPAM filter is triggered. This is done by detecting if the registration failed and `DiscoveryText` becomes a required field. Since the registration is only logged if this field is populated, a generic "SSO connection" message is added to the log entry as the `DiscoveryText`. If the registration fails again with a result that matches the value of `UserModel::REDIRECT_APPROVE`, the attempt is logged and the user is redirected to Vanilla's "thanks for registering" page. This …

Handle SSO connections that trigger SPAM filters

---

applications/vanilla/settings/class.hooks.php

This update increments a user's comment or discussion totals when a post they created has been restored from the log table.
Closes #4988

Fix user comment and discussion counts not being updated when posts restored

---

applications/dashboard/settings/structure.php

Fixes https://github.com/vanilla/vanilla/issues/5227
Depends on https://github.com/vanilla/vanilla/pull/5257
We will need to run this everywhere to lock the current settings!
Some coordination will be needed!

Lock the current database encoding

---

plugins/ProfileExtender/class.profileextender.plugin.php

Fix query error in Profile Extender exporter that could duplicate results when invitations are used.

Fix user duplication in Profile Extender's CSV exports

---

conf/config-defaults.php
library/database/class.database.php

Remove Database.ConnectionOptions.1002 and set the encoding and timezone directly in the database object
We default to utf8mb4 because it is compatible with utf8 and won't cause any problems.
Fix https://github.com/vanilla/vanilla/issues/5226

Set charset and timezone directly in the database object

---

applications/dashboard/models/class.exportmodel.php
applications/dashboard/models/class.importmodel.php
conf/config-defaults.php
library/database/class.database.php

Will need a rebase after https://github.com/vanilla/vanilla/pull/5257 is merged.
Fixes https://github.com/vanilla/vanilla/issues/5228
Depends on https://github.com/vanilla/vanilla/pull/5256
From my tests, this update should not affect already created databases with the utf8 charset.

Update charset from utf8 to utf8mb4

---

applications/dashboard/views/modules/dropdown.php
applications/vanilla/views/categories/helper_functions.php
applications/vanilla/views/discussion/helper_functions.php

Fix styling issues with the MeModule settings dropdown.
After https://github.com/vanilla/vanilla/pull/5100, the MeModule settings dropdown was rendering with the arrow looking real weird because of the OptionMenu class on the wrapper and the badges didn't have the correct styling due to the incorrect badge class being applied.
Closes https://github.com/vanilla/vanilla/issues/5252

Fix arrow and alerts in MeModule settings dropdown

---

bootstrap.php
library/Vanilla/AddonManager.php
library/core/class.plugin.php

Depends on #5031.
Register plugin events to the EventManager directly, bypassing the need for Gdn_PluginManager. A side-effect of this PR is that plugins are now created through the container which means that plugin authors can declare dependencies for their plugins too--that's a beautiful thing.

Bind addon events to the EventManager directly

---

library/core/functions.general.php
library/database/class.dataset.php
tests/Library/Core/DataSetTest.php
tests/Library/Core/JsonFilterTest.php

This will make returning datasets from API controllers easier.
Closes #5254

Make Gdn_DataSet implement JsonSerializable

---

library/core/functions.error.php

Hi,
I realized a missing translation on `not Found Exception()` while I was working with the 404 page and I saw the word "page" as is, without the proper translation for my locale.
Cheers!
**In another subject**: That kind of translation is not very friendly with some languages like spanish. The use of `The %s` for spanish translators is very difficul, because in spanish we don't have a explicit translate for `The`. We have to explicitly define the gender (`La` for woman or `El` for man) of the person/thing/subject that we are talking about ([further reading](http://www.spanishdict.com/blog/el-vs-la-a-guide-to-your-spanish-nouns/)).
For instance: *The %s you were looking for could not be found.*
In 404 pages, `%s` will be `página` (female noun). So the translation in that case is:
`La …

Forgotten translation on notFoundException()

---

bootstrap.php
library/Vanilla/AddonManager.php

Register the AddonManager autoloader right after the first request. In this way the AddonManager will not be created too early and another line from the bootstrap no longer depends on order.
Depends on #5031.

Add autoloader registration to the AddonManager

---

library/database/class.databasestructure.php

If we call `Gdn_DatabaseStructure->columnExists()` and switch table the `_ExistingColumns` attribute is not reset and cause an error!
Example:
```php
// Check for a column exist on the Permission table
$Construct->table('Permission');
$Construct->columnExists('Vanilla.Tagging.Add');
// Define the log table
$Construct->table('Log')
->primaryKey('LogID')
->column('Operation', array('Delete', 'Edit', 'Spam', 'Moderate', 'Pending', 'Ban', 'Error'), false, 'index')
->column('RecordType', array('Discussion', 'Comment', 'User', 'Registration', 'Activity', 'ActivityComment', 'Configuration', 'Group', 'Event'), false, 'index')
->column('TransactionLogID', 'int', null)
->column('RecordID', 'int', null, 'index')
->column('RecordUserID', 'int', null, 'index')// user responsible for the record; …
```

Make sure that we reset the Gdn_DatabaseStructure when switching table

---

applications/dashboard/controllers/class.entrycontroller.php

If Garden.PrivateCommunity is enabled, hides whether a username or email exists when a user logs in.
Closes https://github.com/vanilla/vanilla/issues/5055

Add fuzzy error message to bad logins in private communities

---

library/core/functions.general.php
tests/Library/Core/DataSetTest.php
tests/Library/Core/JsonFilterTest.php

RFC3339 is basically the same as “c”, but I’ve seen it as a more common
choice elsewhere.

Update jsonFilter() date format to RFC3339

---

themes/bittersweet/design/custom.css

I am removing the URL scheme in the css to allow flexibility when forum is ran in an HTTPS mode

Remove URL scheme from css

---

library/Garden/Web/Data.php

The JSON serialized form of `Garden\Web\Data` does not currently go through `jsonFilter`, which will properly format certain field types. This update addresses that.

Apply jsonFilter to Garden\Web\Data JSON result

---

bootstrap.php

The bootstrap was missing some interfaces and had a typo in a class name.

Fix some class references in the bootstrap

---

applications/dashboard/js/dashboard.js
applications/dashboard/js/src/modal.dashboard.js

Our `heading()` function wraps the h1 in a `.header-block` div. The modal looks for and removes the h1 element from the body to add to title. If the h1 is wrapped in a `.header-block` element, the `.header-block` element is left behind, leaving a gap in the body.
This checks whether a `.header-block` exists and removes it after it removes the title. After this, devs can freely use `heading()` to render their headings without having to worry about how it may look in a modal.

Have modals check for a header-block element for the title

---

library/database/class.database.php

This update separates configuring the `names` and `time_zone` values for the database connection. Executing them in one function call can potentially cause a fatal error on some systems.

Fix time_zone SQL bug when configuring connection on some systems

---

applications/dashboard/models/class.updatemodel.php
tests/fixtures/plugins/test-plugin/addon.json

Support addon.json files in the update model's `analyzeAddon` function. Add a test file.
You can test this PR by checking:
```
UpdateModel::analyzeAddon('tests/fixtures/plugins/test-plugin');
```
and also ensuring it works properly and fails properly with other plugins, for example:
```
UpdateModel::analyzeAddon('plugins/editor');
```
Closes: https://github.com/vanilla/vanilla/issues/5121

Support addon.json files in the update model

---

library/core/class.cache.php

The cache is meant to be an “early” object that is available before event handlers have been registered. We shouldn’t have plugins thinking they can do something to the cache during its activation.
The correct way to change cache behavior is to make a new cache driver.

Remove events from the cache

---

library/Garden/Web/Exception/HttpException.php

HHVM doesn't currently support ARRAY_FILTER_USE_KEY.

Fix HttpException::jsonSerialize() to work with HHVM

---

applications/dashboard/controllers/class.homecontroller.php
applications/dashboard/views/home/leaving.php
applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/views/vanillasettings/advanced.php
library/core/class.form.php
library/core/class.format.php
library/core/functions.general.php

* Breaks the embed code replacement into its own function `embedReplacement($url)`, and optimizes and refactors the embed code replacement.
* ~Adds a `matchesTrustedDomain($url)` function to test whether a given url matches a trusted domain in the `linksCallback` function.~
* Adds a redirect to `/leaving` to any non-trusted link if the `Garden.Format.WarnLeaving` config is set.
* Adds a `reverse` param to the toggle to handle "disable"-type config settings.
* Adds controls for the `Garden.Format.WarnLeaving` and `Garden.Format.DisableUrlEmbeds` config settings to the Advanced settings page in the dashboard.
* Adds a title to the `/leaving` page.
Bonus:
* Fixes double-urling in the SafeRedirect function.
* Fixes Wistia and Twitch embeds
Closes https://github.com/vanilla/vanilla/issues/5334

Add an optional site setting to send users to /leaving when clicking a ugc link

---

applications/dashboard/modules/class.profileoptionsmodule.php
applications/dashboard/views/modules/dropdown-navbutton.php
applications/dashboard/views/modules/profileoptions.php

Updates the ProfileOptionsModule to use the dropdown module for the profile options dropdown. Functionally, this PR adds content-specific CSS classes to dropdown menu items and provides future plugins with the ability to add items in a specific order.
Closes https://github.com/vanilla/vanilla/issues/3818

Update ProfileOptionsModule to use the dropdown module

---

library/core/functions.general.php
tests/Library/Core/GeneralFunctionsTest.php

Add the following functionality to isTrustedDomain():
- You can now pass a URL or a domain to isTrustedDomain().
- The domains in the whitelist accept schemes and glob style wildcards.
- The comparison between domains is a bit more efficient.
Note that this breaks some BC where before we accepted regexes in the
domains. IMO freeform regexes should be discouraged more and more. I’m
not sure where they have been used though.

Make isTrustedDomain() work with URLs and use urlMatch()

---

library/Garden/Web/ResourceRoute.php
tests/Library/Garden/Web/ResourceRouteTest.php
tests/fixtures/src/DiscussionsController.php

The resource router was blacklisting methods with an **isProtected** method just like the old router. This was a mistake in the old router and we shouldn’t make the same mistake again.
Now we will use a whitelist so that methods will not be accessible as an endpoint unless they meet the following criteria.
- The method is one of the basic HTTP methods or `index`.
- The method matches `<HTTP method>_name`.
The resource router will not map methods like the current router. This means that the resource router will not be used for current Vanilla controllers. The intention is that when we want to update our HTML app then we will move the controllers over one-by-one.

Make resource routes whitelist instead of blacklist

---

library/core/class.format.php

This update adds a parameter to `Gdn_Format::plainText` to allow collapsing sequential block tags into a single newline. For example, a formatted string that contains `</p></div></div>` would normally be converted to `\n\n\n\n\n\n`. This change will allow that same substring to be converted to `\n\n`.

Add ability to collapse block tags into one newline when plain text

---

library/core/class.format.php

This update alters the doc block on `Gdn_Format::plainText` to clarify the effect of the `$collapse` parameter.

Update docs on Gdn_Format::plainText

---

applications/dashboard/controllers/class.assetcontroller.php
applications/dashboard/js/dashboard.js
applications/dashboard/js/src/main.js
applications/dashboard/js/src/modal.dashboard.js
library/core/class.form.php

Removes edge case properties of dashboard modal to make the class more cohesive. Also, the 'removeSelector' functionality is better handled by `jsonTarget`.
Adds a bunch of docs.

Remove edge case properties of dashboard modal and add docs

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/modules/class.dashboardnavmodule.php
applications/dashboard/modules/class.sitenavmodule.php
applications/dashboard/views/admin.master.php

Updates the panel navigation when a plugin is enabled or disabled. 
Also: 
* Updates calls to consts in the SiteNavModule from `self::` to `static::` for late-binding to allow child classes to override. This allows the DashboardNavModule to override the default section key.
* Moves the rendering call from `handleAddonToggle()` method to the endpoint instead, so it does not have to be the last call in an endpoint that uses it.
Closes https://github.com/vanilla/vanilla/issues/4473

Update the panel navigation on enabling or disabling a plugin

---

library/Garden/EventManager.php

This method is in place to allow us to start to remove some events we don’t want anymore.

Add the EventManager::fireDeprecated() method

---

applications/dashboard/models/class.logmodel.php
applications/dashboard/views/log/edits.php
applications/dashboard/views/log/moderation.php
applications/dashboard/views/log/record.php
applications/dashboard/views/log/spam.php
applications/dashboard/views/settings/bans.php
applications/vanilla/models/class.vanillasearchmodel.php
plugins/Debugger/default.php
showpost.php
themes/default/views
viewtopic.php

dirname(__FILE__) has been used on several places, but since PHP 5.3 the identical magical constant __DIR__ is available and saves one function call.
There were some id attribute relicts in closing divs (in the log views) which I have removed, too.

Replace dirname(__FILE__) with __DIR__

---

.travis.yml
applications/conversations/models/class.conversationmessagemodel.php
applications/conversations/models/class.conversationmodel.php
applications/conversations/models/class.conversationsmodel.php
applications/dashboard/models/class.activitymodel.php
applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/models/class.commentmodel.php
applications/vanilla/models/class.discussionmodel.php
applications/vanilla/models/class.draftmodel.php
applications/vanilla/models/class.vanillamodel.php
applications/vanilla/views/vanillasettings/floodcontrol.php
library/Vanilla/CacheInterface.php
library/Vanilla/FloodControlTrait.php
library/core/caching/class.cachecacheadapter.php
library/core/caching/class.userattributecacheadapter.php
library/core/helpers/class.floodcontrolhelper.php

Fixes https://github.com/vanilla/vanilla/issues/5045
This PR adds 
- CacheInterface
- Ultimately it will inherit the SimpleCache interface from PSR
- Add a level of abstraction
- FloodControlTrait
- Receive a CacheInterface (which is either an adapter of UserAttributes or Gdn_Cache). The latter will be used to fix concurrency issues mentioned in vanilla/vanilla-patches/issues/65
- Some folders in library/core
- Namely, the helpers folder. We can put utility classes in there!

Move flood control to a trait and make the models use it

---

library/core/class.format.php

This is to support plugins tying in to Gdn_Format to do whatever they
need to do. The EventManager class’ new fireFilter() method is a good
fit for formatting stuff.
Note that Gdn_Format has now been stretched way beyond respectable in
terms of what a static class should do. We will refactor HTML
formatting at a later date though :/

Add the event manager to the Gdn_Format class

---

library/core/class.session.php

Fix https://github.com/vanilla/vanilla/issues/5407
ensureTransientKey compare the current UserID with the cookie saved UserID.
Since it is possible the the UserID is set to 0 if the user does not exist I moved the function call after the check.

Always invalidate identity if the session's user is invalid

---

library/core/class.markdownvanilla.php

Fixes https://github.com/vanilla/vanilla/issues/2445
Replace https://github.com/vanilla/htmlawed/pull/7
Here is my test post:
`````
```
This is a paragraph.
`echo 'one';
echo 'two';`
```
This is a paragraph.
`echo 'one';
echo 'two';`
-------
````
This is a paragraph.
```
echo 'one';
echo 'two';
```
````
This is a paragraph.
```
echo 'one';
echo 'two';
```
-------
````
This is a paragraph.
```echo 'one';
echo 'two';
```
````
This is a paragraph.
```echo 'one';
echo 'two';
```
`````
and the result:

Handle CodeSpan properly in MarkdowVanilla

---

library/database/class.mysqlstructure.php

Skip the alteration if the column content is larger than the new size.
This will ensure that we do not corrupt data while shrinking column size when fixing https://github.com/vanilla/vanilla/issues/5284

Add integrity check when downsizing a varchar column

---

applications/conversations/models/class.conversationmessagemodel.php
library/Vanilla/FloodControlTrait.php

As the title says.
Make sure that admins are not affected when enabling flood control for conversation messages.
The fix is already backported.

Fix the flood control check

---

applications/dashboard/models/class.userauthenticationtokenmodel.php
library/core/class.authenticator.php
plugins/Twitter/class.twitter.plugin.php

This update adds support for automatic pruning of records in the UserAuthenticationToken table. A new model has been added: `UserAuthenticationTokenModel`. This model implements `Vanilla\PrunableTrait` and calls its `prune` function whenever new records are inserted with `UserAuthenticationTokenModel::insert`.
`Gdn_Authenticator ` and the Twitter plug-in have been updated to use `UserAuthenticationTokenModel`.
Closes #5064

Support automatic pruning in UserAuthenticationToken table

---

applications/dashboard/views/settings/helper_functions.php

When an addon row is added in the dashboard, it's settings URL is passed straight through. This means it's never modified to be relevant to the current site config. If the site is hosted in a subdirectory, the subdirectory is never prepended as part of the web root.
This update wraps URLs for addon settings buttons in the `url` function to ensure links are properly adjusted.

Ensure web root is added to addon settings URL

---

applications/dashboard/models/class.logmodel.php

Fixes https://github.com/vanilla/vanilla/issues/5238
This update may make the restoration go a bit slower but it will be more accurate.
This should drop support request about counts not being properly updated when restoring a record.

Properly update categories and discussions when restoring a record

---

library/core/class.oauth2.php

There has been a protected property called `$profileRequestParams` which couldn't be set anywhere and there had been a method `setGetProfileParams()` which was setting a never used (or even declared) property `$getProfileParams`.
I assume they should be connected because then they would allow plugin authors to add additional parameters to profile requests.
I've changed their names completely to reflect the already existing `$requestAccessTokenParams` and `setRequestAccessTokenParams()` to `$requestProfileParams` and `setRequestProfileParams()` accordingly.
<hr>
The default settings view has been 'plugins/oauth2'  and in the render() call it has prefixed with 'plugins/' a second time. That prefixing in the render call
a) results to "plugins/plugins/oauth2" for default view, which is …

Fix ProfileRequest Params in Class OAuth2

---

plugins/Quotes/class.quotes.plugin.php

This line is not getting translated because the key is not correct. In the locales files (and site_core.php) the key is 
> Quote Settings
not 
> Quotes Settings
See [site_core.php](https://github.com/vanilla/locales/blob/master/tx-source/site_core.php#L1008)

Correct translation key to the one in Transifex

---

plugins/Quotes/class.quotes.plugin.php

The link to quotes settings in the profile's edit profile page was naked. I added a class so it can be targeted in CSS.
Fixes https://github.com/vanilla/vanilla/issues/5429

Add QuoteSettingsLink class to Quote Settings link

---

applications/dashboard/modules/class.dashboardnavmodule.php

This was causing a warning about array_key_exists second argument not receiving an array!

Fix default value of DashboardNav.SectionLandingPages preferences

---

applications/dashboard/views/modules/me.php

[The moderation queue is populated by logs that have the operation "moderate" and "pending"](https://github.com/vanilla/vanilla/blob/47f0a92fe8af6bb1c7fc7d1b7cc715a199ff1a37/applications/dashboard/controllers/class.logcontroller.php#L321).
Update the me module to report the correct count!
Fixes https://github.com/vanilla/vanilla/issues/5389

Fetch actual count of item that needs to be moderated

---

library/core/class.format.php

There were a number of problematic inconsistencies & overlaps with our text processing. This change set goes method-by-method and refactors these issues and makes it very clear that you will always get the same result: uniformly sanitized output.
Key issues resolved:
* Inconsistent ways of sanitizing final output, making it difficult to ascertain whether it was truly sanitized.
* Not always sanitizing as the ultimate step in HTML transformations, which is critical.
* Redundant checking of `isHTML()` and getting of the HTMLformatter. This is handled in the newer `filterHTML()`.
* Unclear documentation.
These changes should have no noticeable effects on the vast majority of user-generated content.
Removing the whitespace (`?w=1`) will help on this one since I eliminated a couple large logic …

Simplify parsing orders in formatters

---

applications/vanilla/views/discussions/popin.php
applications/vanilla/views/drafts/index.php
plugins/Quotes/class.quotes.plugin.php

This PR translates strings for when a user has no bookmarks or drafts and it handles strings that are passed through javascript by the Quotes plugin.

Add several translations, including to Quotes.

---

applications/dashboard/models/class.usermodel.php

This is a case happening more often then not post migration. When a system user gets deleted from the config but still exists in the database and a user spoofs in as system.
Fixes https://github.com/vanilla/vanilla/issues/5034

Fix creation of duplicate system user when system not set in config but exists in DB

---

applications/vanilla/models/class.discussionmodel.php

/dba/counts sets DateLastComment to 0000-00-00 00:00:00 when current value of DateLastComment is NULL and discussion has no comment.
https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.dbamodel.php#L107
Query on this line becomes the code below, which returns 0 and the case mentioned above and inserts 0000-00-00 00:00:00 into a datetime field.
```
update GDN_Discussion p
set p.DateLastComment = (
select coalesce(max(c.DateInserted), 0)
from GDN_Comment c
where p.DiscussionID = c.DiscussionID)
```
Widening the where clause of the update function fixes that problem.
Fixes https://github.com/vanilla/vanilla/issues/5405

Fixing case when /dba/counts sets discussion DateLastComment to 0

---

library/core/class.dispatcher.php

Backport to `release/2017-Q1-6` & `release/2017-Q2-2`
Needed by some custom plugins.
Gdn::dispatcher() returns Gdn_Dispatcher::BLOCK_PERMISSION for any path is the session is valid...

Expose block exceptions

---

library/core/class.emoji.php

When emoji img tags are generated, most of the config values for that emoji are passed straight through. This can be an issue if HTML special characters are included, such as < or >.
This update runs all potential emoji img attributes through `htmlspecialchars` before inserting them into the image tag.

Fix invalid markup in emoji img tags

---

library/core/class.form.php

Toggle() is used without a label in multiple places.

Allow Form->Toggle to not require a label

---

plugins/editor/js/editor.js

We currently hide the toolbar when we click on "preview" for a comment. However, if you then click on "Post Comment", the toolbar didn't show again for the next comment.

Fix toolbar staying hidden after previewing comment

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

This fixes an issue with API calls.
Backport to release/2017-Q1-6 and up.

Fix categories with custom permissions created with the API not having file uploads by default

---

library/core/class.format.php

This update adds a custom callback for code blocks in `Gdn_Format::markdown`. This custom callback passes through the text, as is, and is done to avoid doubly encoding HTML special characters. More detail can be found in the original issue.
Closes #5490

Fix double encoding of code blocks when using Markdown

---

library/Garden/Web/Cookie.php
tests/Library/Garden/Web/CookieTest.php

The Vanilla\Web\Cookie class is a utility class for handling reading
and changing cookies throughout the lifecycle of the request.
Currently, we don’t have controlled cookie management. Just a bunch of
ad-hoc calls to **$_COOKIE** and **setcookie()**. This results in
problems such as unnecessary Set-Cookie headers.
What still needs to be done:
uncover them.
When implemented this class will be shared in the container and then
any class that wants to manipulate cookies can depend on it.

Add the Cookie class

---

applications/dashboard/controllers/class.addoncachecontroller.php

This update adds logging to the `/addoncache/verify` endpoint. If the cache is determined to be outdated and the site is in debug mode, a log entry is added with the details of the scan. Since issues with the addon cache are often addon-specific or caused by improper naming on the file system, the details of this log can be beneficial in troubleshooting on a case-by-case basis.
Closes #5469

Add logging to addon cache verification

---

applications/dashboard/views/activity/popin.php
applications/dashboard/views/profile/notifications.php

We now have a more accurate translation of the string "You do not have any notifications yet." without using sprintf which was causing gender problems in some languages. This PR is to call that string instead of the old one.

Fix string to match translation for when a user has no notifications.

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

Make sure that the default value is used when nothing was posted.
- FormValue default is ''
- ForceBool convert empty strings to false

Fix form value coercion

---

library/core/class.format.php

The Html format replaces all newlines with break tags. However, tags that retain whitespace formatting, such as the `code` tag, do not need this replacement. Due to the additional handling of code blocks in `Gdn_Format::htmlFilter`, these break tags (and their newlines) are removed. This update alters the regex used to replace newlines with break tags, avoiding replacing newlines between `code` tags.
This update also adds protection for code span contents to Markdown. Previously, only code blocks were protected.

Fix code block handling in Html and Markdown formats

---

plugins/editor/class.editor.plugin.php

After this fix: https://github.com/vanilla/vanilla/pull/5497
I realized that AllowFileUploads was not working properly when creating a category normally.
The problem is that the checkbox is created and hidden.
Backport to release/2017-Q1-6

Fix AllowFileUploads value for category creation

---

library/core/class.format.php

This update moves newline replacement with break tags to come after the markup has been run through `Gdn_Format::htmlFilter` in `Gdn_Format::html`.
Please backport to [release/2017-Q1-6](https://github.com/vanilla/vanilla/tree/release/2017-Q1-6) and [release/2017-Q2-2](https://github.com/vanilla/vanilla/tree/release/2017-Q2-2)

Fix code blocks with less-than symbol in Html format posts

---

library/core/class.format.php

Some behavior was introduced in https://github.com/vanilla/vanilla/pull/5400 that fixed formatting mentions of users with underscores on either side of their name. However, moving parsing of mentions so early in the process meant that code blocks now had their contents parsed for mentions.
This update reverts the early parsing of mentions.

Fix mentions being parsed in code blocks with Markdown

---

applications/dashboard/js/jquery.fluidfixed.js

The init function for the jquery.fluidfixed plugin didn't take into consideration the window height.
Fixes: https://github.com/vanilla/vanilla/issues/4868

Dashboard - Fix init logic for having a “fixed” panel

---

applications/vanilla/modules/class.promotedcontentmodule.php

PromotedContent isn't working so great under 7.1 due to this conflating of variable types.

Fix array push onto a string

---

applications/dashboard/views/modules/media-callout.php

The "Current Theme" slot uses `htmlspecialchars()` to wrap the theme's title. The theme options below do not, nor does the theme descriptions. This isn't a relevant security vector, and there are valid reasons for wanting HTML entities in your theme name. Also, this was surreptitiously added in Dashboard v3 - it did not do this previously. Therefore, this use is inconsistent and unnecessary.

Remove HTML entity escaping from current theme title

---

library/core/class.request.php

I’m hoping to get thoughts on this so let me explain. This PR is to help CORS requests avoid preflights. In order to avoid a preflight (among other things) the content type must be one of the following:
- application/x-www-form-urlencoded
- multipart/form-data
- text/plain
We know we’d have to transmit JSON as text/plain. The question is whether or not to force a querystring parameter for its content type. My thinking is we can treat text/plain as JSON and force an actual text/plain post to use a different content type or a querystring parameter. This would save us the hassle of seeing application/json in every single cross-domain querystring.

Interpret plain text as JSON

---

applications/vanilla/views/categories/subtree.php
applications/vanilla/views/discussions/index.php

This deprecated notice was added with the best of intentions, but I'm removing it because it's not OK to force Vanilla into throwing unavoidable Notices. I downgrade it to a docblock here and document its use elsewhere (which is what triggered the notice).
Forcing notices trains developers to ignore them.

Fix docs around deprecated subtree view & remove notice

---

library/core/class.pluginmanager.php

Make sure that nothing is returned if $PluginInfo is not defined in the plugin's class.
Test $PluginInfo properly in indexSearchPath

Fix plugin scanning logic

---

library/Garden/EventManager.php
tests/Library/Garden/EventManagerTest.php

I'm not super familiar with this area, but going by what _appears_ to be the intent of these checks and the notices I'm receiving when scanning the database for updates, I believe this fixes the method to check variable types correctly.

Repair logic in the unbindClass() method

---

applications/vanilla/controllers/class.postcontroller.php

Missing `$Context` caused a notice on `/post/discussion` submission and 2 others were suffering a similar issue. Also removed an `else` block made redundant by declaring the properties.

Fix undeclared properties in PostController

---

applications/dashboard/js/jquery.fluidfixed.js

When expanding the panel and the panel being longer than the screen, the plugin correctly detected "case 1", but also triggered "case 2". Only one case is valid at a time.
Fixes: https://github.com/vanilla/vanilla/issues/5426

Dashboard - Fixed bug for fluid fixed panel

---

applications/dashboard/js/activity.js
applications/vanilla/js/discussions.js

- Made the selector more precise for the discussion's pager.
- Removed activity's pager code since it was unused. [The code was old](https://github.com/vanilla/vanilla/blame/ee1f67687653a82632b1f2b0dbc86571910a9398/applications/dashboard/js/activity.js#L164) and we are now using a Next, Previous pager for that section.
Fixes https://github.com/vanilla/vanilla/issues/5062

Fix profile/discussions pagination double query 

---

js/embed_local.js

This fix is what https://github.com/vanilla/vanilla/pull/4277 should have been.
Closes https://github.com/vanilla/vanilla/issues/5209 and addresses https://github.com/vanilla/vanilla/issues/4185 properly.

Scroll to top of embed's iframe only for discussions and on page change

---

plugins/Facebook/class.facebook.plugin.php

Closes https://github.com/vanilla/vanilla/issues/5458 and closes https://github.com/vanilla/docs/issues/49
We [removed the automatic sharing feature](https://github.com/vanilla/vanilla/pull/5371) and the publish_actions is not needed by the Share Dialog.
To make sure that everything work, I created an app, made it public, made a coworker login in my forum with their facebook account and share something on their facebook feed.

Do not request publish_actions in facebook plugin

---

.gitignore
tests/APIv0/APIv0.php
tests/APIv0/AltTest.php
tests/TestInstallModel.php

This update primarily does two things:
1. Adds the ability to define a database host. Currently, the database is hardcoded to "localhost". The value still defaults to "localhost", but can be overridden with a "dbhost" environment variable.
1. Adds "phpunit.xml" to the repo's `.gitignore` file. Without explicitly defining a config with the `--configuration` parameter, PHPUnit will attempt to use one of two files: phpunit.xml or phpunit.xml.dist, in that order. Vanilla already comes with a phpunit.xml.dist, so now developers can use their own phpunit.xml.
@DaazKu pointed out an issue in `TestInstallModel::__construct` wherein the `baseUrl` property could be set too early and lead to a config with an invalid name being created (".php"). This was due to `getConfigPath` being called before …

Improve customizability of the PHPUnit testing environment

---

applications/dashboard/modules/class.headmodule.php

`HeadModule::setMobileAddressBarColor` has an unused parameter: `$iosAddressBarColor`. This update removes it.

Fix notice when calling HeadModule::setMobileAddressBarColor

---

applications/dashboard/modules/class.userbanmodule.php

When subcommunities are turned on, the link to the banned reasons had the subcommunity uri twice in the address.

Fix find-ban URL on profile page when user has been banned by a rule

---

applications/dashboard/controllers/class.entrycontroller.php

Presently, when we instantiate a session for a user who has connected over SSO we default the "Remember Me" to true, thus giving the cookie an expiry date. Some forums would like for their users to be logged out as soon as they close the browser. This PR will allow that behaviour to be controlled by the config file.

Make the “Remember Me” setting configurable for SSO connections.

---

applications/dashboard/controllers/class.entrycontroller.php

https://github.com/vanilla/vanilla/pull/5586
Backport 5586 to release/2017-Q2-2
Currently when you connect over SSO we hard code the user's session as if he had signed in and clicked "Remember Me" giving him a cookie with an expiration date. This PR will allow us to configure a site so that when users connect they are given a cookie that expires with the browser session.

Allow admins to not set "Remember Me" by default over SSO

---

library/Vanilla/Addon.php
library/core/class.applicationmanager.php

Fixes https://github.com/vanilla/vanilla/issues/5598
In PermissionModel->getAllowedPermissionNamespaces() we were stripping all applications permissions because the applications index were set to `key` (or `keyRaw`) which are all lowercased instead of `name` which looks like this: `Dashboard`

Properly set addons info fields 'Index'(old info) and 'rawKey'(new info)

---

applications/dashboard/controllers/class.profilecontroller.php

If you did:
- Go to full site
- Go back to mobile
you ended up with the mobile site appearing over the full site because `redirect()` was used instead of `$this->RedirectUrl`

Fix nomobile logic

---

applications/dashboard/library/class.nestedcollectionadapter.php
applications/dashboard/modules/class.navmodule.php
applications/dashboard/modules/class.profileoptionsmodule.php
applications/dashboard/views/settings/helper_functions.php
applications/vanilla/views/discussion/helper_functions.php

`slugify()` does not work with non ascii characters.
Also... keys are used as index in php arrays there is no need to `slugify()` them.
Fixes https://github.com/vanilla/vanilla/issues/5212

Fix non-ascii items not being added to menus

---

.gitattributes

This prevents them from showing up in merge conflict editors. They can
just be rebuilt when they conflict.

Mark built files as binary

---

applications/dashboard/settings/class.hooks.php

Allowing access tokens in the URL is something we allow for the APIv2 and is consistent with [RFC6750](https://tools.ietf.org/html/rfc6750#section-2.3). It’s not necessarily a best practice, but will help us on two occasions:
1. Some clients won’t be able to set a custom header.
2. An authorization header incurs a CORS preflight request which should be avoided if possible.

Allow access tokens in the querystring

---

js/library/jquery.tokeninput.js

My previous patch (https://github.com/vanilla/vanilla/pull/5478) for token inputs in popups didn't work. Here's a better fix.

Fix z-index for token input in modals

---

library/core/class.session.php

This update adds some additional checks around the call to `Gdn_Session::ensureTransientKey` in `Gdn_Session::start`. One of two conditions must be met:
1. The `$SetIdentity` parameter must be truthy. This parameter is used to save the user's identity. For example, the `Gdn_CookieIdentity` class saves a user's data to browser cookies, depending on this value. It's `false` for API calls. When a user first signs in on the frontend, this value will be `true`. However, it will be `false` for page loads after a user has successfully signed in. Which brings us to...
1. The `$UserID` parameter must be `false`. On the frontend, after a user signs into the site, [subsequent page loads will have this parameter set to `false`](https://github.com/vanilla/vanilla/blob/6653443cc3c4d451c6c9e55d7ebb801514 …

Fix TK cookie being unnecessarily set

---

library/core/functions.general.php

The `setAppCookie` function has the cookie path hardcoded to "/". It should be using the site's configured `Garden.Cookie.Path` value. This update should make it do just that.
Closes #5565 
Backport to [release/2017-Q1-6](https://github.com/vanilla/vanilla/tree/release/2017-Q1-6) and [release/2017-Q2-2](https://github.com/vanilla/vanilla/tree/release/2017-Q2-2).

Fix setAppCookie not isolating cookies between subdirectory sites

---

applications/vanilla/controllers/class.postcontroller.php

Embedded comments on a site configured to use Wysiwyg as its post type requires some special considerations in Vanilla. https://github.com/vanilla/vanilla/pull/3275 and https://github.com/vanilla/vanilla/pull/3464 introduced behaviors attempting to fix it. However, there is a lingering issue: commenting on a site configured with Wysiwyg as its input formatter and *allowing* embeds can potentially add unnecessary break tags. These break tags used to add double spacing, but recent updates to Vanilla's formatting chain cause these tags to be encoded and rendered as text.
Vanilla should only be attempting to modify post contents like this if the content is coming from an embedded comment form, so this update just adds that condition. Embedded comments on sites with Wysiwyg configured as its …

Fix double spacing in Wysiwyg posts when embedding allowed

---

applications/vanilla/js/manage-categories.js
applications/vanilla/models/class.categorymodel.php
library/core/functions.validation.php

This update does a few things to improve category slug management:
1. Adds a `validateCategoryUrlCode` function for...validating a category's URL code. This function verifies the slug doesn't contain spaces, isn't numeric and is not a reserved word.
1. Implements `validateCategoryUrlCode` as part of the `CategoryModel::save` validation routine.
1. Updates the JavaScript responsible for auto-generating category slugs to avoid generating purely numeric values.
Closes #5127

Fix category management allowing invalid URL codes

---

applications/vanilla/library/class.categorycollection.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/modules/class.categoriesmodule.php

- Allow the categories module to provide a collapseCategories property
that specifies whether category categories are displayed.
- All the categories module to provide a root category.
- Use the CategoryCollection to filter category categories rather than
the redundant filterChildren() method.
Fixes #5585.

Give more control over the category tree in the categories module

---

plugins/editor/js/editor.js

In IE, when adding a "block' element such as a quote, code block or spoiler, we added an empty paragraph at the bottom so you could continue writing under it. However, in IE, the focus went to the new paragraph, not the block we created. Luckily there's a "bookmark" feature in the wysiwyg plugin to save the cursor position. 
I've also noticed that in IE, if you click on the caret of a dropdown menu, it did not open. I've made the JS a bit more robust by using a ".closest()" call, instead of a ".parent()" to get the button.
Fixes: https://github.com/vanilla/vanilla/issues/5214

Wysiwyg IE bug fixes

---

plugins/Twitter/class.twitter.plugin.php

Fixing this issue by checking if provider already exists, this is done simply by adding the true parameter to the replace structure function of the plugin.

Prevent the twitter provider update to keep showing up in /utility/structure

---

applications/vanilla/controllers/class.moderationcontroller.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/models/class.discussionmodel.php

This update adds some additional checks and updates to the routines involved in moving and deleting discussions to ensure the last post/category fields on a category are updated, in addition to their parent aggregate counts.
Closes #5236

Fix a category's latest post not being updated when moving or deleting a discussion

---

applications/dashboard/controllers/class.settingscontroller.php

Fixes problem where in dashboard/settings/registration upon changing the time when the invitation will expire and saving we get the "Your changes have been saved" message but the page still shows the previous value in the "Invitations will expire" select box until we refresh the page one more time manually.
We were fetching that value from the config before it was updated. Setting $this->InviteExpiration to the postback value will have the view build correctly after the form submission.

Fix registration invitations expire time 

---

library/database/class.sqldriver.php

We use inner selects to greatly optimize queries. Usually we employ pure hacks to do so, but it would be better to move towards support for some common scenarios. This PR adds the following functionality:
- When joining a table check to see if it starts with a bracket, indicating that we shouldn’t search for an alias.
- Add GDN_SQLDriver->mergeParameters to allow an inner select to merge its parameters into the outer select.

Add better support for inner select queries

---

library/core/functions.general.php
phpunit.xml.dist
tests/APIv0/APIv0.php
tests/APIv0/AltTest.php
tests/APIv0/BaseTest.php
tests/APIv2/InstallTest.php
tests/Library/Core/ArrayFunctionsTest.php
tests/Library/Core/ControllerTest.php
tests/Library/Core/DataSetTest.php
tests/Library/Core/DateTimeTest.php
tests/Library/Core/DbEncodeDecodeTest.php
tests/Library/Core/FactoryTest.php
tests/Library/Core/FormTest.php
tests/Library/Core/GeneralFunctionsTest.php
tests/Library/Core/JsonFilterTest.php
tests/Library/Core/PasswordTest.php
tests/Library/Core/PluginManagerTest.php
tests/Library/Core/RenderFunctionsTest.php
tests/Library/Core/RequestTest.php
tests/Library/Garden/ClassLocatorTest.php
tests/Library/Garden/EventManagerTest.php
tests/Library/Garden/Web/CookieTest.php
tests/Library/Garden/Web/ResourceRouteTest.php
tests/Library/Vanilla/AddonManagerTest.php
tests/Library/Vanilla/CheckVersionTest.php
tests/Library/Vanilla/PermissionsTest.php
tests/TestInstallModel.php

- Update environment variables to respect naming convention
- Use PHPUnit namespace
- Fix some unit tests that did not have any assertions
- Update jsonEncodeChecked so that it fails properly when needed
Better version of https://github.com/vanilla/vanilla/pull/5495

Refactor unit tests

---

library/core/class.format.php
plugins/HtmLawed/class.htmlawed.plugin.php

This update moves to generate the htmLawed `$spec` param as an array. Currently, this parameter is a single giant string. In htmLawed, it's eventually passed through to `hl_spec`, which transforms it into an array. This workflow presents two issues:
1. It makes it difficult for anything to modify the standard htmLawed spec.
1. `hl_spec` does its job, but can lead to unexpected results. For instance, if you specify the same element in more than one rule, only the first is kept. A dev would most likely expect these items to be merged into multiple rules for the element.
An `$options` parameter has been introduced to `Gdn_Format::htmlFilter` that will be passed through to the `format` method of the site's HtmlFormatter (this is probably always going to be the htmLawed plug-in). The htmLawed …

Generate htmLawed spec array in plug-in

---

js/embed.js
js/embed_local.js

Fixes https://github.com/vanilla/vanilla/issues/5600
Properly fix https://github.com/vanilla/vanilla/issues/4185
The scrolling behaviour was already coded to work properly.
As suggested in https://github.com/vanilla/vanilla/issues/5600 the proper solution is to scroll to the top the the frame if the parent window is lower than the top of the frame when the page unload (AKA we change pages inside the iframe). The existing solution even disregard scrolling if the parent window is higher than the frame's top which is even better.
The source of the problem was that the unload `event` was never parsed due to `event.source` being `undefined`. I fixed the code and now the scrolling behaviour works properly.
I also removed the scrollto on link click.

Fix embed scrolling

---

applications/dashboard/modules/class.navmodule.php

https://github.com/vanilla/vanilla/pull/5574 introduced some slug/key/grouping improvements. However, its updated method of translating text to keys doesn't work well on its own in areas where markup may be used as part of the text. An example of this is the profile menu options. If a plug-in adds a menu link to the profile page's user menu and it passes markup as part of the title text of that link, it mangles the link. This update adds a `strip_tags` call to the text in `NavModule::textToKey`.
Please backport to [release/2017-Q2-4](https://github.com/vanilla/vanilla/tree/release/2017-Q2-4)

Fix broken user menu links on profile pages

---

plugins/HtmLawed/class.htmlawed.plugin.php

`HtmLawedPlugin::spec` wasn't verifying an array element existed under a specific key before attempting to determine if its value was an array. It still worked, but it had the potential for throwing PHP notices.
This update adds a call to `array_key_exists`, before attempting to verify the value under the key is an array. If either fails, an empty array is set under the specified key.

Fix notice in HtmLawedPlugin::spec

---

.travis.yml
library/Vanilla/Models/AddonModel.php
library/core/class.gdn.php
library/core/class.pluginmanager.php
phpunit.xml.dist
tests/APIv0/APIv0.php
tests/APIv0/AltTest.php
tests/APIv0/SmokeTest.php
tests/Bootstrap.php
tests/Library/Vanilla/AddonManagerTest.php
tests/Models/AccessTokenModelTest.php
tests/Models/InstallModelTest.php
tests/SiteTestTrait.php
tests/TestInstallModel.php
tests/phpunit.php

- Add a bootstrap class to allow container re-initialization.
- Add a SiteTestTrait that allows test classes to install a copy of Vanilla and run internally.
- Move the AccessTokenModelTest out of the APIv2 tests.
- Don't save configurations during unit tests. This is more to work around an issue where the configuration object can only save on destruct which isn't appropriate for unit tests and causes some timing issues too.
Basically, these changes will allow us to move closer to isolating tests against separate installs of Vanilla where a test class can install its own copy of Vanilla without using cURL. This PR started out as a simple cherry pick from the apiv2 branch, but ended up including a lot of yak shaving in order to make builds work on Travis.
*Note to reviewers: The changes to …

Tweak unit tests

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

The toggle for the `Garden.Format.DisableUrlEmbeds` config under Posting Settings in the dashboard is reversed. Instead of "disabling URL embedding", the toggle is for "Enable link embeds in discussions and comments". The UI handles this value inversion, but it's not accounted for during the form's saving routine. This means you can toggle the control on, thinking you're allowing URL embeds, but you're actually setting the `DisableUrlEmbeds` to true and disabling them. The next time you looked at the form, the value would be reversed in the UI, so it wouldn't look like your change had been saved.
This update leaves the UI the way it is, along with existing UI translations, and instead opts to instead introduce the minor correction of the data before it is saved.
Closes #5605

Fix inaccurate toggle for embedding URLs in Posting Settings

---

js/vanilla.embed.js

Fixes https://github.com/vanilla/vanilla/issues/5634
I added a function that calculate the correct offset from the document.
Backport to 2.3, 2.4, 2017-Q1-6, 2017-Q2-4

Fix advanced embed scrolling to top of the page instead of top of the iframe

---

applications/dashboard/views/entry/signin.php
js/global.js

This fixes an issue with embedding where the iframe would be down the page and the page would scroll down to the embed's email field.
Fixes https://github.com/vanilla/vanilla/issues/5597

Disable autoscroll on an embedded signin page

---

applications/vanilla/models/class.draftmodel.php

The `Draft` table's `CategoryID` column is optional. It is a nullable integer field. The current behavior when saving a draft without a category is to grab the first category in the `Category` table and use that for the draft. It's seemingly been like that since Vanilla has been under version control. When you edit such a draft, the Root category (and all its children) can appear in the dropdown.
This update stops guessing at the category ID for a draft. It also removes non-integer values for `CategoryID` during `DraftModel::save`. If an empty string is passed through to this method (as can happen when drafts are auto-saved), it's removed from the `$formPostValues` array.
Please backport to [release/2017-Q1-6](https://github.com/vanilla/vanilla/tree/release/2017-Q1-6) and …

Fix drafts being assigned to the Root category by default

---

library/core/class.bbcode.php

Current BBCode formatting [only uses `pre` tags](https://github.com/vanilla/vanilla/blob/b7a6fafdd821dee3bcab14f0de404856a9897d72/library/core/class.bbcode.php#L389) for code blocks. However, Vanilla's magic parsing only dodges formatting [based on the `code` tag](https://github.com/vanilla/vanilla/blob/b7a6fafdd821dee3bcab14f0de404856a9897d72/library/core/class.format.php#L1869). This causes Vanilla's magic parsing to happen in BBCode's code blocks, where it shouldn't be.
This update alters the BBCode code block template to use `code` tags, in addition to `pre` tags. This is similar to [the structure used by Vanilla's Markdown library](https://github.com/michelf/php-markdown/blob/1f51cc520948f66cd2af8cbc45a5ee175e774220/Michelf/Markdown.php#L1223).
Please backport to …

Fix magic Vanilla formatting in BBCode code tags

---

library/core/class.oauth2.php

Some implementations of Oauth2 may want to issue a refresh token that can then be used to get a new access token when the access token is expired. In this PR the OAuth2 class has been changed to save a refresh token to the users attributes if one is passed and when getting the AccessToken OAuth2 will:
- check if the access token is present, if not
- if no refresh token is saved in Gdn_User Attributes it will use the access_token saved there.
- if there is a refresh token saved in Gdn_User Attributes it will request a new access_token from the provider and save the new a refresh token to Gdn_User Attributes.

Add support for refresh tokens in OAuth2

---

applications/dashboard/controllers/class.usercontroller.php

Fixes https://github.com/vanilla/vanilla/issues/5270
When save fails, verifying if there is a username to restore because we unset the form value on different cases to prevent it from being validated and saved when there is no need to.

Fix username disappearing from the dashboard user edit form on failed submission  

---

applications/dashboard/models/class.usermodel.php

We were not validating the timestamp.
Refer to http://docs.vanillaforums.com/help/sso/jsconnect/embed/ for testing.
`jsSSOString()` from functions.jsconnect.php
Backport to 2.3, 2.4, 2017-Q1-6, 2017-Q2-4

Validate SSO timestamp

---

plugins/VanillaStats/class.vanillastats.plugin.php
plugins/VanillaStats/js/vanillastats.js
plugins/VanillaStats/views/dashboardsummaries.php

On large sites the generation the dashboardsummaries should go from 15-30secs to under a second.
Fixes https://github.com/vanilla/vanillastatsapp/issues/8
`/utility/update` needs to be ran for the indexes to be created!
I was told to make the indexes approved by @tburry

Improve load time of Vanilla Statistics dashboard summaries

---

plugins/HtmLawed/class.htmlawed.plugin.php

Backport to 2.3, 2.4, release/2017-Q1-6, release/2017-Q2-4
I reordered the tags. The only thing I added was `-link`
This affects any formatter that allow some html (WYSIWYG, Markdown, Simple HTML...)

Filter out <link> tags from user posts

---

library/core/class.format.php

Links with no scheme were not matched which resulted in `Garden.Format.WarnLeaving = true` not working with `<a href="//google.com">google.com</a>`
Backport to `release/2017-Q1-6`, `release/2017-Q2-4`
You can do a test Before VS After with (Format Simple HTML)
```
<a href="http://google.com">google.com</a> Parsed
<a href="//google.com">google.com</a> Parsed
http://google.com Parsed
//google.com Not Parsed
//blablabla Not Parsed
http://blabla Parsed 
http://smalldata.io/startup/common-files/icons/sdl_logo.png Parsed
//smalldata.io/startup/common-files/icons/sdl_logo.png Not Parsed
```

Fix external links with relative protocol not always receiving the leaving warning when expected

---

library/Vanilla/AddonManager.php

When addons use duplicate directories or keys, there's currently not a lot of feedback to go on for the errors that arise.
This update adds some exception throwing to two key areas when addons are scanned. If a duplicately-named addon directory is encountered, an exception is thrown indicating which addon is causing the issue. If a duplicate addon key is encountered, a similar exception is thrown and the error is logged to the database. The directory scan doesn't include logging, because it's done before addons are loaded and hence we cannot count on a logger being available. The addon key scanning is run on addon pages during cache checks, so there's an increased likeliness a logger will be available.
We're moving in a directory where an addon is an addon is an addon. Themes, plugins and …

Improve feedback when a duplicate addon key is encountered

---

environment.php

Reverts use of `__DIR__` to `getcwd()` in setting our `PATH_ROOT`. 
Using `__DIR__` adds the benefit of caching its value, but removes the ability to use symlinks for much of Vanilla. Since we currently have no plan or strategy to accommodate complex localhost setups (e.g. "How do you then symlink 50 plugins into 50 localhost sites?"), this tradeoff was very bad. It also creates a bunch of communication overhead for the open source release that we had no plan for.
Relevant discussion was previously here: https://github.com/vanilla/vanilla/pull/5492#pullrequestreview-36433978

Fix path detection in environment setup to work with symlinks again

---

applications/dashboard/controllers/class.settingscontroller.php
library/core/class.pluginmanager.php

When you enable a plugin with dependencies, they're silently enabled. The user doesn't see any feedback in the UI: no toaster message, no "enabled" indicator. You have to refresh the page to see they're enabled.
This update does a couple things:
1. Alters the return type of `Gdn_PluginManager::enabledPlugin` from strictly a boolean to either a boolean or an array. The addition of the array type allows us to include additional information to the result of when a plug-in is enabled, such as including what requirements may've also been enabled.
1. Indicates via a toaster popup and UI element updates when a required addon has been auto-enabled.
Closes #5087 
Please backport to [release/2017-Q1-6](https://github.com/vanilla/vanilla/tree/release/2017-Q1-6) and …

Improve feedback when required addons are enabled

---

.gitignore
.htaccess.dist
build/.htaccess
cache/.htaccess
conf/.htaccess
index.php

- Disallow directories that do not need to be exposed by the webserver
- Prevent any script but /index.php from being called by default.
- Clean up existing rules
- Remove deprecated 
Fixes https://github.com/vanilla/vanilla/issues/3431

.htaccess hardening

---

plugins/HtmLawed/class.htmlawed.plugin.php

If "Enable link embeds in discussions and comments" is toggled off under "Posting Settings" in the dashboard, users can still use `audio` and `video` tags in HTML-format posts to embed media content. This update adds support for excluding these tags via htmLawed if `Garden.Format.DisableUrlEmbeds` is enabled.
Example post (make sure its `Format` is set to "Html" or another HTML-compatible format):
```html
<em>Hello</em> <b>world</b>. <u>This is an HTML test</u>.
<video width="400" controls>
<source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
<source src="https://www.w3schools.com/html/mov_bbb.ogg" type="video/ogg">
</video>
<audio controls>
<source src="https://www.w3schools.com/html/horse.ogg" type="audio/ogg">
<source src="https://www.w3schools.com/html/horse.mp3" …
```

Fix HTML 5 media embeds being allowed when URL embeds are disabled

---

applications/vanilla/models/class.categorymodel.php
applications/vanilla/modules/class.categorymoderatorsmodule.php
applications/vanilla/views/modules/categorymoderators.php

This update refactors the `CategoryModeratorsModule` in the following ways:
1. Add code documentation
1. Update coding standards
1. Use the `Data` array in the module, instead of a dynamically-declared property
1. Update the constructor signature to match the parent class
1. Add a auto-fetching of moderator data for the current category
In addition, the signature of`CategoryModel::joinModerators` has been updated to properly pass its `$Data` parameter by reference.

Refactor CategoryModeratorsModule

---

applications/dashboard/views/profile/preferences.php
applications/vanilla/views/vanillasettings/notificationpreferences.php

First I've changed some `<td>` elements to semantically correct `<th>` elements.
Furthermore I have added `scope` and `headers` attributes to the `th` and `td` elements like @chrisvanpatten suggested [here](https://github.com/vanilla/vanilla/pull/5654). 
If someone has the possibility to test it, I've pasted the table to [codepen](https://codepen.io/anon/pen/qjbMeP)
I'm not sure if the scope in line 25 and 27 of the codepen must be col or colgroup. See [here](https://www.w3schools.com/tags/att_th_scope.asp) for some more info

Extend notification preference table with accessibility attributes

---

applications/conversations/models/class.conversationmodel.php

There is a bug where if you have over 20 recipient and you try to add the 21st again on the conversation it will throw an exception due to the database rejecting the insert query because of the unique constraint on (ConversationID, UserID).
The default limit of getRecipients is 20 so I'm upping the query to 1000 since conversation are not meant to be thread of discussion.

Fix recipient being added a second time to the same conversation

---

library/Vanilla/AddonManager.php

Fixes https://github.com/vanilla/vanilla/issues/5544
Improve AddonManager's readability by encapsulating `$this->cacheDir` comparisons (!empty, !== null, ...) in a function.

Add AddonManager->isCacheEnabled()

---

applications/vanilla/controllers/class.discussioncontroller.php

Fixes getnew() to work with the newer comments.php view, which doesn't expect data's `Comments` to be an array. Pretty sure I'm the only person in existence using this endpoint.

Fix 'getnew' endpoint

---

plugins/Quotes/class.quotes.plugin.php
plugins/Quotes/js/quotes.js

We had untranslated translation strings that we recently added to locales. When adding them we decided that that we should remove some html special chars that were in them to keep the keys clean. This PR removes `&raquo;` and `&laquo;` from strings in locales and in gdn.meta as well.

Remove html from translation keys in quotes plugin

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/views/settings/banstable.php

The ban filters were including admin and mods when we were clicking on the Users' count.
The add Ban Rule button was opening 3 modals dialog because SettingsController->findBanRule was calling render without calling `Gdn_Theme::section('Moderation')` which made the master template render the admin template.
The calling function `bans` is already rendering the correct view so I removed the calls to render in findBanRule.
You have to go on /en/settings/bans/find/ to reproduce this issue.

Fix ban filter including admins and mods

---

plugins/Flagging/class.flagging.plugin.php

The plugin tries to a) add admin.css which is included anyway in the dashboard and b) add flagging.css which has been removed since it wasn't used.
The way that this plugin was add css files wasn't working since release 2.2
This closes https://github.com/vanilla/vanilla/issues/3015

Remove addCssFile calls referencing non existent or superfluous files

---

applications/dashboard/models/class.usermodel.php

Vanilla replaces deleted users mail address with a placeholder: `user_XY@deleted.email`. Since ".email" became a valid TLD, that isn't an invalid mail address any more.
[RFC 2606](https://tools.ietf.org/html/rfc2606) specifies a better TLD for that: ".invalid". Using this TLD leaves no doubt that the mail address itself is invalid although the format isvalid.

Replace deleted users mail placeholder

---

library/Vanilla/Addon.php
library/core/class.applicationmanager.php

Fixes https://github.com/vanilla/vanilla/issues/5642
Depends on https://github.com/vanilla/vanilla-cli/pull/6
While converting from $ApplicationInfo to addon.json I tried to [get rid of some kludges](https://github.com/vanilla/vanilla-cli/pull/1/files#diff-96b428404a3aef197827541a95fb71c9R61).
The problem with this is that by getting rid of keyRaw (which is used to set the 'Index' field in calcOldInfoArray which is in turn used in the ApplicationManager) in addon.json and putting the kludge in the codebase we made the wrong assumption that $ApplicationInfo[INDEX] was === to $addon['name].
As you can see from the old Conversation [about.php](https://github.com/vanilla/vanilla/blob/6ed8a7bbd9fb31ea174271a61a3d71394d8a23bb/applications/conversations/settings/about.php) the index is the name …

Properly set keyRaw for applications if not defined

---

applications/conversations/models/class.conversationmodel.php

That event allows taking influence on the users which should be added. Needful for plugins like "Ignore" which should disallow users to contact ignoring users.
That new event would be a requirement to handle https://github.com/vanilla/addons/issues/510
I have chosen the EventArguments name "UserID**s**" on purpose: although the addUserToConversation method takes an integer "UserID" based on its documentation, that integer is transformed to an array and this array is used in a foreach loop. Using "UserID" as a name would be misleading.
Maybe that variable name should be changed to UserIDs anyway.

Add new beforeAddUser event to ConversationModel->addUserToConversation

---

plugins/ProfileExtender/class.profileextender.plugin.php

https://github.com/vanilla/vanilla/pull/5703/commits/3852f8282736764460b31c76fb8be2e1efeea5a2 missed updating a couple calls to `Gdn_Controller::redirectTo`. This update (hopefully) corrects the last of them.

Fix broken calls to Gdn_Controller::redirectTo

---

applications/dashboard/models/class.dbamodel.php
applications/vanilla/models/class.discussionmodel.php
applications/vanilla/settings/class.hooks.php

The DBA counts page has a couple issues:
1. There is a "Tag.Tag" job. This job tries to update the counts in the "Tag" column of the "Tag" table. This column doesn't exist, so the job errors out. It's due to a misconfigured count job in Vanilla's countJobs hook.
1. The "Discussion.DateLastComment" job can throw an error stating 0 is an invalid value for a `DATETIME` field. This is caused by its usage of `DBAModel::getCountSQL`, which has a hardcoded default of zero. While the function is named `getCountSQL`, [it actually serves as a way to get several aggregate values (min, max and sum)](https://github.com/vanilla/vanilla/commit/9d23700975984b8ce2844beb09199ab35fefd708#diff-7f22adbbfe67749b245f5ac0a5acc443R62), in addition to counts. Forcing zero as the default may not be compatible with …

Fix Tag.Tag and Discussion.DateLastComment errors on DBA count jobs

---

applications/vanilla/models/class.categorymodel.php

We undid an undocumented kludge in https://github.com/vanilla/vanilla/pull/5701
Reverting the kludge does not break https://github.com/vanilla/multisite/pull/133
Changing the URL from being absolute to relative causes some problem since that value is accessible from the API.
Edit:
calculate() sets the URL as relative because the routing process needs the value to be.
calculateUser() then rewrites the URL as absolute to fix that. These kind of kludge should be explained in the code. The comment I made should at least help understand the why a bit more.

Add back category URL kludge in calculateUser

---

library/core/class.smarty.php

`categoryUrl`, `discussionUrl`, `userUrl`, and `commentUrl` should all be allowed for use in Smarty. This PR adds them to list of allowed functions.
Needs backport to `release/2017-Q2-6`

Allow URL functions in smarty

---

library/Vanilla/Addon.php

Fixes https://github.com/vanilla/vanilla/issues/5718
This report a more accurate error if you have a syntax error in the addon.json file.
Having an extra comma in the file would throw "The addon at $subdir doesn't have any info." which is not useful at all :)

Addon: Differentiate between unreadable file and invalid JSON format

---

applications/conversations/controllers/class.messagescontroller.php
applications/conversations/modules/class.addpeoplemodule.php
applications/dashboard/controllers/class.activitycontroller.php
applications/dashboard/controllers/class.addoncachecontroller.php
applications/dashboard/controllers/class.entrycontroller.php
applications/dashboard/controllers/class.profilecontroller.php
applications/dashboard/controllers/class.rolecontroller.php
applications/dashboard/controllers/class.routescontroller.php
applications/dashboard/controllers/class.usercontroller.php
applications/dashboard/settings/class.hooks.php
applications/vanilla/controllers/class.discussioncontroller.php
applications/vanilla/controllers/class.moderationcontroller.php
applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/controllers/class.vanillasettingscontroller.php
plugins/ProfileExtender/class.profileextender.plugin.php
plugins/SplitMerge/class.splitmerge.plugin.php

Partially addresses https://github.com/vanilla/vanilla/issues/5218
We [consolidated all redirect functions into redirectTo](https://github.com/vanilla/vanilla/issues/5218#issuecomment-310513372) in order to have a "safe by default" redirect function.
This PR removes `$trustedOnly = false` to all redirections where it should be safe to do so.
Redirects updated to have `$trustedOnly = true`:
- Any relative `$destination`.
- Any `$destination` coming from Target that are not part of SSO redirects.
Backport to 2.4 (all pr depending on this one too)

Update setRedirectTo calls to use the $trustedOnly option where necessary

---

library/Vanilla/Addon.php

This is to help developers find addons that need fixing.

Add the addon’s proper path to deprecated locale notice

---

applications/dashboard/models/class.userauthenticationnoncemodel.php
applications/dashboard/settings/structure.php

Every page load with jsConnect generate a nonce.
The table need an index since we prune the table on every insert.

Index UserAuthenticationProvider Timestamp and purge nonce after 45 minutes

---

library/Vanilla/AddonManager.php

Fixes https://github.com/vanilla/vanilla-patches/issues/103
An error was introduced in lookupAllByType by all the refactoring/updates we did in the AddonManager.
The function was not returning addons by keys when they were not using multicaching.
I also got rid of the $key variable from Single addons functions since the term key is used a lot in that class and the "key" for single addons are really the addon's directory name which is different from addons' keys.
All this fixes an issue with the [AddonCacheController->verify](c1214664d1794bc3741ddd78d815924cf27038d1) where `AddonManager->lookupByType()` was compared against `AddonManager->scan()` but had differences detected since `lookupByType()1 was not returning the addonss keys for the themes.

Fix AdddonManager->lookupAllByType not returning addons by key in some cases.

---

library/core/class.request.php
tests/Library/Core/RequestTest.php

Fixes https://github.com/vanilla/vanilla/issues/5709
We did an update to improve the install experience in 2.3: https://github.com/vanilla/vanilla/pull/4622
We then [updated our install process](https://github.com/vanilla/vanilla/pull/4736) to avoid overwritting .htaccess which caused the installation process to fail since the urls are now rewritten and no rewrite are set by default.
To fix this issue this PR reverts the default of URL rewrites to false.
Our .htaccess.dist already contains REWRITE_X=1 which makes the forum use rewrites.
Our nginx installation process also specify that this flag must be there.
The config should not exist since rewriting capabilities should be specified by the X_REWRITE alone. We are only keeping it, here, for backward compatibility.

Do not rewrite URLs by default

---

applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/models/class.discussionmodel.php

Fixes https://github.com/vanilla/vanilla/issues/5421
The problem was that `discussionUrl()` was used with `$withDomain = true` to generate the route.
On embeded site that meant that `sendNotification()` could not [transform the route](https://github.com/vanilla/vanilla/blob/a4375c0f666a2f4a610657f2c6d9769e9bfa4cc0/applications/dashboard/models/class.activitymodel.php#L874) properly using `externalUrl()` since it was an absolute URL instead of a relative path.

Notification + embed: Store the route as a relative path for discussions' notifications

---

library/Garden/Web/Cookie.php
tests/Library/Garden/Web/CookieTest.php

`CookieTest::testSetCookie` has a check to validate the cookie's expiry. However, there is an issue where relative dates can be off just enough between when they're set and when they're checked, causing intermittent test failures.
This update does a couple things:
1. It alters the signature of `Cookie::calculateExpiry` to introduce a new parameter: `$timestamp`. If a valid timestamp is specified, its used as the base when determining relative expiry values. If no valid timestamp is supplied, the current timestamp will be used, as is the current behavior.
1. It moves expiry checking out of `CookieTest::testSetCookie` and into its own dedicated batch of tests. Since all `Cookie::setCookie` does with the expiry is pass it along to `Cookie::calculateExpiry`, it will maintain the same code …

Fix build randomly failing on CookieTest::testSetCookie

---

applications/dashboard/models/class.userauthenticationnoncemodel.php

Partially addresses https://github.com/vanilla/vanilla/issues/5763 until we fix the issue for good.
One some MySQL setup insert will throw an exception when trying to do an insert with no Timestamp field.

Default nonce timestamp to the current time if not provided

---

applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/models/class.discussionmodel.php

Backporting https://github.com/vanilla/vanilla/pull/5734 to [release/2017-Q2-6](https://github.com/vanilla/vanilla/tree/release/2017-Q2-6).

Backport #5734 to release/2017-Q2-6

---

library/core/class.format.php

Using an HTML special character (e.g. <, &, >) in a code block with BBCode causes the characters to be doubly encoded: [once by NBBC](https://github.com/vanilla/nbbc/blob/2da62098363c3da5a653d611ce15c41fa6681092/src/BBCode.php#L2218) and [again by Gdn_Format::htmlFilter](https://github.com/vanilla/vanilla/blob/c049793290ad3e91508c8a9ce478a9fdcdb3da42/library/core/class.format.php#L933). This update removes one of these checks. NBBC's application of `htmlspecialchars` remains, while the `$options` parameter passed to `Gdn_Format::htmlFilter` has been altered, explicitly setting the `codeBlockEntities` value to `false`. This change will avoid encoding the HTML entities (the ampersand, in particular) a second time.
Closes #5720 
Please backport to …

Fix double encoding of BBCode code block contents

---

applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/models/class.discussionmodel.php

This fix updates how URLs are generated for new discussion alerts with advanced notifications. Currently, the URL is generated with `discussionUrl`, setting its `$withDomain` to `false`, then it is parsed again with `externalUrl` to generate a full URL for use in emails. Both of these function calls use the `url` function and both of them add the site's web root. It is currently possible for a site's web root to be doubly added to discussion URLs.
This update sets the `$withDomain` parameter to "/" during the call to `$discussionUrl`. This returns the Vanilla path, only. The web root is not included. When the string reaches `externalUrl`, the site's web root is only added the single time, so the URLs should be valid under normal usage.

Fix discussion URLs in advanced notification emails

---

plugins/editor/js/editor.js

Fixes  https://github.com/vanilla/vanilla/issues/5660
Text and TextEx do not support html tags so we need to revert back to display a file preview under the editor when we are on mobile.

Fix inserting images on mobile

---

applications/vanilla/models/class.discussionmodel.php

GDN_Log: `Data mediumtext COLLATE utf8mb4_unicode_ci,`
GDN_Comment: `Body text COLLATE utf8mb4_unicode_ci NOT NULL,`
mediumtext can contain ~256 text fields.
If you add all the other fields + the overhead of the serialization it may be possible to bust the mediumtext field. To ensure that this can't happen this PR lower the number of comments that can be embedded into a discussion to 25.
Fixes https://github.com/vanilla/vanilla/issues/2946 and https://github.com/vanilla/vanilla/issues/5197

Prevent discussions from being truncated when inserted in the log table

---

.editorconfig

We've been moving towards 4 spaces only for a while.
This updates the `.editorconfig` to reflect that.

Change .editorconfig to only 4 spaces.

---

library/core/class.emoji.php
library/core/class.format.php

When posts are presented via the API in external sites it’s important to format URLs as full URLs.

Format emojis and mentions links with full URLs

---

.travis.yml

Until #5815 can be addressed, this update will force usage of the Precise distro on Travis builds.

Force Precise dist on Travis CI builds

---

applications/dashboard/models/class.usermodel.php

This update alters email confirmation tokens by increasing them from eight (8) characters to thirty-two (32) and including lowercase letters. This increases possible combinations from 36^8 to 62^32.
Closes #5817

Increase the complexity of email confirmation tokens

---

applications/dashboard/controllers/class.profilecontroller.php
applications/dashboard/models/class.usermodel.php

This update alters the `UserModel::save` routine to clear any outstanding password reset information when the user row's password or email is modified. Since this operation is performed at the model level, the cited attributes will be reset under the stated conditions, regardless of what is invoking the save routine.
Closes #2903

Clear password reset info when updating password or email

---

bootstrap.php
library/core/class.vanillahtmlformatter.php

Closes https://github.com/vanilla/vanilla/issues/5725
~~Fire 'VanillaHtmlFormatter_init' event when an instance is created.~~
This allows addons to add extra allowed classes through `addExtraAllowedClasses()`
Edit:
To test you can add this to a plugin:
```
/**
* @param Container $container
*/
public function container_init_handler($container) {
$container->get(VanillaHtmlFormatter::class)->addExtraAllowedClasses(['test']);
}
```

Add a way to defined extra allowed classes in VanillaHTMLFormatter

---

applications/conversations/models/class.conversationmodel.php

Make sure that `getMaxRecipients()` does not return `false` before comparing it.
Closes https://github.com/vanilla/vanilla/issues/5842

Fix max recipient check

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/models/class.commentmodel.php

This update adds the insertUserID parameter to the comments index endpoint under API v2 (/api/v2/comments). Performing a GET request to this endpoint using this parameter will allow you to filter the results based on who authored the comment. This can be used on its own to retrieve all comments by a user, or it can be used with the discussionID parameter to filter comments on a particular discussion by a specific user. The index endpoint now requires insertUserID *or* discussionID.
This new functionality uses the `CommentModel::getByUser2` method. The ability to control record sorting and filtering by date has been added to this function.
Closes #5800

Add param to comments index endpoint to allow lookup by author

---

applications/dashboard/controllers/class.settingscontroller.php

`/configuration` under API v1, which sits at /settings/configuration in the Dashboard.
* I cannot figure out what this was ever for.
* It's a bad security idea to leave anything like this laying around.
* It's been broken for a long time due to manually requiring a `transientkey` in a `GET`.
I've elected to leave a deprecated stub despite it consistently returning a 403 to all API request as-is, meaning it's extremely likely no one's using it.

Deprecate & null the API configuration endpoint

---

library/core/class.oauth2.php

Fixes https://github.com/vanilla/vanilla/issues/5766
Throw an exception if the code parameter is not set or empty.

[Oauth2] Display an appropriate error message when the code parameter is missing

---

applications/vanilla/views/categories/flat_all.php
applications/vanilla/views/modules/flatcategory.php

https://github.com/vanilla/vanilla/pull/4953 removed the default value ("1") for the `$depth` parameter of `writeListItem` in category helper functions. The flat category views count on this default. They only call `writeListItem` with one parameter. Up until PHP 7.1, this only generated a warning. As of PHP 7.1, "too few arguments" is a fatal error.
This update makes the calls to `writeListItem` in flat category views explicitly use the previous default: 1. This addresses the fatal error.
Closes #5787

Fix flat category views failing in PHP 7.1

---

applications/dashboard/views/activity/popin.php
applications/vanilla/views/discussions/popin.php

We have recently made changes in the code and created translation strings in order to accommodate differences in gender and pluralizations of certain strings. Instead of composing two unrelated strings (eg. t('All') . t('Bookmarks')) which doesn't translate easily in some languages we have created composed strings: "All Bookmarks". 
This PR replaces two places in the code where we were still putting the string together by composition.

Change "All X" strings to accommodate gendered translations

---

plugins/editor/js/editor.js

iOS does not allow you to call window.parent in an iFrame. The JS error was causing errors for flyouts for the editor.  By surrounding the code with a try/catch, we prevent the bug. The only side effect is we lose scroll to functionality on certain version of iOS, but it was broken to begin with.
Fixes https://vanillaforums.teamwork.com/#/tasks/6317471

Fix error caused by using editor in embedded site under iOS

---

plugins/editor/js/editor.js

Backporting: https://github.com/vanilla/vanilla/pull/5857
Low risk. Edge case on iOS in embedded forums for editor JS.

Backport: Fix error caused by using editor in embedded site under iOS

---

applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/js/category-settings.js
applications/vanilla/views/vanillasettings/category-settings-functions.php

This update adds some improvements to the category management screen to improve the experience when managing a large number of categories (200+).
Highlights:
1. Once a user moves a category, they aren't allowed to move another one until the current request has completed. The content area is "fogged" over and a small "Please wait" message is displayed until the save has completed.
1. The data sent to the server for each reordering request is limited to the current category's branch level and below. Moving a root-level category still sends the whole tree, but moving a child category will only send the subtree of it and its siblings.
Modifying this process obviously has the potential to inflict some catastrophic effects on category structures, so please test thoroughly.
Closes #5415

Optimize category sorting in the dashboard

---

bootstrap.php
library/core/class.dispatcher.php

Allows plugins, or any class really, to have a dependency on the current controller without calling Gdn::controller().
In the plugins it is useful if the event was not fire from a controller but you still need to reference it.
```php
/**
* @param Gdn_Controller $controller Current controller.
*/
public function __construct(Gdn_Controller $controller) {
$this->controller = $controller;
}
public function model_event_handler() {
$this->controller->jsonTarget({TARGET}, {DATA}, {TYPE});
}
```
I tried adding
```
->rule('Gdn_Controller')
->setInherit(true)
->setShared(true)
```
in `bootstrap.php` but the problem is that when you instantiate a new Controller you end up having a `Gdn_Controller` instance instead of a `SpecificController` instance in the container.
I was also playing with the idea …

Allow plugins to set a dependency on Gdn_Controller

---

applications/conversations/controllers/class.messagescontroller.php

This update makes sure names of unknown users are properly formatted when attempting to send a conversation message.

Fix username display when sending a message to unknown users

---

applications/conversations/controllers/class.messagescontroller.php

Backport: Fix username display when sending a message to unknown users

---

library/Vanilla/Web/Controller.php

Seems like we failed to properly do the Controller::permission() docblock.

Add missing throws to Controller::permission()

---

applications/conversations/views/messages/popin.php

This is to un-couple "All" and "messages" for more accurate translations in certain languages.

Fix “All messages” string for translations

---

applications/dashboard/models/class.sessionmodel.php
applications/dashboard/settings/structure.php
library/core/class.session.php

- Remove transient key from GDN_Session table since it was not used.
- Add DateExpire to GDN_Session so that we can prune it.
- Update Gdn_Session object to use the SessionModel.

Add SessionModel and use it in Gdn_Session

---

applications/vanilla/models/class.discussionmodel.php

Part of the decoupling "All %s" for translation purposes.

Fix “All Discussions” to make it more translatable.

---

applications/vanilla/views/drafts/drafts.php

This default text is what is set in the dashboard (It uses a symbol instead of a word) The text isn't currently in our locales at, but shouldn't need to be as a symbol. Using a times symbol would align other languages with the default english translation and the other pages with "delete"/"x" buttons.

Change default draft delete text

---

library/core/class.cookieidentity.php

This appears to be a longstanding typo. I found it by accident while tracing the code path for setting the long-term login persistence cookie.

Fix configuring cookie persistence 

---

library/Garden/Web/Data.php

Since endpoints return arrays or an instance of Data it makes sense for
the data object to act like an array in case we switch between the two.

Implement ArrayAccess with Garden\Web\Data

---

applications/conversations/models/class.conversationmessagemodel.php
applications/conversations/models/class.conversationmodel.php
applications/conversations/models/class.conversationsmodel.php

Add an option that allows to create a conversation without a message.
This is required by the ConversationAPIController.
Once we have time for it we can refactor both models to be separated instead of being mixed together.
What to check when testing:
- Users notifications (Activities)
- Users unread message count
- Conversation's message related fields (FirstMessageID, LastMessageID, CountMessages...)
- UserConversation message related fields (CountReadMessages, LastMessageID...)
- All the above when adding a user to a conversation that has no messages.
Easy way to clean your DB for testing purpose:
```sql
TRUNCATE GDN_Conversation;
TRUNCATE GDN_ConversationMessage;
TRUNCATE GDN_UserConversation;
UPDATE GDN_User SET CountUnreadConversations = NULL;
DELETE FROM GDN_Activity WHERE …
```

Allow conversation to be created without message

---

library/Vanilla/AddonManager.php

This is mainly to support easier testing because the AddonManager is a dependency of so many classes. Using all the defaults in the constructor basically means there are no addons to scan, but that is fine for testing.

Add a default for $scanDirs in the addon manager constructor

---

applications/dashboard/settings/structure.php

This is a pure infrastructure change, so it should never go to `master`.
When we added utf8mb4 compatibility as the default, we manually set every existing forum to use utf8 via the config so we wouldn't get an impromptu change. We're now ready to do that switchover, and ops has already made the necessary changes to the my.cnf. So now it's time to undo the manual setting of this config globally.
Because we've already deployed a change effecting the collation, we're currently blocked from further database changes until this is deployed and activated.

Remove Database.CharacterEncoding from inf configs

---

applications/dashboard/models/class.assetmodel.php

This was raising a deprecated notice which would make unit tests fails.

Fix deprecated call to Gdn::factory()->exists causing tests to fail

---

tests/InternalClient.php
tests/SiteTestTrait.php

This allows APIController calls in `setupBeforeClass` methods.
Otherwise you get permissions exceptions.
Example: https://github.com/vanilla/vanilla/blob/fa2b4ea8429b9c052f57edf087d784f0f8aa7939/tests/APIv2/MessagesTest.php#L31

Move session initiation in SiteTestTrait

---

applications/conversations/models/class.conversationmodel.php
applications/conversations/models/class.conversationsmodel.php

Simple stuff really.
- `$messageID` can be undefined unless `$createMessage` is `true` which was not a problem but it raises a notice.
- Copy pasta errors on `$notifyUserID`
Fixes issues caused by https://github.com/vanilla/vanilla/pull/5908

Fix undefined variable notice and refactoring error

---

composer.json

Install PHPUnit as a development dependency.
This allows for unit testing locally without installing phpunit elsewhere.
Especially useful for https://github.com/vanilla/vanilla-docker

Require PHPUnit ~5.0 as a dev install to allow unit testing

---

applications/dashboard/controllers/Api/UsersApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
tests/APIv2/UsersTest.php

There was an issue with generating automated docs. I also removed an endpoint I don’t want to launch with right now.

Disable the ability to verify users using the users API v2 endpoint

---

conf/config-defaults.php

word(.doc) and excel(.xls) are includes .docx and .xlsx extension for AllowedFileExtensions.
but powerpoint(ppt) is not include .pptx extension in AllowedFileExtensions.

add pptx for AllowedFileExtensions variable.

---

library/Garden/Web/Dispatcher.php
tests/InternalClient.php
tests/InternalRequest.php

I had a really bad time trying to find out what was not working while unit testing the API v2.
This change add the stack trace to reported errors from the new Dispatcher.
With the source of the error the debugging is waaayyy faster.
~The stack trace is only added when we are in the UnitTest environment so that's a good thing!~
The stack is set as part of the Data meta informations which are never displayed on the client side. 
We extract that information in VanillaTests\InternalRequest and set it as a custom header on the `HttpResponse`.
We then check, in `VanillaTests\InternalClient` if the custom header contains an error stack trace.

Improves dispatcher errors while unit testing

---

applications/dashboard/controllers/Api/UsersApiController.php
tests/APIv2/UsersTest.php

The standard for outputting a user's photo as part of a record in API endpoints is in the `photoUrl` field. The output schema used under the /users API v2 isn't adopting this standard and only uses the normal "photo" field.
This update alters the output schemas under the /users endpoint to put a URL to a user's photo under the `photoUrl` field.
"Photo" is going to remain a part of the full schema of the user record, because it is beneficial for setting a photo or reading a raw photo value (e.g. s3://path/to/file.jpg), whereas photoUrl should always be a client-consumable URL to the file.
Closes #5900

Use photoUrl in users API v2 endpoint

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
tests/APIv2/ConversationsTest.php
tests/APIv2/MessagesTest.php

**The blockers need to be merged before this can be fully reviewed.**
Creates 2 new API Controllers and their unit tests.
You can see that we used Message instead of ConversationMessage. We want the API to be simple for the user and ConversationMessage was a bad name. We know that we have a "message" feature in Vanilla but that will called something else. (alert, info, sitemessage...)
This was requested by Todd.
I could not use the `AbstractApiController` class for the Conversation message because it was assuming too many things about the controller. A refactoring of the base class will be likely needed if we want to accommodate controllers.
Note that the unit tests are using other controllers to setup themselves. That was a first and I had to make it work properly! See #5926
Unit tests …

Add conversations and messages API controllers

---

applications/vanilla/controllers/api/DiscussionsApiController.php
tests/APIv2/DiscussionsTest.php

This update adds the ability to pull the current user's bookmarked discussions with the API, using a GET request to /discussions/bookmarked. Available query parameters are:
1. `page` - The current page (defaults to 1).
1. `limit` - The maximum number of records to return, per page (defaults to the value of the Vanilla.Discussions.PerPage config or 50).
1. `expand` - Whether or not to insert a user record fragment for discussion authors.
A simple test is included to verify a bookmarked discussion shows up beneath /discussions/bookmarked.
Closes #5532

Add ability to retrieve bookmarked discussions with API v2

---

applications/dashboard/controllers/class.logcontroller.php

We currently have both the minified and non-minified version of jquery-ui in the core js folder [here](https://github.com/vanilla/vanilla/blob/master/js/library/jquery-ui.min.js), but for some reason we are using the the non-minified one. This PR changes that to use the minified version.
This saves ~150kb of every page load that includes these files, in some cases reducing page weight by more than 10%.

Switch jquery-ui for the minified version

---

applications/dashboard/controllers/Api/TokensApiController.php
applications/dashboard/controllers/class.profilecontroller.php
applications/dashboard/settings/structure.php
applications/dashboard/views/profile/token-delete.php
applications/dashboard/views/profile/token.php
applications/dashboard/views/profile/tokens.php
library/Vanilla/Web/Controller.php
library/core/class.accesstokenmodel.php
library/core/class.session.php
tests/APIv2/AbstractAPIv2Test.php
tests/APIv2/TokensTest.php
tests/InternalClient.php
tests/InternalRequest.php
tests/Models/AccessTokenModelTest.php

First and foremost, this update adds the /tokens endpoint for API v2. To that end, it does several things:
1. Adds index, GET id and DELETE methods to the endpoint. The index will list all of a user's active tokens. Getting a specific token by its AccessTokenID will return a usable `accessToken`. Deleting a token retains the record, but revokes and expires it.
1. To limit the usage of this endpoint to UI operations, some actions require a transient key. By design, API calls dodge transient key checks, so more direct checks have been added to `TokensApiController`. This has necessitated modifications to `Gdn_Session` to allow better access to its transient key generation/verification methods.
1. The AccessToken table now has an auto-increment primary key: AccessTokenID. InsertUserID has …

Add /tokens API v2 endpoint and UI

---

library/core/class.vanillahtmlformatter.php

Presently the VanillaHtmlFormatter will allow certain css classes to be added to certain DOM elements. This PR will allow table, tr and td elements to have css classes added to them.

Allow table-related HTML elements to have classes in posts

---

library/core/class.controller.php

A change in string to array "conversion" breaks RSS feeds on PHP 7.1.
See this comment:
http://php.net/manual/en/migration71.other-changes.php#120336
The error happens in Gdn_Controller::addAsset which assumes an asset container to be an array.
When RSS feeds are served, the container is cleared by setting it to an empty string.
Before PHP 7.1 it would be silently converted to an array, but on PHP 7.1 that conversion is not being made, leading to an empty content asset.

Fix RSS feeds on PHP 7.1

---

applications/vanilla/controllers/api/DiscussionsApiController.php
applications/vanilla/models/class.discussionmodel.php

This update adds the ability to sort and filter the discussions endpoint index by pinned/announced status. The implementation follows what is seen on Vanilla's frontend. If you have 30 normal discussions in a result and there are two pinned discussions, your result is going to be 32 total discussions.
Specifics on usage of the new parameters can be found in the associated issue.
Closes #5534

Add ability to filter and sort discussions endpoint index by pinned status

---

applications/dashboard/controllers/Api/AbstractApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
applications/vanilla/models/class.discussionmodel.php
tests/APIv2/DiscussionsTest.php

This update does a few things:
1. Moves setting the sink, closed and "announce" fields from PUT into POST and PATCH.
1. Updates setting "announce" to splitting it into two fields: pinned and pinLocation.
1. Adds `AbstractApiController::fieldPermission` to verify the current user has the specified permission, if a field is included in an array. This is used on the discussions endpoint, where you want to restrict access to the sink, closed, pinned and pinLocation fields, while still allowing fairly open access to the other fields.
1. Updates `DiscussionModel::save` to translate "pinned" and "pinLocation" into an appropriate value for "Announce".
1. Updates discussions endpoint tests to test the new method of setting the aforementioned fields.
Closes #5937

Move setting of announce, closed and sink fields to PATCH and POST under discussions endpoint

---

applications/dashboard/settings/structure.php

Since #5923 it no longer makes sense to lock the current encoding, and in fact it derives & saves as `false` now on inf.

Do not lock current encoding anymore

---

applications/dashboard/controllers/Api/RolesApiController.php
applications/dashboard/controllers/Api/UsersApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

This update alters existing endpoints to ensure `validateModel` is called after records are added or updated using a model's `save` method. [`validateModel` will analyze the `Validation` property of an object and throw specific `ValidationException` exceptions, if necessary.](https://github.com/vanilla/vanilla/blob/eae0d14e82c550bde08ab32d44f2195d79834102/library/Vanilla/Web/Controller.php#L203) This is done to ensure error messages returned by the API are as clear and specific as possible for these write operations.
Closes #5909

Improve error reporting in API v2 endpoints

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/models/class.commentmodel.php

The /comments endpoint index allow querying comments by discussion ID. Currently, this is done with `CommentModel::getWhere`. However, this method doesn't provide the hooks some addons use to modify comment content.
This update alters `CommentModel::getByDiscussion` to include a `$where` parameter. The contents of this parameter are passed along to the comment query, so additional filtering (InsertUserID, DateInserted, etc.) can be applied on top of filtering by the discussion ID.
There was a minor issue with paginating comments when querying by user, so I opted to solve that here, as well.
Closes #5854

Fix events not firing when using discussionID in /comments endpoint index

---

js/global.js

The close buttons for inform messages were broken on iOS safari. 
* I've added an href, since links are supposed to have them. I'd prefer to use a button, but we're likely to break some styling if we do. 
* I've added the tabindex for keyboard accessibility
* The onclick false is to prevent the link to "navigate"

Fixed click on close buttons iOS Safari

---

applications/dashboard/models/class.logmodel.php
applications/dashboard/models/class.spammodel.php
applications/vanilla/models/class.discussionmodel.php

When a discussion is flagged as SPAM and it has more than X comments, it's "flagged for review". This means the original post remains, but the revision is sent to the SPAM queue for approval. If the revision is confirmed *not to be* SPAM, the revision takes the place of the original post. If the revision is confirmed *to be* SPAM, the revision is deleted, along with the original discussion and its comments.
This update alters the SPAM removal process to be consistent with flagging. If a revision is confirmed as SPAM, but the discussion is still on the site and has more than X comments, it is not deleted. The revision will still be purged.
The number of comments before this behavior was triggered is currently three (3), however, that seems a little low. I'm bumping it up to 10 and moving …

Fix deleting a revision on a popular discussion also deleting the original record

---

applications/dashboard/models/class.logmodel.php
applications/dashboard/models/class.usermodel.php

Fixes https://github.com/vanilla/vanilla/issues/4951
- Update UserModel::insertForApproval() in order to be able to skip spam check.
- Use insertForApproval instead of insertForBasic when registration method is set to approval.

Send spam registration to the applicants queue on approval when registration method is set to "Approval"

---

applications/dashboard/controllers/Api/UsersApiController.php
applications/dashboard/models/class.usermodel.php
tests/APIv2/UsersTest.php

This update adds support for using emailConfirmed and bypassSpam in the users API v2 endpoint, instead of confirmed and verified, respectively. `UserModel` has been updated to support these fields. Tests have been updated to use these fields.
Closes #5920

Add emailConfirmed and bypassSpam as fields in users endpoint

---

library/Garden/Web/RequestInterface.php
library/core/class.request.php
tests/InternalRequest.php
tests/Library/Core/RequestTest.php
tests/fixtures/src/Request.php

This update adds some new members to request classes and tweaks some existing methods. Vanilla needs stronger header support, implemented similar to [PSR-7](http://www.php-fig.org/psr/psr-7). A couple header methods were added in #5349 and refined in #5519. The two remaining functions, `getHeaders` and `getHeaderLine` are implemented here. In addition, tests are included for these two functions, as well as `getHeader` and `hasHeader`.
Closes #5240

Add header methods to GDN_Request and RequestInterface

---

applications/vanilla/controllers/api/CategoriesApiController.php
tests/APIv2/CategoriesTest.php

This update adds a PUT action on the /categories API v2 endpoint for moving categories between parents.
To use, perform a PUT request to /api/v2/categories/[categoryID]/parentCategoryID where the body is a JSON of the new value:
```json
{ "parentCategoryID": 123 }
```
Closes #5799

Add ability to move categories between parents with API v2

---

applications/dashboard/views/activity/helper_functions.php

We don't have proper alt text on the activity photos, so for accessibility, we're adding aria-hidden="true" on the photos on the /activity page

Add aria-hidden="true" on photos on activity page

---

applications/conversations/models/class.conversationmodel.php

Fixes https://github.com/vanilla/internal/issues/1164
Fixes an issue where we were using $settings as an array where it was an object.

Fix deprecated detection when receiving an object in conversation model

---

applications/dashboard/controllers/class.entrycontroller.php

We obviously need to deprecate a method before removing it!

Restore redirectTo on entryController and deprecated it.

---

library/core/class.form.php

It is invalid HTML to have duplicate IDs. Although we should consider getting rid of default element IDs altogether that would be too much of a change so this change at least increments the IDs if they are re-used.
A few points:
* The first use of an ID should not add any prefix. This means that unique IDs will behave the same way they did before.
* If you view the source on a page that has duplicate IDs you’ll notice that some of the IDs seem out of sync. Look at the Form_hpt in particular. I decided that this is acceptable since we aren’t looking for an aesthetic solution to a dirty problem. Again, the ultimate solution should be to remove form element IDs altogether.
- There is a lot of javascript targeting form IDs. This seems risky and some testing should be done. However, according …

Increment duplicate form element IDs when multiple are added

---

applications/vanilla/views/discussion/helper_functions.php

Closes #5969
Posts announced only in their own category were not dismissible (most likely an oversite). This PR fixes this by checking for both types of announced categories instead of just 1.
Would it be better to check for all >0 values or all non-zero values instead of just additionally adding  the check for 2?

Allow dismissal of locally announced categories

---

library/Garden/Web/Dispatcher.php

Some endpoints will need to opt out of CSRF protection (such as SSO
endpoints). So instead of throwing an exception we ban the user within
the request. This will make permission checks fail unless an endpoint
specifically bypasses it.

Use a ban instead of an exception for bans

---

library/core/class.cookieidentity.php

Fixes https://github.com/vanilla/vanilla/issues/5995
This fixes a problem where users cannot Sign in on the forum because of a mismatch between the current host and the configuration.

Disregard Garden.Cookie.Domain if the hosts are completely distinct

---

library/core/class.dispatcher.php

[The dispatcher rewrites the full request to the default controller when visiting the homepage.](https://github.com/vanilla/vanilla/blob/8799b3ae7c468649afbf6e28c2dfa392aa0678af/library/core/class.dispatcher.php#L723) This means query parameters used by some addons (e.g. Multilingual's "locale" parameter) can be inaccessible on the homepage.
This update takes a snapshot of the query before the homepage rewrite, then merges in the original query parameters, if there were any.

Fix losing query parameters on homepage

---

applications/dashboard/models/class.usermodel.php
applications/dashboard/settings/structure.php

This update adds the `DateAccepted` field to the `Invitation` table. When a user accepts an invitation and their user ID is recorded in the invitation row, the `DateAccepted` column will also be populated.

Add DateAccepted to Invitation table

---

library/Garden/Web/RequestInterface.php
tests/InternalRequest.php
tests/fixtures/src/Request.php

There was no way to get the scheme from a RequestInterface.
The method was already implemented on Gdn_Request.

Add getScheme() to RequestInterface

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
library/Garden/Web/Dispatcher.php

Fixes https://github.com/vanilla/vanilla/issues/5941
Also update the APIControllers POST functions to return an array instead of a Data object.

Add default response codes per HTTP verb to API requests

---

applications/vanilla/views/discussion/helper_functions.php

Backport of #5974
Do we normally deploy backports like this everyone where or just on an as-needed basis?

[Backport] Allow dismissal of locally announced categories

---

applications/dashboard/models/class.usermodel.php
applications/vanilla/settings/class.hooks.php

`UserModel::getCategoryViewPermissions` is a virtual method, overridden by Vanilla in its hooks, to check if a user has view permissions on a category. It's been in Vanilla forever. To lookup permissions, it uses the `PermissionModel::getUserPermissions`. This method queries the database for permission values and has no caching.
This update swaps out the aforementioned permission lookup from `PermissionModel::getUserPermissions` to `UserModel::checkPermission`. This new method utilizes `UserModel::getPermissions`, which implements caching and includes the "loadPermissions" event for addons to hook into. Since `UserModel::checkPermission` didn't previously have the ability to check permissions against a specific foreign ID, I've implemented the ability to pass an ID with the existing …

Fix addons inability to affect permissions checks before a notification is sent

---

tests/APIv2/AbstractAPIv2Test.php
tests/APIv2/ConversationsTest.php
tests/APIv2/MessagesTest.php
tests/Bootstrap.php
tests/SiteTestTrait.php

Fixes https://github.com/vanilla/vanilla/issues/6015
- Allows to unit tests without a session being started.
- Add missing alias "RequestInterface" for Gdn_Request.
- Call `startAuthenticator()` after the site was installed (otherwise you get an error when calling `$session->end()` because the password authenticator is not loaded.

Miscellaneous improvements to testing

---

applications/dashboard/models/class.usermodel.php
applications/vanilla/settings/class.hooks.php

This update backports #6003 to [release/2017-Q2-6](https://github.com/vanilla/vanilla/tree/release/2017-Q2-6).

Backport: Fix addons inability to affect permissions checks before a notification is sent

---

applications/dashboard/design/style.css
applications/dashboard/views/modules/dropdown.php
applications/dashboard/views/modules/me.php
library/core/functions.general.php
library/core/functions.render.php

The Accessibility of the icons use a technique recommended by fontawesome. http://fontawesome.io/accessibility/
Note that the `.sr-only` is defined inside `styles.css`. Some themes overwrite that file, but luckily, BS3 has that class as well. I've tested multiple themes and I haven't found any issues with that class not being defined. 
Removed the "em" which doesn't really make sense from a semantic point of view. 
Removed training white space at start of last flyout, creating an extra unwanted space in mebox.
Set "tabindex", "role" and "aria-haspopup" attributes on mebox.
___
*Note that there will also be JS to improve accessibility of flyouts in general in Vanilla. This is a first step for the MeBox.*

Improve accessibility of MeBox

---

.travis.yml
tests/travis/main.sh

This update performs the following updates to the Travis build process:
1. Stop forcing Ubuntu Precise. This LTS release is no longer supported and Travis is phasing it out in favor of the next LTS release: Ubuntu Trusty.
1. Comment the build file.
1. Reorganize the build file (mainly alphabetizing).
1. Move Composer installation/updating from the install step to the before_script step. The install step is typically used for system dependencies and the before_script setup is used to prepare for the build script to be executed.
1. Cache Composer package files.
1. Stop caching apt (Debian) packages. [Travis's caching documentation](https://docs.travis-ci.com/user/caching/#Things-not-to-cache) recommends these types of files should be avoided, because there's no real benefit.
1. Move …

Revise Travis build process

---

applications/vanilla/controllers/api/DraftsApiController.php
applications/vanilla/models/class.draftmodel.php
tests/APIv2/DraftsTest.php

This update adds support for creating drafts with the API. The specifics of the actual implementation are detailed in the associated issue. The API implementation is what will become of drafts: all resource-specific fields going into the `Attributes` column. Right now, the API is serving as a translation layer. Once the necessary refactoring occurs to make drafts a more universally-usable resource, the translations can be dropped.
`DraftsModel` needed some help, so I've also performed the following updates:
1. Do not always require the `Body` field. This was blocking sparse updating with PATCH. The implemented fix mirrors similar `Body` requirement conditions from `DiscussionModel`.
1. Do not unset the `DiscussionID` if it is a `null` value. The condition appeared to be looking for an …

Add drafts API endpoint

---

applications/dashboard/controllers/api/RolesApiController.php
applications/dashboard/controllers/api/UsersApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

This update adds the URL parameter "ID" into all core endpoints that use it. Examples:
1. GET /api/v2/users/1/edit
1. PATCH /api/v2/comments/10
The schemas for some endpoints previously did not include the "id" URL path parameter, so it was not contained in auto-generated documentation. This should no longer be the case.
Closes #5911

Add ID field to input schema of some API endpoints

---

library/core/class.oauth2.php

Vanilla's OAuth2 passes the access token in the body of the request for a user's protected resources from an authenticating server. According to [rfc6750](https://tools.ietf.org/html/rfc6750) this is acceptable, but the preferred way is by passing it in the "Authorization" http request header field, as in:
>    GET /oauth/me HTTP/1.1
Host: server.example.com
Authorization: Bearer mF_9.B5f-4.1JqM
This PR will:
- Add a checkbox to the Oauth2 settings in the dashboard to opt into this workflow.
- If the provider is set to BearerToken=true, it will send not send the access_token in the body but send it in the HTTP request headers.
- These changes are fully backwards compatible.

Add bearer token in HTTP header for profile requests in OAuth2

---

tests/InternalRequest.php

The array should be an associative array with X-Data-Meta as its key.

Fix InternalRequest header merge

---

library/Vanilla/AddonManager.php

Fixes https://github.com/vanilla/vanilla/issues/6049
When the search pattern's class does not contain wildcards we can check a specific index of the autoloadClasses array instead of looping through the whole thing.

Optimize AddonManager->findClass()

---

applications/dashboard/controllers/class.activitycontroller.php
applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/views/post/spam.php

Add fallback translations for approval messages. The existing definitions are the same and we need to order translations for them, so instead of ordering multiple of the same translation, we fall back to the default, but still allow it to be overridden on a granular level in the future.
Goes with https://github.com/vanilla/locales/pull/47

Use fallback for translations of approval messages

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/conversations/models/class.conversationmessagemodel.php
applications/conversations/models/class.conversationmodel.php
library/Vanilla/Exception/ConfigurationException.php
tests/APIv2/ConversationsAllowModerationTest.php
tests/APIv2/ConversationsTest.php
tests/APIv2/MessagesAllowModerationTest.php
tests/APIv2/MessagesTest.php

Fixes #6061 
- Add the new ConfigurationException
- `permissionException()` should not have been used in APIControllerr
- Fix ConversationModel::inConversation function.
- This was a result of bad merges and the patch repo not being in sync with the master repo.
- Fix inability to disable floodControl check on ConversationMessageModel
- If the user was not an administrator `setFloodControlEnabled()` was called which was overriding any prior call to it. This was preventing us from disabling the floodControl check on the model for API tests.
- Update the Conversation/Message test suites to test with and without AllowModeration enabled.
Backport to `release/2.5a`

Fix tests for conversation and message API v2 endpoints

---

applications/vanilla/models/class.discussionmodel.php

Fixes https://github.com/vanilla/internal/issues/1231
I moved the query building part of `DiscussionModel::getWhere()` after the call to `DiscussionModel::categoryPermissions()` which ensure that there is no call to something that can go a query before `$this->sql->get()` is called.

Move SQL building after categoryPermission call

---

applications/dashboard/controllers/api/RolesApiController.php

An overhaul of the structure of permissions was proposed in #5539. This update implements that permission structure in roles API responses.
Closes #6062

Add simplified permissions roles API output

---

bootstrap.php
library/Vanilla/Models/AddonModel.php
library/Vanilla/Models/InstallModel.php
tests/Bootstrap.php
tests/TestInstallModel.php

Make sure that addon's bootstrap file is loaded no matter how/when it was activated.
I also modified the bootstrap `include` to `include_once` to prevent any bugs if we start refactoring that code in the future.
Calling `AddonModel::enable()` will now load the bootstrap file properly.
We also start a non persistent session as System to make sure that everything is installed properly. Some addons needs a valid user to install themselves properly. Especially those that insert data and need to fill the InsertUserID column.

Fix addon installations when installed as part of the initial forum setup

---

phpunit.xml.dist
tests/SiteTestTrait.php

> Restore SiteTestTrait::$addon array to it's original value on teardown.
This prevents pollution between tests since the variable is static and set on the base class AbstractAPIv2Test
Addons can now provide unit tests by having a tests folder.

Add ability for addons to include tests

---

library/Garden/Web/ResourceRoute.php
tests/Library/Garden/Web/ResourceRouteTest.php

This is a bit of a kludge to allow POST to be used against the usual PATCH method to allow for multipart/form-data on PATCH (edit) endpoints.
The initial implementation of this is narrow so POST cannot dispatch to `patch_action` style methods, just the default `patch` method.

Allow POST requests to dispatch to Controller::patch() in some circumstances

---

library/Vanilla/Addon.php
library/Vanilla/AddonManager.php
library/core/class.pluginmanager.php
tests/Library/Vanilla/AddonManagerTest.php
tests/fixtures/plugins/multiclass-namespaced-plugin/class.multiclass-namespaced-plugin.plugin.php
tests/fixtures/plugins/namespaced-plugin/class.namespaced-plugin.plugin.php

Fixes https://github.com/vanilla/vanilla/issues/6065
Return the correct Addon if multiple addons have the same name in different namespaces.

Fix issue with namespacing classes during lookup in AddonManager::lookupByClassname

---

library/core/class.form.php

#5785 was created before #5788, but it was merged after it. This seems to have introduced a casing issue where in the discussion type filtering no longer functions within `Gdn_Form::categoryDropDown`.
This update tweaks the casing to restore the aforementioned functionality.
Backport to [release/2.5a](https://github.com/vanilla/vanilla/tree/release/2.5a).

Fix filtering categories by allowed types in new post form

---

applications/vanilla/controllers/api/CategoriesApiController.php
library/core/functions.validation.php
tests/APIv2/CategoriesTest.php

- Add displayAs to categories endpoints.
- Run prepareRow() in more cases.
- Core enum validation is now case-insensitive.
- Mark some category fields as not required for POST.

Add displayAs to /api/v2/categories

---

library/Vanilla/UploadedFile.php
library/Vanilla/UploadedFileSchema.php
library/core/class.request.php
tests/Library/Core/RequestTest.php

In preparation for using file uploads with the API, this update does a few things:
1. Adds the new `Vanilla\UploadedFile` class, which attempts to be adherent to the `UploadedFileInterface` from [PSR-7](http://www.php-fig.org/psr/psr-7), with the exception that streams are not supported.
1. Merges entries from the `$_FILES` array into POST data in `Gdn_Request` as instances of `Vanilla\UploadedFile`. The structure of file attributes is normalized to something a little more sane in the process.
1. Adds a new `Vanilla\UploadedFileSchema` class, which extends `Garden\Schema\Schema`. This class will be used to verify a field in an API request is populated with a file (instance of `Vanilla\UploadedFile`).
1. Adds tests for `Vanilla\UploadedFile`.
To test out `Vanilla\UploadedFileSchema`, all …

Improve file upload support for API uploads

---

library/core/class.form.php
tests/Library/Core/FormTest.php

`Gdn_Form::input` is used to generate markup for form inputs. One part of this method analyzes the requests and attempts to [set the value attribute on the input markup its generating](https://github.com/vanilla/vanilla/blob/cbb18ce9e5be5eb85126d723ba0fd2d3a98dacff/library/core/class.form.php#L1851), based on values form a form submission. This functionality more or less checks postback data for a field with the same name and, if found, inserts that value as the "value" attribute on the input element.
There's been a longstanding issue where an empty "value" attribute is being applied to field fields. This was caused by the method not checking what the input type was, before attempting to assign its value attribute. Since files weren't in the postback data (`$_POST`), the value defaulted …

Fix attempting to set value on file field in Gdn_Form

---

applications/dashboard/controllers/api/AuthenticateApiController.php
tests/APIv2/Authenticate/LinkUserTest.php

This allows POST `/api/v2/authenticate/link-user` and `/api/v2/authenticate/linkUser` to be called instead of `/api/v2/authenticate/linkuser`

Camel case AuthenticateApiController::post_linkUser()

---

applications/dashboard/controllers/class.settingscontroller.php

Users with admin rights did not have access to /dashboard/settings/bans/find/["userid"]

fixed non-existing permission

---

library/core/class.pluginmanager.php
tests/Library/Vanilla/AddonManagerTest.php

We have unit tests that make sure that old $PluginInfo arrays and
addon.json arrays are compatible. Some of these tests broke when we
removed the $PluginInfo arrays due to underlying bugs in
Gdn_PluginManager::scanPluginFile().
I’m interesting in really fixing a deprecating function that shouldn’t
get called in production much, but our unit tests should not be
failing. This little kludge helps at least one of our addons.
FYI: The offending addon executes the [following
line](https://github.com/vanilla/internal/blob/master/plugins/SimpleAPI/
class.simpleapi.plugin.php#L387) as its addon.

Fix localhost unit testing for some external addons

---

library/Vanilla/DateFilterSchema.php
tests/Library/Vanilla/DateFilterSchemaTest.php

This update adds the `DateFilterSchema` class, which can be used to parse date filter strings into an associative array that can be used for building date filters in API endpoints. Examples of the supported date filter format can be found on the original issue.
```php
$data = ['myDate' => '[2017-10-01,2017-10-30]']
$in = $this->schema(['myDate' => new DateFilterSchema()]);
$data = $in->validate($data);
/**
* $data = [
*     'myDate' => [
*         'op' => '[]',
*         'value' => [
*             DateTimeImmutable,
*             DateTimeImmutable
*         ]
*     ]
* ]
*/
```
Closes #6037 
*Note: The original issue mentions building out a subschema array for these fields and adding a filter function to be called on the data, but this idea was scrapped in favor of subclassing …

Add date filter parsing with schemas

---

library/Vanilla/DateFilterSchema.php
library/Vanilla/UploadedFileSchema.php

This update removes parameters and `InvalidArgumentException` from `DateFilterSchema ` and `UploadedFileSchema` constructors. The exceptions give notice that custom schema specs aren't usable with these child classes, but the parameter causes the constructor signature to give the false impression they are.

Remove exceptions from DateFilter and UploadedFile schemas

---

tests/APIv2/TokensTest.php
tests/InternalRequest.php

There is a date comparison problems in unit tests.
Sometimes the dates are strings and something they are `DateTimeImmutable` objects.
This PR calls `Data::jsonSerialize()` on the returned data to make sure that it is compatible with what would be returned by the API called over HTTP.
This will ensure that IPs and Dates are formatted as strings.

Simulate that the data was passed over HTTP for unit tests

---

library/Vanilla/Addon.php
library/Vanilla/AddonManager.php
tests/Library/Vanilla/AddonManagerTest.php

Closes #6066
PHP namespaces are case insensitive so we are now storing the LC version of the namespace as the autoloadClasses index.
All comparison have been updated to make sure that we compare namespaces using LC.

Compare namespaces in a case insentive manner in the AddonManager

---

applications/dashboard/controllers/class.settingscontroller.php

Users with admin rights did not have access to /dashboard/settings/bans/find/["userid"]
Original PR [6112](https://github.com/vanilla/vanilla/pull/6112)

Backport: Fix invalid permission check when searching ban

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

This update adds a couple events to the comments and discussions API controllers, allowing addons to modify the results of GET and index requests.
To test, an addon can have a hook method with one of the following signatures:
```php
//Modify a single comment from a successful GET request.
public function commentsApiController_get_data(&$data);
//Modify an array of comments from a successful index request.
public function commentsApiController_index_data(&$data, $query);
//Modify a single discussion from a successful GET request.
public function discussionsApiController_get_data(&$data);
//Modify an array of discussions from a successful index request.
public function discussionsApiController_index_data(&$data, $query);
```
Closes #6105

Add data events to comments and discussions API controllers

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/dashboard/controllers/api/AbstractApiController.php
applications/dashboard/controllers/api/InvitationsApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

This update alters the "expand" parameter on several API endpoints, changing it from a boolean to a CSV of field names. The intended effect is to allow more control over what data is expanded.
Addons should be able to modify the allowed "expand" values in these schemas by hooking into relevant events (e.g. `controller_schema`).
Closes #6106

Update expand API parameter to be a CSV of specific fields

---

applications/dashboard/controllers/api/RolesApiController.php
applications/dashboard/controllers/api/UsersApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php

This update alters how nullable parameters are defined in API schemas. Adding the "allowNull" attribute to a field is dropped in favor of specifying null as a valid type for that field.
Closes #6126

Update syntax for allowing nulls in API schemas

---

applications/dashboard/models/class.usermodel.php

In the UserModel we have added hooks to allow plugins to filter users based on custom criteria (e.g. RankID). This requires that, just like we do when we filter by Role, we be able to turn off search optimization.
This PR passes the $optimize to the event handler so that any plugin hooking into 'BeforeUserQuery' or 'AfterUserQuery' can set it to false.

Enable turning off search optimization plugin adds custom filter criteria.

---

library/core/class.plugin.php

Plugin->render() used $this->Sender->render() although $this->Sender isn't set.

Fix Plugin->render()

---

applications/vanilla/controllers/class.categoriescontroller.php

Muting a category while in a mixed layout, would hide that category from the side bar and users are not able to unmute

fixed mixed layout muted categories

---

applications/dashboard/controllers/api/AbstractApiController.php

This update makes "expand" field functions in API controllers public, instead of protected. This allows addons access to these functions when instantiating or receiving an API controller in a hook.

Update the visibility of expand field functions in API controllers

---

applications/dashboard/controllers/api/RolesApiController.php
applications/dashboard/models/class.permissionmodel.php
applications/dashboard/models/class.rolemodel.php
applications/vanilla/controllers/api/CategoriesApiController.php
tests/APIv2/RolesTest.php

This update allows setting permissions on a role with the /roles endpoint. Specifics are in the associated issue, including the permission structure, but here's a rundown:
Closes #5775

Add ability to update permissions to RolesAPIController

---

plugins/vanillaconnect/VanillaConnectAuthenticator.php
plugins/vanillaconnect/VanillaConnectPlugin.php

This fixes 2 bugs 
1- If Gdn_Request::$webroot was set the signin and register url of VanillaConnect would contain 2 times the webroot because created the URLs with `url()` and they were wrapped in `url()` again in the `anchor()` function.
2- This is not a bug per say but since we moved the redirect parameter INTO the jwt token it was a bit messy. `provider.com/sigin?target=something` would become `provider.com/sigin?target=something&jwt={JWT}` which is counter intuitive since the redirect is done with the value of "redirect" which is located IN the jwt. So to clear things up the target parameter is now removed from the query string.

Fix multiple bugs with VanillaConnect redirects

---

applications/dashboard/controllers/class.settingscontroller.php

Users with admin rights did not have access to /dashboard/settings/bans/find/["userid"]
_Already Backported to Branch Release/2.5a__
Original PR [https://github.com/vanilla/vanilla/pull/6153](https://github.com/vanilla/vanilla/pull/6153)

Backport: Fix invalid permission check when searching bans

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

This update does a couple minor things:
1. Adds more parameters for the discussions and comments API data events.
1. Adds validating the query parameter to GETs for discussions and comments. The queries are validated with empty schemas by default, but addons will be able to modify these schemas.

Update API data event parameters for comments and discussions

---

library/Vanilla/Addon.php
library/Vanilla/AddonManager.php
tests/Library/Vanilla/AddonManagerTest.php
tests/fixtures/plugins/bad-require/addon.json

Closes #6146 
This bitwise operator was incorrect causing #6146. 
```php
const REQ_ENABLED = 0x01; // addon enabled, yay!
const REQ_DISABLED = 0x02; // addon disabled
const REQ_MISSING = 0x04; // addon missing from the manager
const REQ_VERSION = 0x08; // addon isn't the correct version
```
We pass `self::REQ_MISSING | self::REQ_VERSION` to `lookupRequirements`  or 
4 | 8 = 12
For `$row['status'] = REQ_MISSING`
(4 & 12) === 12 -> _false 4 & 12 === 4_ 
For `$row['status'] = REQ_VERSION`
(8 & 12) === 12 -> _false 8 & 12 === 8_
For `$row['status'] = REQ_MISSING`
(4 | 12) === 12 -> _true_
For `$row['status'] = REQ_VERSION`
(8 | 12) === 12 -> _true_
With this change addons will correctly check their requirements versions and existance.

Fix bitwise math to validate if an addon exists or is disabled

---

applications/dashboard/controllers/class.setupcontroller.php
library/core/class.cookieidentity.php

Fixes #6035
SetupController starts the admin session but it is invalidated on the next page load.
In https://github.com/vanilla/vanilla/commit/e7a80d4305d88aca6a26802245478c56e427aecd#diff-b2652d1a4ab0d73c2d31b0affccddc06 we moved from using `_setCookie()` which get the cookie salt by calling `Gdn::config('Garden.Cookie.Salt')` (so we would always have the latest value of the configuration) to using 
```
$jwt = JWT::encode($payload, $this->CookieSalt, self::JWT_ALGORITHM);
// Save the cookie.
safeCookie($this->CookieName, $jwt, $expiry, $this->CookiePath, $this->CookieDomain, null, true);
```
which uses the values that were existing on initialization. 
The problem with this is that when we are installing vanilla `$this->CookieSalt` is empty before we initialize the configuration properly. …

Fix not being logged in after installing

---

applications/dashboard/controllers/api/RolesApiController.php

The schema generated with `RolesApiController::getPermissionsFragment` used "type" as a property at the root of the schema definition. This is a special property in `garden-schema`.
This update reformats the schema definition to retain the same properties, but avoids defining the "type" property at the root schema level.
Also included:
1. Fixed the return type documented on `RolesApiController::getPermissionsFragment`.
1. Increased the visibility of `RolesApiController::getPermissionsFragment` to public.

Fix permissions fragment schema definition

---

applications/dashboard/controllers/class.entrycontroller.php

The Confirm form field was changed to PasswordMatch since existing validation functionalities required the field name to be PasswordMatch. While doing so we did not put in place some code to maintain backward compatibility. This PR fixes that by setting PasswordMatch to Confirm if the latter is set but the former is not.
Addresses https://github.com/vanilla/vanilla/pull/5091#issuecomment-340824430

Restore backward compatibility on the entry/passwordReset endpoint.

---

library/core/functions.general.php
tests/Library/Core/ArrayReplaceConfigTest.php

This function differs from **array_replace_recursive** in that if an array is numeric it will be completely replaced.

Add the arrayReplaceConfig() function

---

library/Vanilla/Utility/CamelCaseScheme.php
tests/Library/Vanilla/Utility/NameSchemeTest.php

I'm going to start adding tasks to fix some of our database column names to be consistent with a naming convention. This is PR is just a small test to make sure we have some testing on the actual naming scheme.

Fix invalid plural "IDs" conversion in the CamelCaseScheme

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/dashboard/controllers/api/AbstractApiController.php
applications/dashboard/controllers/api/InvitesApiController.php
applications/dashboard/controllers/api/RolesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

Since is it currently not possible to set a default value in a sub-schemas (See https://github.com/vanilla/garden-schema/issues/27), this PR changes `getExpandFragment()` to `getExpandDefinition()` and allows us to set a default value to the expand definition.
This saves us from "padding" the `$query` parameter and remove unnecessary parsing.

Update getExpandFragment() to getExpandDefinition()

---

applications/dashboard/settings/structure.php

The index was missing on `Timestamp` which is the `PruneField` in the UserAuthenticationTokenModel.
https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.userauthenticationtokenmodel.php#L17
This was causing the prune requests to stack up when the table reaches above 100K entries.
Would need to be backported to 2.5a

Improve pruning of UserAuthenticationToken table

---

applications/vanilla/views/modules/helper_functions.php
library/core/class.format.php

The Promoted content module was showing quotes in the text, and since it only provides a small excerpt, having a quote at the beginning of a post would present the quote as the actual content. 
- Refactor the converting of common tags into plain text into it's own protected function `Gdn_Format::convertCommonHTMLTagsToPlainText()`.
- Create a new function `Gdn_Format::replaceQuotes()` that works like replaceSpoilers. It uses pQuery to strip replace any of our quote elements with a translatable string `(Quote)`.
- Create a new function `Gdn_Format::excerpt()` that that uses the same logic of `Gdn_Format::plainText()`, but strips additional items. Currently the only extra thing it replaces is the quotes, but I could see this replacing additional items in the future such as code blocks.
I've …

Replace quotes in the promoted content module.

---

library/core/functions.render.php

The heading() function wraps the $title variable in h1 tags. The code in the if $returnUrl !== '' statement wraps the (now already altered) $title again in h1 tags, resulting in `<h1><h1>$title</h1></h1>`
I simply removed the second wrapping.

Stop function heading() from nesting h1 tags

---

applications/dashboard/models/class.rolemodel.php

PHP can throw a "strict standards" warning when calling `RoleModel::filterPersonalInfo`, because it uses `array_shift` directly on the result of `RoleModel::getByName`. The issue is the `array_shift` parameter is passed by reference and PHP only wants variables passed by reference. This update adds a simple intermediate variable. Functionality should remain unchanged.

Fix strict standards warning in RoleModel

---

applications/dashboard/controllers/api/AddonsApiController.php
library/Vanilla/Addon.php
library/Vanilla/AddonManager.php
library/Vanilla/Models/AddonModel.php
plugins/ButtonBar/addon.json
plugins/editor/addon.json
tests/APIv2/AddonsTest.php
tests/Library/Vanilla/AddonManagerTest.php

Addons can add a **conflict** key in their addon.json to specify other addons that conflict with them. The key is in the same format at the **require** key. A few points:
- This is a change to the AddonModel which isn't currently hooked up to the various old managers so it won't have an immediate impact on the UI. This is part of a larger change to move to addon management via API.
- I modified the **require** and **conflict** array outputs from the /api/v2/addons endpoints. This isn't specifically necessary for this PR, but I didn't want to make yet another PR for this.
- Addons can now specify "*" as a version requirement like composer. This is useful for specifying conflicts.
*This PR was rebased. Make sure you do a force pull if you have already checked the branch out!*

Add conflict support to addons

---

applications/vanilla/models/class.discussionmodel.php
tests/APIv2/DiscussionsTest.php

Vanilla's abstract API resource tests do some general modification of data during testing. One such test increments the value of any field ending in "ID". A recent patch requires a valid category ID, so blindly incrementing the `CategoryID` column no longer works.
This update fixes discussions API tests. Three test categories are created before the tests are run and tests are limited to those categories. In addition, a small tweak to `DiscussioModel::save` has been added to default its use-categories config check to `true`.
Closes #6202

Fix failing discussion API tests

---

library/Garden/Web/Dispatcher.php
tests/InternalClient.php

This prevents full HTML error pages during low level errors. Also, fix
the naming convention on errorTrace (previously error_trace).

Allow the API dispatcher to handle PHP 7 style errors

---

tests/APIv0/AltTest.php
tests/APIv0/BaseTest.php
tests/APIv2/AbstractAPIv2Test.php
tests/APIv2/AbstractApiControllerTest.php
tests/Library/Core/ArrayFunctionsTest.php
tests/Library/Core/ControllerTest.php
tests/Library/Core/DataSetTest.php
tests/Library/Core/DateTimeTest.php
tests/Library/Core/DbEncodeDecodeTest.php
tests/Library/Core/FactoryTest.php
tests/Library/Core/FormTest.php
tests/Library/Core/GeneralFunctionsTest.php
tests/Library/Core/JsonFilterTest.php
tests/Library/Core/PasswordTest.php
tests/Library/Core/PluginManagerTest.php
tests/Library/Core/RenderFunctionsTest.php
tests/Library/Core/RequestTest.php
tests/Library/Garden/ClassLocatorTest.php
tests/Library/Garden/EventManagerTest.php
tests/Library/Garden/Web/CookieTest.php
tests/Library/Garden/Web/ResourceRouteTest.php
tests/Library/Vanilla/AddonManagerTest.php
tests/Library/Vanilla/CheckVersionTest.php
tests/Library/Vanilla/DateFilterSchemaTest.php
tests/Library/Vanilla/LoggerTest.php
tests/Library/Vanilla/PermissionsTest.php
tests/Models/AccessTokenModelTest.php
tests/Models/CommentModelTest.php
tests/Models/InstallModelTest.php
tests/phpunit.php

Vanilla's tests aren't compatible with PHPUnit v6. This update tweaks several items to make the tests compatible with PHPUnit v6, while maintaining compatibility with PHPUnit v5.
1. Replaced all references to `PHPUnit_Framework_TestCase` with the namespaced equivalent (`PHPUnit\Framework\TestCase`). This forward-compatible class name is compatible with PHP v5.
1. Added error class aliases, mapping relevant PHPUnit v6 namespaced classes (e.g. `PHPUnit\Framework\Error\Notice`) to their PHPUnit v5 counterparts (e.g. `PHPUnit_Framework_Error_Notice`).
The full suite of Vanilla tests should run under both PHPUnit v5 and v6.

Fix test compatibility with PHPUnit 6

---

tests/APIv2/AbstractAPIv2Test.php

There is some case when there is not format (which means that it default to text).
When that's the case we should not attempt to format the "body" field.

Do not try to format the body if format does not exists

---

applications/vanilla/library/class.categorycollection.php
tests/Bootstrap.php
tests/fixtures/src/NullCache.php

Edit: We fear that changing Gdn_Dirty cache may break something on our infrastructure. We are gonna fix the unit tests bootstrap instead. 
~~Five years ago we [changed the way that DirtyCache works](https://github.com/vanilla/vanilla/commit/553b0fe67f8f59701c86f66c467f8d273eae3dc2)~~
~~The problem with this is that we use this caching object when the cache is [DISABLED](https://github.com/vanilla/vanilla/blob/aec797045f14cafb38716b85f9063dbc80429ee9/library/core/class.cache.php#L156).~~
~~This ends up causing problem if the application lives longer than one request which happens to be the case in unit tests.
For example in the role model, when we get the roles, [we cache the results](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.rolemodel.php#L517). …

Properly disable caching for unit tests

---

applications/dashboard/controllers/api/RolesApiController.php
applications/dashboard/controllers/api/TokensApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

Fixes #6190
Fixes #6187
I had to move `$this->roleByID($id);` after the schema definition in RoleApiController.
We need to remember that we must do: `PermissionCheck > Schemas definition > Anything else` in that particular order to be sure that the documentation will be properly generated.
I also changed `getPermissionsFragment()` to `getPermissionFragment()` because it was causing issues.
Long story short:
```
[
something? => Schema::parse([
':a' => [
'id:i?',
'type:s' => [
'enum' => ['global', 'category'],
],
'permissions:o',
],
]),
]
```
Does not work like
```
[
something:a? => Schema::parse([
'id:i?',
'type:s' => [
'enum' => ['global', 'category'],
],
'permissions:o',
]),
]
```

Fix swagger documentation

---

applications/vanilla/models/class.discussionmodel.php
tests/APIv2/DiscussionsTest.php

This update backports #6203 to [release/2.5](https://github.com/vanilla/vanilla/tree/release/2.5)

Backport: Fix failing discussion API tests

---

library/Vanilla/UploadedFileSchema.php
library/core/class.request.php
tests/Library/Core/RequestTest.php
tests/Library/Vanilla/UploadedFileSchemaTest.php

This update performs a few improvements to file upload validation, particularly in regard to `UploadedFile` and `UploadedFileSchema`.
1. Adds configurable size restrictions to `UploadedFileSchema`.
1. Adds extension restrictions to `UploadedFileSchema`.
1. Adds removal of empty (no file) uploads to request parsing.
1. Tests for all of the above are included.

Improve validation in file upload schemas

---

tests/APIv2/UsersTest.php

This update adds a couple tests for setting a user's roles via the API. The tests verify a user's roles can be set when a user is created or when they are patched and that the roles set are exactly what was intended.
Closes #6208

Add tests for setting a user's roles with the API

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
library/Vanilla/Web/Controller.php

This update adds schema IDs, not just types, to some actions in comment and discussion API endpoints.
Bonus fixes:
1. Use `fireFilter` instead of `fireArray` in comments and discussion API events, where the result is being modified, to avoid passing values by reference
1. Fixes a bug in `Vanilla\Web\Controller::schema`, where providing an array of ID and type would not properly translate to `$type` and `$id`.
1. Adds `$this` as a "sender"-style parameter to the schema init event, similar to the "controller_schema" event.

Add IDs to some schemas in comment and discussion API controllers

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php

This update changes the name of post API events from "data" to "output".

Tweak names of post API controller events

---

plugins/Quotes/class.quotes.plugin.php

Users logged in with "Members" are getting a permission error when trying to Quote.
Backporting to 2.5

Permission problem with Quotes-2.5

---

applications/vanilla/controllers/api/DiscussionsApiController.php
library/Vanilla/Web/Controller.php

This will allow addons to update the `$where` array.
Combined with an update of the 'in' schema this allows plugins to add additional filters in `index()`
**We now clone schemas in \Vanilla\Controller to preserve filters and validators added by addons.
If we want to not clone schemas we are gonna have to refactor our code to name ALL schemas.**
Backport to 2.5

Add filter event to discussions API index

---

plugins/Quotes/class.quotes.plugin.php

It is possible, with some plugins, to view a discussion without the "view" permission.
Checking for either add or view to allow quoting solves that problem.

Fix permission check when quoting a post

---

applications/vanilla/views/discussions/table_functions.php

Closes https://github.com/vanilla/internal/issues/1280
The actual issue is pretty well detailed. ~~I didn't use commentUrl() because that requires passing the actual comment. It seemed wasteful to lookup the comment only to strip it right back down to it's ID.~~

Fix latest comment link to point directly to the comment

---

applications/vanilla/controllers/api/CategoriesApiController.php
tests/APIv2/CategoriesTest.php

This update alters the re-casing of the `UrlCode` field in categories endpoints to "urlcode", instead of the current "urlCode".
1. `CategoriesApiController::normalizeInput` has been implemented to handle the proper case adjustment for "urlcode", since `CategoryModel` expects "UrlCode".
1. Tests have been updated, accordingly.

Rename urlCode to urlcode in categories API responses

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/dashboard/controllers/api/AbstractApiController.php
applications/dashboard/controllers/api/InvitesApiController.php
applications/dashboard/controllers/api/RolesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
library/Vanilla/ApiUtils.php
library/Vanilla/Web/Controller.php

This update does a couple things:
1. Moves `getExpandDefinition` from `AbstractApiController` to `ApiUtils`. Usage updates in code made, accordingly.
1. Reverts "{$id}Schema_init" events to just passing the schema, instead of also passing the controller. Passing the controller was originally introduced in #6219.

Move getExpandDefinition into ApiUtils

---

applications/dashboard/controllers/api/UsersApiController.php
library/Vanilla/FileUtils.php
library/Vanilla/ImageResizer.php
library/Vanilla/UploadedFile.php
library/Vanilla/UploadedFileSchema.php
library/Vanilla/Web/Controller.php
library/core/class.upload.php
tests/APIv2/UsersTest.php
tests/Bootstrap.php
tests/fixtures/src/FileUtils.php
tests/fixtures/src/Uploader.php

This update adds the ability to set and remove a user's photo with the API.
1. Added the ability to perform an in-place save of images with `ImageResizer`.
1. Added a method to retrieve the protected `ImageResizer::$typeExt` property.
1. Added the ability to get an upload's temporary filename to `UploadedFile`.
1. Added `$copy` parameter to `Gdn_Upload::saveAs` for allowing copying an upload a destination, instead of moving it.
1. Added `Controller::generateUploadPath` method for generating a valid, randomized upload path/filename, relative to the uploads directory.
1. Added `Controller::saveUpload` for saving uploads represented as instances of `UploadedFile`.
* Allows for easy manipulation of the file's base name, which is handy for the full-size (p) and thumbnail (n) prefixes used by …

Add uploading user photos with the API

---

applications/dashboard/controllers/class.profilecontroller.php

#6000 moved POST requests in the API from returning `Data` objects as responses to arrays. Prior to this, e10c69a altered an internal API call to the tokens endpoint, expecting a `Data` object as the result.
This update removes the assumption the result will be an object and instead allows the response to be processed as an array.

Fix generating user tokens from profile pages

---

applications/dashboard/views/profile/tokens.php

The "Generate New Token" button in a user's profile uses the `userUrl` function to generate the URL. The URLs generated by this function are relative to the configured web root and do not contain the web root, itself.
This update passes the `userUrl` result through `url`, which other links on the page use, and should handle properly prepending a configured web root.

Fix Generate New Token URL link in profile pages

---

applications/dashboard/views/profile/tokens.php

Backport: Fix Generate New Token URL link in profile pages

---

library/Vanilla/Models/SSOModel.php

Depends on #6239
Instead of passing "form" we pass "UserData" and "ExtraData" in the event.
Closes #6075

Add afterSyncUser event in SSOModel

---

applications/dashboard/models/class.updatemodel.php

Backport #6269
> We use core's `parseCoreVersion()` to evaluate uploads to the Addon directory on open.vanillaforums.com. Moving our basic app & version info out of index.php to environment.php broke backwards compatibility with ourselves.

Backport: Fix core version check to read environment.php

---

applications/dashboard/views/settings/helper_functions.php

The addon.json key "newVersion" showed only a number as the link text instead of "PluginName version x.y is available." because the wrong function has been chosen.

Fixed erroneous usage of printf() instead of sprintf()

---

applications/dashboard/controllers/class.entrycontroller.php

Closes #2772
If an SSO connection sets an avatar, it should then be allowed to blank said avatar on a later connection. Currently, or logic does not allow for that. This change fixes that, while preserving the commented functionality of "don't override an avatar we uploaded via Vanilla".

Allow Connect to blank a photo it previously set

---

conf/config-defaults.php
library/core/class.form.php

This was a needless use of parameters - those are already the defaults for `htmlspecialchars()` and we long ago decided this config wasn't necessary. This should be the end of it.
Closes #3047

Remove last references to Garden.Charset

---

library/core/functions.general.php

See #3055
We should no longer use these old functions anywhere. I was unable to find any uses of them.

Deprecate old proxy functions

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/views/settings/themeoptions.php

`Gdn_Form::escapeString()` is deprecated. Internally it just calls `Gdn_Form::escapeFieldName()`. I've replace the all the usages I could find.
See the escapeString declaration here:
https://github.com/vanilla/vanilla/blob/809ac0d730345270164348eda06f7b22b70f0bb9/library/core/class.form.php#L1614-L1617

Replace escapeString with escapeFieldName

---

applications/dashboard/settings/class.hooks.php

* Update PHP version check notice in Dashboard to trigger below PHP 7.0 (from 5.6).
* Cannot move to 7.1 until cloud upgrades.
* Change config value to re-institute in all Dashboards.
* Update MySQL version messaging (only) to reflect latest version recommendations.
Backport to 2.5 branch.

Update the version check to PHP 7.0

---

applications/dashboard/settings/class.hooks.php

Backport of #6270
Need this in the next open source release to give fair warning of changing requirements. See https://open.vanillaforums.com/discussion/35686/vanilla-will-end-php-5-6-support-in-2018

Backport: Update the version check to PHP 7.0

---

applications/dashboard/models/class.updatemodel.php

We use core's `parseCoreVersion()` to evaluate uploads to the Addon directory on open.vanillaforums.com. Moving our basic app & version info out of index.php to environment.php broke backwards compatibility with ourselves.

Fix core version check to read environment.php

---

applications/dashboard/models/class.permissionmodel.php

This allows a unit testing bootstrap to recycle the PermissionModel and
flush the loaded namespaces.
In particular, this fixes a bug in unit tests when both groups and badges are symlinked.

Fix permission namespace pollution in automated testing

---

README.md

Backport https://github.com/vanilla/vanilla/pull/6366 for open source 2.5.1 release.

Backport: Add a note about MySQL strict mode

---

plugins/OpenID/class.openid.plugin.php

Closes #3743
Just redirect to the default page instead.

Remove call to nonexistant `cancel` view in OpenID

---

plugins/ProfileExtender/class.profileextender.plugin.php

Closes #6232
Injects profile extender fields into the controller so they can be used in theme templates.
Output is just `"key" => "value"`.

Inject extended profile fields into controller data

---

applications/dashboard/views/entry/connect.php
plugins/OpenID/class.lightopenid.php
plugins/OpenID/class.openid.plugin.php

OpenID authentication attempts can contain a nonce. If a user is connecting to Vanilla via OpenID and the registration requires more information (e.g. an email address), validation is attempted twice: once during the initial connection and again after the required information has been provided by the user. If a nonce is part of the OpenID authentication, the first validation will succeed and the second will fail.
This update stashes a successful validation in a session, so subsequent validations aren't necessary.
A couple of bonus fixes are included:
1. `microtime` was being called without using the `$get_as_float` parameter, which meant it returned a string. The result was used in a subtraction statement, which are meant for numerical values. This was causing a warning. The fix was using …

Fix inability to validate OpenID authentications with nonce

---

library/core/class.format.php

Fixes https://github.com/vanilla/vanilla/issues/5961
The problem was that we were checking if the URL was in the anchor tag instead of checking that the URL was actually in the opening part of the anchor tag.

Fix issue where anchor text that are URL were altered

---

applications/dashboard/design/style-compat.css
applications/dashboard/design/style-compat.css.map
applications/dashboard/models/class.assetmodel.php
applications/dashboard/scss/style-compat.scss

The purpose of this file is to allow us to add new design elements even for themes that have overridden style.css.
Closes #6392.

Add the style-compat.scss file

---

library/core/class.format.php

Backport: Fix broken link text when using WarnLeaving config and Wysiwyg format

---

applications/vanilla/settings/class.hooks.php
applications/vanilla/views/discussion/profile.php
applications/vanilla/views/discussions/profile.php

Fixes #6107
First of, let's start by saying that the basic pager uses "more" which does not let you access "pages".
Since `/profile/discussions/{DISCUSISON_ID}/{USER_NAME}/p{NUMBER}` works, I added a detection that checks if the page had data before the permission filtering. If that's the case we display a more relevant message and let the "more" page active.
This solves the issue.

Fix error message on profile post lists when all page content is filtered

---

applications/vanilla/models/class.commentmodel.php
tests/Models/CommentModelTest.php

`CommentModel::lookup` has a routine to filter out comments the user doesn't have access to. It does this by looking at the category the comment is in and comparing it against the result of `DiscussionModel::categoryPermissions`. The problem is, in its current state, the category ID isn't available. `CommentModel::lookup` is referencing an undefined property. Because of this, custom category permissions on a site can filter out *all* comments on the comments API endpoint for some users/roles (e.g. ["if `null` isn't in my list of allowed categories, remove this comment](https://github.com/vanilla/vanilla/blob/9491a2dca2f527ebc22c615ef02526afdd403e7b/applications/vanilla/models/class.commentmodel.php#L476)).
This update joins in the Discussion table when querying comments. Since category ID …

Fix category permission check when using the comments API endpoint

---

applications/dashboard/views/profile/activity.php
plugins/editor/class.editor.plugin.php

Update the advanced editor so that image uploads can be activated without file upload.
Fixes https://github.com/vanilla/vanilla/issues/6374
Specifying FileUpload allows both file and image upload.
Specifying ImageUpload only allows image upload.

Fix image upload button not always appearing in Advanced Editor

---

applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/settings/configuration.php
applications/vanilla/settings/structure.php
tests/APIv2/CategoriesTest.php

Vanilla currently has a version of category following that has all categories being "followed" by default. A user has to "mute" a category to unfollow it.
Vanilla will be moving away from its blacklist-style following and towards a whitelist-style. This update introduces selective category following, so a users choose what categories to follow, instead of which categories to unfollow. The specifics of the overall feature are outlined in #6026. The subset of functionality introduced here is only the core components for toggling a category followed or not by a user, getting a list of followed categories and determining if a category is followed by a user. Details can be found in the associated issue, #6397.
The `Vanilla.EnableCategoryFollowing` config is introduced here, defaulting to …

Add explicit category following

---

applications/vanilla/models/class.commentmodel.php
tests/Models/CommentModelTest.php

This is a backport of #6446.
> `CommentModel::lookup` has a routine to filter out comments the user doesn't have access to. It does this by looking at the category the comment is in and comparing it against the result of `DiscussionModel::categoryPermissions`. The problem is, in its current state, the category ID isn't available. `CommentModel::lookup` is referencing an undefined property. Because of this, custom category permissions on a site can filter out *all* comments on the comments API endpoint for some users/roles (e.g. ["if `null` isn't in my list of allowed categories, remove this comment](https://github.com/vanilla/vanilla/blob/9491a2dca2f527ebc22c615ef02526afdd403e7b/applications/vanilla/models/class.commentmodel.php#L476)).
>
> This update joins in the Discussion table when …

Backport: Fix category permission check when using the comments API endpoint

---

applications/dashboard/controllers/class.authenticatecontroller.php
applications/dashboard/settings/class.hooks.php
library/Vanilla/Models/SSOModel.php
library/core/class.controller.php
library/core/class.session.php
plugins/vanillaconnect/VanillaConnectPlugin.php

Fixes #5988
- Session is now "invalid" if the user is banned or deleted.
- Throw the AfterSignIn event everywhere.
- Throw an exception on AfterSignIn if the user is banned.
- This take care of #5988 
- It is done that way (instead of in Session::start() to preserve backward compatibility). I'm also unsure as to why we are filling a ban array instead of throwing an exception but that tells me that we are probably checking the bad array later in the code.
How to test:
- Use entry/signin via PopUp
- Use entry/signin with no popup.
- Use VanillaConnect (which uses the /authenticate endpoint)
- Use any other SSO plugin (which uses the /entry/connect endpoint)

Fix session state during sign-in attempts when a user is banned

---

library/core/class.format.php

This update adds the `rel="nofollow"` attribute to profile links behind \@mentions in Vanilla. This mirrors the behavior seen in the Quotes addon for [linking to an author's profile from a quote](https://github.com/vanilla/vanilla/blob/073651a7e7b1707f39eef167d2fd207d96c1f4c2/plugins/Quotes/class.quotes.plugin.php#L344).
If you want to read up on nofollow, you can checkout it's Wikipedia page: [nofollow](https://en.wikipedia.org/wiki/Nofollow). It primarily functions as a hint for SEO crawlers to avoid "following" the content of links and associating them with the current site. This can also be good for guiding crawlers away from "page not found" (404) errors, when the generated \@mention profile link references a user that doesn't exist (since Vanilla doesn't check for an existing user …

Add nofollow to profile links behind @mentions

---

tests/APIv2/ApplicantsTest.php
tests/APIv2/UsersTest.php

Fix the tests on my local machine. They were hanging while sending emails. The addresses are invalid anyway.

Fix unit tests not always disabling email capabilities before execution

---

applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/models/class.discussionmodel.php
applications/vanilla/settings/structure.php
tests/APIv2/CategoriesTest.php
tests/APIv2/DiscussionsTest.php

This update adds filtering for followed categories to the discussions and categories API indexes. Here's an overview of the included changes:
1. The `UserCategory.Follow` field has been renamed to `UserCategory.Followed`. The original naming was done to be similar to the muting field, but this doesn't make sense with the rest of Vanilla's naming standards. Flags are almost always past-tense.
1. Added filtering for followed categories to the discussions API index.
1. Added tests for filtering in the discussions API index to followed categories.
1. Added filtering for followed categories to the categories API index.
1. Added tests for filtering in the categories API index to only those flagged as followed by the current user.
1. Updated `DiscussionModel::getWhere` to support a "Followed" …

Add followed category filtering to discussions and categories API endpoints

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
applications/vanilla/controllers/api/DraftsApiController.php
tests/APIv2/AbstractAPIv2Test.php
tests/APIv2/AbstractResourceTest.php
tests/APIv2/ConversationsTest.php
tests/APIv2/UsersTest.php

Fixes https://github.com/vanilla/vanilla/issues/6191
- Remove format for all record but get_edit()
- Allow the format to be applied to any records (not just body)

Remove format field from output in non-edit GET API requests

---

applications/dashboard/models/class.activitymodel.php

Fixes #6447
We added flood control to the activity model last year without knowing that the "activity queue" also use that model which means that flood control kicks in after X (default is 2) number of notifications are sent.
This means that if other notifications are queued before others some are not sent.

Disable FloodControl checks when saving the activity notification queue

---

applications/dashboard/settings/structure.php
library/database/class.mysqlstructure.php

Fixes: https://github.com/vanilla/vanilla/issues/5832
This update allow to set the default value of a timestamp to 'current_timestamp' or 'current_timestamp()' and refactor the AccessToken table to use that new feature.

Fix timestamp default values on AccessToken table

---

tests/Bootstrap.php

Can cause problems when running the full test suite with some other plugins.

Fix category cache being polluted between tests

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/conversations/models/class.conversationsmodel.php
applications/dashboard/controllers/api/ApplicantsApiController.php
applications/dashboard/controllers/api/InvitesApiController.php
applications/dashboard/controllers/api/UsersApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
applications/vanilla/controllers/api/DraftsApiController.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/models/class.commentmodel.php
library/Vanilla/ApiUtils.php
tests/APIv2/AbstractAPIv2Test.php
tests/APIv2/AbstractResourceTest.php
tests/APIv2/CategoriesTest.php
tests/APIv2/RolesTest.php

Addresses EOF problem of https://github.com/vanilla/vanilla/issues/6069
Add the ApiUtils::setPageMeta() function which update/create a data object with meta/header information about paging.

Add pagination information to API response headers

---

applications/vanilla/views/categories/all.php
applications/vanilla/views/categories/flat_all.php
applications/vanilla/views/categories/flat_table.php
applications/vanilla/views/categories/helper_functions.php
applications/vanilla/views/categories/table.php

The category follow buttons and filter menus were displaying in a couple areas where they shouldn't have been. The follow button was appearing on category rows and in category page titles where the category was not setup to display as "Discussions". The filter menu was sometimes appearing on non-root category index pages.

Fix category follow elements displaying where they should not

---

applications/vanilla/controllers/class.categoriescontroller.php
applications/vanilla/views/categories/discussions.php

This update adds the "Following" filter menu to the mixed category layout for filtering to followed categories.

Add followed category filtering to mixed category layout

---

applications/dashboard/models/class.usermodel.php

When caching is disabled, Vanilla stores a copy of the user's current permissions in the `User.Permissions` column. When caching is enabled, permissions are read and stored in the caching system. If you enable caching after the site has been running for a bit, there's a good chance the `User.Permissions` column will be populated with old permissions. In most cases this doesn't matter, because the field is not used for any authorization. The exception to this rule seems to be `UserModel::checkPermission`, which [uses the `Permissions` column of a user row to validate permissions, if it is a valid array](https://github.com/vanilla/vanilla/blob/7213c8ed8fcbc8598173b30fc1baf0e8358620db/applications/dashboard/models/class.usermodel.php#L258).
This update is a minimal fix: only use the …

Fix stuck category permission checks after enabling caching

---

library/core/functions.render.php

This update adds a condition to `categoryFilters` and `discussionFilters` to avoid displaying these menus if there is no valid session for the user (i.e. the user is not signed in).
Closes #6492

Fix filter menus showing for guests on Recent Discussions and categories root

---

js/global.js
library/core/class.format.php

This update adds support for `rel` parameters on YouTube links. Previously, only the `t` (start time) parameter was supported.
* Regular URL: https://youtu.be/9rpjlA-z080
* URL with start time: https://youtu.be/9rpjlA-z080?t=2m8s
* URL without related videos: https://youtu.be/9rpjlA-z080?rel=0
* URL with start time and without related videos: https://youtu.be/9rpjlA-z080?t=2m8s&rel=0
Closes #6358
*Bonus fix: The start time parameter was only working with single digits (e.g. 1m55s was treated as "one minute, five seconds"). Now, it works with multiple digits.*

Add support for rel attribute to YouTube embeds

---

library/core/class.format.php

For the sake of being able to backport a recent fix, this update removes usage of the null coalescing operator from `Gdn_Format`.

Avoid using null coalescing operator in Gdn_Format

---

library/core/class.format.php

Backport of #6526
> For the sake of being able to backport a recent fix, this update removes usage of the null coalescing operator from Gdn_Format.

Backport: Avoid using null coalescing operator in Gdn_Format

---

js/embed.js

- window.attachEvent is an IE only feature so I removed the call.
- scrollPosition() actually returns the offsetFromTop where top is the top of the document.
The intended behaviour is that when you click a link you on a link and the top of the iframe is not in the viewport of the browser there should be a "Scroll" top action so that the iframe top position is a the top of the viewport.
If the top of the iframe is in (or below since you shouldn't be able to click on something then) the viewport nothing should happen.

Fix scrolling to top of embed iframe if not in the viewport

---

library/core/class.dispatcher.php

Fixes https://github.com/vanilla/internal/issues/1362 (check it for more details)
Analyticstick.json should not be blocked when `Garden.PrivateCommunity` is turned ON

Fix analytics tick redirecting to sign-in when Private Community enabled

---

library/core/class.dispatcher.php

Backport #6528 
Relate to https://github.com/vanilla/internal/issues/1362

[Backport] Fix analytics tick redirecting to sign-in when Private Community enabled

---

applications/vanilla/views/categories/discussions.php
applications/vanilla/views/categories/helper_functions.php

If a category page had no categories to show, the content area was empty. No feedback was given. This update adds a "No categories were found" message to the page, similar to the message seen on discussion pages, when no categories are able to be displayed. This is particularly apparent when you attempt to view followed categories, but aren't actually following any categories.
Closes #6500

Add "none found" message to category pages with no categories

---

library/core/functions.general.php

If the user does not have permission to the record then just don’t join the record and unset the link as if there is no join.

Don’t unset records in joinRecords() if unset is false

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/dashboard/controllers/api/ApplicantsApiController.php
applications/dashboard/controllers/api/InvitesApiController.php
applications/dashboard/controllers/api/UsersApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
applications/vanilla/controllers/api/DraftsApiController.php
bootstrap.php
library/Garden/Web/Data.php
library/Vanilla/ApiUtils.php
library/Vanilla/Web/JsonView.php
library/Vanilla/Web/WebLinking.php
tests/APIv2/AbstractAPIv2Test.php
tests/Bootstrap.php
tests/InternalRequest.php
tests/Library/Vanilla/Web/WebLinkingTest.php

Fixes https://github.com/vanilla/vanilla/issues/6480
- Add a basic class to handle Web Linking
- This class can be used application wise to add links. The new JsonView uses it to add the relevant header to the Data object before rendering it. Our old Head module can do the same thing.
- Create a custom view that allow to transform Data->meta to headers
- Remove setPageMeta function from APIUtils since it does basically nothing now. (Do not forget to merge https://github.com/vanilla/internal/pull/1385 too)

Update API to use Web Linking

---

plugins/editor/class.editor.plugin.php
plugins/editor/views/editor.php

The editor toolbar was throwing a warning trying to access a nonexistent title attribute (for displaying to screenreaders). This PR adds title attributes to all of the dividers. 
Translation source here https://github.com/vanilla/locales/pull/50

Add title attribute to seperators

---

library/core/class.controller.php

This update adds a method to `Gdn_Controller` to detect if the request was made in the context of API v1 (Simple API). This method is currently only used in `Gdn_Controller::reauth` and is used to avoid potentially triggering reauthentication in API v1 requests (e.g. /api/v1/users/edit.jon).
Closes vanilla/internal#1384

Fix API v1 requests potentially requiring reauthentication
