plugins/ProfileExtender/class.profileextender.plugin.php

[Backport] Inject extended profile fields into controller data

---

plugins/OpenID/class.openid.plugin.php

Fix fatal error in OpenID authentication caused by bad session stash

---

applications/dashboard/models/class.usermodel.php

Fixes #6382
This PR fixes the problem by removing the group by and updating the `addIpFilters()` function which was the only place that could lead to user duplication in the query.
This adds an extra query instead of a join but that's not a big deal since this query is done from the dashboard.
Tested with IP, Roles, Emails. (Using `/user/browse?Keywords=?`)
Related https://github.com/vanilla/vanilla/pull/4332

Fix group by sql strict mode error when searching for users

---

.htaccess.dist

[Backport] Fix .htaccess to work correctly with subdirectory

---

applications/dashboard/models/class.assetmodel.php

Goes with https://github.com/vanilla/vanilla-cli/pull/73

Add config flag to serve hot reload bundle instead of core-js

---

applications/dashboard/views/social/manage.php
plugins/Facebook/addon.json
plugins/Facebook/views/settings.php
plugins/GooglePlus/addon.json
plugins/GooglePlus/views/settings.php
plugins/Twitter/addon.json
plugins/Twitter/views/settings.php

Update docs links for social plugins

---

applications/vanilla/controllers/class.vanillasettingscontroller.php
applications/vanilla/views/vanillasettings/categories.php
library/core/functions.render.php

This page allows category following to be turned on/off.
Closes #6394.

Add advanced category settings

---

applications/conversations/controllers/api/ConversationsApiController.php
applications/conversations/controllers/api/MessagesApiController.php
applications/dashboard/controllers/api/ApplicantsApiController.php
applications/dashboard/controllers/api/InvitesApiController.php
applications/dashboard/controllers/api/UsersApiController.php
applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
applications/vanilla/controllers/api/DraftsApiController.php

Depends on https://github.com/vanilla/docs/pull/211
Relate to https://github.com/vanilla/vanilla/issues/6069

Update APIv2 paging doc

---

applications/dashboard/models/class.activitymodel.php

Backport #6448
Relate to https://github.com/vanilla/vanilla/issues/6447

[Backport]  Disable FloodControl checks when saving the activity notification queue

---

js/global.js
library/core/class.format.php

Backport https://github.com/vanilla/vanilla/pull/6524

Backport: Add support for rel attribute to YouTube embeds

---

library/core/class.dispatcher.php

This PR includes a couple of things:
1. Fix view support in the API. There was a missing line in Gdn_Dispatcher where the wrong render was being called.
2. This is a checkout from another branch so I included the ability to accept dash-cased-controller-names in paths.

Fix view support for API routes

---

applications/vanilla/views/post/comment.php

> Remove the two links (or comment them out). Let's see if we get feedback about them being gone. 
> \- Todd

Comment out back links on the comment form

---

.eslintrc
package.json
yarn.lock

Fixes the broken ESLint config.

Fix ESLint config

---

applications/vanilla/controllers/class.categoriescontroller.php

This update adds the ability to filter followed categories based on a common ancestor. This is particularly useful for subcommunities.
There is no UI for this feature. Only the category index has the "following" filter. To test, you can add "followed=1" to the query string of a category URL.

Add filtering followed categories to a subset

---

applications/vanilla/controllers/api/DiscussionsApiController.php

We'll need to make sure that we can add types in the enum at some point.

Add type to API v2 discussion schema

---

applications/dashboard/scss/compatibility/_mixins.scss
applications/dashboard/scss/compatibility/_utilities.scss
applications/dashboard/scss/new-features/selectBox.scss
applications/dashboard/scss/style-compat.scss
applications/vanilla/models/class.discussionmodel.php
applications/vanilla/modules/class.discussionssortfiltermodule.php
applications/vanilla/views/modules/discussionssortfilter.php
library/core/functions.render.php

We want to update the UI for the ideation plugin for a more consistent look and feel across Vanilla.
Closes https://github.com/vanilla/internal/issues/1348

Refactor sort and filter UI for ideation

---

applications/dashboard/controllers/class.authenticatecontroller.php

Fix casing issues and move sessionID from query to post data.

Fix /authenticate bad refactoring

---

themes/2011Compatibility/addon.json

This is an old theme we haven't touched in several years. We'll hide it for now and likely delete it at some point.

Hide 2011 Compatibility theme

---

src/scripts/app/embeds.js

Added code to truncate excerpt in link embeds

Truncate link embed excerpt

---

applications/vanilla/controllers/class.vanillasettingscontroller.php

Closes https://github.com/vanilla/vanilla/issues/6533
If an ancestor of the added category has a displayAs of "Categories" or "Flat" redirect to that category instead of redirecting to the root category.
There's a protection against infinite loop caused by corrupted/imported data.

Update redirection after adding a category.

---

applications/dashboard/controllers/api/UsersApiController.php

This update adds output filters to the users API endpoint, similar to those seen in `DiscussionsApiController` and `CommentsApiController`.
In addition, schema names have been given to input schemas on the GET and index of the users endpoint, similar to `DiscussionsApiController` \[[1](https://github.com/vanilla/vanilla/blob/6e39fbd7188fb29c0dfec9089f4cdc8eb9af4ada/applications/vanilla/controllers/api/DiscussionsApiController.php#L221), [2](https://github.com/vanilla/vanilla/blob/6e39fbd7188fb29c0dfec9089f4cdc8eb9af4ada/applications/vanilla/controllers/api/DiscussionsApiController.php#L416)\] and `CommentsApiController` \[[1](https://github.com/vanilla/vanilla/blob/6e39fbd7188fb29c0dfec9089f4cdc8eb9af4ada/applications/vanilla/controllers/api/CommentsApiController.php#L166), …

Add output filters to users API endpoint

---

library/Garden/Web/Dispatcher.php
library/Garden/Web/Exception/ServerException.php

Do not mask php errors when in debug mode.
Default ServerException error code to 500.

Quality of life improvements

---

applications/conversations/views/messages/messages.php
applications/dashboard/views/activity/helper_functions.php
applications/vanilla/views/discussion/discussion.php
applications/vanilla/views/discussion/helper_functions.php

Reference vanilla/vanilla#6673
Related vanilla/internal#1464
Related vanilla/addons#599
Add's user content class for non-plaintext content created by users. This class is used for some styles related the rich editor.

Add userContent class

---

applications/vanilla/models/class.discussionmodel.php
applications/vanilla/modules/class.discussionssortfiltermodule.php
applications/vanilla/views/modules/discussionssortfilter.php
library/core/functions.render.php

I screwed up my last [PR for ideation](https://github.com/vanilla/vanilla/pull/6750).
This PR puts back changes to the views for ideation.

Fix - Missing changes to ideation views

---

library/Vanilla/PermissionsTranslationTrait.php

The new permission is uploads.add

Translate the attachments upload permission

---

applications/dashboard/controllers/class.logcontroller.php
applications/dashboard/models/class.logmodel.php

Fixes https://github.com/vanilla/vanilla/issues/6720

Add automatic pruning of the log table

---

plugins/rich-editor/class.rich-editor.plugin.php
plugins/rich-editor/views/rich-editor.tpl

Check if user is allowed to upload images in the rich editor.
Closes: https://github.com/vanilla/vanilla/issues/6770

Rich Editor - check upload permission

---

applications/vanilla/controllers/class.discussioncontroller.php
applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/models/class.commentmodel.php
applications/vanilla/models/class.discussionmodel.php
applications/vanilla/views/discussion/helper_functions.php
library/core/class.model.php

This fixes https://github.com/vanilla/vanilla/issues/5867
It does not take any time outs into consideration and I haven't moved it to the postcontroller. Just a simple fix.

Respect Vanilla.Comment.AllowSelfDelete setting.

---

applications/vanilla/views/modules/discussionssortfilter.php

For theming, I added a generic class to the wrapper for sort and filter in the sort and filter module.

Added common class to discussion filter and discussion sort.

---

README.md

Supported browser versions bumped, and the current release version has been bumped as well. Additionally a sentence has been renamed to make 2.3 past tense instead of future tense.

Fix README product versions

---

README.md

See https://github.com/vanilla/vanilla/pull/6795#issuecomment-377236837

Chow Bye badges

---

library/core/class.controller.php

Add js back to master after the release is forked.
Reverts vanilla/vanilla#6889

Revert "Remove new unused javascript from the release"

---

library/core/class.controller.php

Oops I seemed to have messed up. The fork already happened.
#6889

[Backport Only] Remove new unused javascript from the release

---

plugins/Facebook/class.facebook.plugin.php

Backport changes from PR #6875 
> Facebook has recently changed their Redirect_Uri policy for Facebook Login. In the past and in grandfathered Facebook Login Apps you can have the "Use Strict Mode for Redirect URIs" set to "No" in an app allowing your app to accept Redirec_Uri's with variable query strings attached to them (e.g. https://myforum.com/entry/connect/facebook?Target=%2Fdiscussion%2Fsome-discussion). Now when you create a new Facebook Login app the "Use Strict Mode for Redirect URIs" is toggled to "Yes" and you cannot set it to "No". And if you switch a grandfathered account to "Yes" you cannot set it back to "No". This breaks the log in process entirely.
> This PR removes adding "?Target" strings to Redirect_Uri sent to Facebook Login when a user is logging in.
> The affect …

Backport: Change redirect behaviour for users logging in through Facebook.

---

applications/vanilla/controllers/class.discussionscontroller.php
applications/vanilla/modules/class.discussionsmodule.php

Backport #6948 which fixed #6949

[Backport]  Properly set where condition if all categories are visible

---

js/global.js

Backport Fix init event in IE 

---

applications/dashboard/models/class.logmodel.php

Remove type hinting on LogModel::deleteIDs()

---

applications/dashboard/models/class.logmodel.php

Backport #6975 which closes #6976

[Backport] Remove type hinting on LogModel::deleteIDs()

---

applications/dashboard/modules/class.pagermodule.php
applications/vanilla/controllers/class.categoriescontroller.php
applications/vanilla/controllers/class.discussioncontroller.php
applications/vanilla/controllers/class.discussionscontroller.php
applications/vanilla/controllers/class.vanillacontroller.php

Backport: Fix edge case crawl errors

---

applications/dashboard/controllers/api/AuthenticatorsApiController.php
bootstrap.php
library/Vanilla/Authenticator/Authenticator.php

Fix Authenticator API

---

applications/dashboard/settings/structure.php
library/database/class.mysqlstructure.php

Backport #6376 which closes #5832

[Backport] Fix timestamp default values on AccessToken table

---

library/Garden/Web/Exception/HttpException.php

This change is mainly to aid in ignoring certain exceptions inspections in PhpStorm.

Type hint HttpException::createFromStatus()

---

applications/dashboard/controllers/class.profilecontroller.php
applications/dashboard/modules/class.headmodule.php
applications/vanilla/settings/class.hooks.php
applications/vanilla/views/discussion/profilecomments.php
applications/vanilla/views/discussions/table_functions.php
applications/vanilla/views/modules/usercomments.php

- Nofollow comment deep links.
- Use the userUrl() function instead of hard-coded URLs

Minor crawl management enhancements

---

applications/dashboard/src/scripts/Authenticate/RecoverPasswordPage.tsx

Accidental incorrect casing of this import.

Fix casing error

---

applications/conversations/controllers/class.messagescontroller.php

closes https://github.com/vanilla/vanilla/issues/7097

Fix access and posting of new messages to/in inexistent conversations 

---

plugins/GooglePlus/class.googleplus.plugin.php

Backport: GooglePlus: Double url() call

---

applications/dashboard/controllers/class.homecontroller.php

The class was missing and there is necessary CSS that references it. To what needs to be done: go to /home/updatemode before and after this PR.

Add the error section CSS class to /home/updatemode

---

applications/vanilla/modules/class.tagmodule.php

In order to allow addons to customize which tags are being displayed, we have to allow them to hook in and modify the data.

Add getData event to TagModule

---

library/core/class.pluggable.php

This is a temporary change to give us some protection when moving to PHP 7.1 because it has promoted this warning to an error. We think we don’t really have handlers that express the bug, but if we do we don’t want them to break pages. With this change they will log errors and we can fix them ASAP.
Once we’ve caught errors this change should be reverted.
Closes #7013.

Look for ArgumentCountError exceptions when calling event handlers in Gdn_Pluggable

---

library/core/class.form.php
plugins/editor/class.editor.plugin.php

[Backport] Make image upload on the by default for bodybox

---

applications/dashboard/controllers/api/AuthenticateApiController.php
applications/dashboard/controllers/api/AuthenticatorsApiController.php
library/Vanilla/Authenticator/Authenticator.php
library/Vanilla/Models/AuthenticatorModel.php
tests/Bootstrap.php
tests/Library/Vanilla/Authenticator/AuthenticatorCssColorValidation.php
tests/fixtures/src/CssColorAuthenticator.php

Closes https://github.com/vanilla/vanilla/issues/7025
-Add URIs validation for authenticators in the relevant APIControllers.
-Add CSS color validation in Authenticator class.
-Fix a bug in Bootstrap.php where CategoryModel doesn't exist if you do not run the full test suite (Since the Vanilla application was never installed)

Authenticator fields validation

---

applications/dashboard/controllers/class.authenticatecontroller.php
library/core/class.cookieidentity.php

We seemed to still be using this in a couple of places.

Replace Gdn_ErrorException handler with Exception

---

applications/dashboard/models/class.updatemodel.php

These appear in the addon directory on open.vanillaforums.com and needed some updating.

Update hard-coded descriptions of Vanilla and Porter

---

applications/dashboard/src/scripts/Forms/InputTextBlock.tsx
src/scripts/Interfaces/componentIDs.ts

Had some uncommitted changes from yesterday, sorry!

Fixed broken PR from yesterday - fixes ids for react components

---

tests/javascript/webpack.test.config.js

The modules were being resolved in the wrong directory.

Fix inability to run JavaScript tests

---

applications/dashboard/addon.json
applications/dashboard/global.d.ts
applications/dashboard/src/scripts/dom.test.ts
applications/dashboard/src/scripts/dom.ts
package.json
tsconfig.json
yarn.lock

I've added a getNextTabbable element utility function with the requisite unit tests.

Add getNextTabbableElement utility function

---

library/core/class.request.php

This reverts commit 9bf81855b3bf33c73c51680bc41a6ab64d94837f which fixes https://github.com/vanilla/vanilla/issues/7258.
All the details here: https://github.com/vanilla/vanilla/issues/7258#issuecomment-393958487

Fix installing Vanilla on Apache before .htaccess is available

---

applications/dashboard/src/scripts/dom.ts

There were some browser compatibility issues with out focus handling.

Make focus events browser compatible

---

README.md

Backport to 2.6: Readme update

---

applications/dashboard/views/modules/userbox.php

Backport to 2.5: Email escape

---

applications/dashboard/views/modules/userbox.php

Backport to 2.6: Escape email

---

applications/vanilla/controllers/class.discussionscontroller.php
applications/vanilla/models/class.discussionmodel.php

Backport: Fix cached announcements on Recent Discussions sometimes being filtered out (2.6)

---

applications/vanilla/controllers/class.categoriescontroller.php
applications/vanilla/controllers/class.discussionscontroller.php

Backport: Fix Category following filter displaying on QnA plugin (2.6)

---

applications/vanilla/views/discussions/archives.php

Regarding https://github.com/vanilla/support/issues/11

fix writeDiscussionRow function and calls

---

library/core/functions.general.php

getRecord recently refactored in [Refactor getRecord](https://github.com/vanilla/vanilla/commit/734c4e586d6d2a1db4cb89505e40a396c7edba57#diff-604330a5cab4bf405103e84612897812)
- goto /activity
- report a post
Closes #7280

Reporting a post in activity page error

---

library/Vanilla/Authenticator/ShimAuthenticator.php
library/Vanilla/Models/AuthenticatorModel.php

Provide a valid signIn URL in ShimAuthenticators

---

applications/vanilla/models/class.discussionmodel.php

Backport: Fix inability to restore some discussions from the moderation queue (2.6)

---

applications/dashboard/js/entry.js

In which some jQuery selectors in entry.js allow some wildcards, which can interfere with plugins that add fields to the registration page.

Remove entry.js wildcard selectors

---

library/core/functions.general.php

Backport: Reporting a post in activity page error (2.6)

---

tests/APIv0/SmokeTest.php

As per @initvector advice, adding these @large tags to ignore those tests in the internal repo.

Adding the @large tag to the bookmarking discussions test

---

applications/vanilla/modules/class.bookmarkedmodule.php

Backport: Fix error message "Unknown column" appearing when bookmarking a discussion (2.6)

---

applications/dashboard/models/class.tagmodel.php
applications/vanilla/controllers/class.discussionscontroller.php

Backport: Fix fatal error on /discussions/tagged pages (2.6)

---

applications/vanilla/modules/class.promotedcontentmodule.php

Backport: PromotedContent score type validation (2.6)

---

tests/Library/Vanilla/Embeds/InstagramEmbedTest.php

This adds a tests the parseHtmlResponse method in the Instagram Embed class.
related to Vanilla#7406

Add Instagram Embed Unit Test

---

applications/dashboard/src/scripts/state/getStore.ts
applications/dashboard/src/scripts/state/reducerRegistry.ts
library/Garden/MetaTrait.php
library/Garden/Web/Data.php
library/Vanilla/Browser/ReduxTrait.php
library/core/class.controller.php

- Added the ReduxTrait so that controllers can have methods to transmit initial state information.
- Make the getStore() redux initializer lazy so that addons can register their reducers in any order.
- Refactor the reducerRegistry into a module.

Add server-side redux support

---

applications/dashboard/src/scripts/state/getStore.ts

Fix getStore.ts file format issue

---

applications/dashboard/controllers/api/UsersApiController.php

Add delete method to users API v2 endpoint

---

applications/vanilla/models/class.categorymodel.php

Backport: Add the AfterSaveCategory event (2.6)

---

library/core/class.session.php

Backporting #6992 
Regarding https://github.com/vanilla/support/issues/62

Backport: Always load the transient key (2.6)

---

applications/dashboard/controllers/api/UsersApiController.php
applications/dashboard/models/class.usermodel.php

Backport: Fix users API v2 endpoint requiring an email address when site is configured to not use emails (2.6)

---

plugins/editor/class.editor.plugin.php

Backport: Fix Advanced Editor uploads failing if unable to determine MIME type (2.6)

---

applications/dashboard/models/class.rolemodel.php

Backport: Fix query escaping throwing error when deleting a role (2.6)

---

applications/vanilla/models/class.categorymodel.php

Backport: Add event AfterDeleteCategory (2.6)

---

applications/vanilla/models/class.discussionmodel.php

Backport : Fix discussion summaries not always including all visible categories (2.6)

---

applications/dashboard/views/admin.master.php

Bad look, but mobile needs it. Closes #7554

Restore site link in admin page

---

applications/dashboard/models/ReflectionAction.php
library/Vanilla/DateFilterSchema.php

- Any type that is [“type”, “null”] becomes “type” with an x-nullable attribute.
- The expand attributes are now arrays of string with an extra “all” in the attribute.
- Fix some path parameter issues.

Fix some support for swagger docs

---

applications/dashboard/library/class.nestedcollection.php
applications/dashboard/models/class.usermodel.php
applications/vanilla/views/discussion/helper_functions.php
library/core/functions.render.php

Reverts https://github.com/vanilla/vanilla/pull/7561
That PR broke signin pretty hard in more ways than one. There was this https://github.com/vanilla/vanilla/issues/7603 but additionally sign in was failing because of some arrays being called as if they were objects.
We can revisit that PR later.

Revert Val function changes from #7561

---

applications/dashboard/library/class.nestedcollection.php
applications/dashboard/models/class.usermodel.php
applications/vanilla/views/discussion/helper_functions.php
library/core/functions.render.php

Reverts vanilla/vanilla#7604
The only typo need to be fixed there:
```
deprected(__FILE__.'setCalculatedFieldsObject( &$user)');
```
`deprecated(__METHOD__);`
Lets revert and I'll change one line then

Revert "Revert Val function changes from #7561"

---

applications/dashboard/modules/class.pagermodule.php

The pager module made it difficult to style on mobile. I've added some helper class for the themer:
- How many links are there in the pager
- Common class for next/prev
- Common class for page links

Add classes to pager module to improve ability to style

---

applications/dashboard/src/scripts/app/user-content/embeds/quote.tsx
plugins/rich-editor/package.json
plugins/rich-editor/yarn.lock

Closes https://github.com/vanilla/vanilla/issues/7631

Fix duplicated parchment

---

library/core/class.statistics.php

Subsequent PR to https://github.com/vanilla/vanilla/pull/7602

Fix statistics class variable being used as method

---

library/core/functions.render.php

Added missing translation for "All" in Category-Following.

Category-Following: add translation for "all"

---

applications/vanilla/views/categories/helper_functions.php
library/core/functions.render.php

- Only try and apply the discussion CSS classes if a discussion field is detected.
- Pass $inList = true in category lists.

Fix discussion CSS classes

---

library/core/class.format.php

We currently handle live channels twitch embeds, this addition will also handle twitch embeds of previously recorded videos.

Add recorded twitch embeds

---

applications/dashboard/models/class.tagmodel.php

Backport: Tagged Discussions: Update tagged discussions sort order (2.7)

---

applications/dashboard/design/style-compat.css
applications/dashboard/scss/editor/_richEditor.scss

Original issue: https://github.com/vanilla/support/issues/83
Backport of #7675

Backport: Remove extra line break margins (2.7)

---

applications/dashboard/scss/_core-variables.scss
applications/dashboard/scss/compatibility/_mixins.scss
applications/dashboard/scss/embeds/_embedLink.scss
applications/dashboard/scss/embeds/_embedText.scss
applications/dashboard/scss/new-components/_authenticateUser.scss
applications/dashboard/scss/new-components/_formElements.scss
applications/dashboard/src/scripts/app/user-content/embeds/quote.tsx

- Fixed white space in SASS files
- Got rid of some mixins we don't need or use
- Added new core variables for KB

Minor refactoring and new variables for Knowledge

---

library/Garden/Controller.php
library/Garden/TwigTrait.php

Garden\Controller and Garden\TwigTrait are set (for Knowledgebase)
Fixes: #7682

New base controller empty class and TwigTrait initializer

---

applications/dashboard/scss/_core-variables.scss

New variables for fixing alignment of fonts with line height and added missing colour for visited links.

New variables for KB

---

applications/dashboard/controllers/class.messagecontroller.php

- Refresh page after adding/deleting messages, fixes #5549
- Start new messages auto-enabled, fixes #4546

Messages UI improvements

---

applications/dashboard/controllers/class.dbacontroller.php

Remove style.css from DbaController

---

applications/vanilla/controllers/class.discussioncontroller.php

fixes #5572 and is more in line with other actions that hightlight the item such as closing.

Change announcement dismiss animation to highlight

---

library/core/functions.render.php

The name checked for should match the function name.

Fix formatRssHtmlCustom function defined guard

---

library/Garden/StaticCacheConfigTrait.php
library/Garden/StaticCacheTrait.php
library/Garden/StaticCacheTranslationTrait.php

Implement static cache optimization
Like we discussed, I'll split optimization PR into pieces.
This is 1st part just to get Traits in
Relates to #7734 and to #7689

Add static cache traits to the project

---

composer.json
composer.lock

Updates our coding standard version.
https://github.com/vanilla/standards/releases/tag/1.3

Update vanilla standards version

---

.editorconfig
.travis.yml

Update our travis build scripts to:
- Parallelize our JS Build / Testing and PHP
- Run PHP 7.0, 7.1 jobs only daily (on the cron jobs only).

Test tweaked build matrix

---

applications/vanilla/models/class.categorymodel.php
library/Garden/Legacy/Deprecation.php
library/Vanilla/Utility/Deprecation.php
library/core/functions.general.php

Deprecation class implemented to log when deprecated function is called.
This implementation should allow to track if deprecated function is in use on production
First candidate to deprecate: translateContent()

Deprecation class implemented to log when deprecated function is called.

---

library/core/class.configuration.php
library/core/class.format.php
library/core/functions.general.php

PRs have been reviewed and approved by Todd on the release branches
https://github.com/vanilla/vanilla/pull/7777
https://github.com/vanilla/vanilla/pull/7782
https://github.com/vanilla/vanilla/pull/7783
Basically applying the option `allowed_classes => false`
http://php.net/manual/en/function.unserialize.php

Fix dbdecode and unserialize functions

---

library/database/class.database.php

Update class.database.php misspelling

---

library/database/class.databasestructure.php

speecifty -> specify
barackets -> brackets

Update class.databasestructure.php misspelling

---

composer.lock

- Updating vanilla/standards (v1.3.0 => v1.3.1)

Updating vanilla standards to 1.3.1

---

library/core/functions.deprecated.php

Final check on production to output to error log if any call
Fixes_: #7809
relates to: #7776

Deprecate safeParceStr 

---

library/core/class.configuration.php
library/core/class.format.php
library/core/functions.general.php

Backport: Fix dbdecode and unserialize functions (2.5)

---

library/core/class.configuration.php
library/core/class.format.php
library/core/functions.general.php

Backport: Fix dbdecode and unserialize functions (2.6)

---

library/core/class.configuration.php
library/core/class.format.php
library/core/functions.general.php

Backport: Fix dbdecode and unserialize functions (2.7)

---

composer.lock

Update composer( 2.5)

---

composer.lock

Update composer (2.6)

---

composer.lock

Update composer (2.7)

---

library/core/class.request.php

Revert static cache for url() of Gdn_Request
Fixes: #7844

Revert static cache for url() of Gdn_Request

---

library/core/class.request.php

Backport: Revert static cache for url() of Gdn_Request (2.7)

---

applications/dashboard/models/class.rolemodel.php

Backport: deleting role from userRole table after deleting a role (2.7)

---

applications/vanilla/models/class.categorymodel.php

Backport: Categories set allowdiscussions default to 1 (2.7)

---

library/setup/ComposerHelper.php

Backport fo #7870 
I'm not merging master because some other changes have landed in the meantime.

[2.8.dev.2]  Fix composer post-install always running code validation

---

library/core/functions.deprecated.php

Fixes_: #7811
Relates to : #7776

Deprecate parseUrl global function

---

library/core/functions.deprecated.php

Fixes_ #7813 
Relates to #7776

Deprecate formatDottedAssignment global function

---

library/core/class.format.php

Retaes to: #7734 and #7689
Fixes: #7815

Implement static cache translations trait on Gdn_Format

---

library/src/scripts/components/Sentence.tsx
library/src/scripts/components/dropdown/DropDown.tsx
plugins/rich-editor/src/scss/_richEditor.scss

Allows recursively adding child classes to sentence pieces;.
I also lumped in a fix for the Rich Editor's inline menu nub shadow.
Closes: https://github.com/vanilla/vanilla/issues/7893

Update Sentence component to allow recursive child classes

---

library/src/scripts/components/CloseButton.tsx
library/src/scripts/components/Icons.tsx
library/src/scripts/components/SmartAlign.tsx
library/src/scripts/components/frame/FrameHeader.tsx
library/src/scripts/components/modal/Modal.tsx
library/src/scripts/components/modal/ModalConfirm.tsx
library/src/scripts/components/modal/index.ts
library/src/scss/_coreVariables.scss

New Modal Dialogue component.
Also requires https://github.com/vanilla/knowledge/pull/200, instructions to test are there.

Added Modal Dialogue component

---

PULL_REQUEST_TEMPLATE.md

A quick checklist to review when starting a new PR. My intent isn't that this needs to be in every PR til the end of time, but it's a damn good reminder.

Add a PR template

---

CONTRIBUTING.md
README.md

Separate and improve our 'contributing' suggestions as per the GitHub community profile guidelines.

Separate Contributing section from README

---

library/src/scripts/components/DeviceChecker.tsx
library/src/scripts/components/dropdown/items/DropDownItemButton.tsx

These changes are for the KB. I added a new "device" to detect when there's not enough room for elements a bit out of the main margin like the back button.
I also fixed the styles for the buttons in the drop down components, there was an extra class that shouldn't be there.

Added new "device" to the device checker and Fixed styles for drop down component

---

library/Vanilla/Database/Operation/CurrentDateFieldProcessor.php
library/Vanilla/Database/Operation/CurrentUserFieldProcessor.php

This update introduces a small change to existing pipeline processors, allowing individual fields to be specified for database operations. This is done to allow models to add fields, removing fields or just plain change the casing of existing fields. It is achieved with basic setters and getters and a slightly modified `handle` method, which now allows multiple fields.
Prior usage should be unaffected, since we're keeping the same defaults. Existing tests should ensure nothing is *too* broken.

Make database pipeline processors more configurable

---

applications/vanilla/settings/class.hooks.php

Fix post counters on profile pages exceeding allotted area

---

library/src/scripts/TabHandler.ts
library/src/scripts/componentIDs.ts
library/src/scripts/components/Icons.tsx
library/src/scripts/components/forms/Button.tsx
library/src/scripts/components/siteNav/NavNode.tsx
library/src/scripts/components/siteNav/SiteNav.tsx
library/src/scripts/components/siteNav/SiteNavNode.tsx
library/src/scss/components/_siteNav.scss

Added new Site Nav component.
Notes: 
* For full accessibility spec see: https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-1/treeview-1a.html
* Some click handlers are on the SiteNav and some are on the SiteNavNode.

Add SiteNav component

---

applications/dashboard/scss/new-components/_selectBox.scss
library/src/scripts/components/Heading.tsx
library/src/scripts/components/Icons.tsx
library/src/scripts/components/PopoverController.tsx
library/src/scripts/components/SelectBox.tsx
library/src/scripts/components/dropdown/DropDown.tsx
library/src/scripts/components/dropdown/DropDownContents.tsx
library/src/scripts/components/dropdown/items/DropDownItemButton.tsx
library/src/scripts/components/forms/Button.tsx
library/src/scripts/components/siteNav/SiteNavNode.tsx
library/src/scss/_coreVariables.scss
plugins/rich-editor/src/scripts/components/popovers/EmbedPopover.tsx
plugins/rich-editor/src/scripts/components/popovers/EmojiPopover.tsx

Updates to dropdown and popover controller components. These changes are needed for the KB's selectbox component.

Updates to dropdown / popover controllers for KB

---

library/core/functions.general.php

Fixes type casting error introduced in [#7923](https://github.com/vanilla/vanilla/pull/7923)

Fix type casting (eventlog ipv6 compatibility)

---

applications/dashboard/scss/new-components/_formElements.scss
library/Vanilla/Formatting/Embeds/LinkEmbed.php
library/src/scripts/components/BackLink.tsx
library/src/scripts/components/Breadcrumb.tsx
library/src/scripts/components/Icons.tsx
library/src/scripts/components/SelectBox.tsx
library/src/scripts/components/dropdown/DropDown.tsx
library/src/scripts/components/siteNav/SiteNavNode.tsx
library/src/scripts/user-content/embeds/link.tsx
library/src/scss/_coreVariables.scss
library/src/scss/components/_siteNav.scss
library/src/scss/embeds/_embedGlobal.scss
library/src/scss/embeds/_embedLink.scss
library/src/scss/embeds/_embedQuote.scss
library/src/scss/embeds/_embedText.scss
library/src/scss/userContent/_codeBlocks.scss
plugins/rich-editor/src/scss/_richEditor.scss
plugins/rich-editor/src/scss/_richEditorForm.scss
plugins/rich-editor/src/scss/editor.scss
plugins/rich-editor/views/richeditorstyles/index.php
tests/Library/Vanilla/Formatting/Embeds/EmbedManagerTest.php

Style updates to BackLink, Breadcrumbs components and added styles for richEditorForm component. These updates are for the KB.

Style updates to BackLink, Breadcrumbs and added RichEditorForm component

---

plugins/rich-editor/src/scss/_richEditorForm.scss

Fixes height of "Rich Editor Form", currently only used for KB.

Fixed height of Rich Editor Form (only affects KB)

---

library/src/scss/_coreVariables.scss
plugins/rich-editor/src/scss/_richEditorForm.scss

Adjusted some spacing to match mockups and have sides of text in editor line up with article page. (KB only)
Requires: https://github.com/vanilla/knowledge/pull/225

Editor Form - Spacing adjustments (KB)

---

applications/vanilla/controllers/api/CategoriesApiController.php
library/Vanilla/Formatting/Quill/BlotGroup.php
library/Vanilla/Formatting/Quill/Blots/Lines/HeadingTerminatorBlot.php

Relates to: https://github.com/vanilla/knowledge/issues/77

Extend BlotGroup and HeadingTerminatorBlot to have internal reference

---

plugins/OpenID/class.lightopenid.php

Restrict cURL calls to http and https.

Harden cURL calls

---

library/src/scripts/components/Icons.tsx
library/src/scripts/components/PageHeading.tsx
library/src/scripts/components/forms/select/SearchBar.tsx
library/src/scripts/components/forms/select/SelectOne.tsx
library/src/scripts/components/forms/select/Tokens.tsx
library/src/scripts/components/forms/select/overwrites/multiValueRemove.tsx
library/src/scss/_coreVariables.scss
library/src/scss/components/_searchBar.scss
library/src/scss/components/_suggestedTextInput.scss
library/src/scss/components/_tokens.scss

Updates for KB, does not affect forum.

Refactored "BigInput" to "SearchBar", fixed issues with Token input

---

plugins/ProfileExtender/class.profileextender.plugin.php

This even is added to profile extender to allow for modules or plugins to hook in and modify the a users extended fields data or the extended fields themselves.
The use case for this is vanillaforums/advancedbionics#5

Profile Extender - add modify user fields event

---

library/src/scripts/components/Icons.tsx
library/src/scripts/components/attachments.ts
library/src/scss/_coreVariables.scss

Added new icons for attachments in KB. Note that I did some modifications to make them more accessible.
Also fixed the meta colour to respect accessibility standard for contrast.

Added new icons and modified existing ones for KB attachments

---

library/src/scss/components/_tabButtonList.scss

Required for https://github.com/vanilla/knowledge/pull/378

Renamed _tabList.scss to _tabButtonList.scss

---

library/src/scripts/components/VanillaHeader.tsx
library/src/scripts/components/forms/select/SearchBar.tsx
library/src/scripts/components/forms/select/overwrites.tsx
library/src/scripts/components/mebox/MeBox.tsx
library/src/scripts/components/mebox/pieces/CompactMeBox.tsx
library/src/scripts/components/mebox/pieces/CompactSearch.tsx
library/src/scripts/components/mebox/pieces/MeBoxDropDownItemList.tsx
library/src/scripts/components/mebox/pieces/MessagesContents.tsx
library/src/scripts/components/mebox/pieces/MessagesDropDown.tsx
library/src/scripts/components/mebox/pieces/NotificationsContents.tsx
library/src/scripts/components/mebox/pieces/NotificationsDropDown.tsx
library/src/scripts/components/mebox/pieces/NotificationsToggle.tsx
library/src/scripts/components/mebox/pieces/UserDropdown.tsx
library/src/scripts/components/mebox/pieces/UserDropdownContents.tsx
library/src/scripts/components/tabs/Tabs.tsx
library/src/scripts/components/tabs/pieces/TabButton.tsx
library/src/scripts/components/tabs/pieces/TabButtonList.tsx
library/src/scripts/components/tabs/pieces/TabPanel.tsx
library/src/scss/_coreVariables.scss
library/src/scss/components/_compactMeBox.scss
library/src/scss/components/_compactSearch.scss
library/src/scss/components/_searchBar.scss
library/src/scss/components/_suggestedTextInput.scss
library/src/scss/components/_tabButtonList.scss
library/src/scss/components/_tabList.scss
library/src/scss/components/_vanillaHeader.scss
library/src/scss/layouts/_frame.scss

Added content to compact me box content. Added new tab component.
@charrondev Note that I had another PR approved today for a lot of changes to the header/mebox. Let me know if you have feedback on that.
Closes: https://github.com/vanilla/knowledge/issues/340

Compact MeBox content

---

library/src/scripts/components/mebox/pieces/CompactMeBox.tsx
library/src/scss/_coreVariables.scss
library/src/scss/components/_compactMeBox.scss
library/src/scss/components/_vanillaHeader.scss
library/src/scss/layouts/_frame.scss

Fixed some styling issues in compactMeBox and frameHeader and frameFooter.

Bug fixes for frame header, footer and tabs

---

applications/dashboard/controllers/api/UsersApiController.php

- Remove permission check against /users/by-names api endpoint
Fixes: #8079

Remove permission check against /users/by-names api endpoint

---

applications/dashboard/models/ReflectionAction.php

Schemas the reference themselves can lead to infinite recursion when both generating swagger docs and also serializing them into JSON.
Note that this fix only works for a schema that directly references itself and not more complex cyclical references. Cyclical references are much more complex and we’d like to be able to get away from automatic swagger generation at some point.
Closes https://github.com/vanilla/knowledge/issues/267

Fix infinite recursion in swagger docs

---

library/src/scripts/components/headers/VanillaHeader.tsx
library/src/scripts/components/layouts/PanelLayout.tsx
library/src/scss/components/_navigationManager.scss
library/src/scss/components/_navigationManagerToolbar.scss
library/src/scss/components/_siteNav.scss
library/src/scss/layouts/_panelLayout.scss

These bugs are to match the mockup more closely. KB only.

Fixed style bugs navigation manager

---

library/src/scripts/@types/utils.ts
library/src/scripts/contexts/DeviceContext.tsx
library/src/scripts/contexts/PagesContext.tsx
library/src/scripts/contexts/SearchContext.tsx
library/src/scripts/contexts/TabContext.tsx

This utility better describes what is actually being done in our contexts on the javascript side. The in-code documentation here should be sufficient.

Add optionalize utility type

---

plugins/rich-editor/src/scripts/quill/SyntaxModule.ts

Previously we were working around quill stealing our focus back on a code highlight by just placing back the focus, however this would cause the documents scroll position to jump particularly when something like an embed was focused.
I've updated the implementation to fully override the parent instead and check that our text had focus as well as a previous selection here so that we don't cause this jumping.

Fix scroll jumping when highlighting code

---

applications/dashboard/views/entry/signin.php

Closes https://github.com/vanilla/vanilla/issues/4264

Add extra CSS class for remember password

---

library/src/scripts/dom.ts
library/src/scss/layouts/_frame.scss
plugins/rich-editor/src/scss/_richEditor.scss

Few fixes:
- Fixed emoji test for latest Chrome version
- Fixed overflow issue in Rich Editor
- Fixed title alignment in revision mobile dropdown
Closes https://github.com/vanilla/vanilla/issues/8155

Fix emoji test, overflow issue in Rich Editor and title alignment

---

library/Garden/TwigTrait.php
library/Vanilla/Web/LegacyTwigViewHandler.php

I'm realizing I had a few commits missing from https://github.com/vanilla/vanilla/pull/8178
Here I'm
- Adding a couple of twig utility functions.
- Updating the TwigViewRenderer to use a single instance of the twig environment instead of recreating it every render.

Improve legacy twig view handler

---

.github/ISSUE_TEMPLATE/ask_a_question.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/new_feature.md

This PR adds 2 new issue templates in the `.github` directory. There are for:
1. Adding a feature request. This should help R&D ensure information is put into new feature issue before they are implemented.
2. A second one to redirect questions away from the issue tracker and towards the open source forum.

Add new issues templates

---

applications/vanilla/controllers/class.postcontroller.php
applications/vanilla/models/class.discussionmodel.php

backporting [#7724](https://github.com/vanilla/vanilla/pull/7724)

Backport: Fix inability to reference HTML tags in discussion titles (2.8.dev.6)

---

.gitignore
README.md
build/README.md

Closes https://github.com/vanilla/vanilla/issues/8235
**Final Logo**

Revamp README

---

library/src/scripts/components/NavLinks.tsx
library/src/scripts/components/NavLinksWithHeadings.tsx
library/src/scripts/components/layouts/components/WidgetContainer.tsx
library/src/scripts/components/navigation/SmartLink.tsx
library/src/scss/components/_navLinks.scss
library/src/scss/components/_subcommunityList.scss
library/src/scss/layouts/_widgetContainer.scss

Goes with https://github.com/vanilla/knowledge/pull/594
New components for KB's Help Centre home page.

Add components for KB's Help Centre Home Page

---

library/src/scripts/components/mebox/pieces/HeaderLogo.tsx
library/src/scripts/components/mebox/state/dummyLogoData.ts
library/src/scss/components/_subcommunityTile.scss
library/src/scss/components/_vanillaHeader.scss
library/src/scss/components/_vanillaHeaderNav.scss
library/src/scss/mixins/_mixin.shadows.scss
plugins/rich-editor/src/scss/_richEditor.scss

- Fixed focus/hover states in Vanilla header
- Added stronger shadow on subcommunity tiles when they're hovered
- Fixed z-index issue where the bottom border or the rich editor toolbar was getting cut off when you scrolled the content.

Feedback from Demo - Hover on subcommunity links, header state updates and fix for border on editor

---

library/src/scripts/user-content/code.ts
library/src/scripts/user-content/index.ts
plugins/rich-editor/src/scripts/quill/blots/blocks/CodeBlockBlot.ts

Closes https://github.com/vanilla/knowledge/issues/626

Fix syntax highlighting issues with rich editor.

---

plugins/rich-editor/addon.json

Backport of #8310 

---

plugins/rich-editor/addon.json

Modified richeditor addon.json

---

themes/keystone/addon.json

Update the addon.json to set "hidden" to false.

Fix keystone visibility issue.

---

themes/keystone/addon.json

Fix keystone visibility issue.

Backport 8322

---

package.json
yarn.lock

Closes https://github.com/vanilla/vanilla/issues/8327
This PR will add the Sinon 7.2.3 package (up from 6.3.5) to fix a dependancy problem that was killing our build.

Update the Sinon JS package to fix dependancy problem.

---

themes/keystone/class.keystone.themehooks.php
themes/keystone/views/default.master.tpl

Fix Keystone Advanced Search fatal error

---

package.json
yarn.lock

Backport: Update the Sinon JS package to fix dependancy problem(2.8)

---

themes/keystone/class.keystone.themehooks.php
themes/keystone/views/default.master.tpl

Backport: Fix Keystone Advanced Search fatal error (2.8)

---

applications/dashboard/controllers/api/UsersApiController.php

Backport: Fix users/me endpoint for Admin=2 users (2.8)

---

environment.php

Backport: Update application version to 2.8

---

applications/vanilla/controllers/class.postcontroller.php

Backport: EditDiscussions - Check if the FormValues are set (2.8)

---

applications/vanilla/models/class.commentmodel.php

reverts [#460](https://github.com/vanilla/vanilla-patches/pull/460)

Fix comment edit permission

---

applications/vanilla/models/class.commentmodel.php

Backport: fix comment edit permission (2.8)

---

applications/dashboard/settings/structure.php
library/Vanilla/Models/ReactionModel.php

Add foundation for reactions

---

library/src/scripts/components/ButtonLoader.tsx
library/src/scripts/components/IndependentSearch.tsx
library/src/scripts/components/forms/select/SearchBar.tsx
library/src/scripts/components/headers/VanillaHeader.tsx
library/src/scripts/components/headers/VanillaHeaderNav.tsx
library/src/scripts/components/layouts/PanelLayout.tsx
library/src/scripts/components/modal/ModalConfirm.tsx
library/src/scripts/components/radioButtonsAsTabs/RadioButtonTab.tsx
library/src/scripts/components/siteNav/SiteNav.tsx
library/src/scripts/components/splash/Splash.tsx
library/src/scripts/styles/buttonStyles.ts
library/src/scripts/styles/globalStyleVars.ts
library/src/scripts/styles/mobileDropDownStyles.ts
library/src/scripts/styles/searchStyles.ts
library/src/scripts/styles/styleHelpers.ts
library/src/scripts/styles/vanillaHeaderStyles.ts
library/src/scss/_coreVariables.scss
library/src/scss/components/_searchBar.scss
library/src/scss/layouts/_panelLayout.scss
yarn.lock

These updates are for the KB.
- Updated button loader to get styles from JS
- Fixed search size for both the home page and for the search page (should be 40px high)
- Display search icon in mebox even if we're on the search page
- Fixed overflow issue with breadcrumbs
For: https://github.com/vanilla/knowledge/pull/674

Feedback from demo

---

library/src/scripts/components/icons/common.tsx
library/src/scripts/components/nextPrevious/AdjacentLink.tsx
library/src/scripts/components/nextPrevious/NextPrevious.tsx
library/src/scss/layouts/_panelLayout.scss
library/src/scss/layouts/_panelWidget.scss
plugins/rich-editor/src/scss/_richEditor.scss

This component is meant to be used on mobile on KB articles. They're simple Links to the next and the previous article.
To test, see https://github.com/vanilla/knowledge/pull/694

Add NextPrevious component 

---

plugins/VanillaInThisDiscussion/class.inthisdiscussionmodule.php

Closes #8403
VanillaInThisDiscussion query isn't well formatted if mysql strict mode is enabled.

Fix mysql strict mode error by update sql query

---

applications/conversations/js/conversations.js
applications/dashboard/js/activity.js

Closes https://github.com/vanilla/vanilla/issues/8413
Most information is in the issue.
I've applied the same fix that was applied for the comments box on discussions.

Fix clearing of rich editor for conversations and activity

---

applications/dashboard/controllers/class.notificationscontroller.php

Closes https://github.com/vanilla/vanilla/issues/7678
There were 2 issues:
- We were using the wrong method for formatting an excerpt. The code here may have pre-dated the excerpt method.
- We were not passing the format to use.

Fix Rich notification formatting

---

library/src/scripts/apiv2.ts

Closes https://github.com/vanilla/support/issues/244

Make APIv2 upload file check extension case insensitively

---

applications/dashboard/js/dashboard.js
applications/dashboard/js/src/main.js

https://github.com/vanilla/vanilla/pull/8481 was accidentally added to the built file not the source file. I've applied the same change to the source file and rebuilt the dashboard JS.

Fix wrong source location for dashboard event change

---

environment.php

Update build number to 2019.004

---

library/src/scripts/styles/searchBarStyles.ts

Fix for height of search button in Splash of KB home page.

Fixed height of button on splash component search

---

library/src/scripts/components/ButtonLoader.tsx
library/src/scripts/components/IndependentSearch.tsx
library/src/scripts/components/forms/select/SearchBar.tsx
library/src/scripts/components/mebox/pieces/MessagesContents.tsx
library/src/scripts/components/mebox/pieces/NotificationsContents.tsx
library/src/scripts/components/splash/Splash.tsx
library/src/scripts/styles/buttonStyles.ts
library/src/scripts/styles/dropDownStyles.ts
library/src/scripts/styles/frameStyles.ts
library/src/scripts/styles/globalStyleVars.ts
library/src/scripts/styles/searchResultsStyles.ts
library/src/scripts/styles/splashStyles.ts
library/src/scripts/styles/styleHelpers.ts
plugins/rich-editor/src/scripts/components/popovers/EmbedPopover.tsx

Converted styles from CSS to JS, mainly for buttons, loaders, and search results (which are also used for categories)

CSS to JS - loader, buttons, search results

---

README.md
environment.php

Bump the release number to 2.8.1

Increment 2.8.1 release number

---

library/src/scripts/forms/buttonStyles.ts
library/src/scripts/navigation/CloseButton.tsx
plugins/rich-editor/src/scripts/flyouts/pieces/Flyout.tsx
plugins/rich-editor/src/scripts/toolbars/inlineToolbarClasses.ts
plugins/rich-editor/src/scripts/toolbars/pieces/InlineToolbarLinkInput.tsx
plugins/rich-editor/src/scripts/toolbars/pieces/ToolbarContainer.tsx
plugins/rich-editor/src/scripts/toolbars/pieces/ToolbarPositioner.tsx

Backport https://github.com/vanilla/vanilla/pull/8549

Backport: Fix toolbar positioning in rich editor

---

README.md
environment.php

Increment version number in the environment and in the README.

Bump the version number

---

library/Vanilla/Sitemap/Robots.php
library/Vanilla/Web/Robots.php

Moved from: https://github.com/vanilla/addons/pull/695
Relates to: https://github.com/vanilla/knowledge/pull/776

Move Robots class to core

---

environment.php

Update build number to 2019.005

---

composer.json
composer.lock
conf/constants.php
environment.php

Upgrade the feature requirements and checks to 7.1. I updated the composer.lock, but didn't update any dependencies.

Upgrade PHP version requirements to 7.1

---

plugins/rich-editor/src/scripts/editor/Editor.tsx

The `Editor` component has been updated to allow for a queue of operations to be handed down to it. This is done to allow external submission of Quill operations, without the need to expose the component's Quill instance, itself.
1. Add `operationsQueue` property to the `Editor` component. This is an array of either strings or `DeltaOperation` items. When the component is updated, this queue will be processed.
1. Add `clearOperationsQueue` property to the `Editor` component. This is a function that will be called when the queue has been processed. It can be used to reset the external queue data source.

Add operations queue support to Rich Editor

---

plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenuBar.tsx
plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenusBarToggle.tsx
plugins/rich-editor/src/scripts/menuBar/paragraph/formats/formatting.ts
plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuListsTabContent.tsx
plugins/rich-editor/src/scripts/quill/blots/blocks/ListBlot.ts

Closes https://github.com/vanilla/vanilla/issues/8595

Add support for indent and outdent indicator disabling

---

applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/openapi/categories.yml

Extend  categories/search api when "expand"
to add breadcrumbs data
Closes: #8496

Add  expanding breadcrumbs to categories API search

---

applications/vanilla/views/vanillasettings/posting.php

Fix a typo I found while doing a customization for a client.

fix typo on posting page

---

applications/dashboard/controllers/TickApiController.php
applications/dashboard/openapi/tick.yml

- Add new TickApiController to register basic pageviews
- Add openapi spec yml file for tick endpoint
Closes: https://github.com/vanilla/knowledge/issues/83

Add tick API v2 resource for collecting page view stats

---

library/src/scripts/icons/common.tsx

Closes: https://github.com/vanilla/knowledge/issues/660

Update newFolder svg function

---

bootstrap.php
conf/config-defaults.php
library/Vanilla/Web/Asset/WebpackAssetProvider.php
library/Vanilla/Web/Asset/WebpackContentSecurityPolicyProvider.php
library/Vanilla/Web/ContentSecurityPolicy/ContentSecurityPolicyModel.php
library/Vanilla/Web/ContentSecurityPolicy/ContentSecurityPolicyProviderInterface.php
library/Vanilla/Web/ContentSecurityPolicy/DefaultContentSecurityPolicyProvider.php
library/Vanilla/Web/ContentSecurityPolicy/EmbedWhitelistContentSecurityPolicyProvider.php
library/Vanilla/Web/ContentSecurityPolicy/Policy.php
library/Vanilla/Web/ContentSecurityPolicyMiddleware.php
library/Vanilla/Web/Page.php
library/Vanilla/Web/ThemedPage.php
resources/views/default-master.twig

Relates to: #vanilla/knowledge/issues/132

Implement script content security policy for new pages

---

library/src/scripts/forms/buttonStyles.ts
library/src/scripts/forms/checkRadioStyles.ts
library/src/scripts/forms/radioTabs/radioTabStyles.ts
library/src/scripts/layout/bodyStyles.ts
library/src/scripts/layout/frame/frameStyles.ts
library/src/scripts/navigation/siteNavAdminLinksStyles.ts
library/src/scripts/styles/styleHelpers.ts
plugins/rich-editor/src/scripts/editor/pieces/EditorUploadButton.tsx
plugins/rich-editor/src/scripts/editor/pieces/IconForButtonWrap.tsx
plugins/rich-editor/src/scripts/editor/richEditorClasses.ts
plugins/rich-editor/src/scripts/editor/richEditorFormClasses.ts
plugins/rich-editor/src/scripts/editor/richEditorVariables.ts
plugins/rich-editor/src/scripts/flyouts/EmbedFlyout.tsx
plugins/rich-editor/src/scripts/flyouts/EmojiFlyout.tsx
plugins/rich-editor/src/scripts/flyouts/pieces/EmojiGroupButton.tsx
plugins/rich-editor/src/scripts/flyouts/pieces/EmojiPicker.tsx
plugins/rich-editor/src/scripts/flyouts/pieces/Flyout.tsx
plugins/rich-editor/src/scripts/flyouts/pieces/flyoutClasses.ts
plugins/rich-editor/src/scripts/flyouts/pieces/insertEmojiClasses.ts
plugins/rich-editor/src/scripts/flyouts/pieces/insertMediaClasses.ts
plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenusBarToggle.tsx
plugins/rich-editor/src/scripts/menuBar/paragraph/paragraphMenuBarStyles.ts
plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuBarTab.tsx
plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuResetTab.tsx
plugins/rich-editor/src/scripts/toolbars/pieces/MenuItem.tsx

This is has the rest of the style updates to consistency (first pass) We will do more next sprint through QA.
Closes: https://github.com/vanilla/knowledge/issues/826

UI Updates (mostly states) to match latest mockups

---

library/src/scripts/content/embeds/quote.tsx
library/src/scripts/flyouts/DropDown.tsx
library/src/scripts/flyouts/dropDownStyles.ts
library/src/scripts/headers/pieces/MobileDropDown.tsx
library/src/scripts/layout/frame/FrameHeader.tsx
library/src/scripts/layout/frame/frameStyles.ts
plugins/rich-editor/src/scripts/editor/EditorEmbedBar.tsx
plugins/rich-editor/src/scripts/flyouts/EmbedFlyout.tsx
plugins/rich-editor/src/scripts/flyouts/pieces/flyoutPosition.ts
plugins/rich-editor/src/scripts/flyouts/pieces/insertMediaClasses.ts

Converted insert media dropdown to use more modern components
Closes: https://github.com/vanilla/knowledge/issues/820

Converted insert media dropdown to use more modern components

---

library/src/scripts/flyouts/DropDown.tsx
library/src/scripts/forms/buttonStyles.ts
plugins/rich-editor/src/scripts/flyouts/EmbedFlyout.tsx

Followup of https://github.com/vanilla/vanilla/pull/8672
Fixes the styles of the buttons in that modal while viewing from the forum.

Fix button styles in forum modal

---

plugins/googlesignin/README.md

This PR adds documentation for Google Sign In feature.
This closes https://github.com/vanilla/vanilla/issues/8644

Add README to Google Sign in.

---

library/src/scripts/navigation/NextPrevious.tsx
library/src/scripts/navigation/nextPreviousStyles.tsx

Refactored next/prev component since it didn't follow the conventions I want for styling. 
Although not critical, I want to use it as an example of a simple component for a demo, so I refactored it.

Refactored next/previous component to follow style standards

---

applications/vanilla/controllers/class.categorycontroller.php

backporting https://github.com/vanilla/vanilla/pull/8705

Backport: Fix permission when following a category (2019.005)

---

library/src/scripts/forms/buttonStyles.ts

Fixed border color on hover to match mockups
For: https://github.com/vanilla/knowledge/issues/872

Fixed primary button border color on hover

---

environment.php

 Update build version to 2019.006

---

plugins/ProfileExtender/views/helper_functions.php

Just guessing it's necessary to translate field labels everywhere including profile section.
I just wrapped label with `t` function.

[ProfileExtender] Translate field label with locale definition

---

library/core/class.thememanager.php

Closes https://github.com/vanilla/vanilla/issues/8697

Have theme manager instantiate plugin through the container

---

library/src/scripts/splash/Splash.tsx
library/src/scripts/splash/splashStyles.ts

The `Splash` component needs a default title. Now, it has one.

Add default title for Splash component

---

library/src/scripts/content/attachments/attachmentStyles.ts
library/src/scripts/features/search/IndependentSearch.tsx
library/src/scripts/features/search/SearchBar.tsx
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/forms/Button.tsx
library/src/scripts/forms/buttonStyles.ts
library/src/scripts/forms/inputStyles.tsx
library/src/scripts/headers/vanillaHeaderStyles.ts
library/src/scripts/splash/Splash.tsx
library/src/scripts/splash/splashStyles.ts
library/src/scripts/styles/globalStyleVars.ts
library/src/scripts/styles/styleHelpers.ts

Style update and fixes for the "splash" component.
Fixes issues listed in : https://github.com/vanilla/knowledge/issues/801

Splash style update and fixes

---

library/src/scripts/splash/splashStyles.ts

Fixed broken build: put back missing default value for splash text.

Added back default value for Splash text

---

library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/TitleBarHome.tsx
library/src/scripts/headers/mebox/pieces/CompactMeBox.tsx
library/src/scripts/headers/mebox/pieces/CompactSearch.tsx
library/src/scripts/headers/mebox/pieces/HeaderLogo.tsx
library/src/scripts/headers/mebox/pieces/MeBoxDropDownItemList.tsx
library/src/scripts/headers/mebox/pieces/MessagesDropDown.tsx
library/src/scripts/headers/mebox/pieces/NotificationsDropDown.tsx
library/src/scripts/headers/mebox/pieces/TitleBarListItem.tsx
library/src/scripts/headers/mebox/pieces/TitleBarNav.tsx
library/src/scripts/headers/mebox/pieces/TitleBarNavItem.tsx
library/src/scripts/headers/mebox/pieces/UserDropdown.tsx
library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
library/src/scripts/headers/mebox/pieces/meBoxStyles.ts
library/src/scripts/headers/pieces/TitleBarMobileHome.tsx
library/src/scripts/headers/pieces/mobileDropDownStyles.ts
library/src/scripts/headers/titleBarNavStyles.ts
library/src/scripts/headers/titleBarStyles.ts
library/src/scripts/layout/PanelLayout.tsx
library/src/scripts/messages/messageStyles.ts
library/src/scripts/modal/modalStyles.ts
library/src/scripts/routing/links/backLinkStyles.ts
plugins/rich-editor/src/scripts/editor/richEditorFormClasses.ts
resources/views/default-master.twig

Renamed all instances of "VanillaHeader" to "TitleBar".
For: https://github.com/vanilla/knowledge/issues/863
Please review and merge ASAP, as it touches a lot of files.

Renamed "VanillaHeader" to "TitleBar"

---

library/src/scripts/content/attachments/AttachmentIcons.tsx
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/mebox/pieces/MessagesCount.tsx
library/src/scripts/headers/mebox/pieces/NotificationsCount.tsx
library/src/scripts/modal/ModalConfirm.tsx
library/src/scripts/splash/Splash.tsx

Update some translation keys to align with core

---

applications/vanilla/models/class.discussionmodel.php

This fires the beforeGetAnnouncements the DiscussionModel::getAnnouncements method.

Add beforeGetAnnouncements event to DiscussionModel

---

applications/vanilla/models/class.discussionmodel.php

Backport: Add before get announcement event(release/2019.005)

---

library/src/scripts/navigation/nextPreviousStyles.tsx

Fixed up variables to conform with styling standard.

Update variable usage in nextPreviousStyles

---

library/src/scripts/navigation/nextPreviousStyles.tsx

Renamed the key for the component.

Renamed key for NextPrevious component

---

applications/dashboard/controllers/class.entrycontroller.php

Fixed Spelling Mistake in passwordRequest() should be Username instead of Usermame
Please make sure these points are completed:

Fixed Spelling Mistake in entryController

---

plugins/ProfileExtender/class.profileextender.plugin.php
plugins/ProfileExtender/views/addedit.php

https://github.com/vanilla/vanilla/pull/8745

Backport: Add Salesforce integration(release/2019.006)

---

library/src/scripts/messages/Message.tsx

For https://github.com/vanilla/knowledge/pull/975

KB Added container component to max out the width of the banner

---

library/src/scripts/content/attachments/AttachmentIcons.tsx
library/src/scripts/features/search/SearchBar.tsx
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/features/search/searchStyles.ts
library/src/scripts/flyouts/DropDown.tsx
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/mebox/pieces/CompactSearch.tsx
library/src/scripts/headers/mebox/pieces/MessagesCount.tsx
library/src/scripts/headers/mebox/pieces/NotificationsCount.tsx
library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
library/src/scripts/headers/pieces/mobileDropDownStyles.ts
library/src/scripts/headers/titleBarStyles.ts
library/src/scripts/layout/Heading.tsx
library/src/scripts/layout/PanelLayout.tsx
library/src/scripts/splash/Splash.tsx
plugins/rich-editor/src/scripts/editor/context.tsx

Fixed alignment of the search in the titleBar.
Closes: https://github.com/vanilla/knowledge/issues/950

Fixed alignment of search in titleBar

---

library/src/scripts/flyouts/DropDown.tsx
library/src/scripts/forms/buttonStyles.ts

Most of the feedback in https://github.com/vanilla/knowledge/issues/915 has been addressed. This PR fixes the last problems. Most notably:
- Hover/focus color for "Publish" button
- Hover color for menu (the "..." menu in the editor header)
Companion PR: https://github.com/vanilla/knowledge/pull/991

KB Editor Header - Design feedback on hover/focus states

---

tests/APIv2/CounterProvidersTest.php
tests/Library/Core/CounterProvidersTest.php

Add CounterProviders tests

---

library/src/scripts/layout/pageHeadingStyles.tsx
library/src/scripts/routing/links/backLinkStyles.ts

Found some positioning bugs for back link in article and in editor header.

Fixed styling for back link in article and in editor

---

applications/vanilla/models/class.discussionmodel.php

https://github.com/vanilla/vanilla/pull/8770

Backport #8770 to release/2019.006

---

applications/vanilla/views/discussion/embed.php
applications/vanilla/views/discussion/helper_functions.php
plugins/rich-editor/RichEditorPlugin.php

https://github.com/vanilla/vanilla/pull/8767

Backport #8767 [release/3.0]

---

applications/vanilla/views/discussion/embed.php
applications/vanilla/views/discussion/helper_functions.php
plugins/rich-editor/RichEditorPlugin.php

https://github.com/vanilla/vanilla/pull/8767

Backport #8767 [release/2019.006]

---

applications/conversations/openapi/conversations.yml
applications/conversations/openapi/messages.yml
applications/dashboard/openapi/drafts.yml
applications/dashboard/openapi/notifications.yml
applications/dashboard/openapi/parameters.yml
applications/dashboard/openapi/search.yml
applications/dashboard/openapi/users.yml
applications/vanilla/openapi/categories.yml
applications/vanilla/openapi/comments.yml
applications/vanilla/openapi/discussions.yml

- Fix typo in pagination and move to a component.
- Remove HTML tags. OpenAPI expects pure Markdown.
- Create components for `dateInserted` and `dateUpdated` parameters.
- Remove some duplicate `x-addon` properties.

Fix some OpenAPI docs

---

applications/dashboard/controllers/class.entrycontroller.php
library/core/class.passwordhash.php
library/core/class.sanitizeduserexception.php

This PR will rename an exception class that was created in [#8859](https://github.com/vanilla/vanilla/pull/8859)

Update exception class name

---

composer.json
composer.lock

Backport https://github.com/vanilla/vanilla/pull/8893

Backport update composer dependencies

---

composer.json
composer.lock
library/Vanilla/PageScraper.php
tests/Library/Vanilla/PageScraperTest.php
tests/fixtures/src/PageScraper.php

Backport https://github.com/vanilla/vanilla/pull/8899

Backport Rollback garden-http to v1 [2019.006] 

---

bin/scripts/buildRelease.js
build/build.xml
build/package-exclude.txt
composer.lock
library/Vanilla/PageScraper.php
tests/Library/Vanilla/PageScraperTest.php
tests/fixtures/src/PageScraper.php

- Backport build fixes (so that I can do a proper 2.8 build with correct file permissions). https://github.com/vanilla/vanilla/pull/8888
- Backport garden-http 1.1.4 https://github.com/vanilla/vanilla/pull/8899

Backport multiple fixes to 2.8

---

environment.php

This PR is preparing for the final 3.0 release.
I'm setting to the version to 3.0 directly.

Finalize 3.0 version

---

.gitignore
plugins/emojiextender/EmojiExtenderPlugin.php
plugins/emojiextender/addon.json

Backport https://github.com/vanilla/vanilla/pull/8910

Backport emoji picker fixes [3.0]

---

.gitignore
plugins/emojiextender/EmojiExtenderPlugin.php
plugins/emojiextender/addon.json

Backport https://github.com/vanilla/vanilla/pull/8910 to 2019.007

Backport Fix some case sensitivity issues with emoji extender [2019.007]

---

library/src/scripts/headers/titleBarStyles.ts

Fixes regression bug of vertical position of me box flyouts in KB.
Original issue: (https://github.com/vanilla/knowledge/issues/897).
Closes: https://github.com/vanilla/knowledge/issues/1033

KB: Fixed me box flyout vertical position

---

environment.php

I'm doing a 3.0.1 with https://github.com/vanilla/vanilla/pull/8926

Bump 3.0 release version number

---

applications/dashboard/views/settings/security.php

These are a result of preparing a PR against the locales repo. Sorry for the nitpicks.

More security warning pages

---

library/core/class.oauth2.php

This PR will fix compatibility issues with subclasses of Gdn_OAuth2.

Remove type hinting in Authorize URI

---

library/core/class.oauth2.php

Fix incompatibility with OAuth2 base class.

Backport: Fix incompatibility with OAuth2 base class.

---

plugins/editor/class.editor.plugin.php

Fixes https://github.com/vanilla/vanilla/issues/8858
Upload file FIX for non-windows hosting. https://open.vanillaforums.com/discussion/comment/257089/#Comment_257089
Fixes the error "You are not allowed to upload files in this category." on linux-based webhosts.

FIX file upload error - Update class.editor.plugin.php

---

library/Vanilla/Addon.php

It's = "It Is"
Its = possessive
Here, we want the latter.

Fix grammar of addon cache notice

---

applications/dashboard/modules/class.userinfomodule.php
applications/dashboard/views/modules/userinfo.php

Users should be able to see their own email address when they are viewing their own profile.

Allow users to view their own email address on their profile pages

---

package.json
packages/README.md
packages/vanilla-babel-preset/package.json
packages/vanilla-polyfill/package.json
packages/vanilla-prettier-config/package.json
packages/vanilla-tsconfig/package.json
packages/vanilla-utils/package.json

Add publishing instructions for `@vanilla` modules.
See container README.

Publish packages to NPM and add README for it.

---

library/core/class.oauth2.php

related [#464](https://github.com/vanilla/support/issues/464)

Oauth2: OIDC compliance: set OIDC values in structure method

---

README.md
environment.php

Hold in preparation for the 3.1 release.

Bump some versions for 3.1-2019.009

---

library/Vanilla/EmbeddedContent/Embeds/FileEmbed.twig
library/src/scripts/embeddedContent/VideoEmbed.tsx

- Fixes an issue where video iframes would be invisible after being clicked (simple HTML nesting problem).
- Fixes an issue where attachments would be created inside of an existing link instead of replacing it (simple HTML nesting problem).

Fix a couple issues with the new embed system

---

library/Vanilla/Formatting/Quill/Blots/Lines/SpoilerLineTerminatorBlot.php
library/src/scripts/content/UserContent.story.tsx
plugins/rich-editor/src/scripts/quill/components/SpoilerButton.tsx
tests/fixtures/formats/rich/html/all-blocks/output-client.html
tests/fixtures/formats/rich/html/all-blocks/output.html
tests/fixtures/formats/rich/html/spoiler/output.html

As per https://github.com/vanilla/vanilla/issues/8450, add title on spoiler toggle button.

Added title attribute to spoiler button

---

library/src/scripts/flyouts/FlyoutToggle.tsx
library/src/scripts/routing/DocumentTitle.tsx

Closes https://github.com/vanilla/support/issues/584
Backports 2 performance fixes from https://github.com/vanilla/vanilla/pull/9051

Backport editor performance fixes

---

plugins/rich-editor/src/scripts/editor/richEditorClasses.ts
plugins/rich-editor/src/scripts/quill/KeyboardBindings.ts
plugins/rich-editor/src/scripts/quill/MarkdownModule.ts
plugins/rich-editor/src/scripts/quill/NewLineClickInsertionModule.test.ts
plugins/rich-editor/src/scripts/quill/NewLineClickInsertionModule.ts
plugins/rich-editor/src/scripts/quill/VanillaTheme.ts

Closes https://github.com/vanilla/vanilla/issues/7597
- Adds new line on click, when clicked below quoted/attached content

Add newline to bottom of editor on click

---

.travis.yml
library/Vanilla/Utility/HtmlParserTrait.php

- There is a broken build that I am attempting to fix.
- I am also updating our builds to our minimum supported version and our infrastructure version. It seems as though most builds break on the minimum version so it should be tested more frequently.

Fix the build and switch build cron versions

---

library/src/scripts/features/search/searchResultsStyles.ts
library/src/scripts/styles/globalStyleVars.ts

-fixed line height to the specs height 1.4 
-upd global var excerpt 
Closes: https://github.com/vanilla/knowledge/issues/957

Set result line height to requirements specs

---

applications/dashboard/views/role/index.php

Closes https://github.com/vanilla/vanilla-patches/issues/394.

Escape output fields on the roles page

---

library/src/scripts/content/hashScrolling.ts
library/src/scripts/layout/ScrollOffsetContext.tsx

Backport of https://github.com/vanilla/vanilla/pull/9112
Requested by sales for public cloud.

Backport: Fix changing window hash causing infinite loop

---

plugins/rich-editor/src/scripts/editor/richEditorClasses.ts

Adds hover state for the icons in the editor.

Adds a hover state on icons in editor for the kb and forum

---

library/Vanilla/Models/FsThemeProvider.php

Implement `getDefaultAssets()` method if Theme does not have any assets yet.
Refactor `getFileAsset()` function to get asset as an argument instead of assetKey
and to use `asset['placeholder']` if provided by asset instead of trying to find real file with filename.
Closes: https://github.com/vanilla/knowledge/issues/1051

Refactor FsThemeProvider to deliver missing variables.json asset

---

library/src/scripts/layout/frame/frameStyles.ts

Fixes https://github.com/vanilla/knowledge/issues/1117
Re: https://bugs.chromium.org/p/chromium/issues/detail?id=927066

Fix overflow scrolling inside of a frame

---

library/src/scripts/headers/pieces/MobileDropDown.tsx
library/src/scripts/headers/pieces/mobileDropDownStyles.ts
library/src/scripts/icons/common.tsx
library/src/scripts/modal/modalStyles.ts

Closes https://github.com/vanilla/knowledge/issues/951
Required Companion https://github.com/vanilla/knowledge/pull/1122
New Mockups https://zpl.io/2ZL6on1
- Implements update mobile dropdown style.
- Adds new icon variation `<UpTriangleIcon />
- This change affects the mobiledropdown, most easily seen in the mobile revisions page and mobile navigation for KB.

Implement new Mobile Dropdown Style.

---

library/src/scripts/embeddedContent/Search.story.tsx
library/src/scripts/embeddedContent/StoryExampleModal.tsx
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts

Fixed label in storybook for modal with input text
Fixed hover of independent search and added background for storybook so we can see the borders better.
Closes: https://github.com/vanilla/knowledge/issues/1128

Fixed independent search

---

library/core/class.bbcode.php
library/core/class.emoji.php

Backport https://github.com/vanilla/vanilla/pull/9180

Backport - Fix missing event args

---

library/Vanilla/Web/Asset/DeploymentCacheBuster.php
tests/Library/Vanilla/Web/Asset/DeploymentCacheBusterTest.php

Backport "Remove grace period from the deployment cache buster"

---

applications/dashboard/js/entry.js
cache/.htaccess
library/core/class.dispatcher.php

backports https://github.com/vanilla/vanilla/pull/9207

Backport: Fix user availability search not working on connect registration (release/2019.011)

---

applications/dashboard/library/class.emailtemplate.php

backporting https://github.com/vanilla/vanilla/pull/9204

Backport: Fix plain text emails rendering with HTML tags(2019.011)

---

library/src/scripts/icons/iconClasses.ts
library/src/scripts/navigation/Breadcrumb.tsx
library/src/scripts/navigation/Breadcrumbs.tsx
library/src/scripts/navigation/LocationBreadcrumbs.tsx
library/src/scripts/navigation/breadcrumbs.story.tsx
library/src/scripts/navigation/breadcrumbsStyles.ts

Adds breadcrumbs to storybook and converted styles to JS.
Companion PR: https://github.com/vanilla/knowledge/pull/1170

Added breadcrumbs to storybook and converted styles to JS

---

applications/conversations/views/messages/conversations.php
applications/conversations/views/messages/popin.php

Fixes https://github.com/vanilla/vanilla/issues/9241
We were double encoding in some of these views.

Fix double HTML encoding in messages

---

index.php

Remove E_WARNING from error reporting

---

applications/dashboard/models/class.activitymodel.php
library/core/class.email.php

backporting https://github.com/vanilla/vanilla/pull/9270

Backport: Add email logging (release 2019.012)

---

tests/Library/Core/ArrayTranslateTest.php

Add a test to make sure that arrays translate.

Create tests to ensure that arrayTranslate() function works.

---

plugins/rich-editor/src/scripts/editor/EditorContent.tsx

Fixed #9291 
Pretty straightforward fix for the issue. Since no longer want to auto-scroll all the time, I've manually implemented the scrolling to the editor.

Fix editor not scrolling on rich quote

---

phpunit.xml.dist

Define new phpunit testsuite Sphinx
Relates to: https://github.com/vanilla/internal/issues/1957

Define new phpunit testsuite Sphinx

---

applications/dashboard/models/class.usermodel.php
library/Vanilla/Models/SiteMeta.php
packages/vanilla-dom-utils/src/events.ts
plugins/rich-editor/src/scripts/editor/pieces/EditorUploadButton.tsx
plugins/rich-editor/src/scripts/quill/EmbedInsertionModule.ts
yarn.lock

This PR adds support for multiple image upload to the Rich Editor.
Estimate: https://github.com/vanillaforums/estimates/blob/master/golfwrx/GolfWRX%20-%20RichEditor%20Multiple%20Image%20Upload%20Estimate.md
**Service due date:** 17-09-2019
**Notes:** Copying/pasting only works for 1 file because of lack of OS support.

Add support for multiple image uploads to Rich Editor

---

library/src/scripts/routing/PageLoader.tsx
library/src/scripts/splash/splashStyles.ts

Backport https://github.com/vanilla/vanilla/pull/9302

[Backport] Fix post 2019.013 bugs 

---

library/Vanilla/Contracts/Site/SiteSectionProviderInterface.php
library/Vanilla/Site/SingleSiteSectionProvider.php

Blocking https://github.com/vanilla/multisite/pull/259

Add getCurrent to site section provider

---

library/Vanilla/Models/ThemePreloadProvider.php

[Backport] Fix infinite loop in theme preload

---

library/Vanilla/Contracts/Search/SearchRecordTypeInterface.php
library/Vanilla/Contracts/Search/SearchRecordTypeProviderInterface.php
library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php
library/Vanilla/Navigation/BreadcrumbModel.php

Add advanced search record type interfaces to the core

---

library/Vanilla/Models/ThemePreloadProvider.php

Double quotes lets the variable be interpolated

Improve theme not found warning

---

themes/theme-boilerplate/package.json

Bump theme-boilerplate version to publish this change https://github.com/vanilla/vanilla/pull/8849

bump boilerplate version

---

phpunit.xml.dist
tests/TestInstallModel.php
tests/phpunit.php

Adds TEST_SPHINX_HOST env variable 
set Plugins.Sphinx.Server in the test config file.
require for vanilla/internal#1983

Set sphinx server for unit tests

---

library/Vanilla/Contracts/Search/SearchRecordTypeInterface.php
library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php

Relates to: https://github.com/vanilla/internal/issues/2003

Update advanced search related interfaces and trait

---

library/Vanilla/Models/ThemeVariablesTrait.php

Fixes https://github.com/vanilla/support/issues/883
- We want addon variable providers to overlay on top of the base theme configuration.

Fix variable merging from theme providers

---

library/package.json
library/src/scripts/content/translationGrid/TranslationGrid.tsx
library/src/scripts/content/translationGrid/TranslationGridInput.tsx
library/src/scripts/content/translationGrid/TranslationGridRow.tsx
library/src/scripts/content/translationGrid/TranslationGridStyles.ts
library/src/scripts/content/translationGrid/TranslationGridText.tsx
library/src/scripts/content/translationGrid/translationGrid.story.tsx
library/src/scripts/content/translationGrid/translationGrid.storyData.ts
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/forms/InputBlockStyles.tsx
library/src/scripts/forms/InputTextBlock.tsx
library/src/scripts/icons/common.tsx
library/src/scripts/icons/iconClasses.ts
library/src/scripts/layout/ConditionalWrap.tsx
package.json
yarn.lock

Added new translation grid component to react storybook.
Note that the data structure and state management are WIPs. I just roughed out how it can work in Storybook. Also, the locale chooser is to be added when @NeenaDev is done creating it.
Closes: https://github.com/vanilla/knowledge/issues/1248

Added Translation Grid Component

---

library/Vanilla/Models/UserFragmentSchema.php
library/src/scripts/@types/api/users.ts
library/src/scripts/content/UserLabel.tsx
library/src/scripts/embeddedContent/QuoteEmbed.story.tsx

See https://github.com/vanilla/internal/pull/2014 for information

Use label instead of title in user fragment

---

library/Vanilla/Models/ThemeVariablesTrait.php
library/Vanilla/Models/UserFragmentSchema.php
library/src/scripts/@types/api/users.ts
library/src/scripts/content/UserLabel.tsx
library/src/scripts/embeddedContent/QuoteEmbed.story.tsx

Backport https://github.com/vanilla/vanilla/pull/9382
Backport https://github.com/vanilla/vanilla/pull/9380

[Backport] User fragment and theme api fixes

---

build/.storybook/config.js
library/src/scripts/styles/globalStyleVars.ts
library/src/scripts/toolTip/ToolTip.tsx
library/src/scripts/toolTip/toolTip.story.tsx
library/src/scripts/toolTip/toolTipStyles.ts
package.json
yarn.lock

Added accessible, responsive tooltips to storybook. They stay within the window and dynamically decide to pop up above or below the item. 
Closes: https://github.com/vanilla/vanilla/issues/9342

Added accessible, responsive tooltips to storybook

---

library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php

Hot-fix.
Relates to: https://github.com/vanilla/vanilla/issues/9318
Need to be delivered together with:

Check infrastructure sphinx index template to be enabled

---

library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php

backporting https://github.com/vanilla/vanilla/pull/9400

Backport: Check infrastructure sphinx index template to be enabled (release/2019.014)

---

tests/fixtures/src/MockSiteSectionProvider.php

Blocking https://github.com/vanilla/knowledge/pull/1264

Implement `getForSectionGroup()` in MockSiteSectionProvider

---

library/src/scripts/content/Translate.tsx
library/src/scripts/modal/ModalConfirm.tsx

Fixed "Translate" component doc to match name of component.
Added optional size prop to confirm modal.

Updated "Translate" doc to match name of component

---

library/src/scripts/splash/splashStyles.ts

Fixed hero title size on home page.

Fixed hero title size

---

library/Vanilla/Utility/Deprecation.php
library/core/class.configuration.php

Backport of: https://github.com/vanilla/vanilla/pull/9415

[Backport] Fix configSplit empty

---

library/core/class.configuration.php
tests/Library/Core/GdnConfigurationTest.php

[Backport] Remove logging for empty config keys

---

library/src/scripts/content/UserContent.tsx
library/src/scripts/content/code.ts
library/src/scripts/content/hashScrolling.ts
plugins/rich-editor/src/scripts/editor/EditorContent.tsx
plugins/rich-editor/src/scripts/quill/blots/blocks/CodeBlockBlot.ts

Fixes https://github.com/vanilla/knowledge/issues/1173
Fixes https://github.com/vanilla/support/issues/916
- Fixes asynchronous flow in code block syntax highlighting that could lead to issues like https://github.com/vanilla/support/issues/916.
- Fixes user content not refreshing properly when navigating dynamically between different user contents. The user content is now passed to the hook to refresh it. See https://github.com/vanilla/knowledge/issues/1173

Make syntax highlighting more robust

---

library/src/scripts/content/UserContent.tsx
library/src/scripts/content/code.ts
library/src/scripts/content/hashScrolling.ts
plugins/rich-editor/src/scripts/editor/EditorContent.tsx
plugins/rich-editor/src/scripts/quill/blots/blocks/CodeBlockBlot.ts

[Backport] Make syntax highlighting more robust

---

applications/vanilla/controllers/class.discussioncontroller.php
library/Vanilla/Utility/Deprecation.php
library/core/class.configuration.php
library/src/scripts/content/UserContent.tsx
library/src/scripts/content/code.ts
library/src/scripts/content/hashScrolling.ts
plugins/rich-editor/src/scripts/editor/EditorContent.tsx
plugins/rich-editor/src/scripts/quill/blots/blocks/CodeBlockBlot.ts
tests/Library/Core/GdnConfigurationTest.php

Backports the following:
- Splitconfig key issue - https://github.com/vanilla/vanilla/pull/9415, https://github.com/vanilla/vanilla/pull/9419
- Syntax highlighting issue - https://github.com/vanilla/vanilla/pull/9423
- Announcement issue - https://github.com/vanilla/vanilla/pull/9433

Backport fixes to 2019.014

---

library/Vanilla/Models/SiteMeta.php
library/src/scripts/utility/appUtils.tsx

Closes https://github.com/vanilla/vanilla/issues/9413

Add current site section to SiteMeta

---

applications/vanilla/controllers/class.discussioncontroller.php

Backport https://github.com/vanilla/vanilla/pull/9433

[Backport] Use setProperty instead of setField to announce discussions

---

library/src/scripts/locales/localeBootstrap.ts

Fixes https://github.com/vanilla/vanilla/issues/9429
Backport here https://github.com/vanilla/vanilla/pull/9431

Fix translations not loading in frontend

---

library/src/scripts/locales/localeBootstrap.ts

[Backport] Fix translations not loading in frontend

---

library/Vanilla/Web/SafeCurlHttpHandler.php

This PR adds the option to set cURL followLocation parameter when using safecurl.

Add ability to configure location following in SafeCurlHandler

---

library/Vanilla/Contracts/Site/SiteSectionProviderInterface.php
library/core/class.request.php
tests/Bootstrap.php
tests/fixtures/src/MockSiteSectionProvider.php

Relates to: https://github.com/vanilla/knowledge/issues/1283

Extend mockSiteSectionProvider to provide 2 siteSectionGroups

---

library/Vanilla/Web/SafeCurlHttpHandler.php

backporting https://github.com/vanilla/vanilla/pull/9443/

Backport: Add ability to configure location following in SafeCurlHandler (2019.015)

---

applications/vanilla/views/vanillasettings/editcategory.twig
library/Vanilla/Models/SiteMeta.php
resources/views/userContentError.twig
tests/Library/Vanilla/TwigValidatorTest.php

Followup to https://github.com/vanilla/vanilla/pull/9455 & https://github.com/vanilla/vanilla/pull/9449
- Fixes some template bugs.
- Add a test to do template validation on our twig templates.
- Fixes theme key check when serializing to json.

Fix twig template error & site meta serialization

---

environment.php

update environment version

---

environment.php

update environment version on 2019.015 branch

---

library/core/class.request.php

Relates to: https://github.com/vanilla/support/issues/945

Fix to avoid port 80 and 443 to appear in url

---

library/Vanilla/Site/DefaultSiteSection.php
tests/fixtures/src/MockSiteSectionProvider.php

Relates to: https://github.com/vanilla/support/issues/945

Fix SiteSection path related methods

---

library/src/scripts/flyouts/dropDownStyles.ts
library/src/scripts/flyouts/items/DropDownItemLink.tsx
library/src/scripts/flyouts/items/DropDownItemRadio.tsx
library/src/scripts/forms/buttonStyles.ts
library/src/scripts/forms/styleHelperButtonGenerator.ts
library/src/scripts/headers/titleBarStyles.ts
library/src/scripts/icons/icons.story.tsx
library/src/scripts/icons/titleBar.tsx
yarn.lock

Added subcommunity chooser to pages that aren't explicitely in a subcommunity.

Add checkbox & isCurrent property to DropDownItemLink

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/controllers/class.usercontroller.php
applications/vanilla/views/vanillasettings/floodcontrol.php
library/core/functions.deprecated.php
library/core/functions.general.php

This function had no code coverage and is not really a best practice.

Deprecate arrayCombine()

---

bootstrap.php
library/Vanilla/Contracts/Site/SiteSectionProviderInterface.php
library/Vanilla/Models/SiteMeta.php
library/Vanilla/Site/SingleSiteSectionProvider.php
library/Vanilla/Site/SiteSectionModel.php
tests/Bootstrap.php
tests/Library/Vanilla/Site/SingleSiteSectionProviderTest.php

Relates to: https://github.com/vanilla/knowledge/issues/1206 and https://github.com/vanilla/multisite/issues/276

Refactor site section group functionality

---

library/src/scripts/icons/common.tsx
library/src/scripts/messages/messageStyles.ts
library/src/scripts/routing/links/backLinkStyles.ts
library/src/scripts/styles/styleHelpers.ts

Updated messages styles and wording for untranslated articles.
For https://github.com/vanilla/knowledge/issues/1276
Companion PR: https://github.com/vanilla/knowledge/pull/1322
Companion PR: https://github.com/vanilla/locales/pull/226

Fix design/wording of localization notifications

---

applications/dashboard/models/class.messagemodel.php
applications/dashboard/models/class.permissionmodel.php
library/Vanilla/Formatting/UpdateMediaTrait.php

This is a copy of #9512 to see if tests pass.

Remove Gdn_SQLDriver::whereNotIn workarounds

---

applications/dashboard/models/class.usermodel.php

Fire AfterRegister event only if a UserID is present

---

applications/dashboard/controllers/class.entrycontroller.php

Add meta description to the signin page

---

applications/dashboard/models/class.importmodel.php

Fix warning in ImportModel

---

library/src/scripts/styles/globalStyleVars.ts

We do something like this with the primary colors.
After this change if someone provides the `middleColumn.width` variable it will be used to calculate the `paddedWidth`.

Update global column vars to use the provided column with in calculations

---

library/src/scripts/flyouts/dropDownStyles.ts

Backport https://github.com/vanilla/vanilla/pull/9556

[Backport] Fix broken flyout styles

---

applications/dashboard/library/Jobs/ExecuteActivityQueue.php
applications/dashboard/models/ActivityEmail.php
applications/dashboard/models/class.activitymodel.php
applications/vanilla/models/class.commentmodel.php
applications/vanilla/models/class.discussionmodel.php
library/core/class.email.php

#9412, #9450 and #9548 were merged into a feature branch. Now, it's time to merge that feature branch into `master`.

Add batch notifications feature

---

library/Vanilla/Web/UserSmartIDResolver.php
tests/Library/Vanilla/Web/SmartIDMiddlewareTest.php

Closes #7344. See that issue for details.

Add the $me smart ID

---

applications/vanilla/library/Navigation/ForumBreadcrumbProvider.php
library/Vanilla/Navigation/BreadcrumbModel.php
library/Vanilla/Navigation/BreadcrumbProviderInterface.php
library/Vanilla/Site/SingleSiteSectionProvider.php
library/Vanilla/Site/SiteSectionModel.php

Adjust BreadcrumbProviderInterface and related classes to support locale when generate urls
Relates to: https://github.com/vanilla/knowledge/issues/1022
**Note** This also implement lazy detection of currentSiteSection

Add locale parameter to some methods of BreadcrumbProviderInterface and related classes

---

applications/dashboard/settings/class.hooks.php

Closes https://github.com/vanilla/vanilla-patches/issues/648.

Don’t allow copyLocal to copy from anything but the uploads directory

---

applications/dashboard/controllers/class.profilecontroller.php

Replace deprecated touchConfig() usage

---

applications/dashboard/library/Jobs/ExecuteActivityQueue.php
applications/dashboard/models/ActivityEmail.php
applications/dashboard/models/class.activitymodel.php
applications/vanilla/models/class.commentmodel.php
applications/vanilla/models/class.discussionmodel.php
library/core/class.email.php

Backporting #9564 to `release/2019.016`.
> #9412, #9450 and #9548 were merged into a feature branch. Now, it's time to merge that feature branch into `master`.

Backport: Add batch notifications feature

---

library/Vanilla/Site/SiteSectionModel.php
tests/fixtures/src/MockSiteSectionProvider.php

Relates to: https://github.com/vanilla/vanilla/pull/9565
Blocker for: https://github.com/vanilla/knowledge/pull/1345

Fixes for SiteSectionModel to initialize currentSiteSection

---

applications/dashboard/js/dashboard.js
applications/dashboard/src/scripts/components/DashboardHeaderBlock.tsx
applications/dashboard/src/scripts/forms/0-SimpleForm.story.tsx
applications/dashboard/src/scripts/forms/DashboardFormList.tsx
applications/dashboard/src/scripts/forms/DashboardFormListStyles.ts
applications/dashboard/src/scripts/forms/DashboardInput.tsx
applications/dashboard/src/scripts/forms/DashboardRadioButton.tsx
library/src/scripts/forms/InputBlock.tsx
library/src/scripts/forms/InputBlockStyles.tsx
library/src/scripts/forms/InputTextBlock.tsx
library/src/scripts/forms/RadioButton.tsx
library/src/scripts/forms/select/SelectOne.tsx
library/src/scripts/layout/frame/frameStyles.ts
library/src/scripts/modal/ModalSizes.ts
library/src/scripts/modal/ModalView.tsx
library/src/scripts/modal/modalStyles.ts
plugins/rich-editor/src/scripts/editor/EditorContent.tsx

This PR is getting pretty big, so I'm splitting it. This PR is for the new React Add/Edit Knowledge form. **The form is not yet styled and not yet functional.** To test it, you can replace everything in knowledgesettings/index.twig with `<div data-react="knowledge-bases-manage"></div>` and then uncomment https://github.com/vanilla/knowledge/compare/feature%2Fkb-add-edit-modal?expand=1#diff-f61c7c49bb10b2d46567e841b32867fcR30
Requires: https://github.com/vanilla/knowledge/pull/1349

Updated react dashboard form components and modal for KB forms.

---

applications/dashboard/controllers/api/LocalesApiController.php

Relates to: https://github.com/vanilla/vanilla/issues/9481

Create locale validator

---

packages/vanilla-i18n/src/ContentTranslator.tsx

I've refined the interfaces a little now that the actual API implementation is complete in https://github.com/vanilla/knowledge/pull/1356

Update translation property interfaces

---

.gitignore
library/Vanilla/Formatting/Formats/HtmlFormat.php
tests/fixtures/formats/bbcode/block-formatting/output-excerpt.txt
tests/fixtures/formats/bbcode/block-formatting/output.html
tests/fixtures/formats/bbcode/block-formatting/output.txt
tests/fixtures/formats/bbcode/embeds/output.html
tests/fixtures/formats/html/inline-formatting/input.html
tests/fixtures/formats/html/inline-formatting/output.html
tests/fixtures/formats/html/inline-formatting/output.txt
tests/fixtures/formats/html/paragraph-formats/input.html
tests/fixtures/formats/html/paragraph-formats/output-excerpt.txt
tests/fixtures/formats/html/paragraph-formats/output.html
tests/fixtures/formats/html/paragraph-formats/output.txt
tests/fixtures/formats/markdown/paragraph-formatting/output-excerpt.txt
tests/fixtures/formats/markdown/paragraph-formatting/output.html
tests/fixtures/formats/markdown/paragraph-formatting/output.txt
tests/fixtures/formats/markdown/xss/output.html
tests/fixtures/formats/wysiwyg/paragraph-formats/input.html
tests/fixtures/formats/wysiwyg/paragraph-formats/output-excerpt.txt
tests/fixtures/formats/wysiwyg/paragraph-formats/output.html
tests/fixtures/formats/wysiwyg/paragraph-formats/output.txt

Update KB user content styles to support other rendered HTML from other formats.
I'm told changing the quote in the XXS test is safe and fine.
Closes: https://github.com/vanilla/knowledge/issues/1292

Update HTML format to normalize HTML with consistent classes

---

tests/APIv0/AltTest.php

I want to make sure we have tests for when we deploy update tokens.
Related to https://github.com/vanilla/internal/issues/2006.

Add some smoke tests for update token installs

---

library/src/scripts/modal/modalStyles.ts

Fixes to modal scroll when there's a form element inside

Fixes to modal scroll when there's a form element inside

---

library/src/scripts/flyouts/DropDown.tsx
library/src/scripts/flyouts/DropDownContents.tsx
library/src/scripts/flyouts/dropDownStyles.ts
library/src/scripts/forms/select/SelectBox.tsx
library/src/scripts/modal/modalStyles.ts

Created prop to handle offset of select flyout to align side of toggle with text inside content
Fixed modal height to fix overflow issue when there's little content and a flyout with content longer than height.
Companion PR: https://github.com/vanilla/internal/pull/2084

Fixed alignment of flyout content and height of modal.

---

applications/dashboard/src/scripts/forms/DashboardFormGroup.tsx
applications/dashboard/src/scripts/forms/DashboardFormLabel.tsx
applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx
applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
applications/dashboard/src/scripts/forms/DashboardInput.tsx
applications/dashboard/src/scripts/forms/DashboardRadioGroups.tsx
applications/dashboard/src/scripts/forms/DashboardSelect.tsx
applications/dashboard/src/scripts/forms/DashboardToggle.tsx
library/src/scripts/forms/ErrorMessages.tsx
library/src/scripts/forms/select/SelectBox.tsx
library/src/scripts/layout/frame/FrameHeader.tsx
library/src/scripts/layout/frame/frameHeaderStyles.ts
packages/vanilla-i18n/src/ContentTranslator.tsx

- Allow content translator to have a title.
- Allow all dashboard form fields to have error messages
- Fix some icon placement

Prepare dashboard form fields

---

applications/dashboard/controllers/class.setupcontroller.php

Additionally upgrade links to HTTPS.
Fixes #7770 and #9499

Add mysqlnd and intl as PHP requirements

---

environment.php

update release version

---

environment.php

Update master branch version

---

build/.storybook/config.js

Reduced diff threshold for storybook, it's currently too high.

Reduced diff threshold for storybook

---

library/Vanilla/Formatting/Formats/NotFoundFormat.php
tests/Library/Vanilla/Formatting/Formats/NotFoundFormatTest.php

Followup of https://github.com/vanilla/vanilla/pull/9625

Add tests for the not found format

---

plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuBarTab.tsx

[Backport] Fix editor paragraph menu tabs only appearing when open/active

---

library/Vanilla/Models/UserFragmentSchema.php

Fixes validation not being fully applied

Fix user fragment schema validation

---

library/Vanilla/Models/UserFragmentSchema.php

[Backport 2019.017] Fix user fragment schema validation

---

library/Vanilla/Models/UserFragmentSchema.php

[Backport 2019.016] Fix user fragment schema validation 

---

library/core/class.model.php
library/database/class.sqldriver.php
tests/Library/Database/MySQLDriverTest.php

A lot of the time I'm writing code and seeing a lot of warnings from malformed docblocks makes it more difficult to write new code.

Fix some doc blocs in Gdn_Model and Gdn_SQLDriver

---

library/src/scripts/modal/Modal.tsx
library/src/scripts/modal/ModalConfirm.tsx

Quick followup to https://github.com/vanilla/vanilla/pull/9648

Make confirm modal exit element optional

---

applications/dashboard/models/class.updatemodel.php

Temporary revert of https://github.com/vanilla/vanilla/pull/9498
We'll likely just try and resolve the issue on master, for the next release, but right now this is blocking creation of new sites on infra.
See https://vanillaforums.slack.com/archives/C02RHA2NA/p1574110572139900

[Release 2019.017] Revert session changes in update model

---

tests/SiteTestTrait.php

Relates to: https://github.com/vanilla/knowledge/pull/1382

Add enabledLocales to SiteTestTrait

---

library/Vanilla/Models/SiteMeta.php

As the title says.
For https://github.com/vanilla/vanilla/issues/9616

Add share image to site meta

---

applications/vanilla/tests/EmbeddedContent/Factories/DiscussionEmbedFactoryTest.php
library/Vanilla/EmbeddedContent/Factories/AbstractOwnSiteEmbedFactory.php

Fixes the comment here https://github.com/vanilla/vanilla/pull/9654#discussion_r349101663
I've also added a test with various regex characters.

Escape regex in the own site embed

---

package.json

[Backport 2019.017] Ignore engines in lerna bootstrap 

---

library/src/scripts/forms/select/SelectBox.tsx
library/src/scripts/messages/messageStyles.ts

Made the "name" field optional, because it's redundant to use the same text for the contents and the title.

Make name optional for SelectBox

---

library/src/scripts/flyouts/dropDownStyles.ts
library/src/scripts/forms/select/SelectBox.tsx
library/src/scripts/forms/select/selectBoxStyles.ts
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/mebox/pieces/meBoxStyles.ts
library/src/scripts/headers/titleBarStyles.ts
library/src/scripts/icons/common.tsx
library/src/scripts/icons/iconClasses.ts
library/src/scripts/layout/frame/frameStyles.ts

Various bug fixes, pointed out during demo.
For: https://github.com/vanilla/knowledge/issues/1364
- Fixed width of locale dropdown in dashboard 
- Fixed extra spacing on top of locale dropdown in article in panel (too far from title)
- Fixed alignment of checkbox in selectbox
- Fixed focus color of mebox buttons
- fixed scrolling for KB settings modal (it was broken)
- fixed size of edit icon in KB edit modal (exception, it's 24px everywhere else)
Companion PR: https://github.com/vanilla/internal/pull/2099
Companion PR: https://github.com/vanilla/knowledge/pull/1396

Demo Feedback - Visual bugs

---

themes/theme-boilerplate/addon.json
themes/theme-boilerplate/package.json

Fix boilerplate version in packages

Fix boilerplate version in packages

---

library/src/scripts/embeddedContent/embedStyles.ts
library/src/scripts/styles/globalStyleVars.ts

Fix - https://github.com/vanilla/vanilla/issues/9702
Adjust margin-top for embed header

Fix/Adjusting margin-top for embed header

---

build/.storybook/addons.js
build/.storybook/config.js
package.json
yarn.lock

This plugin is causing errors on my local host, we're not really using it and it's not really compatible with Chromatic. For these reasons, we're removing it.
@charrondev do you get the same `yarn.lock` file as I do here? I know it can be different based on what you have configured...
Related: https://github.com/vanilla/knowledge/pull/1419
Also, I get these warnings now:
```
WARNING in ./plugins/rich-editor/node_modules/quill/modules/keyboard.js 671:14-19
"export 'default' (imported as 'clone') was not found in 'clone'
@ ./plugins/rich-editor/node_modules/quill/core.js
@ ./plugins/rich-editor/src/scripts/editor/EditorContent.tsx
@ ../knowledge/plugins/knowledge/src/scripts/modules/editor/EditorForm.tsx
@ ../knowledge/plugins/knowledge/src/scripts/modules/editor/EditorPage.tsx
@ …
```

Storybook - Remove "knobs" plugin

---

library/Vanilla/Web/ContentSecurityPolicy/ContentSecurityPolicyModel.php
library/Vanilla/Web/ContentSecurityPolicy/DefaultContentSecurityPolicyProvider.php
tests/Library/Vanilla/ContentSecurityPolicyModelTest.php

Fix ContentSecurityPolicyModel  wasn't generating proper headers.
Add unit test.
Closes: #9664

Fix CSP headers

---

library/Vanilla/Formatting/Formats/HtmlFormat.php
tests/fixtures/formats/bbcode/carriage-returns/input.txt
tests/fixtures/formats/bbcode/carriage-returns/output.html
tests/fixtures/formats/bbcode/carriage-returns/output.txt
tests/fixtures/formats/bbcode/code-block-formatting/input.txt
tests/fixtures/formats/bbcode/code-block-formatting/output.html
tests/fixtures/formats/bbcode/code-block-formatting/output.txt

[Backport] Fix BBcode spacing issue

---

plugins/rich-editor/src/scripts/quill/components/blockQuoteStyles.ts

Fixed scrolling issue from https://github.com/vanilla/support/issues/1107

Fix blockquote unnecessary scrolling

---

plugins/Quotes/js/quotes.js

Backport https://github.com/vanilla/vanilla/pull/9762

Fix quote folding

---

library/src/scripts/messages/Message.tsx
library/src/scripts/messages/message.story.tsx

Changes in `<Message />`
wrapping {props.content} into div.
requires: https://github.com/vanilla/vanilla/pull/9726

Fix `<Message />` wrapping requiring wrapping content into div 

---

js/global.js
library/Vanilla/Models/SiteMeta.php

Backport: https://github.com/vanilla/vanilla/pull/9779
Applies #9779 to release/2019.18

[Backport 2019.018] Use dynamicPath from infra context for notifications and analytics requests.

---

tests/Library/Vanilla/OpenAPIBuilderTest.php

Update swagger cli version to 2.3.4

Update swagger cli version to 2.3.4

---

library/Vanilla/Contracts/Site/TranslationProviderInterface.php
library/Vanilla/Contracts/Site/TranslationResourceInterface.php
library/Vanilla/Site/TranslationProvider.php

Relates to: https://github.com/vanilla/knowledge/issues/1442

Introduce TranslationResourceInterface

---

library/Vanilla/Contracts/Site/TranslationProviderInterface.php
library/Vanilla/Contracts/Site/TranslationResourceInterface.php
library/Vanilla/Site/TranslationProvider.php

Backport https://github.com/vanilla/vanilla/pull/9787

[Backport] Introduce TranslationResourceInterface

---

library/Vanilla/Contracts/Search/SearchRecordTypeInterface.php
library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php

Relates to: https://github.com/vanilla/knowledge/issues/1318

Extend SearchRecordTypeInterface and Trait with isEnabled() method

---

library/src/scripts/modal/modalStyles.ts
library/src/scripts/styles/globalStyleVars.ts

Added new global variable for full page modals title gap

Added new global variable for full page modals title gap

---

build/entries/public-path.ts
js/global.js
library/Vanilla/Web/Asset/SiteAsset.php
library/src/scripts/utility/appUtils.tsx
tests/Library/Vanilla/Web/Asset/WebpackAssetProviderTest.php
tests/Library/Vanilla/Web/Asset/WebpackAssetTest.php

The PR fixes an issue with url-paths in multisite environments.

fix relative url path for multisite

---

build/entries/public-path.ts
js/global.js
library/Vanilla/Web/Asset/SiteAsset.php
library/src/scripts/utility/appUtils.tsx
tests/Library/Vanilla/Web/Asset/WebpackAssetProviderTest.php
tests/Library/Vanilla/Web/Asset/WebpackAssetTest.php

Backport for https://github.com/vanilla/vanilla/pull/9809

Fix relative path multisite 2019.018

---

library/src/scripts/theming/loadThemeFonts.ts
library/src/scripts/theming/themeReducer.ts

Fixed a mismatch between the API data structure and the expected JS structure while loading custom fonts.

Fixed font loading for dynamic themes with assets

---

library/src/scripts/theming/loadThemeFonts.ts
library/src/scripts/theming/themeReducer.ts

Backports https://github.com/vanilla/vanilla/pull/9838
Backport to fix font loading in new theming system.

[Backport 2019.018] Fixed font loading for dynamic themes with assets

---

library/Vanilla/Theme/ThemeFeatures.php
library/Vanilla/Web/TwigEnhancer.php

- Fix wrong default for shared master view.
- Fix PHP warning in `TwigEnhancer`

Fix theme feature typos

---

applications/dashboard/controllers/api/UsersApiController.php
applications/dashboard/openapi/users.yml
tests/APIv2/UsersTest.php

Fixes the issue #9735 with missing password change function in APIv2

Fixes the missing field "password" in Userpatch APIv2

---

composer.json
composer.lock

Add GUID generator composer library
https://github.com/ramsey/uuid

Add GUID library to project requirements

---

tests/Bootstrap.php

Fix failing tests that use the Scheduler as a dependency.

update bootstrap test namespace

---

tests/Library/Core/ValidateBooleanTest.php
tests/Library/Core/ValidateCategoryUrlCodeTest.php
tests/Library/Core/ValidateDateTest.php
tests/Library/Core/ValidateDecimalTest.php
tests/Library/Core/ValidateEmailTest.php
tests/Library/Core/ValidateEnumTest.php
tests/Library/Core/ValidateIntegerTest.php
tests/Library/Core/ValidateNoLinksTest.php
tests/Library/Core/ValidateOneOrMoreArrayItemRequiredTest.php
tests/Library/Core/ValidatePhoneIntTest.php
tests/Library/Core/ValidatePhoneNATest.php
tests/Library/Core/ValidateRequiredArrayTest.php
tests/Library/Core/ValidateRequiredTest.php
tests/Library/Core/ValidateStringTest.php
tests/Library/Core/ValidateUrlStringRelaxedTest.php
tests/Library/Core/ValidateUrlStringTest.php
tests/Library/Core/ValidateUrlTest.php
tests/Library/Core/ValidateVersionTest.php
tests/Library/Core/ValidateWebAddressTest.php
tests/Library/Core/ValidateZipCodeTest.php

I added tests for all the functions in the functions.validation file that don't make a call to any Gdn functions.

Add tests for functions.validation

---

library/Vanilla/Utility/SchemaFilters.php
tests/Library/Vanilla/Utility/SchemaFiltersTest.php

Added tests for the methods in the SchemaFilters class.
Partially addresses #9869

Add tests for SchemaFilters class

---

library/src/scripts/headers/ActionBar.story.tsx
library/src/scripts/headers/ActionBar.tsx
library/src/scripts/headers/ActionBarStyles.ts
library/src/scripts/headers/titeBar.story.tsx
library/src/scripts/headers/titleBarRegisterUser.story.tsx

This adds a new ActionBar component along with a storybook story.
note: titlebar stories were moved under Header stories
related to https://github.com/vanilla/vanilla/issues/9826

Add new ActionBar component with storybook

---

library/src/scripts/headers/ActionBar.story.tsx
library/src/scripts/headers/ActionBar.tsx
library/src/scripts/headers/ActionBarStyles.ts
library/src/scripts/headers/titeBar.story.tsx
library/src/scripts/headers/titleBarRegisterUser.story.tsx

files deleted in 
https://github.com/vanilla/vanilla/pull/9861
original pr:
https://github.com/vanilla/vanilla/pull/9863

Re Add Actionbar changes

---

applications/dashboard/controllers/api/ThemesApiController.php
applications/dashboard/controllers/api/ThemesApiSchemes.php
library/Vanilla/Models/FsThemeMissingTrait.php
library/Vanilla/Models/FsThemeProvider.php
library/Vanilla/Models/ThemeModel.php
library/Vanilla/Theme/ThemeProviderInterface.php
library/src/scripts/layout/PanelLayout.tsx
library/src/scripts/sectioning/TabStyles.ts
library/src/scripts/theming/ThemePreviewCard.tsx
library/src/scripts/theming/themeCardStyles.ts

Issue https://github.com/vanilla/internal/issues/2139
Companion https://github.com/vanilla/internal/pull/2164
- Prepare FS theme provider to support PUT `/themes/current`.
- Improvements to the `ThemePreviewCard`.

Feature theming editor components

---

applications/dashboard/settings/structure.php

Fixes https://github.com/vanilla/vanilla/issues/9906

Remove unused old required storageMethod column in structure

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
library/Vanilla/ImageResizer.php
library/src/scripts/Router.tsx
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/layout/panelAreaStyles.ts
library/src/scripts/layout/panelLayoutStyles.ts
library/src/scripts/navigation/breadcrumbsStyles.ts
packages/vanilla-polyfill/index.js
plugins/rich-editor/RichEditorPlugin.php
plugins/rich-editor/src/scripts/entries/admin.ts
plugins/rich-editor/src/scripts/mountEditor.tsx
themes/theme-boilerplate/src/scss/sections/_header.scss

Backports the following PRs:
- https://github.com/vanilla/vanilla/pull/9922
- https://github.com/vanilla/vanilla/pull/9920
- https://github.com/vanilla/vanilla/pull/9925
- https://github.com/vanilla/vanilla/pull/9930
- https://github.com/vanilla/vanilla/pull/9928

Backports for 2020.001

---

applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/controllers/api/DiscussionsApiController.php
library/Vanilla/ImageResizer.php
library/src/scripts/Router.tsx
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/layout/panelAreaStyles.ts
library/src/scripts/layout/panelLayoutStyles.ts
library/src/scripts/navigation/breadcrumbsStyles.ts
packages/vanilla-polyfill/index.js
plugins/rich-editor/RichEditorPlugin.php
plugins/rich-editor/src/scripts/entries/admin.ts
plugins/rich-editor/src/scripts/mountEditor.tsx
themes/theme-boilerplate/src/scss/sections/_header.scss

_This was previously attempted with https://github.com/vanilla/vanilla/pull/9931 but I targetted the wrong branch_
Backports the following PRs:
#9922
#9920
#9925
#9930
#9928

Backorts/2020.001 (2nd attempt)

---

applications/dashboard/controllers/api/ThemesApiSchemes.php
applications/dashboard/openapi/themes.yml

Fixes theme preview image not changing when new them is applied in Theming UI page.
closes https://github.com/vanilla/internal/issues/2169

add preview to themeResultsSchema

---

library/src/scripts/theming/ThemePreviewCard.tsx
library/src/scripts/theming/themeCardStyles.ts
library/src/scripts/theming/themePreviewCard.story.tsx

Add "canCopy : boolean, canDelete: boolean, canEdit: boolean"  props to `<ThemePreviewCard />` component: 
-to show/hide Copy button for custom themes
-to show dropdown for for custom themes

Add dropdown in Theme card

---

applications/dashboard/controllers/class.utilitycontroller.php

Fix twig error on utility/update debug mode

---

addons/themes/theme-foundation/addon.json
library/Vanilla/Models/ThemeModel.php
library/Vanilla/Theme/ThemeProviderInterface.php
library/src/scripts/theming/ThemesActions.ts
library/src/scripts/theming/themeSettingsReducer.ts

Relates to: https://github.com/vanilla/knowledge/issues/1226
Some extra fixes related to: https://github.com/vanilla/internal/pull/2183

Fix edge case when wrong theme preview stored in session data

---

environment.php

Update environment release version on the current release branch.

Fix release/2020.001 version

---

applications/dashboard/controllers/class.logcontroller.php
applications/dashboard/library/class.nestedcollection.php
applications/dashboard/views/log/edits.php
applications/vanilla/views/discussion/helper_functions.php

Closes #9948. See the linked issue for details.

Add edit log access from within a discussion

---

environment.php

update environment version 2020.002

update environment version 2020.002

---

applications/dashboard/src/scripts/entries/forum.tsx
library/src/scripts/theming/ThemeProvider.tsx

Backport https://github.com/vanilla/vanilla/pull/9997

[Backport] Fix theme reset from getting applied to old themes

---

applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
library/src/scripts/animation/EntranceAnimation.tsx
library/src/scripts/embeddedContent/ImageEmbed.tsx
library/src/scripts/embeddedContent/StoryExampleModal.tsx
library/src/scripts/embeddedContent/StoryExampleModalConfirm.tsx
library/src/scripts/flyouts/DropDownContents.tsx
library/src/scripts/flyouts/FlyoutToggle.tsx
library/src/scripts/headers/mebox/pieces/CompactMeBox.tsx
library/src/scripts/headers/pieces/MobileDropDown.tsx
library/src/scripts/headers/pieces/mobileDropDownStyles.ts
library/src/scripts/modal/Modal.tsx
library/src/scripts/modal/ModalConfirm.tsx
library/src/scripts/modal/ModalLoader.tsx
library/src/scripts/modal/ModalView.tsx
library/src/scripts/modal/modalStyles.ts
plugins/rich-editor/src/scripts/editor/pieces/ImageEmbedModal.tsx

Closes https://github.com/vanilla/vanilla/issues/9984
BC Break with a new required prop. Companion PRs here to update usages:
- https://github.com/vanilla/internal/pull/2199
- https://github.com/vanilla/knowledge/pull/1492
- https://github.com/vanilla/multisite/pull/331
A new component for animations has been added. Its first and primary use case is for transitioning modals in.
- Animations are configurable through props.
- Animations are spring-based.
- Animations are cancelable.
- Animated items cannot be interacted with when they are transitioning out. This prevents animated modals and items fading out from interfering with the _visible_ elements on the screen.
For information see the described props.
https://github.com/vanilla/vanilla/blob/3d4e3243036245286f4244e6f505ba0fcdc5c852/libra …

Add animations and transitions to modals

---

applications/dashboard/controllers/class.entrycontroller.php

backport https://github.com/vanilla/vanilla/pull/10007

backport: fix reset password broken link (2020.002)

---

library/src/scripts/utility/appUtils.spec.ts
library/src/scripts/utility/appUtils.tsx

Closes https://github.com/vanilla/vanilla/issues/9974
**[New Documentation Here](https://success.vanillaforums.com/kb/articles/142-navigation-links#handling-subcommunities)**
I'm open to changing the starting character if anyone can come up with a better one.

Allow links to be created relative to the site root

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/views/settings/layout.php
library/Vanilla/Contracts/Site/SiteSectionInterface.php
library/Vanilla/Site/DefaultSiteSection.php
library/Vanilla/Site/SiteSectionModel.php
library/core/class.dispatcher.php
library/core/class.router.php
tests/Library/Vanilla/Site/SingleSiteSectionProviderTest.php
tests/fixtures/src/MockSiteSection.php
tests/fixtures/src/MockSiteSectionProvider.php

Relates to: https://github.com/vanilla/multisite/issues/328

Implement flexible DefaultController

---

applications/vanilla/models/class.commentmodel.php
applications/vanilla/models/class.discussionmodel.php
tests/Models/DiscussionModelTest.php

backporting https://github.com/vanilla/vanilla/pull/10035

Backport: fix adding required user fields when approving a post from moderation (2020.003)

---

library/core/class.smarty.php

backproting https://github.com/vanilla/vanilla/pull/10039

Backport: Add a sensible default Smarty template directory (2020.003)

---

environment.php

update release env version (2020.003)

update release env version (2020.003)

---

packages/vanilla-react-utils/src/mounting.tsx
plugins/rich-editor/src/scripts/mountEditor.tsx

Backport https://github.com/vanilla/vanilla/pull/10046

[Backport] Fix editor mounting

---

applications/dashboard/src/scripts/entries/forum.tsx
library/src/scripts/theming/ThemeProvider.tsx

[Backport] Fix theme double mounting

---

environment.php

update dev environment version

update dev environment version

---

library/src/scripts/embeddedContent/embedService.tsx
library/src/scripts/headers/TitleBar.tsx
packages/vanilla-react-utils/src/mounting.tsx

Backport https://github.com/vanilla/vanilla/pull/10055
Backport https://github.com/vanilla/vanilla/pull/10054

Backports for 2020.003

---

library/src/scripts/banner/banner.story.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/layout/components/containerStyles.ts

Backport https://github.com/vanilla/vanilla/pull/10064

[Backport] Fix banner overflow

---

library/src/scripts/__tests__/testStoreState.ts
library/src/scripts/homeWidget/HomeWidget.story.tsx
library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts
library/src/scripts/homeWidget/HomeWidgetItem.tsx
library/src/scripts/modal/Modal.tsx
packages/vanilla-eslint-config/index.js

- Fix empty spacers not having min-width.
- Add responsive breakpoints to this story.
- Fix alignment of inner-bg to spec discusssed with elisa.
- Remove console log statements that were left lying around.
- Add ESLint config to error on most console, debugger, and alert statements.

Adjust home widget styles

---

applications/vanilla/controllers/class.categoriescontroller.php
library/Vanilla/Contracts/Site/SiteSectionInterface.php
library/Vanilla/Site/DefaultSiteSection.php
tests/fixtures/src/MockSiteSection.php

[Backport 2020.003] Update categories page to load a CategoryID from the current site section

---

applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/features/tiles/tileStyles.ts

[Backport 2020.003] Fix various theming issues in new system

---

applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/features/tiles/tileStyles.ts

Fixes https://github.com/vanilla/knowledge/issues/1527
Also for https://github.com/vanilla/internal/issues/2225
- Fix new image uploads not deleting properly (many DB image columns do not allow null).
- Allow specification of more font properties in tiles and banner

Fix various theming issues in new system

---

applications/dashboard/modules/class.sitetotalsmodule.php

Closes https://github.com/vanilla/support/issues/1405

Fix SiteTotalsModule by implementing lock and job scheduling

---

library/src/scripts/banner/Banner.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/features/tiles/Tiles.tsx
library/src/scripts/features/tiles/tilesStyles.ts
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts
library/src/scripts/homeWidget/HomeWidgetContainer.tsx
library/src/scripts/layout/components/Container.tsx
library/src/scripts/layout/components/containerStyles.ts
library/src/scripts/styles/styleHelpersSpacing.ts
library/src/scripts/styles/styleUtils.ts
library/src/scripts/theming/loadThemeFonts.ts

For https://github.com/vanilla/internal/issues/2225
- Add new "fullGutter" option to container to make the container provide the full mobile and desktop gutters.
- This new option has been used in Tiles, TitleBar, and Banner.
- Wrap home widgets in fullGutter container.
- Append cacheBuster to web fonts CSS that is loaded.

Implement theming improvements

---

library/src/scripts/banner/Banner.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/features/tiles/Tiles.tsx
library/src/scripts/features/tiles/tilesStyles.ts
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/layout/components/Container.tsx
library/src/scripts/layout/components/containerStyles.ts
library/src/scripts/styles/styleHelpersSpacing.ts
library/src/scripts/styles/styleUtils.ts
library/src/scripts/theming/loadThemeFonts.ts

Backport https://github.com/vanilla/vanilla/pull/10085

[Backport 2020.003] Implement theming improvements

---

library/Vanilla/Models/FsThemeProvider.php
library/Vanilla/Models/ThemeModel.php
library/Vanilla/Models/ThemeModelHelper.php
library/Vanilla/Web/Asset/WebpackAssetProvider.php
tests/Library/Vanilla/Web/Asset/WebpackAssetProviderTest.php
tests/fixtures/src/MockAddonProvider.php

Closes: https://github.com/vanilla/internal/issues/2191

Adjust WebpackAssetProvider to respect preview theme if set

---

library/src/scripts/styles/styleHelpersBorders.ts

We need this const to merge another branch on KB that is breaking the build.

Added empoty border const

---

plugins/Akismet/class.socketwriteread.php

backporting https://github.com/vanilla/vanilla/pull/10097

Backport: update akismet host to use ssl (2020.003)

---

library/src/scripts/navigation/SimplePagerModel.ts

required for https://github.com/vanilla/knowledge/pull/1557

Add IWithPagination interface on SimplePagerModel

---

library/src/scripts/flyouts/dropDownStyles.ts

Dropdowns were not respecting border radius, I fixed the issue.

Fixed border radius for dropdown

---

applications/vanilla/models/class.discussionmodel.php
library/Vanilla/Contracts/Formatting/FormatFieldInterface.php
library/Vanilla/Formatting/FormatFieldTrait.php

backporting https://github.com/vanilla/vanilla/pull/10109

Backport: add formatFieldInterface to use with a container rule (2020.003)

---

applications/vanilla/models/class.discussionmodel.php

backport: https://github.com/vanilla/vanilla/pull/10119

Backport: fix deleting posts in spam queue (release/2020.003)

---

applications/dashboard/src/scripts/compatibilityStyles/forumLayoutStyles.ts
library/src/scripts/layout/components/widgetContainerStyles.ts

Backporting https://github.com/vanilla/vanilla/pull/10114

Backporting  - Fixing narrow width always being applied to .Content #10114

---

applications/vanilla/Events/CommentEvent.php
applications/vanilla/controllers/api/CommentsApiController.php
applications/vanilla/models/class.commentmodel.php
tests/Models/CommentModelTest.php

closes  https://github.com/vanilla/internal/issues/2141
add CUD comment operation with unit tests.

Add PSR-14 events for comment CUD operations

---

applications/vanilla/js/post.js

backporting https://github.com/vanilla/vanilla/pull/10142

Backport: Fix save draft button when starting a new discussion (2020.004)

---

applications/dashboard/controllers/api/UsersApiController.php
applications/dashboard/models/class.usermodel.php
applications/vanilla/Events/UserEvent.php
applications/vanilla/models/class.discussionmodel.php
tests/Models/UserModelTest.php

closes https://github.com/vanilla/internal/issues/2143
Add PSR-14 events for user write operations with unittest.

Add PSR-14 events for user  write operations

---

library/src/scripts/forms/themeEditor/themeBuilderStyles.ts
library/src/scripts/forms/themeEditor/themeEditorStyles.ts
library/src/scripts/sectioning/TabStyles.ts
library/src/scripts/styles/styleHelpersColors.ts
library/src/scss/utility/_scaffolding.scss
packages/vanilla-utils/src/debugUtils.ts

Various small visual bug fixes for the theme editor page,
Companion PR: https://github.com/vanilla/internal/compare/feature%2Frename-class?expand=1

Various small visual bug fixes for the theme editor page

---

applications/vanilla/js/post.js

backporting https://github.com/vanilla/vanilla/pull/10142 (2020.003)

Backport: Fix save draft button when starting a new discussion (2020.003)

---

library/src/scripts/banner/bannerStyles.ts
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/features/tiles/tileStyles.ts

Fixes alignment issue with search placeholder.
Closes: https://github.com/vanilla/knowledge/issues/1603

Search placeholder alignment

---

applications/dashboard/src/scripts/entries/admin.tsx
applications/dashboard/src/scripts/roles/MultiRoleInput.tsx
applications/dashboard/src/scripts/roles/RoleActions.ts
applications/dashboard/src/scripts/roles/roleHooks.ts
applications/dashboard/src/scripts/roles/roleReducer.ts
applications/dashboard/src/scripts/roles/roleTypes.ts
library/src/scripts/forms/select/Tokens.tsx
packages/vanilla-utils/src/typeUtils.ts

Working towards https://github.com/vanilla/knowledge/issues/1584
This PR adds the multi-role input for that task.

Add a role token input

---

applications/dashboard/src/scripts/entries/forum.tsx

Fixes https://github.com/vanilla/support/issues/1508

Fix user content translation happening too early

---

applications/dashboard/src/scripts/entries/forum.tsx

backporting https://github.com/vanilla/vanilla/pull/10172

Backport: Fix user content translation happening too early (2020.005)

---

applications/dashboard/src/scripts/entries/forum.tsx

backports https://github.com/vanilla/vanilla/pull/10172

Backport: Fix user content translation happening too early (2020.004)

---

library/src/scripts/content/userContentStyles.ts

backports https://github.com/vanilla/vanilla/pull/10178
closes https://github.com/vanilla/support/issues/1534

Backport: Remove UserContent inline styles(2020.004)

---

applications/dashboard/controllers/api/RolesApiController.php
applications/dashboard/controllers/api/UsersApiController.php
library/Vanilla/Exception/PermissionException.php
library/Vanilla/Models/PermissionFragmentSchema.php
library/Vanilla/Permissions.php
library/Vanilla/PermissionsTranslationTrait.php
library/Vanilla/Web/UserSmartIDResolver.php
library/src/scripts/__tests__/TestReduxProvider.tsx
library/src/scripts/errorPages/CoreErrorMessages.tsx
library/src/scripts/features/users/Permission.test.tsx
library/src/scripts/features/users/Permission.tsx
library/src/scripts/features/users/UserActions.ts
library/src/scripts/features/users/userModel.ts
tests/APIv2/UsersTest.php
tests/Library/Vanilla/PermissionsTest.php
tests/Library/Vanilla/Web/SmartIDMiddlewareTest.php

Backport https://github.com/vanilla/vanilla/pull/10171
Backport https://github.com/vanilla/vanilla/pull/10185
Backport https://github.com/vanilla/vanilla/pull/10192

[Backport 2020.005] Add additional core permission utils and /api/v2/users/:id/permissions

---

applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts
plugins/rich-editor/src/scripts/quill/components/blotStyles.ts

[Backport 2020.005] Move content heading styles to compat styles

---

environment.php

Bump up version to 005 in Environment.php

Bump up version to 005 in Environment.php

---

environment.php

Increment release number to .005

Increment release number to .005

---

library/src/scripts/banner/Banner.tsx
library/src/scripts/banner/banner.story.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/features/search/SearchBar.tsx
library/src/scripts/layout/components/containerStyles.ts
library/src/scripts/styles/styleHelpers.ts
library/src/scripts/styles/styleHelpersBackgroundStyling.ts
library/src/scripts/styles/styleHelpersBorders.test.ts
library/src/scripts/styles/styleHelpersColors.ts
library/src/scripts/styles/styleHelpersSpacing.ts
library/src/scripts/styles/styleUtils.ts

- Added new position for search bar `banner.options.searchPlacement` "middle" or "bottom" supported
- This "search strip" may have
- its own background color/gradient `banner.searchStrip.bg`
- a minHeight: `banner.searchStrip.minHeight`
- vertical offset: `banner.searchStrip.offset`
Examples in Story book.

New Banner variables - seach position, new background options

---

library/src/scripts/content/userContentStyles.ts

Working towards https://github.com/vanilla/knowledge/issues/1661

Fix iframe width on user content and add simple table styles

---

library/src/scripts/features/swagger/swaggerStyles.scss

[Backport 2020.006] Fix try it openapi embed inputs

---

library/src/scripts/banner/Banner.tsx
library/src/scripts/banner/banner.story.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/features/search/IndependentSearch.tsx
library/src/scripts/features/search/SearchBar.tsx

Backport the search result getting cut off fix from https://github.com/vanilla/vanilla/pull/10263

[Backport 2020.006] Fix banner search cutoff

---

applications/dashboard/src/scripts/compatibilityStyles/index.ts
applications/dashboard/src/scripts/compatibilityStyles/messagesStyles.ts
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
library/src/scripts/headers/titleBarStyles.ts
packages/vanilla-theme-core/scss/pages/_inbox.scss

Fixes contrast issues in title bar with the search and the focus state of the mebox buttons. I also snuck an alignment issue with the messages.
Requries: https://github.com/vanilla/vanilla/pull/10268
Closes: https://github.com/vanilla/vanilla/issues/10252

Foundation - Fixed titleBar and messages issues

---

applications/dashboard/src/scripts/forms/DashboardSelect.tsx
library/src/scripts/theming/ThemeChooserInput.tsx

This add adds new ThemeChooseInput with will display all available themes.
accompanying pr for https://github.com/vanilla/multisite/pull/351
required for https://github.com/vanilla/multisite/issues/349

New Theme Choose Input component

---

environment.php

Reference: https://github.com/vanilla/support/issues/1593

Update snapshot version 006

---

environment.php

Reference: https://github.com/vanilla/support/issues/1593

Increment product version

---

applications/dashboard/src/scripts/compatibilityStyles/index.ts
applications/dashboard/src/scripts/compatibilityStyles/messagesStyles.ts
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
library/src/scripts/headers/titleBarStyles.ts
packages/vanilla-theme-core/scss/pages/_inbox.scss

Backport https://github.com/vanilla/vanilla/pull/10270

Backport  Foundation - Fixed titleBar and messages issues

---

library/src/scripts/utility/componentRegistry.tsx

Required for https://github.com/vanilla/internal/pull/2323

Have enabling and disabling of component theming clear the theme cache

---

applications/dashboard/src/scripts/compatibilityStyles/searchPageStyles.ts
applications/dashboard/src/scripts/forms/dashboardStyles.ts
library/src/scripts/features/search/searchBarStyles.ts
library/src/scripts/features/search/suggestedTextStyles.ts

Fixed bug where we were missing styles for the select's search options.
I also moved those styles into their own file and did some refactoring to keep things clean.

Refactored suggested text option styles to be in its own file.

---

library/Vanilla/Models/FsThemeProvider.php

Full site crashes aren't acceptable when loading a FS based theme, even if it is improperly configured.
If Debug is enabled, I've left this as an exception, and it will still crash the site and display an error message.
In production use it will now log a warning.

Fix FS themes crashing with an asset that doesn't exist

---

applications/dashboard/src/scripts/compatibilityStyles/index.ts
applications/dashboard/src/scripts/entries/admin.tsx
library/src/scripts/AppContext.tsx
library/src/scripts/banner/BannerContext.tsx

Fix bug where the banner background image wasn't getting passed to the forum side.
Closes: https://github.com/vanilla/vanilla/issues/10273

Fix banner on Forum not loading variable from theming system.

---

library/src/scripts/theming/ThemeChooserInput.tsx

Sets label to `Default ({currrentTheme})` when initialValue is null.
relates to https://github.com/vanilla/multisite/issues/349

Set default label to currentTheme if not theme is selected

---

applications/dashboard/src/scripts/entries/admin.tsx
library/src/scripts/flyouts/items/DropDownSection.tsx
library/src/scripts/forms/themeEditor/ThemeInfoTooltip.tsx
library/src/scripts/styles/globalStyleVars.ts

Closes https://github.com/vanilla/knowledge/issues/1696
Closes https://github.com/vanilla/knowledge/issues/1695
It's particularly problematic (for a few reasons) to have theme UI point to an array element, so I've moved the google font family into it's own variable which gets generated into our default font.
I also fixed 2 other bugs.
- BodyCSS no longer applying to the theme UI.
- We were using the wrong icon in our theme info tooltips.
Internal PR to update theme UI https://github.com/vanilla/internal/pull/2344

Fix some bugs in theme UI

---

library/Vanilla/Web/Asset/InlinePolyfillContent.js.twig
library/Vanilla/Web/ContentSecurityPolicy/ContentSecurityPolicyModel.php
library/src/scripts/styles/styleHelpersSpacing.ts

[Backport 2020.006] Fix backwards compatibility with old browsers 

---

library/core/class.dispatcher.php

I am planning to do some surgery on some of our core shortly. Ahead of that, I want to fix up some old lint errors so that there is less code affecting those functional PRs.

Clean up lint issues in Gdn_Dispatcher

---

applications/dashboard/scss/src/_forms.scss
applications/dashboard/src/scripts/forms/DashboardForm.story.tsx
applications/dashboard/src/scripts/forms/DashboardRadioGroups.tsx
build/.storybook/addons.js
library/src/scripts/forms/checkRadioStyles.ts

Add story for styles used on https://github.com/vanilla/internal/pull/2322
**This PR is a dependency for:**
https://github.com/vanilla/internal/pull/2322

Add DashboardRadioGroups grid story

---

environment.php

Removed 'SNAPSHOT' to prepare for staging deploy.

remove SNAPSHOT

---

applications/dashboard/src/scripts/compatibilityStyles/textLinkStyles.ts

Fixes styles for in this discussion plugin.
Style approved by @ElisaAlmeida 
Closes: https://github.com/vanilla/internal/issues/2336

Foundation - Fix styles for In this discussion plugin

---

applications/vanilla/models/class.discussionmodel.php

Closes https://github.com/vanilla/support/issues/1696.

Make sure discussion API calls don’t fail with empty types

---

environment.php

Reference: https://github.com/vanilla/support/issues/1715

Increase version to 008-SNAPSHOT

---

library/src/scripts/@types/api/core.ts
library/src/scripts/flyouts/dropDownStyles.ts
library/src/scripts/flyouts/panelNav/PanelNavItems.tsx
library/src/scripts/navigation/SiteNav.tsx
library/src/scripts/navigation/SiteNavNode.tsx
library/src/scripts/navigation/siteNavStyles.ts

required for https://github.com/vanilla/knowledge/issues/1531
companion pr https://github.com/vanilla/knowledge/pull/1742

Add visible header in nav and fix line height issue in hamburger menu

---

applications/conversations/controllers/api/MessagesApiController.php

backporting https://github.com/vanilla/vanilla/pull/10418

Backport: Fix conversation message MaxLength config (2020.007)

---

library/core/class.controller.php

I am planning to do some surgery on some of our core shortly. Ahead of that, I want to fix up some old lint errors so that there is less code affecting those functional PRs.

Cleanup code lint issues on Gdn_Controller

---

plugins/editor/views/editor.php

Closes https://github.com/vanilla/support/issues/1272.

Default advanced editor’s placeholder to https

---

library/Vanilla/Database/Operation/Pipeline.php
library/Vanilla/Models/PipelineModel.php
tests/Library/Vanilla/Database/PostProcessorTest.php
tests/fixtures/src/Database/ProcessorFixture.php

Working towards https://github.com/vanilla/knowledge/issues/1685
In order to run a processor after the main action we have to track them separately.
I've implemented the ability to register post processors for a model and added some tests for them.

Implement post processors for the pipeline model

---

library/src/scripts/forms/InputTextBlock.tsx

That input text class was doing more harm than good.

Removed problematic class on translation grid input

---

library/src/scripts/banner/Banner.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts

Backport https://github.com/vanilla/vanilla/pull/10410

[Backport] Fix banner search strip positioning and home widget background

---

library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/navigationVariables.ts

Fixes https://github.com/vanilla/knowledge/issues/1509

Fix double subcommunity slug getting into sign-in redirect target

---

library/Garden/SphinxTrait.php
library/Vanilla/Adapters/SphinxClient.php

SphinxClient converted from original sphinxapi.php
to PSR-2, PSR-4 friendly class to avoid unnecessary installation and deployment manipulations
Tests located in independent repositories.
Relates to: https://github.com/vanilla/internal/issues/2354

Introduce SphinxClient  to replace aphinxapi.php

---

applications/dashboard/src/scripts/compatibilityStyles/forumTagStyles.ts
applications/vanilla/modules/class.tagmodule.php

Backport of https://github.com/vanilla/vanilla/pull/10447

Backport of #10447 - Revert tag cloud tag 

---

library/src/scripts/banner/Banner.tsx
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/banner/contentBannerStyles.tsx
library/src/scripts/forms/themeEditor/ThemeBuilder.styles.ts
library/src/scripts/forms/themeEditor/ThemeBuilderBlock.tsx
library/src/scripts/forms/themeEditor/ThemeBuilderCheckBox.tsx
library/src/scripts/forms/themeEditor/ThemeBuilderFontBlock.tsx
library/src/scripts/forms/themeEditor/ThemeInfoDocs.tsx
library/src/scripts/forms/themeEditor/ThemeInfoTooltip.tsx
library/src/scripts/forms/themeEditor/ThemeInputNumber.tsx
library/src/scripts/forms/themeEditor/ThemeInputText.tsx

Working on https://github.com/vanilla/internal/issues/2412
Blocking https://github.com/vanilla/internal/pull/2420

Address Theme UI feedback

---

applications/dashboard/src/scripts/entries/forum.tsx
js/flyouts.js

Fixes a couple bugs with flyout and modal rendering in foundation.
|Bug|Before|After|
|---|---|---|
|Modal Background|![image](https://user-images.githubusercontent.com/1770056/79607698-b01dae00-80c1-11ea-8523-f8870450f27b.png)|![image](https://user-images.githubusercontent.com/1770056/79607617-7ea4e280-80c1-11ea-9586-c7c35bf82d38.png)
|Mobile Flyouts|![image](https://user-images.githubusercontent.com/1770056/79607680-a6944600-80c1-11ea-92e6-5915c61fc4b3.png)|![image](https://user-images.githubusercontent.com/1770056/79607652-941a0c80-80c1-11ea-9335-02416d033a10.png)|

Fix flyout and modal bugs in foundation

---

applications/dashboard/views/message/edit.php

Closes https://github.com/vanilla/support/issues/1732

Add info to message field in mod messages

---

environment.php

Increase version to 009.
Reference: https://github.com/vanilla/support/issues/1755

Update master environment.php to 009

---

library/src/scripts/flyouts/dropDownStyles.ts
library/src/scripts/forms/DatePicker.tsx
library/src/scripts/forms/datePickerStyles.ts
library/src/scripts/forms/dateRangeStyles.ts
library/src/scripts/icons/common.tsx
package.json
yarn.lock

Fixed date picker being cut off. It will work with right columns smaller than the flyout.
I also refactored some old style code to the newer format.
Adjusted stroke width of bookmark icons.
Closes: https://github.com/vanilla/knowledge/issues/1552

Date Picker Bug cut off fix

---

library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/navigationVariables.ts

Backport https://github.com/vanilla/vanilla/pull/10441/

Backport Fix double subcommunity slug getting into sign-in redirect target 

---

library/src/scripts/content/DateTime.tsx
packages/vanilla-i18n/src/localeStore.ts

Backport https://github.com/vanilla/vanilla/pull/10495

[Backport 2020.007] Fix crashes with regional locale keys

---

library/src/scripts/content/DateTime.tsx
packages/vanilla-i18n/src/localeStore.ts

Backport https://github.com/vanilla/vanilla/pull/10495

[Backport 2020.008] Fix crashes with regional locale keys

---

library/src/scripts/content/DateTime.test.tsx
library/src/scripts/content/DateTime.tsx
package.json
packages/vanilla-i18n/src/localeStore.ts
yarn.lock

Closes https://github.com/vanilla/support/issues/1767
Note I added react's official testing library along with this for the tests, which is why you are seeing the changes to package.json and yarn.lock

Fix crashing with regional locale key

---

applications/dashboard/src/scripts/compatibilityStyles/forumLayoutStyles.ts
applications/dashboard/src/scripts/compatibilityStyles/forumTagStyles.ts
applications/dashboard/src/scripts/compatibilityStyles/index.ts
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/titleBarStyles.ts
library/src/scripts/styles/tagStyles.ts

This PR fixes various spacing/padding issues with Foundation's layout.
I also snuck in a responsive bug fix and a tag color fix.
Closes: https://github.com/vanilla/vanilla/issues/10227
Closes: https://github.com/vanilla/vanilla/issues/10493

Foundation Layout spacing

---

library/Vanilla/Scheduler/Job/JobExecutionStatus.php

+ Add JobExecutionStatus `intended` and `unknown`

add JobExecutionStatus intended and unknown

---

.circleci/config.yml
build/scripts/build.ts
build/scripts/configs/makeBaseConfig.ts
build/scripts/utility/moduleUtils.ts

Backport: https://github.com/vanilla/vanilla/pull/10498

[Backport 2020.008] Fix vendor.min.js es5 compatibility

---

library/Vanilla/Scheduler/Job/JobExecutionStatus.php

Backport #10510 to `release/2020.008`

Backport #10510 - Scheduler - add intended and unknown status

---

applications/dashboard/controllers/api/ThemesApiController.php
applications/dashboard/controllers/api/ThemesApiSchemes.php
library/Vanilla/Models/FsThemeMissingTrait.php
library/Vanilla/Models/FsThemeProvider.php
library/Vanilla/Models/ThemeModel.php
library/Vanilla/Theme/ThemeProviderInterface.php

Implement `getThemeRevisions()` for ThemeProviderInterface
Relates to: https://github.com/vanilla/knowledge/issues/1772

Implement getThemeRevisions() for ThemeProviderInterface

---

applications/dashboard/views/modules/me.php

closes https://github.com/vanilla/support/issues/1785
- Report a post as spam
- check the count.

Fix spam count not displaying in memodule

---

applications/dashboard/settings/structure.php

This will address some the issues in this issue vanilla/support#1772 . When we do updates and/or run utility/structure we get complaints that they fail. The consequences are not serious but it creates a lot of noise.
Do a utility structure with and with out this branch.

Fix update to timestamp fields on structure updates.

---

library/Vanilla/Models/ThemeModel.php

Fix crashes with recent DB updates.
Re: https://vanillaforums.slack.com/archives/C02RHA2NA/p1588098706115400

Fix theme model crashing on normalize

---

applications/dashboard/src/scripts/compatibilityStyles/forumLayoutStyles.ts

Backport of the responsive fix in: https://github.com/vanilla/vanilla/pull/10492
Note the other changes aren't in here as they are not critical.

Backport - 10492 foundation responsive bug

---

library/src/scripts/banner/Banner.tsx
library/src/scripts/banner/BannerContext.tsx

Backport of https://github.com/vanilla/vanilla/pull/10534

Backport of #10534 Fixed sticky panel calculation

---

library/core/functions.framework.php

Fix a potential infinite loop in our theme model.
ThemeModel -> Calls something -> Calls `asset()` -> calls `assetVersion()` -> If the asset path has "/themes" then it goes to the theme model.
I broke the loop by switching to our standard deployment cache buster instead, which implements the same grace period, etc, but and which increments on every deploy or code change.

Fix infinite loop in assetVersion function

---

applications/dashboard/src/scripts/compatibilityStyles/groupsStyles.ts

Backport of table layout fix for groups

Backport for Groups table styles 

---

applications/dashboard/src/scripts/compatibilityStyles/groupsStyles.ts

Fixes broken table layout for groups.

Fix table styles for groups

---

environment.php

Remove SNAPSHOT from environment application version.

---

addons/themes/theme-foundation/assets/variables.json5

Backport https://github.com/vanilla/vanilla/pull/10559

Fix default navigation items missing

---

library/src/scripts/events/AttendanceStamp.tsx
library/src/scripts/events/Event.tsx
library/src/scripts/events/EventAttendanceDropDown.tsx
library/src/scripts/events/EventsFilter.tsx
library/src/scripts/events/EventsList.tsx
library/src/scripts/events/EventsPanel.tsx
library/src/scripts/events/eventOptions.ts
library/src/scripts/events/eventStyles.ts
library/src/scripts/events/events.story.tsx

This PR includes the components and styles for the panel's event list component. The logic for not displaying it if empty, the view all and the actual placement are not part of this PR. This is strictly styling for the main component.
Closes: https://github.com/vanilla/internal/issues/2478

Event List for Panel

---

applications/vanilla/library/Jobs/UpdateDiscussionCount.php
applications/vanilla/models/class.categorymodel.php
applications/vanilla/models/class.discussionmodel.php

backporting https://github.com/vanilla/vanilla/pull/10526

Backport: Fix deleting discussion timeouts (2020.009)

---

applications/dashboard/src/scripts/compatibilityStyles/index.ts
library/src/scripts/layout/panelLayoutStyles.ts

added new media query for above one column

added new media query for above one column

---

applications/dashboard/src/scripts/compatibilityStyles/index.ts
library/src/scripts/flyouts/NewPostMenu.tsx
library/src/scripts/flyouts/newPostMenuStyles.ts
library/src/scripts/styles/shadowHelpers.ts

Implements a few changes requested by our designer. Note that the focus styles require keyboard access. The focus styles are invisible to mouse users.
Closes: https://github.com/vanilla/vanilla/issues/10323

Designer Feedback on new Post Menu

---

library/Vanilla/Schema/RangeExpression.php
tests/Library/Vanilla/RangeExpressionTest.php

Check the docblock for the class for more information.

Add the RangeExpression class

---

library/core/class.form.php
tests/Library/Core/FormTest.php

This PR is meant to add some basic smoke test coverage for the `Gdn_Form` class. I have also added some fixes where I find bugs, and fixes for code style issues.

Add tests and fixes for Gdn_Form

---

applications/dashboard/src/scripts/compatibilityStyles/index.ts
applications/dashboard/src/scripts/compatibilityStyles/photoGridStyles.ts
library/src/scripts/forms/buttonTabs/buttonTabStyles.ts

The forum's styles were interfering with the event list styles. I had to bump up specificity and rest a few values.
The mobile styles for the events attendance buttons were changed. Note that responsive issues with different text lengths were discussed and the "stretching" style for the mobile style is intentional. 
Fixed some spacing issues in the panel.
Companion PR: https://github.com/vanilla/internal/pull/2543
Working towards: https://github.com/vanilla/internal/issues/2535

Designer Feedback for Panel

---

library/Vanilla/FileUtils.php
library/Vanilla/UploadedFile.php
tests/Library/Vanilla/UploadedFileTest.php

Backport https://github.com/vanilla/vanilla/pull/10598

[Backport 2020.009] Fix file uploads for images with spaces

---

tests/Bootstrap.php

This was causing notices in tests.

Remove self alias in the test bootstrap

---

library/core/class.oauth2.php

related https://github.com/vanilla/support/issues/1829

Increase oauth2 connect timeout

---

tests/Bootstrap.php

There are two Mustache addons: mustache and Mustache. We're ignoring one. Now, we'll ignore the other.

Add exception to test autoloader

---

bootstrap.php
library/Vanilla/Models/SiteMeta.php
library/Vanilla/Web/ContentSecurityPolicy/DefaultContentSecurityPolicyProvider.php
library/Vanilla/Web/ContentSecurityPolicy/VanillaWhitelistContentSecurityPolicyProvider.php

- Adds VanillaWhitelistContentSecurityPolicyProvider
- Add ReCaptcha public key to siteMeta
required for https://github.com/vanilla/knowledge/issues/1826

Updates for reCaptchav3

---

applications/dashboard/Events/NotificationEvent.php
applications/dashboard/controllers/api/NotificationsApiController.php
applications/dashboard/models/class.activitymodel.php
applications/dashboard/models/class.usermodel.php
library/Garden/Events/ResourceEvent.php
tests/Models/ActivityModelTest.php

backporting https://github.com/vanilla/vanilla/pull/10633

Backport: Add resource event dispatching for user notifications (2020.010)

---

library/src/scripts/utility/appUtils.tsx

required for https://github.com/vanilla/knowledge/pull/1833

Add utility method to ensure reCaptcha script is loaded

---

packages/vanilla-dom-utils/package.json
packages/vanilla-eslint-config/package.json
packages/vanilla-i18n/package.json
packages/vanilla-polyfill/package.json
packages/vanilla-prettier-config/package.json
packages/vanilla-react-utils/package.json
packages/vanilla-theme-core/package.json
packages/vanilla-tsconfig/package.json
packages/vanilla-utils/package.json

Add licenses for all NPM packages.

Fix package licenses

---

library/Vanilla/Models/SiteMeta.php
library/Vanilla/ReCaptchaVerification.php
plugins/recaptcha/addon.json
plugins/recaptcha/class.recaptcha.plugin.php
plugins/recaptcha/views/settings/registration.php

- Add a ReCaptchaVerification Class
- Updates reCaptchaPlugin to allow adding reCaptchaV3 keys
required for https://github.com/vanilla/knowledge/pull/1833

Add ReCaptchaVerification Class and update reCaptchaV3 plugin

---

library/src/scripts/content/NumberFormatted.styles.tsx
library/src/scripts/content/NumberFormatted.tsx

Added some missing reset for the text decoration of this element.

Fix text-decoration on `NumberFormatted`

---

library/database/class.sqldriver.php
plugins/ProfileExtender/class.profileextender.plugin.php

Closes https://github.com/vanilla/vanilla-patches/issues/692

Quote the profile extender export

---

applications/dashboard/src/scripts/forms/dashboardStyles.ts
applications/vanilla/src/scripts/forms/CommunityCategoryInput.tsx
applications/vanilla/views/categories/helper_functions.php
library/src/scripts/forms/InputBlockStyles.tsx
library/src/scripts/forms/inputStyles.ts
library/src/scripts/forms/select/Tokens.tsx
library/src/scripts/forms/select/tokensStyles.ts
plugins/pockets/src/scripts/conditions/PocketCategoryInput.tsx
plugins/pockets/src/scripts/conditions/PocketMultiRoleInput.tsx

Fixes mismatched styles for react inputs in dashbaord.
Working towards: https://github.com/vanilla/internal/issues/2591

Fix styles for dashboard's token and category inputs

---

library/Vanilla/Theme/ThemePreloadProvider.php

Fixes https://github.com/vanilla/internal/issues/2597

Fix forced theme preview revision ID getting set incorrectly

---

library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts
library/src/scripts/homeWidget/HomeWidgetItem.styles.ts

Issue https://github.com/vanilla/knowledge/issues/1807
Blocking https://github.com/vanilla/knowledge/pull/1844

Tweak some types for home widgets

---

applications/vanilla/views/categories/helper_functions.php

As we don't have any event  to be able to add some more data for category-heading currently, (and currently there is a need to have it) created and event hook in appropriate place.

add event in category type heading

---

environment.php

Remove "SNAPSHOT" from the environment.php file

Remove snapshot from env.php

---

library/src/scripts/forms/themeEditor/ThemeBuilderContext.tsx
library/src/scripts/forms/themeEditor/ThemeInputText.tsx
library/src/scripts/headers/navigationVariables.ts

Related https://github.com/vanilla/knowledge/issues/1783
Blocker for https://github.com/vanilla/internal/pull/2617

Add placeholder to ThemeInputText and add navigation variables to the theme editor variables

---

library/Vanilla/Theme/Asset/JsonThemeAsset.php
tests/Library/Vanilla/Theme/JsonThemeAssetTest.php

Fixes https://github.com/vanilla/internal/issues/2620
Look at the added tests for value coercion to understand what the issue was.
I've added a bunch of tests because this has happened before.

Fix coercion of array values into objects in jsonAsset

---

library/Vanilla/Theme/Asset/JsonThemeAsset.php
tests/Library/Vanilla/Theme/JsonThemeAssetTest.php

Backport #10695
Issue https://github.com/vanilla/internal/issues/2620

[Backport 2020.011] Fix coercion of array values into objects in jsonAsset

---

tests/fixtures/src/MockSiteSectionProvider.php

required for https://github.com/vanilla/knowledge/pull/1853

Add new mockSiteSectionGroup with only one section

---

applications/dashboard/controllers/class.settingscontroller.php
applications/dashboard/design/admin.css
applications/dashboard/design/style-compat.css
applications/dashboard/scss/style-compat.scss
library/src/scss/utility/_scaffolding.scss

I accidentally disabled pointer events for the dashboard graphs. I made my style more specific. Note that i also added a "dashboard" class to the dashboard home, because it used a different casing for that page than the analytics page...

Fix dashboard svg pointer events

---

plugins/ProfileExtender/class.profileextender.plugin.php

Add visit count to the profile extender export

---

applications/vanilla/views/categories/helper_functions.php
applications/vanilla/views/discussion/discussion.php
applications/vanilla/views/modules/discussionfilter.php
applications/vanilla/views/modules/helper_functions.php

Looks like i missed an import in my last commit, causing an error on my categories page. I also did a search for any other references and made sure to always import the utils.

Fixed a few imports for HTMLUtils

---

applications/vanilla/views/vanillasettings/editcategory.twig

Backport
Closes https://github.com/vanilla/vanilla/issues/10106.

Fix debug mode template errors in category settings view

---

applications/dashboard/modules/class.guestmodule.php
applications/dashboard/views/modules/guest.php

Reference: https://github.com/vanillaforums/oracle/issues/10
**Goal:** Make the GuestModule more flexible
**What this PR does:**
- Add CSS classes to elements on the view so those can be targeted more easily.
- Pass Signin and Register URLs as data leveraging logic from the view.

Make the GuestModule more flexible

---

.github/dependabot.yml

We only want to update lockfile depedencies.

Update the depend bot strategy

---

applications/dashboard/src/scripts/compatibilityStyles/fontStyles.ts
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
library/src/scripts/headers/titleBarStyles.ts
library/src/scripts/headers/vanillaHeaderStyles.ts
library/src/scripts/sectioning/tabStyles.ts
library/src/scripts/styles/globalStyleVars.ts
library/src/scripts/styles/styleHelpersColors.ts
library/src/scripts/theming/ThemePreviewCard.tsx

This function has too many parameters to not use object as a parameter.

Refactored props of modifyColorBasedOnLightness to an object instead of multiple parameters

---

library/Vanilla/Theme/Asset/JsonThemeAsset.php
library/Vanilla/Theme/Asset/NeonThemeAsset.php
library/Vanilla/Theme/Theme.php
tests/Library/Vanilla/Theme/JsonThemeAssetTest.php
tests/Library/Vanilla/Theme/NeonThemeAssetTest.php
tests/Library/Vanilla/Theme/ThemeCacheTest.php

Fixes https://github.com/vanilla/vanilla/issues/10725
Another in the saga of our JSON decoding.
I've had to make some tradeoffs and remove one of the the existing tests. This one is more important than that one, but I'll have to talk to @tburry and come up with a better strategy going forwards.

Fix some edge cases with arrays in json/neon decoding

---

library/Vanilla/Theme/Asset/JsonThemeAsset.php
library/Vanilla/Theme/Asset/NeonThemeAsset.php
library/Vanilla/Theme/Theme.php
tests/Library/Vanilla/Theme/JsonThemeAssetTest.php
tests/Library/Vanilla/Theme/NeonThemeAssetTest.php
tests/Library/Vanilla/Theme/ThemeCacheTest.php

[Backport 2020.011] Fix some edge cases with arrays in json/neon decoding

---

library/src/scripts/errorPages/CoreErrorMessages.tsx
library/src/scripts/headers/TitleBar.tsx
library/src/scripts/headers/mebox/pieces/TitleBarNavItem.tsx

Fixes https://github.com/vanilla/vanilla/issues/10728

Fix sign in URLs on site served in a subdirectory

---

library/Vanilla/Logging/LogEntry.php
tests/Library/Vanilla/Logging/LogEntryTest.php
tests/ObjectTestTrait.php

This PR adds some new convenience methods and withers to round out the class functionality.

Enhance the LogEntry class

---

library/core/class.dispatcher.php

related https://github.com/vanilla/internal/pull/2608
This add a dispatcher method addBlockException for https://github.com/vanilla/vanilla/blob/885b7dca3759a02c3489209a565898afa40b141f/library/core/class.dispatcher.php#L34

add a blockexcpetion method to the dispatcher

---

applications/dashboard/src/scripts/compatibilityStyles/forumLayoutStyles.ts
applications/vanilla/library/Navigation/ForumBreadcrumbProvider.php
applications/vanilla/models/class.categorymodel.php
library/Vanilla/Site/DefaultSiteSection.php
library/Vanilla/Site/SiteSectionSchema.php
library/src/scripts/content/FromToDateTime.tsx
library/src/scripts/forms/select/SelectBox.tsx
library/src/scripts/layout/components/containerStyles.ts
library/src/scripts/sectioning/Tabs.story.tsx
library/src/scripts/sectioning/Tabs.tsx
library/src/scripts/sectioning/tabStyles.ts
library/src/scripts/utility/appUtils.tsx

Working towards https://github.com/vanilla/internal/issues/2547
- Add additional props for the `Tabs` browse styles. See the new story that was added.
- Add `Attributes` to `SiteSectionInterface` json.
- Adjust various breadcrumb links to work with subdirectory sites.

Core work for the All Events page

---

js/flyouts.js

Closes https://github.com/vanilla/support/issues/2061
Closes https://github.com/vanilla/support/issues/2060
**Steps to reporduce:**
- Enable boostrap3 theme on your local
- Try opening any flyout
- Checkout this branch
**Further Testing:**
- Test it lithe (mobile)
- Test it with PennyArcade theme
**Notes:**
- Issue introduced here: https://github.com/vanilla/vanilla/pull/10615
**Backport:**
https://github.com/vanilla/vanilla/pull/10742

Rollback flyouts touchstart event change

---

packages/vanilla-dom-utils/src/shadowDom.tsx

Backport #10706
Issue https://github.com/vanilla/support/issues/2036

[Backport 2020.011] Make header shadow dom mounting work in edge

---

js/flyouts.js

Backport: https://github.com/vanilla/vanilla/pull/10752

[Backport] Fix legacy themes mobile flyouts

---

library/Vanilla/Theme/Theme.php
tests/Library/Vanilla/Theme/ThemeServiceCurrentTest.php

Fixes https://github.com/vanillaforums/king/issues/247

Fix how we overlay variables so that they replace array elements

---

library/Vanilla/UploadedFile.php
tests/Library/Vanilla/UploadedFileTest.php

Backport https://github.com/vanilla/vanilla/pull/10740
Issue https://github.com/vanilla/support/issues/1962

[Backport 2020.011] Fix encoding on file names.

---

applications/dashboard/models/BannerImageModel.php
bootstrap.php

These are some small optimizations that are hopefully okay to do this close to a release.
- There is an every page component that was querying without an available cached endpoint.
- Models were not shared which would cause duplicates to query for their schema info multiple times.

Release optimizations

---

applications/vanilla/openapi/discussions.yml
library/Vanilla/OpenAPIBuilder.php
library/Vanilla/Theme/Theme.php
library/Vanilla/Utility/ArrayUtils.php
tests/Library/Vanilla/OpenAPIBuilderTest.php
tests/Library/Vanilla/Theme/ThemeServiceCurrentTest.php
tests/Library/Vanilla/Utility/ArrayUtilsTest.php

Issue vanillaforums/king#247
Backport #10766
Backport of https://github.com/vanilla/vanilla/pull/10713 which is required for #10766

[Backport 2020.011] Fix how we overlay variables so that they replace array elements

---

applications/dashboard/models/class.activitymodel.php

Relates to vanilla/internal#2691

Improve caching of users in notification events

---

library/core/class.authenticationprovidermodel.php

Related https://github.com/vanilla/internal/issues/2691

Add caching for user auth providers

---

applications/dashboard/models/BannerImageModel.php
applications/dashboard/models/class.activitymodel.php
bootstrap.php
library/core/class.authenticationprovidermodel.php

Forward port various backports

---

composer.json
composer.lock

Note that there is a misnomer in the branch name.

Update jsConnect to 3.2.1

---

environment.php

Reference: https://github.com/vanilla/support/issues/2125

Update APP_VERSION to 4.0-2020.013-SNAPSHOT

---

addons/themes/theme-boilerplate/package.json
packages/vanilla-theme-core/package.json

I need to publish theme-boilerplate to update a theme that has this package as a dependency.
Reference: https://github.com/vanilla/support/issues/1863

Increase theme-boilerplate version

---

tests/Library/Vanilla/Utility/DomUtilsTest.php

Type hint DomUtilsTest:: testTrimWords

add type hinting DomUtilsTest

---

applications/vanilla/models/class.categorymodel.php
applications/vanilla/models/class.commentmodel.php
tests/Models/CountsTest.php
tests/Models/TestCategoryModelTrait.php
tests/Models/TestCommentModelTrait.php
tests/Models/TestDate.php
tests/Models/TestDiscussionModelTrait.php

Note: This includes some commented out failing tests. I want to get this code committed and work on some fixes that don’t impact our site before tacking those failing tests.

Fix and add functionality to the model test traits

---

applications/dashboard/src/scripts/compatibilityStyles/categoriesStyles.ts
applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts
applications/dashboard/src/scripts/compatibilityStyles/forumMetaStyles.ts
applications/dashboard/src/scripts/compatibilityStyles/index.ts
library/src/scripts/banner/bannerStyles.ts
library/src/scripts/forums/forumStyleVars.ts
library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
library/src/scripts/styles/globalStyleVars.ts

Backport https://github.com/vanilla/vanilla/pull/10798

[Backport 2020.012] Increase flexibility of Foundation by introducing new styling variables

---

applications/dashboard/controllers/class.sessioncontroller.php

This method is only called through our js `stash()` function which will post the proper headers and TK.
Closes https://github.com/vanilla/vanilla-patches/issues/687.

Check for an authenticated postback on /session/stash

---

library/src/scripts/search/searchReducer.ts
library/src/scripts/styles/typographyStyles.ts

- Fixes extra margin being applied in the new search page title (some reset missing).
- Fixes types not being cleared when domain changes.

Fix some new search issues

---

applications/vanilla/controllers/api/CategoriesApiController.php
applications/vanilla/src/scripts/categories/CategorySuggestionActions.ts
library/src/scripts/forms/select/SelectLookup.tsx
library/src/scripts/forms/select/SelectOne.tsx

From the demo.
No longer requires you to type some query.

Update category search dropdown to get results immediately

---

applications/dashboard/modules/class.pagermodule.php

Backport: https://github.com/vanilla/vanilla/pull/10853

Fix previous link page error (backport)

---

addons/themes/theme-foundation/assets/variables.neon
packages/vanilla-dom-utils/src/shadowDom.tsx

Issue https://github.com/vanilla/support/issues/2130

Fix incorrect docs in theme variables and bad checking of html chars

---

environment.php

Remove the DEV environment Snapshot.

Remove snapshot.

---

environment.php
library/src/scripts/content/code.ts
library/src/scripts/routing/RouteHandler.tsx

Backport https://github.com/vanilla/vanilla-cloud/pull/28
Issue https://github.com/vanilla/support/issues/2211

Fix some module loading issues

---

library/src/scripts/content/code.ts
library/src/scripts/routing/RouteHandler.tsx

Backporting #10876 to `release/2020.013`.

Backport: Fix some module loading issues

---

environment.php

Incrementing the release version.
Bad backport snipped the "snapshot", so I'm re-adding that.

Increment release version

---

library/core/class.model.php
library/database/class.database.php
library/database/class.databasestructure.php
library/database/class.mysqldriver.php
library/database/class.mysqlstructure.php
library/database/class.sqldriver.php

This PR contains mostly doc block fixes. It also has some light refactoring such as:
1. I extracted some constants for LIKE expressions.
2. I added curly braces to some if statements in accordance to our standards.
3. There may be some misc code tweaks too.

Clean up the code in the database layer

---

library/src/scripts/headers/mebox/pieces/MeBoxDropDownItem.tsx

backport of https://github.com/vanilla/vanilla/pull/10858

[Backport 2020.013] - Verify if user information is defined.

---

library/src/scripts/features/search/IndependentSearch.tsx
library/src/scripts/features/search/searchBarStyles.ts

Backport https://github.com/vanilla/vanilla-cloud/pull/236

[Backport] Export props and fix button styles

---

composer.json
composer.lock

bump cloud-interops

---

build/entries/generatedStories.story.tsx

Restoring build/entries/generatedStories.story.tsx from last known-good state.

Restore build/entries/generatedStories.story.tsx
