- library/core/class.session.php
- tests/APIv2/Authenticate/AutoConnectTest.php
- tests/Models/CommentModelTest.php
The following case (which can happen in unit tests) was causing a bug where permissions were bugged:
```php
Gdn::session()->start($adminUserID, false, false);
Gdn::session()->start(false, false);
Gdn::session()->getPermissions()->hasAny('Garden.Settings.Manage'); // Returns true
```
The problem is that the admin flag is set but not properly removed from the permission object on subsequent call to `Gdn::session()->start()` if the session if not started with a valid user.
I opted to overwrite the whole permission object on each call to `Gdn::session()->start()` so that if we had other properties to the Permission object they will be reset without needing to update this code.
> Fix admin permission not being reset between tests

- tests/APIv2/AbstractResourceTest.php
This allow tests to change the way rows are generated which is useful when created resources can't have the same name or need their own parent resource to be created.
This update would let us redefine the generator function and increment the $recordCounter instead of [having to enable/disable a flag as a workaround](https://github.com/vanilla/internal/blob/3e1094b267b754c7c7a88f497a15741fb52470b4/applications/groups/tests/APIv2/GroupsTest.php#L83).
> Move AbstractResourceTest index's row generation in a separate function

- applications/vanilla/controllers/class.categoriescontroller.php
- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/models/class.categorymodel.php
- applications/vanilla/views/categories/all.php
- applications/vanilla/views/categories/discussions.php
- applications/vanilla/views/categories/table.php
- applications/vanilla/views/discussions/index.php
- applications/vanilla/views/discussions/table.php
- library/core/functions.general.php
- library/core/functions.render.php
This update alters the new "category following" feature in the following way:
1. Adds a new parameter to `paramPreference` function to control if the preference is saved.
1. Adds the ability to pass extra URL query string parameters to the `filtersDropDown` function.
1. Updates the root-category index and "recent discussions" page to require a "saved" query string parameter in the URL to save the current filter.
1. Adds "saved" parameter to filter dropdown menu URLs.
1. Adds `CategoryModel::followingEnabled` as a convenience method for checking the availability of the following feature.
1. Adds a new element to the controller data array (EnableFollowingFilter) to serve as a UI hint for displaying the "following" filter menu.
1. Adds an "EnableFollowingFilter" event to …
> Fix category following filters being saved without explicitly opting in

- library/Garden/Web/Dispatcher.php
This fixes a problem where "php" exception would be treated as successful response instead of errors because the error code could be in the 2xx range.
This was happening for E_USER_ERROR which has a value of 256. These kind of errors should be treated as internal errors when returned.
The problem was worse for unit test since we didn't get to see the error message because the response was a "success".
> Fix some error exception responses having an HTTP code in the 2xx (successful) range

- applications/vanilla/models/class.discussionmodel.php
- tests/APIv2/CommentsTest.php
- tests/APIv2/DiscussionsTest.php
#6446 added a fix for a permission issue related to the comments API index. This update adds some regression testing.
For testing purposes, I also added a parameter to `DiscussionModel::categoryPermissions` that will force a refresh of category permissions. Prior to this, once permissions were cached during a test, they were cached, indefinitely.
Closes #6484
> Add unit test for comments API and custom category permissions

- applications/dashboard/controllers/api/MediaApiController.php
- library/core/class.webscraper.php
- library/core/functions.general.php
- tests/APIv2/MediaTest.php
- tests/Bootstrap.php
- tests/fixtures/html/og.htm
This update adds the /media/scrape action to API v2.
The spec is outlined in the associated issue. Tests are included.
1. This is taking a lot of existing functionality from [`fetchPageInfo`](https://github.com/vanilla/vanilla/blob/36faa6b09a6f8c95dee8ed888d9c240cbba0cc2a/library/core/functions.general.php#L904) and [`Gdn_Format::embedReplacement`](https://github.com/vanilla/vanilla/blob/36faa6b09a6f8c95dee8ed888d9c240cbba0cc2a/library/core/class.format.php#L1388) and marrying it under the media endpoint for the purpose of assisting with embeds. The code is built to return very similar (identical, if possible) values to what we see when performing embeds with the aforementioned functions.
1. Tests are primarily split between gathering data via parsing a page and extracting information …
> Add /media/scrape to API

- applications/vanilla/controllers/api/CategoriesApiController.php
The schemas in `CategoriesApiController::put_follow` were using the default type ("in"). This causes an issue for API documentation generation, because no output schema was detected.
This update explicitly defines a type for both schemas.
Closes #6593
> Define schema types in PUT /categories/follow

- js/global.js
- library/core/class.format.php
Closes #6205 
Adds a function to Gdn_Format that adds `rel="noopener"` to and links with `target="_blank"`. This processing will only be run on formats containing html.
I initially looked into doing this in htmlawed but that seems unmaintainable and doing this with regex seems like it would be a mess.
@tburry Had proposed doing it client side with a javascript solution, but since I couldn't put together a good whitelist or blacklist of places to run/not run the sanitization I feel that a server side solution is necessary to properly implement this.
> Add noopener to all of the things

- bootstrap.php
- library/core/class.session.php
- library/core/helpers/class.ssoutils.php
- plugins/Facebook/class.facebook.plugin.php
- plugins/GooglePlus/class.googleplus.plugin.php
- tests/APIv0/AltTest.php
Closes https://github.com/vanilla/vanilla/issues/6513
- Move everything related to state token into SsoUtils
- Update SsoUtils to be an object instead of a class providing static methods
- Inject SsoUtils where needed
- Use \Garden\Web\Cookie
- I've added a shutdown handler function that calls Cookie::flush() so that cookies set through Cookie are sent to the browser
> Refactor SsoUtils

- applications/vanilla/models/class.categorymodel.php
3 "steps" of dba/counts are important here.
* Recalculate Category.LastDiscussionID
* Recalculate Category.LastCommentID
* Recalculate Category.LastDateInserted 
Previously we were updating the LastDiscussionID when the LastCommentID had a later date, but, our data set to compare the DateInserted from the Comment wasn't including discussions with no comments causing the wrong latest discussion to be used to update the category record (also to show up in the category page in certain themes).
This will in turn enable the 3rd step listed above to update the category records properly.
I also removed in this a few unnecessary lines.
`$lastDiscussionID` was never used.
We don't want to set LastCommentID to null when a discussion is the latest content inserted but instead returning the correct …
> Fix dba/counts overwriting Category.LastDiscussionID with older discussion

- applications/vanilla/models/class.categorymodel.php
Backport of https://github.com/vanilla/vanilla/pull/6585
> 3 "steps" of dba/counts are important here.
> 
> Recalculate Category.LastDiscussionID
> Recalculate Category.LastCommentID
> Recalculate Category.LastDateInserted
> Previously we were updating the LastDiscussionID when the LastCommentID had a later date, but, our data set to compare the DateInserted from the Comment wasn't including discussions with no comments causing the wrong latest discussion to be used to update the category record (also to show up in the category page in certain themes).
> 
> This will in turn enable the 3rd step listed above to update the category records properly.
> 
> I also removed in this a few unnecessary lines.
> 
> $lastDiscussionID was never used.
> 
> We don't want to set LastCommentID to null …
> Backport: Fix dba/counts overwriting Category.LastDiscussionID with older discussion 

- applications/dashboard/controllers/api/UsersApiController.php
- applications/dashboard/models/class.usermodel.php
- tests/APIv2/UsersTest.php
This update adds /users/by-names to API v2 for searching users by partial or full usernames. The primary intended functionality is to support \@mentions.
1. /users/by-names was chosen instead of attempting to add this functionality onto the index of /users, because the index was built for user management, similar to what is seen on the users dashboard page. Permissions are tightened down on the index and the data returned can contain potentially-sensitive information. Making the index accept different parameters or output different fields based on user permissions would likely be confusing to users and difficult to effectively document.
1. `UserModel::searchByName` (public method) has been added as a simple method for searching users by name, allowing wildcards in the search string.
1. …
> Add /users/name to API v2 for searching for users by name

- applications/vanilla/controllers/api/DiscussionsApiController.php
This update adds filtering by type to the discussions API v2 endpoint.
```
GET http://vanilla.localhost/api/v2/discussions?type=idea
```
Only discussions with the type "Idea" should be returned.
> Add filtering by type to discussions API v2 endpoint

- applications/vanilla/controllers/api/CommentsApiController.php
- applications/vanilla/controllers/api/DiscussionsApiController.php
These events allow plugins to normalize records if needed.
Useful for the "attributes" field. (Ideation, QnA..)
This ensure that every output record are properly updated.
> Discussion/Comment API normalization event

- library/Vanilla/Quill/Blots/TextBlot.php
This PR fixes the bad string matching check, so that it no longer attempts to render unknown blots as a string.
> Fix bad string fallback

- tests/APIv2/AddonsTest.php
I missed the travis notification on #6660. This PR removes the theme from the test because it's now hidden.
> Remove 2011 compat theme from addon test

- library/core/class.proxyrequest.php
`ProxyRequest::request` can send along cookies from the user's browser, but will always strip out [Xdebug cookies](https://xdebug.org/docs/remote#browser_session). This update allows the browser's Xdebug cookies to be sent, if the site is in debug mode. Useful when you want to debug server to server calls and both run in your environment.
> Forward client Xdebug cookies in ProxyRequest requests if in debug mode

- library/core/class.dispatcher.php
Closes https://github.com/vanilla/vanilla/issues/6671
Add block exception for /authenticate.
Bonus commits in this PR:
- Improves regexes
- Updated the delimiters so that we do not have to escape slashes
- Replace `(\/.*)?$` by `(/|$)` which essentially does the same thing but is clearer
- Reorder the block exceptions alphabetically
- Update `api/v\d+/applications` to `api/v\d+/applicants(/|$)`
- It was added here https://github.com/vanilla/vanilla/commit/e8cfd89825dbc830b6cd605dd66762e8ba625cf9 but we renamed applications to applicants  in https://github.com/vanilla/vanilla/pull/6140
- Fix "home/leave" to "home/leaving"
> Add block exception for authenticate in Gdn_Dispatcher

- applications/vanilla/controllers/api/CommentsApiController.php
- applications/vanilla/controllers/api/DiscussionsApiController.php
This update adds the "score" column to discussion and comment endpoint results.
Closes #6636
> Add score to post endpoint schemas

- applications/vanilla/controllers/api/CommentsApiController.php
- applications/vanilla/controllers/api/DiscussionsApiController.php
This update renames fired events because an event named` controller_method_path` would add an endpoint on that controller.
> Update names of comment and discussion API filter events

- library/Garden/EventManager.php
Pretty simple.
The function is named getAllHandlers because `getHandlers($name)` already exists.
I will also need that for https://github.com/vanilla/internal/issues/1416
> Allow to get the list of current handlers from the event manager

- applications/dashboard/models/class.usermodel.php
Moves the clearCache call to the only place where it is actually triggered.
Allows UserModel->getID() to returned fresh data when called from an handler of afterSave()
> Fix outdated user data in UserModel's AfterSave event

- applications/dashboard/controllers/api/TokensApiController.php
Signed tokens revealed in the "Access Tokens" area of a user's profile were not using the token's actual expiry, and instead using the current date/time. The signed tokens still work for API access, but could be confusing to users when seeing the last two dot-delimited portions (expiry and signature) changing after every reveal.
This update switches out the call to `AccessTokenModel::signToken` with `AccessTokenModel::signTokenRow` to use the token's true expiry when signing the token.
> Fix revealed token in profile not using row expiry

- library/core/class.session.php
The current method of checking for a new visit (`Gdn_Session::newVisit`) also updates the "visit" cookie. This update adds `Gdn_Session::isNewVisit`, a way to check for a new visit without updating the cookie. The logic for checking for a new session has been moved into the new method and reworked a bit. There should be no functional changes to the original method and it now uses `Gdn_Session::isNewVisit`.
> Add checking for new visit without updating cookie

- README.md
- applications/dashboard/settings/class.hooks.php
Vanilla 2.5 altered its version requirements warning in the dashboard to let users know PHP 5.6 support would be dropped with Vanilla 2.6. Now that Vanilla 2.6 is almost here, it's time to revert the warning message back to alerting users of the *current* version requirements.
This update alters the version requirements phrasing to state that anything less than PHP 7.0 is not current supported.
Closes #6365
> Update version requirements message in dashboard

- build/package-exclude.txt
The Phing build has an exception rule for files ending in "dist". This is primarily meant to keep unwanted files from dependencies or sub-builds from finding their way into the core Vanilla build. However, it has the additional effect of excluding .htaccess.dist from the build.
Phing's pattern matching rules are pretty rudimentary, so this update alters the "dist" exclusion rule to avoid applying it to root-level files. Since .htaccess.dist resides in the root directory of Vanilla, it is once again included in the build. Files ending in "dist" in subdirectories are still excluded.
Closes #6277
> Include .htaccess.dist in phing build

- plugins/rich-editor/README.md
- plugins/rich-editor/addon.json
Closes #6686 
Closes #6733
This PR adds a README for the rich editor, with some details on the project structure and a bit of information on getting started with Quill for use case. It's not 100% comprehensive, but it's a good start.
> Add README for the Rich Editor

- plugins/editor/js/wysihtml5-0.4.0pre.js
Closes #6621
This removes the libraries janky context-menu handling to use native browser undo/redo handling in the context menu. As a result the context-menu undo/redo items with not work editor created events such as formatting. This the case with our new rich editor at least for the time being.
For a little more context, before the library was attempting to detect the context-menu's undo/redo in the same way you would detect cmd-z/cmd-shift-z. This is broken in the latest versions of chrome in a pretty significant way and wasn't really a solid solution in the first place. Maybe we'll investigate other solutions in the future (such as if the browser adds a proper event handler, or using custom context-menu), but for now this will work.
> Remove hacky contextmenu handler in wysiwyg editor

- plugins/editor/js/wysihtml5-0.4.0pre.js
Backport of #6752 
Reference #6621
> This removes the libraries janky context-menu handling to use native browser undo/redo handling in the context menu. As a result the context-menu undo/redo items with not work editor created events such as formatting. This the case with our new rich editor at least for the time being.
>
> For a little more context, before the library was attempting to detect the context-menu's undo/redo in the same way you would detect cmd-z/cmd-shift-z. This is broken in the latest versions of chrome in a pretty significant way and wasn't really a solid solution in the first place. Maybe we'll investigate other solutions in the future (such as if the browser adds a proper event handler, or using custom context-menu), but for now this will work.
> [Backport] Remove hacky contextmenu handler in wysiwyg editor 

- library/core/class.format.php
Removes pQuery noopener handling. After talking with @tburry it seems this may be a little heavier than what we actually needed. The javascript solution added in #6591 should be sufficient.
> Remove pquery noopener handling

- library/Garden/Web/ResourceRoute.php
- tests/Library/Garden/Web/ResourceRouteTest.php
- tests/fixtures/src/DiscussionsController.php
Consider the following endpoints we’d want to create:
```http
GET /conversations/123/participants
GET /conversations/123/participants/1
```
Previously we would be unable to create these routes because they would
both have to be called `get_participants`.
This change allows you to also prefix GET methods with `index_`. The
prefix works the same way as `get_` but is a lower priority. They are
differentiated by different parameter counts.
The above example can be done with the following methods:
```php
public function index_participants($id) {
}
public function get_participants($id, $userID) {
}
```
> Allow the index_ prefix as an alternative to get_ prefixes

- applications/dashboard/controllers/api/AuthenticateApiController.php
- library/Vanilla/Models/SSOModel.php
Closes https://github.com/vanilla/vanilla/issues/6711
Allows to "authenticate" a user without a session being set.
This can be used to verify that everything works properly or sync users informations.
> Add setCookie and persist parameters to authenticate endpoint

- applications/dashboard/controllers/api/AuthenticateApiController.php
- library/Vanilla/Authenticator/SSOAuthenticator.php
- library/Vanilla/Models/AuthenticatorModel.php
- library/Vanilla/Models/SSOData.php
- library/Vanilla/Models/SSOModel.php
- tests/APIv2/Authenticate/AutoConnectTest.php
- tests/fixtures/src/TestSSOAuthenticator.php
Fixes https://github.com/vanilla/internal/issues/1381
Closes https://github.com/vanilla/vanilla/issues/6665
This PR does multiple things that kind of go together:
- Fix a bug where AutoConnect was ON if an authenticator was trusted. This should not happen.
- Create the AuthenticatorModel since there is a need for `getAuthenthicator(Type, ID)` from multiple places.
- Move isTrusted out of SSOData since we now have access to the authenticator instance by using AuthenticatorModel.
- Add the autoLinkUser property on SSOAuthenticator. This replaces the old global `Garden.Registration.AutoConnect` config.
- Update the unit tests to account for the fact that the autoConnect feature has been moved to the authenticators as autoLinkUser.
> Update SSOAuthenticator properties

- js/global.js
- js/library/jquery.atwho.js
- src/scripts/__tests__/legacy.test.js
Closes #6783
Closes #6165
Fixes the broken @mention behaviour.
Unicode characters can now be matched, just like punctuation. Like punctuation they must be quoted. Suggestions will be offered containing unicode characters if the first few characters are valid even without the quotes (this is just the current behaviour).
This was fixed both through a updated regex that now only looks at the current line of text. In order to fix the current line I had to fix the content-editable line detection that was broken. The issue was that a native `Range` when converted to a string, does not contain line breaks. At.who was trying to compensate by counting line breaks elements, but was counting line breaks in the entire editor, not up to the current cursor position. I got rid of the offset and now …
> Fix mention triggering in the editor

- applications/vanilla/models/class.discussionmodel.php
I thought "Hot" was separate from "None" as a sort option for ideation. I removed "None" as an option.
> Remove "none" from discussion sort options

- applications/dashboard/models/class.assetmodel.php
Since the core js isn’t a true addon the check needs to be done
separately. This fix doesn’t currently have an impact since there is no
core app, but it should when code needs to add core app functionality.
Closes #6807.
> Add the core app js if it exists

- applications/vanilla/controllers/class.categorycontroller.php
- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/models/class.categorymodel.php
- applications/vanilla/models/class.discussionmodel.php
- applications/vanilla/models/class.vanillasearchmodel.php
- applications/vanilla/modules/class.discussionsmodule.php
The UI for muting a category was phased out for category following with #6469. However, there still exists some functionality that needs to be walled off.
1. `CategoryController::follow` has been deprecated. This was formerly used to mute/unmute a category. Since we're shifting to following, this should no longer be used.
1. The recent discussions list no longer filters blacklisted (muted) categories.
1. Similar to the recent discussions page, `DiscussionsModule` no longer filters blacklisted (muted) categories.
1. `CategoryModel::categoryWatch` has been deprecated.
1. `CategoryModel::getVisibleCategories` has been added. The method gets categories a user has "view" access too, while allowing additional filtering (e.g. filtering by the `HideAllDiscussions` field).
1. …
> Phase out category muting in favor of category following

- library/core/class.format.php
This update conditionally adds `rel="nofollow"` to \@mention links, based on the value of `Gdn_Format::$DisplayNoFollow`.
> Fix Gdn_Format::formatMentionsCallback not respecting Gdn_Format::$DisplayNoFollow

- applications/vanilla/controllers/api/CategoriesApiController.php
- tests/APIv2/CategoriesTest.php
This update adds the ability to filter results from the index of the categories endpoint by their archived status. Per the original issue:
1. If `archived` is false (default), only return non-archived categories from the current tree.
1. If `archived` is true, only return archived categories from the current tree.
1. If `archived` is null (an empty value), don't filter by the archived status. Return both archived and non-archived categories.
Closes #6255
> Add filtering by archived status to categories API v2 endpoint

- applications/vanilla/controllers/class.discussionscontroller.php
There's currently no way for addons to hook in and modify the discussions displayed on the Recent Discussions page when the "following" filter is applied. This update adds usage of `CategoryModel::getVisibleCategoryIDs` to limit discussions by category. This method is hook-able, so addons can modify the result.
> Add ability for addons to modify followed recent discussions

- applications/dashboard/modules/class.pagermodule.php
`PagerModule` has been updated to add rel=prev/next link tags to the page head, as necessary, when the pager module is used.
1. `PagerModule::addRelLinks`, a private method, has been added. This method is responsible for updating the page head and setting the link response header. It is currently only called in `PagerModule::configure`.
1. Adding the link tags should only occur once. It doesn't matter if you write the pager once or ten times.
1. The first page of the pager has been normalized to have no page number. This is done for search engines, to avoid seemingly duplicating content (e.g. /discussions and /discussions/p1 being identical).
Closes #6522
> Add pagination link tags to page when using pager

- applications/dashboard/models/class.usermodel.php
- applications/vanilla/controllers/api/CommentsApiController.php
- applications/vanilla/controllers/api/DiscussionsApiController.php
This update adds a way for addons to easily hook into `UserModel::expandUsers` to add additional fields without needing to hook into individual endpoint normalization methods.
`UserModel::expandUsers` now throws a filter event: userModel_expandUsers. This event passes along the row(s), an indicator of whether or not this is a single row or multiple and an array of arbitrary options the method does not use, itself. This is primarily used for passing through additional data, such as the "expand" parameter from an API request, without it being required for basic model usage.
Closes #6786
> Add a hookable filter to UserModel::expandUsers

- applications/dashboard/models/class.updatemodel.php
Vanilla made a semi-recent update to using "addon.json" for addon info. Support for this method was implemented in `UpdateModel::analyzeAddon`, a deprecated method. However, the support didn't accommodate ZIP files. Addons, like Community, use this method to analyze such archives. If you had an addon in an archive with only addon.json for info (e.g. no fallback about.php), the analyzation would fail ("Could not parse addon info array.").
This update hopefully makes ZIP file handling more robust.
See https://github.com/vanilla/community/issues/135
> Improve ZIP file handling in UpdateModel::analyzeAddon

- applications/dashboard/controllers/class.authenticatecontroller.php
- plugins/vanillaconnect/VanillaConnectAuthenticator.php
- plugins/vanillaconnect/VanillaConnectPlugin.php
Closes https://github.com/vanilla/vanilla/issues/6801
Pretty simple, we store the nonce in a cookie to make sure that the same browser that initiated the process is trying to validate it. We also sign the nonce in a JWT to make sure that the cookie is not created from a leaked "sign in JWT".
> Add cookie validation to Vanillaconnect

- applications/dashboard/controllers/api/AuthenticatorsApiController.php
- library/Vanilla/Authenticator/Authenticator.php
- library/Vanilla/Models/AuthenticatorModel.php
- tests/APIv2/AuthenticatorsTest.php
Closes https://github.com/vanilla/vanilla/issues/6668
To test you can move MockAuthenticator and MockSSOAuthenticator from tests/fixtures/src into any plugins (dashboard application would do too) and add the following in our database:
```
INSERT INTO `GDN_UserAuthenticationProvider` (`AuthenticationKey`, `AuthenticationSchemeAlias`, `Name`, `URL`, `AssociationSecret`, `AssociationHashMethod`, `AuthenticateUrl`, `RegisterUrl`, `SignInUrl`, `SignOutUrl`, `PasswordUrl`, `ProfileUrl`, `Attributes`, `Active`, `IsDefault`)
VALUES
('mock', 'Mock', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0),
('mocksso', 'MockSSO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0);
```
Unfortunately we have a problem with finding classes that are not in addons so …
> AuthenticateApiController part 1

- applications/dashboard/modules/class.pagermodule.php
The Link header, generated by `PagerModule`, currently uses relative links. This update makes them full URLs, domain included.
> Use full URL for pagination in Link headers

- applications/dashboard/models/class.usermodel.php
`UserModel::expandUsers` contains a filter event for addons to hook in and modify the result. The event currently passes a `$single` parameter, which indicates whether or not the value being passed is a single row or multiple rows. This update removes that parameter, instead packing and unpacking a single row, as necessary. This way, the addons can always act on the input as though it were a multi-row array.
> Update expandUsers filter event to avoid the need for the "single" parameter

- library/Vanilla/AddonManager.php
- library/core/class.applicationmanager.php
There were issues with application.
1. The testApplication method was instanciating object itself and since which caused problem for hook class that have arguments in their constructor.
1. Events were not properly removed from the event manager once an application was disabled which caused an error to show on screen if the application had hooks on the `settingsController_render_before()` since `render()` is called in `disableApplication()`.
> Allow applications to use DI (Dependency Injection)

- README.md
This update drops badges from IssueStats, which no longer seem to work, in favor of badges from Shields.io.
> Use Shields.io for repo badges

- library/core/class.controller.php
Closes #6831 
Removes the new built javascript files (unused in the 2.6 release). This way people don't have to load unnecessary JS.
> Remove new unused javascript from the release

- applications/dashboard/settings/class.hooks.php
PHP 7.0 reaches EOL at the end of this year. Vanilla currently supports PHP 7+, but recommends PHP 7.1+.
This update yanks the PHP 7.1+ nagging message from the dashboard (for inf as much as users) on the 2.6 release. There's already a [hard PHP 7 requirement](https://github.com/vanilla/vanilla/blob/e0476d536c22ad83abe8987c3798fb999ae461ba/environment.php#L10), so downgrading the version requirements in the messsage for PHP 7+ doesn't make much sense.
> Remove recommended version message from v2.6

- plugins/Facebook/class.facebook.plugin.php
Facebook has recently changed their Redirect_Uri policy for Facebook Login. In the past and in grandfathered Facebook Login Apps you can have the "Use Strict Mode for Redirect URIs" set to "No" in an app allowing your app to accept Redirec_Uri's with variable query strings attached to them (e.g. https://myforum.com/entry/connect/facebook?Target=%2Fdiscussion%2Fsome-discussion). Now when you create a new Facebook Login app the "Use Strict Mode for Redirect URIs" is toggled to "Yes" and you cannot set it to "No". And if you switch a grandfathered account to "Yes" you cannot set it back to "No". This breaks the log in process entirely.
This PR removes adding "?Target" strings to Redirect_Uri sent to Facebook Login when a user is logging in. 
The affect for clients means that where ever a …
> Change redirect behaviour for users logging in through Facebook.

- applications/dashboard/controllers/api/OpenApiApiController.php
- applications/dashboard/models/ReflectionAction.php
This prevents the page from crapping out when there is a lower-level error generating docs.
I also moved the OpenApiApiController to the api subdirectory because that is where it belongs.
> Catch a wider variety of errors when generating OpenAPI docs

- src/scripts/application.js
The on ready handler wasn't actually calling its callbacks. This fix ensures they are called to either return a value (gets implicitly wrapped in promise.all) or a promise.
> Fix on ready handler

- js/global.js
Fixes #6455
- Adds the additional `.Button-Options` class to go through our accessible flyout treatment.
- Pressing enter to open these didn't work because they weren't links. So I've added a global click handler for everything we add `[role=button]` to, so that space and enter keys trigger a click on the element, just like a real button. This handler prevents default so there are no clashes with default focus + link enter key behaviour.
Other existing accessibility issues with the flyouts still remain and are outside of the scope of this issue. Thi
> Globally map space and enter keypress on fake buttons to a click

- applications/dashboard/views/modules/profileoptions.php
We use the same class for buttons and links in the edit profile pages. I've added a class to help theming the "back to profile" link and differentiate it from the dropdown button.
Note, I didn't use `.BackToProfile` as the class name because I found it commented out in a css file... which leads me to believe it may exists or have existed at some point... The class I picked is longer and less likely to clash with anything.
Closes https://github.com/vanilla/vanilla/issues/6868
> Added class to back to profile button

- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/models/class.discussionmodel.php
- applications/vanilla/modules/class.discussionsmodule.php
Remnants of Category Watching were removed with #6840. Altering some of the conditions that used Category Watching made them less flexible, specifically when it came to filtering categories with a truthy `HideAllDiscussions` flag. `DiscussionsModel::getWhere` now always filters out these categories.
This update removes the hard condition from `DiscussionsModel::getWhere` and adds it to calls, as needed.
Needs to be backported to [release/2.6](https://github.com/vanilla/vanilla/tree/release/2.6)
> Fix querying discussions always filtering out categories hidden from Recent Discussions

- applications/dashboard/controllers/api/UsersApiController.php
- applications/dashboard/controllers/class.entrycontroller.php
- applications/dashboard/models/class.usermodel.php
- applications/dashboard/views/entry/passwordrequest.php
- applications/dashboard/views/entry/signin.php
- tests/APIv2/AbstractAPIv2Test.php
- tests/APIv2/UsersTest.php
- tests/TestLogger.php
This adds the endpoint with the following changes:
- Some of the code in /entry/password request has been refactored into
the UserModel so that both endpoints can use it.
- You can now only request a password for a username if email address
is not unique and username is unique. This is to crack down on some
attack vectors.
- Labelling on the forms have been changed to reflect the new
restrictions.
- A new TestLogger is now registered for APIv2 tests so that logging
can be checked during testing.
> Add the POST /users/request-password endpoint

- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/models/class.discussionmodel.php
- applications/vanilla/modules/class.discussionsmodule.php
Backports #6934
> Remnants of Category Watching were removed with #6840. Altering some of the conditions that used Category Watching made them less flexible, specifically when it came to filtering categories with a truthy `HideAllDiscussions` flag. `DiscussionsModel::getWhere` now always filters out these categories.
>
> This update removes the hard condition from `DiscussionsModel::getWhere` and adds it to calls, as needed.
> Backport: Fix querying discussions always filtering out categories hidden from Recent Discussions

- applications/vanilla/controllers/class.discussioncontroller.php
The permission check in `DiscussionController::bookmark` expects an associative array, but gets an object. This update resolves a fatal error of trying to access an object's properties as an array when bookmarking a discussion.
Needs to be backported to [release/2.6](https://github.com/vanilla/vanilla/tree/release/2.6)
> Fix bookmarking a discussion

- applications/vanilla/controllers/class.discussioncontroller.php
Backporting #6935 
> The permission check in `DiscussionController::bookmark` expects an associative array, but gets an object. This update resolves a fatal error of trying to access an object's properties as an array when bookmarking a discussion.
> Backport: Fix bookmarking a discussion

- applications/dashboard/controllers/class.profilecontroller.php
- applications/dashboard/modules/class.sidemenumodule.php
In the panel on the edit profile page, we didn't set an "Active" class on the "Edit Profile" link when we were on `/profile/edit/[user id]` urls. I've updated the check to work for both `/profile/edit` and `/profile/edit[user id]`.
Closes: https://github.com/vanilla/vanilla/issues/6868
> Fix "Active" class on edit profile link not appearing under specific circumstances

- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/modules/class.discussionsmodule.php
Fixes https://github.com/vanilla/vanilla/issues/6949
If all categories are visible we were setting the following condition: `$where['d.CategoryID'] = true`
This is obviously incorrect since there should be no condition set at all.
I assume this was translated to `$where['d.CategoryID'] = 1` down the line.
> Properly set where condition if all categories are visible

- applications/dashboard/controllers/class.searchcontroller.php
The search controller needs to use DI so that other search providers can override the model.
> Use dependency injection in the search controller

- applications/dashboard/models/class.assetmodel.php
- library/core/class.controller.php
The new js code still needs a deploy hash and it has not shown off in different places. I’m guessing we’ll need to make the buster more robust in the future for OSS, but this solution should get us through a release or two.
> Normalize the cache buster into the asset model

- tests/Library/Garden/Web/ResourceRouteTest.php
- tests/fixtures/src/AddonsController.php
Add more unit tests related to [this issue](https://github.com/vanilla/vanilla/pull/6888) which we can now fix!
> Allow $id to be type hinted as a string

- js/global.js
Closes #6960 
Apparently IE (and related require the 4th param to initEvent).
> Fix init event in IE

- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/controllers/class.postcontroller.php
- applications/vanilla/views/discussion/helper_functions.php
I just started seeing a lot of notices crop up with a missing variable. I’m not sure when the change was done, but the underlying function in Gdn_Model was added in ccae291fffc03636884b26d51475f57dbc0e4d4e.
> Fix undefined $timeLeft variable notices

- applications/dashboard/modules/class.pagermodule.php
- applications/vanilla/controllers/class.categoriescontroller.php
- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/controllers/class.vanillacontroller.php
There are several edge cases where crawlers may start crawling non-existent pages of discussions, categories, etc. See the individual commits for more information.
There are two main components to this PR:
1. Render a single previous link for numbered pagers when the specified page is greater than the number of pages.
2. Throw not found errors on select pages when the specified page is greater than the number of pages.
The not found errors provide some edge cases that should be taken into consideration:
1. When there are no records the first page should not throw an error.
2. Auto offset into discussions can throw things for a loop.
3. Off-by-one errors.
Closes #6796
> Fix edge case crawl errors

- conf/config-defaults.php
Pretty much all of our new themes set the default thumbnail size to 200, so I changed the default.
> Bump up default thumbnail size to 200px.

- applications/dashboard/models/ReflectionAction.php
Since #6755 the controllers can now define index_subresource but swagger was never updated to list them properly.
$subpath was removed as a "protection" i guess but since #6755 that's actually incorrect!
> Allow index_subresource to be listed in APIv2 documentation.

- library/core/class.session.php
The session was only loading the transient key when there is a valid user even though the TK cookie was submitted.
We need the TK for login pages where there is no session so the TK is important. As it turns out the entry controller always ensured the TK itself, but this really should be handled in the session.
The fix in Gdn_Session::start() caused a nasty redirect loop when signing a user out because Gdn_Session::loadTransientKey() had a bug. This shouldn’t be an issue now, but shows that this seemingly simple fix can cause some bad regressions because of the state of Gdn_Session.
> Always load the transient key

- applications/dashboard/models/class.usermodel.php
User search by IP would return no results when the user count was past the threshold (the query was in "optimized" mode).
The user search IP query was searching for user IDs in a `null` list. This would give no results. User IDs now populate the list, when available, so matches can be properly made.
Related #6381
Fixes #6989
> Fix user search by IP never returning results

- applications/vanilla/views/discussions/table_functions.php
The code in #7046 added a very inefficient comment query inside of the discussion table. Since the information we need is already in the result set this is unnecessary.
This change will need to be back-ported as right now a lot of servers are suffering.
> Remove the comment query tight loop

- applications/vanilla/views/discussions/table_functions.php
Backporting #7052 
> The code in #7046 added a very inefficient comment query inside of the discussion table. Since the information we need is already in the result set this is unnecessary.
>
> This change will need to be back-ported as right now a lot of servers are suffering.
> Backport: Remove the comment query tight loop

- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/views/post/comment.php
Fixes https://github.com/vanilla/vanilla/issues/7014
We added a new property that can be redefined using events.
Views that have been redefined won't reflect that change but nothing will break!
> Move "category" back link definition into discusion controller

- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/views/post/comment.php
Backport #7043 which fixed https://github.com/vanilla/vanilla/issues/7014
> [Backport] Move "category" back link definition into discussion controller

- bootstrap.php
- tests/Bootstrap.php
Needed so that we can redefine what instance will be returned by the container.
> Add SearchModel to the container's rules

- applications/vanilla/views/post/comment.php
- applications/vanilla/views/post/discussion.php
- applications/vanilla/views/post/editcomment.php
The textareas in Vanilla don't have a label. I've added a title and placeholder to help screen readers to announce what the text area is for for new posts. 
Closes: https://github.com/vanilla/vanilla/issues/6380
> Accessibility - Add placeholder/title for text areas

- bootstrap.php
- tests/Bootstrap.php
We should always be configuring dependencies in the container rather than instantiating them in the bootstrap. This ensures that they are instantiated as late as possible which can also mean that they aren’t instantiated at all if they aren’t needed.
> Change authenticator bootstrapping to container config

- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/controllers/class.postcontroller.php
- applications/vanilla/models/class.commentmodel.php
- applications/vanilla/views/discussion/helper_functions.php
`CommentModel::canEdit` (introduced in #6782) grabs the discussion it's associated with, every time it's called. For functions that use it, like `getCommentOptions`, this can mean the same discussion is queried dozens of times on the same page.
This update alters `CommentModel::canEdit` to allow passing in a discussion row. If none is detected, the lookup will occur. Existing calls to `CommentModel::canEdit` have been updated to pass in a discussion row. A simple shortcut has also been added to always return `false` for guests.
> Fix unnecessary discussion querying when verifying comment edit abilities

- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/controllers/class.postcontroller.php
- applications/vanilla/models/class.commentmodel.php
- applications/vanilla/views/discussion/helper_functions.php
Backporting #7062 
> `CommentModel::canEdit` (introduced in #6782) grabs the discussion it's associated with, every time it's called. For functions that use it, like `getCommentOptions`, this can mean the same discussion is queried dozens of times on the same page.
>
> This update alters `CommentModel::canEdit` to allow passing in a discussion row. If none is detected, the lookup will occur. Existing calls to `CommentModel::canEdit` have been updated to pass in a discussion row. A simple shortcut has also been added to always return `false` for guests.
> Backport: Fix unnecessary discussion querying when verifying comment edit abilities

- applications/dashboard/controllers/api/AuthenticateApiController.php
- plugins/Facebook/FacebookAuthenticator.php
- plugins/GooglePlus/GooglePlusAuthenticator.php
- plugins/Twitter/TwitterAuthenticator.php
- plugins/oauth2/OAuth2Authenticator.php
Use what most plugins use in `entryController_signIn_handler` to know if a plugin is allowed to be used to sign in.
With this update authenticators won't show up until they are properly configured!
> Fix shim authenticators active property

- applications/vanilla/controllers/class.postcontroller.php
Problem originates in https://github.com/vanilla/vanilla-patches/pull/224/files
Copy/pasting variable casing and lack of testing caused an error.
> Fix 403 error requiring Community.Manage when trying to post a new discussion draft

- applications/vanilla/controllers/class.categoriescontroller.php
If filtering followed categories by an ancestor (like in subcommunities), not all followed categories in that branch of the tree might be displayed if they're too far down. This is due to `CategoryModel::getTreeAsFlat`, which is currently used by the filtering, not going very deep into the tree.
This update replaces the previous tree filter with a call to `CategoryModel::getTree`, followed by a call to `CategoryModel::flattenTree` (which is actually significantly different from just calling `CategoryModel::getTreeAsFlat`).
No functionality should be affected beyond getting followed categories further into a category branch.
> Fix filtering followed categories on deep branch

- applications/vanilla/controllers/class.categoriescontroller.php
This is a backport of #7080.
> If filtering followed categories by an ancestor (like in subcommunities), not all followed categories in that branch of the tree might be displayed if they're too far down. This is due to `CategoryModel::getTreeAsFlat`, which is currently used by the filtering, not going very deep into the tree.
>
> This update replaces the previous tree filter with a call to `CategoryModel::getTree`, followed by a call to `CategoryModel::flattenTree` (which is actually significantly different from just calling `CategoryModel::getTreeAsFlat`).
>
> No functionality should be affected beyond getting followed categories further into a category branch.
> Backport: Fix filtering followed categories on deep branch

- applications/dashboard/models/class.activitymodel.php
`ActivityModel::canView` has a couple issues that are addressed here.
1. There's a typo in `ActivityModel::NOTIFY_ADMINS` ([that's apparently been there for almost three years](https://github.com/vanilla/vanilla/commit/5250b1cc36f0d2726bf22c77a88cdb37a180e6f9#diff-987a5acb3eb9035837eb3a5a705b500fR104)).
1. The fallback permission check attempts to determine if the user has the community management permission, first, *and* that they are the target user for the action. It should be checking if they are the target user, first, *or* if they have the community management permission.
> Fix default condition in ActivityModel::canView

- library/Garden/Web/Dispatcher.php
- tests/InternalClient.php
- tests/InternalRequest.php
This change stores the exception object in the response rather than the stack trace. The test suite then expands the exception.
> Don’t add exception stack traces to every exception just for tests

- applications/vanilla/settings/class.hooks.php
Currently ideas do not allow for tagging.  This update will ideation to use the afterDiscussionFormsOptions event to enable tagging.
See vanilla/internal#1535
> Enable tags on Ideas

- tests/APIv2/MediaTest.php
This test calls out to the test server so should be marked in a way that it can be skipped like the APIv0 tests. This is necessary for other repos that pull in Vanilla and test against it.
Longer term the scraper should be subclassed/configured for testing and the URL should be replaced by a local fixture.
> Mark a scrape test as @large

- applications/dashboard/models/class.logmodel.php
Properly fix https://github.com/vanilla/vanilla/issues/6976
To test
- Set members permission for Approval -> Required
- Try to post 2 discussion as a member
- Go in the moderation logs with a moderator
- Delete the 2 posts
> Fix LogModel::deleteIDs() when $logIDs is a string containing multiple IDs

- applications/dashboard/controllers/api/DashboardApiController.php
- applications/dashboard/library/class.nestedcollection.php
- applications/dashboard/models/ReflectionAction.php
- applications/dashboard/modules/class.dashboardnavmodule.php
- applications/dashboard/views/modules/nav-dashboard.php
- plugins/swagger-ui/SwaggerUIPlugin.php
- tests/APIv2/DashboardTest.php
- tests/Bootstrap.php
This endpoint lists all of the menus in the dashboard. It is going to be necessary in order to add a client-side nav module and addon management page.
This is a bit of yack shaving, but to give a bit of context on where this PR is coming from:
- We've the /api/v2/addons resource for a while which is necessary for a client-side addons page.
- Since enabling/disabling an addon can affect the menu we need a way of refreshing it.
- We need to refactor the addons page in general to support the new feature in the API such as conflicts. And once we change the page we can remove a bunch of old code.
> Add the /api/v2/dashboard/menus endpoint

- applications/dashboard/controllers/class.homecontroller.php
- applications/dashboard/modules/class.headmodule.php
- library/core/class.controller.php
- Allow the canonical URL to be blank by specifying an empty string.
- Don’t show any canonical URLs on the home controller.
Closes #7089.
> Don’t show canonical links in the home controller

- applications/dashboard/models/class.updatemodel.php
- library/core/class.pluggable.php
This issue was discovered when a plugin declared its `structure()` method private. The `method_exists()` function returns true if a method exists, regardless of its visibility. Trying to call a private method then invokes `__call()` which throws an exception. This PR addresses the issue the following way:
- Make `Gdn_Pluggable` throw a `BadMethodCall` exception instead of triggering an error when it can't find a new method.
- Handle the `BadMethodCall` exception explicitly in `UpdateModel`.
- A pluggable class that does not set its own `ClassName` property will use `get_called_class()` instead to try and find new methods.
There was also an old "optimization" in `Gdn_Pluggable` that was removed in favor of a single call to `call_user_funct_array()`.
> Make Gdn_Pluggable calls more robust

- library/Vanilla/Embeds/LinkEmbed.php
- library/Vanilla/PageScraper.php
- tests/Library/Vanilla/Embeds/EmbedManagerTest.php
- tests/Library/Vanilla/PageScraperTest.php
- tests/fixtures/src/PageScraper.php
This update renames `WebScraper` to `PageScraper`. The class is meant to scrape information from pages. It isn't the general-purpose scraper of all-things-web the original class was intended to be.
> Rename WebScraper to PageScraper

- library/database/class.mysqlstructure.php
Columns of type “timestamp” always have a default of “current_timestamp”, however the database comes back with “CURRENT_TIMESTAMP” which would always show as a database alter. This change makes the current default always “current_timestamp” so it can be shown as not a change.
> Fix timestamp column comparison when altering the database structure

- plugins/VanillaStats/class.vanillastats.plugin.php
The notice was caused by a call to a deprecated plugin manager method. However, it seems to be old code from the previous dashboard and removing it didn’t cause a problem.
> Fix deprecation notice in the Vanilla Stats plugin

- applications/dashboard/controllers/class.entrycontroller.php
- applications/dashboard/models/class.usermodel.php
- applications/dashboard/views/entry/connect.php
- plugins/stubcontent/class.stubcontent.plugin.php
- tests/APIv2/AbstractAPIv2Test.php
- tests/APIv2/Authenticate/AutoConnectTest.php
- tests/APIv2/Authenticate/LinkUserTest.php
- tests/APIv2/Authenticate/NoEmailTest.php
- tests/APIv2/Authenticate/PasswordAuthenticatorTest.php
- tests/APIv2/UsersTest.php
SSO has been updated to utilize `UserModel` updates introduced in #7163.
1. If the username comes from a trusted authentication provider, it must not be a blacklisted name.
1. If the username comes from an untrusted authentication provider, or if the username comes from a user during connection, it must not be blacklisted __*and*__ it must match the regex validation pattern.
Tests and some addons have been updated, as necessary, to generate default valid usernames.
*Warning: At 500 lines, `EntryController::connect` is a complex, delicate beast. It's not something to be taken lightly. Please take your time in carefully reviewing the code.*
This can have a significant impact on SSO. Please test, throughly. I've primarily tested with social connect addons and jsConnect. I recommend testing …
> Fix username validation when signing in with SSO

- applications/dashboard/controllers/api/AuthenticatorsApiController.php
- library/Vanilla/Authenticator/Authenticator.php
- library/Vanilla/Authenticator/ShimAuthenticator.php
- plugins/GooglePlus/GooglePlusAuthenticator.php
- plugins/Twitter/TwitterAuthenticator.php
Fixes https://github.com/vanilla/vanilla/issues/7115
Should be /entry/{PluginName} but for twitter and googlePlus which have an exception.
Authentication will work with all plugins now.
> Fix ShimAuthenticators URL

- applications/vanilla/views/discussions/helper_functions.php
- applications/vanilla/views/discussions/table_functions.php
This issue doesn’t really surface at the moment, but will once [this issue](https://github.com/vanilla/internal/issues/1565) is fixed.
We should only be showing links to categories the user has the ability to view and this extra permission check does just that. Since this is mostly a duplicate check I’m a little concerned about the overhead, but since the `optionsList()` call a few lines above makes many of the exact same call I don’t think it will cause a performance impact that we haven’t already seen.
> Check discussion view permission on a category before rendering its link

- library/Vanilla/Authenticator/Authenticator.php
- library/Vanilla/Authenticator/PasswordAuthenticator.php
- library/Vanilla/Authenticator/SSOAuthenticator.php
- library/Vanilla/Authenticator/ShimAuthenticator.php
- library/Vanilla/Models/AuthenticatorModel.php
- tests/APIv2/Authenticate/InactiveAuthenticatorTest.php
- tests/APIv2/Authenticate/PasswordAuthenticatorTest.php
- tests/fixtures/src/MockAuthenticator.php
- tests/fixtures/src/MockSSOAuthenticator.php
Depends on https://github.com/vanilla/vanilla/pull/7166
- Ensure authentication failure if authenticator is inactive.
- This is done by making `validateAuthentication()` final, putting a check on `isActive()` in there and moving the implementation part into `validateAuthenticationImpl()`
- Unit tests on inactive authenticators
- Type hinting updates
- AuthenticatorModel fixes related to ShimAuthenticators.
> Multiple fixes and improvements about Authenticators

- applications/dashboard/controllers/api/AuthenticateApiController.php
- library/Vanilla/Authenticator/Authenticator.php
- library/Vanilla/Models/SSOModel.php
- tests/APIv2/Authenticate/PasswordAuthenticatorTest.php
Fixes #7119
Throw relevant error when the session could not be started when using the AuthenticateApiController/SSOModel.
Before this fix the session would not be started but the API was returning code 200 with the user's information because `Gdn_Session->start()` doesn't do anything when the session could not be started.
> Throw relevant error when the session could not be started

- library/core/class.form.php
- plugins/editor/class.editor.plugin.php
Closes #6374
This PR allows uploading images on every bodyBox (unless it explicitly opts out by setting the `FileUpload` or `ImageUpload` itself).
I've tested this on every page I can think of (conversation, activity, profile activity, groups, comments, etc).
Just for clarification there were 3 different permutations of the bodyBox and image uploads before.
**Before**
1. User does not have `Plugins.AttachmentsUpload.Allow` permission. Only external image embedding is allowed.
2. User has `Plugins.AttachmentsUpload.Allow` permission. The`FileUpload` and `ImageUpload` options are **not** passed to the bodyBox. Only external image embedding is allowed.
3. User has `Plugins.AttachmentsUpload.Allow` permission. `FileUpload` option is passed to the bodyBox. File uploads, image uploads, and …
> Make image upload on the by default for bodybox

- applications/vanilla/views/drafts/drafts.php
Gdn_Format::text() is meant to work on HTML, not any old format.
Closes #6690.
> Format drafts as plaintext instead of text

- bootstrap.php
- library/Garden/Web/Dispatcher.php
- library/Vanilla/Web/SmartIDMiddleware.php
- library/Vanilla/Web/UserSmartIDResolver.php
- tests/Library/Vanilla/Web/SmartIDMiddlewareTest.php
- tests/Library/Vanilla/Web/TestSmartIDMiddleware.php
Add smart ID support to the API v2. Go to the blocking roadmap issue for a description of how it works.
- I tried to make the middleware extensible without exploding the number of classes we have to have. To this end I allow basic smart ID resolvers that do simple DB lookup and callback resolvers that can do whatever they want.
- I opted not to inject models into the middleware because I don't want every model hanging around for every request. In the future we may want to explore some sort of model factory that allows us to map record types to models since we have many kludges throughout our app for this.
- User ID smart IDs do some basic security checking on email addresses. I opted not to do an extra check on whether authenticators exist or are enabled. If an authenticator does not …
> Add APIv2 smart ID support

- applications/vanilla/views/discussion/helper_functions.php
Backporting #6970
> I just started seeing a lot of notices crop up with a missing variable. I’m not sure when the change was done, but the underlying function in Gdn_Model was added in ccae291fffc03636884b26d51475f57dbc0e4d4e.
> Backport: Fix undefined $timeLeft variable notices

- applications/dashboard/controllers/class.entrycontroller.php
- library/core/class.controller.php
This is to fix a specific issue from ops, but is also a reasonable thing to do.
> Don’t clean certain APIv0 data for users when it’s themselves

- conf/config-defaults.php
A recent internal poll revealed much of our own staff didn't know that Vanilla auto-links #hashtags to a search page. Conversely, we frequently see the results of accidental hashtags from writing numbers, e.g. #3, in the middle of a post. Since this appears to be 99% of all uses of this feature, let's start by disabling it in the config and folks who are super attached to it can tell us to re-enable it on their site.
> Disable hashtags by default

- applications/dashboard/models/class.activitymodel.php
Backports #7090 
> `ActivityModel::canView` has a couple issues that are addressed here.
>
> 1. There's a typo in `ActivityModel::NOTIFY_ADMINS` ([that's apparently been there for almost three years](https://github.com/vanilla/vanilla/commit/5250b1cc36f0d2726bf22c77a88cdb37a180e6f9#diff-987a5acb3eb9035837eb3a5a705b500fR104)).
> 1. The fallback permission check attempts to determine if the user has the community management permission, first, *and* that they are the target user for the action. It should be checking if they are the target user, first, *or* if they have the community management permission.
> Backport: Fix default condition in ActivityModel::canView

- applications/dashboard/controllers/class.setupcontroller.php
We currently auto-enable two addons on install:
* `swagger-ui` (API v2 convenience docs in the Dashboard)
* `stubcontent` (prepopulates some dummy content)
If either of these is missing, a generic "Plugin not found." error is returned on install, blocking further progress and not giving sufficient info to remedy it. Further, adding the missing addon doesn't fix the problem until you manually clear the addon cache (`cache/addon.php`). 
Neither of these addons is critical (hence... addons), there are legitimate reasons they might be removed from a package, and we don't have sufficient handling around the error condition if they fail. Therefore, this pull request removes the error being added to the form data so that install will proceed uninterrupted.
> Do not block Vanilla install for stub or swagger addons

- library/core/class.dispatcher.php
- library/core/functions.general.php
- tests/Library/Core/DispatcherTest.php
- tests/fixtures/src/FooBarController.php
- tests/fixtures/src/UnitTestGdnDispatcher.php
This PR allows us to dispatch to controllers/methods that contain dashes in their URL. That change itself is fairly trivial, but there is a bit of work handling canonical URLs when the dashes are not properly added.
This breaks backwards compatibility with some canonical URLs, but I think the new ones are more robust. This is just for default canonical URLs, not ones that are explicitly set.
I've grabbed the old default canonical URL code for comparison. You can browse around with the debug on and look for notices where the old and new canonical URLs differ. We want to ensure that our "main" canonical URLs are the same while other pages are fine.
Closes #7109.
> Allow Gdn_Dispatcher to dispatch to dash-cased controllers

- library/core/class.authenticationprovidermodel.php
Allow authentication providers that are hard-coded in the database structure to be saved with a `“checkExisting” => true` option so that they don’t show up in the database structure every single time.
> Add a checkExisting option for saving authentication providers

- applications/dashboard/models/class.assetmodel.php
- library/core/class.controller.php
Although class.controller.php said it was possible the override theme from any controller, you couldn't do so, because the assetmodel would never know about it.
To test it:
1. Don't pull the code first, but add 
`$this->Theme = isMobile() ? 'mobile' : desktop';`
to any controller before 
`$this->Render();`
2. Change 'mobile' or 'desktop' to any theme of your kind, i.e. 'bittersweet' and see that the current theme won't change.
3. Pull and merge my code.
4. Repeat step 2 and see that the theme now changes.
> Add ability to override theme per contoller

- applications/dashboard/views/embed/comments.php
A couple of customers I have worked with did not realize they needed to make the change from embed test to "your-content-identifier", which is used earlier. So to be consistent, I figured we should use the same wording.
> Update Universal Comments Code Snippet to Be More Consistent.

- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/models/class.discussionmodel.php
`DiscussionModel::getAnnouncements` is a very delicate method. It performs some unusual caching practices (namely using a fixed cache key, even for dynamic criteria) that didn't play well with the move from category watching to category following. The result is announced discussions might not be properly pinned when caching is enabled and something is filtering categories, like the Subcommunities addon. The announced discussion IDs are cached in one area, then retrieved and filtered out in another area.
This update makes a couple of minor tweaks to make Recent Discussions function a bit like it did in 2.5, while still utilizing the methods introduced with category following.
1. The call to `DiscussionModel::getAnnouncements` gets its own conditions array. This array only gets the …
> Fix cached announcements on Recent Discussions sometimes being filtered out

- applications/dashboard/controllers/api/UsersApiController.php
- applications/dashboard/controllers/class.usercontroller.php
This update opts out of username validation when managing users in the dashboard or using the API.
Closes #7154
> Do not validate usernames when managing users

- applications/vanilla/models/class.discussionmodel.php
A copy-paste error in #7240 led to the discussion summary query only including discussions in categories that haven't opted out of displaying on the Recent Discussions page. This limitation doesn't exist in `DiscussionModel::categoryPermissions`, so it shouldn't exist in the method call that replaced it.
> Fix discussion summaries not always including all visible categories

- library/Vanilla/Embeds/VideoEmbed.php
- tests/Library/Vanilla/Embeds/EmbedManagerTest.php
This update adds a title attribute to the video container markup generated by `VideoEmbed::videoCode`. Hovering over a video should now display its title.
Closes #7201
> Add title to embedded videos created with VideoEmbed

- library/Vanilla/Embeds/YouTubeEmbed.php
`YouTubeEmbed::matchUrl` only supports extracting the start time if it is in the minute-second format (e.g. 1m30s) format and does not currently support extracting the start time when in the second-only format (e.g. 90).
The method has been updated to support a second-only time value in a YouTube URL (e.g. https://youtu.be/QljRe99OMCU?t=110).
Closes #7202
> Add support for second-only time parameter to YouTubeEmbed::matchUrl

- applications/dashboard/controllers/api/AbstractApiController.php
- applications/dashboard/controllers/api/UsersApiController.php
Also make GET /users/by-names return an array of UserFragments. The reason for these changes are the following:
- We think that dateLastActive is a useful field for a variety of purposes such as client-side sorting or showing if a user is online.
- We want to standardize on the UserFragmentModel as a means of displaying user information beside posts or whatever. If we can maintain as useful user fragment schema in one place this will be easier. We just need to take care that it does not become bloated. Perhaps it can be extensible in the future.
> Add dateLastActive to the UserFragmentSchema and UserSchema

- applications/vanilla/modules/class.discussionssortfiltermodule.php
- applications/vanilla/views/modules/discussionssortfilter.php
The default filter detection wasn't taking into consideration `$Configuration['Vanilla']['Discussions']['SortField']`.
Took our some logic from discussionssortfilter.php and moved it into class.discussionssortfiltermodule.php.
Removed unused const `ACTIVE_CSS_CLASS`.
Closes: https://github.com/vanilla/vanilla/issues/7072
> Fix bug with discussion sort default not respecting config

- applications/dashboard/controllers/api/UsersApiController.php
- tests/APIv2/UsersTest.php
This update adds /users/:id/confirmEmail to API v2 to confirm new users email address after registration.  Currently functionality signs the user in after confirmation, this will return true or throw an exception on failure
Closes #7170
> Add /users/:id/confirm-email to APIv2

- applications/dashboard/src/scripts/dom.test.ts
- applications/dashboard/src/scripts/dom.ts
- tests/javascript/karma.conf.js
This PR extends `getNextTabbableElement` and adds additional unit tests to prepare it for work inside of the rich editor.
An additional utility `watchFocusInDomTree` is added as well with it's own unit tests.
> Improve DOM focus utilties

- applications/vanilla/controllers/class.categoriescontroller.php
- applications/vanilla/controllers/class.discussionscontroller.php
fixes vanilla/addons#629
The category-following filter is currently by default true and with and  the option to opt-out.  This allows for the filter to be displayed on views that it shouldn't.  The filter should only be displayed on the category index and recent discussions pages.
This fix checks if category following is enabled and then allows the view to opt in or out accordingly.  In order to opt-in, the SelfUrl will have to be added to the $categoryFilterList.  The DiscussionsController::setCategoryFollowingList can be used to set any request to opt-in.
This approach was taken because some plugins call the DiscussionsController::index method (ie. QnA ) and there was no clear way to distinguish whether the filter should be displayed (opted into) besides the requested url to the …
> Fix Category following filter displaying on QnA plugin

- library/core/class.request.php
This reverts commit 9bf81855b3bf33c73c51680bc41a6ab64d94837f which fixes https://github.com/vanilla/vanilla/issues/7258.
All the details here: https://github.com/vanilla/vanilla/issues/7258#issuecomment-393958487
> Backport: Fix installing Vanilla on Apache before .htaccess is available

- applications/dashboard/models/class.assetmodel.php
Goes with https://github.com/vanilla/vanilla-cli/pull/109.
Allows the hot reload IP address to be read from a configuration value.
> Allow configurable hot reload IP

- README.md
Update our installation and migration instructions to break out per-version instructions better and provide more obvious linking to other sections.
Addresses feedback from @cdepage and this open community discussion: https://open.vanillaforums.com/discussion/36260
> Improve README instructions for upgrades and installs for 2.6

- applications/dashboard/models/class.rolemodel.php
re: https://github.com/vanilla/vanilla-patches/pull/249
We no longer need this manual escaping, and in fact it breaks the world.
> Fix permission column name escaping

- applications/dashboard/models/class.rolemodel.php
Backport https://github.com/vanilla/vanilla/pull/7310
> re: https://github.com/vanilla/vanilla-patches/pull/249
>
> We no longer need this manual escaping, and in fact it breaks the world.
> [Backport] Fix permission column name escaping

- applications/dashboard/models/class.rolemodel.php
re: https://github.com/vanilla/vanilla-patches/pull/249
We no longer need this manual escaping, and in fact it breaks the world.
> Unescape permission column name

- applications/dashboard/models/class.searchmodel.php
- library/database/class.sqldriver.php
This PR fixes the the normal search's plaintext SQL search.
Because we don't have a `fromRaw` or `from(SqlObject)` or `fromSql` type function, we are doing a search and replace that broke because of the additional escaping. 
https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.searchmodel.php#L152-L159
@tburry's preferred fix was allowing to opt out of escaping on the `from()` method.
Other solutions that were initially considered:
- Changed the find/replace query
- Allowing from to take a SQLObject that presumably already be escaped to the correct amount.
> Allow search to opt out of SQL table escaping (fix database error from added escaping)

- applications/dashboard/models/class.searchmodel.php
- library/database/class.sqldriver.php
Backport https://github.com/vanilla/vanilla/pull/7315
> This PR fixes the the normal search's plaintext SQL search.
> 
> Because we don't have a `fromRaw` or `from(SqlObject)` or `fromSql` type function, we are doing a search and replace that broke because of the additional escaping. 
>
> https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.searchmodel.php#L152-L159
>
> @tburry's preferred fix was allowing to opt out of escaping on the `from()` method.
>
> Other solutions that were initially considered:
> - Changed the find/replace query
> - Allowing from to take a SQLObject that presumably already be escaped to the correct amount.
> [Backport] Allow search to opt out of SQL table escaping (fix database error from added escaping)

- library/Vanilla/Authenticator/Authenticator.php
- library/Vanilla/Authenticator/SSOAuthenticator.php
- library/Vanilla/Models/AuthenticatorModel.php
- library/core/functions.general.php
- tests/Library/Core/ArrayFunctionsTest.php
- tests/fixtures/src/Authenticator/MockAuthenticator.php
- tests/fixtures/src/Authenticator/MockSSOAuthenticator.php
- Added `arrayPathExists()` and it's unit test since `valr()` doesn't work properly with null values.
Example:
```php
$array = ['a' => ['aa' => ['aaa'  => null]]];
$default = -1;
$path1Value = arrayPathExists(['a', 'aa', 'aaa'], $array, $value) ? $value : $default; // null
$path2Value = arrayPathExists(['b', 'aa'], $array, $value) ? $value : $default; // -1
```
- signInUrl is now required by all authenticators.
- Leverage Schema for different purpose
- Add `getRequiredFields` which returns a list of fields the MUST be provided when creating an instance of a specific authenticator type. Fields can be marked as required by setting the `x-instance-required` property in the Authenticator's schema.
- Add `getConfigurableFields` which returns a list of fields that can be provided when creating …
> SSOAuthenticator creation improvements

- .tslint.js
- package.json
- tslint.json
Certain IDEs like PHPStorm can't read anything other than a JSON config file. This converts the file back to JSON. The vanilla cli's linting was also never updated to point to the non-json file location so that will not be affected.
> Fix broken tslint config

- applications/dashboard/controllers/class.homecontroller.php
- applications/dashboard/modules/class.headmodule.php
- library/core/class.controller.php
> Backport: Don’t show canonical links in the home controller(2.6)

- library/core/functions.general.php
- tests/Library/Core/ArrayFunctionsTest.php
We added the flattenArray function in #4323 but it has a nasty bug where it corrupts keys when flattening.
I fixed the function and added an extra basic unit test.
> Fix flattenArray function not computing keys properly

- .gitignore
- applications/dashboard/controllers/api/AuthenticatorsApiController.php
- applications/dashboard/controllers/class.authenticatecontroller.php
- composer.json
- composer.lock
- library/Vanilla/Authenticator/Authenticator.php
- library/Vanilla/Authenticator/SSOAuthenticator.php
- library/Vanilla/Models/AuthenticatorModel.php
- library/core/functions.general.php
- library/core/helpers/class.ssoutils.php
- plugins/vanillaconnect/LICENSE.md
- plugins/vanillaconnect/README.md
- plugins/vanillaconnect/VanillaConnectAuthenticator.php
- plugins/vanillaconnect/VanillaConnectPlugin.php
- plugins/vanillaconnect/addon.json
- plugins/vanillaconnect/views/settings.php
- plugins/vanillaconnect/views/settings_addedit.php
- tests/Library/Core/ArrayFunctionsTest.php
- tests/fixtures/src/Authenticator/MockSSOAuthenticator.php
Closes https://github.com/vanilla/vanilla/issues/6892
Add VanillaConnect plugin!
Improve AuthenticatorModel
- Add getAuthenticatorsByClass()
- Fix DB to Authenticator data problems with null vs empty string
- Add deleteSSOAuthenticator()
Add improvements to the SSOAuthenticator class
- Add initiateAuthentication() method which can be overriden to add additional arguments to the SignInUrl
- Add URI validation to URLs
- Add updateAuthenticatorInfo() method to mass update fields on an authenticator
- Override "name" per instance.
- Install/update (composer too) https://github.com/vanilla/stub-sso-providers
- composer update this branch
- Add `$Configuration['EnabledPlugins']['vanillaconnect'] = true;` to your config.php
- Go in the dashboard and on the left sidebar click on VanillaConnect
- …
> Add VanillaConnect plugin

- applications/vanilla/controllers/class.postcontroller.php
Close Vanilla/Vanilla#5641
When you save a draft in child category with Vanilla.Categories.DoHeadings enabled (Parent Category is considered heading so you can't post in it), you're unable to edit the draft.  The root of the issue can be traced back to the postcontroller discussion method where the draft's category id is used to find the category subtree for that specific draft and assigned the context.  The context is passed on to the categoryDropDrown method, where the it now assumes the top level of the subtree is the parent category and disables it.  Removing the assignment of context from the postcontroller fixes this issue.
I've tested with categories displayed as heading, nested, flat and discussion and could not find any adverse effects.
There is same issue in the subcommunities …
> Fix categoryDropDown when editing drafts with DoHeadings enabled

- applications/dashboard/src/scripts/app/index.tsx
- applications/dashboard/src/scripts/app/user-content/embeds/imgur.ts
- bootstrap.php
- library/Vanilla/Embeds/ImgurEmbed.php
- tests/APIv2/MediaTest.php
- tests/Bootstrap.php
- tests/Library/Vanilla/Embeds/EmbedManagerTest.php
- tests/Library/Vanilla/Quill/Sanitize/ExternalEmbed/ImgurSanitizeTest.php
This feature allows for the embedding of imgurs embeds
The imgur link is parsed to extract the postID and a call in made to imgur to get the json for that particular post, from the response it is determined if this post is in album or not.  
The data extracted from the media scrape is used to reconstruct imgurs  embed code and imgurs embed js script is used to render the post.
Data for imgurs embeds has been added to the the MediaTest and EmbedManagerTest as well as Quill Santize tests.
Closes #7209
> Add embed for imgur

- plugins/vanillaconnect/VanillaConnectAuthenticator.php
The function was renamed on the base class and I forgot to rename it on VanillaConnectAuthenticator
> Fix function name on VanillaConnectAuthenticator

- plugins/ProfileExtender/class.profileextender.plugin.php
This PR makes the ProfileExtender plugin recognize "Instagram" as a special field (similar to twitter).
> ProfileExtender: add Instagram magic formatting

- applications/vanilla/views/discussion/helper_functions.php
Current master breaks embedded comment forms when the user is logged in.
The "Gdn_Auth" object does not have a "xgetAuthenticator" method. 
This PR makes the signout URL creation similar to the signin URL:
https://github.com/bleistivt/vanilla/blob/cee99aa4c0e4440da139f9a498c7481fe64667cf/applications/vanilla/views/discussion/helper_functions.php#L628
> Fix broken sign-out URL in embed comment form

- applications/vanilla/modules/class.bookmarkedmodule.php
Closes https://github.com/vanilla/vanilla/issues/7341
Remove separate addition of a where clause prior to the get function that created pollution of SQL objects. Simply added the where condition as a parameter of the `get` function.
I removed the original condition `'w.Bookmarked' => '1'` in the where parameter of the get function as we already fetch the bookmarkIDs with the same condition a little higher in the code.
```
$bookmarkIDs = Gdn::sql()
->select('DiscussionID')
->from('UserDiscussion')
->where('UserID', Gdn::session()->UserID)
->where('Bookmarked', 1)
->get()->resultArray();
```
That condition seemed useless.
> Fix error message "Unknown column" appearing when bookmarking a discussion

- library/Vanilla/Addon.php
Case-sensitive filesystems were giving us issues when the addon scanning was done on a case-insensitive filesystem. This change should ensure that as much as possible the file that is cached is the correct case within our accepted file naming conventions.
> Use glob character ranges for case-sensitive filesystem scans

- library/core/functions.render.php
Category-Following drop down filter and Label of "All" & "Following" was not translated, I added the key for 'Following' in [#62](https://github.com/vanilla/locales/pull/62/files), 'All' key is already added.
> Add translation support for "All" and "Following" in category following filter menus

- applications/vanilla/models/class.discussionmodel.php
Fixes [#1592](https://github.com/vanilla/internal/issues/1592)
**Issue 1**
When Premoderated category plugin is enabled, after a discussion get edited for a second time, we get the error "Field 'InsertUserID' doesn't have a default value|Gdn_Database|Query|replace `GDN_Discussion` "
this got fixed by adding the missing fields to the array before saving the data to GDN_Log
**Issue 2**
After a discussion gets approved, it is marked as closed when the value of DateLastComment is set to "0000-00-00 00:00:00"
https://github.com/vanilla/vanilla/blob/be20cf00c2a40e35f69c5dc187bdde9b7f3731a1/applications/vanilla/models/class.discussionmodel.php#L1012
> Fix inability to restore some discussions from the moderation queue

- library/core/class.format.php
TLDR: Removing vine’s script seems to still allow their embeds to work minus autoplay. Since vine is defunct this is an acceptable tradeoff.
Including an external script for vine means that it can execute whatever code it wants on the page. This poses a security concern that we usually overlook for major sites.
However, another issue is tracking cookies. Sites are not able to block cookies set in such scripts. Making vine just an iframe allows scripts to that want to block all iframes also apply to vine. Since vine is defunct and only in archive mode it shouldn’t really be a holdout for scripts.
> Remove vine’s external script

- applications/dashboard/models/class.tagmodel.php
- applications/vanilla/controllers/class.discussionscontroller.php
Closes https://github.com/vanilla/vanilla/issues/7355
You can read full scope on this in the issue above.
The `setTagSql()` method of the TagModel was used in 2 places. We deprecated it.
In the DiscussionsController, tagged() endpoint/method and in the `getDiscussions()` method of the TagModel, which is never used. From that we decided to refactor how we fetched tagged discussions for the endpoint entirely.
We are now using the refactored `getDiscussions()` method of the TagModel that wasn't used before to fetch discussions in the tagged endpoint.
> Fix fatal error on /discussions/tagged pages

- applications/vanilla/modules/class.promotedcontentmodule.php
Closes #7312 
When calling the promotedcontent api with a score selector, the api was returning all discussions. Validation of  $minScore was failing because of its string value. 
**To test**
api/v1/discussions/promoted.json?selector=score&selection=2
should return all discussion with score >2
> PromotedContent: fixed score type validation

- applications/dashboard/views/deverror.master.php
- library/core/functions.error.php
With PHP 7.1 functions can no longer be called with too few arguments. This was causing issues with the Gdn_ErrorException constructor. I copied the defaults of its base class to help with this.
While fixing this issue I uncovered an issue with the cleanErrorArguments() function. It has no protection for infinite recursion and also doesn’t clean the security blacklist on object properties. I fixed this, but decided to make another version because I wanted a no side-effects version of the function.
> Add default parameters to Gdn_ErrorException and fix cleanErrorArguments()

- library/core/functions.general.php
- tests/Library/Core/AnonymizeIPTest.php
This update adds the `anonymizeIP` function for anonymizing IP addresses. The result is based on [IP anonymization in Google Analytics](https://support.google.com/analytics/answer/2763052?hl=en).
> The IP anonymization feature in Analytics sets the last octet of IPv4 user IP addresses and the last 80 bits of IPv6 addresses to zeros [...]
If the function receives an invalid IP address, the result is `false`.
> Add function to anonymize IP addresses

- applications/dashboard/src/scripts/dom.ts
Goes with https://github.com/vanilla/rich-editor/pull/59
Ensure script will now work far more consistently in different browsers.
Whats new:
- Rejections are cached. _Why: Firefox does not re-throw the script rejection. Additionally a timeout error will be rethrown immediately if someone tries to load the script again._
- Creates a new error instead of throwing the `ErrorEvent`. onerror(err) gives an inconsistent value for `err` in some browsers it is an `ErrorEvent`, in others its and `Error` and `ErrorEvent` itself is not consistent. Instead I'm just creating my own error.
- clears the timeout on success so an error is not unnecessarily thrown (or cached).
This can all be tested in the new embed loader PR https://github.com/vanilla/rich-editor/pull/59.
> Make ensureScript more robust

- tests/APIv0/SmokeTest.php
These ApiV0 integrations tests, tests the users ability to a bookmark on a discussion and remove a bookmark on a discussion. The remove bookmark test (testRemoveDiscussionBookMark()) depends on the add bookmark test (testDiscussionAddBookMark()) to setup a bookmarked discussion.
closes Vanilla#7087
> Add Bookmark Discussion Integration Test

- applications/dashboard/views/rss.master
Moving "items" at the bottom of the channel, as per
>According to the RSS Advisory Board's Best Practices Profile, all item elements should appear after all of the other elements in a channel.
> Replaced tabs by spaces, fix spacing, moved items to the bottom of the channel in rss.master

- applications/vanilla/models/class.commentmodel.php
That method has a lot of nested if-clauses. I replaced them by `if (!condition) { return; }`
The other "bigger" change in this PR is that the following while block:
~~~
$markAsRead = true;
while ($discussion = $discussions->nextRow(DATASET_TYPE_ARRAY)) {
if ($discussion['Read']) {
continue;
}
$markAsRead = false;
break;
}
~~~
with array functions:
~~~
if (in_array(false, array_column($discussions->resultArray(), 'Read'), true) {
return;
}
~~~
> Refactor CommentModel->setWatch

- applications/vanilla/js/discussion.js
Required for https://github.com/vanilla/rich-editor/pull/70
This PR now fires some native events (with the same naming convention and browser compatible style as our `X-DOMContentLoaded` event which bridges our contentLoaded event).
This allows us to bridge our old js to our new ones that don't use jquery or interop directly.
> Trigger native events for post and edit of a comment

- applications/dashboard/controllers/api/MediaApiController.php
- library/Vanilla/ImageResizer.php
- library/Vanilla/UploadedFileSchema.php
JPG is one of the allowed extensions under the API v2 media endpoint. Its four-letter-word counterpart, JPEG, is not. This update remedies that in the following way:
1. Creates a new `getExtType` method in the `ImageResizer` class. There are at least a couple areas of Vanilla that were already performing similar functionality in separate ways, using the data obtained from the `getTypeExt` method.
1. Moves a JPEG kludge from the `imageTypeFromExt` method into `getExtType`.
1. Refactors the `imageTypeFromExt` method to use `getExtType`.
1. Refactors the POST method of the media API controller to use `ImageResizer::getExtType`.
1. Improves error messaging when an invalid file extension is detected. Currently, the message reads "... is not an allowed upload type." It will now read "... …
> Allow JPEG uploads under the API v2 media endpoint

- applications/dashboard/src/scripts/app/user-content/embeds/soundcloud.ts
- library/Vanilla/Embeds/SoundCloudEmbed.php
- tests/Library/Vanilla/Embeds/EmbedManagerTest.php
This fix allows for SoundCloud "sets" and "user" pages to be embeddable.  The embed url is different in each case, as is the the specific id that is used.  The parsehtml function was modified to filter out whether the url is a track, set or user and returns a post id and embed url for each case.  Additional testing was added to ensure the proper response.
Test links
Closes Vanilla#7366
> Fixed broken soundcloud embed urls

- library/Vanilla/Embeds/VimeoEmbed.php
This fix allows for the vimeo embed to support some different url types and throws an exception if the video id can't be parsed by the posted url type.  The regex was also modified to parse only the url path instead of the full url.
The is an issue open to address how we treat the fallback embed type, so that we don't have to throw an error. Vanilla#7365
Test links:
https://vimeo.com/277405526
https://vimeo.com/channels/staffpicks/277826934
https://vimeo.com/ondemand/nature365/113009024
Closes Vanilla#7405
> Fix Vimeo urls supported

- applications/dashboard/src/scripts/state/getStore.ts
Allows you to optionally type the results of `getStore` as anything extending the the core state. This improves typing of `getStore` particularly for external plugins like the rich editor.
Required for https://github.com/vanilla/rich-editor/pull/77 to build properly.
> Allow typing of state in getStore

- applications/dashboard/src/scripts/app/index.tsx
- applications/dashboard/src/scripts/app/user-content/embeds/codepen.ts
- bootstrap.php
- library/Vanilla/Embeds/CodePenEmbed.php
- tests/APIv2/MediaTest.php
- tests/Bootstrap.php
- tests/Library/Vanilla/Embeds/EmbedManagerTest.php
- tests/Library/Vanilla/Quill/Sanitize/ExternalEmbed/CodePenSanitizeTest.php
This feature adds  CodePen embed functionality.
A request is made to CodePen's API endpoint, and the data returned is parsed and used to reconstruct CodePen's iframe embed.  The height, id, class, iframe src and some styles where extracted from the html code sent back in the response.  The iframe is responsive so not additional css styles are needed.  
Additional media, embed, quill tests were added.
Closes Vanilla#7408
> Add CodePen Embed

- library/core/class.dispatcher.php
This addresses an issue during a refactor of the dispatcher to support dash-case names.
When dispatcher looks up a method it should use camelCase rather than CapitalCase.
This could still cause issues with the old behavior of the dispatcher, but is more sensible.
This should fix #7364, but will need some testing.
> Dispatcher should to camel-case controller methods when it canonicalizes them

- library/Vanilla/Quill/Blots/CodeBlockBlot.php
- library/Vanilla/Quill/Blots/TextBlot.php
The text blot was escaping its content on construct and on render. As a result all special characters were getting double encoded. I've fallen back to escaping just in the render. This required me to update the `CodeBlockBlot` to also escape in its render. This is the only blot that overrides `TextBlot::render()`.
> Fix double escaping in Quill rendering

- library/Vanilla/Embeds/SoundCloudEmbed.php
- tests/Library/Vanilla/Embeds/SoundCloudEmbedTest.php
This adds a test for the parsedHtmlResponse method in SoundCloud's Embed.
related to Vanilla#7406
> Add Unit Test for SoundCloud Embed

- library/Vanilla/Embeds/TwitchEmbed.php
- tests/Library/Vanilla/Embeds/TwitchEmbedTest.php
This allows for the getEmbedUrl and getUrlInformation methods in the Twitch Embed class to be test.
related to Vanilla#7406
> Add Twitch Embed Unit Tests

- applications/vanilla/controllers/class.discussionscontroller.php
- applications/vanilla/models/class.discussionmodel.php
Backporting #7240 after it has been reverted in the recent deploy.
> Backport: Fix cached announcements on Recent Discussions sometimes being filtered out (2.6)

- plugins/editor/class.editor.plugin.php
Added a default MIME type of 'application/octet-stream' in case:
- Uploaded file is an allowed file extension
&
- Extension has an unknown MIME
Closes #7270
> Fix Advanced Editor uploads failing if unable to determine MIME type

- library/core/functions.general.php
A recent refactor moved to retrieving discussions as arrays, instead of objects, in `getRecord`. Most of the references were updated, but it looks like `ShareUrl` slipped through the cracks. This update ensures it is properly set.
> Fix sharing discussions

- library/core/functions.general.php
Backporting #7461
> A recent refactor moved to retrieving discussions as arrays, instead of objects, in `getRecord`. Most of the references were updated, but it looks like `ShareUrl` slipped through the cracks. This update ensures it is properly set.
> Backport: Fix sharing discussions

- tests/APIv2/AbstractResourceTest.php
If you have an endpoint with a delete operation that supports the request body, the abstract API delete test currently fails. This seems to be due to GardenHTTP not supporting a request body for deletes. Instead, it forces an empty value. This update works around that to allow for an empty body, by default, for abstract API deletion tests.
> Fix abstract API delete test failing for endpoints allowing request body

- applications/dashboard/controllers/api/AbstractApiController.php
- applications/vanilla/controllers/api/DiscussionsApiController.php
- applications/vanilla/models/class.categorymodel.php
This update adds the ability to expand category data on rows returned in the discussions API v2 endpoint index.
1. `AbstractApiController::getCategoryFragmentSchema` has been added to implement a universal category fragment schema. This follows the same pattern as `getPostFragmentSchema` and `getUserFragmentSchema` in the same class.
1. `CategoryModel::expandCategories` has been added for joining category rows into other rows, under a "category" key. It essentially does the same thing as `UserModel::expandUsers`.
1. Support for "category" has been added to the "expand" parameter of the discussion endpoint's index.
Closes #6640
> Add ability to expand category to index of discussions endpoint

- library/core/class.format.php
Closes https://github.com/vanilla/vanilla/issues/7057
When a post fails to decode properly, instead of throwing an exception, we now are returning some alternative post content. In this case a message that the post could not be rendered and an warning icon that links to our Rich Editor doc. @tburry Said our vanillicon icon was fine for this purpose.
This doc isn't written yet so I've scaffolded out a doc based on the advanced editor. https://github.com/vanilla/docs/pull/292/files#diff-515d6632463f089e470986f0331af87aR117
**After**
1. Change the DB content of a `Rich` format post to something that isn't JSON. Adding some trailing slashes or characters should do the trick.
> Create rendering fallback for badly formatted posts.

- applications/vanilla/models/class.categorymodel.php
Allow an event to hook after a category has been successfully saved, thus providing the CategoryID that is lacking in the `Before` call. I also deleted old commented code at the same line as where this event belonged.
> Add the AfterSaveCategory event

- applications/dashboard/models/class.rolemodel.php
Fixes https://github.com/vanilla/support/issues/41
The changes to escaping broke this, even though we never needed to escape the "field" of the having clause in the first place.
> Fix query escaping throwing error when deleting a role

- applications/vanilla/models/class.categorymodel.php
Allow an event to hook after a category has been successfully **deleted**, providing the CategoryID as an arg. This is the [only addition](https://github.com/vanilla/vanilla/pull/7498/files#diff-f50b339a72d2e0205fa95db96e1f613aR1949) I've made.
I also removed an `else` block that was logically not required and made the code path more complex (and arguably made the event placement far more complex). This changed the indenting of said block, which is making this diff look super complex. I suggest reviewing it [with whitespace removed](https://github.com/vanilla/vanilla/pull/7498/files?w=1).
See also https://github.com/vanilla/vanilla/pull/7493
> Add the AfterCategoryDelete event

- library/core/class.format.php
This PR updates the HTML of our rich editor post rendering error to use some CSS classes from used by our notifications and warnings/and notes.
Eg. From warnings and notes
---
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/43152875-bfc4dac6-8f3d-11e8-920b-d8cd3b2be49c.png)|![image](https://user-images.githubusercontent.com/1770056/43152896-d0df0dd6-8f3d-11e8-8b83-d5082e82bb49.png)|
> Improve rich editor rendering error html

- applications/vanilla/models/class.commentmodel.php
- applications/vanilla/models/class.discussionmodel.php
- library/Vanilla/Formatting/Quill/BlotGroup.php
- library/Vanilla/Formatting/Quill/Blots/Embeds/MentionBlot.php
- library/Vanilla/Formatting/Quill/Parser.php
- library/core/class.format.php
- tests/Library/Vanilla/Formatting/Quill/ParserTest.php
Closes https://github.com/vanilla/rich-editor/issues/65
Acceptance criteria are in the issue.
Implements mention notifications for the Quill rendered mentions for discussions and comments.
Create posts and comments with mentions using the Rich Editor and verify that the notifications are sent according to the acceptance criteria of the original issue.
I've opted to add another parse method to the Quill parser `parseMentions`. Additionally there is an other utility method added to `Gdn_Format` (soon to be `\Vanilla\Formatting\FormatUtility`) to instantiate the parser, do a json decode, and return the names. This will get an array of usernames mentioned in a post. This is then conditionally used in the CommentModel and DiscussionModel, instead of our global `getMentions`.
`getMentions()` is …
> Add new mention notifications and tests

- applications/dashboard/models/class.activitymodel.php
- applications/dashboard/models/class.usermodel.php
- applications/vanilla/models/class.commentmodel.php
- applications/vanilla/models/class.discussionmodel.php
- bootstrap.php
- library/Vanilla/BodyFormatValidator.php
- library/Vanilla/Invalid.php
- library/core/class.model.php
- library/core/class.validation.php
- library/core/functions.validation.php
- tests/Bootstrap.php
- tests/Library/Core/ValidationFunctionsTest.php
- tests/Library/Core/ValidationTest.php
Several improvements to data validation are included. These include:
1. Refactor the `Gdn_Validation` class. One of the key improvements is allowing validation rule callbacks to update the value being validated. This can be done to improve formatting, alter the value's type and more.
1. Add the `BodyFormatValidator` class, which is used to validate a specific format. Currently, only rudimentary support for validating the "rich" format is provided. Instances of this class may be called as a function.
1. Add support for automatically using `BodyFormatValidator` from `Gdn_Validation`, if configured as an available rule.
1. Add `Gdn_Validation` to the container, configuring it to use `BodyFormatValidator`.
1. Add `Gdn_Validation` parameters to the constructors of several models for the sake …
> Add validation filters and the BodyFormatValidator class

- tests/Library/Core/ValidationTest.php
The build began failing after #7230 was merged, because it was a months-old branch and recent changes were made to bootstraping and tests. This update implements those changes in this old test class to restore the build.
> Fix bootstrapping issues in ValidationTest

- library/Vanilla/PageScraper.php
`PageScraper` was not sending a user agent along with its requests. This caused some sites (e.g. Facebook) to reject requests with an "upgrade your browser" message. A user agent is now sent along with the request. Facebook no longer rejects requests with this particular error.
Closes #7529
> Fix /api/v2/media/scrape requests not sending valid user agent when scraping

- library/Vanilla/Formatting/Quill/BlotGroup.php
- library/Vanilla/Formatting/Quill/Blots/HeadingBlot.php
- library/Vanilla/Formatting/Quill/Blots/Lines/AbstractLineBlot.php
- tests/Library/Vanilla/Formatting/Quill/ParserTest.php
Closes https://github.com/vanilla/vanilla/issues/7522
The easiest one to reproduce was to make a post with an empty heading, which would throw an exception. I've made a few changes to rectify this.
The heading issue sprung from a few things. I was not recognizing that a heading blot (specific in only ever being 1 line), could be made of only 1 operation. A heading with content is made up of 2 operations. 
1. Contains the content of the heading and inline attributes
2. Contains a single newline and the heading level.
An empty heading produces only the 2nd operation.
I've rectified this by using the existing Blot::hasConsumedNextOp() to determine where I need to look for the heading level. I also removed the Exception for an invalid heading level. With the current setup a blot with an …
> Fix parser errors in Quill renderer

- applications/dashboard/controllers/api/AuthenticateApiController.php
- applications/dashboard/controllers/api/UsersApiController.php
- applications/vanilla/controllers/api/DraftsApiController.php
Upon validating our swagger file against the spec I discovered some issues. Some of these were simple typos in our controllers while others were ordering problems where the correct schema is constructed, but after the swagger event which is a nope.
> Fix some API schema documentation bugs

- applications/dashboard/controllers/api/LocalesApiController.php
- library/Garden/Web/ResourceRoute.php
- library/core/class.controller.php
- tests/Library/Garden/Web/ResourceRouteTest.php
- tests/fixtures/src/DiscussionsController.php
- Modify the router to define endpoints with file extensions. Adding a .js file extension to a URL gets Varnish to kick in its caching.
- Send back appropriate cache control headers for translations.
> Fix translations from the locales API endpoint not being cacheable

- library/Vanilla/Formatting/Quill/BlotGroup.php
- library/Vanilla/Formatting/Quill/Blots/Lines/HeadingBlot.php
- library/Vanilla/Formatting/Quill/Parser.php
- tests/Library/Vanilla/Formatting/Quill/BlotGroupTest.php
- tests/Library/Vanilla/Formatting/Quill/ParserTest.php
I came across this while working on the in-editor formatting https://github.com/vanilla/vanilla/issues/7516.
Heading blots were not rendering properly if there were multiple separate inline formatted items inside of them. Luckily this structure of operations is already a solved problem. Switching the HeadingBlot to inherit from the `AbstractLineBlot` instead of the `TextBlot` directly solves the issue.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/43419167-3877726a-940e-11e8-84f3-beb9c7c0bbb6.png)|![image](https://user-images.githubusercontent.com/1770056/43419145-28ea14ec-940e-11e8-8870-0c3c7d4cde8e.png)|
I've added a parser test for this particular scenario as well.
> Fix quill rendering of heading with inline formats in it

- library/core/class.model.php
#7230 introduced the ability to verify post/content body formats. While it was enabled by default in instances created by the container, it was not enabled on `Gdn_Validation` instances created in `Gdn_Model::__construct`. For example, if you manually instantiate `CommentModel`, then saved a new comment with it, the additional body-validation rule wasn't run.
This update sees `Gdn_Model` grabbing its copy of `Gdn_Validation` from the container, which will be preconfigured for body format validation. If a row is being saved with a "Body" and "Format" field, and if `BodyFormatValidator` has a routine to handle the format, the row must pass body format validation.
Closes #7524
> Add default body content validation

- applications/vanilla/controllers/class.vanillasettingscontroller.php
- applications/vanilla/views/vanillasettings/posting.php
- plugins/editor/addon.json
- plugins/editor/class.editor.plugin.php
Closes https://github.com/vanilla/vanilla/issues/7527
Moves the formatting options from the editor plugin to the dashboard posting page.
- Adds config options `Garden.InputFormatter`, `Garden.InputFormatter`, `Plugins.editor.ForceWysiwyg` to the /settings/posting page.
- Advanced Editor settings are gone. In place of its previous settings page is a redirect to the /settings/posting page.
- Splits out the label descriptions into separate pieces without HTML in them and wraps them in translation functions.
- Allowing Rich Editor to hook into these settings: https://github.com/vanilla/rich-editor/pull/90
- Translation source strings in the locales repo: https://github.com/vanilla/locales/pull/69
- I've verified that all 3 of the config settings persist when saved.
- The force WYSIWYG option …
> Make editor formatting settings global in the post page

- applications/dashboard/models/class.assetmodel.php
The path to our polyfills have been broken after some changes to the files location. I've updated that location here. It is now putting together the path the same way the automatically loaded dashboard js scripts do.
Things like the rich editor should now work in Edge and IE again.
> Fix broken polyfill loading

- applications/conversations/models/class.conversationmodel.php
- applications/conversations/models/class.conversationsmodel.php
- applications/dashboard/models/class.activitymodel.php
This modifies the activity being created when a group invite is sent out.  The options passed to conversation model, allow the activity created in conversationmodel::notifyusers to be overridden.  Acitivitymodel::email is then passed options to construct and email with these parameters.
> Give addons more customization options when creating new notifications

- applications/dashboard/library/class.nestedcollection.php
- applications/dashboard/models/class.usermodel.php
- applications/vanilla/views/discussion/helper_functions.php
- library/core/functions.render.php
This PR belongs to epic https://github.com/vanilla/vanilla-patches/issues/331
Update setCalculatedFields in class.user.model to avoid calls to val()
Fixes: vanilla/vanilla-patches#325
Update cssClass function in fnctions.render.php to avoid val() calls
Fixes: vanilla/vanilla-patches#326
Update sortItems and addLink function in class.nestedcollection.php to avoid using val() function
Fixes vanilla/vanilla-patches#327
flattenArray fix for nestedcollection class to avoid val() calls 
Fixes: vanilla/vanilla-patches#329
Update discussionOptionsToDropdown function in dicussion/helper_functions.php to avoid val() calls
Fixes vanilla/vanilla-patches#328
> Continuous changes to get rid of deprecated val() function

- applications/dashboard/controllers/class.authenticatecontroller.php
- applications/dashboard/controllers/class.entrycontroller.php
- applications/dashboard/controllers/class.utilitycontroller.php
- bootstrap.php
- library/Vanilla/Web/CacheControlMiddleware.php
- library/core/class.controller.php
This PR is an attempt to put the application’s cache headers inline with our Varnish overrides so that the application has more control over browser and proxy caching.
- Signed in users don’t cache by default. This behavior is unchanged.
- Guests cache requests for two minutes.
- The CacheControlMiddleware handles caching for the API.
- Since endpoints can now opt-out of caching the /authenticate, /utility and /entry endpoints now do so.
- HTTP 1.0 headers are removed and added when headers are sent. This allows programmers to only code with just the Cache-Control header.
This is a fairly significant change so I’m requesting people from Ops also review the PR. We should also test this on infrastructure before merging.
> Add the CacheControlMiddleware and tweak default caching

- applications/dashboard/models/class.usermodel.php
**deprected** typo fixes plus some change to check if user
var is empty when setCalculatedFields called
Fixes: https://github.com/vanilla/vanilla/issues/7603
> change usermodel after getting rid of some val() calls

- library/Vanilla/Formatting/Embeds/EmbedManager.php
- library/Vanilla/PageScraper.php
- tests/APIv2/MediaTest.php
- tests/Library/Vanilla/PageScraperTest.php
- tests/fixtures/html/jsonld.htm
- tests/fixtures/html/koi8-1.htm
- tests/fixtures/html/koi8-2.htm
- tests/fixtures/html/koi8-3.htm
- tests/fixtures/html/unicode-http-equiv.htm
- tests/fixtures/html/unicode-no-hint.htm
- tests/fixtures/html/unicode-xml-comment.htm
- tests/fixtures/html/unicode-xml.htm
- tests/fixtures/html/unicode.htm
Unfortunately, DOMDocument is built with a version of libxml that does not understand HTML5 too well. This cause UTF-8 characters to not be read properly. In an attempt to make our scraper work with the majority of HTML5 documents this small change adds a charset and hopefully doesn’t kill efficiency.
I am well aware that this does not 100% solve the problem. If anyone wants to take a stab at this issue I am fine with that given:
1. Some profiling is done to make sure a solution doesn’t make large documents kill our servers.
2. There are no regression bugs. I recommend adding more character cases to the test files or even a non utf-8 test file.
> Fix UTF-8 page scraping for HTML 5 pages

- library/core/class.validation.php
#7230 made some improvements to validation in Vanilla, but it also introduced a backwards-compatibility-breaking change where validation functions could no longer return a custom error message. Instead, validation functions are expected to return a boolean value or an instance of `Vanilla\Invalid`.
You could see this behavior manifested with the "ValidateLength" rule, which would fail if content exceeded a maximum length and return an error message stating how much longer the content was than allowed (e.g. "Body is 100 characters too long."). Since validation functions could no longer return custom error messages, the name of the rule was used to get the translation string and build the message in [Gdn_Form::errors](https://github.com/vanilla/vanilla/blob/ed28f187337e14c49aa5956ed67d48fb37 …
> Fix empty error message when saving a large discussion

- .gitignore
- composer.json
- composer.lock
- tests/travis/diff-standards.sh
- tests/travis/main.sh
This update adds enforcement of [vanilla/standards](https://github.com/vanilla/standards) rules on changed code in a pull request. It accomplishes it in the following way:
1. Run a `git diff` on the current branch's code versus the pull request's target branch's code. Travis creates a shallow clone with only refs for the current branch, so resetting the refs and grabbing branches is required to perform this step. Capture the output.
1. Perform a [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) scan, using the rules from Vanilla's coding standards repo, on all files with changes. Capture the output.
1. Use [coverageChecker](https://github.com/exussum12/coverageChecker), along with the output from the previous two steps, to filter out the PHP_CodeSniffer messages not …
> Enforce coding standards on changed code in build

- .gitattributes
Previously we were marking only particular JS directories as binary, but we can pretty safely assume that any minified JS file is a binary to git. These things are not mergeable.
> Mark minified javascript files as binary to git

- tests/APIv0/SmokeTest.php
Added Integration test for the following
1. Alter the category of a saved draft discussion before posting.
2. Save a draft from the New Comment form on a discussion.
3. Post a saved draft comment to a discussion.
Closes Vanilla#7503
> Add Integration tests for comment drafts and modifying drafts

- applications/vanilla/models/class.categorymodel.php
- library/core/class.cache.php
- library/core/class.pluginmanager.php
- library/core/class.request.php
- library/core/functions.general.php
remove unnecessary strtolower() calls  in pluginmanager
Fixes: #7615
Implement few static variables to avoid unnecessary calls to port() and host() functions
in function url() of Gdn_Request class 
Fixes: #7617
Update calculate() function of class.categorymodel to avoid val() calls
Fixes: vanilla/vanilla-patches#343
Refactor calculateUser function of class.categorymodel to avoid val() calls
Fixes: vanilla/vanilla-patches#348
Refactor stripKey function of class.cache (memcached) to avoid val() calls
Fixes: vanilla/vanilla-patches#352
Refactor makeKey function of class.cache (memcached) to avoid val() calls
Fixes: vanilla/vanilla-patches#351
Refactor joinUserData function of class.categorymodel to avoid val() calls
Fixes: vanilla/vanilla-patches#349
> Implement memory optimizations

- applications/dashboard/models/class.tagmodel.php
Closes [#7641](https://github.com/vanilla/vanilla/issues/7641)
discussions/tagged/{tag} was not displaying latest discussions.
> Fix tagged discussions page not including the most recent discussions

- library/core/class.memcached.php
Update array $finalOptions type casting.
We experienced errors on cluster 40011
`
Aug 21 09:29:30 app2.cl40011.vanilladev.com php-error:  2018-08-21T12:29:30Z	php-error	{"level":"Fatal","error":"Uncaught TypeError: Argument 2 passed to Gdn_Cache::makeKey() must be of the type array, null given, called in /var/www/frontend-b755a7995be475/library/core/class.memcached.php on line 443 and defined in /var/www/frontend-b755a7995be475/library/core/class.cache.php:644","program":"php-error","source":"app2.cl40011.vanilladev.com"}`
to fix it here is the patch.
> memcache type error when posting comments

- library/core/class.auth.php
Seems like getAuthenticator got unintentionally renamed Authenticator by mistake.
https://github.com/vanilla/vanilla/commit/cb680b454a08ce79335134ec7e0d900e569eef63#diff-08f731f7271fdcee4302d371b457308cR265
> Fix refactoring gone wrong

- applications/dashboard/models/class.logmodel.php
- applications/dashboard/models/class.spammodel.php
What this PR does
---
We recently updated our handling of IPv6. We found 2 cases where IPs aren't encoded/packed prior to insertion.
We need to encode IPs before inserting them into the Log table to make sure we aren't busting the column limit. This PR does this. We also need to encode IPs before inserting them when restoring from the log, our current process decodes them on fetch. This PR does this.
Strict Mode & IPv6
---
FYI, With our current IP columns set to `VARBINARY 16`, without MySQL strict mode it will actually truncate the value for IPv6, hence, storing a erroneous IP, but with MySQL strict mode it will fail entirely, throwing a `Data too long for column ...` error.
> Fix spam logging & log restoring by packing IPs before insertions

- tests/Bootstrap.php
#7647 improved Vanilla's handling of IPv6, but in the process it removed a call to `forceIPv4` from request processing. This call would force a dummy IP address, if none was detected. Since Vanilla wasn't setting up an IP address in its tests, this function was picking up the slack. Once that function was removed, IP addresses were no longer being set in tests, and we began seeing failures in builds (although, strangely, not in core).
This update sets up tests to use the IPv6 localhost address. This should make it a little easier to test IPv6 support, as well as give us an actual IP address for the portions of Vanilla that depend on one being available.
> Fix IP address not being available in tests

- applications/dashboard/models/class.logmodel.php
We fixed restoring of SPAM in [7653](https://github.com/vanilla/vanilla/pull/7653)
but when restoring a SPAM that was caught by Akismet, we get the error 
because of `$data = ipEncode($log['Data']);`
> Akismet spam restore- update ip encoding

- library/core/functions.general.php
The call to `filter_var` in `anonymizeIP` is using a bitwise "and" for its flags, which is not what should be used. The bitwise "or" should be used, so the bits from both flags are included, instead of only overlapping bits.
[There is testing coverage for this function.](https://github.com/vanilla/vanilla/blob/380de43021ba29aa30a624fc8f67c145fa8dd071/tests/Library/Core/AnonymizeIPTest.php)
> Fix filter_var flags in anonymizeIP

- plugins/editor/class.editor.plugin.php
We were having issues `Uncaught TypeError gdn.atCompleteInit is not a function` with the advanced editor in conversations and signatures after the recent changes to javascript.
The new "legacy" JavaScript doesn't add that gdn.atCompleteInit function to those pages, adding it by default will fix those issues.
Vanilla will only add the file once even if requested multiple times over the stack.
> Fix JavaScript error when using Advanced Editor outside the Vanilla application

- applications/dashboard/controllers/class.entrycontroller.php
- applications/dashboard/views/entry/connect.php
Why we need this
---
Users using SSO couldn't register with an "invalid" username. After investigation we realized that pr #7250 which introduced our new username validation logic was missing an important part of its implementation. At this point we are not exactly sure why (some merging voodoo perhaps).
Locally re-introducing these changes allowed invalid usernames (spaces and dots) to register properly if we are linking by email or if it's a complete new user without any linking to make.
A little history of what happened and when
---
1. A feature branch, feature/usermodel-name-validation, was created for work on updating username validation.
1. PR #7148, targeting feature/usermodel-name-validation,  was created on May 1st to update username validation.
1. PR #7163, also targeting …
> Fix new username validation being incorrectly applied to SSO connections by re-applying code lost in bad merge

- composer.lock
- tests/travis/diff-standards.sh
Vanilla's composer "lint-diff" command can return a non-zero result, even if PHP_CodeSniffer returns a non-zero result, due to the Travis-specific code at the end of the script hijacking the default result. This update rectifies that by ensuring the underlying script always returns the result of the PHP_CodeSniffer command.
The composer.lock file is also updated here to use the latest version of Vanilla's coding standards.
> Fix lint-diff command reporting failure on success

- applications/dashboard/models/class.tagmodel.php
closes [#87](https://github.com/vanilla/support/issues/87)
related [#7642](https://github.com/vanilla/vanilla/pull/7642)
PR [#7642](https://github.com/vanilla/vanilla/pull/7642) was ordering discussion by page on DiscussionID. I modified the query to order tagged discussion by DateLastComment.
1. Tag enough discussions so that you can have multiple pages on /discussions/tagged/{Tag.Name}.
1. Get the full list of discussions for a tag, sorted by the `DateLastComment` field. You can use a database query for this.
1. View /discussions/tagged/{Tag.Name}, using your chosen tag. Verify the results are the same as your list from step two for the first page.
1. Advance to the second page. Verify your list from step two continues in the same order on this page.
> Tagged Discussions: Update tagged discussions sort order

- applications/dashboard/library/class.nestedcollection.php
- applications/dashboard/models/class.usermodel.php
- applications/dashboard/modules/class.headmodule.php
- applications/vanilla/library/class.categorycollection.php
- applications/vanilla/models/class.categorymodel.php
- library/SmartyPlugins/function.asset.php
- library/core/functions.general.php
Refactor joinUsers function of class.usermodel to avoid val() calls
Fixes: vanilla/vanilla-patches#350
Refactor _formatStringCallback function of functions.general to avoid val() calls
Fixes: vanilla/vanilla-patches#361
Refactor getVisibleCategories function of class.categorymodel to avoid val() calls
Fixes: vanilla/vanilla-patches#360
Refactor buildCssClass function of class.nestedcollection to avoid val() calls
Fixes: vanilla/vanilla-patches#359
Refactor toString function of class.headmodule to avoid val() calls
Fixes: vanilla/vanilla-patches#364
Refactor flattenTreeInternal function of class.categorycollection to avoid val() calls
Fixes: vanilla/vanilla-patches#365
Refactor smarty_function_asset function of function.asset.php to avoid val() calls
Fixes: vanilla/vanilla-patches#366
> Ongoing removal of val from codebase

- applications/dashboard/design/style-compat.css
- applications/dashboard/scss/editor/_richEditor.scss
Closes https://github.com/vanilla/support/issues/83
Removes the extra margins in Firefox. Breaks should not be receiving additional margins.
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/44601319-0b42b480-a7aa-11e8-82de-ad1ffd3674d8.png)|![image](https://user-images.githubusercontent.com/1770056/44601279-f1a16d00-a7a9-11e8-96c7-f08fa3aa3524.png)|
> Remove extra line break margins

- tests/Library/Vanilla/Formatting/Embeds/EmbedManagerTest.php
Fixing the broken test here. I'll need to investigate why travis didn't catch this when it was introduced in https://github.com/vanilla/vanilla/pull/7709
> Fix broken embed manager test

- applications/vanilla/models/class.categorymodel.php
Currently when a category is created if the allowdiscussions parameter isn't passed, the default is set to an empty string.  This is fine when a category is created in the dashboard as is the allowdiscussions parameter is always set to 1, but when creating a category through the api/v2/categories endpoint, the value is not passed so the default is '' (evaluates to false) and discussions aren't allowed in the created category. 
There's a lot of code the is redundant, as trying to do a refactor could cause some unforeseen side effects. 
Closes vanilla/support#90
> Categories set allowdiscussions default to 1

- library/Vanilla/Models/Model.php
Vanilla has a problem with sharing the result of two queries, so the strict result checking in the new base model's `update` method is *too* strict. It needs to be loosened up until #7720 has been addressed.
This update simplifies `Vanilla\Models\Model::update` to return a boolean `true` by default. If an error is encountered during the execution of an update query, the underlying function to `Gdn_SQLDriver` and `Gdn_Database` will be responsible for throwing relevant exceptions up to this level.
> Fix base model update method improperly evaluating success criteria

- applications/dashboard/controllers/class.settingscontroller.php
Ever since bans are added from a popup (Dashboard v3) the page does not automatically refresh after changes have been made.
This is really confusing for users.
> Refresh page after adding/deleting bans

- applications/dashboard/controllers/class.searchcontroller.php
Debug trace:
Could not find file 'menu.css' in folder 'dashboard'.
> Remove nonexistent CSS file from search controller

- library/core/class.format.php
This performance optimization never worked for Html because the arguments are switched.
> Do not filter RSS html twice

- applications/vanilla/views/discussions/index_rss.php
HTMLawed already filters all invalid characters.
Fixes #4490 and #3218
> Filter invalid characters from discussion titles in feeds

- plugins/Facebook/class.facebook.plugin.php
As cURL is required by Vanilla and it's used in this plugin, good idea is to change file_get_contents to cURL as some servers have allow_url_fopen set to false due security reasons.
> Changing file_get_contents in getProfile() to cURL

- library/Garden/StaticCacheConfigTrait.php
- library/Garden/StaticCacheTranslationTrait.php
- library/core/class.locale.php
Fixes: https://github.com/vanilla/vanilla/issues/7735
Add condition to fire event `beforeTranslate`.
Fixes some issue with original StaticCacheConfigTrait and StaticCacheTranslationTrait (was not calling correct method and because of that was not caching the response)
> Remove unnecessary event fire 'beforeTranslate'

- applications/vanilla/models/class.discussionmodel.php
- applications/vanilla/settings/class.hooks.php
The DiscussionModel::checkPermission calls userModel_getCategoryViewPermission_created hook  to validate if a user has permission to view a discussion in a certain category.  The permission check in this hook is done against the user.  The Ranks plugin sets the user permission on the session, so the the permissions in the session don't match those in the database.  Certain actions(warn, report) are denied as a result.  This was because 
1) only Administrator and Moderators were given privileges on that category.  
2) This permission check was done against the user's role permissions, not the rank permissions which are set in the session.
To avoid this CategoryModel::checkPermission is called if there's a valid session matching the userid  and we fall back to …
> Use CategoryModel::checkPermission to validate user's permission to view discussions in categories.

- package.json
- tests/javascript/webpack.test.config.js
- tsconfig.json
- yarn.lock
Closes https://github.com/vanilla/vanilla/issues/7772
Blocking https://github.com/vanilla/knowledge/pull/131
- Uses the `ForkTsCheckerPlugin` for typechecking, similar to our main build. This resolves the primary type-checking issue from https://github.com/vanilla/vanilla/issues/7772.
- Drops the extra babel step in loader chain for typescript files. Our current typescript setup does not require this step.
- Adds the `TsConfigWebpackPlugin` to allow us to use our path aliases from our `tsconfig.json` file instead of redefining those aliases.
- Fixes a typo in the tsconfig file making it invalid JSON to some parsers.
> Improve javascript test setup

- library/core/class.configuration.php
- library/core/class.format.php
* Deprecated the faulty function containing unserialize in Format class.
* Added (copy pasted) that function as a private deprecated method in both classes in the configuration file so we are able to call it internally. Also leaves room for an eventual complete removal from both classes in that file.
* Added the allowed class => false in the Format class and in both classes on the configuration file.
These are the changes @tburry requested.
> Tweak how configuration reads serialized data

- library/core/class.session.php
Ongoing optimization.
Implement StaticCacheConfigTrait on Gdn_Session to avoid multiple c() global function calls
Relates to #7734 and #7689
Fixes: https://github.com/vanilla/vanilla/issues/7759
> Add caching of config val in Gdn_Session::checkPermission

- library/Vanilla/Utility/Deprecation.php
- library/core/functions.general.php
Add check for config 'Vanilla.Deprecation.Enabled' if false - to not output any deprecation error
This will allow to disable log flooding if ever deprecated function detected on particular client instance.
> Add config toggle to Vanilla\Utility\Deprecation::log

- applications/dashboard/models/class.rolemodel.php
closes #7758 
When a role is deleted with a replacement role selected , table GDN_UserRole is getting orphaned role records.
- Delete a role 
- Select a replacement role
- Check GDN_UserRole table (role is not deleted)
> Roles: userRole table not getting updated after role is deleted, leaving orphaned records

- library/database/class.dataset.php
Idea by @charrondev here: https://github.com/vanilla/vanilla/pull/7692#pullrequestreview-150776737
However, Gdn_DataSet does not benefit from array access as the result set is an array anyway.
But the rows it contains can be either objects or arrays.
If these objects implement the `ArrayAccess` interface, result rows can be accessed as both `$row['DiscussionID']` and `$row->DiscussionID` interchangeably. This would allow refactoring all views to use array notation _right now_, independently of model changes, and would ease the transition to array only return types.
Conveniently, there is already a PHP standard class that implements all array functionality:
http://php.net/manual/en/class.arrayobject.php
Using the `ARRAY_AS_PROPS` flag makes this "backwards compatible" as it allows changing …
> Add array access to object rows in DataSet results

- applications/dashboard/controllers/api/UsersApiController.php
- tests/APIv2/UsersTest.php
This update adds the ability to get information about the current user from the users API v2 endpoint. Requesting /api/v2/users/me should respond with values reflecting the current session. The existing "user fragment" schema is used for the output schema.
```json
{
"userID": 1,
"name": "Vanilla",
"photoUrl": "//we.vanillicon.com/v2/b58996c504c5638798eb6b511e6f49af.svg",
"dateLastActive": "2018-09-01T01:00:00+00:00"
}
```
```json
{
"userID": 0,
"name": "Guest",
"photoUrl": "http://example.com/applications/dashboard/design/images/defaulticon.png",
"dateLastActive": null
}
```
Closes #7733
> Add ability to get fragment for the current user to users API v2 endpoint

- library/core/functions.deprecated.php
Deprecate trueStripSlashes global function.
Apply error log output on production for final check.
Relates to: #7776
Fixes: #7792
> Deprecate trueStripSlashes global function.

- library/core/functions.deprecated.php
Apply error log output on production for final check.
I did not find any calls to that function in our projects.
Relates to : #7776 
Fixes: #7790
> Deprecate viewLocation global function.

- composer.lock
PR to update vanilla's composer.lock file because vanilla/garden-password was recently updated. 
**Note**. When I ran composer update, smart was updated as well.  Not sure if we should update that as well.
> Update garden-password and Smarty versions in composer.lock file

- applications/dashboard/controllers/class.importcontroller.php
- applications/dashboard/settings/class.hooks.php
- Community imports are now behind a feature flag that is default disabled.
- Specific import paths must now be under PATH_UPLOADS and that path is always prepended to a custom path.
> Put imports behind a feature flag and harden custom import paths

- applications/dashboard/controllers/class.importcontroller.php
- applications/dashboard/settings/class.hooks.php
Backporting #7798 
- Community imports are now behind a feature flag that is default disabled.
- Specific import paths must now be under PATH_UPLOADS and that path is always prepended to a custom path.
> Backport: Put imports behind a feature flag and harden custom import paths (2.5)

- applications/dashboard/controllers/class.importcontroller.php
- applications/dashboard/settings/class.hooks.php
Backporting #7798 
- Community imports are now behind a feature flag that is default disabled.
- Specific import paths must now be under PATH_UPLOADS and that path is always prepended to a custom path.
> Backport: Put imports behind a feature flag and harden custom import paths (2.6)

- library/core/class.proxyrequest.php
> Backport: Only allow http/https in ProxyRequest (2.5)

- library/core/class.proxyrequest.php
> Backport: Only allow http/https in ProxyRequest (2.6)

- applications/dashboard/controllers/api/AuthenticateApiController.php
- applications/dashboard/controllers/api/AuthenticatorsApiController.php
- applications/dashboard/controllers/class.authenticatecontroller.php
- applications/dashboard/controllers/class.importcontroller.php
- library/Vanilla/Exception/FeatureNotEnabledException.php
- library/Vanilla/FeatureFlagHelper.php
It was proposed in #7797 that Vanilla throw a specific, explicit exception for whenever access to disabled feature is detected with the `FeatureFlagHelper` class. This update implements that exception.
1. Add `FeatureNotEnabledException` class.
1. Add `FeatureFlagHelper::ensureFeature` method. This method does the same thing `FeatureFlagHelper::throwIfNotEnabled` did, only it forces a standard exception.
1. Deprecated `FeatureFlagHelper::throwIfNotEnabled` in favor of `FeatureFlagHelper::ensureFeature`.
1. Remove call to global `c` function in favor of `Gdn::config` in `FeatureFlagHelper::featureEnabled`.
1. Update all calls to `FeatureFlagHelper::throwIfNotEnabled`, including the one added in #7798.
> Add explicit exception for accessing disabled features

- applications/dashboard/controllers/class.importcontroller.php
- applications/dashboard/settings/class.hooks.php
Backporting #7798 
- Community imports are now behind a feature flag that is default disabled.
- Specific import paths must now be under PATH_UPLOADS and that path is always prepended to a custom path.
> Backport: Put imports behind a feature flag and harden custom import paths (2.7)

- library/core/functions.general.php
This also prevents an error caused by a newly added type hint.
> Only check an activity’s permission if it was found

- library/database/class.dataset.php
Due to memory-usage concerns in production, we're reverting code introduced in #7705.
> Revert "Allow array access on DataSet results"

- library/core/class.vanillahtmlformatter.php
This PR is to satisfy issue https://github.com/vanillaforums/rapidminer/issues/10
This PR will add 'rapidminer' to $config['schemes'] in the VanillaFormatter class in order to make it possible to create and post URLs like rapidminer://rapidminer.com/myfiles .
> Add the string ‘rapidminer’ as an acceptable scheme to be output as HTML

- library/core/functions.general.php
- tests/Library/Core/GeneralFunctionsTest.php
- Allow a schema-less host (ex. //example.com).
- Only work on http and https schemes.
- Simplify the code a bit.
- Add unit tests.
> Fix the absoluteSource() function

- library/Vanilla/AddonManager.php
- tests/Library/Vanilla/AddonManagerTest.php
- tests/fixtures/plugins/bad-require/addon.json
Enforce what add-on types and keys can be passed to the `AddonManager` so that appropriate error messages are surfaced to the user.
> Enforce add-on types and keys

- plugins/Twitter/class.twitter.plugin.php
<strike>This was never correct</strike>(see below), but twitter did not check for a correct callback_url until recently:
https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342
related:
https://github.com/vanilla/docs/pull/299
> Fix Twitter callback URL for profile connections

- library/setup/ComposerHelper.php
Currently, post-commit hooks skipping the build causes your prompt to appear after this warning.
> Open newline after skip build warning

- README.md
- library/setup/ComposerHelper.php
- Updates README to reference build tool documentation
- Updates the post-install command to install node_modules by default. Closes https://github.com/vanilla/vanilla/issues/7664
The first is to improve documentation. The second is something we want to always do in local and infrastructure.
> Update build tool documentation and auto-install addon dependencies

- library/setup/ComposerHelper.php
The wrong build flag was being passed from the post install script to the build tool. [The proper flag](https://github.com/vanilla/vanilla/blob/master/build/scripts/options.ts#L19) is `--disable-validation`. Previously it was called `--low-memory` but was changed at @DaazKu's suggestion. It seems all the variables got changed except for the string constants that makes up the flag.
> Fix composer post-install always running code validation

- applications/dashboard/models/class.usermodel.php
Closes https://github.com/vanilla/vanilla/issues/7564
Simply following the call stack from the issue above, when creating one of the where clauses, escaping the field results in something like this:
```
`inet6_ntoa(LastIPAddress)` like :inet6_ntoaLastIPAddress
```
We are including the MySQL native function in the column name when escaping the field.
We are doing that in 2 places that are resulting in a fatal error when searching for users through ban rules on a IP Address rule.
By setting the `$escapeFieldSql` parameter of the where method of the SQL object we will prevent adding the back ticks as illustrated above, users cannot alter that field and therefore changing this to not be escaped should not open us to any SQL exploit.
This is a result of this …
> Fix ban rules fatal error on search by not escaping field in SQL query

- library/Vanilla/AddonManager.php
- tests/Library/Vanilla/AddonManagerTest.php
- tests/fixtures/bad-addons/CobbSalad 1.1/addon.json
- tests/fixtures/bad-themes/KingFrank 1.2/addon.json
Add-ons with invalid keys should not be included in scans, but should also not cause an exception.
Closes #7873.
> Fix addon scanning when an addon has a bad key

- library/Vanilla/Models/Model.php
- library/Vanilla/Models/PipelineModel.php
When `Vanilla\Model\Model` was created, it was mostly made private. In recent development projects, I've seen reason to allow access to some of these private members from child classes. So, that's what I'm doing here.
1. The `sql` method is now protected, instead of private.
1. There's a protected accessor method for the `table` property.
1. I fixed a dumb copy-paste error in `PipelineModel`.
> Make new base model class more accessible to its child classes

- js/embed.js
We have not supported non-pretty URLs for a few years now (`/index.php?p=discussions` instead of `/discussions`). There remains one URL in the embedding Javascript that still routs using the `p` variable that breaks local builds and impedes local testing/development.
This PR will remove that line from embed.js.
This has been tested on infrastructure, and has no side-effects.
For testing: https://github.com/vanilla/stub-embed-providers/pull/3
> Fix embedding comments on local builds

- library/Vanilla/Database/Operation/CurrentDateFieldProcessor.php
- library/Vanilla/Database/Operation/CurrentUserFieldProcessor.php
- library/Vanilla/Models/Model.php
- library/Vanilla/Models/PipelineModel.php
- tests/Library/Vanilla/Database/CurrentDateFieldProcessorTest.php
- tests/Library/Vanilla/Database/CurrentUserFieldProcessorTest.php
- tests/fixtures/src/BasicPipelineModel.php
This update introduces the first two "pipeline processors": one for the current user ID, one for the current date-time. These classes will be responsible for automatically handling `InsertUserID`, `UpdateUserID`, `DateInserted` and `DateUpdated`.
1. When added as a processor on a `PipelineModel` instance, `CurrentUserFieldProcessor` will add the current user's user ID to an "InsertUserID" field for insert operations, and "UpdateUserID" for update operations.
1. Similar to the above, when `CurrentDateFieldProcessor` is added as a processor on an instance of `PipelineModel`, it will add the current date to the `DateInserted` field when performing an insert, or to the `DateUpdated` field when performing an update.
Tests are included to further illustrate usage.
Closes #7825
> Add date and user field pipeline processors

- applications/dashboard/models/class.usermodel.php
Closes #7713 
The problem was with our new validation logic, users with embedded sso couldn't bypass the username validation even when coming from a trusted provider.
The goal here was to apply the same changes to the validation we already did in the EntryController `connect` endpoint. I tried to make it as consistent  to the EntryController as possible in the UserModel `connect` endpoint.
Steps I took to test this:
* Setup up an embedded site (with vanilla-docker)
* Setup up an embedded sso (JS Connect) (with vanilla-docker)
* `Registration.AutoConnect = true`
* I added the vanilla_sso string to my embedded site for every user I was testing (with stub-sso-providers JsSSOString method for JS Connect
* After creating a user and signin with him on the SSO, hitting the homepage of the …
> Make embedded sso (UserModel::connect) validation more relax for trusted providers

- plugins/ProfileExtender/class.profileextender.plugin.php
Context
---
A customer requested we add the "Location" field to the endpoint. I thought it would be good to ask around and see what fields aren't a part of the current data this endpoint generate and add them to reduce the number of export request we receive.
Added fields
---
Location (customer request)
LastIPAddress
Roles (concatenated names)
Rank (name) (only if plugin is enabled)
Optimizations
---
I also made a small optimization by calling the `select()` function only once with an array instead of once for every field in the basic query.
Other info
---
This endpoint is capped at 100,000 users through the `$UserMegaThreshold` variable of the `UserModel`. If you have more than that it returns the message "you have too many users" before even trying to fetch them. Joining on roles …
> Add different fields frequently requested to /utility/exportprofiles

- applications/vanilla/models/class.categorymodel.php
closes [7901](https://github.com/vanilla/vanilla/issues/7901)
details in the referenced ticket.
Ex.  a user is following 2 categories with CategroyIDs[1,3]
When debugging this, if you put a break point in [class.categorymodel.php#L1742](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.categorymodel.php#L1742) we had [$iDs](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.categorymodel.php#L1739) 
userData would be
[ $row = ($userData[$iD] ?? false);](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.categorymodel.php#L1748) would be false , and when in view "Following" . instead of having the option to Unfollow a category, you would still see the "Follow" option.
I updated $categories array_keys …
> Category-Following: Displaying Unfollow option when filtering by followed categories

- .github/ISSUE_TEMPLATE/bug_report.md
Per GitHub community profile guidelines, adding a generic bug report template. We can refine this and add more templates as time goes on, but this is a fine starting point.
> Add first issue template

- library/src/scripts/state/ReduxActions.ts
- library/src/scripts/state/ReduxReducer.ts
- library/src/scripts/state/utility.ts
Issue https://github.com/vanilla/vanilla/issues/7910
Deprecation and removal of the old utility methods will come in a followup PR. It will a bit hairier to untangle the mention actions for Rich Editor, so that should have its own PR.
Initial implementation using these https://github.com/vanilla/knowledge/pull/205
> Implement new redux base classes

- applications/dashboard/models/class.assetmodel.php
- library/core/class.controller.php
In pursuit of https://github.com/vanilla/knowledge/issues/197
Refactors the generation of a script URL for a given asset by moving it to `AssetModel:: getJSLocalePath()` so it can be used outside of a `Gdn_Controller`.
Functionality should be unchanged.
> Add asset model method for getting JS locale script

- applications/vanilla/controllers/class.moderationcontroller.php
- applications/vanilla/models/class.categorymodel.php
This tricky fix should temporary disable cascade cache update of CategoryModel when **confirmdiscussionmoves** action of ModerationController and reset Category cache.
This should increase performance and decrease memory usage on this action.
Any next incoming request should get fresh data and reinitialize CategoryModel cache keys and values 
Relates to #7843 
Fixes #7105
> Bypass cascade cache update when move discussion

- applications/dashboard/views/dba/job.php
Closes https://github.com/vanilla/vanilla/issues/7909
The information you need as to why this was modified is in the issue. Checkboxes on the dba/counts page are now all unchecked by default.
> Make dba/counts options opt-in instead of opt-out

- plugins/editor/class.editor.plugin.php
- plugins/editor/js/editor.js
The problem
---
Although our code was previously looking for a "file that already existed" when uploading a new file through the editor we never accounted for that error when dealing with the possible error messages, resulting in displaying a pop up error message "undefined". This condition is based on the filename.
You can see what I'm explaining here:
https://github.com/vanilla/vanilla/blob/master/plugins/editor/js/editor.js#L1055
We check if the 3 conditions are met otherwise we go into the else statement but we never account for the possibility of fileAlreadyExists being true while creating the error message.
The fix
---
I basically only added the message for the "file already existing" error, but, I did refactored a little bit how we build the error message. Instead of having …
> Advanced editor: Fix error message handling when uploading a duplicated file

- tests/APIv0/Controllers/ModerationControllerTest.php
- tests/travis/templates/vanilla/cgi-bin/saveconfig.php
1. Source and Destination category are brand new **Lvl1** (root).
Discussion is **new and has no comments.**
Initial Category set to Source
Discussion moved to Destination category.
**_Note:_** **Lvl2** skipped to keep it empty but to check aggregated fields to be updated correctly
Source and Destination category are brand new **Lvl3-4-5-6-7**.
Discussion is new and has no comments.
Discussion moved to Destination category same level.
2. Source categories are **existing** **Lvl1-3-4-5** destination categories from previous step.
Destination category is brand **new** **Lvl3**.
Discussions are **existing** created on previous step.
4 Discussions from 4 **different Source** categories are moved to the **same Destination** category.
3. Source category is **existing Lvl3** category created on …
> Add tests for moving posts with the moderation controller

- library/Garden/TwigTrait.php
- switch config 'Debug' true/false 
- add `{{ dump() }}` section to your twig template
As a result we should be able depending on Debug mode to see or not to see the dump of variables passed to the twig template 
Fixes #7934
> Enable Twig debug extension when Garden debug mode is true

- applications/dashboard/models/class.banmodel.php
closes #7954 
Details of the issue in the referenced ticket.
- IP ban rules are applied to users when the rule is created
- Add an ip ban rule
- try to login with a non-admin user
> Fix IP ban field escaping

- library/src/scripts/components/frame/FrameHeader.tsx
- library/src/scripts/components/modal/Modal.tsx
- library/src/scripts/components/modal/ModalConfirm.tsx
- library/src/scripts/components/modal/ModalLoader.tsx
I noticed there were a few accessibility issues with the modal component:
The `aria-hidden` was being added to the "app", but not the page. I.E. it wasn't including the header and footer in there. (requires: https://github.com/vanilla/knowledge/pull/259)
We also enabled scrolling no matter what when we closed a modal. This is incorrect as there could be another modal underneath. I've added a static "stack" of modals to the Modal component so we can keep track of where we are. Now we only remove the `aria-hidden` and enable scrolling only if we're removing the last modal in the stack.
I've also fixed an issue with the labels/description. The description is optional. If we use a heading element to describe the modal, there's no need for a label, but if we don't have one, we must add a …
> Fix accessibility issues with modals regarding aria-hidden element and body scroll

- library/Vanilla/AliasLoader.php
- library/Vanilla/Web/Assets/LegacyAssetModel.php
- library/core/class.thememanager.php
Issue: https://github.com/vanilla/vanilla/issues/7942
This PR does the initial moving of the `AssetModel` into core in preparation for a larger refactoring/update. The followup steps are outlined in https://github.com/vanilla/vanilla/issues/7942.
This PR renames the class `AssetModel` ->`Vanilla\Web\Assets\LegacyAssetModel`.
I opted for this name because it is my intention to pull parent classes out of it, and try and to not update all of the existing usages in the Vanilla proactively.
I've added an alias to the old name. This should be apparent because everything still works even though __no__ usages have been changed as of this PR.
This class has no special rules in our container or factory so didn't need any updates there.
This class _does_ extend Gdn_Pluggable so I've manually set the …
> Rename AssetModel and add aliases

- applications/dashboard/views/settings/themeoptions.php
Closes #7900 
This view has no hooks, the new core theme [Keystone](https://github.com/vanilla/themes/tree/feature/keystone) depends on this event to add more options
> Add event in theme options view to assist with customizing the page

- applications/dashboard/library/class.emailtemplate.php
- library/Vanilla/Web/Assets/LegacyAssetModel.php
- library/core/class.controller.php
- plugins/editor/class.editor.plugin.php
- plugins/swagger-ui/SwaggerUIPlugin.php
Issue: #7942
Followup of: https://github.com/vanilla/vanilla/pull/7943
Updates usages in this repo to the new name. This PR does not change functionality. An alias already exists, but it is simply housekeeping.
> Rename AssetModel usages to Vanilla\Web\Assets\LegacyAssetModel

- library/src/scripts/dom.ts
- package.json
- yarn.lock
This PR adds a `:focus-visible` polyfill. https://github.com/WICG/focus-visible
This adds a class fallback for the `:focus-visible`  CSS pseudo-selector, for browsers that don't support. Currently only Firefox has native support, but Chrome has it behind a flag and Safari is considering it for their upcoming release.
This allows us to apply big bold focus styles for keyboard navigating users, without cluttering up the UI for users navigating with a mouse or pointing device.
I've added this to `@library/dom` instead of our main polyfill feature because the main polyfill feature is meant to be targeting non-evergreen browsers (it's all or nothing). I don't want chrome/safari users receiving our full promise/async/await/generator polyfills so I've not including this in that criteria.
Once …
> Add focus visible polyfill

- build/package-include.txt
We're currently including the entire contents of `conf/` in Phing builds. This resulted in the accidental release of confidential information when the localhost contents of my config.php went live in a release (I recently changed my localhost setup to install directly out of my git repo for test running). We should whitelist exactly what we expect in the build from that folder to prevent future mishaps.
> Whitelist Phing includes in conf folder

- CONTRIBUTING.md
Broke when we moved to CLA Assistant last year.
> Fix contributors' agreement link in docs

- library/src/scss/components/_checkboxAndRadioButton.scss
- library/src/scss/components/_suggestedTextInput.scss
The clear button in the search box was misaligned. Affects KB only.
> Fixed alignment for clear icon in search box

- applications/dashboard/settings/class.hooks.php
- library/core/class.auth.php
Issue: https://github.com/vanilla/vanilla/issues/7950
After talking a little with both Ryan and Todd, the goal here was to trigger the token based authentication at the same "time" than standard auth to prevent different behaviours depending on your auth method as explained in the issue linked above. After taking both of your inputs into consideration this is what I came up with.
We add an event in the startAuthenticator method of the Auth class. We then change on what even the checkAccessToken method of the dashboard hooks is being called. Before `gdn_dispatcher_appStartup_handler` ,now `gdn_auth_startAuthenticator_handler`.
I have tested the changes in this PR and the API now works as expected. Let me know what you guys  think @initvector @tburry.
There is also a small casening fix in …
> Fix token & standard authentication not happening at same time during request

- js/embed.js
**The Problem**:
When embedding comments in an articling site or blog the embedded document can be cached by browsers. This means that a user who was not logged-in will be served the same embedded document after he logs in, making it impossible to add comments.
**The Fix**:
In the embed.js file that generates the iframe and injects the URL into it, add a time stamp to the URL.
**Test**:
I found that Firefox has the most aggressive browser caching. Create an embed comments page. 
- Before checking out this fix, visit the embedded comments page not logged in. 
- Click on the "Comment as..." button to log in.
- When you come back you will still see the "Comment as.." button.
- Checkout this fix and repeat the above steps. You will be see the message "You are logged in as.." next to the …
> Fix users not appearing logged-in in embedded comments by breaking the cache.

- applications/dashboard/settings/structure.php
This PR will remove Garden.AllowJSONP form the config on utility/update.
Related [#410](https://github.com/vanilla/vanilla-patches/issues/410)
> Remove Garden.AllowJSONP from config

- composer.lock
Minor and patch versions of Composer dependencies are updated here. This is mostly done to get Garden Schema v1.10, upgraded from 1.9, but other minor package updates are coming along for the ride. We're grabbing the latest minor version of Garden Schema v1, so we can utilize some of its new numeric validators. These validators will use schema configs that are already in place on various API endpoints. Now, "maximum" and "minimum" will be enforced on integer/numeric fields that define them, like the "limit" parameter on some API v2 endpoints.
> Fix limit parameter not being properly validated on API endpoints

- applications/dashboard/models/DraftModel.php
- applications/dashboard/settings/structure.php
- applications/dashboard/src/scripts/@types/api/draft.ts
- library/Vanilla/Database/Operation/JsonFieldProcessor.php
- library/Vanilla/Models/DraftModel.php
- library/Vanilla/Models/Model.php
- tests/Library/Vanilla/Database/JsonFieldProcessorTest.php
- tests/fixtures/src/BasicPipelineModel.php
Vanilla's [drafts API v2 resource](https://docs.vanillaforums.com/help/apiv2/swagger/#/Drafts/get_drafts) uses a generic format, but performs request translations to map fields to the existing, Vanilla-specific (i.e. discussions and comments) drafts table. The next step in moving towards revising drafts is introduced here: adding a new table for truly generic drafts and a model for managing them. The new database table is based on the API schema, which itself is based off #5535 (and its comments).
1. Add the new drafts table. Drafts are being overhauled, slowly, one step at a time. The new drafts table will need to exist alongside the existing Vanilla drafts table, until the next phase of refactoring sees everything moving to the new table structure.
1. Add `Vanilla\Models\DraftModel` to …
> Add database support for generic drafts

- applications/dashboard/controllers/class.profilecontroller.php
**Issue**
Currently if the user wish to modify a profiles email, they must re authenticate.  This in turns causes the the form to lose the original values and the email update is never saved.
**The Fix**
We check if there are original submission values in the $_POST array, if so after the user reauthenticates, the values are reapplied to the form and then saved.
**To Reproduce/ Test**
1) Go To Edit Profile
2) Change the users email
3) Click Save
4) Enter Password
5) Fields should be blank
6) Users email shouldn't be updated
7) Checkout branch and repeat steps.
Closes #8017
> Fix profile edit when user re authenticates

- applications/dashboard/controllers/api/MediaApiController.php
Extend upload media endpoint to accept different extensions different than images
Fixes: https://github.com/vanilla/knowledge/issues/303
**Note:** Does not cover "external resource" functionality
> Extend upload media endpoint to accept different upload types

- applications/dashboard/controllers/api/MediaApiController.php
- applications/vanilla/settings/class.hooks.php
- tests/APIv2/MediaTest.php
Uploads made using the media API v2 resource are automatically given a "foreign type" of "embed" and a "foreign ID" value set to the current user's ID. There is currently no way to manually update a media item's attachment status using the API.
This update introduces the media "attachment" endpoint, which allows users the ability to edit the attachment status of media items. A patch request made to /api/v2/media/1/attachment will allow you to update the "foreign type" and "foreign ID" of a media item, thus updating its attachment status.
1. Create a new upload using the media API v2 endpoint.
1. Grab the ID of the new upload.
1. Make a patch request to /api/v2/media/{id}/attachment using the `foreignType` and `foreignID` fields in the body of your request, where "{id}" is the upload ID …
> Add attachment endpoint to media API v2 resource

- library/Garden/Web/Dispatcher.php
Issue: dispatcher failed when $action is null.
Patch: Check $action type before try to detect CustomExceptionHandler
Relates to: https://github.com/vanilla/vanilla/pull/8021
> Fix custom exception handling being improperly attempted on API exceptions

- .cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
- .gitignore
- build/scripts/@types/react-docgen-typescript-webpack-plugin.d.ts
- build/scripts/configs/makeBaseConfig.ts
- build/scripts/configs/makeStoryConfig.ts
- build/tsconfig.json
- library/src/scripts/components/DateTime.story.tsx
- library/src/scripts/components/DateTime.tsx
- package.json
- tsconfig.json
- yarn.lock
Closes https://github.com/vanilla/vanilla/issues/7965
- Add's support for creating react-storybook components by creating a file with a following the pattern `*.\.story\.tsx?$`. I've added one example story with 2 knobs, `DateTime.story.tsx`.
- Adds tooling to automatically generate documentation for components that have stories if the following conditions are met:
- Class has a named export with the same name as the story.
- Component is created by using the named import `Component` or `PureComponent`. So do:
```ts
import React, { Component } from "react";
export class MyComponent extends Component {}
// If you need to have a default export
export default MyComponent;
```
These limitations are due to limitations of the storybook `info` addon which automatically generates these docs. …
> Add react storybook support

- library/src/scripts/components/navigation/QueryString.tsx
When tied to the value of an input our `<QueryString />` component could take precedence in updating before the UI. This is likely due to the adjusting the window's history object not being instant. When quickly typing into an input tied to this component it could lag immensely. This has been rectified by:
- Throttling to only occur at most once every 100ms (on the tail end).
- Placing the update in a `requestAnimationFrame()`.
> Improve performance of <QueryString /> component

- applications/dashboard/controllers/api/MediaApiController.php
- applications/vanilla/settings/class.hooks.php
- tests/APIv2/MediaTest.php
#8024 added support for attaching a media item to a resource. This update improves on that by adding an event, allowing addons to verify the resource exists and the current user has permission to attach media items to it.
This has been implemented in Vanilla. If a user did not create a post, and doesn't have the moderation permission, they shouldn't be able to attach to it. Similarly, if the post does not exist, the attach operation should also fail. Lastly, if attaching to "embed" (the default `foreignType`), a user can only attack to their own user ID.
> Improve attachment validation in media API v2 resource

- library/core/class.model.php
This adds the ability to lock resources by assigning a cache key to the process id trying to access it.  If there are competing processes for the same resources, the first one in will receive a master key that is cached.  If the cache key exists, an attempt to access the resource will fail.  Once the the process is complete, it can release the resource by calling Gdn_Model::releaseCacheLock.
Something similar was done on the categories model 
https://github.com/vanilla/vanilla/blob/9e495f412581c19aa21a2eccd7b0f4279f09b7c6/applications/vanilla/models/class.categorymodel.php#L549
This implementation will be a standard way to implement mutual exclusion across Vanilla.
> Implement Mutual exclusion functionality on the Vanilla's Base Model

- applications/dashboard/settings/structure.php
The new drafts table stores its attributes as a MySQL text field, which have a limit of approximately sixty-five thousand characters. We're changing the field type to a "medium text" field, which has a limit of approximately sixteen million characters.
> Update size limitations of generic drafts to allow larger content

- library/src/scripts/state/ReduxActions.ts
This PR updates our `ReduxActions` class to allow it recieve it's `getState()` method as a constructor argument. This is useful for unit tests.
> All getState to be injected into ReduxActions

- library/src/scripts/components/navigation/SmartLink.test.tsx
- library/src/scripts/components/navigation/SmartLink.tsx
The `SmartLink` component generates a child `NavLink` component by massaging an incoming URL. However, if the incoming URL contains a search/query string, it can be passed through as the `pathname` property. This can adversely affect routing in the application. The search/query string should be separated and passed through as the `search` property. This update performs that separation when using the `SmartLink` component.
> Fix generating NavLink in SmartLink when search string present

- library/src/scripts/components/SelectBox.tsx
- library/src/scripts/components/forms/select/ClearButton.tsx
- library/src/scripts/components/forms/select/SearchBar.tsx
- library/src/scripts/components/mebox/pieces/CompactSearch.tsx
- library/src/scripts/components/search/SearchOption.tsx
- library/src/scripts/contexts/ApiContext.tsx
- library/src/scss/_coreVariables.scss
- library/src/scss/components/_headerLogo.scss
- library/src/scss/components/_meBox.scss
- library/src/scss/components/_searchBar.scss
- library/src/scss/components/_suggestedTextInput.scss
- library/src/scss/components/_vanillaHeader.scss
- library/src/scss/components/_vanillaHeaderNav.scss
- package.json
- yarn.lock
Wired up compact search, using new API context to make it easier to plug in searches anywhere.
Various bugs:
- Fixed styles of clear button
- Fixed focus handling for compact search
- Added prop to conditionally trigger updates on any changes in searchBar
- Debouced search (This required bringing an additional debounce function besides lodash/debounce so that it would work with async functions).
> Compact Search - Wire it up and fix bugs

- .travis.yml
This PR removes `sudo: false` from the config. `sudo: false` enables travis's container based configuration. This is being sunsetted this year in favour of their docker based infrastructure (default).
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
I'm pre-emptively updating this in accordance with the information there.
Also the comment there: "# Run build in a Docker container.  Reduces time between commit and start of build." Is backwards.
> Update Travis build to use Docker-enabled virtual machines

- library/Vanilla/Formatting/Quill/BlotGroup.php
- library/Vanilla/Formatting/Quill/Blots/Embeds/ExternalBlot.php
- library/Vanilla/Formatting/Quill/Blots/NullBlot.php
Related to: https://github.com/vanilla/knowledge/issues/334
- extend ExternalBlot to have private $content with data->url  
- let BlotGroup to getContent() from ExternalBlots as well as from TextBlots
> Extend Quill ExternaBlot to have url as content 

- bootstrap.php
- library/Garden/Web/ResourceRoute.php
- tests/Library/Garden/Web/ResourceRouteTest.php
- tests/fixtures/src/ArticlesHelpController.php
- tests/fixtures/src/RootHelpController.php
Resource routes can now specify a root controller that will be looked at after specific controllers fail, allowing the root of a path to be specifically routed to.
> Allow resource routes to specify a root controller

- applications/dashboard/controllers/api/NotificationsApiController.php
- applications/dashboard/models/class.activitymodel.php
- library/Garden/Web/ResourceRoute.php
- tests/APIv2/NotificationsApiTest.php
This update introduces the notifications API v2 resource and *mostly* adheres to [the original spec](https://github.com/vanilla/roadmap/blob/master/api/notifications.md). I believe the only significant deviation was the introduction of a "limit" parameter on the index endpoint. This was due for consistency with pagination across other endpoints.
There will likely be additions or modifications to this resource as it is developed against, but I want to get the spec-complete state merged in.
Vanilla's magic API routing doesn't efficiently handle differentiating between patching a specific resource row and patching "all" resource rows (e.g. "index"). This is due to both being dispatched to a controller's `patch` method and the determination of whether or not "index" or "row" is based off …
> Add notifications API v2 resource

- .travis.yml
- package.json
- yarn.lock
Reference https://github.com/dominictarr/event-stream/issues/116
`tsc-watch` was our only dependency that showed this anywhere in the tree. They've promptly update their dependencies to no longer have this malicious dependency. https://github.com/gilamran/tsc-watch/issues/42
- Updates `tsc-watch` version.
- Updates our travis build script to run `yarn audit` now. [This command](https://yarnpkg.com/lang/en/docs/cli/audit/) is built into newer versions of yarn and detects modules and downstream dependencies with known security holes. This required updating the version of yarn we are using on travis.
As of this morning the output looked like this:
> Fix malicious event stream from tsc-watch

- applications/dashboard/src/scripts/entries/forum.tsx
- library/src/scripts/@types/api/index.ts
- library/src/scripts/@types/api/notifications.ts
- library/src/scripts/components/LinkAsButton.tsx
- library/src/scripts/components/headers/VanillaHeader.tsx
- library/src/scripts/components/headers/pieces/VanillaMobileHomeHeader.tsx
- library/src/scripts/components/mebox/MeBox.tsx
- library/src/scripts/components/mebox/pieces/CompactMeBox.tsx
- library/src/scripts/components/mebox/pieces/MeBoxDropDownItem.tsx
- library/src/scripts/components/mebox/pieces/MeBoxDropDownItemList.tsx
- library/src/scripts/components/mebox/pieces/MessagesDropDown.tsx
- library/src/scripts/components/mebox/pieces/MessagesToggle.tsx
- library/src/scripts/components/mebox/pieces/NotificationsContents.tsx
- library/src/scripts/components/mebox/pieces/NotificationsDropDown.tsx
- library/src/scripts/components/mebox/pieces/NotificationsToggle.tsx
- library/src/scripts/notifications/NotificationsActions.ts
- library/src/scripts/notifications/NotificationsModel.ts
- library/src/scss/components/_meBoxMessage.scss
This update wires up live notification data into the `MeBox` component.
1. Lots of miscellaneous small styling fixes.
1. `NotificationsActions` has been added, providing API thunks for the notifications resource.
1. `NotificationsModel` has been added, providing basic state management for notifications using the Redux store.
1. `NotificationsDropDown` has been connected to Redux to populate its content.
1. Relevant interfaces have been added for API responses from the notifications resource, local notifications state and parameters.
1. Minor tweaks to existing `MeBox` components to update their data, making it more flexible and accommodating to the data available from API responses.
> Add notifications to MeBox component

- build/scripts/Builder.ts
Closes https://github.com/vanilla/vanilla/issues/8009
As we saw from the demo today, this is backwards.
> Fix misleading build error message

- plugins/rich-editor/src/scripts/components/editor/Editor.tsx
Required to fix https://github.com/vanilla/knowledge/issues/388
Previously the editor was only re-initialized through the `key` prop, but that recreates the quill instance and throws away the user's current selection. This prop gives a more subtle approach.
> Allow editor to take a re-initialize prop

- library/src/scss/components/_vanillaHeader.scss
This overflow was causing a bug for the "compact search". KB only.
> KB: Fixed unnecessary overflow hidden

- library/Vanilla/DateFilterSchema.php
- tests/Library/Vanilla/DateFilterSchemaTest.php
- tests/Library/Vanilla/DateFilterSphinxSchemaTest.php
`DateFilterSchema` (and by extension `DateFilterSphinxSchema`) do not include the full date when performing a simple comparison on a date-only value. For example, You might expect "<=2018-01-01" to match on anything less-than-but-including January 1, 2018. What you would actually get is just less-than January 1, 2018. The comparison is exclusive.
This update tweaks the logic in `DateFilterSchema::parseSimple` to include the whole day of a date-only value when using an or-equal-to comparison.
Closes #8047
> Fix DateFilterSchema or-equal-to comparisons on date-only values not including full date

- library/src/scripts/components/forms/DateInput.tsx
Related issue: https://github.com/vanilla/knowledge/issues/345
This PR makes various improvements to the `<DateInput />`.
- Represent values as an ISO string without a time. This makes things more consistent for API endpoints that expect days without times. This component no longer specifies any times in outs datestrings.
- Better handle native input events.
- Native inputs should now be working much better on iOS and Android.
- All aspects of Android DatePicker are now working properly, including clear button.
- iOS native DatePicker works, but the clear button does not. Followup issue here https://github.com/vanilla/vanilla/issues/8083 but @tburry told me to give it a low priority.
- Make date handling more consistent by using moment to parse dates instead of the `Date` constructor. I …
> Update <DateInput /> to use ISO string without a time.

- library/src/scripts/components/dropdown/items/DropDownItemLink.tsx
- library/src/scripts/components/modal/ModalRouter.tsx
- Adds a new constant `DropDownItemLink.CSS_CLASS`.
- Adjusts types on the `ModalRouter` to use the wider type `React.ReactNode` (can be multiple types of components, null or string) as opposed to the much narrower `JSX.Element`.
> Add better types and more constants

- library/core/class.controller.php
This update adds sending the [Access-Control-Allow-Credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials) CORS header to `Gdn_Controller::setAccessControl`, which currently only sends the [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header. The new header tells the requesting browser it's okay to send the user's credentials (cookies) along with the request. Without this header, CORS-capable requests cannot be made as a signed-in user, only guests.
> Add Access-Control-Allow-Credentials to setAccessControl

- applications/dashboard/views/log/table.php
closes [#8101](https://github.com/vanilla/vanilla/issues/8101)
Browsing to dashboard/log/edits, logs type is displaying as unknown.
[table.php#L86](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/views/log/table.php#L86)
we are sending a default value for the translation function in case RecordLabel translation is not available. We do not have translation of comment/discuissopn causing the function to chose the default value of unkown
This was originally handled in [#431](https://github.com/vanilla/vanilla-patches/pull/431) to avoid an Xss.
We can htmlspecialchar the default value being sent to the translation function.
> Change Log: Fix - Default type displays as "unknown"

- library/src/scripts/components/DateTime.tsx
Closes https://github.com/vanilla/knowledge/issues/392
This PR updates the relative mode of the `<DateTime />` component to return `just now` in the passed timestamp is within 5 seconds of the current time.
> Have relative datetime return just now for very short differences

- plugins/Facebook/class.facebook.plugin.php
- plugins/GooglePlus/class.googleplus.plugin.php
- plugins/Twitter/class.twitter.plugin.php
Related [#7918](https://github.com/vanilla/vanilla/issues/7918)
Adding nofollow attribute to "Twitter,Facebook,GooglePlus" after seeing a rise in 401 and 403 errors on links for social reactions in new Google Webmaster tools reports.
> Social-Reactions: added nofollow attribute (Facebook, GooglePlus, Twitter)

- applications/vanilla/controllers/class.postcontroller.php
Closes #8111
PostController does not check if an embedded discussion's ForeignID is already posted, resulting in duplicate discussions created in Vanilla.
- Setup https://github.com/vanilla/stub-embed-providers locally
- Open 2 tabs and try to post a comment in a discussion(that has not already been posted in Vanilla) without refreshing the page in the other tab.
- 2 discussions would be created in GDN_Discussion with the same ForeignIDs
When trying to post a comment in the 2nd tab, the form does not know of the previous discussion id already posted, resulting in the creation of 2 discussions.
We are checking if there is a discussion already created based on the ForeginID, if this is the case, we add the DiscussionID to the form.
> Fix: Embed Comments - PostController not checking for duplicate discussion ForeignID

- tests/travis/diff-standards.sh
The current PHP_CodeSniffer diff scan in Vanilla's Travis build implements folding its results in the build log. If no issues are detected, this isn't a big deal. However, if issues *are* detected, they can be a little tough to find in the log, because they'll likely be collapsed by default. This update shuffles around the start and end of the folding points to ensure the PHP_CodeSniffer status is always visible, while still collapsing the verbose setup steps that made folding necessary in the first place.
See it in action here: [Job #1018.1 on Travis](https://travis-ci.com/vanilla/vanilla/jobs/165615076)
> Fix collapsing PHP_CodeSniffer scan results in build if issues detected

- library/src/scripts/components/forms/select/SearchBar.tsx
- library/src/scripts/components/navigation/QueryString.tsx
- library/src/scripts/components/navigation/SmartLink.tsx
- library/src/scripts/components/search/SearchOption.tsx
- library/src/scss/components/_suggestedTextInput.scss
This PR is required for https://github.com/vanilla/knowledge/pull/461/files
- Have search autocomplete items jump directly to their URL when clicked.
- Updates the `<QueryString/>` component to only reflect non-null, non-default values in the querystring. This results in some much shorter/cleaner query strings, and resolves some issues when when not properly initializing null values when loading from the query string.
- No longer disables search bar while loading results. https://github.com/vanilla/knowledge/issues/414
> Make search autocomplete items links, improve querystring component, fix search bar clickability

- library/src/scripts/components/siteNav/SiteNav.tsx
- library/src/scripts/components/siteNav/SiteNavNode.tsx
- library/src/scripts/utils/Hoverable.tsx
Adds a new component `<Hoverable />` which triggers a callback after a certain duration of mouseover.
An example usage has been provided in the class doc and the first implementation has been added on the `SiteNav` component. Nothing in this PR currently uses that component but a function implementation can be found here https://github.com/vanilla/knowledge/pull/463
> Add Hoverable component & hover support to navigation tree

- library/Vanilla/Formatting/Quill/Blots/Lines/CodeLineTerminatorBlot.php
- library/Vanilla/Formatting/Quill/Formats/AbstractFormat.php
- library/Vanilla/Formatting/Quill/Formats/Code.php
- plugins/rich-editor/src/scripts/__tests__/OpUtils.ts
- plugins/rich-editor/src/scripts/components/toolbars/pieces/InlineToolbarMenuItems.tsx
- plugins/rich-editor/src/scripts/components/toolbars/pieces/ParagraphToolbarMenuItems.tsx
- plugins/rich-editor/src/scripts/quill/Formatter.test.ts
- plugins/rich-editor/src/scripts/quill/KeyboardBindings.test.ts
- plugins/rich-editor/src/scripts/quill/KeyboardBindings.ts
- plugins/rich-editor/src/scripts/quill/blots/blocks/CodeBlockBlot.ts
- plugins/rich-editor/src/scripts/quill/blots/inline/CodeBlot.ts
- tests/fixtures/editor-rendering/codeBlock/input.json
- tests/fixtures/editor-rendering/codeBlock/output.html
- tests/fixtures/editor-rendering/inline-formatting/input.json
- tests/fixtures/editor-rendering/inline-formatting/output.html
Closes #7746
Additionally closes a recently noticed issues (that doesn't seem to have an issue filed) where if a code block was the last thing pasted, the editor could get into a weird undefined state. This will also simplify the implementation of https://github.com/vanilla/vanilla/issues/6612 greatly.
This PR fixes the pasting of code blocks and inline code into the editor. To test just copy paste a large document such as https://docs.vanillaforums.com/help/embedding into the editor and notice how the code blocks are pasted.
By reverting some our changes to the code-block &  code elements. Quill's clipboard module [has a laundry list of exceptions](https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L282) for code blocks and we were bypassing them all because it expects …
> Fix pasting of code into the rich editor

- js/flyouts.js
- js/global.js
- library/core/class.controller.php
Required for/blocking https://github.com/vanilla/themes/issues/253
Our latest iteration of flyouts is done in react and switches between rendering the flyout as a dropdown on desktop and a modal on mobile. There were some really nasty javascript/stylesheet hacks to make mobile/responsive flyouts possible in the various client themes we've done in the past 2 years. 
The goal of this PR is to:
- Allow a new base theme to have nice responsive flyouts.
- Not break compatibility with any flyouts in our forum.
- Not break compatibility with any existing themes, including the numerous responsive ones that are unsetting/recreating the flyout event listeners themselves.
make it possible for these to be removed for the new base theme.
- Adds a feature flag `NewFlyouts`. I was debating calling this …
> Refactor legacy flyouts

- build/scripts/Builder.ts
- build/scripts/configs/makeBaseConfig.ts
- build/scripts/configs/makeProdConfig.ts
- build/scripts/options.ts
- library/setup/ComposerHelper.php
Closes https://github.com/vanilla/vanilla/issues/8133
- Adds a new option/environmental variable check, `VANILLA_BUILD_LOW_MEMORY` and `--low-memory`. The old environmental variable `VANILLA_BUILD_DISABLE_CODE_VALIDATION` triggers this flag as well to ease the migration. See inf change here https://github.com/vanilla/vanillainfrastructure/pull/183.
- When this flag is enabled, do the following:
- Run builds sequentially instead of using webpack's multi-compiler. (Can reduce required memory by  up to 4x in my tests, and likely more as we add more "parallel" builds)
- Disable the `WebpackBar` plugin when the flag is enabled. This provides a progress bar for the completion time of the build. Removed ~100mb of peak usage (20% of our cap) in my profiling.
- Make a few other speed/memory …
> Reduce build memory usage with --low-memory flag

- library/core/class.format.php
Closes https://github.com/vanilla/vanilla/issues/7796
All mentions will now use the `atMention` CSS class, which is what is currently used by Rich Editor.
> Add CSS class for user mentions

- package.json
- tsconfig.json
- yarn.lock
Add [typescript-tslint-plugin](https://github.com/Microsoft/typescript-tslint-plugin), a microsoft typescript plugin, to enable better IDE support for some of our TSLint rules, such as `no-floating-promises`.
> Add typescript-tslint-plugin

- applications/vanilla/controllers/class.vanillasettingscontroller.php
- applications/vanilla/models/class.categorymodel.php
These parameters were removed some time ago, but the doc block was never updated. I've additionally removed the 1 instance where a parameter was still being passed.
Related https://github.com/vanilla/vanilla/issues/3848
> Fix CategoryModel::getAll references to nonexistent parameters

- applications/dashboard/models/class.usermodel.php
- applications/vanilla/models/class.discussionmodel.php
- library/core/class.session.php
Closes https://github.com/vanilla/vanilla/issues/3456
- When calling `Discussion::getByUser` with the guest or no user ID we would set use the userID of the user whose profile was being viewed (`empty(0) = empty(null) = false`). This was clearly incorrect. I've updated this to initialize the default to be the guest user ID.
- Our calculations for unread calculations are stupidly complex. Rather than dive into the nastiness of it (with no tests mind you) I've opted to just set the `Read` status to be `false` for guest users for all discussions.
- I've added a constant for the guest user ID and used it in a couple of places. I'm quite surprised that we didn't have one.
> Fix unread status on discussions for guests

- library/database/class.database.php
In some weird case it's possible that vanilla could be hit with no proper configuration. When that's the case we should throw a relevant error message instead of "masking the error".
This is especially relevant since we added type hinting on method where we expect Gdn_SQLDriver.
We get the following error message:
```
Uncaught TypeError: Argument 1 passed to CategoryCollection::__construct() 
must be an instance of Gdn_SQLDriver, instance of stdClass given...
```
and it is quite confusing.
I did a fresh install with no problems and the `testAltInstall()` test works no problems.
I'd just like some context about https://github.com/vanilla/vanilla/commit/8d02cbd1d432f9e72c468686bf225388b4847f6d before determining if this fix is "ok" or if it will break some things I am unaware of.
> Throw relevant message when SQLDriver cannot be instantiated

- tests/Library/Core/IpEncodeDecodeTest.php
Related [#7928](https://github.com/vanilla/vanilla/pull/7928)
Extending TestCase class for the referenced UnitTest instead of "SharedBootstrapTestCase" which is not required for this particular unit test.
> Fix IpEncodeDecodeTest including unnecessary bootstrapping

- plugins/rich-editor/src/scripts/entries/forum.ts
Closes https://github.com/vanilla/internal/issues/1705
This PR fixes the mounting of the editor anytime new HTML is added to the page. We were handling the specific event of a comment edit form being added to the page but there are many other places that might expect the editor to be mounted, see the linked issue.
After the creation of the editor we added 1 common event to handle all of these scenarios including comment edit boxes, so I've removed our specific handler and just used the `onContent()` handler form `@library/application`.
I also added some protected from duplicated mounting by settings a JS class once mounting has started.
> Fix mounting rich editor on any content load events

- applications/vanilla/settings/class.hooks.php
**Issue**
On the profile page the discussion and comment tabs for newly created users display a blank bar because the user doesn't have any posted discussions or comments.  This is because the the default value for CountDiscussions and CountComments is NULL in the db.
**To Reproduce:**
1) Create New User
2) Go to the users Profile Page
3) Discussion\Comment tab should be display weird bar
**Solution:**
When building the Discussion and Comment Tabs validate the counts aren't NULL or 0, if they are don't display the count.
Closes Vanilla/Support#116
> Profile - display discussion and comment count when count greater than 0

- bootstrap.php
- library/Vanilla/Contracts/Web/LegacyViewHandlerInterface.php
- library/Vanilla/Web/LegacyTwigViewHandler.php
- library/core/class.smarty.php
Blocking https://github.com/vanilla/knowledge/issues/487
While working on some new dashboard pages it became apparent that we were going to want support for twig in our old controllers as well.
This PR:
- Adds an interface to for our legacy ViewHandlers (Gdn_Smarty) was the only implementation.
- Adds a new view handler using the `Garden\TwigTrait` that supports rendering twig templates.
- Adds a couple of utility methods to our twig instance (translation and url building).
> Add twig support to the existing Gdn_Controller view infrastructure

- library/core/class.format.php
**Issue:**
When _Garden.Format.WarnLeaving_ is enabled and posted links that contained '&' characters in the query string, the link in the leaving page is double encoded and will not bring the user to the proper address.
**Solution:**
If the link is valid html it should be decoded before the link is urlencoded.
**To Test:**
1) Enable _Garden.Format.WarnLeaving_
2) Create a post with the following link
https://glumobile.helpshift.com/a/kim-kardashian-hollywood/?p=web&s=transferring-your-game-to-a-new-device&f=how-can-i-transfer-my-game-from-an-ios-device-to-an-android-device-or-from-an-android-device-to-an-ios-device&l=en
3) Click on link, it will bring you to https://glumobile.helpshift.com and won't resolve the query string
4) Checkout branch and repeat steps.
Closes Vanilla/Support#118
> Fix Leaving page links that are double encoded

- library/Vanilla/Utility/ModelUtils.php
- tests/Library/Vanilla/Utility/ModelUtilsTest.php
This update adds basic support for converting a Garden Schema exception object into its `Gdn_Validation` equivalent. This allows API controllers to be used within legacy controllers and models, where `Gdn_Validation` is still heavily used and expected to report relevant messaging. A Garden Schema validation exception can be caught by these legacy classes, converted to a `Gdn_Validation` object and then handled with existing validation capabilities (e.g. displaying relevant errors on a form).
> Add support for converting Garden Schema exceptions to Gdn_Validation

- .travis.yml
Closes https://github.com/vanilla/vanilla/issues/6485
Closes https://github.com/vanilla/vanilla/issues/8144
I've added a PHP `7.3` job which only runs on the daily cron jobs. Once we've deployed our own infrastructure with `7.3`, we can make the `7.3` build the one that runs every pull request and move 7.2 onto the cron job.
I've put the build on the xenial ubuntu 16.04 distribution. This necessitated a couple changes outlined in [travis's xenial documentation](https://docs.travis-ci.com/user/reference/xenial/).
- Manually enable the MySQL service.
- Manually add the Google Chrome apt repository.
**Other noteworthy changes**
- The MySQL is version 5.7, which has strict mode enabled by default
> Update travis build config to xenial and add PHP 7.3 job

- library/Vanilla/Formatting/Quill/Parser.php
- tests/Library/Vanilla/Formatting/Quill/ParserTest.php
Closes https://github.com/vanilla/vanilla/issues/8192
The issue has a pretty good overview of the reason for this change. I've implemented it in the parser, by stripping the trailing newlines before we split them up. I've added a test case as well.
> Trim trailing whitespace from rich editor contents

- applications/dashboard/controllers/api/RolesApiController.php
- applications/vanilla/models/class.categorymodel.php
- tests/APIv2/RolesTest.php
**Issue:**
When the saving custom category permissions by role via the api endpoint, it overwrites the custom permissions set on the category.
**Solution:**
Send a flag whether to overwrite all the category permissions in Category::Save.  Unit test to make sure a call to /roles/{id)/permissions doesn't overwrite other roles permissions.
**To Test:**
1)  Create category with custom permissions
2) Create 2 roles and give them different permissions.
3) send a call to /api/v2/roles/35/permissions to modify a roles permissions.  
4) the other roles permissions should have disappeared.
closes vanilla/support#111
> API v2 Roles: Fix permissions updates overwriting all saved permissions for a category

- library/core/class.format.php
The documented type for this method was      `* @param string|array $body The string or array body content of the post.` and it got typed as just a string.
This would cause crashes where rich quotes were used, so I've resolved it by restoring the previous less strict body type, and doing the string conversion before passing it along to the stricter `Format::renderQuote(string $body)`.
> Fix over strict typing on Gdn_Format::quoteEmbed

- applications/dashboard/controllers/class.setupcontroller.php
This PR should fix https://github.com/vanilla/vanilla/issues/6945
By now only two of five required PHP extensions have been taken care of during setup. This PR defines an array of required extensions and loops through this array to check for the modules status. If a module is not enabled, an error is added to the form.
> Verify required PHP extensions are available during setup

- plugins/rich-editor/src/scripts/quill/FocusModule.ts
Closes https://github.com/vanilla/vanilla/issues/7686
Most notably this affected the signature page.
The `EmbedFocusModule` requires some form container to mount itself, which in legacy mode needs to be provided by the forum's HTML markup. Some lesser used forms used `FormTitleWrapper` instead of `FormWrapper` so I've added support for it.
- Enable the signature plugin and set rich editor as the default formatter.
- Sign in
- Navigate to `/profile/edit/signatures`
- The editor will fail to load without this PR.
> Fix mounting of editor in forum with FormTitleWrapper

- library/database/class.sqldriver.php
Throw a deprecation warning when using Gdn_SQLDriver::whereNotIn with empty arrays
You may want to use `Gdn_SQLDriver::whereNotIn` in a chained manner like this:
```php
$result = Gdn::sql()
->from('User')
->whereNotIn('UserID', $excludeUserIDs)
->get();
```
However, this will never return anything, if `$excludeUserIDs` is empty, because of a logic error in `Gdn_SQLDriver::_whereIn`. **Even though you don't want to exclude anything, nothing will be returned.**
Note that this is a bug, not a matter of preference: The function does exactly the opposite of what the name implies in that case.
Thus, a check like this is always necessary when using `Gdn_SQLDriver::whereNotIn`, obstructing fluent use:
```php
$sql = Gdn::sql()
->from('User');
if (!empty($excludeUserIDs)) { …
```
> Throw a deprecation warning when using Gdn_SQLDriver::whereNotIn with empty arrays

- applications/vanilla/controllers/class.postcontroller.php
- applications/vanilla/models/class.discussionmodel.php
Safe alternative to #7717 
Using htmlspecialchars instead of Gdn_format::text() has several advantages:
- You can talk about HTML elements in discussion titles, because tags are encoded, not stripped, fixes #3474
- Encoded output can be fully decoded, fixing the `&amp;` bug described in my previous PR
- It does not preserve line breaks like Gdn_format::text(); does with default parameters, fixes #5185
To see the difference test what happens to a discussion title like this:
<WOW!> This is <br> a title & it contains an ampersand sign.
> Fix inability to reference HTML tags in discussion titles

- applications/dashboard/models/class.activitymodel.php
https://github.com/vanilla/vanilla/issues/7592
We simply weren't doing any formatting before sending emails. This looked ok for text and HTML formats which would render fine in emails, but this also affected rich, bbcode, and markdown which would send along unformatted text to the emails.
> Fix emails not being formatted for Rich, BBCode, Markdown

- library/core/class.dispatcher.php
https://github.com/vanilla/vanilla/issues/8244 is related, but this PR does not resolve the entire issue. It only affects 1 possible situation.
This PR whitelists the locales API while private communities is enabled. This can resolve an issue where the API (requested as a JS file) gets redirected to signin, which is not valid JS and crashes the pages JS.
> Add translations api to private community block exceptions

- library/core/class.format.php
Removes `Gdn_Format::arrayAsAttributes()`. It was deprecated in 2016 and I couldn't find usages in any code in the `vanilla` or `vanillaforums` github organizations.
I can add a line to the open source release notes once this has merged indicating this function has been removed.
> Remove deprecated Gdn_Format::arrayAsAttributes method

- library/core/class.dispatcher.php
Backporting [#8245](https://github.com/vanilla/vanilla/pull/8245)
> Backport: Add translations api to private community block exceptions(2.8.dev.6)

- library/core/class.format.php
This bespoke fallback BBCode parser was vanilla's original BBCode parsing before https://github.com/vanilla/vanilla/pull/3572. Previously that parser using nbbc was it's own plugin.
Since that PR we have had a proper BBCode parser registered in the factory/container in all installations so this fallback path was not used.
[Sometimes we override it in the container](https://github.com/search?q=org%3Avanilla+BBCodeFormatter&type=Code) but it is never removed in first party code.
This PR removes the bespoke formatter and only allows the formatter to be pulled from the container.
_Note:_ I'd recommend viewing the diff with whitespace disabled.
> Delete BBCode fallback parser

- library/src/scripts/state/ReduxActions.ts
- package.json
- yarn.lock
- Adds 2 new redux dependencies. `typescript-fsa` & `typescript-fsa-reducers`. These 2 packages allow simpler and safer declaration of actions and reducers. 
- Adds a new utility function `bindThunkAction` and accompanying types.
Here's an example fo what some actions and reducers look like with these new utilities.
```ts
// Actions
const dispatch = getDispatchFromSomeWhere(); // This is normally provided by react-redux
const actionCreator = actionCreatorFactory("@@knowledge-base");
const GET_ACS = actionCreator.async<undefined, IKnowledgeBase[], IApiError>("GET_ALL");
function getAll = () => {
const thunk = bindThunkAction(KnowledgeBaseActions.GET_ACS, async () => {
const response = await this.api.get("/knowledge-bases");
return response.data;
})();
return this.dispatch(thunk);
};
// …
```
> Add some additional redux utilities

- build/package-include.txt
Fixes file leaks in our distro build:
Awaiting feedback in https://open.vanillaforums.com/discussion/36771/security-update-vanilla-2-6-4#latest
> Update Phing build with more exclusions

- applications/vanilla/models/class.commentmodel.php
closes [#141](https://github.com/vanilla/support/issues/141)
In Table Layout, when a comment is deleted from a discussion, discussion's most recent was not getting updated properly when the last comment in a discussion was deleted.
[class.commentmodel.php#L1437](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.commentmodel.php#L1437) would always be true even if we have 
In that case, [class.commentmodel.php#L1461](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.commentmodel.php#L1461) would never evaluate and LastCommentUserID would never get updated causing 'Most Recent' to still display the username of the deleted comment.
Also, the update statement in [class.commentmodel.php#L1468](https://github.com/vanilla/vanilla/blob/ …
> Fix discussion 'most recent' not updating username when deleting last comment in a discussion

- library/Vanilla/Formatting/Formats/RichFormat.php
- resources/views/userContentError.twig
We have a catch all view render if a rich post fails to render properly.
The view path for this view was misconfiguring causing a fatal error. This can be seen easily in the following post.
https://open.vanillaforums.com/discussion/20286/github-1364-allow-users-to-delete-their-own-posts
This PR
- Fixes the view path
- Fixes the view content to use proper variables.
- Adds a warning if when the error is encountered.
> Fix twig view for rendering when rich editor fails to load.

- library/src/scripts/simplePager/SimplePager.tsx
- library/src/scripts/simplePager/SimplePagerModel.ts
- library/src/scss/components/_simplePager.scss
This update introduces the `SimplePager` frontend component, as well as `SimplePagerModel` for parsing data to be used with the component.
1. Add `SimplePager` component. This component will display 1-2 buttons, depending on the available pages.
1. Add `SimplePagerModel`. This model currently contains a single method, which allows parsing page parameters out of a link HTTP header for "previous" and "next" pages.
> Add frontend component for prev/next pagination

- library/src/scripts/components/navigation/QueryString.tsx
- library/src/scripts/components/radioButtonsAsTabs/RadioButtonTab.tsx
- library/src/scripts/components/radioButtonsAsTabs/RadioButtonsAsTabs.tsx
- library/src/scripts/contexts/SearchContext.tsx
- library/src/scripts/contexts/TabContext.tsx
Required for https://github.com/vanilla/knowledge/pull/605
- In most instances when using `QueryString` in a render method we don't want it render on first mount. This prevents us from reading the query string for initialization (will render and override it first). I've now made this behaviour opt-in.
- I've added options to the autocomplete interface.
- Fixes `TabContext` to work as a controlled component.
> Allow search options, improve querystring init, fix tab context init

- library/src/scss/components/_richEditorForm.scss
Fixed color for title of editor.
Closes: https://github.com/vanilla/knowledge/issues/595 
(the line issue was already fixed)
> Fixed title color in editor

- plugins/pockets/PocketsPlugin.php
https://github.com/vanilla/vanilla/commit/69abf732fbdfcd4c561df14a4bef3163be5784d9#diff-49e665719a2162db7c163395a91eda47 introduced an issue that causes pockets plugin to break `utility/update` or `utility/structure` or to turn on due to some implicit referencing of the file name.
It turns out the addon manager autoloads these now so PR just removes the reference instead of updating it.
> Fix pocket plugin implicit import reference name

- library/src/scripts/components/navigation/SmartLink.tsx
`SmartLink` renders either an anchor or a [`NavLink`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/NavLink.md), a `react-router-dom` module. `NavLink` extends [`Link`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md) (also a `react-router-dom` module), which supports a `replace` property, allowing the current history item to be replaced, instead of appending a new item for the link. This update adds support for handing this property down from `SmartLink` to `NavLink`.
> Update SmartLink to allow replacing of current history item

- library/Garden/CustomExceptionHandler.php
- library/Garden/Web/Dispatcher.php
- library/Vanilla/Models/SiteMeta.php
- library/Vanilla/Web/JsInterpop/PHPAsJsVariable.php
- library/Vanilla/Web/JsInterpop/PhpAsJsVariable.php
- library/Vanilla/Web/JsInterpop/ReduxAction.php
- library/Vanilla/Web/JsInterpop/ReduxErrorAction.php
- library/Vanilla/Web/Page.php
- library/Vanilla/Web/PageDispatchController.php
- library/Vanilla/Web/SimpleTitlePage.php
- library/src/scss/layouts/_container.scss
- resources/views/default-master.twig
- resources/views/error.twig
This PR takes what we were working on with `Vanilla\Knowledge\Controllers\PageController`, iterates on it, and brings it to core.
There are a few different concepts here that differentiate it from our previous attempts at a new controller.
- **Each page should be represented by 1 class**. This mirrors how our frontend pages are implemented. This also makes dependency injection a little bit cleaner. In our existing structure 1 controller may need to inject dependencies for 5-10 separate pages, even if they aren't always used.
- **Our backend controllers have a much more limited purpose now.**
- Rendering a simple page template
- Rendering assets and data for the frontend.
- _Sometimes_ rendering out SEO data like description, `<noscript />` views, and canonical URLs.
- Implements a fluent …
> Implement Vanilla\Web\Page and Vanilla\Web\PageDispatchController

- library/src/scripts/contexts/DeviceContext.tsx
- library/src/scripts/contexts/ScrollOffsetContext.tsx
https://github.com/vanilla/vanilla/pull/8272 brought along a couple small bugs:
This PR fixes them.
- The device size was not being properly initialized on mobile. I've updated it so that it is always initialized.
- Previously it was possible to scroll to the top of the document without the header coming back if you did it very slowly. This is not possible anymore.
> Fix some fixed vanilla header bugs

- conf/config-defaults.php
- tests/APIv2/AddonsTest.php
This set's Rich-Editor as the default editor for new vanilla installations.  The Keystone theme is set to the default theme for new vanilla installations.
Related to 
#7880
> Set Rich-Editor and Keystone theme to enabled by default

- tests/APIv2/AddonsTest.php
This test was removed on master in [#8293](https://github.com/vanilla/vanilla/pull/8293)
> button bar: remove failing test

- library/core/class.dispatcher.php
This reverts commit 66b422874c1eda4a454ba603fa737f0b55cc0fa0 from https://github.com/vanilla/vanilla/pull/8190. Is was causing some naming conflict issues as @alex-mtl predicted.
We'll come up with a better solution later. For now we are falling back to uglier URLs where this was being used. https://github.com/vanilla/knowledge/pull/656
> Revert "Add ability for all addons to create settings controllers"

- library/core/class.thememanager.php
- themes/keystone/class.keystone.themehooks.php
- themes/theme-boilerplate/class.vanillathemeboilerplate.themehooks.php
Backport of #8318
> Keystone and theme boilerplate set a feature flag that enables backwards incompatible changes in the mebox and flyouts.
> 
> This PR add the shutdown method so they remove it when they are disabled. Otherwise changing from keystone to and older theme breaks flyouts.
> 
> I had to add the shutdown hook in the theme manager as well
> [Backport 2.8] Fix disabling of keystone

- plugins/rich-editor/addon.json
Removed beta from the name and changed version to 1.0.1 for the rich-editor
> Rich Editor- Update name and version number in the addon.json

- library/core/class.thememanager.php
- themes/keystone/class.keystone.themehooks.php
- themes/theme-boilerplate/class.vanillathemeboilerplate.themehooks.php
Keystone and theme boilerplate set a feature flag that enables backwards incompatible changes in the mebox and flyouts.
This PR add the shutdown method so they remove it when they are disabled. Otherwise changing from keystone to and older theme breaks flyouts.
I had to add the shutdown hook in the theme manager as well.
> Fix disabling of keystone 

- applications/dashboard/controllers/api/UsersApiController.php
The `/api/v2/users/me` endpoint would fail with users with the `Admin` flag set to 2 (eg. `System` user). It was expecting only 1 or 0.
The error would look something like this:
```json
{
"message": "Validation Failed",
"status": 422,
"errors": [
{
"field": "isAdmin",
"code": "invalid",
"status": 422,
"message": "isAdmin is not a valid boolean."
}
]
}
```
This PR fixes that.
> Fix users/me endpoint for Admin=2 users

- applications/dashboard/settings/structure.php
It's possible for the new Rich editor's format to become the default on some sites as the mobile input format, when the editor had not been enabled. This can cause new mobile posts entered in some other  intended format to be interpreted as a rich post and fail.
This update adds a step in the dashboard's structure file to check if the mobile format is Rich and the Rich editor is disabled. If this condition is met, the format is reset to the site's desktop input formatter. This update can be executed using a request to /utility/update.
> Fix mobile input default being Rich when addon disabled

- applications/dashboard/settings/structure.php
Backport of #8335
> It's possible for the new Rich editor's format to become the default on some sites as the mobile input format, when the editor had not been enabled. This can cause new mobile posts entered in some other  intended format to be interpreted as a rich post and fail.
>
> This update adds a step in the dashboard's structure file to check if the mobile format is Rich and the Rich editor is disabled. If this condition is met, the format is reset to the site's desktop input formatter. This update can be executed using a request to /utility/update.
> Backport: Fix mobile input default being Rich when addon disabled

- conf/config-defaults.php
- tests/APIv2/AddonsTest.php
Reverting mobiletheme setting in config-default back to basic.
previous changes made with #8302
> Revert Mobiletheme default back to basic

- library/src/scripts/components/forms/select/SearchBar.tsx
- library/src/scripts/components/navigation/LinkContextProvider.tsx
- library/src/scripts/components/navigation/SmartLink.test.tsx
- library/src/scripts/components/navigation/SmartLink.tsx
The `SearchBar` component provides result suggestions while typing. Clicking on these suggestions can take you to the result. However, using keyboard navigation and hitting the enter key will submit the search form. The expected behavior is for hitting the enter key on a suggestion to navigate you to that record.
This update fixes the aforementioned issue with the following changes:
1. Add `LinkContextProvider` module. This pulls much of the link context logic from `SmartLink` into reusable components and expands on them.
1. Update `SmartLink` to utilize `LinkContextProvider`.
1. Fix the `handleOptionChange` method in `SearchBar` not distinguishing between when a suggestion had been selected or a search had been submitted.
1. Update `SearchBar` to use `LinkContext`, introduced in the …
> Fix hitting enter on autocomplete search suggestions causing form submission

- environment.php
OSS reference: https://open.vanillaforums.com/discussion/36986/moving-to-semantic-versioning-in-2019
> Add a build number to core for the first time.

- plugins/rich-editor/src/scripts/quill/KeyboardBindings.ts
Rich Editor's key bindings setup has a routine for resetting some of Quill's defaults. One of these defaults controls how tabs are handled in code blocks. Quill has two key bindings: [one for indenting in code blocks and one for outdenting in code blocks](https://github.com/quilljs/quill/blob/f74616e838a96d4269de4c59e74ff848085c734a/modules/keyboard.js#L221). Quill refers to code blocks in this rule as kebab case (e.g. code-blocks). However, Rich Editor refers to code blocks with camel case (codeBlocks) while attempting to override the bindings. This meant Rich Editor was not actually overriding the code block indent and outdent bindings.
Rich Editor's key bindings have been updated to properly override the Quill default code block indent and outdent configs, as intended.
Closes …
> Fix tabs being intercepted by code blocks when using Rich Editor

- README.md
* Update release branch info.
* Strike cloud release info (no one is going to remember to update this and it's an internal concern anyway).
* Remove LTS info as we are not committed to one today.
> Update versioning info in README

- .travis.yml
- tests/travis/audit.sh
We currently have an issue with a low severity security disclosure in our test framework blocking all pull requests. No fix has been made available but in any case a report like this should not hijack anyones sprint. It should be triaged.
As such I've updated our node dependency auditing to fail builds in the daily cron jobs. Pull requests builds will still run the audit, but will not fail the build.
> Make audit only block builds in cron jobs

- plugins/heroimage/addon.json
This solves issue https://github.com/vanilla/vanilla/issues/8339
Without this fix the author of the plugin is shown as "Array".
> Fix typo in Hero Image addon.json

- .travis.yml
Parts of our travis build only run in daily cron jobs, but right now we have no centralized place to collect these cron job reports.
This PR:
- Removes the defunct hipchat integration.
- Adds a slack integration to our `#dev-ci` room using a token encrypted with `travis encrypt` for our cron job builds.
> Add slack notifications to travis

- library/core/functions.general.php
closes [#175](https://github.com/vanilla/support/issues/175)
This bug was noticed after a recent change in [#7724](https://github.com/vanilla/vanilla/pull/7724)
**To Replicate** 
- Find a profile with a comment in their Activity
- Using an admin/mod account, flag that comment for the report. 
- The author of the comment will be sent to 'Reported Posts' with the expanded html as the title.
> Reported Posts: fix reported activity posts displaying as html

- library/src/scripts/components/siteNav/SiteNavNode.tsx
- library/src/scss/components/_siteNav.scss
Fixed bug in navigation. When the categories are toggeable and not navigable, the children must be, or you can't navigate anywhere.
Close: https://github.com/vanilla/vanilla/issues/8405
> Fixed issue in SiteNavNode where users potentially could not navigate anywhere

- applications/dashboard/controllers/class.settingscontroller.php
- library/core/class.controller.php
Closes https://github.com/vanilla/vanilla/issues/8065
Closes https://github.com/vanilla/vanilla/issues/7482
Of note to https://github.com/vanillaforums/hmd-global/issues/158
Enabling this feature flag will cause all scripts to have the `defer` attribute set. This causes them to happen after document rendering in order but before the DOMContentLoaded event. This is what we currently do for all scripts using `WebpackAssetProvider` (eg. Kb, Rich Editor, some advanced editor behaviour).
This is a feature flag disabled by default because of some difficulties with jquery (see https://stackoverflow.com/a/46814123). It could also potentially cause issues with inline content scripts required jquery to be synchronously loaded. As a result something like this can only be enabled on a case by case …
> Add a feature flag to to defer legacy scripts

- library/src/scripts/components/nextPrevious/NextPrevious.tsx
I've made a few small changes to the `<NextPrevious />` component to make it easier to work with:
- The props have been nested a little deeper so that a single item can be passed (worrying about null/undefined on less items).
- Moved render to top of the component.
- Made `accessibleTitle` a required prop and got rid of the default referencing knowledge base.
- Adjusted the hover style so it applies to individual items instead of the whole thing.
> Update the props & styles of <NextPrevious />

- tests/Library/Vanilla/OpenAPIBuilderTest.php
Recently, #8382 migrated Vanilla's OpenAPI spec from dynamic-built to static files. Part of this change introduced a test to validate the fully-merged OpenAPI spec, using the Swagger CLI command. This command requires the build be altered to perform a global yarn install, since the Swagger CLI command is provided by node. Until other repos running tests with Vanilla have their builds updated to also include the global yarn install, they should be able to avoid this test. The current preferred method is by skipping the "large" group.
This update addresses the aforementioned issue by assigning the OpenAPI validation test into the ["large" group](https://phpunit.de/manual/6.5/en/appendixes.annotations.html#appendixes.annotations.large). Repos running Vanilla's test suite and excluding the …
> Fix OpenAPI validation test running in other repos using Vanilla

- plugins/pockets/PocketsPlugin.php
Closes https://github.com/vanilla/support/issues/208
This was a side effect of the casening when moving https://github.com/vanilla/vanilla/pull/8173.
`addCssFile` is case sensitive on certain file systems so it went unnoticed. I've fixed all the casing issues I could find.
> Fix casing of pockets CSS class location

- cache/.htaccess
Vanilla's cache folder was accidentally removed with #8201. This update restores it to the state previous to that PR.
> Fix cache folder removal

- library/src/scripts/styles/buttonStyles.ts
- library/src/scripts/styles/globalStyleVars.ts
- library/src/scripts/styles/splashStyles.ts
- library/src/scripts/styles/styleHelpers.ts
- library/src/scss/layouts/_modal.scss
Blocking https://github.com/vanilla/knowledge/pull/709
Closes https://github.com/vanilla/knowledge/issues/676
This PR:
- Fixes `subComponentStyles()`. Previously this had an implicit return type of `any` which when unioned with other types would cause them to be any. As a result many of the core variable objects had a type of `any`. I alterred the return type to be `object` and now the union types work properly. As a result I had to fix a few broken types. These broken types masked by `any` were the cause of https://github.com/vanilla/knowledge/issues/676
- Added variables for `meta` text and `baseUnit`.
> Add some additional typestyle variables and clean up "any" type usage

- plugins/pockets/addon.json
closes https://github.com/vanilla/support/issues/215
registerPermissions was written as registerPermrissions causing the pockets permission not to get added to permissions table when the plugin is enabled.
> Pockets: Fix typo in pockets permissions

- applications/dashboard/settings/structure.php
- library/Vanilla/Models/ReactionOwnerModel.php
Move ownerType, reactionType and RecordType to separate table.
We need to drop GDN_reaction table and reinitialize it after since few columns where deleted and we can't delete them through utility/update. 
Relates to: #8379
> Normalize reaction Model

- library/src/scripts/components/mebox/pieces/NotificationsContents.tsx
Notifications displayed in the React `MeBox` component are sorted by date, ascending, as a side effect of the rows being keyed by their ID when stored. Iterating through the items moves through the IDs from lowest to highest, which essentially means they'll be sorted by their inserted date in ascending order. This update essentially reverses the sort into descending order, so newer notifications are displayed first.
> Fix notification sort in React MeBox components

- applications/vanilla/views/discussion/helper_functions.php
This PR would close https://github.com/vanilla/vanilla/issues/8422
Pass the DOM element id of the embedded comments (#vanilla-comments) to the sign in URL on embedded comments. This hash will be passed as part of the redirect URL through the log in workflow so that when the authenticated user will come back to the page where the embedded comments are they will be brought to the commenting form.
> Make page scroll down to embedded comments when user logs into embedded comments.

- library/src/scripts/users/Permission.tsx
- library/src/scripts/users/UsersActions.ts
Fixes https://github.com/vanilla/vanilla/issues/8471
This seems to have been broken recently. This PR fixes a typo in the `mapStateToProps()` and fixed a bug where the current user could be request more than once if multiple permission components were rendered in the same pass.
This component already has unit tests, but since the bug was outside of the component itself they weren't caught in the tests.
I'm opening an issue to add some integration tests covering rich editor rich would give full coverage to this as well some other components.
> Fix <Permission /> component

- library/core/class.form.php
Some uses of the category dropdown require the heading categories to be selectable. Closes https://github.com/vanilla/internal/issues/1827.
> Add an option in Gdn_Form::categoryDropdown() do enable headings

- applications/dashboard/js/dashboard.js
Vanilla's dashboard makes use of [iCheck](https://github.com/fronteed/icheck), a jQuery plugin for customizing checkboxes and radio buttons. Part of what the plugin does includes hijacking the native JavaScript events triggered by the controls when they're clicked or changed and re-triggering them as jQuery events. Those jQuery events cannot be easily handled by native JavaScript. Since Vanilla trying to move away from using jQuery, this isn't an ideal situation. As such, we're implementing a re-firing of these jQuery events as native JavaScript events.
> Add native JS event for iCheck change event

- library/core/class.controller.php
https://github.com/vanilla/vanilla/pull/8415 introduced a feature flag to defer all of our legacy scripts. There was a slight issue though. Previously the fact they were synchronous and the new webpack scripts were deferred allowed their JS to still be loaded before the build scripts.
This broke some the `@library/legacy` scripts (some stuff I converted so I could unit test it) that relies on the rest of those scripts to be loaded.
In this PR I've moved the webpack scripts to load after the old scripts.
_This has no practical affect unless this new feature flag is enabled, which had not been released yet._
> Fix legacy script order in GDN controller

- applications/dashboard/models/class.updatemodel.php
When that uploading an addon an _"Could not parse addon info array."_  is thrown if the addon.json isn't set to the first entry in the entries array.  The $info variable we are passing to `UpdateModel::checkAddon` is `false` if none of the conditions in the IF block are met.   `UpdateModel::checkAddon` will then throw the error because it is expecting an array.  This checks if $info is `false` and is a valid array, if it is we iterate through the foreach again.
To reproduce:
Pre-requisite : Community Repo
1 ) Enable Addons Directory Application
2) navigate to /addon and try to upload the zip file below
Closes vanilla/community#145
Related to https://open.vanillaforums.com/discussion/36924/could-not-parse-addon-info-array-posting-update-to-addon#latest
> AddonUpload - Address "Could not parse addon info array." error being thrown when addon.json exists

- js/flyouts.js
- plugins/editor/js/editor.js
Closes https://github.com/vanilla/vanilla/issues/8465
This whole legacy flyout situation is probably the biggest definition of spaghetti code that I've ever seen. I'm very glad we don't use it anymore.
Heres what I ended up doing:
- Improve the selectors of the keystone style flyout handling to close more things. Advanced Editor and core fight over settings handlers a lot, so I'm sorry if it's kind of ugly.
- A kludge for the WYSIWYG editor was covering too many selectors and causing flyouts to close and open again immediately. I narrowed the scope of that event handler.
I've manually tested various permutations of the following:
- **Themes:** Keystone, Deflector, Basic Mobile
- **Editors:** Markdown, BBCode, WYSIWYG
- Desktop & Mobile devices.
> Fix Advanced Editor flyouts on mobile with keystone

- applications/vanilla/models/class.commentmodel.php
- applications/vanilla/models/class.discussionmodel.php
- Add joinDiscussionData to DiscussionModel
- Add related call to CommentModel when 'joinDiscussion' in `getWhere()`
Relates to: https://github.com/vanilla/knowledge/issues/653
> Extend DiscussionModel to 'join' selected columns data to any array or ResultSet

- library/src/scripts/components/IndependentSearch.tsx
- library/src/scripts/components/forms/select/SearchBar.tsx
- library/src/scripts/components/splash/Splash.tsx
- library/src/scripts/styles/compactSearchStyles.ts
- library/src/scripts/styles/globalStyleVars.ts
- library/src/scripts/styles/searchBarStyles.ts
- library/src/scripts/styles/siteNavStyles.ts
This PR fixes a couple things got off spec in the current theme branch.
- Closes https://github.com/vanilla/knowledge/issues/731
- Search in the header has fixed background
- Search has correct border-radiuses when no search button is displayed.
- Splash search does not show search button on mobile.
- SiteNav links now have active and hover colors again.
> Fix theme style regressions

- applications/dashboard/controllers/api/ThemesApiController.php
- applications/dashboard/openapi/themes.yml
- library/Vanilla/Theme/ImageAsset.php
- tests/APIv2/ThemesTest.php
The themes API resource has been updated to include the site's desktop and mobile logos, if present.
1. Add `logo` and `mobileLogo` asset to themes API resource responses. These assets are only included if the site has configured them.
1. Add `ImageAsset` class to represent an image asset of a resource.
1. Add tests for verifying the proper desktop and mobile logos are returned by the API when configured on a site.
1. Update OpenAPI spec for the themes resource to include the new assets.
1. Fix location of `ThemesApiController`. This controller was previously under Vanilla. Now, it lives under Dashboard.
The original spec had "logo" and "mobileLogo" as top-level fields in the response of a theme. However, they were flagged as TBD, which I take to mean they were only there as placeholders …
> Add logo and mobileLogo to theme API resource responses

- library/src/scripts/components/headers/VanillaHeaderNav.tsx
- library/src/scripts/components/layouts/PanelLayout.tsx
- library/src/scripts/components/navigation/backLinkStyles.ts
- library/src/scripts/components/nextPrevious/NextPrevious.tsx
- library/src/scripts/styles/attachmentIconsStyles.ts
- library/src/scripts/styles/attachmentStyles.ts
- library/src/scripts/styles/bodyStyles.ts
- library/src/scripts/styles/buttonStyles.ts
- library/src/scripts/styles/checkRadioStyles.ts
- library/src/scripts/styles/compactMeBoxStyles.ts
- library/src/scripts/styles/compactSearchStyles.ts
- library/src/scripts/styles/globalStyleVars.ts
- library/src/scripts/styles/searchBarStyles.ts
- library/src/scripts/styles/shadowHelpers.ts
- library/src/scripts/styles/splashStyles.ts
- library/src/scripts/styles/styleHelpers.ts
- library/src/scripts/styles/subcommunityListStyles.ts
- library/src/scripts/styles/subcommunityTitleStyles.ts
- library/src/scripts/styles/vanillaHeaderStyles.ts
- library/src/scripts/styles/widgetStyleVars.ts
Various improvements for KB styles:
- Refactored several (but not all) instances of debugHelper with styleFactory
- Better handling of color types and transparencies
- Added body color and background options
- Renamed `getColorDependantOnLightness` in favour of `modifyColorBasedOnLightness` for clarity
- Added function `shadowOrBorderBasedOnLightness` to conditionally use a shadow or border based on color value
- Converted Slash styles and hooked up options
- Fixed style helper functions to not get errors if options don't exist in props passed
- Added get background function that checks for fallbacks and prepares image url for styles
> KB Styles - refactoring helper functions, improve color types, splash styles, background images

- js/flyouts.js
closes [#255](https://github.com/vanilla/support/issues/255)
This was causing an error when reacting in IE 11.
> Fix: Javascript error when interacting with reactions, bookmarks

- library/core/class.applicationmanager.php
Fixes #7263.
Vanilla currently returns an incorrect folder name for applications when Vanilla is run on Windows. This causes applications to not be enabled because Vanilla depends on a properly set value for elements in the EnabledApplications array in config.php.
**Actual values on Windows:**
```
$Configuration['EnabledApplications']['Conversations'] = '/applications/conversations';
$Configuration['EnabledApplications']['Vanilla'] = '/applications/vanilla';
```
**Expected values:**
```
$Configuration['EnabledApplications']['Conversations'] = 'conversations';
$Configuration['EnabledApplications']['Vanilla'] = 'vanilla';
```
The Conversations and Vanilla applications are just two examples to show how the EnabledApplications array looks like on Windows.
On Linux environments, the values are …
> Fix application folder name under Windows 

- applications/vanilla/settings/structure.php
closes [#253](https://github.com/vanilla/support/issues/253)
Details in the referenced ticket.
Score column had no index causing slow queries post deploy.
> Add index to GDN_Comment.Score

- resources/views/default-master.twig
Closes https://github.com/vanilla/knowledge/issues/681
There were a few missing meta tags in our default master twig template that was causing issues on mobile browsers.
> Fix meta tags on default master template

- plugins/rich-editor/src/scripts/quill/HistoryModule.ts
- plugins/rich-editor/src/scripts/quill/blots/embeds/ExternalEmbedBlot.ts
Embeds created in a rich post were previously difficult to remove. You could _delete_ them, but not _undo_ them. This seems to have been caused by some refactoring.
1. Fix checking for invalid key when determining if a blot is a "loaded" embed. Previously, the history module was checking for the presence of a `loaderData.loaded` property in an embed.  This property does not exist. An embed blot can be considered "loaded" if it has a populated `data` attribute. The check has been updated to reflect this.
1. Fix embed blot attempting to convert from loader to full embed when the embed's DOM node is no longer available.  When an embed is inserted, it is added in its "loading" state while the content is being fetched. If the embed is deleted before the content finishes fetching (i.e. the …
> Fix inability to remove embeds in rich posts

- library/src/scripts/styles/bodyStyles.ts
- library/src/scripts/styles/compactSearchStyles.ts
- library/src/scripts/styles/globalStyleVars.ts
- library/src/scripts/styles/shadowHelpers.ts
- library/src/scripts/styles/splashStyles.ts
- library/src/scripts/styles/styleHelpers.ts
- library/src/scripts/styles/subcommunityTitleStyles.ts
- Fixes some incorrect assertions were being made about the what properties were available that were masked by a `get` call.
- Fixes the `background` and `getBackgroundImage` utility functions so that they return the proper image.
- Fixes shadow utilities to align with mockups.
- Fixes active/focus states calculation to align with mockups using default colours.
- Fix alignment and colour of the VanillaHeader search bar "search" icon.
> Fix various style issues

- library/src/scripts/components/navigation/LinkContextProvider.tsx
- library/src/scripts/components/siteNav/SiteNav.test.tsx
- library/src/scripts/components/siteNav/SiteNav.tsx
- library/src/scripts/components/siteNav/SiteNavContext.tsx
- library/src/scripts/utility.ts
This update adds some basic tests for `SiteNav`, in addition to introducing some changes to make those tests easier to write.
1. Add test for initializing `SiteNav` with a valid active record.
1. Add test for initializing `SiteNav` with an invalid record.
1. Add test for changing the record on an existing instance of `SiteNav`.
1. Fix `SiteNav` requiring the application router. This was unnecessary.
1. Fix default configuration of `LinkContextProvider` throwing unnecessary fatal errors.
Closes #8104
> Add tests for SiteNav

- library/src/scripts/theming/ThemeProvider.tsx
- plugins/rich-editor/src/scripts/entries/forum.ts
There exists the potential for Rich Editor to "crash" when loading for a discussion or comment. This is caused by `ThemeProvider` attempting to get the store before it's been properly initialized.
This update delays attempting to grab the store in `ThemeProvider` until after it's had a chance to fully initialize. After this fix was implemented, it became apparent Rich Editor was attempting to register its reducer too late, so that was also addressed here.
Closes #8530
> Fix Rich Editor crashing on page load

- library/Vanilla/Formatting/Quill/Filterer.php
- tests/Library/Vanilla/Formatting/Quill/FiltererTest.php
Closes https://github.com/vanilla/vanilla/issues/8539
https://github.com/vanilla/vanilla/pull/8492 fixed a pretty nasty bug, but created a regression by using `sort` to ensure that we had an indexed array instead of using `array_values`.
I've fixed that and added a test case covering code blocks which were an example of what was being broken by this `sort`.
> Fix filterer regression and add test case

- plugins/VanillaInThisDiscussion/class.inthisdiscussionmodule.php
https://github.com/vanilla/vanilla/pull/8394 introduced a bug where suers
I approved the PR not realizing that these items were meant to be unique. The fix was to remove that unnecessary piece in the `GROUP BY` and use the aggregate selected value `DateLastActive` for the `ORDER BY`.
I updated the function doc block too.
> Fix duplicate users from In this discussion module

- library/src/scripts/forms/buttonStyles.ts
- library/src/scripts/navigation/CloseButton.tsx
- plugins/rich-editor/src/scripts/flyouts/pieces/Flyout.tsx
- plugins/rich-editor/src/scripts/toolbars/inlineToolbarClasses.ts
- plugins/rich-editor/src/scripts/toolbars/pieces/InlineToolbarLinkInput.tsx
- plugins/rich-editor/src/scripts/toolbars/pieces/ToolbarContainer.tsx
- plugins/rich-editor/src/scripts/toolbars/pieces/ToolbarPositioner.tsx
I noticed that the positioning of Rich Editor toolbars were not really accurate in the forum while working on another issue. It seems to have gotten a little jumbled up during the style conversion.
I've gone in and fixed (the offsets needed to be adjusted a bit) as well as some translates.
I also fixed some minor issues with icon buttons not applying properly on the forum by adding an actual typestyle class with a reset. I also removed the now unused `legacyMode` prop from `<CloseButton>`.
> Fix toolbar positioning in rich editor

- library/core/class.pluggable.php
Closes https://github.com/vanilla/vanilla/issues/7180
> Remove suppression of ArgumentCountError exceptions from Gdn_Pluggable

- applications/vanilla/controllers/api/DiscussionsApiController.php
- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/models/class.discussionmodel.php
- applications/vanilla/openapi/discussions.yml
- tests/APIv2/DiscussionsTest.php
New DiscussionsAPI endpoints:
```
PUT /discussions/{id}/canonical 
DELETE /discussions/{id}/canonical
```
Update openapi schema.
Update discussion controller  to update meta tag `canonical` with custom `canonicalUrl` when present
Relates to: #8260
> Add ability to set the canonical URL for a discussion over the API

- applications/vanilla/controllers/api/DiscussionsApiController.php
Getting a single discussion via the API does not currently allow expanding any fields. This update adds that ability. To start there is nothing to expand, but addons may make use of this field by adding options to it.
As a bonus, I fixed an issue where `lastPost.inserUserID` might not be set, but is still required by the schema. It's probably been broken in some capacity for a long time.
> Add expand parameter to discussions API get

- applications/vanilla/src/scripts/@types/api/categories.ts
- applications/vanilla/src/scripts/categories/CategorySuggestionActions.ts
- applications/vanilla/src/scripts/categories/categoriesReducer.ts
- applications/vanilla/src/scripts/entries/knowledge.tsx
- applications/vanilla/src/scripts/forms/CommunityCategoryInput.tsx
- applications/vanilla/src/scripts/redux/reducer.ts
- applications/vanilla/src/scripts/redux/state.ts
- library/src/scripts/forms/select/SelectLookup.tsx
- library/src/scripts/forms/select/SelectOne.tsx
- library/src/scripts/forms/select/overwrites.tsx
This update introduces the `CommunityCategoryInput` component.
1. Add `SelectLookup` component. This component allows a straightforward way to create a select menu with options that update as the user types. This is essentially a specialized version of `SelectOne`.
1. Fix type errors in `SelectOne`.
1. Add frontend classes for looking up community (forum) categories. This includes actions (`CategorySuggestionActions`) to perform lookups via the API based on a full or partial category name, as well as a reducer (`categoriesReducer`) to save category-related data to the state.
1. Add `CommunityCategoryInput` component. This component provides category suggestions based on user input, ultimately allowing a user to select a single specific category.
> Add CommunityCategoryInput component

- environment.php
#8571 increased Vanilla's PHP version requirement to 7.1. However, the value of `PHP_VERSION_ID` it was checking for was "71000", which would be 7.10. It should be "70100".
Per [php.net](https://www.php.net/manual/en/function.phpversion.php):
1. (`major_version` * 10000) + (`minor_version` * 100) + `release_version`
1. (7 * 1000) + (1 * 100) + 0
1. 70000 + 100 + 0
1. 70100
Guessing the build ducks this check.
> Fix PHP 7.1 version requirement

- applications/vanilla/controllers/class.discussioncontroller.php
- applications/vanilla/settings/class.hooks.php
- library/Vanilla/Message.php
The ability to set a discussion's canonical URL was recently added. There we no UI indicators that a discussion could potentially be pointing to a new resource. Those UI indicators are added here.
1. Add `Vanilla\Message` class. This is a basic class that represents a site message. It is built to follow the established convention of message classes and structure (see [class.messagecontroller.php](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/controllers/class.messagecontroller.php)).
1. Add backward-compatible display of messages when viewing a discussion. The BeforeDiscussionDisplay event is hooked into and messages are output at that point.
1. Add ability to set messages in `DiscussionController`. Messages may be added any time before rendering. When a discussion …
> Add informational message to discussion if it has a user-provided canonical URL

- plugins/rich-editor/src/scripts/editor/richEditorClasses.ts
- plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenuBar.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenusBarToggle.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/items/ParagraphMenuBarRadioGroup.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/pieces/ParagraphMenuCheckRadio.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuBarTab.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuHeadingsTabContent.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuListsTabContent.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuResetTab.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuSpecialBlockTabContent.tsx
This PR is adding keyboard shortcuts for the new paragraph menu. Note there will be another PR for the missing shortcuts.
MenuBar:
- Escape: (closes submenu if open) or closes menuBar (i.e. paragraph menu)
- Home: jump to first element
- End: jump to last element
- Arrow Right : jump to next element (wraps)
- Arrow Left: jump to last element (wraps)
- Arrow Down : opens menu and selects first item if available
- Arrow Up: closes menu
Other changes: 
- Refactored calculation for top level icons
- Keep menu's state when we close the paragraph menu. (i.e. if you were in the list tab, you'll be there again when you open the menu up again)
> New Paragraph Menu - Keyboard shortcuts

- library/Vanilla/Formatting/Quill/Blots/Lines/HeadingTerminatorBlot.php
- tests/Library/Vanilla/Formatting/Quill/ParserTest.php
- tests/fixtures/formats/rich/html/headings/input.json
- tests/fixtures/formats/rich/html/headings/output.html
Closes https://github.com/vanilla/vanilla/issues/8432
@slafleche Already wired up the new heading levels in the editor. This PR adds server rendering support for them.
> Allow headings of level 2-5 in the rich content renderer

- library/src/scripts/dom/TabHandler.ts
- plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenuBar.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/paragraphMenuBarStyles.ts
- plugins/rich-editor/src/scripts/menuBar/paragraph/pieces/ParagraphMenuCheckRadio.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuBarTab.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuListsTabContent.tsx
- plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuResetTab.tsx
All keyboard shortcuts should work now. Please read the spec here:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html
Closes: https://github.com/vanilla/vanilla/issues/8434
> Implement missing accessible keyboard short cuts for new paragraph menu.

- applications/conversations/settings/class.hooks.php
PHP is throwing a warning for an unnecessary `use` statement in Conversations' hooks.
> The use statement with non-compound name ConversationCounterProvider has no effect
It's been removed.
> Fix warning for use statement in Conversation hooks

- library/Vanilla/Formatting/Embeds/ImgurEmbed.php
closes [#249](https://github.com/vanilla/support/issues/249)
Using rich-editor, some imgur image embeds with image extensions were failing.
On imgur site, links looks something like https://i.imgur.com/1okCy50. this link embed is currently handled. 
What users are doing is 
this gives https://i.imgur.com/1okCy50.jpg which we don't handle in our embeds because of the image extension at the end
Our [ImgurEmbed.php](https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/Embeds/ImgurEmbed.php) does not handle this type of link.
Based on a feedback from RnD, we should strip those extensions.
- Using rich-editor, try to post these 2 images
- https://i.imgur.com/RuFna0O.jpg (should fail)
- https://imgur.com/gallery/mzto8oD (should work)
> Fix: imgur embeds not rendering correctly

- build/scripts/configs/makeBaseConfig.ts
- build/scripts/options.ts
The args parsing weren't properly parsing boolean values. This seems to have fallen apart when ops changed the way they passed us the arguments. They used to be passed as `--low-memory=true` now it's passed as `--low-memory`.
> Fix args parsing an enable webpack bar in low memory situations

- applications/vanilla/controllers/class.postcontroller.php
closes [#256](https://github.com/vanilla/support/issues/256)
- Create a Group
- Create a discussion inside a group and Announce it
- Check GDN_Discussion.Announce for the created discussion, it should be set to 2 instead of 1
I added a check to test when we have a discussion created inside a group, in that case I am setting Announce to 2. The reason I did this change is explained below.
After investigating this, the fix in the referenced issue would not solve the problem (running the db update to set announce to 2 would fix the problem for the currently created discussions inside groups) initially this was thought to be related to their data, which is not the case. Every time a new discussion is created inside a group, and announce is checked,GDN_Discussion.Announce would be set to 1. …
> Fix: seeing group announcements in recent discussions

- bootstrap.php
Decoding a JWT token includes validation of its "issued" and "expired" fields. If the token is decoded before its "issued" time, it isn't considered valid. This can be a problem when generating and decoding JWT tokens between servers if there is a slight difference in times between them.
The JWT library Vanilla uses is essentially a class of static methods. It contains the ability to configure the allowable variance in "issued" times in the library by way of setting the value of a static property in that class.
This update sets the "leeway" to five seconds, from zero, as part of Vanilla's bootstrapping process. Any usage of `Firebase\JWT\JWT` in the application will now allow for five seconds of difference between issued and expiration times.
> Fix JWT cookie decoding between servers with slightly offset times

- library/core/class.logger.php
Vanilla has configuration rules for its `Vanilla\Logger` instance in the bootstrap. However, this instance is not used by the `Logger` class, which creates a fresh instance of `Vanilla\Logger`. Any logging calls made through `Logger` are not using the configured copy of `Vanilla\Logger` from the container.
`Logger::getLogger` has been updated to grab the class's `Vanilla\Logger` instance from the container, which should be configured per the application's bootstrap.
> Instantiate logger from container in Logger

- library/core/class.applicationmanager.php
- library/core/class.gdn.php
- library/core/class.pluggable.php
- library/core/class.pluginmanager.php
- library/core/class.thememanager.php
This PR deprecates the following classes:
- `Gdn_ApplicationManager`
- `Gdn_ThemeManager`
- `Gdn_PluginManager`
- `Gdn_Pluggable`
Additionally, methods to fetch instances of these have deprecated. I also explicitly deprecated some pluggable methods.
**Note:** I did not use the `deprecate` call because we don't have intention of retroactively replacing all usages of these. However, we do not want new development to make use of these methods.
> Deprecate ApplicationManager, ThemeManager, PluginManager, PluginManager, Pluggable

- library/core/class.form.php
I bungled another #8448 which resulted in enabled nested/flat categories in the post discussion dropdown. I'm assigning two senior reviewers to bail me out here.
Closes vanilla/support#259
> Fix regression disabling of categories

- library/Vanilla/Formatting/Embeds/ImgurEmbed.php
closes https://github.com/vanilla/support/issues/249
Using rich-editor, some imgur image embeds with image extensions were failing.
On imgur site, links looks something like https://i.imgur.com/1okCy50. this link embed is currently handled. 
What users are doing is 
this gives https://i.imgur.com/1okCy50.jpg which we don't handle in our embeds because of the image extension at the end
Our [ImgurEmbed.php](https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/Embeds/ImgurEmbed.php) does not handle this type of link.
Based on a feedback from RnD, we should strip those extensions.
- Using rich-editor, try to post these 2 images
- https://i.imgur.com/RuFna0O.jpg (should fail)
- https://imgur.com/gallery/mzto8oD (should work)
> Fix imgur embeds

- library/Vanilla/Web/ThemedPage.php
Revert unnecessary config class dependency.
Relates to: https://github.com/vanilla/vanilla/pull/8661
> Revert unnecessary config class dependency

- plugins/rich-editor/src/scripts/quill/ClipboardModule.test.ts
- plugins/rich-editor/src/scripts/quill/blots/blocks/ListBlot.test.ts
- plugins/rich-editor/src/scripts/quill/blots/blocks/ListBlot.ts
Closes https://github.com/vanilla/vanilla/issues/8593
This PR fixes the issues specifically outlined in https://github.com/vanilla/vanilla/issues/8593 and adds unit tests for those scenarios.
_**If you encounter other list issues that are not specifically a regression from this pull request, please file a separate issue.**_
The most complicated operation occurs whens changing the paragraph format of some inner list item with children or siblings. After some discussions with @tburry We determined that for simplicity it was OK to flatten an items children and its following siblings when it changes formats as long as the user can undo the action.
See the following docblock for the implemented behaviour.
https://github.com/vanilla/vanilla/blob/347ca4dd81dfc56eaf4bf0f291445f81a31072eb/plugins/r …
> Make conversion of lists to other formats more robust

- library/src/scripts/navigation/NavLinksWithHeadings.tsx
The `NavLinksWithHeadings` component supports grouped and ungrouped content. Grouped content can have "View All" URLs, per group. The ungrouped content does not currently support a "View All" link.
`NavLinksWithHeadings` has a new property: `ungroupedViewAllUrl`. If this property is specified, a "View All" link can be displayed alongside the ungrouped content.
> Add view-all-ungrouped-url property to NavLinksWithHeadings

- library/src/scripts/messages/Message.tsx
- library/src/scripts/messages/MessageAndRefresh.tsx
- library/src/scripts/messages/MessageAndRefreshFixed.tsx
- library/src/scripts/messages/messageStyles.ts
I've extracted a more generic `<Message />` component from `<MessageAndRefresh />`. I've also tweaked the styles to make it a little more flexible. There are no current uses of this component as it was introduced this sprint.
> Extract generic <Message /> component from <MessageAndRefresh />

- plugins/googlesignin/addon.json
The link to the documentation from the dashboard doesn't take the user to the GoogleSignIn section. This PR will fix that .
> Correct the link to the docs for Google Sign in.

- applications/dashboard/modules/class.pagermodule.php
Closes https://github.com/vanilla/vanilla/issues/8629
This PR improves the accessibility of our pagination component.
- Add `role="navigation"` to the pager.
- Add `aria-label="pagination"` to describe the type of navigation.
- Add an `aria-label` to each page link to read out the purpose of the link, for example "Page [Page #]"
- Add aria-current="page" to the link that points to the current page.
- Add aria-disabled="true" to pager elements that are disabled.
- I thought this seemed like a quick enough thing so I just did it. Low priority in the review list.
- I deprecated `PagerModule::rel` even though I don't see it used anywhere because it's public.
> Make pagination more accessible

- library/src/scripts/styles/globalStyleVars.ts
- library/src/scripts/styles/textUtils.ts
CSS now has good support for controlling hyphenation. This PR includes the CSS variables as well as a helper function to apply them (with all the fallbacks we need).
Note that this PR does not yet apply these styles, since I want to get approval for the values chosen. Issue created here to apply styles: https://github.com/vanilla/knowledge/issues/807
> Add variables and helper functions for hyphenation CSS props

- library/src/scripts/bootstrap.ts
- library/src/scripts/features/search/searchBarStyles.ts
- library/src/scripts/forms/FormError.tsx
- library/src/scripts/headers/vanillaHeaderStyles.ts
- library/src/scripts/layout/components/widgetContainerStyles.ts
- library/src/scripts/layout/frame/frameStyles.ts
- library/src/scripts/styles/styleUtils.ts
Closes https://github.com/vanilla/vanilla/issues/8686
Closes https://github.com/vanilla/vanilla/issues/8687
This PR adds the ability for someone using `styleFactory` to debug their input into typestyle.
To do so just pass the imported `DEBUG_STYLES` symbol as the first param to the `style()` call.
I've used a symbol instead of a boolean or string so that it has an explicit name and it won't be confused with the first string parameter of the output name.
- I tightened up the type returned from `style()`. It's always a string. Then I fixed some broken places that were trying to use this string as a mixin.
- Fixed an issue where the debug value on the frontend wasn't being set properly in KB with hot reload enabled.
> Add the ability to debug styleFactory calls

- applications/dashboard/src/scripts/legacy/atwho.ts
- build/entries/polyfills.ts
- library/src/scripts/content/embeds/video.tsx
- library/src/scripts/content/spoilers.ts
- library/src/scripts/flyouts/FlyoutToggle.tsx
- library/src/scripts/styles/styleHelpers.ts
- tsconfig.json
After https://github.com/vanilla/vanilla/commit/5f55fd88891a0195269998aa7394c4540892b43e I believe we have some potential issues with moving usages from class components into function components.
I've enabled the `noImplicitThis` typescript flag, which throws an error if the value of `this` cannot be statically determined. I had to replace a few usages when enabling this, and fixed one big in our dropShadow helper.
> Update typescript config to handle no-implicit-this

- library/src/scripts/dom/EscapeListener.ts
- library/src/scripts/dom/FocusWatcher.ts
- library/src/scripts/flyouts/DropDown.tsx
- library/src/scripts/flyouts/FlyoutToggle.tsx
- library/src/scripts/layout/DeviceContext.tsx
- library/src/scripts/layout/deviceCheckerStyles.tsx
- plugins/rich-editor/src/scripts/editor/EditorEmbedBar.tsx
- plugins/rich-editor/src/scripts/editor/ForumEditor.tsx
- plugins/rich-editor/src/scripts/editor/richEditorClasses.ts
- plugins/rich-editor/src/scripts/flyouts/EmbedFlyout.tsx
- plugins/rich-editor/src/scripts/flyouts/EmojiFlyout.tsx
- plugins/rich-editor/src/scripts/flyouts/pieces/EmojiPicker.tsx
- plugins/rich-editor/src/scripts/flyouts/pieces/insertMediaClasses.ts
- plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenusBarToggle.tsx
Required Companion PR https://github.com/vanilla/knowledge/pull/887
Closes https://github.com/vanilla/knowledge/issues/768
I fixed the bug by refactoring the `FlyoutToggle` component. I converted use react hooks which allowed me reason about the various state interactions a lot easier. In order to facilitate this I created 2 new hooks. `useEscapeListener` and `useFocusWatcher` which assist in setting up and tearing down their associated classes within the lifecycle of a react element.
Additionally the way initial focus is set in flyouts has changed slightly. I've updated a couple of usages that were not focusing properly. Notably the rich editor emoji picker & embed menu should now properly focus their initial elements.
- I added the `DeviceChecker` to the forum and converted its styles …
> Fix various issues with Flyouts converting to Modals on mobile

- plugins/rich-editor/RichEditorPlugin.php
In rich editor has been a typo in one of the initial saveToConfig values, see [this issue](https://github.com/vanilla/vanilla/issues/8396)
Instead of fixing the typo I directly used the class constant which is used later on to set this config key. This makes it more robust and flexible than simply fixing the typo.
> Fix quote config detection in Rich Editor addon

- plugins/googlesignin/addon.json
This PR will close https://github.com/vanilla/vanilla/issues/8699
If you are testing this locally, make sure you clear your Vanilla cache.
> Fix broken link to Google Sign In settings page.

- applications/vanilla/controllers/class.categorycontroller.php
closes [#335](https://github.com/vanilla/support/issues/335)
**Issue**
When following a category, we get the error
**Fix**
Set permission name properly
> Fix permission when following a category

- plugins/googlesignin/addon.json
The recently launched Google Sign In plugin does not link correctly to its settings page in the Dashboard.
> Backport: Fix broken link to Google Sign In settings page.

- applications/dashboard/controllers/api/ThemesApiController.php
- library/Vanilla/Models/ThemeModel.php
- library/Vanilla/Theme/VariablesProviderInterface.php
The variables asset of records returned from the themes API v2 resource can now be expanded on by addons.
1. Add the `Vanilla\Theme\VariablesProviderInterface` interface. This defines the contract for addons who wish to register a theme-variables provider.
1. Add support for variable providers to `ThemeModel`. Currently, providers can only be registered and retrieved. No processing is applied through the model, since the variables asset is generated by `ThemesApiController`.
1. Add support for variable providers to `ThemesApiController`. Normalizing a theme now includes adjusting its variables asset, based on any variable providers configured in the controller's `ThemeModel`. It would be much better if this lived in the model, but it's been added to `ThemesApiController` since that's …
> Add ability for addons to extend theme variables

- library/src/scripts/layout/FlexSpacer.tsx
- library/src/scripts/splash/Splash.tsx
- library/src/scripts/splash/splashStyles.ts
- library/src/scripts/styles/styleHelpers.ts
The `Splash` component now has an `action` property, which will allow a custom button to be included when the component is rendered.
1. Add `action` property to `Splash` component. The property is referenced in the component's `render` method.
1. Fix `FlexSpacer` component including styles it did not need, which brought along `flex-grow` rules that could conflict with other styles.
1. Updated styles in `splashStyles` to accommodate the new action button area.
Relates to vanilla/knowledge#862
> Add action property to Splash component

- library/Vanilla/Web/ContentSecurityPolicy/EmbedWhitelistContentSecurityPolicyProvider.php
Update trusted domains whitelist (for content-security-policy implementation) for embed content 
Relates to: https://github.com/vanilla/knowledge/issues/898
> Update embed whitelist security policy provider to allow twitter and instagram embeds

- library/src/scripts/routing/links/LinkContextProvider.tsx
- library/src/scripts/utility/appUtils.tsx
Fix url links transformation when kb is installed under web server subfolder
Relates to: https://github.com/vanilla/knowledge/issues/761
Blocks: https://github.com/vanilla/knowledge/pull/927
> Fix url links transformation when app is installed in subfolder

- applications/vanilla/js/autosave.js
fix https://github.com/vanilla/support/issues/285
Because the content of the Rich Editor is saved into JSON objects, empty objects are frequently saved in the database since blank posts aren't considered empty. Same thing is happening when editing a discussion. Because `lastVal` is set to null in `autosave.js`, the value of the textarea is always compared to null the first time.
The `lastVal` variable in the `autosave.js` file is now set to the initial textarea value instead of null. The fix is pretty simple, but will prevent any empty and unchanged posts from being saved automatically.
> Fix post autosave when drafts are empty or untouched

- library/src/scripts/splash/Splash.tsx
- library/src/scripts/splash/splashStyles.ts
`splashStyles` now returns a `customBackground` member, which is a function used to generate a background-image style. This is used by the `Splash` component to render a custom background.
1. Add `customBackground` member to the result of `splashStyles`. This is a function that generates a background-image style.
1. Add `backgroundImage` prop to `Splash` component. If provided, this value will be used as the background image for the rendered element.
1. Fix styling inconsistencies in `splashStyles`. Thanks [Prettier](https://prettier.io).
Relates to vanilla/knowledge#936
> Add custom background image support to Splash component

- library/src/scripts/content/UserContent.tsx
- library/src/scripts/content/hashScrolling.ts
- library/src/scripts/headers/VanillaHeader.tsx
- library/src/scripts/layout/PanelLayout.tsx
- library/src/scripts/layout/ScrollOffsetContext.tsx
Relates to https://github.com/vanilla/knowledge/issues/908
- Refactors `<UserContent />` to use hooks & make it aware of the scroll offset context.
- Add the hash offset to `ScrollOffsetContext` so that it works with custom theme headers (and our own header). This will use the calculated offset from the top of the page as the anchor point when scrolling to hash urls. I've wrapped `VanillaHeader` with this.
- Add method to disable the scroll offset temporarily. This is important because we can only calculate the target position at the beginning of the scroll. Everything looks incorrect if the headers adjust themselves in the middle of the scroll.
> Fix scroll positioning issues

- applications/vanilla/models/class.commentmodel.php
Categories that has never been marked as read weren't automatically marked as read when all discussions in such a discussion have been read.
This PR solves issue https://github.com/vanilla/vanilla/issues/6856
> Fix auto marking categories as read

- library/src/scripts/forms/inputStyles.tsx
- library/src/scripts/styles/styleHelpers.ts
- plugins/rich-editor/src/scripts/editor/richEditorFormClasses.ts
Fixes issue on iOS devices where some input text fields are being cut off.
I split the "textInputSizing" into 2 functions, one that calculates its own height based on the font size and padding and the other that figures out the padding based on the target height.
> Fixed text input styles for iOS devices

- library/setup/ComposerHelper.php
Using `system` instead of `passthru` allows you to see the progress of the the build command.
Previously it would run the whole build (takes a couple minutes) then spit out all of the output at once.
> Use system instead of passthru for build handoff

- applications/vanilla/views/discussion/helper_functions.php
When the rich-editor is the default editor on a community, embedded comments doesn't work.  This is because the rich-editor isn't mounted and and textbox doesn't support the format type of rich.
The writeEmbedCommentForm method has been modified to use GDN_Form::bodyBox to allow for the editor to handle various formats.  A default format of _TextEx_ has been added.
1. ensure you can embed comments on your local
2. enable rich editor
3. From embedded comments from post a comment
4. Verify comment is posted can renders correctly on the site and local.
5. Ensure posting on you local isn't broken
6. Test with various posting formats
Closes vanilla/wordpress-vanilla#28 
Closes vanilla/support#272
> RichEditor - Enable compatibility with embedded content

- applications/dashboard/modules/class.mediaitemmodule.php
This PR refers to [this issue](https://github.com/vanilla/vanilla/issues/8675). It changes the MediaItemModules addButton method to the following definition:
`public function addButton($text, $url, $attributes = ['class' => 'btn btn-secondary'])`
During process flow an empty $attributes parameter would have been replaced by exactly that array. 
Therefore passing it as default
1. makes this behaviour more obvious and
2. makes using this method more convenient
> Add default value for MediaItemModule->addButton() $attributes parameter

- library/core/class.proxyrequest.php
Presently in the ProxyRequest class we expect successful responses to have a response body. Many APIs will return no content and a 204 response code when PATCHing or PUTing. This is being interpreted as a failure. 
This PR will check if the response code is not 2XX before concluding there was a negative response.
[See this document for more information about 204 responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)
> Fix ProxyRequest so that it can handle content-less 204 responses.

- library/src/scripts/theming/reset.ts
- library/src/scss/_base.scss
- library/src/scss/utility/_icons.scss
I've moved the icon base styles from KB. I need these setup for the retreat demo and it's too much work to convert to typestyle right now, so I'm just moving it.
I'm also adding a single JS import `@library/theming/reset` that will bring along the required style reset to make stuff like `<TitleBar />` and `<DropDown />` look correct.
> Move icons styles from KB

- library/core/class.proxyrequest.php
Presently we do not treat PATCH requests differently from GET requests which any integral modern API will not support. This PR will package cURL request properly when the PATCH verb is invoked.
This PR closes: https://github.com/vanilla/vanilla/issues/8749
> Add support to make PATCH request through ProxyRequest.

- library/core/class.proxyrequest.php
Package cURL request properly when the PATCH verb is invoked. Presently we do not treat PATCH requests differently from GET requests which any integral modern API will not support.
> Backport: Add support to make PATCH request through ProxyRequest Class.

- plugins/rich-editor/RichEditorPlugin.php
As described [here](https://github.com/vanilla/vanilla/issues/8690), when the Rich Editor is disabled it removes the input formatter lines from the config which causes Vanilla to use the values from config-defaults, but "Rich" is the format in config-defaults. Therefore the remains "Rich" which causes errors and is not the intention of those lines in the onDisable() method.
When Rich Editor is disabled the format must be set to some format which doesn't require a special editor. I've chosen Markdown but that was quite arbitrary. I feel allowing HTML "surprisingly" might be a bad decision, Text would be  to barebone and Markdown feels somewhat more modern than BBCode.
> Set Markdown as input formatter when Rich Editor is disabled

- plugins/rich-editor/src/scripts/@types/quill.d.ts
- plugins/rich-editor/src/scripts/quill/KeyboardBindings.ts
- plugins/rich-editor/src/scripts/quill/MarkdownModule.ts
- plugins/rich-editor/src/scripts/quill/VanillaTheme.ts
Closes https://github.com/vanilla/vanilla/issues/7159
* `` ``` ``         -> Code Block
* `###`           -> Headings (2-5)
* `>`             -> Quote
* `!>`            -> Spoiler
* `_text_`        -> Italic
* `__text__`      -> Bold
* `___text___`    -> Bold & Italic
* `*text*`        -> Italic
* `**text**`      -> Bold
* `***text***`    -> Bold & Italic
* `~~text~~`      -> Strike
* `` `text` ``        -> Code
- I've added a new module that implements these directly with it's own `keydown` handler. This way it can run before the built in `KeyboardModule`.
- I've made some of the types surrounding quill keyboard handlers a little bit more accurate.
- It's not really possible to write tests at the moment. We need additonal test infrastructure to simulate actual keyboard events. Issue here …
```
> Add markdown keyboard shortcuts to Rich Editor

- library/src/scripts/content/userContentStyles.ts
Fixes https://github.com/vanilla/vanilla/issues/8635
Inline code was not styled properly for the new `userContentStyles`. This PR fixes it.
> Fix inline code styles

- library/Vanilla/AddonManager.php
I used `Cache.` config prefix becuase it already exists. I didn't use `Cache.Filecache.` becuase this is a lower level thing than filecache, and involves the object/class/addon caching regardless of type of cache.
Default is relative for backwards compatibility. 
Setting false will allow you to set an absolute path to the cache directory, as a constant in a similar way to the upload directory.  Useful for multi-tenancy arrangements.
> A config override for relative/absolute path in setCacheDir

- library/src/scripts/headers/mebox/pieces/CompactSearch.tsx
There is some focus watching going on in `CompactSearch` that is responsible for closing the component if it loses focus. That is no longer the desired behavior, so the watching is being removed. The component should remain until a search is performed or its "Cancel" button is clicked.
Closes vanilla/knowledge#895
> Fix CompactSearch closing when losing focus

- applications/dashboard/controllers/class.entrycontroller.php
Remove unnecessary calls of
Gdn::session()->ensureTransientKey();
since we have a check down there, which can be confirmed with X-Request-With header
$this->Request->isAuthenticatedPostBack()
Closes: #8578 
Closes: #8714
> Activate X-Request-With header validation instead of Transient key for entry controller

- library/src/scripts/bootstrap.ts
- library/src/scripts/dom/domUtils.tsx
- library/src/scripts/forms/TextInput.tsx
- library/src/scripts/forms/mountInputs.tsx
- library/src/scripts/utility/utils.ts
Relates to https://github.com/vanilla/knowledge/issues/846
Blocking https://github.com/vanilla/knowledge/issues/989
This PR
- adds some core utilities to allow mounting a React managed input component on top of an existing normal input (like from `GDN_Form`).
- Improvements to our `slugify` function to allow more flexibility.
- A `<TextInput />` component that can do realtime filtering of input.
- Automatically mounts `<TextInput />` components over fields with `data-react-input` attribute while preserving their existing attributes.
> Add support for React-based input validation in existing forms

- library/Vanilla/Web/Asset/DeploymentCacheBuster.php
- tests/Library/Vanilla/Web/Asset/DeploymentCacheBusterTest.php
`DeploymentCacheBuster` had some logic that would reset the instance's `deploymentTime` property if calling the `value` method and the "grace period" had elapsed. The property would be incremented by the value of `GRACE_PERIOD`, each time. This property would then be used as the basis for generating the cache-busting key. If `value` is only called once, this isn't a problem. However, Vanilla keeps a _shared_ instance of the cache buster. If `value` were invoked multiple times in the same request, you'd see different values for the cache buster.
The value of `deploymentTime` is no longer reset after the object is instantiated. The return value of `value` should now be consistent in requests. A basic test has been added to verify this behavior.
> Fix deployment cache buster incrementing when called

- applications/dashboard/controllers/RobotsController.php
Now that Vanilla has core robots.txt support, the default rules are being tightened up a little. Registration and sign-in pages, both local and SSO, should be "disallowed". The current ruleset already blocks the local registration and sign-in pages. However, now all pages under (and including) /sso will be similarly blocked.
Closes #8577
> Add /sso to default robots.txt

- library/src/scripts/flyouts/DropDown.tsx
- library/src/scripts/flyouts/DropDownContents.tsx
- library/src/scripts/flyouts/dropDownStyles.ts
- library/src/scripts/layout/frame/FrameHeader.tsx
- library/src/scripts/layout/frame/frameStyles.ts
- plugins/rich-editor/src/scripts/flyouts/EmbedFlyout.tsx
Design tweaks for embed flyout:
- Now wider on desktop
- Fixed vertical positioning to match the emoji picker's position
- Updated placeholder text to be "https" instead of "http"
Design tweaks for location picker: 
- Fixed styles for back chevron "<"
- Fixed paddings so the selected state goes all the way to the edge
For: https://github.com/vanilla/knowledge/issues/914
> KB: Location picker and embed flyout design tweaks

- library/src/scripts/features/search/IndependentSearch.tsx
- library/src/scripts/features/search/searchBarStyles.ts
- library/src/scripts/headers/TitleBar.tsx
White preparing my demo I noticed 2 problems:
- No results in the search page was in a box shadow (as if it was in a modal)
- The search icon in the page was above the results in the titleBar
This PR fixes both issues.
> Fixed styles for "no results" on the search page and a z-index issue

- applications/vanilla/views/discussion/embed.php
- applications/vanilla/views/discussion/helper_functions.php
- plugins/rich-editor/RichEditorPlugin.php
Per vanilla/vanilla#8738 we mounted an editor for embedded content and set the format type for those comments to TextEx.  The format of TextEx causes a mismatch with that of the form and would cause content to render incorrectly.  Quotes rendering was especially off (see below).  
This allows for the comment form to inherit the format type set in the dashboard so that there would be no conflict in rendering.  So changes had to be made in embed view and the rich editor plugin to ensure the data being accessed was an object instead of an array.  This was done to make sure rich content would display correctly on the page where the embedded comments were displayed.
Example of Embedded Comment with a quote
```
> @user1 said:
> Quoted Text form the body of the comment
> 
This looks weird ^
``` …
> Embedded Comments - Inherit dashboard post format type

- library/src/scripts/content/embeds/codepen.tsx
The client-side CodePen embed class and the server-side CodePen embed class are not using the same attribute to build the iframe. The client-side class is looking for [`src` in the `attributes`](https://github.com/vanilla/vanilla/blob/276b178c5ba7182d1f3432b04dc7cfe8b7cdc741/library/src/scripts/content/embeds/codepen.tsx#L17), while the server-side class is looking for [`embedUrl` in `attributes`](https://github.com/vanilla/vanilla/blob/276b178c5ba7182d1f3432b04dc7cfe8b7cdc741/library/Vanilla/Formatting/Embeds/CodePenEmbed.php#L53). The server-side class renders. The client-side class does not.
The client-side CodePen embed class has been updated to use the proper attribute, `embedUrl`.
Closes vanilla/knowledge#973
> Fix CodePen embeds in Rich Editor

- .travis.yml
- library/src/scripts/content/_codeDark.scss
- library/src/scripts/content/countStyles.ts
- library/src/scripts/forms/radioTabs/tabButtonListStyles.ts
- library/src/scripts/headers/mebox/pieces/compactMeBoxStyles.ts
- library/src/scripts/layout/smartAlignStyles.ts
- library/src/scripts/result/ResultMeta.tsx
- plugins/rich-editor/src/scripts/editor/richEditorVariables.ts
- plugins/rich-editor/src/scripts/flyouts/pieces/flyoutClasses.ts
- plugins/rich-editor/src/scripts/flyouts/pieces/insertEmojiClasses.ts
In https://github.com/vanilla/knowledge/pull/953 we started enforcing prettier in CI for KB.
In this PR I've fixed a few formatting issues that slipped through and update the travis script to run prettier --check. I also re-ordered the JS commands to be similar to the KB travis setup (Eg. Run the fast things first).
> Enforce prettier in CI and fix some typescript formatting

- library/src/scripts/bootstrap.ts
- library/src/scripts/pageViews/pageViewTracking.test.ts
- library/src/scripts/pageViews/pageViewTracking.ts
Closes https://github.com/vanilla/vanilla/issues/8761
Adds page view tracking and unit tests. Just register your callbacks with `onPageView()`.
> Create page view handlers and initialization

- themes/keystone/views/default.master.tpl
- themes/theme-boilerplate/views/default.master.tpl
This solves https://github.com/vanilla/vanilla/issues/8856
Boilerplate (and therefore Keystone, too) moved the AfterBody event upwards in the DOM tree. This PR moves it right before the closing body tag again
> Move AfterBody event in boilerplate and keystone before the closing body tag

- applications/dashboard/controllers/class.entrycontroller.php
- library/core/class.coreexception.php
- library/core/class.passwordhash.php
closes [#8850](https://github.com/vanilla/vanilla/issues/8850)
An admin can force reset a user's password from the dashbaord
Next time the user tries to log in, you get
"here" is text and not a link.
The error message has an html tag
(1*) that gets stripped in (2*).
(1*) [class.passwordhash.php#L92](https://github.com/vanilla/vanilla/blob/978119bdc451284b2cd4785e66319d3292152f7b/library/core/class.passwordhash.php#L92)
(2*) [class.form.php#L2278](https://github.com/vanilla/vanilla/blob/master/library/core/class.form.php#L2278)
From the dashboard, edit a user, select "Force user to reset their password and send a notification email"
Login, verify the resetpassword link.
I added a new exception class to handle html in the error message at the same time keeping code sanitization in place.
> Fix: Reset password link when password has been force reset by an admin

- library/src/scripts/content/userContentStyles.ts
- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
- plugins/rich-editor/src/scripts/editor/richEditorClasses.ts
- plugins/rich-editor/src/scripts/editor/richEditorVariables.ts
Currently rich editor doesn't have a way to enable a placeholder.
This PR adds
- Support for providing quill options with the `options` parameter on rich editor.
- Styling support for this placeholder. This might seem a little odd, but a `::before` element is the only easy way to get some relatively positioned content into the editor that's not actually part of the content editable. The `.ql-blank` class is how quill applies this in its own styles (which we don't use). https://github.com/quilljs/quill/issues/1831#issuecomment-351938711
> Add styling and wireup for editor placeholder

- library/src/scripts/bootstrap.ts
- library/src/scripts/pageViews/pageViewTracking.ts
- plugins/rich-editor/src/scripts/editor/ForumEditor.tsx
- plugins/rich-editor/src/scripts/quill/ClipboardModule.ts
Blocking https://github.com/vanilla/knowledge/pull/1031
Looks like https://github.com/vanilla/vanilla/issues/7567 is happening on KB right now.
I'm adding an explicit class so we can manage these differently between KB and forum.
This has been moved out of bootstrap. It's not quite the right place for it.
> Add explicit rich editor scrolling container class and remove analytics setup in bootstrap

- bootstrap.php
- library/Vanilla/Analytics/ActionConstants.php
- library/Vanilla/Analytics/Client.php
- library/Vanilla/Contracts/Analytics/ClientInterface.php
This update adds a couple new things:
1. A standard interface for analytics clients to be used by Vanilla and its addons.
1. A stub class that implements the aforementioned interface.
1. Add `Vanilla\Contracts\Analytics\ClientInterface`. This interface defines the shape analytics clients in Vanilla should follow.
1. Add `Vanilla\Analytics\Client`. This class is meant to be a placeholder stub for now. Addons can safely inject this "client" class as a dependency.
1. Add `Vanilla\Analytics\ActionConstants`. This is intended to be a class of constants representing front-end action slugs. These slugs will likely be associated with Redux actions.
No functional changes to Vanilla are included.
Relates to #8559
> Add Analytics Client interface and stub

- applications/dashboard/controllers/class.entrycontroller.php
- library/Vanilla/Web/CacheControlMiddleware.php
- library/core/class.controller.php
Closes https://github.com/vanilla/vanilla/issues/8581
After some discussions and testing the `vary` header is required so that the user does not get stuck on a cached page when returning some previously cached page.
I've removed the special case of no caching from the entry controller. It will now return standard cache headers (`no-cache` if the user has a session and `public, max-age 120` if not).
> Add cache headers to entry controller and ensure vary header for Gdn_Controller

- library/src/scripts/features/search/IndependentSearch.tsx
- library/src/scripts/features/search/searchBarStyles.ts
- library/src/scripts/layout/PanelLayout.tsx
- library/src/scripts/navigation/navLinksStyles.ts
- library/src/scripts/styles/styleHelpers.ts
Closes https://github.com/vanilla/knowledge/issues/1032
Closes https://github.com/vanilla/knowledge/issues/1035
- Fixes code blocks overflowing the center column of the panel layout.
- Fixes NavLinks only displaying 1 column.
- Fixes some flickering effect that was occurring with the `IndependantSearch` (we were doing a lot more updating than necessary. This become clear with some light refactoring of the component).
> Fix various style regressions

- plugins/Twitter/addon.json
- plugins/Twitter/class.twitter.plugin.php
- Twitter’s API changed `callback_url` to `oauth_callback` resulting in broken profile connects.
- Remove the ability to profile connect on another user’s profile. Twitter now whitelists their callback URLs so we can only redirect back to the generic profile URL which belongs to the current user. This also comes with an additional check that the profile that initiated the connect matches the current session user.
- Fix typo in the `profileConnectUrl()` function name.
> Twitter addon fixes

- applications/vanilla/models/class.discussionmodel.php
closes [#421](https://github.com/vanilla/support/issues/421)
When creating a discussion without selecting a category, we are getting a redundant missing category error.
(1*)[class.discussionmodel.php#L1967](https://github.com/vanilla/vanilla/blob/eb9b742d4234d0254db1107333470f6c7cec6955/applications/vanilla/models/class.discussionmodel.php#L1967) (adds "Category does not exist")
& 
(2*)[class.discussionmodel.php#L2052](https://github.com/vanilla/vanilla/blob/eb9b742d4234d0254db1107333470f6c7cec6955/applications/vanilla/models/class.discussionmodel.php#L2052) (adds "Category is required")
> Remove redundant missing category error

- library/core/class.controller.php
- isHomepage is not really an API value, but rather a view value similar to title and description.
- Currently, the page will segfault of some traces are included in an XML rendering because of circular references in exceptions from notices.
> Remove isHomepage from data rendering and the trace from XML rendering

- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
Needs backport to `release/3.0` (so we can actually get the release out).
Issue https://github.com/vanilla/vanilla/issues/8889
I'm not closing the issue because tests will come as a followup. This is just to unblock the release.
The issue ended up being some missing dependencies in the `useEffect` calls. There is an ESLint rule that can automatically detect this kind of thing, and I've detailed it as part of this issue https://github.com/vanilla/vanilla/issues/8719.
It's called [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks) is part of the official react monorepo, and would have caught this bug. Some integration tests around the `legacyMode` for rich editor would have caught this as well though, so I intend to add some this …
> Fix forum post editing not working with Rich Editor

- library/core/class.form.php
This fixes: https://github.com/vanilla/vanilla/issues/8575
The color picker always started with a default value. With this change the starting value can be passed to the form control like that: ` $form->color('FieldName', ['Value' => '#0099aa'])`
> Allow starting values for color picker form control

- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
There's no issue for this, I just came across it.
There was a slow running infinite loop in EditorContent. You could see this by throwing a console.log() in the render.
It would render approximately 60 times a second due this effect constantly clearing the operations.
Essentially:
1. Check `!operationsQueue` for bailout.
2. `operationsQueue` is `[]` so no bailout.
3. No operations to run.
4. Clear queue.
5. Causes re-render. Go back to step 1
I fixed this by
- Accepting an empty array as a bailout condition for this hook.
- Returning the cleanup method for scheduling with react, instead of running it synchronously.
> Fix editor content queue infinite loop

- composer.json
- composer.lock
- library/Vanilla/PageScraper.php
- tests/Library/Vanilla/PageScraperTest.php
- tests/fixtures/src/PageScraper.php
#8893 introduced the latest version of [vanilla/garden-http](https://github.com/vanilla/garden-http). Unfortunately, this version contained some breaking changes. Namely, stricter typing was introduced into classes Vanilla would be extending (e.g. `HttpClient`, `HttpRequest`). These extended classes in Vanilla also implement interfaces (e.g. `RequestInterface`) that no longer align with garden-http v2. These classes and interfaces will need to be refactored before garden-http v2 can be used in core Vanilla.
The garden-http version is being rolled back to its latest v1 release.
`PageScraperTest` had to be updated to avoid using garden-http, because of recent protocol restrictions in the library. The fixture used by `PageScraperTest` now reads file contents from the disk and serves them up …
> Rollback garden-http to v1

- library/src/scripts/dom/domUtils.test.ts
- library/src/scripts/dom/domUtils.tsx
This needs to make it to the 3.0 branch.
Works towards https://github.com/vanilla/vanilla/issues/8889
This PR fixes the comment editing specifically.
https://github.com/vanilla/vanilla/pull/8890 fixes the discussion editing.
Our `delegateEvent` function checks if there is a hash of an event already. If there is, it will not set the listener (just re-use the same one). This method is supposed to return a hash which can be used to clear the delegated event, but in cases where the event was already set we were not removing the hash. This would cause a crash when `removeDelatedEvent()` would be called with `undefined`.
I fixed the method and updated a test to cover this case.
> Fix comment post editing in the forum

- applications/dashboard/controllers/class.settingscontroller.php
- applications/dashboard/locale/en.php
- applications/dashboard/settings/class.hooks.php
- applications/dashboard/views/settings/plugins.php
While reviewing some locale strings I noticed two very similar strings. On top of that neither of them were used in the app, but rather a third string that we don’t currently translate.
This PR changes the string to one in our locales repo with a translation.
> Tweak the locale settings help text

- composer.json
- composer.lock
- library/Garden/Web/RequestInterface.php
- library/core/class.request.php
- tests/InternalRequest.php
- tests/fixtures/src/Request.php
Our Garden HTTP version was out of date. I've brought it up to the latest version.
There was a slight change in the `HttpRequest` class provided by garden http that required minor updates to some strengthen tighten up some types.
> Update garden-http to version 2

- .gitignore
- plugins/emojiextender/EmojiExtenderPlugin.php
- plugins/emojiextender/addon.json
Backport will need to target `release/3.0` and `release/2019.007`.
Fixes https://github.com/vanilla/support/issues/456
> Fix some case sensitivity issues with emoji extender

- library/src/scripts/bootstrap.ts
Client-side page view events will now use the `onPageView` function to make a request to the tick API v2 resource on every page load. Successful completion of this request will also dispatch a custom "analyticsTick" event, which is a native implementation of [the existing jQuery event triggered in global.js](https://github.com/vanilla/vanilla/blob/56624c7f454d5f6879c43b90e629bd61ff8e761e/js/global.js#L847).
> Add call to tick API v2 endpoint when tracking a page view

- applications/dashboard/controllers/class.entrycontroller.php
After resetting your password the site should redirect to the homepage. This stopped working after the form moved to AJAX.
> Fix password reset redirect

- applications/dashboard/controllers/class.entrycontroller.php
After resetting your password the site should redirect to the homepage. This stopped working after the form moved to AJAX.
> Fix password reset redirect (Backport)

- applications/dashboard/views/entry/connect.php
- applications/dashboard/views/entry/signin.php
- Add a hook into the sign in form to support the TermsManager.
- Add the ability to hide the password field.
The Terms Manager is an internal plugin that allows Admins to control when users agree to the terms of use, including when users connect over SSO.
> Modify core code to support the Terms of User Manager plugin.

- composer.json
- composer.lock
- tests/APIv0/APIv0.php
The APIv0 tests were failing because of a mismatch from the upgrade to garden-http 2.0 (see line 245). This PR also includes some other inspection fixes that helped troubleshoot the issue.
The composer.json was only upgraded to include ext-pdo which should not have made a material change to the config.
> Fix the APIv0 build

- .travis.yml
If we have an issue only on the cron build it would be nice to be able to trigger that build in order to test rather than wait a day for the cron to run.
> Allow the Travis CI API to also trigger full builds

- applications/dashboard/views/entry/connect.php
- applications/dashboard/views/entry/signin.php
Backport: https://github.com/vanilla/vanilla/pull/8928
- Add a hook into the sign in form to support the TermsManager.
- Add the ability to hide the password field.
The Terms Manager is an internal plugin that allows Admins to control when users agree to the terms of use, including when users connect over SSO.
> Backport: Modify core code to support the Terms of User Manager plugin.

- applications/dashboard/views/settings/security.php
It does look nicer to have HTML in our descriptions, but it makes translation more difficult. In addition, concatenating strings means that some languages may not work properly.
This change simplifies the text so that translations can be more easily maintained.
> Update the security wording for easier translation

- plugins/rich-editor/src/scripts/editor/EditorContent.test.tsx
- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
The editor test had a flag for only running one single test. This has been removed.
Bonus: `useOperationsQueue` was improperly clearing its cache. This has also been addressed.
> Remove "only" test flag from editor test

- library/Vanilla/Web/CacheControlMiddleware.php
- library/core/class.controller.php
- library/core/class.oauth2.php
- plugins/googlesignin/addon.json
This PR uses the verification tokens from `SsoUtils` in `Gdn_OAuth2` to prevent CSRF and replay attacks when signing in via OAuth 2. Notes:
- `SsoUtils` is injected via the `Vanilla\InjectableInterface` to avoid affecting subclasses.
- The sign in has been changed into a redirect to avoid HTTP cache pollution. Even though we don’t fully respect cache headers, I’ve added the appropriate no cache headers before the redirect too.
- The state has been changed from a URL encoded array to a base 64 JSON array because I found that some OAuth servers can’t handle the double encoding.
Testing
I tested this with two subclasses of `Gdn_OAuth2`: The Google Sign-in addon and a custom subclass. Both worked and also threw the appropriate error when the token was wrong.
Closes …
> Add state token support to Gdn_OAuth2

- plugins/emojiextender/EmojiExtenderPlugin.php
Fixes https://github.com/vanilla/support/issues/491
The previous refactoring here added a namespace, which alterred the default class name for the plugin.
`Gdn_Pluggable` depends on this automatically determined plugin to figure out the event name by default.
> Fix broken emoji extender event name

- library/core/functions.general.php
We have a long standing difficulty when converting regular pages to AJAX pages where everything works except for redirects. Currently we go through and change calls to `redirectTo()` to `Gdn_Controller::redirectTo()` and have had to do that over and over again.
This change proposes putting some logic within `redirectTo()` itself to properly render the correct redirect code if the call is being made within an AJAX request. This is a bit of a kludge, but I figured I would put this out for code review because it is a trade off between a kludge and constantly doing the same bug fix over and over again.
> Fix some AJAX forms not properly redirecting

- themes/keystone/views/default.master.tpl
- themes/theme-boilerplate/views/default.master.tpl
Fixes https://github.com/vanilla/vanilla/issues/8956
The mobile search boxes here were missing the check for advanced search. As a result the module would not appear on mobile unless advanced search was enabled.
> Add advanced search check to mobile searchbox

- library/core/class.theme.php
When a site doesn’t have an uploaded logo image then the site’s title is used. However, the title is not escaped. Even though the title is permission gated it is a good practice to escape the title in this function nonetheless.
I polled all of our sites and see that the only sites that would be affected all have “&” in their titles.
Closes https://github.com/vanilla/vanilla-patches/issues/391.
> Escape the title in Gdn_Theme::logo()

- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
- plugins/rich-editor/src/scripts/quill/VanillaTheme.ts
Fixes https://github.com/vanilla/vanilla/issues/8957
Some recent refactoring introduced a bug where certain editor events were not being properly tracked.
This is fixed by 2 things:
1. Tracking the `EDITOR_CHANGE` event instead of the `selection-change` event.
2. Initializing the synchronization handler when first mounting the editor.
> Fix incorrect editor selection handling

- applications/vanilla/controllers/class.moderationcontroller.php
- applications/vanilla/views/moderation/confirmdiscussionmoves.php
related [#1789](https://github.com/vanilla/internal/issues/1789)
When moving a discussion, we are not sending the discussion's data, which in the case of ideation [class.ideation.plugin.php#L354](https://github.com/vanilla/internal/blob/master/plugins/ideation/class.ideation.plugin.php#L354) Type is false, and the proper ideation categories are not filtered, allowing moderators to move idea discussions to non-idea categories (cause api v2 /discussions call to fail).
> Add discussion data when calling categroydropdown

- applications/vanilla/models/class.draftmodel.php
related [#1885](https://github.com/vanilla/internal/pull/1885)
related [#459](https://github.com/vanilla/support/issues/459)
This PR fires the event added in the referenced PR to check if the user saving the draft has rank restrictions for posting links.
> Add event draftModel_beforeSaveDiscussion when saving a draft

- applications/dashboard/package.json
- plugins/editor/package.json
Our recent changes to yarn workspaces means that node modules get installed for all plugins.
Our deployment process runs as `root` w/ a sudoers config, so this flag has to be passed for the post install to work.
> Fix dashboard/editor bower install during deployment as root

- applications/dashboard/controllers/class.entrycontroller.php
This PR will remove the RankID from being filtered out of the data being inserted into the User table and instead, filter it out in the entry endpoint. This way SSO plugins can allow trusted sources to pass the RankID. This is the same way we handle Roles.
> Don’t allow the passing of the RankID directly to connect endpoints.

- applications/dashboard/controllers/class.entrycontroller.php
Backport #8975 
This PR will remove the RankID from being filtered out of the data being inserted into the User table and instead, filter it out in the entry endpoint. This way SSO plugins can allow trusted sources to pass the RankID. This is the same way we handle Roles.
> Backport: Don’t allow the passing of the RankID directly to connect endpoints.

- applications/dashboard/views/entry/connect.php
This PR adds conditions to show or hide the connect name field based on arguments (data(‘HideName’)) passed from plugins.
If a plugin wants to inject business logic into `/entry/connect` script it will trigger showing the Password and the User Name field every time. There are various kludges that can be done to hide these fields but it gets way too messy.
> Add conditions to show or hide the entry/connect name field.

- applications/vanilla/controllers/class.categorycontroller.php
**Issue:**
Currently non administrators\moderators are unable to follow categories.
**Details:**
A permission check in the CategoryController::Followed endpoint was failing because it was receiving _null_ instead of the categoryid.
**To Test:**
1) create a category 
2) have a member try to follow the account.
3) A _Vanilla.Discussions.View_ should appear
Addresses Vanilla/Support#511
> Fix Category following for members

- applications/dashboard/views/entry/connect.php
Backport 8984
Add conditions to show or hide the connect name field based on arguments (data(‘HideName’)) passed from plugins.
If a plugin wants to inject business logic into /entry/connect script it will trigger showing the Password and the User Name field every time. There are various kludges that can be done to hide these fields but it gets way too messy.
> Backport: Add conditions to show or hide the entry/connect name field.

- library/Vanilla/Web/ContentSecurityPolicy/DefaultContentSecurityPolicyProvider.php
Vanilla serves up a [`frame-ancestors` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) as part of its `Content-Security-Policy` header. Essentially, it ensures you can only embed a site under specific hosts. Currently, the header only sends out trusted domains. This update will add a fallback: if no trusted domains are found, try to grab the host from `Garden.Embed.RemoteUrl`. This config value is managed on the Embed Settings page of the dashboard.
The `frame-ancestors` will also now only be sent if the site is configured to enable embedding. This should be the only time this directive is relevant. If the site is not configured for embedding, Vanilla will already [send an `X-Frame-Options` …
> Add frame ancestor fallback of embed remote URL

- package.json
- yarn.lock
Axios version was outdated. It has been updated. The yarn lock file was regenerated as part of this process.
> Update axios version

- applications/vanilla/models/class.discussionmodel.php
Adds sink as a filter field so that sinking can’t be done by general purpose endpoints. Closes https://github.com/vanilla/vanilla-patches/issues/576.
Tested:
- Adding a discussion with Sink: 1. The sink was set to 0.
- Editing a discussion with Sink: 1. The sink didn't change.
- Sinking/unsinking a discussion. Still works.
> Don’t allow users to sink a discussion from the /post/*discussion endpoints

- applications/conversations/controllers/class.messagescontroller.php
Don’t allow users to specify a message ID when posting a message. Closes https://github.com/vanilla/vanilla-patches/issues/575.
I tested this just by adding a hidden MessageID to the view.
> Strip the MessageID out of /conversations/addmessage

- library/src/scripts/content/hashScrolling.ts
- library/src/scripts/dom/TabHandler.ts
- library/src/scripts/dom/hookUtils.tsx
- library/src/scripts/flyouts/FlyoutToggle.tsx
- library/src/scripts/headers/mebox/pieces/UserDropdown.tsx
- library/src/scripts/layout/PageHeading.tsx
- packages/vanilla-eslint-config/index.js
- packages/vanilla-eslint-config/package.json
- plugins/rich-editor/src/scripts/editor/Editor.tsx
- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
- yarn.lock
__DO NOT MERGE THIS PR UNTIL https://github.com/vanilla/vanilla/pull/8941 IS MERGED__
Contributes to https://github.com/vanilla/vanilla/issues/8719 Other parts of that issue will be completed in followup PRs
- Adds `eslint-plugin-react-hooks` to `@vanilla/eslint-config`.
- Fixes loose usages of react hooks (the warnings are pretty darn good).
> Add eslint plugin for react hooks validation

- applications/dashboard/models/class.logmodel.php
https://github.com/vanilla/vanilla/pull/8989 introduced formatting to the bodies of moderation queue posts.
Unfortunately, the post titles ended up getting formatted as well. I've switched them to just filter the titles instead of calling `formatKey()`.
> Fix moderation/spam queue titles being formatted

- applications/dashboard/models/class.searchmodel.php
Fixes https://github.com/vanilla/vanilla/issues/8680
This only affected the search page _**Without Advanced Search**_.
There is some additional downstream formatting that is not aware of the change that occured here. Really what happen is that by formatting the summary with `Gdn_Format::to` it has been converted to HTML. I've update the type to accurately represent that.
> Fix simple search formatting

- library/src/scripts/embeddedContent/GettyImagesEmbed.tsx
- library/src/scripts/embeddedContent/ImgurEmbed.tsx
- library/src/scripts/embeddedContent/InstagramEmbed.tsx
- library/src/scripts/embeddedContent/TwitterEmbed.tsx
A few embeds use relative-protocol URLs for including the third-party embed scripts. Now, they're explicitly secure URLs. There should be no functional change.
> Fix third-party embed scripts using relative protocol

- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
It seems I broke the user content styles in the editor with the performance fix in https://github.com/vanilla/vanilla/pull/9012
As a result, user content styles weren't properly being applied in KB.
I've opted for a new approach to preventing the infinite appending of classes.
> Fix broken editor styles in KB

- library/src/scripts/icons/common.tsx
- library/src/scripts/icons/iconStyles.ts
Many of our icon styles are still in CSS, so I've created icon size partial for icon sizes. This PR only fixes the size of the new folder icon, but more sizes will get added in the future.
Also see: https://github.com/vanilla/knowledge/pull/1081
Closes: https://github.com/vanilla/knowledge/issues/956
> Fixed new folder icon size

- library/src/scripts/routing/LinkAsButton.tsx
- library/src/scripts/styles/styleHelpersBorders.ts
Fixes a button issue (on the KB not found page) and border radii issues (same page and in the editor.
Removed the "type" from the back to home button, since it doesn't need one and was adding 2 conflicting classes.
Removed if statement bypassing all border styles if none were given. They should use defaults (which they now do).
Added fallback to global radius if none were found.
Closes: https://github.com/vanilla/vanilla/issues/9039
> Fix border radius for go back to home and for editor flyouts

- applications/dashboard/design/admin.css
- applications/dashboard/design/style-compat.css
- applications/dashboard/js/dashboard.js
- applications/dashboard/scss/compatibility/editor/_richEditorLegacy.scss
- library/Vanilla/EmbeddedContent/Embeds/ErrorEmbed.twig
- library/Vanilla/EmbeddedContent/Embeds/QuoteEmbed.php
- library/Vanilla/Formatting/Formats/RichFormat.php
- library/Vanilla/Formatting/Quill/Filterer.php
- library/src/scripts/embeddedContent/QuoteEmbed.tsx
- library/src/scripts/embeddedContent/embedService.tsx
- library/src/scripts/navigation/CloseButton.tsx
- library/src/scripts/routing/links/LinkContextProvider.tsx
- tests/Library/Vanilla/Formatting/Quill/FiltererTest.php
Fixes https://github.com/vanilla/internal/issues/1920
Fixes https://github.com/vanilla/vanilla/issues/9037
- Fixes some data corruption issues in some embeds leading to crashes.
- Updates `Quill\Filterer` to work better with the new embeds. Unit tests for additional coverage have been added. The inline comments should serve as some documentation.
- Fixes embed styles. No issue for this but embeds 1 after another were butted up against each other.
- Fixes a bug in `SmartLink` when used without it's context wrapper. The default behaviour is not to just pass links through the default format function if there is not context wrapper. More tests will come later in the sprint as I have a task for validating stuff around that.
- Fixes the button style on the EmbedFlyout.
- Updates the embed error …
> Fix various embed errors

- library/Vanilla/Formatting/Quill/Filterer.php
- tests/Library/Vanilla/Formatting/Quill/RendererTest.php
Getting the embed data pointer on line 62 was creating that value and assigning it to null if it did not exist. This caused non-external embeds, such as a mentions to end up with a structure similar to the following:
```json
{
"insert": {
"mention": {},
"external-embed": { "data": null }
}
}
```
This would have been caught if we ran all the rendering tests through the filterer first, so I've done, which should improve coverage of the filterer immensely.
See posts like this https://staff.vanillaforums.com/discussion/comment/3086/
> Fix broken mention rendering in Rich Editor

- library/src/scripts/features/search/SearchBar.tsx
- library/src/scripts/flyouts/FlyoutToggle.tsx
- library/src/scripts/flyouts/items/DropDownItemButton.tsx
- library/src/scripts/forms/Button.tsx
- library/src/scripts/forms/ButtonSubmit.tsx
- library/src/scripts/forms/select/ClearButton.tsx
- library/src/scripts/navigation/CloseButton.tsx
We were using "types" on buttons both for their HTML effects (like in forms) and also for classes. We had several class conflicts, so I decided to refactor the types. They no longer affect the classes, "baseClass" is the proper way to do that now.
"button" is the assumed type, but "submit" can also be specified when applicable.
> Refactored the way we use "type" for buttons

- library/src/scripts/forms/styleHelperButtonGenerator.ts
This looks like a big PR, but the only diff is [one line](https://github.com/vanilla/vanilla/compare/fix%2Fremove-debug-mode?expand=1#diff-86e7c89b254b6218b71eb5cae47b0a6cL59). I removed the debug mode on the button generation. It was generating warnings in the console.
> Removed "debug" mode from button generation

- plugins/rich-editor/src/scripts/toolbars/InlineToolbar.tsx
Closes https://github.com/vanilla/knowledge/issues/977
Simply focusing the editor before the selection fixes prevents the scroll position from jumping.
> Fix inline toolbar menu causing scroll position to jump

- library/Vanilla/EmbeddedContent/Factories/ScrapeEmbedFactory.php
- library/src/scripts/features/users/suggestion/UserSuggestionModel.test.ts
- library/src/scripts/features/users/suggestion/UserSuggestionModel.ts
- plugins/rich-editor/src/scripts/toolbars/pieces/MentionSuggestionList.tsx
Closes https://github.com/vanilla/vanilla/issues/5936
- Implements sorting logic in the mention list that prioritizes users that have been active in the last 90 days.
- Updates sorting to prioritize accents over casing. Essentially if the there are 2 users, `stephane` and `Stéphane`, and the user starts mentioning `sté` the accented username will be prioritized over the non accented one.
- Adds additional unit tests to reflect this change.
- Fixes mention crash when there are multiple users with the same username. (Fix is to user our properly calculated `domID` instead of the `user.name` as the unique react key.)
If anyone wants a big DB of usernames to test with I can share my sanitized one.
> Implement active user sorting in mention list

- applications/dashboard/settings/structure.php
closes https://github.com/vanilla/support/issues/624
closes https://github.com/vanilla/support/issues/630
GDN_DateExpires does not have an index, causing queries to generate a token to run slow.
> Fix slow pruning of access token tables with a high number of rows

- applications/vanilla/controllers/class.moderationcontroller.php
closes https://github.com/vanilla/vanilla/issues/9008
As a moderator, when moving a discussion without selecting a category, we get this error.
w'ere currently checking for permission to add a discussion in 
https://github.com/vanilla/vanilla/blob/ebf117f95a0d68020e3d37afc87df2cdc86ab7a8/applications/vanilla/controllers/class.moderationcontroller.php#L394
Add CategoryID validation.
To Test
Move a discussion without selecting a category, you should be served with the below validation error.
> Fix category validation when moving a discussion

- applications/dashboard/controllers/class.usercontroller.php
- applications/dashboard/views/profile/helper_functions.php
closes https://github.com/vanilla/support/issues/610
In order to switch a user from 'Not Verified' to 'Verified' from their profile, you have to click on 'Not Verified' and then reload the page for the change to take place.
from a user's profile, as an admin:
1) Click on 'Not Verified/Verified' one time and then reload the page.  status updates
2) Click on 'Not Verified/Verified' twice.  This changes the status immediately and without a reload.
**What should happen**
If a user is verified (GDN_User->Verified =1), clicking once on the 'verified' label , label should be updated to 'Not Verified'
$url should be updated to  $url = "/user/verify.json?userid=$userID&verified=1"; for when the user clicks next time (should become verified)
but instead what is happening is this 
if a user is …
> Fix toggling verified status on user profile not properly refreshing

- library/Vanilla/EmbeddedContent/Factories/VimeoEmbedFactory.php
- tests/Library/Vanilla/EmbeddedContent/Factories/VimeoEmbedFactoryTest.php
This regression was introduced with the refactoring. Noticed while doing some testing for https://github.com/vanilla/support/issues/631
I've added the URL type as well as the test for ti.
> Fix longform Vimeo URLs not embedding

- library/Vanilla/EmbeddedContent/Embeds/QuoteEmbed.php
- library/Vanilla/Formatting/Quill/BlotGroup.php
- library/Vanilla/Formatting/Quill/Blots/Embeds/ExternalBlot.php
- library/Vanilla/Formatting/Quill/Parser.php
- tests/Bootstrap.php
- tests/Library/Vanilla/Formatting/Quill/ParserTest.php
- tests/fixtures/src/EmbeddedContent/EmbedFixtures.php
Closes https://github.com/vanilla/vanilla/issues/8406
- Updates `Quill\Parser` to check for `QuoteEmbeds` in addition to `MentionBlots` inside of `parseUsernames`.
- Updates tests to cover quotes, and duplication of mentions.
- Adds some fixtures for creating embeds.
- Adds some minimal configuration of the `EmbedService` in the test bootstrap and removes config for the now-removed `EmbedManager`.
> Add notifications to users quoted in Rich posts

- library/src/scripts/forms/Button.tsx
- library/src/scripts/forms/buttonStyles.ts
- library/src/scripts/forms/styleHelperButtonGenerator.ts
- library/src/scripts/headers/mebox/pieces/MessagesContents.tsx
- library/src/scripts/headers/mebox/pieces/NotificationsContents.tsx
- library/src/scripts/layout/pageHeadingStyles.tsx
- library/src/scripts/routing/LinkAsButton.tsx
- library/src/scripts/styles/styleHelpersTypography.ts
Fixes https://github.com/vanilla/knowledge/issues/1086
- Fixes missing `TEXT` style in switch statement.
- Fixes incorrect `compose` icon import.
- Fixes generation of various border styles creating an incoming text color.
- Adds a missing base class in `<LinkAsButton />`.
> Fix button styling regressions

- plugins/rich-editor/src/scripts/quill/MarkdownModule.ts
Fixes https://github.com/vanilla/vanilla/issues/9028
Updates regex and logic of heading blot to:
- Not match lines that already have text.
- Fix calculation of selection indexes to be more robust.
Also
- Enforce all handlers to only run with space or enter. The only one that should now be triggered by enter is the Code Block handler.
> Fix markdown macros breaking lists

- library/Vanilla/EmbeddedContent/Embeds/ErrorEmbed.php
- library/Vanilla/EmbeddedContent/Embeds/QuoteEmbed.php
Making new quotes are broken on master.
This is because the output of the quote APIs being passed in are not nested under `attributes` and don't get transformed properly. I've fixed that.
I also fixed an issue with the `ErrorEmbed` not setting the correct key to `error`. As a result the frontend would attempt to mount over it anyways (and sometimes work). This could cause the styling to get a little messed up.
> Fix broken quoting

- library/Vanilla/Formatting/Quill/Filterer.php
Escaping unicode makes searching for unicode rich posts impossible so leaving it unescaped is necessary. This change requires the database to be utf8mb4 or else emoji will break.
Closes #9076.
> Don’t escape unicode characters when saving the rich format

- library/src/scripts/content/hashScrolling.ts
- library/src/scripts/layout/ScrollOffsetContext.tsx
Visiting a KB page with a hash in the URL would trigger an infinite loop.
It's fixed in this PR, by restructuring a method before passing it in and correcting the triggering conditions for this effect.
Go to a KB article and click on one of the hash links.
Closes vanilla/knowledge#1100
> Fix changing window hash causing infinite loop

- library/core/class.controller.php
- plugins/editor/js/editor.js
This PR adds to the gdn object the current theme's url path. This can be used to import assets from the theme with JS.
> Add current theme url to site meta

- themes/keystone/src/scss/components/_herobanner.scss
The hero image is absolutely positioned in Keystone, but was missing explicit top and left values. IE 11's default is weird, which is why it looked broken on the client's site.
For: https://github.com/vanilla/support/issues/629
> Added explicit top and left positioning to absolute positioned hero image

- plugins/rich-editor/src/scripts/flyouts/EmbedFlyout.tsx
- plugins/rich-editor/src/scripts/toolbars/InlineToolbar.tsx
This PR fixes an issue with the rich editor's embed menu. When pasting a valid URL, it did not validate it properly without a change to the text.
I also took the liberty of setting focus inside the menu, since it's a single action dropdown, we can set the focus there.
Closes: https://github.com/vanilla/support/issues/627
> Fix pasting URL in Rich Editor's embed menu

- applications/dashboard/views/settings/registration.php
**Bug:**
Invitation target was misleading as it had a prefix with the community host suggesting it could only be set with a relative path. Turns out full paths also work as long as they are trusted.
**Fix:**
Removed the prefix.
Issue reported here: https://github.com/vanillaforums/king/issues/179
> Add a fix to dashboard/registration/invitation target field

- library/core/helpers/class.ssoutils.php
Ref. #9120
Presently when connecting using OAuth2 we pass, store and retrieve a state token. If no state token is passed back, we give the error "Invalid State Token" which is misleading since it is not there at all. This PR fixes this problem.
> Give clearer error message when no state token is found.

- applications/vanilla/controllers/api/DiscussionsApiController.php
Closes https://github.com/vanilla/vanilla/issues/8463
It turns out that https://github.com/vanilla/vanilla/issues/8463 was actually an issue and was incorrectly closed.
I've switched the required permission on the `/api/v2/discussions/:id/quote` endpoint to be View instead of Edit. This aligns with the permissions set on the comment quote endpoint.
> Fix permission required for quoting a discussion

- library/Vanilla/EmbeddedContent/Factories/ScrapeEmbedFactory.php
As a result of sending and `OPTIONS` request instead of a `HEAD` request as indicated in the comment, we were never able to properly determine the content-type fo the resource, and would fall back to the HTTP scraper.
> Fix typo breaking image scrape

- library/core/functions.general.php
Some of our javascript looks for “RedirectTo” instead of “RedirectUrl” so I’m adding both to the redirect JSON response.
> Add “RedirectTo” to redirect JSON responses

- applications/vanilla/src/scripts/categories/CategorySuggestionActions.ts
- build/scripts/configs/makeBaseConfig.ts
- library/src/scripts/features/users/suggestion/UserSuggestionModel.test.ts
- library/src/scripts/forms/DatePicker.tsx
- packages/vanilla-eslint-config/index.js
- packages/vanilla-eslint-config/package.json
- plugins/rich-editor/src/scripts/editor/EditorContent.tsx
reduced the size of the minified bundle by ~30%
- `highlight.js` dynamically imported (goes into it's own chunk and only used when needed).
- `moment.js` locales have been filtered down to the most common ones. There's not a great solution at the moment to dynamically import these. If some other date time format ends up being needed we can add it to the whitelist.
- Added a lint rule mandating single lodash imports.
- Removed the full lodash import in `<EditorContent />`.
Relates to: https://github.com/vanilla/knowledge/issues/695
> Reduce JS bundle size through optimized imports

- library/src/scripts/embeddedContent/TwitterEmbed.tsx
- packages/vanilla-dom-utils/src/scripts.ts
Fixes https://github.com/vanilla/support/issues/660
`ensureScript` was resolving immediately if it saw a script already in the header. Unfortunately just having the script existing there doesn't mean it is loaded and has executed.
- Updates `ensureScript` to always attach the `onload` and `onerror` handlers if it has not already.
- Updates `convertTwitterEmbeds()` to remove duplicated check for twitter library. The check in `renderTweet()` has error handling and logging which would have made this easier to track down.
> Fix a bug in twitter embed rendering

- library/Vanilla/EmbeddedContent/Embeds/LinkEmbed.php
- library/src/scripts/embeddedContent/LinkEmbed.tsx
Currently the link embed schema requires the body to parameter.  A link embed's body is built with the content attribute of the page, if that's an empty string it will cause the media scrape to fail and throw a 422 error code.  This relaxes the schema and makes the body parameter optional.
closes vanilla/vanilla#9049
> Allow body parameter to be optional for link embeds

- library/core/class.session.php
This adds the users and sites transient key to the the db logger when there is a csrf failure event.
> Add TK information to csrf failure event

- tests/APIv2/AbstractAPIv2Test.php
Gdn_Format::to() could call `Gdn_Format::rich()` which emits and `E_USER_WARNING` for deprecation. I've switched this call to use the format service to prevent the call to the deprecated method.
Blocking https://github.com/vanilla/knowledge/pull/1127
> Fix deprecated method call in abstract resource test

- library/src/scripts/content/userContentStyles.ts
- plugins/rich-editor/src/scripts/quill/MarkdownModule.test.ts
- plugins/rich-editor/src/scripts/quill/MarkdownModule.ts
Closes https://github.com/vanilla/vanilla/issues/9140
Closes https://github.com/vanilla/vanilla/issues/8917
Closes https://github.com/vanilla/support/issues/655
- Fixes the above issues.
- Offsets the regexed text area to require [left flanking delimiter runs](https://spec.commonmark.org/0.29/#left-flanking-delimiter-run). This greatly reduces the risk of false positives.
- Cuts off the regexed to text to the current cursor position. Macros are now only matched if your cursor is directly at the end of them.
- Takes into accounts inline embeds (such as mentions) which can't be represented easily in plaintext (so `quill.getText()` doesn't handle them).
- Adds unit tests for `MarkdownModule`.
- Adds additional keyboard keys that can trigger various macros. Mostly additional punctuation. See …
> Improve Rich markdown macros and add unit tests

- library/src/scripts/embeddedContent/FormElements.story.tsx
- library/src/scripts/features/users/MultiUserInput.tsx
- library/src/scripts/forms/Checkbox.tsx
- library/src/scripts/forms/CheckboxGroup.tsx
- library/src/scripts/forms/InputBlock.tsx
- library/src/scripts/forms/InputBlockStyles.tsx
- library/src/scripts/forms/RadioButton.tsx
- library/src/scripts/forms/RadioButtonGroup.tsx
- library/src/scripts/forms/checkRadioStyles.ts
- library/src/scripts/forms/select/SelectOne.tsx
- library/src/scripts/forms/select/tokensStyles.ts
Created RadioButtonGroup and CheckboxGroup components. They wrap inputBlock to add appropriate markup and styles.
Got rid of all SASS classes on radio buttons and checkboxes.
Fixed input spacing in advanced search (KB). Some elements didn't have the proper class and were too tight.
Fixed bug with token input. After inputting the first element, the text input would be super small ( 1 or 2 pixels wide). Making it difficult to click back and continue adding text. I also gave a minimum width for the input so it won't ever be too small up against the edge if the tokens happen to take almost a full line.
Companion PR: https://github.com/vanilla/knowledge/pull/1131
> Demo Feedback - Checkbox/Radio button groups, token click target

- applications/vanilla/models/class.commentmodel.php
- applications/vanilla/models/class.discussionmodel.php
- library/Vanilla/Formatting/Quill/Parser.php
- library/core/class.validation.php
- library/core/functions.validation.php
- tests/Library/Vanilla/Formatting/Quill/ParserTest.php
Closes https://github.com/vanilla/vanilla/issues/7290
Closes https://github.com/vanilla/support/issues/691
- Updates the Rich parser to be more robust when given empty values.
- Does better and validation and throws a `FormattingException` when given more types of bad values.
- Falls back to some default value when given "empty" values.
- Add tests for `Quill\Parser::jsonToOperations()`. Also added some missing docblocks in that test file.
- Doing this further exposed https://github.com/vanilla/support/issues/691 so I fixed that too.
- Apply min length validation to Discussions.
- Improve min length validation to properly work on plaintext instead of just stripping tags.
Relevant configuration options that affect this are `Vanilla.Comments.MinLength`, and …
> Improve min length validation and fix rich rendering with empty bodies

- plugins/rich-editor/src/scripts/editor/richEditorStyles.ts
- plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenusBarToggle.tsx
Closes https://github.com/vanilla/knowledge/issues/1137
The direction selection was missing some minimum height check that would cause it to always display the menu in the wrong direction if the the scroll-bounds were particularly short.
I also added a z-index on this menubar so that it would stay above the bottom border when opening on mobile.
> Fix editor paragraph direction

- library/src/scripts/messages/Message.tsx
This PR removes the `<Container />` padding from the `<Message />` component by default. It is still needed for the fixed version however.
Other components are now free to specify their own padding. This is to prevent issue with double padding. https://github.com/vanilla/knowledge/pull/1140 required to place the container in a couple places that need it now.
For example:
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/62953733-0c566280-bdbc-11e9-8f44-3d873bae96a5.png)|![image](https://user-images.githubusercontent.com/1770056/62953648-e466ff00-bdbb-11e9-9d8b-a9e94822061c.png)|
|![image](https://user-images.githubusercontent.com/1770056/62953776-2001c900-bdbc-11e9-8783-c4a2f881ad6a.png)|![image](https://user-images.githubusercontent.com/1770056/62953798- …
> Make <Message /> component padding more flexible

- library/core/class.bbcode.php
- library/core/class.emoji.php
https://github.com/vanilla/vanilla/pull/8980 updated some deprecated event firings to use the event manager. Unfortunately a couple did not properly pass the arguments array.
This is fixed in this PR.
> Fix missing event args

- applications/dashboard/controllers/class.notificationscontroller.php
- library/core/class.format.php
Closes https://github.com/vanilla/support/issues/703
Cleanup from https://github.com/vanilla/vanilla/pull/8980
Prior to https://github.com/vanilla/vanilla/pull/8980 `Gdn_Format::plainText()` and `Gdn_Format::excerpt()` redirected their format through `Gdn_Format::to()` which has explicit null handling.
During the refactoring this was removed causing "No formatter is installed for format" messages if a `null` format was was passed https://github.com/vanilla/support/issues/703
I've added handling of null to these 2 methods, and updated the 1 call-site that was unknowingly passing in null. This both fixes the proper cause of https://github.com/vanilla/support/issues/703 and addresses other potential backwards compatibility issues if there is some other call site doing this.
> Fix notifications rendering with null format
