plugins/rich-editor/src/scripts/quill/MarkdownModule.test.ts, plugins/rich-editor/src/scripts/quill/MarkdownModule.ts
Closes https://github.com/vanilla/vanilla/issues/9187
Our markdown macros were only working properly when completed on the first line. This is because they were only being tested there in our automated tests.
I've updated the tests so that they all run with 3 newlines at the start and updated the module to properly handle these offsets.
=> Fix incorrectly calculated markdown macro offsets & tests

plugins/rich-editor/src/scripts/quill/utility.ts
Closes https://github.com/vanilla/vanilla/issues/9189
Rich editor was crashing while creating a mention inside of an inline code formats. We already restrict mentions inside of block code formats, so I've added an additional restriction there.
=> Prevent editor crash with mention inside of inline code

library/Vanilla/Formatting/FormatService.php, library/Vanilla/Formatting/Formats/WysiwygFormat.php
Fixes https://github.com/vanilla/support/issues/703
The raw format is an alias for `Wysiwyg` in `Gdn_Format`. This commit adds a similar alias for `FormatService`.
=> Fix search result item rendering

library/Vanilla/Formatting/FormatService.php, library/Vanilla/Formatting/Formats/WysiwygFormat.php
Backporting #9191 
> The raw format is an alias for `Wysiwyg` in `Gdn_Format`. This commit adds a similar alias for `FormatService`.
=> Backport: Fix search result item rendering

library/Vanilla/Web/Asset/DeploymentCacheBuster.php, tests/Library/Vanilla/Web/Asset/DeploymentCacheBusterTest.php
Fixes https://github.com/vanilla/support/issues/718
After some recent deployment and discussion with ops, it seems the incrementing behaviour of our grace period increases the chance of conflict in our shared cache bucket.
So with that said, this behaviour is being removed at the insistence of @DaazKu.
=> Remove grace period from the deployment cache buster

applications/dashboard/controllers/api/AbstractApiController.php
Call FormatService::renderHtml instead of deprecated Gdn_Format::to 
same as https://github.com/vanilla/vanilla/pull/9163
=> Use FormatService::renderHtml() on AbstractApiController

applications/dashboard/library/class.emailtemplate.php
Vanilla's plain text emails have been rendering with HTML tags since the recent formatting service improvements were introduced. `EmailTemplate` has been updated to generate HTML that is then converted to plain text using the new formatting service before. This ensures the message is rendering consistently without HTML, as expected.
1. Visit the email settings page of the Vanilla dashboard. Ensure HTML email is **off**.
1. Send a test email.
1. Verify the email you receive is a plain text message with no visible HTML tags. The formatting of the message should also separate all relevant portions onto their own newlines (e.g. the title and the message should be separated by at least one new line).
Closes vanilla/support#719
=> Fix plain text emails rendering with HTML tags

library/src/scripts/redux/ReduxReducer.ts
Blocking https://github.com/vanilla/knowledge/pull/1158
The instance property of this class for initial state was a bit of a mistake.
- This always needs to be defined as a constant anyways so the initializer was unnecessary. 
- It's not possible to have an `static abstract` property in typescript, so I had to remove it rather than make it static.
=> Remove ReduxReducer instance initial state requirement

library/src/scripts/embeddedContent/EmbedErrorBoundary.tsx, library/src/scripts/embeddedContent/EmbedRenderError.tsx, library/src/scripts/embeddedContent/GettyImagesEmbed.tsx, library/src/scripts/embeddedContent/ImgurEmbed.tsx, library/src/scripts/embeddedContent/InstagramEmbed.tsx, library/src/scripts/embeddedContent/TwitterEmbed.tsx, library/src/scripts/embeddedContent/embedErrorStyles.ts, library/src/scripts/embeddedContent/embedService.tsx, library/src/scripts/icons/common.tsx, library/src/scripts/icons/iconClasses.ts, packages/vanilla-react-utils/src/index.ts, packages/vanilla-react-utils/src/useThrowError.ts, plugins/rich-editor/src/scripts/quill/blots/embeds/ExternalEmbedBlot.ts
Closes https://github.com/vanilla/vanilla/issues/7606
The main issue here is that our error handling was at the Blot level, but react was catching the errors before they ever got there. What I've done is:
- Create an `EmbedRenderError` component. This displays the link error.
- Create an `EmbedErrorBoundary` component. This catches the errors thrown in react.
- A new react utility `useThrowError` to make throwing errors from inside of `useEffect` hooks work.
- Update `TwitterEmbed`, `GettyEmbed`, `ImgurEmbed`, and `Instagram` to properly throw an error (previously getting caught in hook, now `useThrowError()` is used.)
=> Fix rich editor embed render error handling

applications/dashboard/js/entry.js, cache/.htaccess, library/core/class.dispatcher.php
closes https://github.com/vanilla/support/issues/726
related https://github.com/vanilla/vanilla-patches/pull/592
When trying to connect over SSO with (Private-communities & Registration not set to basic) users cannot connect.
When inspecting the page, you'll notice this error:
We added this definition https://github.com/vanilla/vanilla/blob/46c27769344e83dd6752cc5bb2b76c765dae3357/applications/dashboard/controllers/class.entrycontroller.php#L79
https://github.com/vanilla/vanilla/blob/c120a36c1f901726f473f3f5bf27e72c1d2b641f/applications/dashboard/js/entry.js#L3
that's supposed to be turning off availability searches if the feature isn't available, but it isn't
In this PR we check if userSearchAvialable is true before we call checkConnectName();
Those availability checks are also updated …
=> Fix user availability search not working on connect registration

applications/dashboard/models/SwaggerModel.php, bootstrap.php, composer.json, composer.lock, library/Garden/ArrayContainer.php, library/Garden/EventManager.php, library/Garden/Web/Dispatcher.php, library/Garden/Web/ResourceRoute.php, library/Vanilla/InteropContainer.php, library/Vanilla/Models/InstallModel.php, library/core/class.gdn.php, library/core/class.pluginmanager.php, tests/Bootstrap.php, tests/Library/Vanilla/VanillaClassLocatorTest.php, tests/TestInstallModel.php, tests/fixtures/src/Container.php
Garden container updates to PSR container which is the same interface as interop container, but with a different name. This presents a challenge in upgrading. I’ve added an adaption object so that we can slowly move other dependencies over to the new PSR container.
The work on this PR was fairly easy with just the adapter class (`InteropContainer`). However, changing container usage throughout the app to PSR container proved to be a bit more difficult as sometimes missing a single item in a dependency would cause site crashing errors. Some care should be taken when removing the interop container from other repos.
Closes #8853.
=> Upgrade to Garden Container 2.0

.circleci/config.yml
This updates the circleci config to use the newly created orbs under the vanilla namespace
Related vanilla/internal#1921
=> Updated config to use new orbs created in Vanilla namespace

index.php
I want to be able to trigger warnings for some things that we plan to change in the future, but are uncertain of the production implications.
This change will send E_WARNING and E_USER_WARNING errors to the log rather than discarding them.
**Note: I added E_WARNING to the list of warnings we report because it seems like the right thing to do, but that may end up being too noisy. I feel like I remember some really dumb things escalating to E_WARNING in PHP, but I just can't remember what.**
=> Set the error reporting to include E_USER_WARNING

library/src/scripts/flyouts/DropDownContents.tsx
Fixes https://github.com/vanilla/knowledge/issues/1165
I added this while attempting to fix some focus stealing issue in contenteditable. It turns out the real solution is what I put in a few lines above this.
I've gone and tested and the alt text UI (that this was added for as a I tested it) and this fixes it.
=> Fix overzealous event propagation stopping in dropdown content

applications/dashboard/settings/class.hooks.php, library/core/class.emoji.php
Emoji suggestions are currently broken. Typing a colon should trigger the emoji suggestion menu in a default install of Vanilla. This is not happening due to [recent revisions to Vanilla's formatting](https://github.com/vanilla/vanilla/pull/8980). Vanilla started instantiating the `Emoji` class earlier for DI. The `Emoji` class had code in it to add its config to the controller's definitions whenever it was instantiated. Since we started instantiating it earlier, there is no controller available at the time.
Having the controller definitions added at the time the class is instantiated is weird. Adding the config to the controller has been moved to `base_render_before` in the Dashboard hooks file. This should be in a place where it's always available and only added when needed.
1. Navigate …
=> Fix emoji suggestions not displaying

applications/dashboard/settings/class.hooks.php, library/core/class.emoji.php
Backporting #9250 to `release/2019.012`
> Emoji suggestions are currently broken. Typing a colon should trigger the emoji suggestion menu in a default install of Vanilla. This is not happening due to [recent revisions to Vanilla's formatting](https://github.com/vanilla/vanilla/pull/8980). Vanilla started instantiating the `Emoji` class earlier for DI. The `Emoji` class had code in it to add its config to the controller's definitions whenever it was instantiated. Since we started instantiating it earlier, there is no controller available at the time.
>
> Having the controller definitions added at the time the class is instantiated is weird. Adding the config to the controller has been moved to `base_render_before` in the Dashboard hooks file. This should be in a place where it's always …
=> Backport: Fix emoji suggestions not displaying

library/Vanilla/EmbeddedContent/EmbedService.php, library/Vanilla/Models/UserFragmentSchema.php, library/Vanilla/PageScraper.php, library/Vanilla/Web/RequestValidator.php, tests/Library/Vanilla/PageScraperTest.php, tests/fixtures/src/MockPageScraper.php
Prepares for https://github.com/vanilla/internal/pull/1956
Fixes https://github.com/vanilla/dev-inter-ops/issues/23
**Breaking the infinite loop**
I've left plenty of inline comments here I think, but the _TL;DR_ is if the embed service was used in a get request (or the page scraper), and someone pointed the scraper to that page, then the site would take itself out pretty quickly in an infinite loop.
I've created a utility to check the request type and throw an exception and applied that to the page scraper and embed service.
Note this breaks the reporting plugin which was recently updating to use the `EmbedService` in a get request (on accident).
I've created an update to the reporting plugin as well to fix this.
**Utility**
I've also added a utility for normalizing user fragments (from …
=> Add class to prevent self scraping and apply to the embed service & page scraper

applications/vanilla/js/autosave.js, applications/vanilla/js/discussion.js
This PR fixes two bugs related to saving drafts when the rich editor is enabled.
1. It fixes incorrect string escaping in autosave.js that causes it to never match rich editor "empty string" markup, and 
2. It aligns empty string matching in discussion.js with the same functionality in autosave.js to fix a bug where it was possible to save empty drafts when rich editor is in use.
When combined, these two bugs allow for empty comments to be autosaved, which quickly fills an active user's drafts index up with empty drafts.
1. With rich editor enabled, carry out all tests below
2. With rich editor disabled, carry out only tests 1, 2, 4, and 5.
1. Write a comment and click 'save draft'
2. Confirm draft has been saved
1. With an empty comment, click 'save draft'
2. Confirm no draft saved
1. …
=> Fix empty comment draft button and autosave behaviour for rich editor (#9198)

index.php
Backporting #9266 to `release/2019.012`.
> TOO LOUD!!!
=> Backport: Remove E_WARNING from error reporting

applications/dashboard/models/class.activitymodel.php, library/core/class.email.php
related https://github.com/vanilla/support/issues/757
This PR adds email logging. 
- Enable DB Logger
- Set $Configuration['Garden']['Email']['Debug'] = true
=> Add email logging

library/src/scripts/features/search/SearchBar.tsx, library/src/scripts/features/search/searchBarStyles.ts
On mobile, the search button was hidden, but the border radius was not applied to the right side of the input.
Closes: https://github.com/vanilla/vanilla/issues/9252
=> Fixed border radius issue for splash's search

composer.json, composer.lock
In particular the bug fix from 3.0.1 was required (See https://github.com/vanilla/garden-container/pull/37)
3.0 was a SEMVER breaking change in that it required PHP 7.1. Since this is already the minimum version for vanilla, there should be no issues.
`garden-http` seems to have some breaking change in it's signature. For now I'm restricting the version of it to `2.0.x` until the break is rectified.
See https://github.com/vanilla/garden-http/issues/22
The rest came from running `composer update`
- Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0)
- Updating symfony/yaml (v3.4.28 => v3.4.31)
- Updating vanilla/garden-http (v2.0.1 => v2.0.2)
- Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0)
- Updating twig/twig (v2.11.2 => v2.11.3)
- Updating sebastian/exporter (3.1.0 => 3.1.1)
- …
=> Bump composer dependencies (particularly garden-container)

build/scripts/utility/EntryModel.ts, library/Vanilla/Web/Asset/LocaleAsset.php, library/Vanilla/Web/Asset/WebpackAddonAsset.php, library/Vanilla/Web/Asset/WebpackAssetProvider.php
- A new common asset is now possible on a per-addon basis (starting with https://github.com/vanilla/vanilla/pull/9246 and [used in multisite](https://github.com/vanilla/multisite/tree/master/plugins/subcommunities/src/scripts/entries)). Make sure these get loaded by the asset provider.
- Prevent `common` from being recognized as it's own section.
- Fix locale asset loading with subcommunities (API endpoints shouldn't have a subcommunity slug).
=> Fix asset loading bugs

library/core/class.router.php
Routes with the # characters like `something#p1` were modifying the request.
Even if the route is "invalid" in the first place, delimiters should be escaped.
=> Escape route regex delimiter

library/src/scripts/styles/styleHelpersBorders.test.ts, library/src/scripts/styles/styleHelpersBorders.ts, plugins/rich-editor/src/scripts/quill/MarkdownModule.test.ts
Fixes https://github.com/vanilla/vanilla/issues/9293
- Fixes the border helper which was creating some corrupted styles (it was trying to merge a string/number/etc with an object).
- Adds some unit tests for the `borders()` utility.
- Removes an `it.only` that was accidentally left in some other tests.
=> Fix embed container styles by fixing style corruption in borders helper

tests/Library/Vanilla/Formatting/DateTimeFormatterTest.php, tests/phpunit.php
This test was set to be isolated to not effect timezone behaviour of other tests in a non-deterministic way.
Unfortunately this massively slows down this suite of tests, so I've opted instead to just move the timezone setting to the phpunit test setup to it applies to all tests evenly, in any order.
=> Move timezone test setup out of DateTime test and into global test setup

library/src/scripts/routing/PageLoader.tsx, library/src/scripts/splash/splashStyles.ts
2 bugs popped up after deploying the latest release.
- Pages weren't scrolling.
- Opacity detection on the splash background caused the background color to bleed in.
=> Fix some post 2019.013 bugs

library/Vanilla/Web/TwigRenderTrait.php
Followup from https://github.com/vanilla/vanilla/pull/9281
This auto-wrapping was too overzealous. It totally breaks the top level template. Renders that want to mark their output as sanitized can manually wrap their string in `new \Twig\Markup()` (already used in a few different places.)
=> Fix double escaping in twig templates

build/.storybook/config.js
Closes https://github.com/vanilla/vanilla/issues/9248
- Adds a slight rendering delay to chromatic to help prevent false positives.
- I found this from an example in the storybook docs: https://github.com/storybookjs/storybook/pull/5943/files
=> Add slight rendering delay for chromatic

library/src/scripts/@types/api/core.ts, library/src/scripts/content/userContentStyles.ts, library/src/scripts/layout/frame/frameBodyStyles.ts
Blocking https://github.com/vanilla/multisite/pull/262
- Fixes some conflicts with the `FrameBody` styles in the dashboard.
- Add a padding reset to user content styles (dashboard doesn't provide one).
- Add an additional generic value to `ILoadable` to allow specifying the error type.
=> Add some frame style fixes in the dashboard and make ILoadable more flexible

applications/dashboard/openapi/schemas.yml, applications/dashboard/openapi/search.yml, applications/dashboard/openapi/users.yml
This is just for docs, but depends on functionality in another repo. It's probably the case that these docs should be moved, but if that's so then that should be done after a deploy cycle.
I also noticed an error in the `UserFragment` schema docs that doesn't agree with our default implementation. It's very possible some addon modifies `UserFragment`, but I would rather we don't *document* that because that doesn't seem like a wise course of action.
=> Add insertUser to /search spec and fix the UserFragment schema docs

library/Vanilla/OpenAPIBuilder.php, library/src/scripts/navigation/SiteNav.tsx, library/src/scripts/routing/RouteHandler.tsx, library/src/scripts/utility/appUtils.tsx, tests/Library/Vanilla/OpenAPIBuilderTest.php, tests/fixtures/src/Request.php
Goes with https://github.com/vanilla/knowledge/pull/1202
Fixes https://github.com/vanilla/internal/issues/1970
Fixes https://github.com/vanilla/support/issues/781
Fixes https://github.com/vanilla/support/issues/551
Fixes https://github.com/vanilla/multisite/issues/219
- Format full URLs in `makeProfileUrl()`.
- Use `<SmartLink />` in `RouteHandler`.
- Have `RouteHandler` wrap it's URLs in `formatUrl()` -> This change required a fix in KB https://github.com/vanilla/knowledge/pull/1202
- Fix a react warning in SiteNav caused by having an unneeded fragment wrapper.
- Fix generation of the OpenApi URL when site is served from a subdirectory (test added).
- Fix our PHP request test fixture having backwards logic about setting a site root.
@tburry has a WIP PR that lets you serve your site out …
=> Fix frontend URL generation when site is served in a subdirectory

library/Vanilla/Web/LegacyTwigViewHandler.php, library/src/scripts/splash/Splash.tsx
The `outerBackgroundImage` prop was not being used in the component. This occurred during the refactor to use `styleOverwrite`.
This led to the prop not being updated in the help center home page here causing this bug. https://github.com/vanilla/knowledge/issues/1186
- Clean up `<Splash />` style overwrite (and remove unused prop).
- Fix a random PHP notice I found.
- Actual bug fix in this PR https://github.com/vanilla/knowledge/pull/1187
=> Remove unused`<Splash />` property & fix PHP notice

library/Vanilla/Web/Asset/WebpackAssetProvider.php
The locales asset is critical for development a multilingual feature, but do to some sloppy logic here it wasn't being include when the hot build was enabled.
I've fixed that.
=> Fix locale asset not being include in hot build

applications/dashboard/views/components/dashboardHeading.twig, library/core/functions.render.php, tests/Library/Core/RenderFunctionsTest.php
Followup to https://github.com/vanilla/vanilla/pull/9314
During routine testing a notice a couple issues with the refactoring:
- The back arrow and button container was always appearing (I've switch the if statement in the template to fix this).
- The title wasn't being unnecessarily escaped. In the previous implementation, the title could container HTML (see the `/settings/swagger` page for an example).
I've fixed these and added some rendering tests for the old `heading()` function.
=> Fix heading rendering and add tests

.circleci/scripts/diff-standards.sh
Working towards https://github.com/vanilla/vanilla/issues/9254
Our `diff-standards.sh` script only worked if the repository root was also the CWD and the repository was the vanilla repository.
I've updated the script to make it properly resolve relative directories. This allows it to be called and used on another repo.
Eg.:
```sh
./vanilla/.circleci/scripts/diff-standards.sh master ~/srv/internal/
```
=> Update diff-standards to work in non-pwd directory

applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php
Vanilla's notification system is beginning to undergo an overhaul. Instead of doing this in one giant leap, we're taking small incremental steps. This particular step moves notification logic outside post save methods and into dedicated methods on the model. This is done so that when the new notification system is introduced, changes can confidently be made without affecting the rest of the record's save routine. For the sake of simplifying future updates, the process behind generating notifications has been normalized between the comment and discussion models. Previously, each had their own way of handling notifications.
No functional changes have been introduced. Notifications should function the same as they currently do.
Closes #9285
=> Extract post notifications into dedicated methods

library/Vanilla/Formatting/Quill/BlotGroup.php, library/Vanilla/Formatting/Quill/BlotGroupCollection.php, library/Vanilla/Formatting/Quill/Blots/AbstractBlot.php, library/Vanilla/Formatting/Quill/Blots/Lines/ListLineTerminatorBlot.php, library/Vanilla/Formatting/Quill/Nesting/InvalidNestingException.php, library/Vanilla/Formatting/Quill/Nesting/NestableItemInterface.php, library/Vanilla/Formatting/Quill/Nesting/NestingParentInterface.php, library/Vanilla/Formatting/Quill/Nesting/NestingParentRendererInterface.php, tests/fixtures/formats/rich/lists/input.json, tests/fixtures/formats/rich/lists/output.html, tests/fixtures/formats/rich/lists/output.txt
Closes https://github.com/vanilla/vanilla/issues/9216
- Adds improved test cases related to nested lists for the rich renderer.
- Adds new interfaces related to nesting blots and groups. `NestableItemInterface`, `NestingParentInterface`, and `NestingParentRendererInterface`.
- Nested items now live on the `Blot` instead of the `BlotGroup`. This is so that order of blots can be preserved. Previously all nested items would render at the end of their group. In some use cases they can actually be rendered in the middle.
- Ensure `RichFormat::renderPlainText` renders nested list items.
- Add methods for merging groups together.
=> Make nested list rendering for RichFormat more robust

library/Vanilla/Web/JsInterpop/ReduxActionPreloadTrait.php, library/Vanilla/Web/Page.php, resources/views/error.twig
Closes https://github.com/vanilla/knowledge/issues/1153
- Fixes a twig template error in the error SEO view.
- Catches exceptions in `ReduxActionPreloadTrait` and converts them to a `ReduxErrorAction`.
=> Fix Vanilla\Web\Page error handling with redux preloads

applications/dashboard/library/Jobs/ExecuteActivityQueue.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php
Post notifications are currently queued up and sent in the middle of the request, after the post has been saved and before the post is rendered. This update moves executing of the `ActivityModel` queue, which includes post notifications, to the local scheduler. This scheduler processes its own queue after the response has been sent to the client. The intent is to remove sending notifications as a blocking operation for responses.
This is the first use of the scheduler, introduced into Vanilla via #9290.
Make sure you've enabled the deferredNotifications feature flag in your config (`Feature.deferredNotifications.Enabled` set to `true`).
The only functional change here should be the order in which notifications are sent. To test, you can add a high-interval …
=> Add deferment of post notifications

library/Vanilla/Models/ThemePreloadProvider.php
Closes https://github.com/vanilla/support/issues/836
- Create a theme with directory name `not-theme-a`.
- Set the theme key in the `addon.json` or `about.php` file to `theme-a`.
- Set the sites current theme to `theme-a`.
- Visit any page.
- See the infinite loop and subsequent max nesting depth or OOM error.
I've wrapped our theme fetching in a catch statement, and am ensuring all functions return some default value if that could not be found. I'm then triggering a warning if the theme doesn't match.
=> Fix infinite loop in theme preload

library/src/scripts/theming/loadThemeFonts.ts
I turned on one of the test themes I made for the KB and noticed it crashed when no fonts were defined. I added an extra check to avoid the crash.
=> Fix error in font loader when no fonts are loaded

applications/vanilla/models/class.discussionmodel.php
Adding a utility method to the DiscussionModel to be used to prevent double encoding data.
Blocking https://github.com/vanilla/internal/pull/1995
=> Add fix rows method to discussion model

applications/dashboard/models/class.activitymodel.php
Fixes https://github.com/vanilla/support/issues/791
This PR adds a fallback URL to activity if no route is specified. This URL is the single item activity view, `/activity/item/:id`.
=> Fix activity URL generation when no route is specified

library/Vanilla/Web/JsonView.php, library/Vanilla/Web/WebLinking.php
I noticed some tests failing because the WebLinking is a property of JsonView and doesn’t get cleared from test to test. This wasn’t the intent of view objects as they are meant to me more view renderers.
This fix just makes the web linking a convenience object within the render.
The change isn’t without risk since there is the possibility that other functionality depends on adding links to the header via the web linking property. If we find anything like that I would rather they add link headers directly to the response rather than polluting the renderer.
=> Fix header link corruption in JsonView

applications/vanilla/controllers/class.discussioncontroller.php
The `setField` function from the discussion model is a wrapper for `Gdn_Model::setField` which fires the `AfterSetField` event.
By replacing the `setProperty` call by `setField`, it is possible to hook into the AfterSetField event after a discussion is announced (or un-announced). Both functions are used to update an existing records and produce the same results.
=> Use setField instead of setProperty to announce discussions

applications/dashboard/views/settings/registration.php
closes https://github.com/vanilla/vanilla/issues/9273
This PR adds a description and a placeholder for "Invitation Target" under "/dashboard/settings/registration".
Go to /dashboard/settings/registration
Change registration method to "Invitation" 
I'll add the translation key in a separate PR.
=> Add missing invitation target placeholder & description

library/Garden/JsonFilterTrait.php, library/Garden/Web/Data.php, library/Vanilla/Attributes.php, tests/Library/Vanilla/AttributesTest.php
The `Attributes` class is meant to properly JSON encode object-like data, but was not handling date/time objects properly, nor IP addresses.
This fix grabs functionality from the `Data` class into a trait that can be used by both classes. I cut/pasted the methods into the traits rather than using a refactoring tool.
=> Fix Attributes JSON encoding for special data types

applications/vanilla/models/SearchRecords/SearchRecordTypeComment.php, applications/vanilla/models/SearchRecords/SearchRecordTypeDiscussion.php, applications/vanilla/models/SearchRecords/SearchRecordTypeProvider.php, applications/vanilla/settings/class.hooks.php
Move `SearchRecordTypeProvider` together with `SearchRecordTypeDiscussion` and `SearchRecordTypeComment` to the core forum application Vanilla namespace
Relates to : https://github.com/vanilla/internal/issues/2003
=> Add SearchRecordTypeProvider to core Vanilla namespace

applications/dashboard/views/entry/signout.php, library/Vanilla/Web/CacheControlMiddleware.php, library/core/class.controller.php, library/core/functions.general.php
Fixes https://github.com/vanilla/vanilla/issues/9374
302 redirects are temporary and should have no cache headers.
Upon investigation I found we were not actually sending any additional headers when return 302 redirects.
- Ensure `CacheControlMiddleware::NO_CACHE` is sent for 302 redirects.
- Make sure `safeHeader` is used in `CacheControlMiddleware`. Not really sure if there would be an issue without it, but I don't know all the contexts, `redirectTo()` might be called.
During testing I found the signout view actually doesn't work with `DeferredLegacyScripts` on. Updating this minor script to not rely on jquery fixes it though.
- Update the middleware itself to send the vary header. This was causing pages using the new controller that redirect to signin to not invalidate properly after …
=> Fix caching of temporary redirects

library/Vanilla/Formatting/Quill/BlotGroupCollection.php, tests/Library/Vanilla/Formatting/Formats/RichFormatTest.php, tests/fixtures/formats/rich/list-embed/input.json, tests/fixtures/formats/rich/list-embed/output.html
Fixes https://github.com/vanilla/vanilla/issues/9324
- Adds minimal failing test case.
- Fixes some parsing logic in the blot group collection. Blots that don't extend `AbstractLineTerminatorBlot` can still clear a group w/ their `shouldClearCurrentGroup()` method. In this case our embed blot needs to clear the current group.
- Since this test case requires an image embed, I needed to register the image embed with the embed service in the test setup.
=> Fix list embed rendering issue

plugins/rich-editor/src/scripts/quill/utility.test.ts, plugins/rich-editor/src/scripts/quill/utility.ts
Fixes https://github.com/vanilla/knowledge/issues/1171
- Adds failing test.
- Fixes the test by excluding links when trying to get a mention range.
It's illegal to try and insert a link (mention) inside of another link. We already have a few excluded blots for mentions, so I've added link to the list
=> Fix mention crash and add tests

bootstrap.php, library/setup/ComposerHelper.php
The twig caching wasn't being cleared ever. This could cause in issues in future deploys when if the twig cache wasn't properly cleared.
- Fix cache directory (typo).
- Add cache clearing in composer helper.
- An extra bit of cleanup has been added to clear twig cache directories that might have been created in the wrong place.
=> Fix twig file caching

library/setup/ComposerHelper.php
It turns out the initial implementation wasn't robust enough. I've updated it and tested with full cache folders.
=> Fix ComposerHelper delete recursively method

applications/dashboard/controllers/api/LocalesApiController.php, applications/dashboard/openapi/locales.yml, bootstrap.php, library/Vanilla/Models/LocalePreloadProvider.php
Blocking https://github.com/vanilla/knowledge/issues/1240 and https://github.com/vanilla/knowledge/issues/1233
- Adds an index endpoint to the `/api/v2/locales` endpoint.
- Lists all enabled locales and their translations.
- This API endpoint will remove the need for the expand `locales` param on the [subcommunities API](https://github.com/vanilla/multisite/blob/master/plugins/subcommunities/controllers/Api/SubcommunitiesApiController.php#L181-L202) these names are required even when that plugin is disabled.
=> Add index endpoint to the locales API

library/src/scripts/redux/getStore.ts, library/src/scripts/redux/reducerRegistry.ts, library/src/scripts/styles/styleUtils.ts, library/src/scripts/theming/getThemeVariables.ts, library/src/scripts/theming/loadThemeFonts.ts
Historically we have been very picky about the order/when redux reducers are configured.
The previous rule, which was enforced in the code was that you were not allowed to register a reducer after the store had been fetched.
There is no longer any need for this. With the latest version of redux (which we are using), the store provides a `replaceReducer` that lets us add extra reducers at any time.
- I've remove all checks that the store has already been fetched/onReady called.
- Remove `getDeferredStoreState()` which is no longer necessary. Usages have been fixed.
- Update our reducer registrations to replace reducers including all dynamic reducers. This is implemented similar to [this example from the redux documentation](https://redux.js.org/recipes/code-splitting#defining-an-injectreduc …
=> Allow truly dynamic redux reducers

library/package.json, library/src/scripts/AppContext.tsx, library/src/scripts/bootstrap.ts, library/src/scripts/locales/localeActions.ts, library/src/scripts/locales/localeBootstrap.ts, library/src/scripts/locales/localeReducer.ts, library/src/scripts/redux/reducerRegistry.ts, library/src/scripts/utility/appUtils.test.ts, library/src/scripts/utility/appUtils.tsx, packages/vanilla-i18n/package.json, packages/vanilla-i18n/src/LocaleDisplayer.tsx, packages/vanilla-i18n/src/LocaleProvider.tsx, packages/vanilla-i18n/src/index.ts, packages/vanilla-i18n/src/localeStore.ts, packages/vanilla-i18n/src/translationStore.test.ts, packages/vanilla-i18n/src/translationStore.ts, packages/vanilla-i18n/tsconfig.json
Blocking https://github.com/vanilla/knowledge/issues/1240
Companion PR to remove duplicate code from subcommunties https://github.com/vanilla/multisite/pull/280
We currently have most our localization stuff locked up into our subcommunities plugin. However we have parts of front-end that need to display available locales, even without using subcommunities. As a result I've decouple some stuff out of there and placed it the `@vanilla/i18n` package here.
Notably this package now includes:
- A locale context in React.
- Provides utility method `useLocaleInfo()`. Returns available locales, display names, and the current locale.
- A `<LocaleDisplayer />` component for displaying a locale in the language of another given locale.
This package is configured in our bootstrapping & can fetch its …
=> Implement locale utilities using /api/v2/locales endpoint in @vanilla/i18n package

library/core/class.configuration.php, tests/Library/Core/GdnConfigurationTest.php
Closes https://github.com/vanilla/support/issues/850
Our `touchConfig` method was not accounting for config values that were set to false, 0, `""`, null, or `[]`.
I've added a new method `configKeyExists()` which is mostly a duplicate of `get()` but checks handles these edge cases.
I've also added tests for the `configKeyExists`, `get`, and `touch` methods.
=> Fix touch config from overriding falsy values

applications/conversations/openapi/conversations.yml, applications/conversations/views/messages/conversations.php
Closes https://github.com/vanilla/support/issues/866
- The conversations page was calling `FormatService::renderExcerpt()`, which does not allow null parameters, even when it had no message.
- I've moved the check for an empty message before rendering the excerpt.
- Fixed a missing parameter in the POST endpoint's OpenApi definition.
=> Fix excerpt rendering with empty conversations

library/core/helpers/class.ssoutils.php
Backport: https://github.com/vanilla/vanilla/pull/9356
It became apparent that this PR was necessary when debugging a customer's SSO when the State token failed to verify. It is not a good practice to expose the details of every error when it comes to user authentication for fear of giving hackers too much knowledge. This PR uses the Logger class to update the Event Log with details of why a State token has failed to be verified.
=> Backport: Track errors related to the state token.

applications/dashboard/src/scripts/tables/DashboardMediaItem.tsx, library/Vanilla/Contracts/Site/SiteSectionInterface.php, library/Vanilla/Contracts/Site/SiteSectionProviderInterface.php, library/Vanilla/Site/DefaultSiteSection.php, library/Vanilla/Site/SingleSiteSectionProvider.php, library/Vanilla/Site/SiteSectionSchema.php, library/src/scripts/icons/common.tsx, tests/fixtures/src/MockSiteSection.php
- Updates the `SiteSectionInterface::getSectionID()` to return a string. `SubcomunitySiteSection::getSectionID()` was returning always a string which caused an error on access.
- Add `JsonSerialize` to the interface.
- Add a `SiteSectionSchema` with a utility for json serialization.
- Add a new provider interface method `getForSectionGroup()`.
- A couple minor tweaks in some frontend files.
Multisite PR to update interface implementations https://github.com/vanilla/multisite/pull/284
=> Prepare site section interface to allow expansion in API responses

applications/conversations/openapi/conversations.yml, applications/conversations/views/messages/conversations.php, library/core/class.configuration.php, tests/Library/Core/GdnConfigurationTest.php
Backport #9388 Ticket https://github.com/vanilla/support/issues/850
Backport https://github.com/vanilla/vanilla/pull/9396 Ticket https://github.com/vanilla/support/issues/866
=> [Backport] Fix touch config from overriding falsy values & fix excerpt rendering on empty conversations

applications/vanilla/models/class.commentmodel.php
Some parts of `CommentModel` were refactored in #9329 for the sake of preparing the notifications routine for improvements. Part of that refactoring caused "participating" users not to receive notifications, when they had explicitly opted into them. This was due to treating the result of `DiscussionModel::getParticipatedUsers` like an array, instead of an instance of `Gdn_Dataset`. This has been corrected.
A minor formatting issue has also been corrected.
=> Fix notifications not being sent to participating users

applications/vanilla/models/class.commentmodel.php
Backporting #9406 to `release/2019.014`
> Some parts of `CommentModel` were refactored in #9329 for the sake of preparing the notifications routine for improvements. Part of that refactoring caused "participating" users not to receive notifications, when they had explicitly opted into them. This was due to treating the result of `DiscussionModel::getParticipatedUsers` like an array, instead of an instance of `Gdn_Dataset`. This has been corrected.
>
> A minor formatting issue has also been corrected.
=> Backport: Fix notifications not being sent to participating users

composer.lock
The htmLawed version in composer.lock has been updated to v2.2.5, the current release.
=> Upgrade htmLawed to v2.2.5

applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php
Vanilla supports including post contents in comment and discussion notifications. This is currently optional, but moving forward with improvements to notifications, this will be required to give adequate context for email notifications.
Merging into a feature branch for batching email notifications.
Closes #9309
=> Add body to comment and discussion notifications

library/Vanilla/Utility/Deprecation.php, library/core/class.configuration.php
- Adds some additional logging utility `unsupportedParam()`
- Shows message, param, and stack trace.
- Stack depth is configurable.
- Throws an error if debug is enabled.
- Fixes some undefined behaviour when splitting string keys in `Gdn_Configuration::get($name)`. Name is not guaranteed to be a string but `splitConfigKeys` requires one. A type cast and logging has been added.
=> Fix bad type cast in Config::splitConfigKey() & add logging

library/core/class.configuration.php, tests/Library/Core/GdnConfigurationTest.php
It turns out `Gdn_Locale` uses a `Gdn_Locale` internally and `""` is definitely a valid value to pass in.
I've added a test and removed the logged warning that this is "undefined" behaviour potentially.
=> Remove logging for empty config keys

library/core/class.session.php
Recent changes made to Session Stash feature created a subtle bug by not putting the sessionID back into the session array. This PR will put it back.
The code before was like this:
```
if (!$session) {
$sessionID = betterRandomString(32);
$session = [
'SessionID' => $sessionID,
'UserID' => Gdn::session()->UserID,
'DateInserted' => Gdn_Format::toDateTime(),
'Attributes' => [],
];
// Save the session information to the database.
$sessionModel->insert($session);
```
We would generate a SessionID and insert it into the DB and then return the $session array. Now we use the SessionModel which returns the SessionID, but we aren't putting that sessionID back into the $session array before returning it.
This PR will fix it.
Clear your session table, clear your cookies. Do some functionality that …
=> Fix session stash not having a sessionID.

library/core/class.session.php
Recent changes made to Session Stash feature created a subtle bug by not putting the sessionID back into the session array. This PR will put it back.
The code before was like this:
```
if (!$session) {
$sessionID = betterRandomString(32);
$session = [
'SessionID' => $sessionID,
'UserID' => Gdn::session()->UserID,
'DateInserted' => Gdn_Format::toDateTime(),
'Attributes' => [],
];
// Save the session information to the database.
$sessionModel->insert($session);
```
We would generate a SessionID and insert it into the DB and then return the $session array. Now we use the SessionModel which returns the SessionID, but we aren't putting that sessionID back into the $session array before returning it.
This PR will fix it.
=> Backport: Fix session stash not having an ID.

applications/vanilla/controllers/class.discussioncontroller.php
A change was made recently to use setField in the announce function of the DiscussionController. This tweak ended up breaking announcements.
This PR revert the change made in https://github.com/vanilla/vanilla/pull/9353 to use setProperty instead of setField 
Issue: https://github.com/vanilla/support/issues/890
=> Use setProperty instead of setField to announce discussions

applications/dashboard/modules/class.userbanmodule.php
I would rather expand strings as little as possible because it hinders localization and can introduce XSS more easily. Also, we use “corresponding” here and “matching” in the dashboard which is inconsistent.
=> Tweak the ban rule search text

library/Vanilla/Web/JsInterpop/ReduxErrorAction.php, library/Vanilla/Web/Page.php
Working towards https://github.com/vanilla/knowledge/issues/1216
Used in https://github.com/vanilla/knowledge/pull/1296
- Update the `Vanilla\Web\Page::handleException()` to only call rendering of the base master view & not the overridden full rendering. Handling an exception should be as short & container a process as possible.
- Update the `Vanilla\Web\Page::hasExceptionHandler()` to handle all `Vanilla\Web\HttpExceptions`.
- Update `ReduxErrorAction` to not pass null values of description. The frontend has it's own fallback descriptions that will display if the value is undefined.
=> Improve error handling in new controllers

applications/dashboard/controllers/class.profilecontroller.php, library/core/class.controller.php
This is a backport of https://github.com/vanilla/vanilla-patches/pull/645
In the Edit Profile page you can add any of the possible form values that are not displayed or are disabled and submit them. The model does not filter them. This will filter out the values in the controller on submission.
The controller already handles this with the Name field.
=> Backport: Fix updating email addresses when not allowed .

applications/vanilla/views/vanillasettings/editcategory.twig
There were some errors in this page in debug mode (mostly due to undefined varaible access).
These were not errors with debug mode off.
I've fixed them so the template now renders properly in debug mode.
Go to the category add page in the dashboard with debug mode on.
=> Fix debug mode template errors in category settings view

applications/dashboard/openapi/search.yml
Addressing https://github.com/vanilla/support/issues/894#issuecomment-544541309
I know it's not ideal to put these here, but we already have groups in this spot.
On top of that this endpoint doesn't even belong to dashboard, but I'll leave that for another PR.
=> Add answer and poll to search type docs

applications/dashboard/views/entry/registerinvitation.php
This makes the invitation registration mirror the other registration methods. Closes https://github.com/vanilla/support/issues/568.
=> Add the password requirements text to the invitation form

library/core/class.request.php, tests/fixtures/src/MockSiteSectionProvider.php
Adjust `getSimpleUrl` method of `Gdn_Request` with `assetRoot` (when set)
Relates to: https://github.com/vanilla/vanilla/pull/9432 , https://github.com/vanilla/knowledge/pull/1299 
Closes: https://github.com/vanilla/vanilla/issues/9410
=> Adjust getSimpleUrl method of Gdn_Request with assetRoot

applications/vanilla/controllers/api/CommentsApiController.php
related https://github.com/vanilla/internal/pull/2031
closes https://github.com/vanilla/support/issues/777
When creating a comment inside a discussion inside a group and then trying to get the discussion's comment using api/v2/
with api/v2/comments?discussionID= you get this permission error.
The reason this works for /discussion and not /comment is because
We're overriding group permissions when making an api/v2/discussions call, we check if the user can view the group then we set 'Vanilla.Discussions.View' on the category. However, we haven't implemented that for /comments
It could be a feature request to do the same for /comments. We will have to discuss it with Todd.
[class.hooks.php#L955](https://github.com/vanilla/internal/blob/master/applications/groups/settings/class.hooks.php#L955 …
=> add group discussion permission-override to comments api

library/Vanilla/Models/SiteMeta.php, library/Vanilla/Models/ThemePreloadProvider.php, tests/Bootstrap.php, tests/fixtures/src/MockSiteSectionProvider.php
Blocking https://github.com/vanilla/knowledge/pull/1296
**SiteMeta**
- No longer requires a `Gdn_Locale`. It pulls it's locale from the current site section.
- No longer requires a theme. The theme can now be null (common in a test or partiality initialized site.) `ThemePreloadProvider` now has some handling of a null theme value as well.
**MockSiteSectionProvider**
- `MockSiteSectionProvider::fromLocales()` now returns a full provider instance. It is no longer called automatically in the constructor. This allows other tests to use their own site sections. `Bootstrap` has been updated to accommodate this.
- It now uses the default site section.
- Added methods for pushing extra site sections.
- Implement `getForLocale()`, `getByBasePath`, `getForID()`.
=> Improve SiteSection and MockSiteSectionProvider for tests

applications/vanilla/controllers/api/CommentsApiController.php
related https://github.com/vanilla/vanilla/pull/9454
similar to the referenced issue, api/v2/comments/commentid would also return a 'Vanilla.Discussions.View' permission error.
This PR calls commentsApiController_getFilters to update the 'Social Groups' category permission.
api call api/v2/comments/commentid
=> add getFilters to comments api

applications/vanilla/models/class.discussionmodel.php
This was uncovered when I saw a deprecated notice.
=> Fix typo in discussion model

.github/stale.yml
I want us to be able to manually add a “Won’t Fix” label, butt that doesn’t play nice with stalebot so I am giving it its own label.
=> Change the “Status: Won’t Fix” label to “Status: Stale”

library/Vanilla/AddonManager.php, tests/Library/Vanilla/AddonManagerTest.php
The calls to the static `Logger` methods sneaks a dependency into the AddonManger and was causing certain tests to fail.
=> Remove dependencies from AddonManager

plugins/rich-editor/src/scripts/editor/EditorContent.tsx, plugins/rich-editor/src/scripts/editor/richEditorStyles.ts, plugins/rich-editor/src/scripts/editor/richEditorVariables.ts
The pilcrow icon and the placeholder were not aligned with the text. This PR fixes that issue.
Companion PR: https://github.com/vanilla/knowledge/pull/1309
=> Rich Editor Placeholder Alignment

library/database/class.mysqldriver.php, library/database/class.sqldriver.php, tests/Library/Database/MySQLDriverTest.php
We were logging a deprecation warning which was filling up logs on certain servers. Furthermore, the deprecation warning was wrong because the method isn’t deprecated; just one code path was deprecated.
That being said, it shouldn’t really be an error to pass an empty array to a “in” clause. This change cleans up the logic a bit to just make the empty set cases a truthy or falsey expression rather than the `(null)` set.
I added some basic functional tests for the generated SQL. These will provide a good basis if there are any bugs found with this code.
=> Remove Gdn_SqlDriver::_whereIn() empty set deprecation

applications/dashboard/library/Jobs/ExecuteActivityQueue.php, applications/dashboard/models/ActivityEmail.php, applications/dashboard/models/class.activitymodel.php, library/core/class.email.php, library/core/class.request.php
Introducing sending notifications in fewer emails. Users having the same notification regarding the same record will be lumped into email messages as BCC recipients in batches. The default is fifty per message, but this is configurable via the `Garden.Email.BatchSize` key. Users are grouped on emails based on the notifications sharing the following: activity type, record type, record ID, subject and body. If all these align, emails are reused for up to X users.
This functionality is currently only implemented behind the `deferredNotifications` feature flag. You should need to enable this to see the batch-sending of notification emails. If you observe the behavior without this feature enabled, something has gone wrong. No functional changes should be observed in notifications when …
=> Add support for batch sending of notification emails

applications/dashboard/models/class.usermodel.php, bootstrap.php, library/Vanilla/Contracts/Models/FragmentProviderInterface.php, library/Vanilla/Contracts/Models/UserProviderInterface.php, tests/Bootstrap.php, tests/MinimalContainerTestCase.php, tests/fixtures/src/Models/MockUserProvider.php
With this new mock, we can now write unit tests against stuff that depends on user record/expansion without needing the a real DB for the actual `UserModel`.
- Add `Contracts\Models\UserProviderInterface`
- Expands users.
- Get user fragments by ID.
- Update `\UserModel` to implement this interface.
- These are **new methods** that call out to old ones & do a little cleanup. The new methods don't have weird/unneeded parameters like the base user model, and doesn't have any 
- Main application `bootstrap.php` and the test `Bootstrap` class have been updated with a definition for the interface/implementation.
- Add's a `MockUserProvider` that is configurable with fake users. No DB connection.
- Configured automatically in the container setup of `MinimalContainerTestCase`
=> Add UserProviderInterface & MockUserProvider

library/core/functions.general.php, tests/Library/Core/UserAgentTypeTest.php
The device detection library we use can return a string of “mobile;tablet”. In the past, we’ve modified that to return just “tablet”. This seems to be prone to regressions so I’m hardening the detection on the app-side.
Closes https://github.com/vanilla/support/issues/58.
=> Fix device detection for multiple device types

.github/stale.yml
It turns out we didn’t really have any stale issues older than 2 years. Right now there are about 2 pages of stale issues older than a year.
=> Decrease stale.yml to 1 year

applications/dashboard/controllers/class.entrycontroller.php, library/core/class.dispatcher.php, library/core/class.gdn.php, library/core/class.request.php
I did a test to see how far off our request class is from the PSR-7 `ServerRequestInterface` and it turns out that `withURI()` is the only method that has a signature mismatch.
I am temporarily deprecating the method now to give us time to update our other code without having to do too much coordination.
=> Deprecate Gdn_Request::withURI() to start working towards PSR-7 support

applications/vanilla/views/vanillasettings/editcategory.twig
Fixed logic in edit category template, it was crashing when creating a new category.
=> Fixed logic in edit category template

library/database/class.database.php
Add supports for database connection smoothness.
In the case that the connection cannot be done because a resources limit is reached (max connections, max user connections, user limits) we loop up to `SmoothTimeoutMillis` milliseconds and we retry the connection.
Every try sleeps for a random amount of time between SmoothWaitMinMillis & SmoothWaitMaxMillis and then attempts a new connection.
The defaults value are:
SmoothTimeoutMillis = 5000
SmoothWaitMinMillis = 250
SmoothWaitMaxMillis = 750
These values can be overwritten via Gdn::config('Database')
In the `query` method, the connection to the database was moved outside of the retry loop. Otherwise, the connection smoothness would be also influenced by the retry configuration.
=> Adds database connection smoothness

library/core/class.router.php, tests/APIv2/AbstractAPIv2Test.php, tests/BootstrapTrait.php, tests/Library/Core/RouterTest.php
Routes haven’t been stored as serialized arrays since I think 2016, but we have this BC code in there. I am at least hardening it to not allow objects.
=> Don’t allow classes for serialized routes

library/src/scripts/AppContext.tsx, library/src/scripts/contexts/SearchFilterContext.tsx, library/src/scripts/forms/select/SelectOne.tsx
- Adds a pluggable context search context provider to be used in https://github.com/vanilla/multisite/pull/297
- Provider holds different query params and components per search domain.
- Set up the context provider in it's core.
- Update `<SelectOne />` to propagate an `isClearable` prop to the underlying select.
=> Add pluggable search filter context provider

applications/dashboard/settings/class.hooks.php, conf/constants.php, environment.php, library/Vanilla/Models/InstallModel.php
In anticipation of the most wonderful time of the year when we upgrade our version requirements, I’m trying to consolidate the places that need to be updated to as few files as possible.
This change:
1. Moves our version requirement to the earliest version check in `environment.php`.
2. Makes use of the constants whenever version checking.
3. The dashboard warning has different logic now. It makes use of a new `ENVIRONMENT_PHP_NEXT_VERSION` constant to warn people when they are below the next version of PHP.
=> Centralize PHP version checks

library/core/class.oauth2.php
Use the DateTimeImmutable class to create the expiry time for stashed sessions.
This is a follow up to this PR: https://github.com/vanilla/vanilla-patches/pull/636 in response to this issue: https://github.com/vanilla/support/issues/840
=> Use DateTimeImmutable to create timestamps for OAuth2 class.

applications/vanilla/views/categories/helper_functions.php
Two things:
- The most recent date used “most recent by user on date”. If the date is formatted as just a time then it should be “at”. This would be very tedious to determine with localization so I opted just to remove the word “on” entirely.
- The category list displays the date twice. I added an option to remove it from the string.
Closes https://github.com/vanilla/support/issues/30.
Closes #7252.
=> Fix date grammar on category list

plugins/GooglePlus/addon.json, tests/APIv2/AddonsTest.php
This PR set Google+ plugin to hidden as requested in https://github.com/vanilla/vanilla-patches/issues/642
=> Set Google+ plugin to hidden

library/core/functions.validation.php, tests/Library/Core/ValidateUsernameTest.php
It is currently possible to add custom validation on usernames by adding the "ValidationRegex" and "ValidationLength" configs to the configuration file. The "ValidationRegex" is wrapped in a character class which makes the functionality very rigid.
For example, it is impossible to do negative look-around to prevent usernames from starting with a certain pattern.
The change was discussed in [this internal issue](https://github.com/vanillaforums/estimates/issues/708)
It will now be possible to add "ValidationRegexPattern" to your configuration file and write the full regular expression without any restrictions. This pattern will have priority on the other (ValidationRegex, ValidationLength) configurations.
=> Add full regular expression patterns support for username validation

applications/dashboard/models/class.messagemodel.php, applications/dashboard/models/class.permissionmodel.php, library/Vanilla/Formatting/UpdateMediaTrait.php
Thanks to #9439 some workarounds from the past can now finally be removed.
=> Remove Gdn_SQLDriver::whereNotIn workarounds

applications/conversations/views/messages/all.php
Found an old typo in messages/all, where it tries to count a boolean.
`count(): Parameter must be an array or an object that implements Countable`
=> Fix typo in messages/all view

applications/dashboard/models/class.searchmodel.php, applications/vanilla/models/class.vanillasearchmodel.php
Closes
Search model generates sql query like:
```
select *
from (
select d.DiscussionID as `PrimaryID`, d.Name as `Title`, d.Body as `Summary`, d.Format as `Format`, d.CategoryID as `CategoryID`, d.Score as `Score`, concat('/discussion/', d.DiscussionID) as `Url`, d.DateInserted as `DateInserted`, d.InsertUserID as `UserID`, 'Discussion' as `RecordType`, d.Type as `Type`
from `GDN_Discussion` `d`
where (d.Name like '%some text to search%'
or d.Body like '%some text to search%')
and `CategoryID` in (...)
union all
select c.CommentID as `PrimaryID`, d.Name as `Title`, c.Body as `Summary`, c.Format as `Format`, d.CategoryID as `CategoryID`, c.Score as `Score`, concat('/discussion/comment/', c.CommentID, '/#Comment_', c.CommentID) as `Url`, c.DateInserted as `DateInserted`, c.InsertUserID as …
```
=> Optimize search query when 'union all' is in use

applications/dashboard/controllers/api/AbstractApiController.php, applications/vanilla/controllers/api/DiscussionsApiController.php, applications/vanilla/openapi/discussions.yml, tests/APIv2/DiscussionsTest.php
This option allows body expansion to the discussions API. Because the body requires more queries and could add a significant amount of data to the result it is left as a parameter.
This PR also includes a slight fix to `lastUser` expansion. When this field is expanded it actually expands in two places which is not optimal. This functionality is kept for BC, but an additional `lastPost.insertUser` expansion parameter has been added for a lesser expansion.
Closes #9527.
=> Add lastPost.body expansion to /api/v2/discussions endpoints

applications/dashboard/modules/class.mediaitemmodule.php
This fixes [issue](https://github.com/vanilla/vanilla/issues/8674).
The MediaItemModule->tag property can be set when the module is created, but it cannot be changed later or accessed in a view. This PR implements a `setTag()` and `getTag()` method to make this property usable.
=> Implement getter/setter for MediaItemModule->tag

library/core/class.oauth2.php
This PR will close issue https://github.com/vanilla/vanilla-patches/issues/657
We currently have code that could be used to connect an individual user to an authentication provider once he/she is logged into a forum. It was probably copied over from Facebook connect when the Oauth2 plugin was created. This code is no longer needed. This PR removes it.
=> Backport: Remove unused code from the OAuth2 base class.

applications/conversations/views/messages/popin.php
We had a fatal error here because `renderExcerpt()` requires a string as the first parameter.
This is a similar fix to what we did on the actual conversations page in https://github.com/vanilla/vanilla/pull/9396
=> Fix conversation popin w/ Empty message

applications/dashboard/controllers/class.usercontroller.php
`/dashboard/user/(add|edit|delete)` do not highlight the proper menu item currently when not opened in a popup (e.g. when being redirected from ProfileController) because these routes belong to the "Moderation" section.
Fixes #6129
=> User moderation: set proper theme section

applications/vanilla/js/discussions.js
This will ensure the checkboxes still work if content is delivered via AJAX.
Closes #9532.
=> Use $(document).on() for discussions admin toggles

applications/vanilla/controllers/class.discussioncontroller.php, applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/settings/structure.php
Many, many years ago, 181a6f6 introduced `Vanilla.QueueNotifications`. It was a way to offset the sending of notifications. It was used by (almost) no one. Today, we remove it from core.
All removed code is gated behind a truthy `Vanilla.QueueNotifications` config. I do not anticipate any collateral damage.
=> Remove legacy Vanilla notifications queueing

applications/vanilla/js/discussions.js, applications/vanilla/views/discussion/profile.php
This make the "more" pager work the same way on profile/comments as it does on profile/discussions.
Fixes #5651
This was partly introduced in #5557 by the more restrictive selector, but the CSS class of the profile/comments `.Datalist` has always been wrong.
=> Fix $.morepager on profile/comments

applications/vanilla/models/class.commentmodel.php
There used to be this notice in the discussion view:
Trying to get property 'DateMarkedRead' of non-object
This was fixed here, but not correctly:
https://github.com/vanilla/vanilla/commit/dceb535e408fc268f29f15ad9dff2582547e2398
CategoryModel::categories() always returns categories as an array, thus the null coalescing operator is not needed and was just masking the actual error.
=> Fix array access in CommentModel::setWatch

applications/vanilla/views/discussion/helper_functions.php
fixes #2469 
While i appreciate closing off stale issues, this just came up recently:
https://open.vanillaforums.com/discussion/comment/258777/#Comment_258777
With the suggested fix of inserting JS to remove the anchor.
So why not fix what (for the time being) is still a feature.
=> Do not add #latest anchor when AutoOffset is disabled

library/core/functions.general.php
Soft-deprecation is probably as far as we can go. So let’s get on with it.
See #7687, #7688, #7694.
=> Soft deprecate t(), c(), config(), and saveToConfig()

library/Vanilla/Scheduler/Job/CallbackJob.php
A new type of scheduled job has been added, allowing for a simple callback to be executed at end of the request.
```php
$scheduler->addJob(
Vanilla\Scheduler\Job\CallbackJob::class,
[
"callback" => "implode",
"parameters" => ["one", "two", "three"],
]
);
```
Any valid [`callable` in PHP](https://www.php.net/manual/en/language.types.callable.php) can be provided as the callback. The parameters array will be passed to the callable with each element representing a separate parameter to the function/method.
=> Add callback scheduled job

library/src/scripts/flyouts/dropDownStyles.ts
https://github.com/vanilla/vanilla/pull/9451 made all flyout styles force to open to the right.
This broke our auto placement of flyouts.
=> Fix broken flyout styles

applications/dashboard/models/ActivityEmail.php, applications/dashboard/models/class.activitymodel.php
For the sake of improving compatibility with some existing email addon capabilities, the following changes have been made:
1. Update `ActivityEmail` to use an internal route versus an external URL.
1. Add a user-authentication hint (UserAuthorized) to the `BeforeSendNotification` event fired by `ActivityModel::sendActivityEmail`. This is done to allow addons to know they can skip per-user notification checking. If a user notification has been queued up using `ActivityEmail`, they should already been authorized.
=> Improve batch email compatibility with email addons

tests/Bootstrap.php, tests/fixtures/src/Scheduler/InstantScheduler.php
If tests in Vanilla happen to touch any code that makes use of the scheduler, it will currently fail. This is due to the scheduler not being properly configured in the test bootstrap. That is resolved with this update.
=> Add Scheduler to Vanilla's testing bootstrap

library/Vanilla/EmbeddedContent/AbstractEmbedFactory.php, library/Vanilla/EmbeddedContent/Factories/AbstractOwnSiteEmbedFactory.php, library/Vanilla/EmbeddedContent/Factories/CommentEmbedFactory.php, library/Vanilla/EmbeddedContent/Factories/DiscussionEmbedFactory.php, tests/Library/Vanilla/EmbeddedContent/Factories/CommentEmbedFactoryTest.php, tests/Library/Vanilla/EmbeddedContent/Factories/DiscussionEmbedFactoryTest.php, tests/fixtures/src/MockSiteSection.php
Requires https://github.com/vanilla/multisite/pull/301 to actually work
- Updates `CommentsEmbedFactory` and it's tests.
- To support site sections.
- Tests now use a data provider.
- Updates `DiscussionEmbedFactory` and it's tests.
- To support site sections.
- Tests now use a data provider.
**Expected**
`/api/v2/media/scrape` now works on discussions/comment URLs that have a site section in them.
=> Update comment and discussion embed factories to support site sections

applications/dashboard/src/scripts/forms/0-SimpleForm.story.tsx, applications/dashboard/src/scripts/forms/DashboardFormGroup.tsx, applications/dashboard/src/scripts/forms/DashboardFormLabel.tsx, applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx, applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx, library/src/scripts/apiv2.ts, library/src/scripts/forms/buttonStyles.ts
Blocking https://github.com/vanilla/knowledge/issues/1337
- Adds a react image upload for the dashboard.
- This relies on existing dashboard styles.
- Image upload displays an image preview.
- Image upload has an "undo" action to revert to the old image.
- Images are uploaded through the `/media` API endpoint.
- Works purely by URL. Form value is a URL, and a URL is returned. This means when initializing an existing form, the name will not present. This is also a limitation of our non-react dashboard image upload.
- Adds the image upload to the storybook.
=> Add dashboard image upload in react

applications/vanilla/controllers/class.vanillasettingscontroller.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/views/vanillasettings/archive.php, library/core/class.configurationmodel.php, tests/ExpectErrorTrait.php, tests/Models/DiscussionModelTest.php
We haven’t officially supported archiving for some time. We can’t remove archive date functionality at this time, but we can remove the filtering which is more bug prone anyway.
Closes #5294.
Closes #5206.
Closes #2894.
Closes #3870.
With respect to the archive dates, I extended it to allow for date expressions since that would be the most common use-case anyway.
=> Remove Garden.Archive.Exclude functionality

applications/dashboard/views/settings/tags.php
The merge checkbox wasn’t properly wrapped for the new dashboard. If you want to test this, do the following:
1. Have at least two tags.
2. Edit one and rename it to be the same as another tag.
3. Hit save. The checkbox should appear.
Closes https://github.com/vanilla/support/issues/102.
=> Fix merge tags HTML

library/Vanilla/Scheduler/DummyScheduler.php, tests/Library/Vanilla/Scheduler/SchedulerTest.php
The job scheduler tests were always failing on my local host due to PHPUnit’s strict checking of output buffering. This change adds an option to the DummyScheduler to not flush buffers.
=> Fix output buffer corruption during tests

plugins/ProfileExtender/views/helper_functions.php
This also fixes various "Undefined index" notices since `$allFields` includes user properties which do not have a `OnProfile` key set.
=> Remove val() call from ProfileExtender view

library/core/class.session.php
#9265 did not fully fix the warning
The `$foreignKey` passed into `validateTransientKey()` may be `false`, especially when coming from a function like `val()`:
https://github.com/vanilla/vanilla/blob/666558094c9dbdbf1ad3ee9d5fb3e34767912e54/applications/vanilla/controllers/class.moderationcontroller.php#L48
The above code should probably not use $_POST directly, but why not make sure both arguments of hash_equals are always a string.
Changed the variable names to reflect the arguments of [hash_equals](https://www.php.net/manual/en/function.hash-equals.php) for clarity.
=> Gdn_Session: Fix hash_equals notice

plugins/editor/js/buttonbarplus.js
This changes Advanced Editors markdown so that when hyperlinking a selected piece of text, the link is created without the optional and always redundant (in the case of this editor) title. This makes the generated markdown easier to understand.
fixes #5806
=> Advanced Editor: Remove redundant link title

library/core/class.request.php
It suggests you use "addAssetRoot" which doesn't exist.
=> Fix getAssetRoot deprecation warning

conf/config-defaults.php, library/core/class.vanillahtmlformatter.php
I followed the suggestions of #7769
The only difference is, that `Garden.Html.CustomUrlSchemes` replaces the default config in my implementation. This is because afaik array configs are somewhat deprecated and because of HtmLawed's special scheme syntax which doesn't really map to an array. String concatenation would be another option.
=> Allow custom url schemes

library/core/class.cookieidentity.php
This will make it easier to hunt down configs while going through logs.
=> Add the specific domain values during cookie domain warnings

applications/dashboard/models/class.updatemodel.php
Since the structure now runs as system, the session should be restored for requests that don’t end after the update.
=> Restore the user’s session after running the structure

applications/vanilla/openapi/comments.yml, applications/vanilla/openapi/discussions.yml
The reactions endpoints don’t use expand parameters so they should be in the spec.
=> Remove expand parameters from the reactions specs

applications/dashboard/src/scripts/pages/authenticate/SignInPage.tsx, applications/dashboard/src/scripts/pages/authenticate/components/PasswordForm.tsx, applications/dashboard/src/scripts/pages/recoverPassword/RecoverPasswordPage.tsx, applications/vanilla/src/scripts/forms/CommunityCategoryInput.tsx, library/src/scripts/@types/api/users.ts, library/src/scripts/content/Translate.tsx, library/src/scripts/contexts/SearchContext.tsx, library/src/scripts/contexts/TabContext.tsx, library/src/scripts/features/search/SearchOption.tsx, library/src/scripts/features/users/MultiUserInput.tsx, library/src/scripts/features/users/Permission.tsx, library/src/scripts/forms/select/overwrites.tsx, library/src/scripts/headers/mebox/pieces/MessagesContents.tsx, library/src/scripts/headers/mebox/pieces/NotificationsContents.tsx, library/src/scripts/headers/mebox/pieces/UserDropDownContents.tsx, library/src/scripts/headers/mebox/pieces/UserDropDownContext.tsx, library/src/scripts/headers/mebox/pieces/UserDropdown.tsx, library/src/scripts/layout/DeviceContext.tsx, library/src/scripts/routing/PagesContext.tsx, library/src/scripts/styles/textUtils.ts, library/src/scripts/theming/ThemeProvider.tsx, package.json, packages/vanilla-eslint-config/index.js, packages/vanilla-eslint-config/package.json, packages/vanilla-react-utils/src/index.ts, plugins/rich-editor/src/scripts/editor/withEditor.tsx, plugins/rich-editor/src/scripts/toolbars/MentionToolbar.tsx, yarn.lock
**Why?**
- Prettier <= 1.19 breaks on nullish coalescing operators.
**Why are there changes?**
It looks like prettier 1.18 adjusted 2 things in how it formats stuff.
- HOC components will prefer to be on a single line when below the line length.
- Spreads w/ typecasts now get parantheses. Eg. `{(...thing as T)}` vs `{...thing as T}`
=> Update prettier to 1.19.1

library/Vanilla/Web/Controller.php
Currently, the `Vanilla\Web\Controller` throws a generic `Exception` when the session hasn’t been injected. If you are using PHPStorm then this riddles subclasses with a tonne of code inspection warnings which makes code hygiene quite difficult.
This change proposes to change the exception type to our general HTTP level `ServerException`. It’s the same code, but can then be ignored in your project settings. This makes sense because we generally expect `HttpException` subclasses to throw their exceptions up to the dispatcher.
=> Make the controller throw a ServerException rather than a generic Exception

library/core/functions.deprecated.php, library/core/functions.general.php, library/core/functions.render.php
We currently use `markString()` to add `<mark>` tags to search results. This presents a few issues:
1. The function only works on plain text, but is not documented as such. It ends up being called incorrectly.
2. We don’t often use plain text at all. Usually, when we say plain text we mean text that has passed through `htmlspecialchars()`. Currently, `markString()` has several edge case bugs with html entities.
3. Since we won’t always use plaintext it will make our functionality appear inconsistent.
4. I suspect there are also hidden XSS vulnerabilities waiting to be uncovered in this function too. We must remain vigilant.
=> Deprecate markString()

library/Vanilla/Formatting/Formats/HtmlFormat.php, library/core/class.vanillahtmlformatter.php, tests/Library/Vanilla/Formatting/Formats/MarkdownFormatTest.php, tests/fixtures/formats/html/images/output.html
- The imploding URL schemes actually had a default added in https://github.com/vanilla/vanilla/pull/9538, but we don't load the default when using our `MockConfig`. I added a non-fatal fallback if the config is not defined.
- We intentionally updated the way we rendered HTML, but the fixtures were added in a different PR so they were never run together. I've updated that fixture.
=> Fix HTML format tests

.circleci/config.yml
Vanilla's [Chromatic](https://www.chromaticqa.com) job runs every time there's a build. Forked repositories do not contain the necessary environmental variable (`CHROMATIC_APP_CODE`) required to perform this job, so builds based on those forks fail.
The build has been updated to check for the Chromatic app code in the environment to determine whether or not Chromatic tests should be run. If no Chromatic app code is detected, those tests should be skipped.
Making this happen required essentially wrapping the existing `chromatic/test` job in a custom `chromatic_test` job and putting in a conditional stop. The `core/checkout` step was not compatible with this method. [Yarn errors were triggered](https://app.circleci.com/jobs/github/vanilla/vanilla/21961) unless `checkout` was used, instead.
=> Add ability to make Chromatic optional in build

applications/dashboard/models/class.usermodel.php
Whenever a signed in user visits a page that is the controllers `index()` with non-empty arguments (e.g. a standard discussion page like /discussion/123/slug), `UserModel::clearSectionNavigationPreference()` is called.
This is because the user may have been redirected from a falsely set `DashboardNav.DashboardLandingPage` in their preferences. This logic is flawed, but since with the current architecture there is not way to "test" a dispatch to a particular route, it is probably the best that can be done.
See #4497 and #4734 for reference.
Unfortunately `clearSectionNavigationPreference()` calls `saveToSerializedColumn()` twice leading to 2 entirely useless and duplicated write queries on the user table even if there is no actual change in the data. 
This PR checks for an actual change in …
=> Prevent useless user preference queries

tests/phpunit.php
This change allows addons that run through our core test harness to add files within their `/tests/Utils` directory and have them included for tests. The intention is for them to add classes and traits that can be helpful for tests.
I thought of this while noticing a lot of copy/pasted code in some tests in other repos. I realized they really had no way to not do that since they have no `autoload-dev`.
This is a bit kludgey, but I figure that’s not the worst since this is *just* for tests.
Do you want to know what I specifically have in mind for this? Well, approve this PR and then stay tuned.
=> Add a poor man’s autoload-dev to tests

library/src/scripts/routing/links/BackRoutingProvider.tsx
This was actually just added in https://github.com/vanilla/vanilla/pull/9606 but had an inconsistent name.
I forgot to push the commit before merging.
Blocking https://github.com/vanilla/knowledge/pull/1358
=> Rename FallbackUrlSetter to FallbackBackUrlSetter

applications/vanilla/settings/structure.php
This should mainly help small setups without an active cache.
I tested this on a board with 7k discussion and around a dozen announcements. Announcement queries that used to take ~5ms are now  0,27ms. The single index for `Anounce` was required to make the /discussions query fast as well (and not just single categories).
fixes #3566
=> Announcements: Add indices to Discussion table

library/setup/ComposerHelper.php
Related https://github.com/vanilla/dev-inter-ops/issues/38
Add ignore engines while installing node modules through composer helper.
```js
// --ignore-engines is used until https://github.com/vanilla/dev-inter-ops/issues/38 is resolved.
// Node 10.11.0 is run there and our linter has an engine requirement of 10.13.0
// We don't even run the linter as part of this process.
// It even technically works but many packages that support node 10 only want to support the LTS version (10.13.x).
```
Re:
=> Ignore engines during composer install

library/setup/ComposerHelper.php
backporting https://github.com/vanilla/vanilla/pull/9623
=> Backport: Ignore engines during composer install (2019.017)

library/Vanilla/Formatting/Formats/NotFoundFormat.php
`FormatInterface` was updated with #9554. Most of core Vanilla's formats seem to have been updated, with the exception of `NotFoundFormat`. The method is added here.
=> Fix fatal error when rendering unknown format

library/Vanilla/Formatting/Formats/NotFoundFormat.php, tests/Library/Vanilla/Formatting/Formats/NotFoundFormatTest.php
Backport of #9625 and #9628
> `FormatInterface` was updated with #9554. Most of core Vanilla's formats seem to have been updated, with the exception of `NotFoundFormat`. The method is added here.
=> Backport: Fix fatal error when rendering unknown format

applications/vanilla/models/class.discussionmodel.php, applications/vanilla/views/discussions/helper_functions.php, applications/vanilla/views/discussions/table_functions.php, tests/APIv2/DiscussionsTest.php
The discussions APIv2 was failing with empty discussion titles. This fix is primarily for that defect, but also includes the enhancement to correct the title at the model level so that other code that may benefit from it.
This change also renames the translation for untitled discussions to a simple “(Untitled)” that is more generic for other types of data.
=> Correct empty discussion titles at the model level

plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuBarTab.tsx
Fixes https://github.com/vanilla/knowledge/issues/1376
Fixes https://github.com/vanilla/support/issues/1054
In the recent typescript update the conditional here was flagged as being incorrect. https://github.com/vanilla/vanilla/commit/9dab47625eb1d35a2a81d17a488acbce5ee4648d#diff-865586e0184f5855dca1fd1863126621R63
Eg. `if (open)` always was true because `open` is global function on the window.
I guess I didn't think critically enough because I just updated it to be `this.props.open` instead. Unfortunately that totally breaks the logic of component. As the previous behaviour intended, this should __always__ be visible, and should not ever be null, so I removed the conditional altogether.
I've opened this tech debt issue to get this component into storybook so regressions like this don't …
=> Fix editor paragraph menu tabs only appearing when open/active

library/src/scripts/headers/TitleBar.tsx, library/src/scripts/headers/TitleBarHome.tsx, library/src/scripts/layout/PageHeading.tsx, library/src/scripts/routing/links/BackLink.tsx
Working towards https://github.com/vanilla/knowledge/issues/1379
The behaviour of `fallbackElement` w/ `<BackLink />` changed in https://github.com/vanilla/vanilla/pull/9606. Unfortunately it was still very confusing and misleading, since we __always__ set a backlink now.
I've done the following:
- Remove the prop from `<BackLink />` entirely.
- Remove the usage from `<PageHeading />` it already has it's own `includeBackLink`  prop to control this.
- Remove the usage in `<TitleBar />` and add a `useMobileBackButton` prop, defaulting to true on `<TitleBar />`.
=> Allow it to be specified if the back button is allowed in the titlebar

applications/dashboard/src/scripts/forms/DashboardSelect.tsx, library/src/scripts/forms/select/SelectOne.tsx, library/src/scripts/modal/Modal.tsx
Blocking https://github.com/vanilla/knowledge/pull/1388
- Update `<Modal />` to autodetect the `elementToFocusOnExit`. The prop will still be respected if passed though. This new default value is the last focused element before before we focus the first modal item.
- Update `<SelectOne />` and `<DashboardSelect />` to be able to pass a ref through.
=> Improve focusing behaviour in modals

library/src/scripts/embeddedContent/StoryExampleDropDown.tsx, library/src/scripts/embeddedContent/StoryExampleDropDownMessages.tsx, library/src/scripts/embeddedContent/StoryExampleDropDownNotifications.tsx, library/src/scripts/embeddedContent/dropDowns.story.tsx, library/src/scripts/layout/bodyStyles.ts, library/src/scripts/layout/panelLayoutStyles.ts, library/src/scripts/storybook/StoryBookStyles.ts, library/src/scripts/storybook/StoryContent.tsx, library/src/scripts/styles/styleUtils.ts
Fixes https://github.com/vanilla/knowledge/issues/1385
**Note that this PR updates the storybook intentionally. Please review the changes and approve those if they make sense.**
- Fixes dropdown styles by applied the `$unique: true` value to its style. The order of selectors was inconsistently being rendered without that. This now automatically gets applied to all simple styles in the style factory.
- Updates the story for the dropdown.
- Automatically opens the first dropdown item.
- Run in mobile and desktop viewports.
- Improves storybook utilities
- Adds better types for media queries.
- Allow media queries to opt-out of the min-width.
- Update `<StoryTiles />` to switch to a single column on smaller layout sizes.
=> Fix dropdown styles and improve DropDown storybook entry.

cache/.htaccess, library/core/class.oauth2.php
This PR will close this issue: https://github.com/vanilla/support/issues/987
We have recently added the State Token to Authorization request. Most OAuth2 providers do not use a separate URL for users to register so we weren't adding the Token to the Registration request. 
However, some customers ***do*** have a register button and would like to return the user back to the forum after registering them. This requires a State Token. This PR will modify the Registration URL by passing it through the same authorization redirect endpoint as the Authorization URL to generate and save  the State Token and attach it to the request.
- Turn on the OAuth2 Plugin.
- Put a valid URL in the RegisterURL field (you could put the same URL as the Authorization).
- Click on Register.
- Observe that the State …
=> Add state token to OAuth2 registrations

cache/.htaccess, library/core/class.oauth2.php
This is a backport of https://github.com/vanilla/vanilla/pull/9634
We have recently added the State Token to Authorization request. Most OAuth2 providers do not use a separate URL for users to register so we weren't adding the Token to the Registration request.
However, some customers do have a register button and would like to return the user back to the forum after registering them. This requires a State Token. This PR will modify the Registration URL by passing it through the same authorization redirect endpoint as the Authorization URL to generate and save the State Token and attach it to the request.
=> Backport: Add state token to OAuth2 registrations

applications/dashboard/openapi/locales.yml
Move `GET /locales/translations endpoints` to under Translations group in docs.
=> Add locales/translations endpoints to translations group in APIv2 docs

library/src/scripts/content/code.ts, plugins/rich-editor/src/scripts/editor/EditorContent.tsx, plugins/rich-editor/src/scripts/quill/KeyboardBindings.test.ts, plugins/rich-editor/src/scripts/quill/KeyboardBindings.ts, plugins/rich-editor/src/scripts/quill/SyntaxModule.ts, plugins/rich-editor/src/scripts/quill/blots/blocks/CodeBlockBlot.ts
Fixes https://github.com/vanilla/vanilla/issues/9440
Fixes https://github.com/vanilla/knowledge/issues/1347
There were a few issues causing the cursor to jump around and CPU usage to spike.
1. When initializing a synchronized editor `useInitialValue()` was re-initializing too often due to some faulty logic. Additionally it was not clearing history or setting the initial selection. This could cause the selection to jump when first editing a code block.
2. `SyntaxModule` has some logic to preserve the selection after a highlight. Unfortunately we made `highlightText` asynchronous for a dynamic import. This method **has to work synchronously**.
- If we awaited the async value we would likely be setting back the old selection value or content.
3. Our editor UI synchronizer was listening to …
=> Fix editor syntax highlighting moving cursor and spiking CPU

library/src/scripts/layout/frame/frameStyles.ts, packages/vanilla-polyfill/index.js, plugins/rich-editor/src/scripts/editor/richEditorStyles.ts, plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenusBarToggle.tsx
Fixes https://github.com/vanilla/vanilla/issues/9141
Fixes https://github.com/vanilla/support/issues/536
- Adds a stub method for `String.prototype.normalize` to prevent an IE11 crash.
- Fix the vertical flex rule used in `frameBody` to be IE11 compatible.
- Fixed a specificity error on master preventing the paragraph menu from appearing.
- Fixed some duplicate CSS classes being applied where they didn't need to be.
- Fix the paragraph menu icon not being the correct width.
- Remove extra paddings from the embed toolbar in legacy mode.
=> Fix IE11 bugs in Rich Editor

applications/vanilla/EmbeddedContent/Factories/CommentEmbedFactory.php, applications/vanilla/EmbeddedContent/Factories/DiscussionEmbedFactory.php, applications/vanilla/bootstrap.php, applications/vanilla/tests/EmbeddedContent/Factories/CommentEmbedFactoryTest.php, applications/vanilla/tests/EmbeddedContent/Factories/DiscussionEmbedFactoryTest.php, bootstrap.php, library/Vanilla/EmbeddedContent/EmbedService.php, library/Vanilla/EmbeddedContent/Factories/AbstractOwnSiteEmbedFactory.php
Fixes https://github.com/vanilla/dev-inter-ops/issues/36
The Vanilla application is optional, so I've removed references to it from the `EmbedService`.
- `DiscussionEmbedFactory` and `CommentEmbedFactory` moved to `applications/vanilla`.
- Added a `bootstrap.php` file with registration of these factories only when the forum app is enabled.
- Moved the tests to the forum (vanilla) app.
- Removed a reference to the `EmbedManager` in the main bootstrap. This class doesn't exist anymore for a few releases, and was removed in favour of the `EmbedService`.
=> Fix forum classes being referenced in the core library

applications/dashboard/js/dashboard.js, applications/dashboard/js/src/main.js
Issue -  https://github.com/vanilla/vanilla/issues/8878
This PR is to fix uploaded image name preview on dashboard category page. 
**Test**
Create an image file named `x<img src=x onerror=alert(document.cookie)>x.jpeg`
Go to the dashboard categories page.
Upload it as the category thumbnail.
Verify file name.
=> fix - Uploaded image filename on dashboard category 

library/Vanilla/Web/Asset/InlinePolyfillContent.js.twig, library/Vanilla/Web/Asset/WebpackAssetProvider.php
Fixes https://github.com/vanilla/support/issues/1001
The HTML5 script loading spec states the following
> The script's type is "classic", and the element has a src attribute, and the element does not have an async attribute, and the element does not have the "non-blocking" flag set:
> Add the element to the end of the list of scripts that will execute in order as soon as possible associated with the node document of the script element at the time the prepare a script algorithm started.
> ...
Unfortunately IE11 does not comply with the spec as it is worded, and instead is treating it as async, which means it gets loaded whenever the browsers gets a chance.
Sometimes that is immediately (like when the script is cached). Other times it takes some time causing errors.
- Set the async …
=> Fix IE11 polyfills not loading consistently

library/core/functions.general.php
Less intrusive version of #9533
This is mainly used in activitiy headlines, where "[deleted user] has joined" shouldn't really appear.
=> Exclude deleted users from format strings

library/Vanilla/Formatting/Formats/WysiwygFormat.php, tests/fixtures/formats/wysiwyg/remove-carriage-returns/input.html, tests/fixtures/formats/wysiwyg/remove-carriage-returns/output.html, tests/fixtures/formats/wysiwyg/remove-carriage-returns/output.txt
So content in contains`\r\n` characters  which isn't parsed out by the Wysiwyg format, causing the content to be rendered incorrectly.
relates to https://github.com/vanilla/support/issues/1033
blocks https://github.com/vanilla/internal/pull/2097
=> Filter out '\r\n' (new-line) characters from Wysiwyg content

library/Vanilla/Models/CurrentUserPreloadProvider.php
Fixes a mistake from https://github.com/vanilla/vanilla/pull/9670/ and uses a more scoped, less permissioned endpoint.
=> Fix the user preloader typo

applications/dashboard/views/role/index.php
The docs page for default role types was outdated and broken. Now, it is fixed.
=> Fix Default Role Types docs URL

.circleci/config.yml, composer.json, composer.lock, environment.php
PHPmas has to come a bit early this year because I want to bring in the psr-14 event dispatcher which is PHP 7.2+. See #9559.
Due to an [earlier PR](https://github.com/vanilla/vanilla/pull/9485) I’m hoping this is all that is needed for the version bump.
=> PHPmas 7.2

library/src/scripts/messages/message.story.tsx
Fix - https://github.com/vanilla/knowledge/issues/1371
This PR is for  - Add message variations in storybook
- messages with full width.
- sticky message with fixed position.
- short message and long message with icons and buttons.
- message with link.
=> Add message component to storybook

applications/dashboard/views/role/index.php
Backporting #9682 to `release/2019.017`.
> The docs page for default role types was outdated and broken. Now, it is fixed.
=> Backport: Fix Default Role Types docs URL

package.json
Related https://github.com/vanilla/vanilla/pull/9623
Blocking an infra deploy, because our engine version is older than what some CI dependencies require (but are not actually used during deployment).
=> Ignore engines in lerna bootstrap

library/src/scripts/forms/select/SelectBox.tsx, library/src/scripts/messages/Message.tsx, library/src/scripts/messages/messageStyles.ts
This PR fixes wording issues for both the "other locales" dropdown and for error messages. See https://github.com/vanilla/knowledge/issues/1370
Requires: https://github.com/vanilla/vanilla/pull/9684
For: https://github.com/vanilla/knowledge/issues/1370
Companion PR: https://github.com/vanilla/knowledge/pull/1398
=> Fix styling for messaging

library/Vanilla/Web/Asset/InlinePolyfillContent.js.twig, library/Vanilla/Web/Asset/WebpackAssetProvider.php
Backporting #9672 to `release/2019.017`.
> [...]
> ## The changes
>
> - Set the async attribute to false on the script being loaded.
> - Convert the inline polyfill content to be a twig js template.
=> Backport: Fix IE11 polyfills not loading consistently

library/database/class.mysqlstructure.php, tests/Library/Database/MySQLStructureTest.php, tests/fixtures/TestMySQLStructure.php
Vanilla always checked if a table had a FULLTEXT key in one row and forced that table to MyISAM. The minimum required MySQL version for Vanilla already supports fulltext keys for InnoDB tables, therefore that logic isn't needed any more.
The Gdn_MySqlStructure class had a helper function "_supportsFulltext. Under the assumption that this will always return `true`, I've deleted all code lines that became unnessecary.
This will close 
https://github.com/vanilla/vanilla/issues/5555
https://github.com/vanilla/vanilla/issues/6029
=> Get rid of forcing tables to MyISAM when FULLTEXT key is used (rebased)

applications/dashboard/controllers/class.utilitycontroller.php, applications/dashboard/models/class.updatemodel.php, tests/APIv0/AltTest.php
The test was failing due to our session restoring functionality during the alt install. That has been checked as a special case.
In addition to the fix I added 500 response codes when utility/update fails to hopefully help troubleshoot errors more. This should close #9144.
=> Fix alt install tests

library/Vanilla/Models/SiteMeta.php
Some pages fail to load and return json error message instead when site logo is not set.
This patch fixes this issue.
=> Fix SiteMeta::getLogo() method to return nullable string

plugins/rich-editor/src/scripts/quill/VanillaTheme.ts
Fixes https://github.com/vanilla/vanilla/issues/9705
This is notable bug in quill we are working around https://github.com/quilljs/quill/blob/1.3.7/modules/keyboard.js#L409
This event is silent, because they aren't handling some edge case. One of these days we'll need to fix it, but this makes sure we always update our location when hitting enter.
=> Fix issue where paragraph menu can lag in the editor

plugins/rich-editor/src/scripts/toolbars/MentionToolbar.tsx
Fixes https://github.com/vanilla/vanilla/issues/9709
-  Remove `requestAnimationFrame` that was causing an infinite loop after recent changes.
- Fixes call to setState that would just recreate the autocomplete blot over and over again.
=> Fix mention crash in rich editor

build/scripts/utility/EntryModel.ts
Our addon manager lowercases addon keys. This can lead to issues when loading our scripts in our webpack asset model, because we have to check if a file exists on the system. On case-sensitive systems this leads to addon assets not loading.
See https://github.com/vanilla/vanilla/blob/e0ff3c5d7fbf31e59686ef5ec6840036b4d6a1d5/library/Vanilla/Addon.php#L765
I'm essentially mimicking this my lowercasing the frontend assets too.
=> Fix case sensitivity of build output

library/Vanilla/Formatting/Formats/HtmlFormat.php
~Removes the LIBXML_NOEMPTYTAG from HtmlFormat::cleanupEmbeds.  This was causing and extra <br> to appended to the body content causing formatting issues.  Tests will be written ensure this doesn't occur.~
~https://www.php.net/manual/en/libxml.constants.php~
~` LIBXML_NOEMPTYTAG (integer) Expand empty tags (e.g. <br/> to <br></br>)`~
filter out `</br>` from content, this breaks formatting.
closes https://github.com/vanilla/support/issues/1106
=> Fix BBcode spacing issue

applications/vanilla/models/class.commentmodel.php, tests/Models/CommentModelTest.php
Since #9488, visiting a new discussion fails to create a new "watch" status. This status is used by Vanilla to determine which discussions have new content since the user last viewed them. Existing "watch" status records are still being updated. Only _new_ discussion "watch" statuses are being missed. This was caused by mistakenly removing the insert routine for these statuses, along with the archiving code it was adjacent to.
The code for inserting new discussion "watch" statuses has been restored and a simple (yet verbose) test has been added to ensure the relevant records continue to be added and updated.
=> Fix comment watch status in visited discussions

tests/fixtures/formats/bbcode/carriage-returns/input.txt, tests/fixtures/formats/bbcode/carriage-returns/output.html, tests/fixtures/formats/bbcode/carriage-returns/output.txt, tests/fixtures/formats/bbcode/code-block-formatting/input.txt, tests/fixtures/formats/bbcode/code-block-formatting/output.html, tests/fixtures/formats/bbcode/code-block-formatting/output.txt
Add testing for bbcode to ensure that formatting isn't broken when we filter closing <br> tags.
closes https://github.com/vanilla/support/issues/1106
=> Ensure filtering </br> tags don't break formatting

library/core/functions.deprecated.php, library/core/functions.general.php
- There was an invalud `{}` string access in functions.general.
- Our deprecated `trueStripSlashes()` calls a now deprecated `get_magic_quotes_gpc()`. I checked all of our source code and this function can safely be removed.
=> Fix PHP 7.4 deprecation warnings

applications/dashboard/models/class.permissionmodel.php
Permissions in vanilla can be upper or lower case.  In this case if this check would fail based on casing of the $permissionName and the $limitToSuffix parameter.  For example `plugin.manage.view` ===`View` would return false and not be listed as a Global permission.
Related to https://github.com/vanilla/knowledge/issues/1319
=> Make limitToSuffix check case insensitive in PermissionModel::isGlobalPermission

applications/vanilla/models/class.commentmodel.php, tests/Models/CommentModelTest.php
Backporting #9723
> Since #9488, visiting a new discussion fails to create a new "watch" status. This status is used by Vanilla to determine which discussions have new content since the user last viewed them. Existing "watch" status records are still being updated. Only new discussion "watch" statuses are being missed. This was caused by mistakenly removing the insert routine for these statuses, along with the archiving code it was adjacent to.
>
> The code for inserting new discussion "watch" statuses has been restored and a simple (yet verbose) test has been added to ensure the relevant records continue to be added and updated.
=> Backport: Fix comment watch status in visited discussions

applications/dashboard/design/admin.css, applications/dashboard/design/style-compat.css, applications/dashboard/scss/compatibility/_scaffolding.scss, library/src/scripts/bootstrap.ts, library/src/scss/utility/_scaffolding.scss
Added config (true by default) to use the focus visible plugin. Some clients may not want this style and it can now be bypassed with a config.
Note that there are more styles in our core theme that is problematic. For the moment if a client wants it, they will need to style the outline. They can do a feature request to remove the core styles. It's not so easy, since we need to worry about backwards compatibility. 
@irina-vanillaforums
=> Added config setting to bypass js-focus-visible plugin

library/src/scripts/bootstrap.ts
A `gdn.getMeta()` is exposed, but not on the imported Gdn object here.
I've cleared up the scoping issues that were causing the bootstrap to emit a module error.
=> Fix gdn & global scope issues in bootstrap

.circleci/config.yml, .codecov.yml, README.md
Working towards https://github.com/vanilla/vanilla/issues/9714
- Adds code coverage setup for https://codecov.io w/ CircleCI.
- Adds CircleCI coverage tracking.
- Increases the resource class size for our PHP tests to help offset the increased time  of tracking coverage.
The reports have started to appear in Codecov, but it looks like it can't actually generate any comparisons until the master branch contains the coverage reporting config file.
I will make followup PRs to tweak this setup once I can see it running.
- Codecov uses the clover coverage files.
- CircleCI uses the junit files.
=> Add code coverage reporting for to CI

library/core/class.oauth2.php
This PR is in response to this issue: https://github.com/vanilla/support/issues/1088
We have a customer whose Register URL in OAuth2 connection has query parameters attached to it which makes for double '?' when we add our GET parameters. 
This PR will create a static public method (so we can use it elsewhere) that will add an array of queries to an existing URL regardless of if the URL already has parameters.
- Turn on the OAuth2 plugin.
- Configure the plugin so that the Register URL and the Authorize URL has a query parameter (e.g. `https://myauthserver.com/authorize?forward=true`).
- Try to connect.
- Observe borking.
- Checkout this branch.
- Now try to correct. 
- It may still bork because of the extra parameters you passed but if the URL contains only one '?' then we are good.
=> Fixing adding GET params to existing URLs in OAuth2.

library/core/class.oauth2.php
This is a backport of https://github.com/vanilla/vanilla/pull/9748
We have a customer whose Register URL in OAuth2 connection has query parameters attached to it which makes for double '?' when we add our GET parameters.
This PR will create a static public method (so we can use it elsewhere) that will add an array of queries to an existing URL regardless of if the URL already has parameters.
=> Backport: Fixing adding GET params to existing URLs in OAuth2.

plugins/rich-editor/src/scripts/quill/MarkdownModule.ts
When triggering inline markdown macros in the rich-editor, the `*` would immediately trigger _italic_ fonts instead of continuing reading for potential  __bold__ markup.  This removes `*`'s as trigger character so that user can continue typing before the marco is trigger.
`**test**` would result in \*_test_\* 
closes https://github.com/vanilla/knowledge/issues/1346
=> Rich-editor: remove '*' as a Inline trigger for markdown marcos

library/core/class.format.php, tests/Library/Core/FormatTest.php
We have an ill-advised use of `Gdn_Format::to()` where we allow arrays or objects to be passed and the class will format everything in them. Although the practice is heavily discouraged, we still support it.
There is a problem with self-referencing objects or arrays where `Gdn_Format::to()` will infinitely recurse when formatting in that case. This fix puts a guard against infinite recursion by keeping track of the objects and arrays that have already been formatted and not re-formatting them.
This also adds core support for the “display” format as a sanitized format. That’s our version of `htmlspecialchars()` with some extra processing. I think that’s an okay thing to do, but am asking reviewers to check it out.
Closes https://github.com/vanilla/support/issues/316.
=> Add a recursion guard in Gdn_Format::to()

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/views/entry/connect.php
After discovering a bug in which user's could not input a different user name than the one that was passed over SSO (see https://github.com/vanilla/support/issues/906) we decided to revisit the workflow of the Connect page. This PR will change a little bit of the wording and clean up the logic of the Connect method in the Entry Controller. 
This PR will: 
- Create 3 distinct code blocks for the 3 distinct scenarios of connection (Name exists, Email exists, create a new User).
- Change some of the wording on the Connect page. (see images below).
- Not overwrite the ConnectName with the Name passed over SSO (which was causing the bug to allow user's to change their name if it existed.
=> Fix confusing message and workflow in SSO connections.

bootstrap.php, composer.json, composer.lock, library/Garden/EventManager.php, library/Vanilla/Contracts/Addons/EventListenerConfigInterface.php, tests/Bootstrap.php, tests/Library/Garden/EventManagerPsrTest.php, tests/fixtures/src/TestEvent.php, tests/fixtures/src/TestEventChild.php
This PR introduces PSR-14 event dispatching and listening to the app for more structured events.
The `EventManager` now supports the two main interfaces: `EventDispatcherInterface ` and `ListenerProviderInterface `. I've also added an internal interface to configure listeners: `EventListenerAddonInterface `.
The idea is for addons to inject only the interfaces they need so we know the functionality they are using. Addons can use the `EventListenerAddonInterface` in their bootstraps to configure event listeners.
Closes #9559
=> Add PSR-14 event dispatcher support to Vanilla

library/src/scripts/content/UserContentLegacy.story.tsx, library/src/scripts/content/userContentStyles.ts, plugins/rich-editor/src/scripts/quill/components/blockQuoteStyles.ts, themes/keystone/package.json
~~When quotes are too deeply nested, they become impossible to read. The background color has a transparency, so it gets darker and darker the more you nest the quotes. I've capped it to 4 and then it's a solid color. Unfortunately, there's no magic bullet here for all themes because the specificity of deeply nested classes will be higher than styles overwriting the base styles. Fixes will need to go through services.~~
~~I checked the core themes and the only theme it didn't work for has a PR open.~~
Issue https://github.com/vanilla/support/issues/1107
The root of the issue was setting a color on the legacy blockquotes. We've moved that style to KB only.
=> Removed "color" style on legacy blockquotes

applications/conversations/controllers/api/ConversationsApiController.php, applications/dashboard/models/class.usermodel.php, applications/vanilla/controllers/api/CommentsApiController.php, applications/vanilla/controllers/api/DiscussionsApiController.php, library/Vanilla/Contracts/Models/FragmentProviderInterface.php, library/Vanilla/Contracts/Models/UserProviderInterface.php, tests/Models/UserModelExpandUserFragmentTest.php, tests/fixtures/src/Models/MockUserProvider.php
Revert changes introduced: https://github.com/vanilla/vanilla/pull/6867
Seem that `$options` parameter and event `userModel_expandUsers ` were never used.
Closes: https://github.com/vanilla/support/issues/1122
Closes: https://github.com/vanilla/vanilla-patches/issues/667
=> Validate user fragment

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/views/entry/connect.php
Backport https://github.com/vanilla/vanilla/pull/9721
After discovering a bug in which user's could not input a different user name than the one that was passed over SSO (see https://github.com/vanilla/support/issues/906) we decided to revisit the workflow of the Connect page. This PR will change a little bit of the wording and clean up the logic of the Connect method in the Entry Controller. 
This PR will: 
- Create 3 distinct code blocks for the 3 distinct scenarios of connection (Name exists, Email exists, create a new User).
- Change some of the wording on the Connect page. (see images below).
- Not overwrite the ConnectName with the Name passed over SSO (which was causing the bug to allow user's to change their name if it existed.
=> Backport: Fix confusing message and workflow in SSO connections.

plugins/rich-editor/package.json, plugins/rich-editor/src/scripts/quill/VanillaTheme.ts, yarn.lock
Removes the hacky keyboard handler from https://github.com/vanilla/vanilla/pull/9706
and bumps the quill version to include the change in https://github.com/vanilla/quill/commit/b43ef4105ae8c02008cfec24e0eca1dc503cca73
I skipped straight to `1.3.10` as a number because of some previous failed attempts to make yarn understand `1.3.8` and `1.3.9`.
=> Remove enter handler hack and fix quill handler

tests/Library/Core/DateTimeTest.php
Our existing coverage of this function was not consistent, leading to coverage  issues in PRs like this https://codecov.io/gh/vanilla/vanilla/pull/9767/src/library/core/functions.general.php
Sometimes tests would run and cover these lines, other times it wouldn't.
I just added some full coverage to prevent this from happening again
=> Add  dateCompare test

library/core/class.form.php, tests/Library/Core/FormTest.php
Our `Gdn_Form::color()` creates a visible text input and some hidden ones, along with a color chooser.
We weren't passing the full options to visible input though, so it was no possible to set certain attributes on it, such as `placeholder`.
=> Fix options not being passed to visible colour picker form input

.gitignore, .phpunit.result.cache, applications/dashboard/controllers/api/LocalesApiController.php, applications/dashboard/modules/class.headmodule.php, build/entries/public-path.ts, build/scripts/configs/makeBaseConfig.ts, library/Vanilla/Contracts/Web/AssetInterface.php, library/Vanilla/Models/SiteMeta.php, library/Vanilla/Web/Asset/ExternalAsset.php, library/Vanilla/Web/Asset/HotBuildAsset.php, library/Vanilla/Web/Asset/LegacyAssetModel.php, library/Vanilla/Web/Asset/LocaleAsset.php, library/Vanilla/Web/Asset/PolyfillAsset.php, library/Vanilla/Web/Asset/SiteAsset.php, library/Vanilla/Web/Asset/ThemeScriptAsset.php, library/Vanilla/Web/Asset/WebpackAsset.php, library/Vanilla/Web/Page.php, library/Vanilla/Web/ThemedPage.php, library/core/class.controller.php, library/core/class.gdn.php, tests/Library/Vanilla/Web/Asset/AssetsTest.php, tests/Library/Vanilla/Web/Asset/WebpackAssetProviderTest.php, tests/Library/Vanilla/Web/Asset/WebpackAssetTest.php
Required KB subclass update here https://github.com/vanilla/knowledge/pull/1429
Adds support for static-asset handling. It allows better handling of Cache header
+ Adds method `isStatic(): bool` to the interface
+ Implements default isStatic as false
+ `makeAssetPath` and `makeWebPath` now handle path as relative
+ fix small phpdocs
+ Implements isStatic as false
+ Implements isStatic as true
+ fix `style-compat.css` path as relative
+ fix  `self` usage for `$this`
+ Implements isStatic as true
+ fix  `self` usage for `$this`
+ Implements isStatic as true
+ Adds EventManager as a dependency
+ Fires a new Event `BeforeRenderMasterView` before rendering the Twig template
+ Adds EventManager as a dependency
+ Removes some unused imports
+ `addScript` and `addCss` methods assume that a new …
=> Add static designation support for assets

library/Vanilla/Web/ThemedPage.php, library/src/scripts/flyouts/DropDown.tsx
This was rendering as a literal parenthese in the dropdown.
Likely leftover from some merge conflict.
Additionally fixed some dependency order that's breaking https://app.circleci.com/jobs/github/vanilla/knowledge/8520
=> Remove extra parenthese & fix dependency order

library/Vanilla/Models/DraftModel.php, library/src/scripts/flyouts/dropDownStyles.ts, library/src/scripts/headers/mebox/pieces/UserDropDownContents.tsx
Add section `Articles` with menu item `Drafts` with proper implemented link to `/kb/drafts/` and counter.
Update section `Discussion` with proper link for discussions drafts `/drafts` and counter.
Closes: #9713
=> Split sections: discussion and article in user menu

packages/vanilla-i18n/src/ContentTranslator.tsx
Fix: https://github.com/vanilla/knowledge/issues/1372
Add afterSave() as props to IContentTranslatorProps to get navigationFlat data after saving translations for organize categories page.
Requires: 
https://github.com/vanilla/knowledge/pull/1432,
https://github.com/vanilla/internal/pull/2127
=> Add afterSave as props to IContentTranslatorProps 

library/src/scripts/redux/getStore.ts, library/src/scripts/redux/reducerRegistry.spec.ts, library/src/scripts/redux/reducerRegistry.ts
Issue https://github.com/vanilla/knowledge/issues/1435
- Re-apply default actions when new reducers are registered.
- Adds unit tests for the reducerRegistry.
=> Re-apply store actions after registering reducers

js/global.js, library/Vanilla/Models/SiteMeta.php
Issue https://github.com/vanilla/dev-inter-ops/issues/41
The PR adds a new SiteMeta parameter called `dynamicPathFolder` and it usage into js/global.js
It allows `url-path` manipulation for the endpoints `/settings/analyticstick.json` and `/notifications/inform`
=> Use dynamicPath from infra context for notifications and analytics requests.

library/Vanilla/Models/ThemePreloadProvider.php
There is kind "typo" in our code in ThemePreloadProvider `header` and `footer` data are mixed up
=> Fix header and footer called in opposite methods

library/Vanilla/Models/ThemePreloadProvider.php, library/src/scripts/redux/getStore.ts, library/src/scripts/redux/reducerRegistry.spec.ts, library/src/scripts/redux/reducerRegistry.ts
Backports
- Re-apply store actions after registering reducers #9775
- Fix header and footer called in opposite methods #9784
=> [Backport 2019.018] Multiple fixes

library/src/scripts/headers/TitleBar.tsx, library/src/scripts/headers/titleBarNavStyles.ts
Fixes https://github.com/vanilla/vanilla/issues/9213
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/70483935-2711bd00-1ab8-11ea-9de4-2e0b86997556.png)|![image](https://user-images.githubusercontent.com/1770056/70483834-d39f6f00-1ab7-11ea-9b64-116fea9e9c6c.png)|
- Fixes missing theme cache around titlebarNav styles.
- Fixes titlebar background color not getting applied in IE11
- Fixes alignment of titlbarnav links in IE11.
=> Fix titlebar styles in IE11

.codecov.yml
- Sets codecov config to informative mode. This means PRs will not fail for missing a status. Once we've got our config down, we can change this if we want.
- Add a couple config directories to the coverage exclusions.
- Removes confusing graph from the pull request comment.
=> Tweak codecov config

library/core/class.form.php
The strip tags behavior should not happen when a developer explicitly adds a sanitized exception.
Closes https://github.com/vanilla/support/issues/1126.
=> Fix reset password link in login form error message

applications/dashboard/controllers/class.utilitycontroller.php
I noticed a permission typo in the utility controller
`Garden.Settings.Manager` instead of `Garden.Settings.Manage`
=> Fix permission typo in utilityController

library/Vanilla/Site/SiteSectionModel.php, library/Vanilla/Web/Page.php, resources/views/default-master.twig, tests/Library/Vanilla/Web/PageTest.php, tests/MinimalContainerTestCase.php, tests/fixtures/src/PageFixture.php
Blocking https://github.com/vanilla/knowledge/pull/1450
- Allows setting `link` tags in addition to `meta` tags on `Vanilla\Web\Page`.
Additionally I've added some test coverage in this repo over `Vanilla\Web\Page`.
=> Add ability to add link tags to Vanilla\Web\Page

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/src/scripts/entries/admin.tsx, applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx, applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx, applications/dashboard/views/modules/configuration.php, library/Vanilla/Web/TwigFormWrapper.php, library/core/class.form.php, library/src/scripts/AppContext.tsx, library/src/scripts/utility/componentRegistry.tsx, tests/Library/Core/FormTest.php, tests/MinimalContainerTestCase.php
Blocking https://github.com/vanilla/vanilla/pull/9797
Closes https://github.com/vanilla/vanilla/issues/9795
- No special endpoints needed. Uses `/api/v2/media`.
- Works in `Gdn_Form`
- directly with `imageUploadReact`.
- in twig.
- in `ConfigurationModule`.
- In `Gdn_Form::simple()`.
- Improves `DashboardImageUploadGroup`
- Offers confirm dialogue while deleting (similar to old image upload in `Gdn_Form`). New translation strings here https://github.com/vanilla/locales/pull/241
- Use the file name as a fallback when the image name is not available.
=> Add `imageUploadReact` to `Gdn_Form`

library/src/scripts/AppContext.tsx, library/src/scripts/headers/TitleBar.tsx, library/src/scripts/headers/TitleBarHome.tsx, library/src/scripts/headers/titleBarNavStyles.ts, library/src/scripts/headers/titleBarStyles.ts, library/src/scripts/layout/TitleBarContext.tsx
This PR add a new context for the title bar only. It doesn't really make sense to be using the media queries for the layout for the title bar. Their layouts have nothing in common.
I do have an idea for a much better way to implement the title bar's breakpoints, but I won't have time this sprint.
=> Added new media query for title bar only

library/src/scripts/features/search/searchBarStyles.ts
Fixed line height, cutting off text in compact search.
=> Fixed line height, cutting off text in compact search.

library/src/scripts/styles/styleHelpersBackgroundStyling.ts
=> [Backport 2019.018] Fix background image default breaking with assetUrl subdirectory

library/src/scripts/styles/styleHelpersBackgroundStyling.ts
Fix typo when checking for image background for theme images.
This would cause our default `data:filter` SVG thing we use in the hero banner to break on sites with a different asset path (eg. hub/node or local subdirectory `vanilla.localhost/dev`).
=> Fix background image default breaking with assetUrl subdirectory

composer.json, composer.lock
This will allow us to use functions from later releases if need be.
=> Add PHP 7.3 and PHP 7.4 polyfills

package.json
When trying to build storybook locally I keep running into problems with the amount of memory allocated to building. Other people probably will have the same problem. This PR will fix it.
=> Bump up the space available to build storybook.

applications/conversations/controllers/api/MessagesApiController.php, applications/conversations/openapi/messages.yml, applications/dashboard/openapi/rich.yml, applications/dashboard/openapi/schemas.yml, applications/vanilla/controllers/api/CommentsApiController.php, applications/vanilla/controllers/api/DiscussionsApiController.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/openapi/comments.yml, applications/vanilla/openapi/discussions.yml, library/Vanilla/EmbeddedContent/Embeds/QuoteEmbed.php, library/Vanilla/Models/FormatSchema.php, plugins/rich-editor/controllers/api/RichApiController.php, tests/APIv2/AbstractResourceTest.php
Currently, our app supports only a subset of formats, but some API endpoints don't check against formats. This PR adds some base tests for formats and makes fixes where appropriate.
Note: I've intentionally left some of the formats we will allow (html, ipb) out of the OpenAPI docs because I want to consider them deprecated.
=> Add API format tests and fixes

library/Vanilla/Web/Asset/LegacyAssetModel.php
Backport https://github.com/vanilla/vanilla/pull/9843
Recent changes made the calling of the style-compat.css not work in subfolders (subcommunities). This PR will address it correctly. The most obvious result of this was extremely large category follow icons on pages.
=> Backport: Fix missing style-compat.css in sub-communities.

library/Vanilla/Web/Asset/LegacyAssetModel.php
This PR will close https://github.com/vanilla/support/issues/1194
Recent changes made the calling of the style-compat.css not work in subfolders (subcommunities). This PR will address it correctly. The most obvious result of this was extremely large category follow icons on pages.
=> Fix missing style-compat.css in sub-communities.

applications/vanilla/js/post.js
When submitting a new discussion, the form submission button is disabled, then re-enabled before the page fully redirects the user to their new discussion. This can present a confusion experience for the user. It is caused by the "complete" handler for the AJAX request, which always runs when the new-discussion form is submitted. This handler always re-enables the submit button.
The button will now only be enabled in certain circumstances that warrant it (basically everything it was doing before, minus the redirect).
1. Create a new discussion with valid values. When clicking the submit button, notice it goes from enabled to disabled and back to enabled, before you are redirected to your new discussion.
1. Checkout this branch.
1. Repeat step one. The submit button should go from enabled …
=> Fix new discussion submit returning during redirect

library/Vanilla/Web/Controller.php
When invoking `Vanilla\Web\Controller::saveUpload`, a call is made to `Gdn_Upload::saveAs`. One of the possible options to this call is the client's original filename. It is not currently used, which means upload-handling addons cannot carry forward the original filename. This update should address that.
=> Add original filename support to API controller uploads

library/Vanilla/Web/MasterViewRenderer.php, library/Vanilla/Web/PageHead.php, library/Vanilla/Web/PageHeadInterface.php, library/Vanilla/Web/PageHeadProxyTrait.php
- Ensure title is always included in the new master view renderings.
- This fixes a crash in Debug mode on new pages.
=> Add missing title on new pages

applications/dashboard/models/class.activitymodel.php, applications/vanilla/controllers/class.vanillasettingscontroller.php, applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, applications/vanilla/views/vanillasettings/posting.php
Creating a notification as the result of some comment or discussion activity can potentially cause an excerpt of the post to display in popup notifications. This is caused by the post content automatically being included as the notification activity's `Story`.
To fix this, we're creating a separate story for emails that will only be temporarily attached to the activity data. Notification popups will no longer display post content. Email notifications will continue to display post content, but now have the option of displaying the full post or a 160-character excerpt.
Please try the following with `deferredNotifications` enabled and disabled.
1. Configure User A's notification preferences to be emailed when someone comments on their discussion, as well as also receiving a popup …
=> Fix post contents displaying in popup notifications

tests/Library/Core/GdnConfigurationTest.php
The `GdnConfigurationTest` test case creates instances of `Gdn_Configuration`. By default, this class will attempt to save its data, if necessary, [as part of its `__destruct` routine](https://www.php.net/__destruct#language.oop5.decon.destructor). Saving the config involves firing an event ("BeforeSave"), which requires retrieving the plug-in manager from the container. If an instance of `Gdn_Configuration` has its `__destruct` routine invoked when the container has not been properly configured, such as during library tests, a fatal error will be generated.
The fix here is simple: avoid trying to auto-save the config as part of `__destruct`. This is a matter of setting the instance's `autosave` property to `false`. The relevant library tests have been updated to do so.
=> Fix tests sometimes throwing NullContainer exceptions

plugins/Akismet/class.akismet.php, plugins/StopForumSpam/class.stopforumspam.plugin.php
Changed stopforumspam and akismet plugins to use https rather than http.
Tested each plugin on localhost.
Closes issue [https://github.com/vanilla/vanilla/issues/9744](url)
Closes issue [https://github.com/vanilla/vanilla/issues/9745](url)
=> Use https with spam detectors

tests/Library/Garden/Web/DataTest.php
I added tests that cover the Data class as well as the Meta trait and JsonFilter trait.
I don't know why the codecov test claims it will decrease code coverage.
=> Add tests for Data class methods

applications/dashboard/models/class.usermodel.php
The `time()` function does not take any arguments and supplying one causes issues in later versions of PHP. Basically, this was fixing a typo.
=> Fix call to time() in user model

library/Garden/ArrayContainer.php, library/Vanilla/Addon.php, library/core/class.autoloader.php, library/core/functions.deprecated.php, library/core/functions.general.php
Now that our code coverage of functions.general.php is in good shape I’ve added some ignore directives for areas that we just can’t hit.
In doing that I wanted to clean up some lint errors because I find it easier to not introduce new ones if an entire file is in a clean state.
Our old `Gdn_Autoloader` class has not been used for some time so I’m marking it as deprecated.
=> Fix some lint errors and code coverage

build/.storybook/config.js, library/src/scripts/AppContext.tsx, library/src/scripts/__tests__/testStoreState.ts, library/src/scripts/content/CollapsableContent.tsx, library/src/scripts/layout/PanelLayout.story.tsx, library/src/scripts/layout/PanelLayout.tsx, library/src/scripts/layout/ScrollOffsetContext.tsx, library/src/scripts/layout/bodyStyles.ts, library/src/scripts/layout/panelAreaStyles.ts, library/src/scripts/layout/panelLayoutStyles.ts, library/src/scripts/redux/ReduxActions.ts, library/src/scripts/redux/getStore.ts, library/src/scripts/storybook/StoryContext.tsx, library/src/scripts/storybookConfig.tsx, library/src/scripts/styles/styleUtils.ts, library/src/scripts/theming/ThemeProvider.tsx, packages/vanilla-dom-utils/src/shadowDom.tsx
Closes https://github.com/vanilla/knowledge/issues/1434
- Update our storybook config to allow the new story format. [Component Story Format](https://storybook.js.org/docs/formats/component-story-format/)
- Add a new storybook utility `storyWithConfig()` that makes it easier to:
- Make a story use a specific redux state.
- Opt out of the outer storybook wrappers.
- Make a story use some particular theming variables.
- Panel layout is now in storybook.
- Side panels are now scrollable separate from the main page content.
- Customer request https://github.com/vanilla/knowledge/issues/1434
- I implemented a similar scrolling system previously for our dashboard https://github.com/vanilla/vanilla/pull/8490
- Linear gradients are used to show that some content is not visible (similar to our …
=> Enhance Panel Layout and add to Storybook

library/Vanilla/Web/CacheControlMiddleware.php, tests/Library/Vanilla/Web/CacheControlMiddleWareTest.php
I added tests for the CacheControlMiddleWare methods (except for sendCacheControlHeaders()).
Partially addresses #9869
=> Add tests for CacheControlMiddleWare

library/Vanilla/Web/ApiFilterMiddleware.php, tests/Library/Vanilla/Web/ApiFilterMiddlewareTest.php
Added the getBlacklistFields() method to the ApiFilterMiddleware class as well as adding tests for the class methods. 
Partially addresses #9869
=> Add tests for ApiFilterMiddleware

library/SmartyPlugins/function.hero_image_link.php
Fixes a bug preventing the legacy smarty banner image call from working.
For whatever reason calling smarty function from another smarty function gives an error.
=> Fix banner image legacy fallback

library/src/scripts/features/tiles/tilesStyles.ts, library/src/scripts/styles/styleHelpersBackgroundStyling.ts
Fixes 2 small bugs:
-  The left alignment wasn't working for tiles
- Added optional opacity property on background image to make it more subtle.
=> Added opacity property to background image options and fixed alignment issue with tiles

applications/vanilla/models/class.categorymodel.php
closes https://github.com/vanilla/support/issues/1234
in [class.categorymodel.php#L2540](https://github.com/vanilla/vanilla/blob/92bfca055e907b38d30f65a1512b7a3307246f86/applications/vanilla/models/class.categorymodel.php#L2540)
we are calling self::calculate($category); without checking if we have a category returned from  `$category = self::categories(val('PermissionCategoryID', $category)); `this is resulting in a fatal error when categoryModel::Calculate is called that requires $category to be an array
=> Fix getting the permissions for a category with an invalid permission category ID

applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx, library/src/scripts/forms/buttonStyles.ts, library/src/scripts/layout/bodyStyles.ts, library/src/scripts/layout/panelAreaStyles.ts, library/src/scripts/layout/panelLayoutStyles.ts, library/src/scripts/theming/themeCardStyles.ts
- Fix panel layout sometimes clipping dropdowns inside of them.
- Fix panel layout having weird top offset @slafleche Not really sure why these were added, but they break the layout calculations I was doing.
- Fix active/hover/focus border color for primary buttons. I consulted with @ElisaAlmeida for this.
- Fix layout issue in the theme preview card
=> Fix panel layout overflows and stickiness

applications/vanilla/controllers/api/DiscussionsApiController.php
This is a patch to ensure that discussion names don't display html entities when using the quoting functionality.  There's a been a history of discussion names not being displayed correctly and at the moment no elegant solution has been proposed.
note: this has been tested to ensure it doesn't open up any xss vulnerabilities, but should be tested by any reviewers.
closes https://github.com/vanilla/vanilla/issues/9837
=> Fix encoded discussion name in quotes

applications/dashboard/controllers/class.entrycontroller.php, applications/dashboard/controllers/class.homecontroller.php
Fixes https://github.com/vanilla/support/issues/1130
This PR sets some canonical URLs to match their commonly linked to versions throughout the application.
It sets the following as canonical URLs on their methods.
- /entry/signin
- /home/termsofservice
- /entry/passwordrequest
I could have updated the method names, because PHP is case-insensitive with those,  but I didn't want to leave behind a bunch of methods that were cased incorrectly.
=> Fix canonical URLs on entry controller

library/core/class.form.php, tests/Library/Core/FormTest.php
Closes https://github.com/vanilla/vanilla/issues/9070
To quickly test without burp-suite, add the following to Vanilla\Formatting\Quill\Parser.php:150
```php
$errMessage = "JSON could not be converted into quill operations.\n <script>alert(document.cookie);</script> $json";
throw new FormattingException($errMessage);
```
We weren't sanitizing validation results when we merged them in from some other `Gdn_Validation` instance (which doesn't do it's own sanitization).
- Make sure all merged validation errors go through `addError()`.
- Update `addError` to
- Escape plain strings.
- Stop stripping tags on items that we are calling `htmlspecialchars()` on.
- Add tests for the sanitization of validation results.
**Other Implementations**
I had initially tried to just add sanitization in the …
=> Escape output of Gdn_Form error items

library/Garden/Events/ResourceEvent.php, tests/Library/Garden/Events/ResourceEventTest.php, tests/fixtures/src/Events/TestResourceEvent.php
This update adds a very simple class that will be used for creating [PSR-14-style events](https://www.php-fig.org/psr/psr-14/) for basic resource operations (e.g. adding a discussion, deleting a comment, registering a user).
=> Add basic class for simple resource events

library/src/scripts/Router.tsx, library/src/scripts/layout/panelAreaStyles.ts, library/src/scripts/layout/panelLayoutStyles.ts, library/src/scripts/navigation/breadcrumbsStyles.ts
Fixes https://github.com/vanilla/knowledge/issues/1475
- Fix paddings and offsets in the panel layout
- Bottom margin converted to an inner padding. Height was adjusted for consistency
- Scroll to the top on history URL change (this used to happen automatically in chrome, but was removed in a recent chrome update).
- Add a min-height to breadcrumbs to prevent 1px off error when displaying loader
- Add min-height to breadcrumbs
- Add a little extra theme caching for functions called that create classes. This prevents the classes from being recreated over and over again if they have the same parameters.
=> Fix panel scrolling issues

library/src/scripts/layout/Heading.tsx, library/src/scripts/layout/PageHeading.tsx, library/src/scripts/loaders/LoadingRectanges.story.tsx, library/src/scripts/loaders/LoadingRectangle.tsx, library/src/scripts/loaders/loadingRectangeStyles.ts, library/src/scripts/navigation/BreadcrumbsLoader.tsx, library/src/scripts/storybook/StoryContext.tsx, library/src/scripts/styles/typographyStyles.ts
**_This PR includes all of https://github.com/vanilla/vanilla/pull/9922. Once that is merged, I will retarget this PR._**
- Add some nice typing for storybook variables.
- Expand various heading components to allow a ReactNode for their contents (so you can put a loader in them).
- Add a new `<RectangleLoader />` and spacers. See the new stories that were added.
=> Add new components for creating custom loaders

applications/vanilla/controllers/api/CommentsApiController.php, applications/vanilla/controllers/api/DiscussionsApiController.php, plugins/rich-editor/RichEditorPlugin.php, plugins/rich-editor/src/scripts/entries/admin.ts, plugins/rich-editor/src/scripts/mountEditor.tsx
With https://success.vanillaforums.com/kb/articles/144-release-2020-001#api-v2 going out we are likely to begin seeing more lowercase usages of Rich throughout existing parts of the application.
Unfortunately not everything was:
- Using the constant.
- Doing a case-insensitive comparison.
I've updated some case-sensitive checks to now be case-insensitive & used the constant in a few places it wasn't in use.
=> Apply more case-insensitive format checks for rich

plugins/rich-editor/src/scripts/quill/ClipboardModule.ts, plugins/rich-editor/src/scripts/quill/MarkdownModule.test.ts, plugins/rich-editor/src/scripts/quill/MarkdownModule.ts, plugins/rich-editor/src/scripts/quill/VanillaTheme.ts, plugins/rich-editor/src/scripts/toolbars/InlineToolbar.tsx
Fixes https://github.com/vanilla/vanilla/issues/9912
Fixes https://github.com/vanilla/vanilla/issues/9914
- Fixes the double space inserted after an inline markdown macro. https://github.com/vanilla/vanilla/issues/9912
- Fix scroll jumping when creating a link https://github.com/vanilla/vanilla/issues/9914
=> Fix markdown macro issues and link scroll jumping issues

packages/vanilla-polyfill/index.js, themes/theme-boilerplate/src/scss/sections/_header.scss
Bumps up specificity and fixes bad value for CSS logo style.
Added missing polyfills for append/prepend.
Fixes bugs for https://github.com/vanilla/support/issues/1190
=> IE 11 - Bumped up specificity and fixed CSS prop for logo

applications/conversations/settings/structure.php, applications/vanilla/settings/structure.php, library/core/class.proxyrequest.php
The versions in the addon.jsons are never updated, and had only 1 usage.
I've switched the curl wrapper to use the environment version, which should be more up-to-date, and remove this extra step of saving versions into the config.
=> Remove unneeded versions and just use the environment version

library/Vanilla/ImageResizer.php
Fixes https://github.com/vanilla/vanilla/issues/9927
PNGs and ICO files need to have additional properties applied to the **destination** image in order for for them to save properly with transparency.
Unfortunately, even though so some other code in `Gdn_Upload` was applying these properties, using `imagecreatetruecolor()` creates a _**new image**_ and requires the properties to be set again.
=> Allow image transparency when resizing images using GD

library/src/scripts/headers/TitleBar.tsx, library/src/scripts/navigation/breadcrumbsStyles.ts
Fixes https://github.com/vanilla/support/issues/1133
- The breadcrumbs had a 1 pixel overflow. I couldn't really figure out why it was happening, but it had also been causing issues for the panel layout, which I resolved with a min-height on the list in https://github.com/vanilla/vanilla/pull/9922
- I also noticed while testing in IE11 that the titlebar background class wasn't being applied. Changing the way we applied it fixed the issue
=> Fix breadcrumb scrolling issue

applications/dashboard/controllers/class.entrycontroller.php
A client is currently unable to pass roles via SSO because Vanilla's SSO is using "Roles" and does not accept "roles" (in lower case).
I initially hid this feature behind a feature flag, however, I felt it was a bit extreme. In this change, I am also making sure that "roles" does not take over "Roles" if both are set.
Estimate request: https://github.com/vanillaforums/estimates/issues/886
Project: https://github.com/vanillaforums/sonicwall/issues/10
To test this change, you will need to have SSO setup locally. I followed the directives from both repositories below.
https://github.com/vanilla/vanilla-docker
https://github.com/vanilla/stub-sso-providers
=> Translate "roles" into "Roles" when passing roles over SSO.

applications/dashboard/controllers/class.entrycontroller.php
Backport: https://github.com/vanilla/vanilla/pull/9905
A client is currently unable to pass roles via SSO because Vanilla's SSO is using "Roles" and does not accept "roles" (in lower case).
I initially hid this feature behind a feature flag, however, I felt it was a bit extreme. In this change, I am also making sure that "roles" does not take over "Roles" if both are set.
Estimate request: https://github.com/vanillaforums/estimates/issues/886
Project: https://github.com/vanillaforums/sonicwall/issues/10
To test this change, you will need to have SSO setup locally. I followed the directives from both repositories below.
https://github.com/vanilla/vanilla-docker
https://github.com/vanilla/stub-sso-providers
=> Backport: Translate "roles" into "Roles" when passing roles over SSO.

applications/dashboard/controllers/api/ThemesApiSchemes.php, library/Vanilla/Models/ThemeModel.php
This updates the POST\PATCH themes endpoints so that assets can be passed as an array or string. This lines up with the GET response.
required for https://github.com/vanilla/internal/pull/2184
related to https://github.com/vanilla/internal/issues/2140
=> Update to allow post\patch endpoints to allow assets parameter to be array

applications/vanilla/views/categories/discussions.php
Closes https://github.com/vanilla/support/issues/275
The issue It's not keystone related actually, it's just how this view works (disable the theme and you will see the same behavior).
The view doesn't render categories who have no discussions. Since you can't add discussions to categories type "Nested", it ignores them: https://github.com/vanilla/vanilla/blob/9dda0f328015a74cd88a3a54f0a66ad5addd76e8/applications/vanilla/views/categories/discussions.php#L17
**Notes:** The view seems to flat the category tree when rendering so I've just followed the same logic.
=> Display categories with no discussions on "Mixed" layout

library/setup/ComposerHelper.php
Reported by ops.
The `dist` directory is current created by the build if it doesn't exist, but on infra this step runs before the build.
That means on a fresh data server with no dist directory created this part of the build will fail.
=> Fix creation of vendor licenses when dist directory doesn't exist

applications/vanilla/models/class.discussionmodel.php, plugins/Quotes/class.quotes.plugin.php
closes https://github.com/vanilla/support/issues/195#issuecomment-576496613
When member level users quote inside a group, they are being caught by 'Vanilla.Discussions.View' permission on the 'Social Groups' category.
This PR overrides that permission.
- Create a group/discussion (with group view permission revoked for members)
- as a member, quote a comment.
=> Fix permission check when using quotes

library/src/scripts/theming/ThemePreviewCard.tsx, library/src/scripts/theming/themePreviewCardStyles.ts
Fixes a bug that would cause the action menu in the theme card from getting cut off by it's surrounding container.
**Due to the indentation change I recommend viewing the diff with this link https://github.com/vanilla/vanilla/pull/9980/files?utf8=%E2%9C%93&diff=split&w=1**
=> Prevent theme card menu from overflowing container

applications/dashboard/controllers/api/AbstractApiController.php, applications/dashboard/models/class.usermodel.php, applications/vanilla/Events/DiscussionEvent.php, applications/vanilla/Schemas/CategoryFragmentSchema.php, applications/vanilla/Schemas/PostFragmentSchema.php, applications/vanilla/controllers/api/DiscussionsApiController.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.discussionmodel.php, library/Vanilla/ApiUtils.php, library/Vanilla/ExtensibleSchemasTrait.php, library/Vanilla/Formatting/FormatFieldTrait.php, library/Vanilla/SchemaFactory.php, library/Vanilla/Utility/ModelUtils.php, library/Vanilla/Web/Controller.php, library/core/class.model.php, tests/Library/Vanilla/SchemaFactoryTest.php, tests/Models/DiscussionModelTest.php
This update introduces [PSR-14-style events](https://www.php-fig.org/psr/psr-14/) for discussion-write operations (insert, update, delete). To ensure discussion event data shared the same shape as Vanilla's public API v2, some refactoring has been done to allow the code to be more easily shared between models and controllers. That refactoring represents the bulk of the changed lines here. Mostly, the individual lines of code have been unaltered as they were moved from one area to another. Original methods have been left in place, but use new methods internally, to ensure backwards compatibility. Tests have been added for the newer functionality, including verifying events have been dispatched.
Relates to vanilla/internal#2142
=> Add PSR-14 events for discussion write operations

library/Vanilla/SchemaFactory.php, tests/Library/Vanilla/SchemaFactoryTest.php
A typo in `SchemaFactory::prepare` caused an event to not be dispatched when expected. The bug is fixed here by checking the proper variable and tests have been implemented to protect against regressions of the behavior.
=> Fix SchemaFactory not firing events on schema objects

library/src/scripts/Router.tsx, library/src/scripts/analytics/AnalyticsData.tsx, library/src/scripts/bootstrap.ts, library/src/scripts/pageViews/pageViewTracking.spec.ts, library/src/scripts/pageViews/pageViewTracking.ts
- Fixes `pageViewWithContext` firing too often.
- Fired even when hash changed.
- Was firing any time data object changed. Should only have been firing when the uniqueKey changed. As a result every article preload while looking at the article page triggered a page view.
- Fixes `onPageView` handlers never being called (registration was missing).
- Refactor onPageView to handle unregistering events by using built-in JS event system.
- Adds additional unit tests for page views.
- Expose the `onPageView` event so that it can be used by customers in a javascript theme asset.
=> Fix analytics events firing incorrectly

library/Vanilla/Models/FsThemeProvider.php, library/src/scripts/features/tiles/tilesStyles.ts, library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts, library/src/scripts/styles/styleHelpersColors.ts, tests/APIv2/ThemesTest.php
- Fix theme API index not returning the current theme if it's hidden.
- Fix Tiles (KB chooser) not having padding on mobile.
- Fix TitleBar compact search having a poorly calculated BG color with our default tiltebar color.
=> Fix various theming issues

library/core/functions.validation.php, tests/Library/Core/ValidateRequiredTest.php
Please make sure these points are completed:
Along with vanilla/internal#2197, this will close issue vanilla/support#1239
The updated comboBreaker data was not being saved to the db. 
Because the badge status was an empty string and didn't have a default value of null, it was not passing validation. This fix adds logic to validateRequired() in functions.validation that allows it to pass validation.
* Open the GDN_UserBadge table
* Give a user a badge
* Verify that the Attributes field for the comboBreaker badge (BadgeID = 3) updates with a new event
* Give that user 4 more badges
* Verify that the status field for the comboBreaker badge switches from NULL to given
=> Insert logic to validate empty string where the default is not null

tests/Bootstrap.php
`SchemaFactory` has some static properties set that were persisting between test suites. This was causing errors, so the properties will now be reset as part of the testing cleanup routine.
=> Fix polluted SchemaFactory dependencies in tests

applications/dashboard/src/scripts/entries/forum.tsx, library/src/scripts/theming/ThemeProvider.tsx
Fixes https://github.com/vanilla/support/issues/1337
Fixes https://github.com/vanilla/support/issues/1338
Fixes https://github.com/vanilla/support/issues/1339
We were not doing a proper check before applying the compatibility backgrounds styles. These should only be applied in the forum, when the proper theme feature flag is applied.
=> Fix theme reset from getting applied to old themes

build/scripts/utility/moduleUtils.ts
These directories are quite large, unneeded, and are causing size issues in our deployment bundle.
=> Exclude unneeded monaco directories

applications/dashboard/views/log/table.php
Issue reported here: https://github.com/vanillaforums/mse/issues/64#issuecomment-578261937
During implementation, I think there was one step missing, where mods/admins could click on the record link and it would take the user to the record's "change history".
=> Change log deleted record url

applications/dashboard/controllers/class.entrycontroller.php
closes https://github.com/vanilla/support/issues/1343
=> Fix HTML being unnecessarily encoded in form error messages

library/Vanilla/Formatting/FormatService.php, library/Vanilla/Formatting/Formats/HtmlFormat.php, tests/Library/Vanilla/Formatting/Formats/AbstractFormatTestCase.php
Filters out emoji images when parsing image urls.
closes vanilla/support#1236
related to https://github.com/vanilla/support/issues/1236
=> Filter emojis when parsing Image Urls in HtmlFormatter

applications/dashboard/src/scripts/entries/common.tsx, library/src/scripts/embeddedContent/embedService.tsx, library/src/scripts/modal/Modal.tsx, packages/vanilla-react-utils/src/mounting.spec.tsx, packages/vanilla-react-utils/src/mounting.ts
Fixes https://github.com/vanilla/support/issues/1354
_Note: Reproducing this issues requires a production build. To run one quickly, disable hot reload config, and run `yarn build --debug`_
- When we added the theme preview card, we used mountModal.
- mountModal tries takes over the entire modal container.
- The actual Modal component did not have the unmounting behaviour of mountModal, so it would try to render into the container before clearing it.
- This caused a fatal react error, because react does not automatically call `unmountComponentAtNode` when using `React.createPortal`
- This never showed up in developer builds because the load order of modules is not the same.
The fix
- Extract a new function mountPortal, that cleans up the mounting container and attaches to the end of the …
=> Fix convert to discussion being broken

applications/dashboard/src/scripts/forms/DashboardFormSubheading.tsx, applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx, library/Vanilla/Theme/ThemeFeatures.php, library/src/scripts/banner/Banner.tsx, library/src/scripts/banner/banner.story.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/forms/buttonStyles.ts, library/src/scripts/icons/common.tsx, library/src/scripts/loaders/ButtonLoader.tsx, library/src/scripts/styles/globalStyleVars.ts, library/src/scripts/styles/styleHelpersSpinner.ts
_**See [Changed Chromatic Diffs Here](https://www.chromaticqa.com/build?appId=5d5eba16c782b600204ba187&number=2033)**_
KB side of the PR https://github.com/vanilla/knowledge/pull/1501
Closes https://github.com/vanilla/knowledge/issues/1480
After discussion w/ Todd there were a few changes that needed to be made with the Banner.
- Responsiveness of the component needs some improvement.
- Content image and text now have fixed min-widths, and content image will be pushed off the screen as it shrinks. Variable breakpoint to make it disappear entirely has been added.
- Allow backgroundImage and contentImage to exist at the same time.
- Rename the props of the new banner `contentImage`.
- Rename the existing `image` props to `backgroundImage`.
- Story is updated with linear-gradient as the …
=> Prepare new banner variables for use in custom themes

library/core/functions.compatibility.php
We have a few really old compatibility functions that haven't been necessary for several years. This code removes them.
- `array_column()`: PHP 5.5+.
- `hash_equals()`: PHP 5.6+
- `parse_ini_string()`: PHP 5.3+ haha
=> Remove some compatibility functions that are no longer needed

plugins/googlesignin/class.googlesignin.plugin.php
Closes https://github.com/vanilla/support/issues/437
The issue was described as Keystone related but it actually happens in the `GoogleSignInPlugin` class.
To test the issue first make sure you have "Google SignIn" enabled and configured.
=> Fix Signin and Register buttons when Googlesignin is default method

applications/dashboard/design/admin.css, applications/dashboard/scss/src/_type.scss, library/src/scripts/errorPages/CoreErrorMessages.tsx
- Fixes style specificity for subheadings.
- Fixes core error messages not respecting the `defaultError` code.
=> Fix subheading spacing and error message tilles

library/Vanilla/Scheduler/DummyScheduler.php, tests/Library/Vanilla/Scheduler/SchedulerTest.php, tests/fixtures/src/Scheduler/ParentJob.php
`DummyScheduler::dispatchAll` currently executes its jobs by running a `foreach` on its internal tracking slips array. Since `foreach` runs on a copy of the array by default, any new jobs queued up during execution of the queue will be ignored.
This update adds a simple [generator function](https://www.php.net/manual/en/language.generators.syntax.php) to `DummyScheduler` for accessing the internal tracking slips array in way that will allow iteration to include new items.
=> Fix DummyScheduler not running child jobs

applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, tests/Models/DiscussionModelTest.php
closes https://github.com/vanilla/support/issues/1309
When a post gets sent to moderation after being edited->saved, the post is missing InsertUserID and DateInserted.
whenever a plugin hooks into https://github.com/vanilla/vanilla/blob/03eba20c06cf9678556c4b87cc964f5ee1fdfb86/applications/vanilla/models/class.commentmodel.php#L1148, $commentData is missing InsertUserID and DateInserted. If a post goes to moderation and then it gets approved, the post gets overwritten here https://github.com/vanilla/vanilla/blob/cb23d99019c198ea2f7aeeb903f8a93eaa615b07/applications/dashboard/models/class.logmodel.php#L967 with the missing information.
There is also another bug that was introduced in https://github.com/vanilla/vanilla/pull/9944 when creating a discussion, if a discussion gets sent to …
=> fix adding required user fields when approving a post from moderation

library/core/class.smarty.php
Currently, Smarty uses the directory of the template being rendered as the root path for included partials. This currently has two issues:
1. If the template is specified using the `file:` protocol then the function will fail. **This is fixed with a specific logic check.**
2. If some other protocol is used then a nonsense path is used. **This is fixed by falling back to the theme’s view path.
=> Add a sensible default Smarty template directory

packages/vanilla-react-utils/src/mounting.tsx, plugins/rich-editor/src/scripts/mountEditor.tsx
Add a new mounting option to cleanout the contents of the target before mounting.
This is best used when mounting over placeholders.
=> Fix editor mounting

library/src/scripts/embeddedContent/embedService.tsx, packages/vanilla-react-utils/src/mounting.tsx
Fixes https://github.com/vanilla/vanilla/issues/10053
Due to their odd integration with quill blots, the embed contents cannot work in the shared portal system, and needs independant renders.
I've added a flag to bypass the shared portal rendering and applied to the embeds.
=> Fix embeds double rendering

library/src/scripts/headers/TitleBar.tsx
- Fix left alignment of mobile logo theme variable (stopped working after a refactor).
- Remove collision detection from left aligned navigation variables. It is not absolute positioned in these scenarios and gets triggered too aggressively.
=> Fix titlebar alignment and collision detection

applications/dashboard/controllers/class.settingscontroller.php
The translations are complete, but the codes aren’t being used.
=> Add email setting translation strings

build/.storybook/config.js, library/Vanilla/Formatting/BaseFormat.php, library/src/scripts/content/TruncatedText.tsx, library/src/scripts/forms/buttonStyles.ts, library/src/scripts/headers/titleBarStyles.ts, library/src/scripts/homeWidget/HomeWidget.story.tsx, library/src/scripts/homeWidget/HomeWidget.tsx, library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts, library/src/scripts/homeWidget/HomeWidgetContainer.tsx, library/src/scripts/homeWidget/HomeWidgetItem.styles.ts, library/src/scripts/homeWidget/HomeWidgetItem.tsx, library/src/scripts/layout/PanelLayout.story.tsx, library/src/scripts/result/Result.tsx, library/src/scripts/storybook/storyData.ts, library/src/scripts/storybookConfig.tsx, library/src/scripts/styles/globalStyleVars.ts, library/src/scripts/styles/styleHelpersBorders.ts, library/src/scripts/styles/styleUtils.ts, packages/vanilla-react-utils/package.json, packages/vanilla-react-utils/src/useMeasure.ts
Closes https://github.com/vanilla/knowledge/issues/1489
___[See the stories.](https://www.chromaticqa.com/build?appId=5d5eba16c782b600204ba187&number=2104)___
- `<HomeWidgetContainer />` - Handle paddings, backgrounds, and grid.
- `<HomeWidgetItem />` - Handle view layout and option of individual items in a home widget.
- `<HomeWidget />` - Combine the previous 2 widgets with some extra capabilities.
- [Text only items](https://www.chromaticqa.com/snapshot?appId=5d5eba16c782b600204ba187&id=5e408602475c230022c19aa7)
- [Image items](https://www.chromaticqa.com/component?appId=5d5eba16c782b600204ba187&name=Home%20Widget&buildNumber=2104&specName=Container%20With%20Image)
- [Edge Cases with item variance](https://www.chromaticqa.com/component?appId=5d5eba16c782b600204ba187&name=Home%20Widget&b …
=> Implement home widget components and stories

library/Vanilla/Models/LimitedPipelineModel.php
Implement limited pipeline model for specific cases when full DB operations are not welcome 
and we need to operate against few specific fields only.
Relates to: https://github.com/vanilla/knowledge/issues/1517
=> Implement limited pipeline model for specific cases

applications/dashboard/views/debug.tpl, applications/dashboard/views/debug_vars.tpl, library/core/class.smarty.php, tests/Library/Core/SmartyTest.php
The smarty `{debug}` function outputs useful information for debugging. However, if this function is accidentally left on then sensitive information will leak.
This PR does the following:
- Effectively disables the `{debug}` function by overriding its template to give a deprecation notice. This was done because I couldn’t find a way to change its behavior.
- Adds another `{debug_vars}` function that does some basic sanitization of variables before rendering them. It uses a modified version of the built in smarty debug console that has some nicer styling and only outputs assigned variables.
Closes https://github.com/vanilla/vanilla-patches/issues/661
=> Sanitize variables during smarty debug

library/src/scripts/banner/banner.story.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/layout/components/containerStyles.ts
Closes https://github.com/vanilla/vanilla/issues/10066
Fixes banner image overflow cutting off the search results.
The new calculations are more complex but deliver the same behaviour as before. I've added additional stories and breakpoints for stories so due to the more complex behaviour.
=> Fix banner overflow

applications/vanilla/controllers/class.categoriescontroller.php, library/Vanilla/Contracts/Site/SiteSectionInterface.php, library/Vanilla/Site/DefaultSiteSection.php, tests/fixtures/src/MockSiteSection.php
Related to https://github.com/vanilla/support/issues/1411
- When no ID is provided to the categories controller index, check the site section and see if it has a contextual ID in it's attributes.
- Add attributes method to site section interface.
=> Update categories page to load a CategoryID from the current site section

applications/vanilla/models/class.commentmodel.php
After vanilla/vanilla#9944, we're calculating whether there are new comments based on dates rather than comment counts. This caused a user's own comment to discussions display as new to that user. This PR fixes that problem by updating the DateLastViewed field in the user_discussion table whenever a user makes a comment.
1. Before checking out branch, make a comment on a discussion. 
1. Go to Discussions page and verify that the discussion displays as new.
1. Checkout branch, repeat steps 1 and 2, and verify that the discussion doesn't display as new.
=> Fix Users' Own Comments Appearing to them as New

applications/vanilla/modules/class.newdiscussionmodule.php
Closes vanilla/support#1347
The New Discussion display buttons were not being translated. This fixes that by using the LocaleInterface with the NewDiscussion class.
* View forum in a locale other than en and verify that the buttons are still in English.
* Check out branch, view the forum in a locale other than English and verify that the buttons are in the selected language.
=> Fix NewDiscussionModule to ensure translation of button text

plugins/stubcontent/class.stubcontent.plugin.php
Closes https://github.com/vanilla/support/issues/1412
The issue happens because **Stub Content** checks for the config `Garden.Installed` before adding the content, and all those communities (for whatever reason I couldn't find why) have this config set to `'1'` instead of `true`.
I've made a fix which reenforces this check so it doesn't happen again.
=> Fix Stub Content re-adding content by re-enforcing the check for Garden.Installed

applications/dashboard/src/scripts/entries/forum.tsx, library/src/scripts/theming/ThemeProvider.tsx
If the theme provider was mounted twice it would delete the theme header and footer.
I've added some checks to prevent it from double mounting, and an removed an unnecssary app context.
=> Prevent duplicate mounting of theme provider

library/Vanilla/Formatting/DateTimeFormatter.php, tests/Library/Vanilla/Formatting/DateTimeFormatterTest.php
- Trigger notices instead of warnings.
- Add a third parameter for empty/null fallbacks.
- Allow the method to return null instead of just an integer.
Closes #9489
=> Relax DateTimeFormatter::dateTmeToTimesStamp()

applications/vanilla/views/modules/helper_functions.php
Closes vanilla/support#723.
This fixes double html encoding in of content in the Promoted Content Module.
=> Fix html double-encoding in Promoted Content Module

applications/vanilla/models/class.discussionmodel.php, applications/vanilla/views/vanillasettings/posting.php
Closes vanilla/support#343
The minimum length configuration setting previously applied to comments, but not the original post of a discussion. Since users expect that that setting would apply to the original post as well as comments, this fix implements that.
1. On master, set a minimum post length and start a discussion where the body is shorter than the min.
1. Observe that the discussion passes validation.
1. Checkout branch, repeat steps 1 and 2, and verify that the 'This discussion is x characters too short' error message displays.
=> Add minimum length validation rule for the original post of a discussion

applications/dashboard/modules/class.sitetotalsmodule.php
`tryRecalculate` had a bug where it was trying to match with `true` but if the `mt_rand(0, 999999)` returns `0` it would fail.
=> Refactor tryRecalculate lock condition

.circleci/config.yml
Old accepted stories keep appearing in new PRs. This seems to be the cause of 2 things.
- The old version of orb 1.0.1 that we're using passes the wrong flag (`--accept-all` instead of `--auto-accept-changes`). Unfortunately the only version that passes the correct flag doesn't support using a secure environment variable for configuring chromatic.
- Manual PR approvals don't work with squash merges, because the "approved" commit never makes it master branch. Instead a new unapproved change is applied. Talking to CircleCI support, the proper solution is to add `--auto-accept-changes` when calling chromatic.
It came to my attention that the orb we are using is not actually an official chromatic one, because they currently don't have one. I've passed along the feature request through their …
=> Fix chromatic not working with squash merges

plugins/Akismet/class.socketwriteread.php
closes https://github.com/vanilla/support/issues/1393
we recently upgrade akismet to use port 443 https://github.com/vanilla/vanilla/pull/9864
but we didn't prefix the host in  fscoketopen with 'ssl://'
[Get a dev akismet api key](https://akismet.com/account)
You can debug this locally to test if your key passes validation.
Ref. https://akismet.com/development/api/#verify-key
=> prefix akismet host with ssl

applications/vanilla/views/modules/helper_functions.php
Backport https://github.com/vanilla/vanilla/pull/10080
Closes vanilla/support#723.
This fixes double html encoding in of content in the Promoted Content Module.
=> Backport: Fix html double-encoding in Promoted Content Module 

library/src/scripts/banner/Banner.tsx, library/src/scripts/content/TruncatedText.tsx, library/src/scripts/flyouts/dropDownStyles.ts, library/src/scripts/homeWidget/HomeWidget.story.tsx, library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts, library/src/scripts/homeWidget/HomeWidgetContainer.tsx, library/src/scripts/homeWidget/HomeWidgetItem.styles.ts, library/src/scripts/homeWidget/HomeWidgetItem.tsx, library/src/scripts/layout/Heading.tsx, library/src/scripts/layout/PageHeading.tsx, library/src/scripts/layout/components/Container.tsx, library/src/scripts/layout/components/containerStyles.ts, library/src/scripts/layout/heading.story.tsx, library/src/scripts/navigation/NavLinks.tsx, library/src/scripts/navigation/NavLinksWithHeadings.tsx, library/src/scripts/navigation/navLinksStyles.ts, library/src/scripts/navigation/navLinksWithHeadings.story.tsx, library/src/scripts/storybook/StoryContext.tsx
Working Towards https://github.com/vanilla/knowledge/issues/1516
This PR adjusts a lot of spacing in the nav links and home widget in order to accomplish the styles in the following mockups:
- https://zpl.io/bJxP9kJ
- https://zpl.io/VY7jG9L
- https://zpl.io/bAQgWL6
In order to accomplish this I've needed to adjust the CSS on a few components.
- Refactor `<Heading />` component as discussed with @slafleche. It now applies default sizes to all heading levels, not just level 1s. `displayDepth` is still respected.
- Refactor spacing & margins & fonts in `<NavLinksWithHeadings />`.
- Uses "half" size gutters with extended outside instead of double width gutters. This made the sizing much easier to port to home widget.
- Add new smaller width option to to `<Container />`
- Apply `<Container />` …
=> All home widget to be styled as nav links

library/src/scripts/headers/titleBarStyles.ts
- Fix compact search background in full bleed mode.
- Fix foreground color for linkButtons in the titleBar.
- Fix padding from full bleed titlebar cutting off banner.
=> Fix title bar styles with full bleed

library/Vanilla/Models/FsThemeProvider.php
If you set a logo in a theme:
```
"titleBar": {
"logo": {
"desktop": {
"url": "/addons/themes/lavendermoon/design/knowShare.png"
},
"mobile": {
"url": "/addons/themes/lavendermoon/design/knowShare.png"
}
},
}
```
It's only supposed to be taken if there is no logo set through the dashboard. The theme always took precedence. I updated the logic to allow the overwrite.
=> Fixed bug where the theme's logo was not overwritable

applications/vanilla/models/class.discussionmodel.php, library/Vanilla/Contracts/Formatting/FormatFieldInterface.php, library/Vanilla/Formatting/FormatFieldTrait.php
closes https://github.com/vanilla/support/issues/1425
This PR adds FormatFieldInterface that has [formatFieldTTrait ](https://github.com/vanilla/vanilla/blob/578ccf1ac33fb6da5d0d0caec460db75bb10e0e6/library/Vanilla/Formatting/FormatFieldTrait.php#L19)method signatures. This will allow us to use it with the container.(Container does not support using traits).
=> add formatFieldInterface to use with a container rule

applications/vanilla/models/class.discussionmodel.php, applications/vanilla/settings/structure.php, library/database/class.sqldriver.php
Regularly our monitoring tool is reporting about slow queries like:  
```
select d2.*
from `GDN_Discussion` `d`
join `GDN_Discussion` `d2` on d.DiscussionID = d2.DiscussionID
where `d`.`CategoryID` = ?
order by `d`.`DateLastComment` desc
limit 248350, 50`
```
This is the query generated by DiscussionModel. There is a code fragment that does strange `join`:
```
// Build up the base query. Self-join for optimization.
$sql->select('d2.*')
->from('Discussion d')
->join('Discussion d2', 'd.DiscussionID = d2.DiscussionID')
->limit($limit, $offset);
```
In the comment it is written that this self-join was done with **optimization** in mind. In reality it does nothing. But there is a very well known technique to optimize deeply paginated query issue.
The point of that technique is to reduce …
=> Optimize DiscussionModel query

applications/vanilla/models/class.discussionmodel.php
closes https://github.com/vanilla/support/issues/1459
When a post is marked as Spam and gets moved to the Spam queue, and an admin tries to delete that post, $data would be false https://github.com/vanilla/vanilla/blob/39d4c97c4a7806645c924373fb8bb5c0a4150f79/applications/vanilla/models/class.discussionmodel.php#L2980 discussion no longer exists in the discussion table.
- Move a post to the Spam queue (you can edit the spam reaction and increase the points to get it to move to Spam immedietly) 
- Delete the post.
=> Fix deleting posts from spam queue

conf/config-defaults.php, tests/APIv2/AddonsTest.php
Closes https://github.com/vanilla/support/issues/1438
Mobile theme default config was set to `mobile` instead of `keystone`.
=> Add Keystone as default mobile theme

applications/dashboard/src/scripts/forms/DashboardFormList.tsx, library/src/scripts/layout/frame/FrameBody.tsx, library/src/scripts/layout/frame/FrameHeader.tsx, library/src/scripts/layout/frame/frameBodyStyles.ts, library/src/scripts/layout/frame/frameHeaderStyles.ts, library/src/scripts/sectioning/TabStyles.ts
Working towards https://github.com/vanilla/knowledge/issues/1576
- Add blurred/disabled style for DashboardFormList
- Tabs are now sticky positioned and extend their width to account for their border (allowing them to be used in all modals, not just full screen ones)
- Tabs now flex grow to be of equal size rather than a fixed 25%.
- Frame header now was an option to omit it's top border.
- Add `<FrameBodyContainer />` to pad self-padded frames.
=> Add additional styling options for tabs and frames

.htaccess.dist
Fixes #10091 
`$_SERVER['HTTP_AUTHORIZATION']` is empty by default, even when `Authorization` it's present in apache request headers. This passes the `Authorization` header to it, so [access token checking](https://github.com/vanilla/vanilla/blob/Vanilla_3.3/applications/dashboard/settings/class.hooks.php#L753) will work.
Feel free to disregard if there's a better way to address #10091.
=> Fix API authentication by setting HTTP_AUTHORIZATION in .htaccess.dist

library/src/scripts/sectioning/TabStyles.ts
require : https://github.com/vanilla/internal/pull/2254
Fix: set height using calc() for tabs in theme editor page.
=> Fix - calculate height for nav in theme editor

applications/dashboard/src/scripts/compatibilityStyles/forumLayoutStyles.ts, library/src/scripts/layout/components/widgetContainerStyles.ts
Fixing bad CSS selector applying narrow width to .Content unconditionally. 
Closes: https://github.com/vanilla/vanilla/issues/10112
=> Fixing narrow width always being applied to .Content

library/core/functions.render.php, tests/Library/Core/SignInUrlTest.php
Closes vanilla/support#1450.
This fixes an issue where users who are signed out with autosignout sign back in, they are redirected to the the same "You have been signed out" page. This PR redirects users to the home page.
TO TEST
1. Enable the autosignout plugin and set the minutes to 1.
1. After you are signed out, sign back in.
1. Verify that you are redirected to the home page rather than the "You have been signed out" page.
=> Fix sign-in link generation sometimes redirecting back to entry pages

applications/dashboard/models/class.permissionmodel.php
Unset (reset) `$juncIDs` var inside the loop to avoid data pollution.
Relates to: https://github.com/vanilla/knowledge/issues/1583
=> Fix PermissionModel

library/core/class.format.php
Closes vanilla/support#1400
This fixes a problem when using wysiwyg with the advanced editor. If there were two spaces after an '@mention', '&nbsp;' would be appended to the name. This fix strips out the '&nbsp;'.
1. Make sure advanced editor is enabled and set to WYSIWYG.
1. Add a mention with two spaces after it.
1. Verify that '&nbsp;' is not appended to the name.
=> strip out &nbsp; from end of mentions

applications/vanilla/Events/UserEvent.php, applications/vanilla/controllers/class.moderationcontroller.php
closes https://github.com/vanilla/support/issues/1443
Moving a post out for reported posts is not currently allowed. In the drop-down menu, the only available option is 'Reported Posts' category. However, this is not the case when selecting the discussion with a checkbox. then moving it.
**Changes**
I've set the CategoryID and DiscussionType on the Data array similar to what we're doing when moving a discussion with the cog wheel.
- Move a discussion using the cog wheel, you should have Reported Posts as the only available option
- Move a discussion using the checkbox 
- Confirm that you have a similar behaviour.
=> Fix category dropdown options when moving a reported discussion using a checkbox

applications/vanilla/models/class.commentmodel.php, applications/vanilla/models/class.discussionmodel.php, bootstrap.php, library/Vanilla/Contracts/Formatting/FormatInterface.php, library/Vanilla/Formatting/BaseFormat.php, library/Vanilla/Formatting/FormatService.php, library/Vanilla/Formatting/Formats/NotFoundFormat.php, library/Vanilla/PlainTextLengthValidator.php, tests/Library/Vanilla/PlainTextLengthValidatorTest.php
Backport #10095 
Closed issues: vanilla/support#1439 and vanilla/support#1396
* Add a validation function that validates Rich Text on the length of visible text.
* Create validation methods for visible content lengths for different formats.
- Simplify the validateRawLength validation function.
- Create an interface for it in the FormatInterface.
- Create a call to the getVisibleTextLength() function in the Format Service.
- Create corresponding functions in HtmlFormat, RichFormat and TextFormat classes.
* Add getVisibleTextLength() to NotFoundFormat class.
* Output the correct format in NotFoundFormat.
* Fix type-hinting.
* Use `mb_strlen` to count string length. Fix validation function.
* Add test case.
* Starting creating tests.
* Create fixtures to test text counting.
* Add fixtures, …
=> Backport: Fix formatting always counting against post character limits (#10095)

library/src/scripts/headers/ActionBar.tsx, library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts, library/src/scripts/navigation/NavLinksPlaceholder.tsx, library/src/scripts/navigation/NavLinksWithHeadings.tsx, library/src/scripts/navigation/navLinksStyles.ts, library/src/scripts/navigation/navLinksWithHeadings.story.tsx
Working towards https://github.com/vanilla/knowledge/issues/1575
- Adds a placeholder for Nav Links.
- Adds a story for this placeholder.
- Fixes the width of the NavLinksWithHeading & associated home widget style to be the same width as the tiles grid.
=> Add navLinks placeholder

applications/vanilla/js/post.js
Closes vanilla/support#1289.
When starting a new discussion, the 'Save Draft' button was permanently disable after being clicked, meaning you could only save a draft one time. This fix re-enables the button so that users can save a draft as many times as they like.
Start a new discussion, type something in the body, and click the "Save Draft" button. Verify that it's re-enabled and can be clicked again.
=> Fix save draft button when starting a new discussion

library/src/scripts/features/tiles/Tiles.tsx, library/src/scripts/features/tiles/tiles.story.tsx, library/src/scripts/features/tiles/tilesStyles.ts, library/src/scripts/navigation/NavLinksWithHeadings.tsx, library/src/scripts/navigation/navLinksStyles.ts
Working towards https://github.com/vanilla/knowledge/issues/1575
- Update `Tiles` to display its existing title props (not sure why these weren't being used before.)
- I updated the story to use this title.
- Adjust spacing of separator and top title of the navLinks
=> Adjust headers separators for tiles and navLinks

library/src/scripts/sectioning/TabStyles.ts
The current tab was while on whilte in the theme editor. This fixes the colors.
=> Fixed colors for current tab

applications/dashboard/models/class.permissionmodel.php
We need to only join when `JunctionTable` filtered, if not we can attach wrong data and get wrong permissions.
Relates to: https://github.com/vanilla/knowledge/issues/1538
=> Fix permission query when join JunctionTable data

library/src/scripts/navigation/NavLinksWithHeadings.tsx
See with https://github.com/vanilla/knowledge/pull/1607
We needed more control over when the separator is displayed in the universal content widget, so I  moved the separator to the widget itself.
=> Remove unwanted separator from navlinks

applications/vanilla/models/class.discussionmodel.php, tests/Models/DiscussionModelTest.php
Closes vanilla/support#1481.
This PR fixes a bug where discussions created after a category has been marked read would display the number of unread comments, even though the user had never viewed the discussion. With this fix, the 'new' tag displays without a number, as it should.
1. As user A, mark a category as read.
1. As user B, create a new discussion in that category and add a comment to that discussion.
1. As user A, refresh the page and ensure that discussion's tag is 'new' and not '1 new'
=> Fix "new" tags on discussions created after category has been marked read

addons/themes/keystone/views/default.master.tpl
Closes https://github.com/vanilla/support/issues/1221
**Steps to test:**
- Enable Keystone
- Enable Integrate Banner Image
- Change layout to "Mixed"
- Look at the categories page
=> Add HeroBanner to mixed layout

library/SmartyPlugins/function.logo.php, library/SmartyPlugins/function.mobile_logo.php, library/core/class.theme.php, library/src/scripts/headers/TitleBar.tsx, library/src/scripts/headers/titleBarStyles.ts
Working on the Success community, I wanted to set a default logo so it was more portable with the theme. I created a new prop for the smarty helpers "logo" and "mobile_logo" to accept a "fallbackLogo" param. This will only apply if no logo was found in the config. Makes logos more portable/version controlled, but still editable by client.
Example usage:
`{logo fallbackLogo={"/themes/success/design/images/logo.png"|asset_url:true:true} }`
May be of interest for @irina-vanillaforums @alexbrohman @hhovhannes
=> Added optional fallbackLogo option to set on smarty function.

library/Vanilla/Exception/PermissionException.php, library/Vanilla/Permissions.php, library/src/scripts/errorPages/CoreErrorMessages.tsx, tests/Library/Vanilla/PermissionsTest.php
Working towards https://github.com/vanilla/knowledge/issues/1642 and https://github.com/vanilla/knowledge/issues/1619
- Add some permission checking utilities to the core permission model. There are 3 modes.
- **Check Resource Only** (was possible by passing a resource id before, but not explicit).
- **Check Global only** (was not possible to check before).
- **Check global or any resource** (previous default).
- These 3 modes are not an optional third param to the various `has*` methods.
- Add couple test assertions to existing permission object tests.
- Update the `PermissionException` class.
- Now has a short title.
- Description is the exception message.
- Translates it's title and message.
- This means incorrect permission errors in the dashboard now look like this.
=> Add some addition permission utilities

library/src/scripts/content/userContentStyles.ts
Closes https://github.com/vanilla/support/issues/1516
Relevant info: https://github.com/vanilla/support/issues/1516#issuecomment-595966306
- Enable guildwars theme
- Checkout to release/2020.004 and run the build
- Visit a discussion page and notice the font-size
- Checkout this branch
- Run the build again and notice the font-size (should be bigger)
**Notes:**
- This branch is in sync with `master` on the other repos (knowledge, multisite, internal...) you might have to sync the branches in all the repos for the build to run smoothly.
=> Remove UserContent inline styles

applications/vanilla/controllers/class.categoriescontroller.php, applications/vanilla/views/categories/discussions.php
Closes https://github.com/vanilla/support/issues/1248
Relevant info: https://github.com/vanilla/support/issues/1248#issuecomment-595801464
**Steps to test:**
- Test it in chrome.
- Test it in a local with a bunch of data (categories and discussions). Enable the mixed layout and set the categories page as the homepage.
- Checkout `master` and measure the "DOMContentLoaded" on the dev tools, Network tab.
- Checkout this branch, refresh the page and match the difference.
(Although I know local testing doesn't mean much in this case, I monitored mine and it decreased from 1.6min to 8.17s).
=> Optimize Categories Mixed Layout loading discussions

library/core/class.theme.php
[Google has deprecated Data-Vocabulary.org support in favor of Schema.org.](https://webmasters.googleblog.com/2020/01/data-vocabulary.html) There are only two references of this in core Vanilla. They're both related to breadcrumbs. This update makes the swap. For better or worse, there should be no other appreciable changes (except removing a duplicate "CrumbLabel" class on the home crumb).
There's an example of this switch-a-roo in Google's deprecation announcement (https://webmasters.googleblog.com/2020/01/data-vocabulary.html).
Closes #9962
=> Replace Data-Vocabulary.org references with Schema.org

applications/dashboard/src/scripts/compatibilityStyles/inputStyles.ts, library/src/scripts/banner/Banner.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/features/search/IndependentSearch.tsx, library/src/scripts/features/search/SearchBar.tsx, library/src/scripts/features/search/searchBarStyles.ts, library/src/scripts/forms/inputStyles.ts, library/src/scripts/forms/themeEditor/colorPickerStyles.ts, library/src/scripts/forms/themeEditor/inputNumberStyles.ts, library/src/scripts/headers/titleBarNavStyles.ts, library/src/scripts/styles/styleHelpersTypography.ts
Fixes height, alignment issues (placeholder mostly) and font sizes inconsistencies with independent search. 
FYI, if you see the placeholder misaligned again, it's missing a "box-sizing: 'content-box'" style.
Companion PR: https://github.com/vanilla/knowledge/pull/1647
=> Fixed independent search style inconsistencies

applications/dashboard/controllers/api/RolesApiController.php, applications/dashboard/controllers/api/UsersApiController.php, library/Vanilla/Models/PermissionFragmentSchema.php, library/Vanilla/Permissions.php, library/Vanilla/PermissionsTranslationTrait.php, library/Vanilla/Web/UserSmartIDResolver.php, library/src/scripts/__tests__/TestReduxProvider.tsx, library/src/scripts/features/users/Permission.test.tsx, library/src/scripts/features/users/Permission.tsx, library/src/scripts/features/users/UserActions.ts, library/src/scripts/features/users/userModel.ts, tests/APIv2/UsersTest.php, tests/Library/Vanilla/Web/SmartIDMiddlewareTest.php
Working towards https://github.com/vanilla/knowledge/issues/1619
**Create a user endpoint to return all permissions for a particular user**
- Extract a PermissionFragmentSchema from the roles controller.
- Permission fragments for global and each resource are returned.
- Method added to `Permission` object to generate permission fragments.
- This can be used for the current user with the `$me` smartID.
**Update frontend**
The frontend has been updated to use the data from this endpoint now instead of the `/users/me` endpoint.
- Add reducer & action for new endpoint.
- Update `<Permission />` component to use this new data.
- Uddate `<Permission />` to be able to check per-resource, global, or combinations of them for permissions.
=> Pass resource specific permissions to the frontend

applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts, plugins/rich-editor/src/scripts/quill/components/blotStyles.ts
Fixes https://github.com/vanilla/support/issues/1547
These styles were only supposed to be applied in foundation, but they manage to sneak into the normal styles
=> Move content heading styles to compat styles

applications/vanilla/models/class.discussionmodel.php
A change was made in https://github.com/vanilla/vanilla/pull/10094 to optimize the getWhere function of the discussion model.
A custom plugin created a little while ago was hooking into the `beforeGet` event fired in this same function to add a "select" to the SQL object. This new change is now breaking the query into two parts and the select is now being added to the wrong query. The query then fails when the plugin is turned on.
https://github.com/vanillaforums/mse/issues/166
Instead of firing an additional event, a new argument is passed to it allowing plugins to specify columns to add to the query.
=> Allow plugins to add selects in getWhere function of the DiscussionModel.

applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts, plugins/rich-editor/src/scripts/quill/components/blotStyles.ts
Backporting #10192 
Closes vanilla/support#1547.
These styles were only supposed to be applied in foundation, but they manage to sneak into the normal styles
=> [Backport 2020.004] Move content heading styles to compat styles

library/core/functions.render.php
Closes vanilla/support#1523.
This fixes a problem where users who have the `Garden.Profiles.View` permission cannot view their own profiles. This PR removes some additional permission checks in the `hasViewProfile()` function that aren't necessary. (It appears they were copied over from the `hasEditProfile()` function). 
1. Make sure that neither `Garden.Profile.Titles` nor `Garden.Profile.Locations` are enabled AND that `Garden.Registration.Method` is not set to `'Connect'`.
1. Sign in as a member-level user and verify that you the "View Profile" option is absent from the MeBox dropdown menu.
1. Checkout this branch and verify that the "View Profile" option is there.
=> Fix view profile restrictions

applications/vanilla/models/class.discussionmodel.php
Backport: https://github.com/vanilla/vanilla/pull/10187
A change was made in https://github.com/vanilla/vanilla/pull/10094 to optimize the getWhere function of the discussion model.
A custom plugin created a little while ago was hooking into the `beforeGet` event fired in this same function to add a "select" to the SQL object. This new change is now breaking the query into two parts and the select is now being added to the wrong query. The query then fails when the plugin is turned on.
https://github.com/vanillaforums/mse/issues/166
Instead of firing an additional event, a new argument is passed to it allowing plugins to specify columns to add to the query.
=> Backport: Allow plugins to add selects in getWhere function of the DiscussionModel.

library/Garden/SphinxTrait.php
In order to address fatal errors when using the bundled PHP API class bundled with Sphinx v3.2.1, changes need to be made to `SphinxTrait`. The changes are backwards-compatible with v2, so either should be functional.
1. `setMatchMode` has been removed from the Sphinx API as of v3.1.1. It was already deprecated in newer versions of v2, so seeing it go here should be no surprise. Its presence is used to determine which version of the API we'll be working with. The default search behavior in v3  matches the "extended" behavior, so there's not much to do here aside from removing it.
1. `SPH_SORT_TIME_SEGMENTS` is not a valid sort mode in Sphinx v3.2.1. It's documented as a valid sort mode, but attempting to use it throws a fatal unknown/unsupported error from the search service. Its usage is …
=> Fix SphinxTrait compatibility with Sphinx v3 API

library/src/scripts/embeddedContent/embedStyles.ts
This PR will close vanilla/support#1321
Recent changes to our EmbedStyles added a white background colour explicitly but did not specify the font colour. This meant, in certain themes it was rendered white on white. This PR will add the the foreground colour to the font.
- Find a theme which has white text as default (or set it in custom CSS).
- Do `yarn build` in the root of vanilla.
- Warn a user's post.
- Go to the user's profile page.
- See that the body text is invisible.
- Pull this branch.
- Repeat the above steps. 
- See that the body text is visible.
=> Fix quoted text showing white on white.

bootstrap.php, cache/.htaccess, library/Vanilla/Contracts/Formatting/FormatInterface.php, library/Vanilla/Formatting/BaseFormat.php, library/Vanilla/Formatting/ExtendedContentFormatService.php, library/Vanilla/Formatting/Formats/HtmlFormat.php, library/Vanilla/Formatting/Formats/NotFoundFormat.php, library/Vanilla/Formatting/Html/HtmlSanitizer.php, library/core/class.vanillahtmlformatter.php
The ExtendedFormatService allows for formats the ability to exclude certain elements from being stripped out by the vanilla formatter.
required for https://github.com/vanilla/knowledge/issues/1664
accompanying PR https://github.com/vanilla/knowledge/pull/1667
=> Create ExtendedFormatService to allow extended content to be rendered.

library/Vanilla/Models/UserFragmentSchema.php
This PR will close vanilla/support#1198
The original issue arose at the release of release/2019.018 when an event that one of your customers was hooking into to alter the UserFragmentSchema stopped working.
This PR returns that functionality by instantiating the SchemaFactory.
To test you will need to 
1. Create profile extender fields.
2. Populate those fields for a user.
3. Turn on an addon that adds user meta values to the UserFragment.
4. Make this API call: https://dev.vanilla.localhost/api/v2/users/{userID}?expand=true;
5. Checkout this branch and repeat. 
6. Compare.
=> Allow plugins to hook into the UserFragmentSchema.

applications/vanilla/models/class.discussionmodel.php
This change has been made following the PRs below.
https://github.com/vanilla/vanilla/pull/10187
https://github.com/vanillaforums/mse/pull/167
This change will allow plugins to hook into the `beforeGetID` event fired in the DiscussionModel and add fields to the query that are expected in the result. The "Selects" array is now passed as event argument, in which additional columns can be added to.
Before this change, it was only possible to add fields by grabbing the SQL object from the plugin and call the select method on it, which is not a good practice in general.
This same logic was added to the `getWhere` function of the discussion model a few days ago. (can be found in the first linked PR above)
=> Add the "Selects" argument to the BeforeGetID event fired in the discussion model.

library/Vanilla/Web/Asset/WebpackAssetProvider.php
This fixes the bug that came up in the demo where the theme color picker was not appearing in production builds.
=> Fix shared and vendor CSS loading in production builds

applications/dashboard/controllers/api/UsersApiController.php, applications/dashboard/models/class.usermodel.php
This PR will close vanilla/support#1582
Moving the user Schema from the API controller to the usermodel caused a problem when updating the User table when the Password field is empty. This PR will fix that by adding a subset of the full schema to the UserModel.
=> Fix firing PSR-14 user events for users with empty password fields

applications/dashboard/controllers/api/UsersApiController.php, applications/dashboard/models/class.usermodel.php
Backport: vanilla#10244
This PR will close vanilla/support#1582
Moving the user Schema from the API controller to the usermodel caused a problem when updating the User table when the Password field is empty. This PR will fix that by adding a subset of the full schema to the UserModel.
=> Backport: Fix firing PSR-14 user events for users with empty password fields

applications/dashboard/controllers/class.settingscontroller.php, applications/dashboard/locale/en.php, applications/dashboard/models/class.invitationmodel.php, applications/dashboard/views/embed/forum.php, applications/dashboard/views/settings/security.php, applications/vanilla/locale/en.php, applications/vanilla/views/vanillasettings/posting.php
Some translation string codes are shortened by vanilla/locales#266. This PR changes the args of the relevant t() function calls to match the shortened codes.
Addresses vanilla/locales#264
=> Edit translation string t() args with shorter codes

applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx, library/src/scripts/forms/themeEditor/ThemeBuilderUpload.tsx, plugins/rich-editor/src/scripts/editor/pieces/EditorUploadButton.tsx
Closes part of https://github.com/vanilla/internal/issues/2299
Older issue of the same thing (that was never resolved but closed anyways) https://github.com/vanilla/vanilla/issues/7864
- HTML input elements with a file type don't fire a change event when if you try to give the same file they already have.
- The only way to clear the existing file is to re-create the input from scratch.
- I've done this just be added a key prop that changes on upload to our 3 image upload components.
=> Fix file upload inputs not being cleared after upload

library/src/scripts/features/search/SearchOption.tsx, library/src/scripts/features/search/searchBarStyles.ts, library/src/scripts/forms/select/SelectOne.tsx, library/src/scripts/forms/select/overwrites.tsx, library/src/scripts/forms/select/selectOneStyles.tsx, library/src/scripts/forms/themeEditor/ThemeDropDown.tsx
Closes part of https://github.com/vanilla/internal/issues/2299
> There seems to have been a glitch when you selected different values for the banner alignment that seemed like a bug. You had to select the same item again to get it to take effect.
The issue was that we had no good indicator on which is item is currently selected from the dropdown. This could be confusing, so I've added our compact check as the current indicator of the selected value.
This is consistent with some of the newer mockups we've had recently anyways.
=> Add check indicator to active item in `SelectOne` dropdown

library/src/scripts/features/swagger/swaggerStyles.scss
They were being hidden after the recent updates.
=> Fix try it openapi embed inputs

applications/dashboard/models/class.activitymodel.php
closes https://github.com/vanilla/support/issues/921
- Enable conversations with subject $Configuration['Conversations']['Subjects']['Visible'] = true;
- Send a message to a user with a subject
- email received should have the sender's name added to the subject
- test again with $Configuration['Conversations']['Subjects']['Visible'] = false, you should still see the username.
=> Fix username not visible in conversation email when using a subject

library/Vanilla/Addon.php, library/Vanilla/Contracts/AddonInterface.php, library/Vanilla/Models/FsThemeProvider.php, library/Vanilla/Models/ThemeModelHelper.php, library/src/scripts/theming/addThemeStyles.ts, tests/APIv2/ThemesTest.php, tests/MinimalContainerTestCase.php, tests/Models/ThemeModelHelperTest.php, tests/fixtures/src/MockAddon.php
Relating to https://github.com/vanilla/knowledge/issues/1681
We had some issues with hidden themes appearing in results, so I've done some refactoring to the method and added some tests for it.
- Update AddonInterface and MockAddon with additional info methods.
- Move `FsThemeProvider::filterTheme` to `ThemeHelperModel::isThemeVisible`.
- The method now takes an addon instead of an array.
- Add unit tests for this method.
- Update `MinimalContainerTestCase` to allow setting session information.
- Fix the minHeight on the add theme item (visible when it is by itself).
- SysAdmin users can see all themes now, similar to our behaviour on the addons page. **_Because of this I had to set the user to a guest for the theme index test_**
_Note:_ I moved a "public" method on the `FsThemeProvider` …
=> Fix theme API filtering

applications/dashboard/settings/structure.php, library/Vanilla/Contracts/ConfigurationInterface.php, library/Vanilla/Models/ThemeModelHelper.php, library/core/class.configuration.php, tests/MinimalContainerTestCase.php, tests/Models/ThemeModelHelperTest.php, tests/fixtures/src/MockConfig.php
Address part of https://github.com/vanilla/knowledge/issues/1681
Targeting https://github.com/vanilla/vanilla/pull/10275 until that is merged.
> If someone has a hidden theme enabled and then disables it it should still be allowed to show. Maybe add a config key for visible themes that will always display.
It turns out we already have that config!
- Save current themes into forced visible themes config on structure.
- Add some tests.
- Expand config interface to allow saving.
- Use some constants for config values in the `ThemeHelper`.
=> Save current theme into the allowed theme keys on structure

applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/fontStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/forumMetaStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/forumTagStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/index.ts, applications/dashboard/src/scripts/compatibilityStyles/tableStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/textLinkStyles.ts, applications/vanilla/modules/class.tagmodule.php, library/src/scripts/styles/globalStyleVars.ts, library/src/scripts/styles/styleHelpersLinks.ts, library/src/scripts/styles/tagStyles.ts, packages/vanilla-theme-core/scss/components/_lists.scss
Fixed styles for tags to match mockups: https://app.zeplin.io/project/5e271637b9bef8985fd77a08/screen/5e73dd7eb601dab3510c6736
Note that the color and border are a tad different from the mockups, because I used the same ones we have as defaults instead of making new colors.
Closes: https://github.com/vanilla/vanilla/issues/10220
=> Foundation - Tag styles

addons/themes/theme-foundation/addon.json, library/Vanilla/Models/AddonModel.php
The check introduced here looks to see if themes are visible or not. https://github.com/vanilla/vanilla/commit/538011cd388f3c3eec6cb1f8e3d2926f1d4062a8
However, this config can also be a CSV, with 'all' as the value that shows everything.
The line here was recently introduced and is both combined broke our tests on circleCI.
https://github.com/vanilla/vanilla/blob/d618eef0945177ed2e3ae7df8d6f593fca37dd85/applications/dashboard/settings/structure.php#L1037
https://app.circleci.com/pipelines/github/vanilla/vanilla/5817/workflows/7e5b37a8-d097-49e6-b7bb-ae69247148c9/jobs/47311
- Fix that check to look for 'all'.
- Mark foundation as visible.
=> Fix addon model check to force as visible

library/Vanilla/AliasProviderTrait.php
My IDE was reporting issues with the `AliasProviderTrait`, specifically the use of `self` on an abstract method. While I don’t think this is a bug for a trait per se, it is a best practice to call methods with `static::` instead of `self::`.
=> Fix static calls and lint on the AliasProviderTrait

applications/dashboard/controllers/class.routescontroller.php
Similar to #7728
After deleting a route, the page did not refresh, which could confuse users.
=> Refresh page after deleting route

library/setup/ComposerHelper.php
`getenv()` returns a string. 
Setting `VANILLA_BUILD_DISABLE_AUTO_BUILD` to `false` (or anything) returned true.
This PR fixes that by ensuring that the value must be equals to `"true"`
=> Fix  VANILLA_BUILD_DISABLE_AUTO_BUILD check

applications/vanilla/library/class.categorycollection.php
Any time a category collection is created, it will save its calculated entries to the site cache. If a category collection is created by an addon and configured with custom calculation routines, it can cause bad data to be cached for all other category collections.
This update allows creating a category collection that will only read from the cache, not write to it. Custom category calculations are still allowed without polluting the site's cache.
=> Add read-only cache mode to CategoryCollection

applications/dashboard/controllers/class.settingscontroller.php, library/core/class.uploadimage.php
Closes https://github.com/vanilla/support/issues/1626
Unfortunately ICO sizes are hardcoded and don't respect configs, so I bumped that up too.
=> Increase favicon size

applications/dashboard/src/scripts/compatibilityStyles/forumMetaStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/index.ts, applications/dashboard/src/scripts/compatibilityStyles/searchPageStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/textLinkStyles.ts, library/src/scripts/content/userContentStyles.ts, library/src/scripts/flyouts/dropDownStyles.ts, library/src/scripts/forms/buttonStyles.ts, library/src/scripts/headers/titleBarStyles.ts, library/src/scripts/headers/vanillaHeaderStyles.ts, library/src/scripts/homeWidget/HomeWidgetItem.styles.ts, library/src/scripts/messages/messageStyles.ts, library/src/scripts/navigation/breadcrumbsStyles.ts, library/src/scripts/navigation/navLinksStyles.ts, library/src/scripts/navigation/siteNavStyles.ts, library/src/scripts/styles/globalStyleVars.ts, library/src/scripts/styles/styleHelpersButtons.ts, library/src/scripts/styles/styleHelpersLinks.ts, library/src/scripts/styles/tagStyles.ts, plugins/rich-editor/src/scripts/flyouts/pieces/insertEmojiClasses.ts
Refactored some unclear (or just plain bad) names to clarify the focus styles.
Extra checks to make sure we don't pass empty or undefined styles to CSS.
Companion PR: https://github.com/vanilla/knowledge/pull/1698
Working towards: https://github.com/vanilla/vanilla/issues/10218
=> Refactor State Names

applications/dashboard/views/robots/index.twig
The rules in robots.txt are being encoded as if they're HTML. They should be treated as plain text. This update removes the automatic HTML encoding applied to them via the Twig template.
1. Add some robots rules to Vanilla's `Robots.Rules` config that include some HTML special characters (e.g. &).
1. Open /robots.txt on the site.
1. Observe the special characters are not encoded (e.g. & is not &amp;amp;).
Closes vanilla/support#1627
=> Fix HTML encoding in robots.txt

js/global.js
Vanilla may specify a path for its cookies. If specified, those cookies will only be sent on requests within that path. Some path-altering behavior was introduced in vanilla/vanilla#9809 that allowed the path to Vanilla's analytics endpoint to be overridden. If its path was not the same as Vanilla's cookie path (and it very likely would not be), vital cookies would not be sent to the analytics endpoint.
The path changes for the analytics endpoint path are reverted here to reflect their state [prior to December 2019](https://github.com/vanilla/vanilla/commit/2c506946424fbc35d7ac23a4954f90b464b97238).
Closes vanilla/support#1497
=> Fix analytics tick endpoint path reference

js/global.js
Backporting #10300 to `release/2020.006`.
> Vanilla may specify a path for its cookies. If specified, those cookies will only be sent on requests within that path. Some path-altering behavior was introduced in vanilla/vanilla#9809 that allowed the path to Vanilla's analytics endpoint to be overridden. If its path was not the same as Vanilla's cookie path (and it very likely would not be), vital cookies would not be sent to the analytics endpoint.
>
> The path changes for the analytics endpoint path are reverted here to reflect their state [prior to December 2019](https://github.com/vanilla/vanilla/commit/2c506946424fbc35d7ac23a4954f90b464b97238).
=> Backport: Fix analytics tick endpoint path reference

applications/dashboard/src/scripts/compatibilityStyles/forumLayoutStyles.ts, applications/dashboard/src/scripts/compatibilityStyles/index.ts
Removed padding from user photo, it was getting cut off by its parent container.
Closes :https://github.com/vanilla/vanilla/issues/10250
=> Foundation - Removed padding from user photo

library/Vanilla/Contracts/Search/SearchRecordTypeInterface.php, library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php
Default index weight in SearchRecordTypeTrait to 1.
Relates to: https://github.com/vanilla/knowledge/issues/1658
=> Extend SearchRecordTypeInterface with getIndexWeight() method.

library/src/scripts/headers/mebox/pieces/MessagesContents.tsx
Seems like we've had 2 links to the messages inbox instead of 1 to new message and 1 to inbox in the mebox messages menu.
@hhovhannes
=> Fix path of new message button to be new message and not inbox

plugins/SplitMerge/locale/en.php, plugins/SplitMerge/views/mergediscussions.php
Closes vanilla/support#1630
This PR adds a locale directory and en.php file to the splitmerge plugin. It also fixes a typo in the `mergediscussions` view.
=> Add SplitMerge translation strings to locale

applications/dashboard/modules/class.messagemodule.php
Site messages are managed by site administrators and community managers. In their current form, they allow direct HTML entry. This lack of filtering/processing can cause undesired effects, including broken markup in the page.
This update adds some standard HTML processing to the message prior to rendering using `HtmLawed` via Vanilla's `HtmlSanitizer`.
Closes #10296
=> Fix filtering on site messages

applications/dashboard/models/BannerImageModel.php, applications/dashboard/src/scripts/entries/forum.tsx, library/Vanilla/Models/CurrentUserPreloadProvider.php, library/Vanilla/Models/FsThemeProvider.php, library/Vanilla/Models/SiteMeta.php, library/Vanilla/Theme/ThemeFeatures.php, library/Vanilla/Web/TwigEnhancer.php, library/Vanilla/Web/TwigRenderTrait.php, library/src/scripts/banner/CommunityBanner.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/banner/contentBannerStyles.tsx, library/src/scripts/forms/buttonStyles.ts, library/src/scripts/forms/styleHelperButtonGenerator.ts, library/src/scripts/headers/TitleBar.tsx, library/src/scripts/headers/titleBarNavStyles.ts, library/src/scripts/headers/titleBarStyles.ts, library/src/scripts/layout/PanelLayout.tsx, library/src/scripts/navigation/breadcrumbsStyles.ts, library/src/scripts/styles/globalStyleVars.ts, library/src/scripts/theming/ThemeActions.ts, library/src/scripts/theming/ThemePreviewTitle.tsx, library/src/scripts/theming/loadThemeFonts.ts, tests/Library/Vanilla/Theme/ThemeFeaturesTest.php, tests/Library/Vanilla/Theme/TwigAssetTest.php
Closes https://github.com/vanilla/vanilla/issues/10286
Closes https://github.com/vanilla/internal/issues/2333
Working towards https://github.com/vanilla/knowledge/issues/1682
Theme to test with https://github.com/vanillaforums/king/pull/230
Numerous features and fixes were implemented to service this issue.
- Fix centered logo not hiding on search open
- Adjust titlebar nav to use transparent overlays 
- Add an offset for the item immediately following a "swooped" titlebar.
- Fix flickering of titlebar nav items with permissions (Items would "pop in" as permissions loaded). The fix was to preload the permissions the same way we preload the user info. 
- Add additional breadcrumb variables 
- Add simpler custom font loading (Just set `global.font.customFontUrl`)
- Add additional content …
=> Add various theme fixes

applications/dashboard/controllers/class.entrycontroller.php
Along with vanilla/internal#2331, this closes vanilla/support#1606
This PR, in conjunction with vanilla/internal#2331, fixes a problem where temporary bans triggered by amassing more than 5 active warning points would never expire because the session would end before there was a check for expired warnings. This fixes that by adding a beforeSignIn event to complement the afterSignIn event calls in the entry controller.
1. Give a user 5 or more active warning points and verify that the user is banned.
1. Alter the times in the GDN_UserAlert table to make the ban expire.
1. Try to sign in as the banned user and verify that the ban has been lifted
=> Add support for addons hooking in before user signin

applications/dashboard/src/scripts/compatibilityStyles/searchPageStyles.ts, library/src/scripts/features/search/searchBarStyles.ts, library/src/scripts/features/search/searchResultsStyles.ts
Fixed margin for search result excerpts to match mockups.
Closes: https://github.com/vanilla/knowledge/issues/1703
=> Fixed margin for search result excerpts

library/core/class.vanillahtmlformatter.php, library/src/scripts/utility/appUtils.tsx
- Fix URLs in the frontend ocasionally getting the base path added twice. (this could occur easily if you used `assetUrl` or `themeUrl` on something, then used `siteUrl()` to get a fully qualified URL).
- Fix embeds getting un-embedded in the trusted content formatter. Youtube embeds were the one I noticed, but iframe embeds would get transformed into our ugly old embeds instead of staying as iframes.
=> Fix some URL formatting issues

library/src/scripts/theming/ThemeProvider.tsx
The new compatibility styles are only supposed to apply to Foundation based themes and it was always applied.
Closes: https://github.com/vanilla/vanilla/issues/10328
=> Fix compatibility styles applying to Keystone based themes

library/Vanilla/Models/ThemeModel.php, library/Vanilla/Theme/KludgedVariablesProviderInterface.php, library/Vanilla/Theme/VariablesProviderInterface.php, library/src/scripts/headers/TitleBar.tsx, library/src/scripts/headers/mebox/pieces/HeaderLogo.tsx, library/src/scripts/headers/mebox/pieces/TitleBarNav.tsx, library/src/scripts/headers/navigationVariables.ts, library/src/scripts/headers/titleBarNavStyles.ts, library/src/scripts/headers/titleBarStyles.ts, library/src/scripts/styles/styleHelpers.ts, library/src/scripts/styles/styleHelpersBorders.test.ts, packages/vanilla-react-utils/src/useCollisionDetector.tsx
The swoop style header was creating some body overlay after recent changes. Since we can't put `overflow: hidden` back on the body (it was removed to fix this https://github.com/vanilla/vanilla/pull/10312), I've opted for an extra overflow container around the swooped backgrounds.
I also had to adjust the height here to compensate for the swoop.
Added a custom logo URL.
Closes https://github.com/vanilla/vanilla/issues/10107
Our desktop centered logo did not have collision detection with the nav. As a result you could have them overlaying each other at different breakpoints.
I've fixed it.
Previously all variable providers were considered kludged and could be excluded by a theme feature.
Some themes may need a custom variable provider though, so I've added a different interface to …
=> Theme TitleBar improvements

applications/dashboard/src/scripts/forms/dashboardStyles.ts, applications/dashboard/src/scripts/tables/DashboardTable.tsx, applications/vanilla/src/scripts/entries/admin.ts, library/src/scripts/forms/select/selectOneStyles.tsx, library/src/scripts/forms/themeEditor/ThemeBuilder.styles.ts
I've made a more generic fix for the dropdown styles, so this should fix both the styles in the dashboard and in the theme editor pages.
@charrondev I don't see any font size consistencies in the dashboard anymore, do you have an example?
=> Fixes dashboard issues with Dropdown Styles 

applications/dashboard/controllers/api/UsersApiController.php, applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/models/class.usermodel.php, library/Vanilla/Permissions.php, library/core/class.session.php, tests/APIv2/AbstractResourceTest.php, tests/APIv2/UsersTest.php, tests/Library/Vanilla/PermissionsTest.php, tests/SiteTestTrait.php
Partially addresses vanilla/support#1571
This PR adds functions that allow comparison between the current user's permissions and the permissions of a user the current user wants to perform some kind of administrative action on (ban, mark as a troll, etc.). These functions can be called by other classes to make sure a user isn't able to take an action against another user with the same or higher permissions.
The PR also implements this check in the ban method of the `usercontroller.php`
1. Make sure the moderator role can warn users (enable `Garden.Moderation.Manage` for that role).
1. Make sure you have at least to moderator users.
1. As one moderator, try to ban the other. Verify that it works.
1. Check out this branch and repeat step 4, but verify that it doesn't work.
=> Add functions for comparing ranked permissions

library/Vanilla/Database/Operation.php, library/Vanilla/Database/Operation/CurrentDateFieldProcessor.php, library/Vanilla/Models/PipelineModel.php, tests/Library/Vanilla/Database/CurrentDateFieldProcessorTest.php
Adjust CurrentDateFieldProcessor to reflect operation mode accordingly.
Relates to: https://github.com/vanilla/knowledge/issues/1671
=> Extend database Operation with mode: force, default.

tests/SiteTestTrait.php
Fixes a problem caused by #10284 where a method name was inadvertently reused, which caused some conflicts. This PR renames the method.
=> Change duplicated method name

library/core/class.oauth2.php
The OAuth2 SSO method allows for admins to translate the keys of the profile response for authenticating a user so that it matches what our script expects. More and more organizations pass Roles over SSO. This PR will add Roles to the translation array and gives an interface for the admins to modify the name of the key.
(Backwards compatibility)
- With an existing OAuth2 configuration:
- Checkout this branch.
- Connect over SSO.
- With an existing OAuth2 configuration:
- Check out this branch.
- Modify the Roles field in the Dashboard Settings.
- Connect over SSO
- With an existing OAuth2 configuration:
- Check out this branch.
- Modify the Roles field in the Dashboard Settings to match roles being passed. e.g. put 'position' in the Roles field. (if you are unable to pass roles over SSO …
=> Add a Roles as translatable field to OAuth2 feature.

applications/dashboard/src/scripts/compatibilityStyles/clickableItemHelpers.ts, library/Vanilla/Web/Asset/InlinePolyfillContent.js.twig, library/Vanilla/Web/ContentSecurityPolicy/ContentSecurityPolicyModel.php, library/src/scripts/styles/styleHelpersSpacing.ts
Closes https://github.com/vanilla/knowledge/issues/1600
Closes https://github.com/vanilla/vanilla/issues/9988
Comments inline should be clear enough I think.
I've tested in browserstack with safari 9 and edge 17/18. IE was already working beforehand.
=> Fix backwards compatibility with old browsers

library/src/scripts/content/DateTime.tsx
Fixes https://github.com/vanilla/internal/issues/2326
Our DateTime component was using the browsers default locale instead of the subcommunity one when formatting dates.
I've updated the component to request date formatting in the current site sections current locale.
In the end no work with moment or webpack loading was required because we use the built in browser Date object to format dates.
=> Update datetime to use current locale

composer.json, library/Vanilla/Formatting/Formats/HtmlFormat.php, library/Vanilla/Formatting/Html/HtmlDocument.php, library/Vanilla/Formatting/Html/Processor/HeadingHtmlProcessor.php, library/Vanilla/Formatting/Html/Processor/HtmlProcessor.php, library/Vanilla/Formatting/Html/Processor/ImageHtmlProcessor.php, library/Vanilla/Formatting/Html/Processor/UserContentCssProcessor.php, tests/fixtures/formats/html/paragraph-formats/input.html, tests/fixtures/formats/html/paragraph-formats/output.html, tests/fixtures/formats/html/paragraph-formats/output.txt, tests/fixtures/formats/html/xss/output.html, tests/fixtures/formats/markdown/paragraph-formatting/output.html, tests/fixtures/formats/wysiwyg/paragraph-formats/output.html
Working towards https://github.com/vanilla/knowledge/issues/1723 and https://github.com/vanilla/support/issues/1510
I'm moved out HTML processing out of `HtmlFormat` and into a few new classes.
- `HtmlDocument`
- `HtmlProcessor` -> `HeadingHtmlProcess`, `ImageHtmlProcessor`, `UserContentCssProcessor`
Previously our heading processing only extracted IDs from HTML. Now it applies them to the HTML as well.
- I've also updated the heading extraction to stop generating IDs for empty headings.
=> Apply HTML outline IDs into headings

library/src/scripts/banner/BannerContext.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/result/ResultList.tsx
Working towards https://github.com/vanilla/knowledge/issues/1700
- Fix border radius of search not applying correctly on mobile. This was to do numerical radii not getting a unit attached. Eg. `border-top-right-radius: 40 !important`
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/78382821-6d2de780-75a5-11ea-92f2-ea9b03d9b3b9.png)|![image](https://user-images.githubusercontent.com/1770056/78382845-75862280-75a5-11ea-948b-27df5a6ad28f.png)|
Our result list component actually has no coupling to the search bar. Some search bar styles were applying though and causing unwanted BG colors to apply. See the category issue in https://github.com/vanilla/knowledge/issues/1700
Our banner context provider was resetting on _any_ location change (including hash …
=> Fix various theme issues

applications/dashboard/controllers/api/LocalesApiController.php
Fixes regional locale variants being displayed as `unknown`.  We were originally not trimming to the locale key to the first 2 characters which exclude the variant (ie. pt_BR would be just pt).  This has been changed and the region has been appended to display name if there is one.
closes https://github.com/vanilla/multisite/issues/354
=> Fix regional locale variants displaying incorrectly

library/src/scripts/styles/globalStyleVars.ts
As noted in the demo the offset here, stacked on top of the offset we already had for the secondary could result in some colors that were way to dark for a hover variation.
I've toned it down for a much lighter touch.
=> Tweak link color state generation

library/core/class.dispatcher.php
Endpoints added by event handlers get passed an `args` that is an array of remaining path variables. This wasn’t being added properly to calculated canonical URLs and was causing a notice.
I'm also removing the canonical URL comparison since it isn't really used anymore.
=> Fix canonical URL generation

library/core/class.request.php, library/core/functions.framework.php, library/core/functions.render.php
- When calling functions my IDE gives warnings that sometimes come from wrong types in docblocks.
- The `t()` function really shouldn’t be deprecated as there isn’t a good alternative right now.
=> Fix some docblocks

library/src/scripts/banner/bannerStyles.ts, library/src/scripts/headers/TitleBar.tsx, library/src/scripts/headers/mebox/pieces/CompactMeBox.tsx, library/src/scripts/headers/mebox/pieces/CompactSearch.tsx, library/src/scripts/headers/mebox/pieces/compactMeBoxStyles.ts, library/src/scripts/headers/titleBarStyles.ts, library/src/scripts/headers/vanillaHeaderStyles.ts, library/src/scripts/icons/iconClasses.ts, library/src/scripts/icons/icons.story.tsx, library/src/scripts/icons/titleBar.tsx, library/src/scripts/routing/links/BackLink.tsx, library/src/scripts/theming/ThemeLogo.tsx
Fixes various issues with titleBar/banner
- I was unable to reproduce the border radius issue
- Cheated position of icons (both signed in and out) to have the edge of the icon line up with the margins, not the edge of the button.
- Works with or without the back link. I added a param to hide it when there's no where to go (like when you land on the home page for the first time)
- Mobile logo is smaller and can be adjusted.
Closes: https://github.com/vanilla/vanilla/issues/10295
Needs approval from @ElisaAlmeida
=> Banner and TitleBar Style polish

library/src/scripts/flyouts/DropDown.tsx, library/src/scripts/flyouts/DropDownContents.tsx, library/src/scripts/modal/modalStyles.ts
Closes https://github.com/vanilla/knowledge/issues/1727
- Modals were overflowing the screen on iOS due to the max height getting set in vh units. VH units extend beyond the UI chrome on iOS. Percentages are more consistent and work because we are a fixed position container.
- Fix scrolling being broken in dropdowns converted to modals. The main issue here was extra containers being added around by the dropdown between the modal root and the scrollable frame. I fixed this by removing them. These extra wrappers didn't add any significant styles that weren't already provided by the modals.
The `VH` unit fix could only be reproduced on an actual iOS device. I did testing with my personal one. The scrolling could be reproduced with a big subcommunity list and desktop chrome in responsive …
=> Fix modal scrolling on iOS

library/src/scripts/banner/Banner.tsx, library/src/scripts/banner/DefaultBannerBg.tsx, library/src/scripts/embeddedContent/FormElements.story.tsx, library/src/scripts/errorPages/ErrorBoundary.tsx, library/src/scripts/forms/FormToggle.styles.ts, library/src/scripts/forms/FormToggle.tsx, library/src/scripts/forms/checkRadioStyles.ts, library/src/scripts/forms/formElementStyles.ts, library/src/scripts/forms/inputStyles.ts, library/src/scripts/forms/themeEditor/ThemeBuilder.styles.ts, library/src/scripts/forms/themeEditor/ThemeBuilderBlock.tsx, library/src/scripts/forms/themeEditor/ThemeBuilderCheckBox.tsx, library/src/scripts/forms/themeEditor/ThemeBuilderUpload.styles.ts, library/src/scripts/forms/themeEditor/ThemeDropDown.styles.ts, library/src/scripts/forms/themeEditor/ThemeEditor.story.tsx, library/src/scripts/forms/themeEditor/ThemeToggle.tsx, library/src/scripts/styles/globalStyleVars.ts, library/src/scripts/styles/styleHelpersAnimation.ts
- Add a form toggle component ([see the story](https://www.chromaticqa.com/component?appId=5d5eba16c782b600204ba187&name=Forms%2FUser%20Facing&mode=interactive&buildNumber=2936&specName=Elements&viewport=1200&browser=chrome)).
- Add a theme toggle component ([see the story](https://www.chromaticqa.com/component?appId=5d5eba16c782b600204ba187&name=Forms&mode=interactive&buildNumber=2936&specName=Theme%20Editor&viewport=1200&browser=chrome)).
- Update `<ThemeBuilderBlock />` to allow an info tooltip.
- Make form border colors consistent (we had different ones in use for the checkboxes, other user inputs, and the theme inputs).
=> Add form toggle component and info to theme block

library/Vanilla/Models/LimitedPipelineModel.php
PipelineModel methods `insert` and `update` were changed recently (https://github.com/vanilla/vanilla/pull/10330)
We need to align LimitedPipelineModel accordingly.
Required for: https://github.com/vanilla/knowledge/pull/1737
=> Adjust insert and update methods to match parent method declaration

applications/dashboard/views/modules/userinfo.php
Clients with custom themes always want to change the profile page and more than often this view has to be overridden because of the lack of flexibility. Adding those events should suppress that need in the future.
Reference: https://github.com/vanillaforums/telkomsel/pull/13#discussion_r401522988
=> Add events to userinfo view

applications/dashboard/settings/class.hooks.php
Fixes this potential error which could be reproduced with an invalid theme config. (dashboard only).
=> Fix null checking in dashboard hooks

library/src/scripts/banner/bannerStyles.ts, library/src/scripts/flyouts/DropDown.tsx, library/src/scripts/flyouts/FlyoutToggle.tsx, library/src/scripts/icons/iconClasses.ts
Fixed labels/screen reader text for the globe dropdown.
Fixed Banner text default color to not use fg (to stay white on both dark and light presets)
Closes: https://github.com/vanilla/internal/issues/2346
=> Globe dropdown text and banner fg color

library/src/scripts/theming/loadThemeFonts.ts
Backport #10392
> Using both siteUrl and assetUrl breaks the assetUrl handling on infra's node sites. I've adjusted the handling to just use `assetUrl`.
=> [Backport] Fix custom theme font loading on infrastructure

library/src/scripts/theming/loadThemeFonts.ts
Using both siteUrl and assetUrl breaks the assetUrl handling on infra's node sites. I've adjusted the handling to just use `assetUrl`.
=> Fix custom theme font loading on infrastructure

build/scripts/configs/makeBaseConfig.ts, library/src/scripts/banner/banner.story.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/banner/contentBannerStyles.tsx, library/src/scripts/forms/FormToggle.styles.ts, library/src/scripts/forms/FormToggle.tsx, library/src/scripts/forms/themeEditor/ThemeBuilderBreakpoints.tsx, library/src/scripts/forms/themeEditor/ThemeBuilderContext.tsx, library/src/scripts/forms/themeEditor/ThemeEditor.story.tsx, library/src/scripts/forms/themeEditor/ThemeToggle.tsx, library/src/scripts/styles/styleHelpersBreakpoints.ts
Blocking https://github.com/vanilla/internal/pull/2371
- Implements a utility method for defining responsive breakpoints.
- Implements a theme UI component for handling responsive breakpoints.
- Target something using responsive variables.
- Has a toggle to enable.
- When disabled it clears existing responsive images.
- Adds responsive breakpoint to story.
- Tweak the transition of the form toggle to be more fluid.
=> Implement responsive breakpoint utils and components for theming system

applications/dashboard/src/scripts/compatibilityStyles/textLinkStyles.ts
As per https://github.com/vanilla/internal/issues/2349 we're changing the color of discussion titles on the discussions page to black.
Closes: https://github.com/vanilla/internal/issues/2349
=> Foundation - Switch discussions titles color

library/Vanilla/Utility/HtmlUtils.php, library/core/functions.general.php, library/deprecated/functions.deprecated.php, tests/Library/Vanilla/Utility/HtmlUtilsTest.php
This method provides a PHP implementation similar to our [Translate component](https://github.com/vanilla/vanilla/blob/fc69c3cc00298ef0b7711b634fbcef72731fed86/library/src/scripts/content/Translate.tsx#L51) so that we can use the same translation strings on the client and server.
=> Add the HtmlUtils::formatTags() method

applications/dashboard/models/class.usermodel.php
closes https://github.com/vanilla/support/issues/1692
Searching for users in the dashboard moderation displays 0 users when no keyword is supplied if you have a role with no name and no users assigned to that role.
https://github.com/vanilla/vanilla/blob/d510e30533a4be57a8bae9c7815d7c65fef02604/applications/dashboard/models/class.usermodel.php#L2958
we try to get a role based on the keyword provided, if there is nothing provided then the keyword would be an empty string, when we do
$roleID = $this->SQL->getWhere('Role', ['Name' => $keywords])->value('RoleID');
}
this would return any role that has no name.
- Create a Role with no name
- Go to the dashboard moderation page
- Notice your user count displays 0 (if the new role with no name has no users already assigned to it)
=> Fix user count displaying 0 users when no search keyword is supplied

library/Vanilla/Models/SiteMeta.php, library/src/scripts/headers/mebox/pieces/UserDropDownContents.tsx, library/src/scripts/headers/mebox/pieces/UserDropDownContext.tsx
Closes: https://github.com/vanilla/vanilla/issues/10387
- Make sure you have SSO setup, I'm using jsConnect but any here will do https://github.com/vanilla/stub-sso-providers
- Make sure you have the Foundation theme or Keystone with the config `$Configuration['Feature']['DataDrivenTitleBar']['Enabled'] = true;` set to `true`.
- Log-in through SSO and click "Sign Out" in the mebox.
- Navigate back to the community and click "Sign In", your session should continue automatically because the cookie wasn't killed.
- Checkout this branch and reproduce the Sign-in/Sign-out steps to see the cookie was killed this time.
=> Fix Sign Out url in TitleBar

applications/dashboard/settings/structure.php, library/Vanilla/Database/Operation/CurrentUserFieldProcessor.php, tests/Library/Vanilla/Database/CurrentUserFieldProcessorTest.php
Add new `foreignID` field to reaction model db table.
Adjust `CurrentUserFieldProcessor` to allow user fields to be set when operations in `MODE_IMPORT`
Extend **CurrentUserFieldProcessorTest** to test operations in `MODE_DEFAULT` and `MODE_IMPORT`
Relates to: https://github.com/vanilla/knowledge/issues/1675
=> Extend CurrentUserFieldProcessor to respect operation MODE_IMPORT

library/Garden/ArrayContainer.php, library/Garden/Web/Dispatcher.php, library/core/class.dispatcher.php, tests/Library/Garden/Web/DispatcherTest.php
This PR implements a new `Dispatcher::reflectArgs()` method to replace the global `reflectArgs()` function. It is mostly the same, but allows for type-hinted class parameters to be satisfied by the container.
The use-cases for this are as follows:
- Some controllers may not want to inject an object for every single method, but rather only the method that needs it.
- For SSO, it’s sometimes easier to just use the `RequestInterface` rather than map arguments. This way you can implement against an exact spec, using a schema against the query parameters or something like that.
=> Add the ability for Gdn_Dispatcher to use the container to satisfy type-hinted args

library/src/scripts/banner/Banner.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts
Issue https://github.com/vanilla/knowledge/issues/1700
**NOTE: I highly recommend [viewing with whitespace changes hidden](https://github.com/vanilla/vanilla/pull/10410/files?diff=split&w=1)**
The search strip was being positioned on top of the background image, even if there was no offset being applied. This was due to a bug after our previous round of overflow fixes. Basically a `position: relative` container was missing.
Update the home widget inner container default color to match the body background instead of the main colors bg. The body BG defaults to the main color BG, but it the home widget is meant to blend with the body BG even if explicitly set.
=> Fix banner search strip positioning and home widget background

applications/dashboard/models/class.usermodel.php
Closes vanilla/support#939.
This PR adds rate limiting for confirmation email deliveries.
1. Check out this branch
1. Have outgoing email set up 
1. Sign in as a user with a role of unconfirmed and an email address you can access
1. Set the `LOGIN_RATE` constant to 100 in `class.usermodel.php`
1. Click on the link to send an email confirmation multiple times
1. Confirm that only one email was sent
=> Rate limit confirmation email deliveries

applications/conversations/controllers/api/MessagesApiController.php
closes https://github.com/vanilla/support/issues/1579#event-3232022436
Conversation message max length is configurable. You can do that by setting 
$Configuration['Conversations']['Message']['MaxLength']. 
Setting this config is not taking effect because of 
https://github.com/vanilla/vanilla/blob/1f988352b1888568f8160c5cc7a96c38f5cae860/applications/conversations/controllers/api/MessagesApiController.php#L121
We are looking for MaxLength config instead of Conversations.Message.MaxLength.
=> Fix conversation message MaxLength config

library/src/scripts/features/search/searchBarStyles.ts
Note that the border radis for the butons, do not impact the input text.
The Banner has as sparate border radius for the search, that's what's fixed here.
Closes: https://github.com/vanilla/knowledge/issues/1753ut
=> Fix bug regarding border radius of search bar in banner

library/Vanilla/Web/SmartIDMiddleware.php, tests/Library/Vanilla/Web/SmartIDMiddlewareTest.php, tests/Library/Vanilla/Web/TestSmartIDMiddleware.php
Currently, the primary key of a column name must be in the request body or the query string in order for a smart ID to take effect. This works for most of our API. However, there are some API endpoints where the column names do not correspond to primary keys.
This change allows developers to specify a fully-qualified smart ID in the form:
```
'$<primary key>.<column>:<value>'
```
So for example, I could let’s say have the following payload to the category table:
```json
{
"parentCategoryID": "$urlCode:hello"
}
```
Let’s say the column name was simply `parentID`. In this case I could specify the same payload with:
```json
{
"parentID": "$categoryID.urlCode:hello"
}
```
The extra “categoryID” tells the smart ID middleware to lookup the smart ID that resolves to a category ID.
*Note: By …
=> Add fully qualified smart ID support

library/src/scripts/navigation/NavLinks.tsx, library/src/scripts/navigation/NavLinksWithHeadings.tsx, library/src/scripts/navigation/SiteNavNode.tsx, library/src/scripts/navigation/navLinksStyles.ts
Working towards https://github.com/vanilla/knowledge/issues/1685
The nav categories component now has the ability to show a message on empty nav categories instead of hiding them.
Additionally they will never be hidden now. The view all link will always be displayed even if the index is empty.
=> Show an message in empty nav categories instead of hiding them

library/src/scripts/sectioning/TabStyles.ts, library/src/scripts/sectioning/Tabs.story.tsx, library/src/scripts/sectioning/Tabs.tsx, library/src/scripts/sectioning/TabsTypes.ts
Recently I needed to use this component for a different feature and needed to change the styles to fulfill this mockup https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5e6bde2eae501b111c0602bc even though the functionality is the same.
**This PR is a dependency for:**
https://github.com/vanilla/internal/issues/2358
=> Make the Tabs  Component CSS more flexible

library/src/scripts/forms/themeEditor/CustomFontUrl.tsx
I loosened the check for valid urls to allow empty fields to be valid. Prevents the user from seeing an error before having entered anything.
=> Theme Editor - Loosen valid url value check

applications/vanilla/views/modules/helper_functions.php
#8980 altered the way discussion titles are rendered in some modules. In the case of `DiscussionModule`, it ran titles through `htmlspecialchars`. Since those titles were already encoded, they are ultimately rendered as double-encoded on the site. This leads to seeing things like &amp;gt; instead of > or &amp;amp instead of & in discussion titles displayed by the module.
Title rendering has fallen back to displaying these titles using the practical replacement of the original `Gdn_Format::text`. No unnecessary HTML encoding is performed.
Closes vanilla/support#1727
=> Fix double encoding in DiscussionsModule titles

library/core/class.oauth2.php, library/core/class.ssoaddon.php, plugins/Facebook/class.facebook.plugin.php, plugins/Twitter/class.twitter.plugin.php, plugins/googlesignin/class.googlesignin.plugin.php, plugins/oauth2/class.oauth2.plugin.php
vanilla/addons#796 depends on this PR.
vanilla/internal#2399 depends on this PR.
Partially addresses vanilla/support#1618
Partially addresses vanilla/internal#2342.
Closes #10331
This PR fixes a problem where an SSO provider could be the default authentication provider even when disabled. This PR creates a class, SSOAddon, that extends Gdn_Plugin and includes a method that sets the `Gdn_UserAuthenticationProvider`'s 'IsDefault' value to 0 for any provider matching the 'AuthenticationSchemeAlias'.
It also adds an authenticationSheme variable to the Gdn_oauth2 class, which can be set in the Oauth2Plugin constructor.
I have done functional tests with every SSO plugin I know about, but this probably should be tested with one or two client custom oauth plugins as well.
1. Enable an …
=> Fix SSO provider can be default when disabled

library/Garden/Web/Dispatcher.php, tests/Library/Garden/Web/DispatcherTest.php
I had forgotten about our event handler controller args where the dispatcher itself supplies object arguments. This PR allows arguments to supply objects, but protects against bad arguments.
Closes #10446.
=> Fix Dispatcher::reflectArgs()

applications/dashboard/src/scripts/compatibilityStyles/forumTagStyles.ts, applications/vanilla/modules/class.tagmodule.php
Looks like adding the `.Tag` class on the tag cloud caused some compatibility issues with some legacy themes. Updated legacy styles to not rely on that class.
Closes: https://github.com/vanilla/support/issues/1722
=> Revert tag cloud tag

environment.php, tests/phpunit.php
This ensures that calls to functions like `htmlspecialchars()` will default to UTF-8.
Closes #10388.
=> Set the default character set to UTF-8

bootstrap.php
Closes https://github.com/vanilla/support/issues/1711
What is at issue here is that robots.txt is being served in the root of every subcommunity but never in the root of a domian. If someone has subcommunities turned on and they do want to apply specific rules for specific subcommunities they cannot. This PR will fix that.
- Turn on subcommunities.
- In a browser, type the root domain /robots or /robots.txt
- See that you are redirected to the default subdomain.
- Check out this branch.
- Repeat.
- See that you get a robots.txt in the root domain.
=> Fix robots.txt being served from subcommunities.

library/Vanilla/Models/ThemeModel.php, library/Vanilla/Theme/ThemeProviderCleanupInterface.php, library/Vanilla/Theme/ThemeProviderInterface.php, tests/Library/Vanilla/Web/Asset/WebpackAssetProviderTest.php, tests/Models/ThemeModelTest.php
Regarding https://github.com/vanilla/support/issues/1749
I've updated the theme model to be more robust in case something prevents a provider from registering.
- No longer tries to directly fetch the `DbThemeProvider` through it's provider list. Instead it checks if the provider has switch and if the provider implements `ThemeProviderCleanupInterface` it will use that to cleanup. DbProvider implementation here https://github.com/vanilla/internal/pull/2421
- No longer throws an exception if a provider can't be found. Instead a known fallback provider (FsThemeProvider) will be used in the event of a misconfiguration, some plugin getting disabled, or a bug in container registration.
- Adds a couple tests.
=> Fix theme model crashing site when theme provider can't be found

applications/dashboard/src/scripts/entries/forum.tsx, js/flyouts.js, library/Vanilla/Models/ThemeModel.php, library/Vanilla/Theme/ThemeProviderCleanupInterface.php, library/Vanilla/Theme/ThemeProviderInterface.php, tests/Library/Vanilla/Web/Asset/WebpackAssetProviderTest.php, tests/Models/ThemeModelTest.php
This PR backports to the following 2 changes to 2020.007
- [Fix theme model crashing site when theme provider can't be found](https://github.com/vanilla/vanilla/pull/10462)
- [Fix flyout and modal bugs in foundation](https://github.com/vanilla/vanilla/pull/10460)
=> 2020.007 backports

library/src/scripts/forms/buttonStyles.ts
Fix border color for secondary button ouline color, when selecting the "solid" preset.
Closes: https://github.com/vanilla/internal/issues/2308
=> Theming UI - Fix secondary button outline color when using "solid" preset

applications/vanilla/models/class.discussionmodel.php
Allows addons to adjust the format if the `force.inputformatter` is true
required for https://github.com/vanilla/internal/pull/2422
relates to https://github.com/vanilla/support/issues/999
=> Check if forcedFormat is set when Force.InputFormatter is true

library/src/scripts/styles/styleUtils.ts
We've had some warning popping up in the console here. https://success.vanillaforums.com/kb
Previously our `rgba()` and `hsla()` regexes did not allow integer values for the alpha, like `0` and `1`.
Now they do.
=> Allow color parsing to work with integer alpha values

applications/vanilla/controllers/class.postcontroller.php
closes https://github.com/vanilla/support/issues/1734
When a user has a rank that is restricted to a certain format, when the user edit a comment/discussion, the user gets "Format is required" erorr.
This is coming from here
https://github.com/vanilla/vanilla/blob/12770740af4634049ab9812dec0ef368b6cb5046/applications/vanilla/controllers/class.postcontroller.php#L990
w'ere setting ForceInutFormatter here
https://github.com/vanilla/internal/blob/master/plugins/Ranks/class.rankmodel.php#L278
then we check for that config, based on it, we remove the format.
Create and assign a rank that restricts a format to a user.
Post a comment/discussion and edit/save.
=> Fix format is required error with rank format restriction

library/core/functions.general.php
`betterRandomString` has a series of fallback strategies for attempting to generate cryptographically-secure values. The [`random_bytes`](https://www.php.net/random_bytes) function has been added as one of them.
=> Add random_bytes fallback to betterRandomString

applications/vanilla/controllers/api/CommentsApiController.php, applications/vanilla/models/class.commentmodel.php
Closes #9673 
The API sorts comments by commentID, but we want it to sort them by dateInserted instead. This PR does that by adding a $sort param in the `commentmodel.php` lookup function that can takes the name of the column to sort by. The `CommentsApiController` index function then specifies that comments should be sorted according to the DateInserted column.
1. Check out this branch. 
1. Find a discussion with multiple comments and change the dates of that discussion's comments in the `GDN_Comment table` so that the date order doesn't match the commentID order.
1. Make the api call to get the comments (`https://dev.vanilla.localhost/api/V2/comments?discussionID={discussionID}`).
1. Verify that the comments are ordered by date rather than commentID.
=> Sort APIv2 comments by dateInserted rather than commentID

applications/vanilla/js/discussion.js
closes https://github.com/vanilla/support/issues/1684
When editing a comment, cancelling then editing again, the cogwheel is not unresponsive.
when canceling, this is set to display:none
- Edit a comment
- Cancel
- Edit again
=> Fix comment cogwheel dropdown menu unresponsive after edit

applications/dashboard/src/scripts/entries/admin.tsx, library/src/scripts/theming/ThemeChooserInput.tsx
Issue https://github.com/vanilla/support/issues/1786
This is a core reducer but was only being registered in the themeapi plugin. As a result when it was disabled the theme chooser input would crash. I've removed the registration from the themeapi here https://github.com/vanilla/internal/pull/2453
I also added a couple of null checks.
=> Fix crash of product chooser when theme UI is disabled

applications/dashboard/src/scripts/entries/forum.tsx, library/src/scripts/analytics/AnalyticsData.tsx, library/src/scripts/bootstrap.ts
As I was writing some documentation for https://github.com/vanilla/internal/issues/2415 on configuring analytics events, I noticed our new pageView event isn't firing on the community.
I configured it to run there, but had to add a method for disabling our standard APIv2-based analytics tick.
This is because we currently have our old tick very tangled up in `global.js` which runs in the community and I don't have time at the moment to untangle it.
**Community & Dashboard**
1. Page loads
2. Legacy analytics tick from `global.js` runs.
3. handlers registered with `window.onPageView()` will run.
- The handler for `/api/v2/tick` will not run.
- Customer registered handlers will run.
**KB**
1. Page loads
2. handlers registered with `window.onPageView()` will run.
- The handler for …
=> Fire page view event in the community

applications/vanilla/controllers/class.categorycontroller.php
Closes vanilla/support#1776.
This PR fixes a problem where a user who follows a sub-category is redirected back to the main categories page, rather than the parent category page (i.e., the page they are on). This PR checks whether the followed category has a parent category and, if so, redirects to the parent category page.
1. Make a nested category.
1. Click the inner category's cogwheel and choose 'Follow'
1. Note that you are redirected to the main categories page.
1. Check out this branch, repeat steps 1 and 2, and note that you stay on the parent category page.
=> add sub-case for redirecting to parent category

library/src/scripts/forms/select/Tokens.tsx, package.json, yarn.lock
This PR is to make it possible for automated tests on token inputs. Since the values were all in memory, there was no easy way to access them. What I've done is added a hidden input that reflects the data stored in React. It will also listen to changes, so it can be set manually with something like: `document.querySelectorAll(".js-tokens-tokenInput")[0].value = '[{"value":14,"label":"AAAA"},{"value":15,"label":"BBBB"},{"value":6,"label":"CCCC"}]';`
I've also added a class to help with targeting the hidden input with JS. Note that it does not guarantee a unique class, unlike the actual ID of the component.
Closes: https://github.com/vanilla/vanilla/issues/10363
=> Token Improvements for testing

applications/dashboard/models/BannerImageModel.php, library/src/scripts/banner/Banner.tsx, library/src/scripts/banner/bannerStyles.ts, library/src/scripts/forms/themeEditor/ThemeBuilderContext.tsx, library/src/scripts/forms/themeEditor/ThemeInputText.tsx
- Modifies the bannerStyles.title.text to take the siteTitle and fallback to default text.
- Modifies bannerModel to only pass title prop if there is a category title.
- Modifies banner to use bannerStyles.title.text if no title prop is passed.
- Add allowEmpty on ThemeBuilderContext to allow for empty strings to be saved passed from ThemeInputText
required for https://github.com/vanilla/internal/pull/2436
related issue https://github.com/vanilla/knowledge/issues/1752
=> Various banner title changes

applications/vanilla/views/categories/helper_functions.php
Fixed https://github.com/vanilla/vanilla/issues/10499
`$row` was actually the incorrect variable. Looks like it was a copy/paste mistake. +10 points to adding some static checking into our PHP process.
=> Fix a bug preventing descriptions from appearing in foundation category list

library/core/class.upload.php
Regression from https://github.com/vanilla/vanilla/pull/10520
Example handler https://github.com/vanilla/vanillainfrastructure/blob/master/plugins/s3files/src/S3FilesPlugin.php#L208-L226
Fix the way we are passing the arguments to more consistent with existing events.
=> Fix regression in url event firing

library/Vanilla/Models/ThemeModel.php
I added this initially trying to a be a bit smart in overlaying current variables to mobile foundation when a legacy theme was the desktop theme.
This will need to be revisited in the future. For now I'm going to remove it as we had no requirements for it.
=> Fix theme normalization causing current theme assets to be added to foundation

applications/vanilla/controllers/api/DiscussionsApiController.php
Closes vanilla/support#962
This PR fixes a problem in the DiscussionsAPIController class where the categoryID is being used in the patch() method's fieldPermission calls. This creates a permission error when trying to patch a discussion in a nested category that inherits custom permissions from its parent by replacing the categoryID with the PermissionsCategoryID.
Make a category with custom permissions that allows a moderator to sink the discussion. Then add a subcategory that doesn't have custom permissions. Add a discussion to that subcategory and try to sink that discussion through postman as a moderator.
=> Fix permission check in categories that inherit permissions

applications/dashboard/controllers/api/NotificationsApiController.php, applications/dashboard/openapi/notifications.yml, tests/APIv2/NotificationsApiTest.php
These endpoints functionally can only mark notifications read, but were taking entire notifications as input parameters. This PR removes the rest of the notification input parameters, but does not otherwise modify functionality.
=> Fix the signatures of the PATCH /api/v2/notifications/* endpoints

applications/vanilla/controllers/class.postcontroller.php, applications/vanilla/views/post/discussion.php
Closes: https://github.com/vanilla/support/issues/1775
Relevant info: 
> The issue happens because drafts are not aware of subcommunities, when you access /drafts it returns all drafts made by that user, independent of which subcommunity you are.
When enabled, Subcommunities hook into the categoryDropdown and change the structure to fit the current subcommunity. It also shift the draft category ID to the subcommunity category, since this category is usually type "nested" it doesn't select that option in the categoryDropdown (because those options are disabled).
> 
> Since Drafts are supposed to be a shared content the Subcommunities is not supposed to intervene on the categoryDropdown when editing a draft.
**Reference:** https://github.com/vanilla/support/issues/1775#issuecomment-620731068 …
=> Fix drafts CategoryDropdown when Subcomunities is enabled

library/src/scripts/banner/Banner.tsx, library/src/scripts/banner/BannerContext.tsx, tests/fixtures/formats/html/attachments/output-attachments.json
The ref for the banner was undefined when `options.overlayTitleBar` was false, causing the calculation of the banner height to be 0.
Closes: https://github.com/vanilla/knowledge/issues/1808
=> Fixed sticky panel calculation

applications/dashboard/controllers/class.usercontroller.php, applications/dashboard/views/user/delete.php, applications/dashboard/views/user/deleteconfirm.php
Along with vanilla/internal#2485, this closes vanilla/support#1455.
This PR adds a checkbox option when deleting a user's content to choose whether to delete any moderation notes pertaining to the user's posts.
1. Create 2 users and add a moderation note for each one.
1. Check out both this branch and the `add/delete-notes-check` branch from vanilla/internal.
1. From `dashboard/user`, select the first user to delete using the trash can icon.
1. Choose 'Delete User Content'.
1. Leave the 'Delete moderation information' box unchecked and click 'Delete User Forever'.
1. Verify that the user is deleted, but the moderation note is still present (in the `Gdn_UserNote` table).
1. Repeat steps 2-4 with the second user.
1. This time, check the checkbox.
1. Verify that the moderation note is …
=> Add option to delete moderation notes

library/Vanilla/EmbeddedContent/EmbedService.php, library/Vanilla/EmbeddedContent/Embeds/PanoptoEmbed.php, library/Vanilla/EmbeddedContent/Factories/PanoptoEmbedFactory.php, library/Vanilla/Web/ContentSecurityPolicy/EmbedWhitelistContentSecurityPolicyProvider.php, library/src/scripts/embeddedContent/PanoptoEmbed.tsx, library/src/scripts/embeddedContent/embedService.tsx, tests/Library/Vanilla/EmbeddedContent/Factories/PanoptoEmbedFactoryTest.php
Estimate request: https://github.com/vanillaforums/estimates/issues/932
Issue: https://github.com/vanillaforums/panopto/issues/2
Add embed support for Panopto videos. You can find videos to test with [right here](https://howtovideos.hosted.panopto.com/Panopto/Pages/Folders/DepartmentHome.aspx?folderID=4b9de7ae-0080-4158-8496-a9ba01692c2e)
You can find the documentation I referred to in [a comment](https://github.com/vanillaforums/panopto/issues/2#issuecomment-599748154) I left in the github issue living in the customer's repo.
I looked at existing code we had for the react part, but it might not be the most efficient way to do it, I am open to any recommendations.
=> Add Panopto video embeds support.

applications/vanilla/settings/structure.php, applications/vanilla/tests/VanillaStructureTest.php, plugins/rich-editor/RichEditorPlugin.php
Closes https://github.com/vanilla/vanilla/issues/10536
- At some point we changed the rich format that gets applied from the branding page to `'rich`
- Config defaults (local and on infra) are 'Rich'.
- Value was historically 'Rich'
The casening was done in most places to some lowercase constant, and a lot of checks are case-insensitive, however getting the config values to be lowercase would be a lot riskier. As a result I'm reverting the config values to the old value for rich, and added something in structure to ensure it gets fixed for existing sites that may have set themselves to the lowercase value in the interim.
This affected a couple of our own sites which raised it to my attention. Notably in the last few days, our demo, staff, and success sites all lost their formatter as …
=> Fix rich post format getting lost

library/Vanilla/Web/ContentSecurityPolicy/EmbedWhitelistContentSecurityPolicyProvider.php
The script path defined in the PanoptoEmbed class was added to the EMBED_WHITELIST array in the EmbedWhitelistContentSecurityPolicyProvider class.
However, Content Security policy only works with domains.
The script path was replaced with the domain.
=> Fix the Panopto embed Content Security policy.

plugins/ProfileExtender/views/registrationfields.php
Related to https://github.com/vanilla/support/issues/952
Options were honoured properly in the profile view but not the registration view.
This caused an issue where `MaxLength` option would be respected on the profile page but not at registration.
This fix replicate exactly what is in the other view to minimize unforeseen problems. The logic seems very odd to me...
=> Honour ProfileExtender text fiels options on registration page

applications/vanilla/controllers/api/DiscussionsApiController.php
This will close vanilla/support#1837.
The post method of the discussionApiController currently uses the `categoryID` to check permissions, which creates a problem for creating discussions in certain nested categories. This PR fixes the problem by using the associated `CategoryPermissionID` from the `Gdn_Category` table. 
Make a category with custom permissions that allows a moderator to post discussions. Then add a subcategory that doesn't have custom permissions. Try to post a discussion to the subcategory through postman as a moderator. Alternately, you can comment out lines 309-311 in Permissions.php and post as an administrator.
=> Fix permission check in post method

applications/vanilla/controllers/api/DiscussionsApiController.php, library/Vanilla/ApiUtils.php, tests/APIv2/AbstractAPIv2Test.php
Closes vanilla/vanilla#9004
This PR fixes a problem where, when making this API call: `https://dev.vanilla.localhost/api/v2/discussions/`
the "Link" headers containing links to next and previous pages were relative rather than absolute.
Check out the branch and make this call: `https://dev.vanilla.localhost/api/v2/discussions/`
Verify that the links in the "Link" header are absolute.
=> Add host to links in discussion list API header

addons/themes/theme-foundation/assets/variables.json5
The empty array should have been commented in the default variables.
=> Fix default navigation items missing

library/database/class.sqldriver.php, tests/Library/Database/MySQLDriverTest.php
The SQL driver’s field expression passes through an unnecessarily long code path to arrive at a basic escape. This PR removes the overhead.
=> Optimize field expression in Gdn_SQLDriver::_whereIn()

library/database/class.sqldriver.php, tests/Library/Database/MySQLDriverTest.php
The SQL driver’s field expression passes through an unnecessarily long code path to arrive at a basic escape. This PR removes the overhead.
=> Backport: Optimize field expression in Gdn_SQLDriver::_whereIn()

library/core/class.theme.php, tests/Library/Core/BreadcrumbStructureTest.php
This PR will close vanilla/support#1658 
What's at issue here is that we are trying to follow http://schema.org/BreadcrumbList structured data but are receiving errors. The cause was twofold:
1. We are not declaring the first item in the breadrumb (the link to home) but we are adding an `item` tag to it.
2. We are using spans to structure the list but each list item, instead of being siblings are nested inside one another. 
This causes it to throw errors in googles validator: https://search.google.com/structured-data/testing-tool/u/0/
- Add an entry in your `/etc/hosts` so that you are using a legit TLD (**not** `.localhost`, **this will throw errors non-descript errors in google's validator**, I found out the hard way). **OR** you can manually change the base URL in the breadcrumbs from …
=> Fix structure of breadcrumb so that it follows the BreadcrumbList schema.

applications/dashboard/models/class.rolemodel.php, tests/APIv2/AbstractAPIv2Test.php, tests/InternalClient.php, tests/UsersAndRolesApiTestTrait.php
The trait structure and setup is inspired by the laravel setup test.
- Make an easy way to apply traits to our API testcase that each hook into the setup. This is done by making a method of a particular name. They cannot specify just `setUp` because then it is impossible to use multiple of these traits together.
- Create a user/role test trait.
- Create users.
- Create roles.
=> Add a test trait to make testing roles and user more easy

library/Vanilla/Utility/StringUtils.php, tests/Library/Vanilla/Utility/StringUtilsTest.php
These methods are meant to deprecate our problematic `stringBeginsWith()` and `stringEndsWith()`.
=> Add string utils methods

composer.json, composer.lock, library/core/functions.compatibility.php
PHP 8 has a few nice string functions that would be good to start using where needed rather than calling our own weird versions. The functions are:
- `str_starts_with()`
- `str_ends_with()`
- `str_contains()`
=> Add some PHP 8 compatibility functions

applications/vanilla/library/Navigation/ForumBreadcrumbProvider.php, library/Vanilla/Models/GenericRecord.php, library/Vanilla/Theme/ThemeFeatures.php, tsconfig.json
Blocking https://github.com/vanilla/internal/pull/2519
- A `GenericRecord` can be used when you don't know the exact type of your record and want to lookup breadcrumbs or something similar from what's registered on the model.
- Add some logic to make sure the "fake" synthetic root of the community is never returned.
The community has category named root as the `-1` record. Normally it does not get returned, however there's a special case of generating crumbs when viewing the root category. We actually want this to go to `/categories`.
=> Adjust forum breadcrumb generation and add generic record class

applications/vanilla/library/Jobs/UpdateDiscussionCount.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/models/class.discussionmodel.php
closes https://github.com/vanilla/support/issues/1709
closes https://github.com/vanilla/support/issues/1814
closes https://github.com/vanilla/support/issues/1804
When a category has hundreds of thousands of discussions, deleting a discussion is causing timeouts.
running select count(DiscussionID) on a table with 150+ records will take >30 seconds to complete.
Everytime we delete a discussion, w'ere calling https://github.com/vanilla/vanilla/blob/9d44b56e402ddc159012ece449ab307cd3bc71e9/applications/vanilla/models/class.discussionmodel.php#L2638
that updates the discussion count on a category.
updateDiscussionCount is taking more than 30 seconds(timeout) to complete.
I've created a job to update the count.
On a category with >150K discussions, delete a discussion
=> Fix deleting discussion timeouts

applications/dashboard/src/scripts/compatibilityStyles/searchPageStyles.ts, library/src/scripts/forms/select/tokensStyles.ts
- Fixed size of title on KB search page to be bigger than the panel's title
- Fixed the styles of the token input, the spacing was ugly and strange when the inner input text wrapped to a new line. It looks a lot more consistent now
- Improvements to forum's advanced search input. The arrow was positioned properly and the padding was adjusted as to not have text going under the arrow.
Companion PR: https://github.com/vanilla/knowledge/pull/1796
=> Various Designer Feedback Fixes

applications/vanilla/controllers/api/DiscussionsApiController.php, applications/vanilla/openapi/discussions.yml
This PR addresses vanilla/support#1240 and works in conjunction with vanilla/internal#2507
It adds the option to expand reactions to the `discussions/bookmarked` endpoint. It also changes the event name in the `fireEvent` call in the `discussionApiController`'s index method.
1. Make sure you have some discussions that are both bookmarked and have reactions. 
1. Check out both this branch and the `fix/refactor-reaction-api-hooks` branch from the internal repo.
1. Make these calls:
`api/v2/discussions?expand=reactions`
`api/v2/discussion/{some discussionID}?expand=reactions`
`api/v2/discussions/bookmarked?expand=reactions`
1. Verify that reactions are expanded on all of these calls
=> Add expand reactions option to bookmarked discussions

applications/vanilla/controllers/api/CategoriesApiController.php
I'm not sure why this was manage before, but we do have category permissions. We have category-specific permissions.
Here's the check on the normal category controller.
https://github.com/vanilla/vanilla/blob/3c15c05b199331e5677c828b6f8d745052b86688/applications/vanilla/controllers/class.categoriescontroller.php#L321
This category model method checks the PermissionCategoryID of the given category, then goes to the session to check the permission on it.
=> Fix permission check on GET categories endpoint

tests/Library/Garden/Web/DataTest.php
The data class tests were echoing out test data to the console. This fixes that to clean up the output.
=> Fix data tests

tests/Library/Garden/Web/DataTest.php
When I fixed the data test earlier, I had forgotten that there is actually a proper PHPUnit way to test echo’d output. Have a look.
=> Make the data test use the proper PHPUnit method

library/src/scripts/navigation/SimplePager.tsx
Relates to https://github.com/vanilla/internal/issues/2534
Using `<SimplePager />` will now automatically set `<link rel="prev|"next" />` elements in the head when used.
=> Add link rel elements to simple pager

applications/dashboard/models/class.searchmodel.php, library/core/functions.render.php, library/deprecated/functions.deprecated.php
The condense() function is likely to be buggy. The discussionLink() and fixnl2br() functions were already deprecated, but never moved.
I’ve checked and cleaned up usages of these functions.
=> Deprecate fixnl2br(), discussionLink(), and condense() render functions

composer.json
This API has a clear dependency on the `intl` extension, and is used by various parts of the frontend.
=> LocalesApiController requires ext-intl

applications/dashboard/settings/class.hooks.php, applications/dashboard/views/settings/mobilethemes.php
This PR will close this issue: https://github.com/vanilla/support/issues/1583 
What is at issue here is that there are desktop themes with options and mobile themes with options and there are desktop themes with options are that are also responsive. If you have chosen a responsive theme as your mobile theme you should not be presented with the options. 
This PR makes the distinction between a mobile theme and a responsive desktop theme and only allows users to change the mobile options on mobile themes.
- Choose a desktop theme with options (hint: keystone).
- See that there is a link in the Theme description to modify the Theme Options.
- See that you have a link in the left-hand menu for Mobile Theme Options
- Click on it and see that there are many checkmarks on theoretical display …
=> Do not display mobile theme options when a theme responsive.

library/core/functions.error.php
Closes vanilla/support#1896.
This PR puts the "Whoops! There was an error." string through the translate function.
=> Translate Whoops error message

library/Vanilla/FileUtils.php, library/Vanilla/UploadedFile.php, tests/Library/Vanilla/UploadedFileTest.php
Fixes https://github.com/vanilla/vanilla/issues/10593
Related https://github.com/vanilla/support/issues/1880
The bug was was introduced in https://github.com/vanilla/vanilla/pull/10520 when I started trying to preserve original file names in the URL. (previously we always used random IDs).
I swapped to slugifying the file names because it's URL safe and easier than handling URL encoding them (because then the file names on disk and in the URL are different). There's still no chance of collision because we use unique hashes for the file directory.
=> Fix file uploads for images with spaces

library/Garden/Web/Dispatcher.php
I was noticing undefined exeptions during some tests.
=> Add a null guard in the Dispatcher exception handler

applications/dashboard/controllers/class.profilecontroller.php
Closes vanilla/support#1824.
This PR fixes a problem that results in users being able to upload a photo from the `profile/edit` endpoint if that page includes with a `userphotomodule`. This fix loads the necessary js files that allow the button to function.
1. Load a version of vanilla that includes the userphotomodule at the `profile/edit`.
1. Go to that endpoint and try to upload a photo.
1. Note that the "Upload New Picture" button doesn't work.
1. Checkout this branch and try again, this time noting that it does work.
=> Fix js files not loading at profile/edit endpoint

composer.json, composer.lock, tests/APIv2/AbstractApiControllerTest.php, tests/Bootstrap.php, tests/Library/Vanilla/Web/APIExpandMiddlewareTest.php, tests/definitions.php, tests/phpunit.php
This PR makes all applications and plugin classes available during testing. This should aid addon tests that can be run without enabling the addon and reduce the need for extraneous `require` statements.
You will see in Bootstrap::registerAutoloader() there are some hard-coded addons being excluded. These addons have duplicate class definitions which is no-bueno. Until we can fix those addons they’ll need to be tested without global autoloading.
=> Add a global autoloader for testing

applications/dashboard/controllers/class.entrycontroller.php, cache/.htaccess
Original issue: https://github.com/vanillaforums/sonicwall/issues/50
**Description**: Depending on the login scenario the messaging sent to the user is confusing & may not be applicable. We need supplemental messages that would better explain the situation and guide the user. The new message goes as follow: "_You are trying to connect with a username that is already assigned to a user. If this is you, please enter the password you used when you created this account on this forum._" and is shown when the user tries to login with an existing user & no password is provided.
**QA Steps**:
- Have OAuth2 login enabled on the platform.
- Try to authentify with a user that would suggest an existing user handle. Ex.: If there is a user using the user handle "info" try an OAuth2 login with an email …
=> Improve user feedback upon login if there's a user match but the password is missing

library/Vanilla/Logging/LogDecorator.php, library/core/class.request.php, tests/Library/Core/RequestTest.php
Generate a UUID for each request for the purposes of logging.
_Note: I added some methods to `Gdn_Request` that model the PSR-7 `ServerRequestInterface`_
=> Add a UUID request ID to logs

library/Vanilla/Database/Operation/JsonFieldProcessor.php
Given that our attributes are almost always key value stores I think it’s more prudent to encode empty arrays as “{}” instead of “{}”.
=> Encode empty PHP arrays as “{}” in the JsonFieldProcessor

library/core/class.request.php, tests/Library/Core/RequestTest.php
This is a bit of campground cleanup with the following:
1. Added doc blocks to `Gdn_Request` and `RequestTest`.
2. Fix some line length and other lint issues.
3. Soft deprecate some of our older `Gdn_Request` methods where new ones already exist.
=> Cleanup Gdn_Request and its test

library/core/class.oauth2.php
backport https://github.com/vanilla/vanilla/pull/10625
=> Backport: update oauth2 connecttimeout (2020.009)

applications/dashboard/controllers/class.entrycontroller.php
This PR will close: vanilla/support#1718.
When we pass the target to the login link it is always a relative path. Forums with subcommunities and sitehub enabled are redirecting back to the hub but not the right subcommunity. In our smarty link function we pass the full URL as the target. 
https://github.com/vanilla/vanilla/blob/master/library/core/class.theme.php#L206
This PR would pass it in the default Sign In link.
=> Change the Target to the full path to website.

applications/dashboard/Events/NotificationEvent.php, applications/dashboard/controllers/api/NotificationsApiController.php, applications/dashboard/models/class.activitymodel.php, applications/dashboard/models/class.usermodel.php, tests/Models/ActivityModelTest.php
This update adds dispatching of a new `NotificationEvent` object when there are user notifications on a site.
1. `NotificationEvent` has been added to represent a user notification event.
1. The notifications API controller has had its schema and normalize methods extracted and moved to `ActivityModel`. There should be no functional changes in the notifications API controller.
1. The random calls to `Gdn::userModel` within `ActivityModel` are now replaced with a more apparent dependency, set as a class property in the class constructor. No functional changes should be caused by this adjustment.
1. If a notification is scheduled to be sent to a user, a `NotificationEvent` should be dispatched.
1. If a queue of user notifications is being processed, the default SSO IDs and user rows are …
=> Add resource event dispatching for user notifications

library/src/scripts/flyouts/StoryExampleDropDown.tsx, library/src/scripts/flyouts/dropDownStyles.ts, library/src/scripts/flyouts/items/DropDownItemLink.tsx
- isCurrent was unused.
- Check style is similar to the dropdown toggle.
- Added a cheat to our `dropdown-check` class to align it to the right (so it aligns correctly to the edge).
=> Add checkmark link prop for DropdownItemLink

tests/Bootstrap.php
This fixes a conflict where the autoloader tests were failing because the tests registered duplicate classes. Excluding this older plugin from the tests will fix the problem.
=> Exclude NBBC from autoloader tests

.gitignore
In #9505 this addition was [flagged](https://github.com/vanilla/vanilla/pull/9505#pullrequestreview-309312316) as incorrect, but it made it in anyway.
=> Remove phpunit.xml.dist from gitignore

applications/vanilla/controllers/class.categoriescontroller.php
Closes vanilla/support#1910.
This PR fixes an issue where the Categories aren't displayed in the side panel when viewing a nested category.
1. Set a category's display mode to "Nested".
1. View the category and note that the "Categories" section is missing from the side panel.
1. Check out this branch, view the page, and verify that the "Categories" section is there.
=> Add categories module to side panel on nested category page

library/core/class.dirtycache.php
Dirtycache caches values since 2013 despite its class description. See #6199 for more detail.
Since at least the UserModel relies on this behaviour (for the DB not to be flooded with queries), it should be documented.
=> Correct Gdn_Dirtycache documentation

library/src/scripts/utility/componentRegistry.tsx, plugins/pockets/PocketsPlugin.php, plugins/pockets/addon.json, plugins/pockets/src/scripts/conditions/PocketMultiRoleInput.tsx
This PR adds a new section to the edit pocket page, allowing the user to only display the pocket in chosen subcommunities.
A few things to note:
- The subcommunity picker and the roles picker have been moved up because they have a dropdown that made the page jump at the bottom
Closes: https://github.com/vanilla/vanilla/issues/10586
Requires: https://github.com/vanilla/multisite/pull/370
Replaced: https://github.com/vanilla/vanilla/pull/10629
=> Pockets by subcommunity

js/flyouts.js
Latest version of Safari on iPhone seems to have an issue handling [click events](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html), resulting in a bug where the flyouts don’t close once the user clicks outside.
**Reproduce the Error:**
1. Open community on an iPhone with latest version of Safari (or use Browserstack iPhone 8+).
1. Click on the Hamburger menu.
1. Click on any icon on the Mebox.
1. Try click outside the flyout to close it. 
**Fix:** :  Add ```touchstart``` event to handle the ```closeAllFlyouts()```
=> Fix click outside Flyout with Safari/Iphone by adding touchstart event

applications/dashboard/settings/structure.php
File based themes can be updated on deploys so we need to clear out the theme cache when updating the site after the deploy.
Our cache TTL is pretty low, but this way there is no significant delay.
=> Clear the theme cache on deploys

applications/dashboard/models/BannerImageModel.php, plugins/pockets/PocketsPlugin.php, plugins/pockets/js/pockets.js, plugins/pockets/src/scripts/conditions/PocketCategoryInput.tsx
This PR adds a pocket location under the banner, only for data driven themes.
Note I also found a bug with the category filter not being cleared properly on save.
Closes: https://github.com/vanilla/vanilla/issues/10417
=> Added pocket location after banner

library/Vanilla/Theme/NeonAsset.php
Backport of the fix for vanilla/support#1967
Initial implementation was here https://github.com/vanilla/vanilla/pull/10655 but the assets are quite different so I just made the change differently.
=> [Backport 2020.010] Fix NEON asset rendering

library/Vanilla/Theme/Asset/JsonThemeAsset.php, library/Vanilla/Theme/Asset/NeonThemeAsset.php, library/Vanilla/Theme/Theme.php, library/Vanilla/Theme/ThemePreloadProvider.php
Closes https://github.com/vanilla/support/issues/1967
- Fix JSON asset rendering all objects as arrays. This was a bug even before the refactor.
- Fix javascript asset not getting loaded (I was loading the wrong asset name.)
=> Fix JSON asset rendering and fetching the wrong asset for theme JS

applications/dashboard/Events/UserEvent.php, applications/dashboard/models/class.banmodel.php, applications/vanilla/Events/CommentEvent.php, applications/vanilla/Events/DiscussionEvent.php, library/Garden/Events/ResourceEvent.php, library/Vanilla/Database/Operation/JsonFieldProcessor.php, library/Vanilla/Events/EventAction.php, library/Vanilla/Logger.php, library/Vanilla/Logging/LogDecorator.php, library/Vanilla/Logging/LoggerUtils.php, library/core/class.logger.php, tests/APIv2/AbstractAPIv2Test.php, tests/APIv2/AssertLoggingTrait.php, tests/APIv2/CommentsTest.php, tests/APIv2/DiscussionsTest.php, tests/APIv2/UsersTest.php, tests/Bootstrap.php, tests/BootstrapTrait.php, tests/Library/Core/LoggerTest.php, tests/Library/Garden/Events/ResourceEventTest.php, tests/Library/Vanilla/Logging/LogDecoratorTest.php, tests/Library/Vanilla/Logging/LoggerUtilsTest.php, tests/Library/Vanilla/Logging/ResourceEventLoggerTest.php, tests/SiteTestTrait.php, tests/TestLogger.php
- Massage resource event payloads.
- Add standardized log fields.
- The log decorator can now resolve standard username fields.
- Log user bans.
- Add default log assertions to the Bootstrap trait so that classes can easily test logging.
- A lot of unit tests.
=> More logging enhancements

applications/dashboard/openapi/themes.yml, library/Vanilla/Theme/Asset/JsonThemeAsset.php, library/Vanilla/Theme/Asset/ThemeAsset.php, tests/APIv2/ThemesTest.php
As requested during the demo.
Requires https://github.com/vanilla/internal/pull/2590 as well to keep tests passing over there.
=> Add content type to the return of a theme

library/core/class.bbcode.php, tests/Library/Vanilla/Formatting/Formats/BBCodeFormatTest.php
This change will allow any URL where `parse_url()` succeeds with an appropriate scheme. Closes vanilla/support#859.
=> Relax URL checks in BBCode

applications/vanilla/views/categories/helper_functions.php
I ran into an issue where my `LastCategoryID` is 0 and it crashes the page. I added an extra check. @igraziatto, I saw you touched [this line](https://github.com/vanilla/vanilla/compare/fix%2Flast-category-id-zero?expand=1#diff-c1b172827df39c8108768ab4a4ebce5fL350) recently, so it might be related to that? 
I'm not sure if it's just my DB that has bad data, or this is a bug. If it's my DB, ignore this PR, but I would like to know how to fix it. Thanks!
=> Check if last category id is zero

applications/dashboard/models/class.activitymodel.php, library/core/class.format.php
Closes https://github.com/vanilla/support/issues/1872
1. Make sure your local is setup to send emails
2. On the Dashboard > Registration > Method set to **Approval**
3. Take an admin user, go to edit profile mark the "Notify me when anyone applies for membership."  preference. Save the form.
4. Open an anonymous tab and register for your local.
5. Notice you do not get an email notification saying "{username} applied for membership." 
6. Checkout this branch and repeat step 4., this time you should get an email.
=> Fix applicants email notification

library/src/scripts/navigation/SimplePager.tsx
Backport #10669 
I've only backported the bug fix part. I did not backport the testing library updates.
=> [Backport 2020.010] Fix simple pager meta link crash

library/Vanilla/Models/ThemePreloadProvider.php
=> [Backport 2020.010] Fix forced loading of the theme preview page when another theme is enabled

library/Vanilla/AliasLoader.php, library/Vanilla/Theme/Theme.php, library/Vanilla/Theme/ThemeService.php
Fixes https://github.com/vanilla/knowledge/issues/1840
We had an edge case where a theme could be cached, but the value of whether it was current or not was changed by something that didn't trigger a cache clear (like manually editing a theme).
This would cause the manage themes page to get the incorrect "current" theme. In order to mitigate this, our "normalize" method now set the proper current theme for every theme that passes through.
=> Fix theme current crash

library/src/scripts/content/NumberFormatted.tsx
This PR is related to the issue [#2587](https://github.com/vanilla/internal/issues/2587) and the PR [#2602](https://github.com/vanilla/internal/pull/2602). Todd commented that the number 2 tooltip on top of the number is not useful (see screenshot below): 
I've add an optional title so that we could have 
by writing ` +<NumberFormatted value={extraCount} title={"View all attendees"} />`
=> Add an optional title for number count

applications/dashboard/views/settings/helper_functions.php, library/Vanilla/Addon.php, tests/Library/Vanilla/AddonTest.php
Related https://github.com/vanilla/support/issues/2012
Some types of addons, like groups have issues with changing their `name` field. The name field gets misused and
- Written to the config.
- Used in URLs.
- Used to display permissions!!!
Rather than rework these existing systems extensively for our 1 and only application (groups), I've just added an ability for an addon to set a `displayName` property for them. This will be shown in the addons/plugins page but not used for any actual logic.
=> Add ability for addons to have a new addon display name

applications/dashboard/views/settings/helper_functions.php, library/Vanilla/Addon.php, tests/Library/Vanilla/AddonTest.php
Backport https://github.com/vanilla/vanilla/pull/10684
Issue https://github.com/vanilla/support/issues/2012
=> [Backport 2020.011] Add ability for addons to have a new addon display name

applications/dashboard/views/settings/helper_functions.php, library/Vanilla/Addon.php, tests/Library/Vanilla/AddonTest.php
Backport https://github.com/vanilla/vanilla/pull/10684
Issue https://github.com/vanilla/support/issues/2012
=> [Backport 2020.010] Add ability for addons to have a new addon display name

bootstrap.php, library/Vanilla/Logging/LogDecorator.php, library/core/class.logger.php
Backporting #10688 to `release/2020.011`.
=> Backport: Don’t install the log decorator too early

applications/vanilla/library/class.categorycollection.php, applications/vanilla/models/class.categorymodel.php
Required for https://github.com/vanilla/internal/pull/2612
- Add `getDescendantIDs` method to categoryCollection class.
- Modifies `expandCategories` to look for `ParentRecordID` if `CategoryID` not available.
=> Add CategoryCollection::getDescendantIDs

applications/dashboard/views/settings/helper_functions.php
Since #10684, addons are appearing with their default, less-readable names in the dashboard. This update addresses that to make them display the intended name.
=> Fix addon naming in dashboard

library/core/functions.render.php
This PR closes vanilla/support#1409
When a user is banned his/her avatar is replaced by a "Banned" avatar. Vanilla allows admins to add upload a different photo and configure it in the config file as `Garden.BannedPhoto`. However, in the dashboard we show a different avatar for banned users which is not configurable (`https://images.v-cdn.net/banned_100.png`). 
This PR will create a new config value `Garden.BannedPhotoSmall` which will allow admins the ability to set that to a custom photo. This is backwards compatible because if nothing is set it will get the default photo `https://images.v-cdn.net/banned_100.png`.
=> Fix the user avatar for banned users.

library/Vanilla/Contracts/Formatting/FormatInterface.php, library/Vanilla/EmbeddedContent/AbstractEmbed.php, library/Vanilla/Formatting/FormatService.php, library/Vanilla/Formatting/Formats/HtmlFormat.php, library/Vanilla/Formatting/Formats/NotFoundFormat.php, library/Vanilla/Formatting/Formats/RichFormat.php, library/Vanilla/Formatting/Formats/TextFormat.php
This PR adds a new function to the formats interface to fetch image attributes. I chose not to touch the existing `parseImageUrls` as it is used in multiple places and I also don't want to make drastic changes to the code here. I'm just trying to fetch the alt tag for search results.
=> Added function to fetch image attributes from user content

applications/vanilla/openapi/discussions.yml, library/Vanilla/OpenAPIBuilder.php, library/Vanilla/Utility/ArrayUtils.php, tests/Library/Vanilla/OpenAPIBuilderTest.php, tests/Library/Vanilla/Utility/ArrayUtilsTest.php
This PR fixes a long standing issue with the way we build our schemas when two schemas have overlapping enums. Before it would choose one. Now it will merge the two and remove duplicates.
This PR introduces the following changes:
- Added the `ArrayUtils::arrayMergeRecursive()` utility function as a generic way to solve this problem. It has full test coverage, but I'm guessing there are edge cases it doesn't cover.
- Refactored the `OpenAPIBuilder` a tiny bit to make use of the above utility function. In particular `OpenAPIBuilder::mergeSchemas()` handles the specific schema merging. It has tests for the specific bugs in question.
- Refactored the `discussions.yml` OpenAPI spec to consolidate the various expand parameters as this was the cause of the original bug report, addressed in [this …
=> Fix OpenAPI’s schema merging

applications/dashboard/controllers/api/UsersApiController.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/openapi/schemas.yml, applications/dashboard/openapi/users.yml, applications/vanilla/controllers/api/CategoriesApiController.php, applications/vanilla/controllers/api/CommentsApiController.php, applications/vanilla/controllers/api/DiscussionsApiController.php, applications/vanilla/models/class.categorymodel.php, applications/vanilla/openapi/categories.yml, applications/vanilla/openapi/comments.yml, applications/vanilla/openapi/discussions.yml, library/Vanilla/ApiUtils.php, library/Vanilla/Schema/RangeExpression.php, library/Vanilla/Utility/SchemaUtils.php, tests/APIv2/CategoriesTest.php, tests/APIv2/CommentsTest.php, tests/APIv2/DiscussionsTest.php, tests/APIv2/TestPrimaryKeyRangeFilterTrait.php, tests/APIv2/UsersTest.php, tests/Library/Database/MySQLDriverTest.php, tests/Library/Vanilla/ApiUtilsTest.php, tests/Library/Vanilla/OpenAPIBuilderTest.php, tests/Library/Vanilla/RangeExpressionTest.php, tests/Library/Vanilla/Utility/SchemaUtilsTest.php
Added the ability so specify a range or CSV of values in various endpoints:
- `GET /api/v2/discussions?discussionID=<range>`
- `GET /api/v2/users?userID=<range>`
- `GET /api/v2/comments?commentID=<range>`
- `GET /api/v2/categories?categoryID=<range>`
This functionality all has some basic test coverage.
This PR also comes with some yack shaving:
- The `RangeExpression` has some bug fixes and enhancements. Everything here has test coverage.
- I added the `ApiUtils::parsePageHeader()` utility function to cut down on regex errors. This was in service of the main tests, but it has its own smoke tests too.
- I added the `SchemaUtils::onlyOneOf()` utility higher order function to hopefully prevent a support request when someone passes incompatible parameters to the `GET /categories` endpoint. …
=> Add primary key lookup support in various API v2 endpoints

library/Vanilla/Theme/ThemeService.php
Related https://github.com/vanilla/support/issues/2021
Related https://github.com/vanilla/support/issues/2060
Fixes https://github.com/vanilla/support/issues/2047
Related https://github.com/vanilla/support/issues/2063
=> Fix normalization of current theme when Garden.CurrentTheme isn't set

library/Vanilla/Theme/ThemeService.php
Related https://github.com/vanilla/support/issues/2021
Related https://github.com/vanilla/support/issues/2060
Fixes https://github.com/vanilla/support/issues/2047
Related https://github.com/vanilla/support/issues/2063
Backport #10734
=> [Backport 2020.011] Fix normalization of current theme when Garden.CurrentTheme isn't set

library/Vanilla/EmbeddedContent/EmbedService.php, library/Vanilla/Utility/UrlUtils.php, tests/Library/Vanilla/Utility/UrlUtilsTest.php
Currently, our schema rejects non-ascii URLs which results in scrape errors for unicode characters. This PR normalizes and encodes all URLs before scraping to address this. It also will hopefully use fewer cache keys for the scrapes.
Fixes https://github.com/vanilla/support/issues/860.
=> Normalize unicode in URL paths before scraping

applications/vanilla/controllers/class.categoriescontroller.php
Fixes an issue where the root category would be visible because our default site section now has a categoryID.
=> Fix category homepage displaying the root category

js/flyouts.js
Closes https://github.com/vanilla/support/issues/2061
The code introduced here https://github.com/vanilla/vanilla/pull/8475 make a few improvements on the flyouts but also broke it on lithemobile.
This is a bit tedious to test but essentially you need to test the flyouts on a bunch of different themes. I've tested with:
- keystone (desktop and mobile)
- theme-foundation (desktop and mobile)
- deflector (desktop)
- bootstrap3 (desktop)
- lithemobile (mobile)
**Tests to perform:**
- The "New Discussion" dropdown:
- Open the flyout, close clicking outside, close clicking the arrow, choose one of the options (test desktop and mobile)
- The "Flag" flyout:
- Open the flyout, close clicking outside, choose the "warn" option. Close the popup (test desktop and mobile).
- …
=> Fix legacy themes mobile flyouts

library/Vanilla/Theme/ThemeService.php
Backport https://github.com/vanilla/vanilla/pull/10754
=> [Backport 2020.011] Fix theme service caching not accounting for normalized variables

library/Vanilla/Theme/ThemeService.php
These changes are needed for the K KB launch.
Normalization can merge in extra variables that aren't considered in our theme cache, so we still have to do this no matter what.
Things this accounts for:
- ThemeFeatures.
- Current theme
- overlayed addon variables
=> Fix theme service caching not accounting for normalized variables

library/src/scripts/flyouts/items/DropDownEditProfileLink.tsx, library/src/scripts/headers/mebox/pieces/UserDropDownContents.tsx, library/src/scripts/headers/mebox/pieces/UserDropDownContext.tsx
This PR creates a new component for the edit profile/preferences. It checks if the user can edit their profile. If not, it falls back to a link to the user's preferences.
Closes: https://github.com/vanilla/knowledge/issues/1846
=> Extra check for edit profile link in new mebox

library/Vanilla/UploadedFile.php, tests/Library/Vanilla/UploadedFileTest.php
This PR will close vanilla/support#1962
In Rich editor we use actual names of files for images embedded on sites which is great for SEO, etc. Unfortunately when image that have "foreign" characters in their names they are saved URL encoded. But when you fetch them the URLs are decoded, so that they are not found.
This PR will double encode the saved URL so that when we fetch the image from storage we have the correct address.
1. Turn on Rich editor.
2. Re-name an image on your local computer to 'pic-我的照片.jpg'
3. Upload it in a post.
4. See that it is not found.
5. Check out this branch.
6. Upload the same image.
7. Make sure English named images still work.
8. Test on other editors.
9. Approve PR.
=> Fix encoding on file names.

library/src/scripts/flyouts/items/DropDownEditProfileLink.tsx
This extra character was appearing
=> Remove extra character from mebox

library/core/class.format.php, tests/Library/Vanilla/Formatting/GdnFormatLinksTest.php
Closes vanilla/support#1930
While using the Advanced Editor's BBCode option, you cannot post a url that includes braces. This PR allows a url with braces as long as it occurs after the `//` in an address.
1. Enable Advanced Editor and select the BBCode posting option.
1. Post this url in a discussion: 
`https://www.example.com/this{has-braces}`
1. Verify that the link ends right before the opening brace
1. Repeat steps 1-2 above.
1. Verify that the whole url is a link
=> Fix urls splitting on braces in BBCode

plugins/pockets/PocketsPlugin.php
Fixes https://github.com/vanilla/support/issues/2110
`processPockets()` function was assuming the sender was always a controller. In the case of the banner image renderer, it was not.
In order to fix this, I explicitly grab the controller (which was already being used in this method), to get the page.
=> Fix pocket location insantiation

library/Vanilla/Theme/Theme.php, tests/Library/Vanilla/Theme/ThemeServiceCurrentTest.php, tests/fixtures/addons/themes/theme-options/addon.json, tests/fixtures/addons/themes/theme-options/assets/option1_variables.json, tests/fixtures/addons/themes/theme-options/assets/option2_variables.json
Fixes https://github.com/vanilla/support/issues/2077
I was using the wrong index on the theme options regex. I fixed the index and added some tests.
=> Fix theme options not working in the theme service

applications/vanilla/models/class.categorymodel.php
When expanding a the root category we were assigning the name of the category to the value in config for `$Configuration['Garden']['Title'] `.  If that was empty it would return an empty string which would fail validation on the expand param in the \events endpoint.  This fallback to the value set in our config-defaults which is `Vanilla`, if the config value is empty.
closes https://github.com/vanilla/vanilla/issues/10751
=> Fix events created in root category failing validation

library/Vanilla/FeatureFlagHelper.php, library/Vanilla/Models/FullRecordCacheModel.php, library/Vanilla/Models/ModelCache.php, library/Vanilla/Models/ModelCacheInvalidationProcessor.php, library/Vanilla/Models/PipelineModel.php, tests/Library/Vanilla/Models/ModelCacheTest.php
Related https://github.com/vanilla/internal/issues/2691
Implement a core model and some utilities that implement full record caching.
To help lower the risk (because this will likely need to be backported for performance considerations), I've added a feature flag to disable it.
`Feature.DisableNewModelCaching.Enabled = true`
- A pipeline processor for invalidating.
- Nice utility methods
- `getCachedOrHydrate(array $cacheArgs, callable $hydrator)` -> Get a cached value or hydrate it.
- `invalidateAll()` -> Invalidate the whole cache for the model.
- A extra convienience model base class anything that passes through the pipeline.
- Items could be manually invalidated with the invalidate method.
- Invalidation happens by rolling over an incrementing ID thats used in every cache key.
- …
=> Add a model with full record caching

addons/themes/theme-boilerplate/package.json
This is a blocker for publishing theme-boilerplate to maintaining themes who have it as a dependency.
This is a blocker for: https://github.com/vanilla/support/issues/1863
=> Remove theme-boilerplate private flag

library/Vanilla/Database/Operation/JsonFieldProcessor.php, tests/Library/Vanilla/Models/ModelTest.php, tests/Library/Vanilla/Models/PipelineModelTest.php
Since https://github.com/vanilla/vanilla/pull/10764 we are now running pipelines on delete operations.
CI over here is failing because we have tests for a delete operation on a pipelinemodel using the JsonFieldProcessor. https://app.circleci.com/jobs/github/vanilla/knowledge/18628
- I've fixed the json processor.
- I've added some tests that reproduced the issue in core.
- I've reviewed all of our other processors. This is the only one with a condition where it would fail to return a value.
=> Fix json processor breaking delete operations

applications/vanilla/views/discussions/popin.php
This was actually a fairly tedious support issue to track down because both the old and new translation key were in different resources.
=> Change the no bookmarks translation code

plugins/ProfileExtender/class.profileextender.plugin.php
Closes vanilla/support#2015.
Currently, if you have a profile extender field named "location," the location data that is stored in the `Gdn_User` table is overwritten by the query for location data in the `Gdn_UserMeta` table. The problem is that the location data is never stored in the `Gdn_UserMeta` table in the first place, so the location field will always be empty. This PR fixes the problem by skipping the `Gdn_UserMeta` query if the field is named "location".
1. Enable Profile extender and add a "Location" field.
1. Create or edit a user to give their profile a location.
1. Go to the `utility/exportprofiles` endpoint and press enter.
1. Look at the .csv file and note that there is no location data for that user.
1. Check out this branch and repeat step 3.
1. Look at the .csv file …
=> Fix location data missing when exporting profiles

bootstrap.php, library/Vanilla/Utility/ContainerUtils.php, tests/Library/Vanilla/Utility/ContainerUtilsTest.php
This update adds a `replace` method to `ContainerUtils` that performs the following:
1. Replaces a shared instance of a class, if available.
1. Optionally adds an alias from the original class to the replacement class.
The method is used to replace the introduction of the log decorator in the bootstrap.
The `ContainerUtils` class has been cleaned up a little to satisfy my IDE.
=> Add convenience method for replacing shared instances in the container

plugins/VanillaStats/class.vanillastats.plugin.php
#10700 fixed pointer events with SVGs in the dashboard, but Vanilla Stats overrides some dashboard pages and was not getting this fix because of it. This update applies the same fix to the Vanilla Stats page override.
=> Add SVG pointer events fix to Vanilla Stats page override

library/src/scripts/headers/mebox/pieces/UserDropDownContents.tsx
Closes https://github.com/vanilla/support/issues/2055
- Have some applicants count
- Enable Foundation theme or Keystone with `$Configuration['Feature']['DataDrivenTitleBar']['Enabled'] = true;`
- Check that the Applicants count don't match
- Checkout this branch
=> fix Applicants count on UserDropDownContents

plugins/VanillaStats/class.vanillastats.plugin.php
Backporting #10810 to `release/2020.012`.
> #10700 fixed pointer events with SVGs in the dashboard, but Vanilla Stats overrides some dashboard pages and was not getting this fix because of it. This update applies the same fix to the Vanilla Stats page override.
=> Backport: Add SVG pointer events fix to Vanilla Stats page override 

applications/dashboard/controllers/api/UsersApiController.php, applications/dashboard/models/class.usermodel.php, applications/dashboard/openapi/users.yml, tests/APIv2/UsersTest.php, tests/SiteTestTrait.php
This PR adds a `roleID` parameter to the `GET /api/v2/users` endpoint. Closes https://github.com/vanilla/support/issues/2151.
=> Add the role ID parameter to the GET /users endpoint

applications/vanilla/models/class.discussionmodel.php
This PR will close vanilla/support#2067
When using the Report feature we quote the post and create a new post with the quote. This means that the post now consists of an embedded quote which does not get counted in the size of the post. In other words, the full post becomes : "Quote" when you convert to plain text. It's count is therefore, 7 with the quotation marks. If a forum is configured to have a minimum content length of, say, 10 it will say that this content is 3 characters too short. 
Since Reports are always quoted, this PR will bypass that plain text conversion when validating its minimum length.
1. Turn on reporting.
2. Make sure the minimum post length is more that 7 in "Posting" in the Dashboard.
3. Report a post (make sure your Report comment is bigger than the minimum post …
=> Fix validating content length on Reported Posts

applications/dashboard/controllers/class.profilecontroller.php
Closes vanilla/support#2103.
Right now, if you try to upload an avatar that a disallowed file type (e.g., `.exe` or `.svg`), the file is never uploaded, but the user doesn't receive and error message. This PR adds an error message in that case.
1. Go to `profile/picture` and try to add a disallowed file type.
1. Note that although the image doesn't get uploaded, you get a little inform message in the bottom lefthand corner that reads: "Your settings have been saved"
1. Check out this branch and try to upload the file again.
1. Verify that you get a proper error message.
=> Add error message when uploading avatar of disallowed file type

applications/dashboard/settings/class.hooks.php, library/Vanilla/Utility/SqlUtils.php, tests/Library/Vanilla/Utility/SqlUtilsTest.php
This feature will ensure that text fields are not altered when the database alters if the old field is already a text field.
Sometimes a text field changes in size for whatever reason or sometimes a particular site requires a larger field. We want to be able to support those scenarios without being spammed on database alters.
This feature does not come without some risk: we are hiding inconsistency in our system and we are changing some important, low-level code. However, that risk is mitigated with tests and best practices. We should use this feature rarely and carefully.
Closes https://github.com/vanilla/internal/issues/2730
=> Keep text field lengths the same on alters

applications/vanilla/controllers/class.discussionscontroller.php
closes https://github.com/vanilla/support/issues/1046
**Details**
Category following filter is getting applied to pages other than /discussions.
**To Test**
- Follow a category
- In recent discussions, filter by followed categories
- Goto /discussions/unanswered, the filter should not be applied to this page
Categories are getting filtered on the discussions/unanswered page because of https://github.com/vanilla/vanilla/blob/7edd743c181f2d80c828f78ccd6724c13b37e122/applications/vanilla/controllers/class.discussionscontroller.php#L165
we are returning followed categories. 
The filtering has been removed from Qna here https://github.com/vanilla/vanilla/pull/7220
=> fix category following filter

tests/fixtures/src/MockSiteSectionProvider.php
back-port of https://github.com/vanilla/vanilla/pull/10696
=> [Backport 2020.011] Add new mockSiteSectionGroup with only one section

applications/vanilla/js/autosave.js, js/flyouts.js
Making some improvements to saving drafts and kludging flyouts.
1. Saving drafts will be de-prioritized a bit in the browser by way of [`window.requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).
1. All flyouts in a page are currently being kludged whenever new content is loaded. This means the same content can be re-kludged several times, per page view (e.g. when drafts are automatically saved and the notification is displayed). They're now tagged as being kludged and the selector should dodge them in subsequent kludging.
Closes vanilla/support#1484 (best effort for now)
=> Fix kludged flyouts being unnecessarily re-kludged

applications/vanilla/models/class.discussionmodel.php
This PR will backport https://github.com/vanilla/vanilla/pull/10804 to release/2020.011
When using the Report feature we quote the post and create a new post with the quote. This means that the post now consists of an embedded quote which does not get counted in the size of the post. In other words, the full post becomes : "Quote" when you convert to plain text. It's count is therefore, 7 with the quotation marks. If a forum is configured to have a minimum content length of, say, 10 it will say that this content is 3 characters too short. 
Since Reports are always quoted, this PR will bypass that plain text conversion when validating its minimum length.
1. Turn on reporting.
2. Make sure the minimum post length is more that 7 in "Posting" in the Dashboard.
3. Report a post (make sure your …
=> [Backport] Fix validating content length on Reported Posts

applications/vanilla/controllers/class.moderationcontroller.php
Closes vanilla/support#1298.
Currently, when you delete one or more comments of a discussion via the checkbox (rather than the cogwheel), you are redirected to the main discussions page, which is undesirable if you're not done working on that discussion. This PR sets the redirect to the current discussion.
I have done functional tests within subcommunities and on a hub-node setup.
1. Go to any discussion with comments and delete a comment via the checkbox.
1. Note that you get redirected to the main discussion page.
1. Repeat step 1 and verify that you get redirected to the current discussion.
=> Fix confirmCommentDelete redirect to point to current discussion

applications/dashboard/models/class.usermodel.php
Closes https://github.com/vanilla/vanilla-patches/issues/702
1. Register with an email and username (basic registration method) and wait for the confirmation email to appear.
1. Take the supplied link in the register confirmation  email (for example: https://open.vanillaforums.com/entry/emailconfirm/72565/ZKID6I2f6FwDeyshAXUCEkJybbkRAzYU) and increment the value "72565" (or whatever number appears in the confirmation link) by 1 (thus: "72566").
1. Open the changed link in a browser.
1. Logout.
1. Register with a different email and different username directly after opening the link. The error message will now pop up and say "value is not a valid object" preventing the user from registering.
=> Clear user cache on insertInternal

library/Vanilla/ApiUtils.php, tests/Library/Vanilla/ApiUtilsTest.php
When an object is used internally in an API endpoint, such as `RangeExpression`, pagination headers are not properly including these values. This is due to `http_build_query` not stingifying objects.
`ApiUtils::pagerUrlFormat` has been updated to cast values to strings before attempting to build the query.
=> Fix RangeExpression parameters not being passed in link headers

library/Vanilla/Search/GlobalSearchType.php, library/Vanilla/Search/SearchQuery.php
This PR implements a few new features in our search service (currently only implementation to target is sphinx. MySQL will need to be implemented by @alex-mtl).
- Implements filtering by date.
- Implements 2 new recently added explicit sort filters. Relevance was always the default before, but now sorting can be specifically done by dateInserted (which is a global sort).
Tests for sphinx implementation are here https://github.com/vanilla/internal/pull/2738
=> Add date filters and search relevance

applications/dashboard/views/message/edit.php
Closes https://github.com/vanilla/support/issues/2167
**Steps to test:**
- Open `https://{{local}}/dashboard/message`
- Make sure you have a message, click on the "edit" icon. A modal will open.
- Scroll to the right and notice the "Include Subcategories" checkbox is misaligned.
- Checkout this branch.
=> Fix mod message subcategory checkbox alignment

applications/dashboard/modules/class.pagermodule.php
There was a change introduced in [this PR](https://github.com/vanilla/vanilla/pull/10694) that was later partially rolled back [here](https://github.com/vanilla/vanilla/pull/10694). It left behind an extra parameter that wasn’t always passed, which lead to a page crash because the method wasn’t being properly called.
Closes https://github.com/vanilla/support/issues/2189.
=> Fix previous link page error

library/src/scripts/search/SearchPageRoute.tsx
Fixes issue in the prod build where the dashboard won't load.
I'm not 100% sure why not implicitly specifying the loader for this page caused the issue, but this resolves it.
=> Fix kb dashboard dependency on kb

library/Vanilla/AddonManager.php
This reverts commit 04ad592d91b9a638b593f082b76506c3206bea5b.
Sorry, we strive not to use static references in the Vanilla and Garden namespaces. Moreover, that reference is bugged.
=> Revert "A config overide for relative/absolute path in setCacheDir"

applications/dashboard/src/scripts/entries/forum.tsx, library/src/scripts/routing/RouteHandler.tsx, library/src/scripts/search/SearchPage.tsx, library/src/scripts/search/SearchPageRoute.tsx
The loader component type of `RouteHandler` was incorrect and as a result caused the search page to load incorrectly.
I've fixed the type and the incorrect usage.
=> Fix search page mounting

tests/SiteTestTrait.php
I just recently added this method so that it could be overridden, but I accidently used `self` instead of `static`.
=> Update site test trait to allow overrides

library/Vanilla/Logging/LogDecorator.php, library/core/class.oauth2.php, tests/Library/Vanilla/Logging/LogDecoratorTest.php
Even though viewing our logs are generally something that is admin access only, we should be better about sending sensitive information to the log. This PR removes one such sensitive secret and also adds some global protection against sending sensitive information.
Closes https://github.com/vanilla/support/issues/2191.
=> Obscure known sensitive fields in the LogDecorator 

library/Vanilla/EmbeddedContent/Factories/TwitchEmbedFactory.php, tests/Library/Vanilla/EmbeddedContent/Factories/TwitchEmbedFactoryTest.php
Twitch "clip" URL detection was broken for the clips.twitch.tv domain, due to an incorrect condition. It has been resolved here. Additionally, tests have been added for the ID-extraction routine.
=> Fix Twitch clip URL parsing

applications/vanilla/controllers/class.postcontroller.php
Closes https://github.com/vanilla/support/issues/2164
**Steps to test:**
1. Make sure you have embedded comments setup on your local (or Wordpress)
2. If a discussion is already created with the embedded comments local, delete it. (this test requires the discussion to be created).
3. Change your local language to spanish.
4. Make a comment in the embedded comments.
5. Go to your local and open the discussion it created, notice the link to the post says "Read the full story here"
6. Delete the discussion.
7. Checkout this branch and repeat from step **4.**. Observe now that the link matches the language set.
=> Fix embedded discussions link translation 

applications/dashboard/controllers/api/UsersApiController.php, applications/dashboard/openapi/users.yml, applications/vanilla/library/Menu/UserCounterProvider.php, library/src/scripts/@types/api/users.ts, library/src/scripts/headers/mebox/pieces/MessagesCount.tsx, library/src/scripts/headers/titeBar.story.tsx, library/src/scripts/headers/titleBarRegisterUser.story.tsx, library/src/scripts/headers/titleBarStyles.story.tsx, tests/APIv2/UsersTest.php
Adds the users unread conversations count to the /me endpoint.  Applies it in the front for the message count.
closes https://github.com/vanilla/support/issues/2168
=> Add unread conversations to GET /me

library/Vanilla/SchemaFactory.php, tests/Library/Vanilla/SchemaFactoryTest.php
Static caching of the container and event manager can make testing difficult for any components that make use of `SchemaFactory`. The initial usage creates the instances, which are then stored. Future usage will reference a potentially out-of-date container or event manager.
The caching here is probably unnecessary, so it's being dropped. Tests won't have to worry about `SchemaFactory`'s container doppelgänger anymore.
=> Remove caching of dependencies in SchemaFactory

library/src/scripts/headers/mebox/pieces/MeBoxDropDownItem.tsx
This fixes https://github.com/vanilla/support/issues/2166.  Not all the user information is sent back from `/conversations`, so trying access the authors prop info would throw an error.
closes https://github.com/vanilla/support/issues/2166
closes https://github.com/vanilla/support/issues/1758
=> Verify if user information is defined.

applications/dashboard/controllers/class.entrycontroller.php, tests/Bootstrap.php, tests/Controllers/EntryControllerTest.php
This makes a few tweaks to the target cleaning functionality of the `EntryController`.
- Add /entry/autosignedout to the list of URLs that won’t redirect. This is mainly a UX fix.
- Make unsafe domains redirect to ‘/‘ instead of the default route. This should dispatch to the default route.
- Make URLs process on the same domain rather than just checking targets without a domain. This ostensibly fixes a regression, but could also cause a regression where code depends on the behavior. I think this is an acceptable risk.
Closes https://github.com/vanilla/support/issues/2231
=> Tweak the EntryController target cleaning

library/core/class.theme.php
Closes vanilla/vanilla-patches#682.
Currently, the banner title string is being encoded in the `Gdn_Theme::logo()` method, but not the `Gdn_Theme::mobileLogo()` method, which returns even when the site loaded on a desktop. Because we want to prevent html from being output from that field, this encodes the `$title` variable before returning it.
1. Go to `https://dev.vanilla.localhost/dashboard/settings/branding`
1. Enter `aaaa"><script>alert(1337)</script>` in the "Banner Title" field.
1. Navigate to the homepage and verify that an alert is triggered.
1. Checkout this branch and reload the page.
1. Verify that the alert is not triggered.
=> Encode banner title strings before outputting them

library/Vanilla/Theme/Asset/JsonThemeAsset.php, tests/Library/Vanilla/Theme/JsonThemeAssetTest.php
Backport: https://github.com/vanilla/vanilla-cloud/pull/222
=> [backport] Fix JSON output of empty arrays in /api/v2/themes/:id/assets/:assetID

applications/vanilla/views/categories/helper_functions.php
The `FormatService::renderPlainText()` method requires a string and will crash the page if null is passed to it. This change does some casting and default checking.
Note that we encountered the null when it came to the line with `$lastCategory` being null.
=> Make sure we call renderPlainText() with a string

library/core/class.proxyrequest.php
This is a temporary fix until our code completely supports the HTTP/2 protocol. Before updating the our base data server image to focal, the protocol used was HTTP/1.1.
> According to curl's documentation, the curl tool enables HTTP/2 by default for HTTPS connections since 7.47.0.
> 
> Headers are lower cased on HTTP/2, while they aren't on HTTP/1.1. This is causing problems, especially in cases like this one, where we are using the response "Content-Type" header to determine how we handle the response.
> 
> The temporary solution we found is to ensure the CURLOPT_HTTP_VERSION is specified and set to CURL_HTTP_VERSION_1_1 when making curl calls on infrastructure.
More information on the above here: https://github.com/vanillaops/roadmap/issues/331
=> Specify HTTP protocol version to use in ProxyRequest class.
